### ISSUE TITLE
If I update a filter value on a saved chart, it doesn't update in the export

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10008]
### Description

If I create a saved chart with a filter, it doesn't update the filter int eh export if I change teh filter. This means I'm exporting data with values that don't match my filtered values. 

### Steps to Reproduce the Bug or Issue

1. Open a saved chart: https://analytics.lightdash.cloud/share/XB05qBja7g3_YNCvjWSOc
2. Click `export` from teh chart panel and export the results to a .csv 
3. See that the values in the export match the values in the filters/chart
4. Click `edit chart`
5. Update the filter value to something else (e.g. change the filter value to `comment_created` from the example above)
6. save the chart
7. click `export` from the chart panel and export the results to a .csv
8. See that the values in the export _**do not**_ match the values in the filters/chart. Instead, they match the previous filter values. 

### Cloud or self-hosting

cloud

**Comment by almeidabbm** [comment]
**Steps to reproduce:**

1. Create chart with filter e.g. `event = song_played` & save
2. Edit chart, add another filter
3. Change root filter group to `Any`
4. Remove new filter
5. Save changes
6. Export CSV -> results will be correct, e.g. filtered to `song_played`
7. Edit chart
8. Change filter value
9. Save
10. Export CSV -> results will be incorrect, still filtered to previous filter value


https://github.com/lightdash/lightdash/assets/22939015/c1f86b2f-445c-4f0d-b8c5-cecd581beb66
