### ISSUE TITLE
Publish api documentation

### ISSUE THREAD

**Issue by chrisbol-lf** [lightdash/lightdash#1002]
### Description: What is it?

Would be great to have the possibility to connect the Lightdash via API so I can build a dashboard and visualize the charts via the Lightdash API. So it would be great if you can open up the documentation on API if available.
### Problem: What problem does this solve?

For me it would solve the problem to generate a generic dashboard for all of my clients via API. This functionality is currently not possible in f.e. Google Data Studio.

**Comment by owlas** [comment]
Thanks @chrisbol-lf !

A good chunk of the api is described by an `openapi.json` file - we just need to expose this documentation on the documentation site and possibly in the app too for developers.

**Comment by ZeRego** [comment]
Relevant docs: 
[Designing and managing APIs: Best practices & common pitfalls | Google Cloud Blog](https://cloud.google.com/blog/products/api-management/api-design-best-practices-common-pitfalls)

[API design: Which version of versioning is right for you? | Google Cloud Blog](https://cloud.google.com/blog/products/api-management/api-design-which-version-of-versioning-is-right-for-you)

**Comment by owlas** [comment]
@chrisbol-lf this is now available at: https://docs.lightdash.com/api/v1

It's changing quite fast and is currently in beta! Drop us a message in the community if you want to keep up with when a stable v1 will be available
