### ISSUE TITLE
Ability to reset password

### ISSUE THREAD

**Issue by chrisbol-lf** [lightdash/lightdash#1003]
### Description: What is it?

There is currently no ability to reset your password

### Problem: What problem does this solve?
For the rare occasion that a user loses his/her password

**Comment by owlas** [comment]
@ZeRego I propose we split this into two issues:

- [ ] Expose an admin command that can be run on the server to reset passwords (quick)
- [ ] Implement email flow for triggering reset (larger piece of work)

**Comment by owlas** [comment]
@all-contributors add @chrisbol-lf for ideas
