### ISSUE TITLE
The week being shown in results table doesn't match with the week shown on the chart 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#10030]
### Description

![image](https://github.com/lightdash/lightdash/assets/14341285/1663f619-ea28-426c-9734-e0cd27468941)

Charts and results tables are off by one day. 

Reported here: 
https://lightdash-community.slack.com/archives/C03MG2VTR08/p1715294687927269

### Steps to Reproduce the Bug or Issue

Reported here: 
https://lightdash-community.slack.com/archives/C03MG2VTR08/p1715294687927269
https://lightdash.slack.com/archives/C06PAQCH932/p1715290354141549

### Cloud or self-hosting

cloud

**Comment by TuringLovesDeathMetal** [comment]
@magnew I wonder if this is related to `start of week` set to Monday vs. Sunday?
