### ISSUE TITLE
add support for dbt projects on bitbucket

### ISSUE THREAD

**Issue by xjaner** [lightdash/lightdash#1004]
### Description: What is it?
Add support for dbt projects hosted on Bitbucket.

### Problem: What problem does this solve?
I can't complete the Lightdash setup because my dbt project is on Bitbucket, and currently only Github and Gitlab are supported.

### Success: How will we know if we’ve solved this problem?
A new option for Bitbucket should appear in the dropdown list of dbt connection types. Then the connection should work as expected. :)

**Comment by owlas** [comment]
@all-contributors add @xjaner for ideas
