### ISSUE TITLE
`view underlying data` in metrics with filters applied are not correctly applying the filters

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10040]
### Description

If you create a metric with a filter, then click `view underlying data` on that metric, you'll see that the metric filter isn't being applied to the underlying data shown. 

### Steps to Reproduce the Bug or Issue

https://www.loom.com/share/cffc08ff2ae64133ab8c78ee6426a259

### Cloud or self-hosting

None

**Comment by TuringLovesDeathMetal** [comment]
just kidding - not resolved

**Comment by magnew** [comment]
Adding a loom I made showing this working in main. 

https://www.loom.com/share/4f6dacbce659493f8e479d23f8595c36?sid=29c1e36f-97e2-4e0b-985f-ecbb021af3e4

Looking into the analytics cases.
