### ISSUE TITLE
Unexpected crash during git clone

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1006]
### Describe the bug

When cloning an git repo, Lightdash can crash.

### To Reproduce

Still investigating

#### Logs showing moment of crash
<img width="1272" alt="Screenshot 2021-12-16 at 09 57 45" src="https://user-images.githubusercontent.com/11660098/146350017-27670332-6d47-4115-ba1d-d9a0e68d0e34.png">

#### Memory usage
Seems not to spike (MAX over 1 minute aggregation)
<img width="1027" alt="Screenshot 2021-12-16 at 09 59 14" src="https://user-images.githubusercontent.com/11660098/146350149-0b15ea12-06a8-4eee-b21c-4631e5b732bc.png">

#### Kuberenetes pod logs
<img width="1097" alt="Screenshot 2021-12-16 at 10 07 17" src="https://user-images.githubusercontent.com/11660098/146351577-d6049df1-07ae-46e0-9542-0202a55b0b3b.png">

**Comment by owlas** [comment]
@ZeRego you can find more context on this here: https://lightdash.slack.com/archives/C02PEMS515E/p1639664684003100

**Comment by ZeRego** [comment]
I expect the work on #1038 to resolve this issue. Closing this until we see the error again and replication steps.
