### ISSUE TITLE
show available postgres ssl options

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1007]
### Description: What is it?

When connecting to postgres/redshift there's an option to choose the ssl policy. There are fixed values for this but we expose it as a free text field.

### Problem: What problem does this solve?

When connecting typos are possible e.g. `disabled` vs `disable` which will cause an error

### (Optional) Why: How do we know this is a real problem and worth solving?

It's preventing people from getting started with Lightdash

**Comment by ZeRego** [comment]
Options: 
- disable
- allow
- prefer
- require
- verify-ca
- verify-full

Ref: https://www.postgresql.org/docs/9.1/libpq-ssl.html

**Comment by ZeRego** [comment]
This has been done in https://github.com/lightdash/lightdash/pull/1057
