### ISSUE TITLE
Selfhost lightdash cannot render login and register form

### ISSUE THREAD

**Issue by Pavlmits** [lightdash/lightdash#10135]
### Description

I self hosted lightdash on kubernetes and everything was working nicely and suddenly the /register and /login urls stopped rendering the form fields.

<img width="539" alt="image" src="https://github.com/lightdash/lightdash/assets/36935403/8d26b4df-02b6-447f-9636-afeba3e4cc0a">
<img width="674" alt="image" src="https://github.com/lightdash/lightdash/assets/36935403/4d1ef071-06cf-4bba-a28b-dd6a97ec3834">

And here are some logs from the server:
<img width="867" alt="image" src="https://github.com/lightdash/lightdash/assets/36935403/17354369-dbd4-44fd-a061-e1975e8dcb6c">

Also I don't see any problem on the responses that I am receiving and no console errors.
<img width="1723" alt="image" src="https://github.com/lightdash/lightdash/assets/36935403/419c7e67-c014-4a8a-9178-60a8f23c2bb8">

I tried also both chrome and safari and I get the same response.

I tried to delete all the kubernetes resources together with the db and redeploy but still nothing.

Any idea what it is going on?

### Steps to Reproduce the Bug or Issue

1. Deployed all the k8s resources
2. mydomain.net/login

### Cloud or self-hosting

self-hosting

**Comment by ZeRego** [comment]
Hi @Pavlmits 👋 

What is your Lightdash version?
Do you have any SSO authentication methods configured? gmail/azure/okta/etc 
Do you have password authentication enabled/disabled? 

To find this information you can open the following URL in your browser `https://mydomain.net/api/v1/health` (replace with your real domain).

**Comment by Pavlmits** [comment]
ops I found out that I had set up on the configmap  AUTH_DISABLE_PASSWORD_AUTHENTICATION: "true" 🙈. Thank you very much @ZeRego for the help :)
