### ISSUE TITLE
Month name ordering and day of week ordering works in Snowflake, but not in BigQuery

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10146]
### Description

Right now, if you try to add a `month name` or `day of week name` to a query in BigQuery, then try to order that query based on those fields, it will throw an error saying "those fields aren't aggregated in the order by clause". 

**Note:** The day of week name will only throw an error if you're using a field that's actually a timestamp. It will work fine if the underlying data of the field is a _**date**_ field.

Here's a query in Snowflake: https://analytics.lightdash.cloud/share/UdEcCusYa7kMrN9w4tQsq

Then the same query in BigQuery: https://analytics.lightdash.cloud/share/yOX7xWfhb0JD9xzAowHMZ

### Steps to Reproduce the Bug or Issue

1. Create a `month name` or `day of week name` field. 
2. Add it to your query
3. Order by this `month name` or `day of week name` field. 
4. See that this works in Snowflake, but throws an error in BigQuery 

### Cloud or self-hosting

cloud

**Comment by rephus** [comment]
I can replicate 

![image](https://github.com/lightdash/lightdash/assets/1983672/e76fb1a7-85a5-4b4f-b140-831cc139aff1)
