### ISSUE TITLE
Downgrade permissions on space groups

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#10165]
Another weird UI behaviour, probably caused by the recent change in permissions. 
I can upgrade permissions for individual users in the group, but I can't downgrade. 

eg: if The group can `edit` I can't set an individual user to `viewer`

[Screencast from 23-05-24 09:50:54.webm](https://github.com/lightdash/lightdash/assets/1983672/60979ae1-0e2a-406c-9682-4412c8ead633)

_Originally posted by @rephus in https://github.com/lightdash/lightdash/issues/10082#issuecomment-2126460722_

**Comment by IrakliJani** [comment]
context: https://www.notion.so/lightdash/Group-Permissions-Issues-da5d83b4a0384409b0e2847904a9e0fb
