### ISSUE TITLE
Hide the action menu from custom visualizations

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10199]
### Description

We show an action menu on Vega visualizations. 

We should remove this. 

![image](https://github.com/lightdash/lightdash/assets/31848148/b9171ff5-3645-49d4-a04f-1fed337ded61)

It should be just done in the "renderer"

I believe it's just this bit: https://github.com/vega/altair/issues/1705

**Comment by magnew** [comment]
@hamzahc1 I did this cause I saw it and it was really easy, so I'm putting it back on the board.
