### ISSUE TITLE
Set a display label for metrics with dbt metrics

### ISSUE THREAD

**Issue by rlebrao** [lightdash/lightdash#1021]
### Description: What is it?
Addition of an `label` field in metrics section on schema yml file.

### Problem: What problem does this solve?
Currently there's no way to edit a metric display name without changing it's reference name. 

### Success: How will we know if we’ve solved this problem?
in Lightdash interface we should see the value of `label` attribute as the metric's name

### Audience: Who are we building this for?
Mostly data consumers
 

### What: Roughly, what does this look like in the product?
Adding this `label` attribute would facilitate the visualization of a metric name without changing it's `name` attribute. This way we can customize a better and friendly display name than the more technical one set in it's reference.

**Comment by owlas** [comment]
Thanks @rlebrao !

We really need to capture this. We just need to adjust our own metrics definitions to handle this.

Together with #857, @ZeRego we should introduce friendly display names to most objects.

**Comment by owlas** [comment]
@all-contributors add @rlebrao for ideas, bugs
