### ISSUE TITLE
Enforce a limit in the SQL runner

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#10238]
### Description

The SQL runner currently injects `LIMIT 25` at the end of queries, but it's easy to accidentally remove, and if you write a query from scratch there is no limit applied. We should add a limit similar to the one in the table explore that defaults to 500. 

<img width="412" alt="Screenshot 2024-05-29 at 12 43 54 PM" src="https://github.com/lightdash/lightdash/assets/5532776/cd4d8b1c-48db-41da-9ad3-ae878820c696">

### What problem does this solve?

If we enforce a limit, then the page will not crash if too much data is returned in the query results.

**Comment by ZeRego** [comment]
@jpetey75 We don't parse the SQL so we can't inject the limit. Parsing the SQL and supporting all warehouses syntax would be an enormous effort.

Some other options:
- add basic validation to search for the word `limit` in the input
- wrap the user SQL in a CTE and apply the limit in the second query
