### ISSUE TITLE
On the 'setup' pages, users should see instructions in the app rather than be redirected to docs. 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1023]
### Description: What is it?
The help tooltips on the setup pages (connect dbt and warehouse) are the same for every field! They redirect the user to 'Read documentation'. The user should be able to read the instructions on the setup page. 

### Problem: What problem does this solve?
Users may spend too long carrying out this process. It is quite tedious having to  open up a new tab for every field - it is a poor first time experience. 

###  Why: How do we know this is a real problem and worth solving?
Not many people make it past this stage in their first go. Feedback.

### Success: How will we know if we’ve solved this problem?
Users are able to connect to their dbt projects and warehouses much faster. 

### Audience: Who are we building this for?
The data builders who are setting up Lightdash for the first time

### What: Roughly, what does this look like in the product?
The user clicks on the help icon for a particular field and the relevant helper.text appears on the same page.

**Comment by PriPatel** [comment]
**The help icons should achieve an effect similar to the ones in this prototype:**
https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=682%3A31610&scaling=min-zoom&page-id=671%3A31489&starting-point-node-id=682%3A31610

The exact 'help text' for each field:
https://lightdash.notion.site/lightdash/Update-information-icons-8368cc99fb144c7d944878cb3f73d197

**Comment by PriPatel** [comment]
super relevant!

**Comment by PriPatel** [comment]
still very relevant!!

**Comment by rephus** [comment]
@PriPatel on the notion doc we're missing info for this "new?" field: 

```
                <BooleanSwitch
                    name="warehouse.ra3Node"
                    label="Use RA3 node"
                    documentationUrl="https://docs.lightdash.com/get-started/setup-lightdash/connect-project#ra3-node"
                    defaultValue
                    disabled={disabled}
                />
                ```

**Comment by rephus** [comment]
Gitlab / github are also missing `Host domain (for self-hosted instances` and `target name` 

Bitbucket, azure, local dbt are not included in this notion document... 

Unless you tell me otherwise I'll keep those as they are.

**Comment by PriPatel** [comment]
ahh @TuringLovesDeathMetal - can you confirm that its ok that the above are missing?

**Comment by TuringLovesDeathMetal** [comment]
ah, sorry, I didn't 100% look through it (more skimmed)

I'll find the docs for these other things and add them to teh Notion doc.

**Comment by TuringLovesDeathMetal** [comment]
@rephus updated the doc here: https://www.notion.so/lightdash/67d3fd912f764d9eaf0f8e741d76fa00?v=805962b15e6a49958b88d1ec7dce15c4&p=76fe38575fcd4d3989da52abe8bbbf66&pm=s

I don't think there are any entries for the dbt project connection of a local project though 🤔
