### ISSUE TITLE
Scrolling improvements

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#10243]
- [ ] There shouldn't be an inner scroll bar in the panel. I should be scrolling the page only.

**Comment by joaoviana** [comment]
[fix: enable overflowY scroll if sidebar open #10286](https://github.com/lightdash/lightdash/pull/10286) fixes the first point on the ticket. the second one is _harder_ @PriPatel

**Comment by PriPatel** [comment]
@joaoviana cool - the second one isnt essential. I have removed it. !
