### ISSUE TITLE
Capture users' job titles

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1024]
### Description: What is it?
Ask new users for their job title during the sign up process.

### Problem: What problem does this solve?
I want to understand who our users are and what the split between data builders and data consumers is. This is so that we can start to think about our ‘meaningful building blocks’ value.

### Success: How will we know if we’ve solved this problem?
We will be able to segment users 

### Audience: Who are we building this for?
Ultimately, all users. Initially, for us to understand our users better. 
 

### What: Roughly, what does this look like in the product?
An extra field during the sign up process. 

<img width="300" alt="Screenshot 2021-12-17 at 00 48 46" src="https://user-images.githubusercontent.com/12776522/146470480-74df1857-4067-4e3d-99a2-a89938b7c517.png">

**Comment by ZeRego** [comment]
Note: we also need this field when we invite a user
