### ISSUE TITLE
Start of week doesn't work (Bigquery)

### ISSUE THREAD

**Issue by pranasas-karutis** [lightdash/lightdash#10268]
### Description

Selecting "Start of week" in connection settings has no impact. Tested various days, but it always shows the default (Sunday) as the week start day in any results/charts.

### Steps to Reproduce the Bug or Issue

<img width="443" alt="image" src="https://github.com/lightdash/lightdash/assets/7551207/03970efa-c45a-48b7-8106-bcb2ddeaf891">
<img width="867" alt="image" src="https://github.com/lightdash/lightdash/assets/7551207/478dfb8d-1b8e-4fee-81c9-0459a3414c51">

### version

v0.1114.0

### Cloud or self-hosting

self-hosting

**Comment by pranasas-karutis** [comment]
As a (temporary) hack/workaround I've found the following (add to .yaml file of the table): 

      - name: created_at
        meta:
          dimension:
            type: timestamp
          additional_dimensions:
            week_monday:
              type: date
              label: 'Week (Monday)'
              sql: 'timestamp_trunc(${TABLE}.created_at, WEEK(Monday))'
              time_intervals: off
              groups: [ 'Created at' ]

This nicely merges the new dimension into the timegroup.

**Comment by pranasas-karutis** [comment]
(Accidentally closed this down; it should not be set as DONE yet, as it only has a temporary workaround)

**Comment by ZeRego** [comment]
Hi @pranasas-karutis 👋 

Do you deploy your project via the CLI?

Users that deploy their Lightdash project via the CLI ( including GitHub actions ) should add the following command option `--start-of-week=0`

```
--start-of-week
Specifies the first day of the week (used by week-related date functions). 0 (Monday) to 6 (Sunday)
```
