### ISSUE TITLE
Some table icons are missing 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#10272]
<img width="47" alt="Screenshot 2024-05-31 at 10 28 06" src="https://github.com/lightdash/lightdash/assets/12776522/a0fad8d0-d1b6-4f39-8450-47fd445afc2b">

I can't tell what the difference is between those that have them and those that don't!

**Comment by joaoviana** [comment]
Duplicate: https://github.com/lightdash/lightdash/issues/10271
