### ISSUE TITLE
Disable scheduled deliveries with non-retryable errors

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#10297]
If a scheduled delivery fails with a non-retryable error, it should be disabled. Example errors to disable:

- Google credentials have expired

**Comment by rephus** [comment]
Errors from workers to disable: https://lightdash.sentry.io/issues/?project=5959292&query=is%3Aunresolved+Worker&referrer=issue-list&statsPeriod=24h 

- uploadGsheets:  Worker worker-f18d1f5ab12d46f2ad failed job 453905 (uploadGsheets). Error: Error: invalid_grant  https://lightdash.sentry.io/issues/4150573551/?project=5959292&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0
- handleScheduledDelivery: Worker worker-bb3f4229725d34adf9 failed job 1922 (handleScheduledDelivery). Error: Could not find slack installation  https://lightdash.sentry.io/issues/4202827650/?project=5959292&query=is%3Aunresolved+Worker&referrer=issue-stream&statsPeriod=24h&stream_index=2
