### ISSUE TITLE
Dimensions are missing for dbt models in bigquery

### ISSUE THREAD

**Issue by philcarr-tsl** [lightdash/lightdash#1030]
### Describe the bug

Lightdash fails to read the meta data of GBQ projects that are not hosted in the US. 

All our tables are in eu west 2 for compliance reasons. From looking at the project query logs for the service account key that I set up for testing Lightdash I found that despite the dbt project and the project setting in Lightdash to eu west 2 then queries to fetch meta data were in location:US, therefore not erroring but equally not producing the expected result.

### To Reproduce
1. Create a dataset in not the US in GBQ (europe-west2).
2. Create a dbt project and files appropriate to the dataset and tables from step 1.
3. Set up Lightdash to use what has been created in step 1 and 2 
4. Once it has finished doing all the scanning of the data warehouse connection and the dbt files then for the "tables" part of "explore" you will see:
![Screenshot 2021-12-17 at 14 36 56](https://user-images.githubusercontent.com/90601643/146560517-74c0a346-2cac-4ff5-a409-db6088499555.png)

To get round the issue you need to add the datatypes for ALL the columns in the dbt model .yml (schema) file any column omitted from the file is not selectable, any column in the file but without the defined type causes step 4 error to occur.

### Expected behavior

Point Lightdash at GBQ and dbt files with its project setting and it reads the all the meta it needs from the different places to be able to work (access tables in Lightdash)

### Screenshots or Loom video
When I changed the location of the query:
![Screenshot 2021-12-17 at 13 43 06](https://user-images.githubusercontent.com/90601643/146561182-9c2689de-2577-41b4-b4e9-8eb89e4cd72d.png)

When I got the query with the settings it had at execution time, as you can see the query executes, so no err:
![Screenshot 2021-12-17 at 14 43 19](https://user-images.githubusercontent.com/90601643/146561472-ee8d0bb0-143b-4849-a329-500c73bb6c5c.png)

Lightdash setting for location:
![Screenshot 2021-12-17 at 14 44 11](https://user-images.githubusercontent.com/90601643/146561555-868e4bd1-6541-4b7b-951d-350a6a1d7613.png)

**Comment by owlas** [comment]
Thanks @philcarr-tsl, this is an extremely detailed bug report.

My feeling is that when we query BigQuery for the column types, we're ignoring the `Location` parameter that we asked for when collecting credentials.

I'm taking a look!

**Comment by owlas** [comment]
@all-contributors add @philcarr-tsl for bugs, data

**Comment by owlas** [comment]
We're moving away from automatically inferring dimension types and instead have them attached to dimensions on the `meta.dimension.type` tag, like you mentioned as a work around.

It used to be horrible to maintain these types but we've since shipped the lightdash CLI, where `lightdash generate` can be used to automatically detect types. 

Give it a go @philcarr-tsl - if the types are not appearing there it should be easier to debug and we can re-open this issue!
