### ISSUE TITLE
Generated SQL is wrong with filters in joined table

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1032]
### Describe the bug

Run a query on an explore with two joined tables. Select a metric and dimension from table A and a filter from table B. Table B is not included in the join condition, and so the filter for the column it table B is invalid.

### To Reproduce

See above

### Expected behavior

When filtering on table B, Lightdash should include table B in the join logic

### Screenshots or Loom video

**Config**
<img width="1504" alt="Screenshot 2021-12-17 at 14 55 25" src="https://user-images.githubusercontent.com/11660098/146563257-238d8471-40ec-4abc-80a3-cc97e530af74.png">

**Error**

<img width="707" alt="Screenshot 2021-12-17 at 14 55 19" src="https://user-images.githubusercontent.com/11660098/146563282-604e7392-9edf-47c3-86be-99167cd6f103.png">

**Generated sql**
```yaml
SELECT
  orders.status AS "orders_status",
  AVG(orders.amount) AS "orders_avg_amount"
FROM "demo_db_57w5"."jaffle"."orders" AS orders

WHERE (
  (customers.first_name) IN ('Oliver')
)
GROUP BY 1
ORDER BY "orders_avg_amount" DESC
LIMIT 500
```

**Comment by djayatillake** [comment]
oh no I think my previous change caused this... it only takes the tables from the metrics and dimensions plus the explore for joins. I didn't realise that if something was used for a filter that it wouldn't be a dimension.

**Comment by djayatillake** [comment]
let me have a go at fixing this now, I need to wait for https://github.com/lightdash/lightdash/pull/1036 to be merged before I can have a go at https://github.com/lightdash/lightdash/issues/999

**Comment by djayatillake** [comment]
I've brought this into my open PR https://github.com/lightdash/lightdash/pull/1036

Sorry my git isn't great, so I couldn't figure out how to fork the main repo again onto my username so that there could be a second separate PR.

**Comment by ZeRego** [comment]
> I've brought this into my open PR #1036
> 
> Sorry my git isn't great, so I couldn't figure out how to fork the main repo again onto my username so that there could be a second separate PR.

The ideal flow is to create a new branch per each fix. This way you can have the changes separate by branch and create a PR from each branch into our repo.

**Comment by djayatillake** [comment]
ah of course, that make's sense, I'll do that next time. So my personal main would just be the same as the lightdash one.

**Comment by ZeRego** [comment]
> So my personal main would just be the same as the lightdash one.
Correct 👍  Each time you want to contribute you make sure your 'main' branch is up to date with our main and then create a branch out of it.
