### ISSUE TITLE
Upgrade to react 19 and test new compiler

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#10346]
### Description

Investigate React 19 upgrade and test incremental adoption of new React compiler

Benefits are: 
- Reducing re-evaluations of variables
- Removal of memoization, which should be handled smartly by React 19's compiler

See this as a reference of adoption: https://react.dev/learn/react-compiler#using-the-compiler-effectively
We should start with the following approach for the `TreeProvider`:
```ts
const ReactCompilerConfig = {
  sources: (filename) => {
    return filename.indexOf('src/path/to/dir') !== -1;
  },
};
```

> [!NOTE]
> Use branch that already uses React 19: `experiment/react-compiler-beta`

Excerpt from community Slack for reference

```
Hi team,
I have encountered a performance issue that I am unable to resolve. I have defined many tables with numerous dimensions in my hosted Lightdash project. After adding more joined tables and new dimensions, toggling a dimension has become very time-consuming, causing significant performance issues. I reviewed some code related to the TableTree section but couldn’t identify the problem. However, when I toggle a field, it seems to render a log in TableTree and TableTreeSections multiple times.
I would appreciate any feedback and suggestions. :electric-mint-heart:

=======================================================================
This is a known issue from React and should be resolved with the upcoming [react compiler](https://react.dev/learn/react-compiler) (currently in beta).
At the moment we use the library use-context-selector in some of our other providers/context to reduce this problem.
We are open to contributions to apply the same fix to the TreeProvider. Let us know if you need help with this.
```

**Comment by joaoviana** [comment]
React 19 significantly improves performance when dealing with a large number of dims/metrics in the explorer sidebar. 
All we have to do is to enable it by default and even with existing code it will handle the `ExplorerProvider` changes really well. It will only apply the changes to the node being selected (currently, with react 18, when you click on a field, it will trigger an explorer provider change, which will cause the rerender of all the other nodes as well)

**Comment by joaoviana** [comment]
Unfortunately, react 19 isn't yet recommended to be used in production. So I'm closing this ticket until we get an official release and assess its impact.

**Comment by samliu2022** [comment]
Thanks.
