### ISSUE TITLE
Clicking on charts should filter other charts on a dashboard

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1041]
### Description: What is it?

When exploring multiple charts, it would be good to have some basic interactivity. For a start, when I click on a chart object (e.g. a bar) it should apply a filter to all charts to that data.

Context: https://lightdash.slack.com/archives/C02QP2UKYVC/p1639750521008100

**Comment by TuringLovesDeathMetal** [comment]
@owlas I think thsi was solved when we built cross-filtering, but just want to double check it's not different?
