### ISSUE TITLE
Option to disable/hide date zoom on dashboards

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#10437]
### Description

Give editors an option to hide or turn off date zoom.

### What problem does this solve?

When multiple date definitions are used in the same dashboard, it can be confusing or return unexpected results when using date zoom. Better to disable the feature in those scenarios.

**Comment by jpetey75** [comment]
internal slack customer request: https://lightdash.slack.com/archives/C069QQMERD2/p1723213661347799?thread_ts=1723212005.666809&cid=C069QQMERD2

>I have a large table that I’m shifting to date trunc month granularity instead of daily, so would like the option to turn of the date zoom at the day level

**Comment by hamzahc1** [comment]
Should be editors and above (so editors, developers and admins)
