### ISSUE TITLE
Update share in slack docs image on integrations page

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#10443]
Now slack is inside integrations submenu in settings, not in `slack` the screenshot in this page is misleading https://docs.lightdash.com/guides/sharing-in-slack#adding-slack-to-your-organization-lightdash-cloud

**Link to existing docs:** 

**Changes?**

**Comment by TuringLovesDeathMetal** [comment]
https://github.com/lightdash/lightdash/pull/10512 - closed by this PR
