### ISSUE TITLE
Project service doesn't destroy projects on update

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1045]
### Describe the bug

When we successfully update a project, we create a new project adapter object and we should destroy the previous one.

### To Reproduce

1. Go to project settings
2. Click on test & save
4. See the old project adapter directory in tmp/

### Expected behavior

It should destroy the project adaptor.
It should delete the directory from the old project adapter.

### Screenshots or Loom video

n/a

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego is this still a problem? Or has it been fixed with our updates to the project compilation/refresh?

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal it is still a problem. The temporary directory for the project isn't being destroyed. 
The code is missing a `this.projectAdapters[projectUuid].destroy();`
