### ISSUE TITLE
Dashboard charts do not resize along with the page until you refresh

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1047]
### Describe the bug

When a dashboard finishes loading on the screen and the user resizes the window the charts are not responsive. Scroll bars appear on the charts - a page refresh fixes this.

### To Reproduce

1. Go to a dashboard
2. Resize the window
3. The charts don't resize. Now refresh the page
4. Now the charts have resized.

### Expected behavior

The charts should have resized along with the window.

**Comment by ZeRego** [comment]
Seems related to https://github.com/lightdash/lightdash/issues/907
