### ISSUE TITLE
Add the ability to show / hide mark labels

### ISSUE THREAD

**Issue by andre347** [lightdash/lightdash#1048]
### Description: What is it?

Currently charts do not have any mark labels. Especially when users want to export their charts you need labels. In addition, not every user uses tooltips.

### Problem: What problem does this solve?

- Charts become more legible
- Easier and better exporting of charts

### Audience: Who are we building this for?

All users of the product

 

### What: Roughly, what does this look like in the product?

Dropdown / configure pane somewhere in the UI. You want to be abel to select:
- Add / remove mark label
- Rotate label 
- Format label (percentages, decimal points etc)
- Colour and other style elements (bold, italics etc)

**Comment by PriPatel** [comment]
Thanks @andre347 ! 
Just so I understand, is this similar to this issue #292 (but with additional customisation requirements?). Thanks!

**Comment by PriPatel** [comment]
Perfect, thanks for clarifying. We will discuss general improvements to the charts area in our next planning session and get back to you when there are any updates on this!

**Comment by TuringLovesDeathMetal** [comment]
I really like the way Metabase gives teh option to "show all labels" or "show as many labels as looks nice"

![image](https://user-images.githubusercontent.com/31848148/151352497-790682d0-fec1-40ab-ac99-55a7a0670de8.png)
