### ISSUE TITLE
Use colourblind-friendly palette 

### ISSUE THREAD

**Issue by andre347** [lightdash/lightdash#1049]
### Description: What is it?

Your default colours for charts is blue and green. These are not the best colours for people that are colour blind / weak. I would suggest to use blue / orange as default colours.

### Problem: What problem does this solve?

Colour blind / weak analysts will appreciate and use your product

### What: Roughly, what does this look like in the product?

A way to configure the styling of the charts:
- Change colour palette per charts or on a dashboard level
- Add  / remove borders (and their colours)
- Opacity / transparency of the marks

**Comment by PriPatel** [comment]
Thanks again for this @andre347 !  So it feels like there are two potential improvements here: 

1. Our UI should follow accessibility guidelines by default. This is definitely something that we will look at when we revisit our UI library and product branding. 

2. Users should be able to configure how their charts / dashboards look depending on their preferences and their own branding.
