### ISSUE TITLE
Unable to edit or remove table calculation withtout a formula

### ISSUE THREAD

**Issue by michrzan** [lightdash/lightdash#10505]
### Description

Adding a new _table calculation_ with an empty formula breaks chart irrecoverably.
See the reproduction steps I created using your [demo portal](https://demo.lightdash.com/) below.
The UI should either prevent creating a _table calculation_ without a formula or allow the user to edit it.

### Steps to Reproduce the Bug or Issue

1. Create a new query from tables. Add dimensions and measures.
![1](https://github.com/lightdash/lightdash/assets/8075164/0a336a72-3628-484d-b2b1-1262356702e6)

2. Create a new _table calculation_. Give it a name, but leave the formula empty.
![2](https://github.com/lightdash/lightdash/assets/8075164/c4dbcdcc-3ac0-40dd-9019-65d21848a792)

3. As expected this is throwing an error as the _table calculation_ without a formula cannot be calculated.
![3](https://github.com/lightdash/lightdash/assets/8075164/636f9677-f286-4ec3-b4b4-74469533ddfa)

4. However, one cannot edit or remove this formula. Clicking the remove button has no effect. The chart stays broken forever. The only way to recover is to restore a previous version from the version history.
![4](https://github.com/lightdash/lightdash/assets/8075164/b8717571-222a-4b71-b99b-811f433183ef)

### version

v0.1139.0

### Cloud or self-hosting

cloud

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey @michrzan - thanks for opening this issue and the great detail you put into it. We'll take a look at this and fix it!

**Comment by nimit9** [comment]
Can I take this up? @TuringLovesDeathMetal
