### ISSUE TITLE
Dates in results affected by browser timezone

### ISSUE THREAD

**Issue by rlebrao** [lightdash/lightdash#1050]
### Describe the bug

The values from date fields are being affected by the browser timezone

### To Reproduce
Change the browser's timezone for simulating Moscow or Brasilia timezone, then the display value from date fields are shown as -1 day

### Expected behavior
The display value should keep the same date as it is in the database

**Comment by TuringLovesDeathMetal** [comment]
ooh, not a fun bug. Thanks for opening this one! 

We'll take a look at this and see what fixes we can make 👀

**Comment by rephus** [comment]
@TuringLovesDeathMetal I can replicate locally. This is a blocker for me for properly fixing https://github.com/lightdash/lightdash/issues/1867 , We should probably prioritize this

![image](https://user-images.githubusercontent.com/1983672/169520467-9c54d03c-8808-487f-ad8d-47a428de499c.png)

![image](https://user-images.githubusercontent.com/1983672/169520481-04240a43-c1b9-4a62-bd23-db3d8c470bc0.png)
