### ISSUE TITLE
Stream SQL runner results

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#10515]
### Description

Goal: Build an endpoint that doesn't wait until the data is available from the warehouse. 

Acceptance criteria: 
- Main API endpoint should be fast to return (doesn't timeout or wait for results) 
- Memory should always be low in the backend ( do not load all results in memory) 

#### Worker approach
1 - Build an API endpoint to run the SQL query
2 - The backend creates a `job` that is going to be processed by a worker
3 - The worker is going to fetch the data and store it in cloud storage
4 - We have another API endpoint to stream the data from cloud storage

#### Websockets 
1 - Create a websocket to run the SQL query in the backend
2 - The backend will fetch the data  `by batches`  (make sure we don't use too much memory) 
3 - Each chunk will be returned via websocket

Make sure the websocket is stable and doesn't lose any data on `server restart` or `client restart` (at least it should be similar to our current worker implementation) 

### Open questions: 
- do we need to `formatRows` ? if so, when ?

**Comment by Darshan813** [comment]
Hi,

I'm interested in the issue and would like to work on it

**Comment by owlas** [comment]
Hey @Darshan813 the team have this as key focus and should have it fixed within the next few days!

**Comment by Darshan813** [comment]
Alright, no worries. Thank you for getting back.

**Comment by ZeRego** [comment]
# Implementation details

## Worker + pulling

1 - FE requests new results. eg: `[put] /sql-query-job`

2 - BE creates a job and returns job id (trigger warehouse job here and save warehouse query id, is it possible for all wharehouses? )

2.1 - The worker is going to fetch the data based on query id

2.2 - For each chunk: it formats, saves it in storage, updates job state

3 - FE fetches job state every X seconds `[get] /sql/query-job/{job id}`

4 - BE returns latest job state

```jsx
// initial state
{ error: null, isComplete: false, rowsSize: 0, lastUpdate: [date]}

// in progress state
{  error: null, isComplete: false, rowsSize: 100, lastUpdate: [date]}

// complete state
{  error: null, isComplete: true, rowsSize: 146, lastUpdate: [date]}

// error state
{ error: 'SQL has an error', isComplete: false, rowsSize: 0, lastUpdate: [date]}
```

- if job state `lastUpdate` is older than X minutes → update state as failed

5 - when job is complete, FE request the necessary around of results.

- For cartesian charts, we want to load all rows. Might require multiple requests.
- For table chart, we can load just the first page and load more on scroll/page change

```jsx
// get by page
[get] /sql/query-job/{job id}/results?page=1&limit=500
```

6 - BE returns rows from storage

### To investigate

- how many workers do we need?
    - ( find how many queries are ran in production on average/median per minute? )
    - create different queue + high priority
- will it work without using S3?
    - we can store in temp files. how can we clear these temp files after some time?
- do we need to load the entire S3 file in memory to then get the page 2 rows?
