### ISSUE TITLE
Table interactions update

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#10530]
<img width="822" alt="Screenshot 2024-06-26 at 09 59 55" src="https://github.com/lightdash/lightdash/assets/12776522/74956266-e1c6-43b7-afa7-2b094629367b">

- [ ] When I click on the row (whether its a table or a field), I should open the new relevant explore (right now it opens the metadata sidebar)
- [ ] The explore should open in the same page (not a new tab, like it currently does). 
- [ ] Replace the 'Use Table' CTA with 'More Info'. This CTA should open the sidebar

**Comment by joaoviana** [comment]
UX testing done, closing
