### ISSUE TITLE
Investigate pagination on s3 cloud storage

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#10544]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/selecting-content-from-objects.html

https://aws.amazon.com/blogs/developer/introducing-support-for-amazon-s3-select-in-the-aws-sdk-for-javascript/

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#selectObjectContent-property

**Comment by rephus** [comment]
Pagination via s3 select seems not possible, as it is not compatible with GCP https://lightdash.slack.com/archives/C0797GG4TPH/p1719493593472119
we can still returns the full s3 file to the frontend, and skip frontend pagination for now https://lightdash.slack.com/archives/C0797GG4TPH/p1719493670153469

**Comment by ZeRego** [comment]
> we can still returns the full s3 file to the frontend, and skip frontend pagination for now

sounds like a good plan for now 👍
