### ISSUE TITLE
I want to be able to turn off date zoom on a dashboard

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#10565]
### Description

We have a customer request for disabling date zoom on a dashboard. This should probably 
just be an option available during dashboard editing.

**Comment by jpetey75** [comment]
@magnew I have a duplicate issue here that has one customer conversation attached to it: https://github.com/lightdash/lightdash/issues/10437

**Comment by magnew** [comment]
> @magnew I have a duplicate issue here that has one customer conversation attached to it: #10437

Ah, nice, I will close this one and relink the customer requesting this.

**Comment by magnew** [comment]
Closing as a duplicate of #10437
