### ISSUE TITLE
I want to be able to freeze filters at the top of the page

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#10562]
### Description

I want to be able to toggle on/off frozen filters at the top of the page when viewing a dashboard. This would keep the filters visible at the top of the dashboard while scrolling. Ideally a default for this toggle setting could also be saved from the edit view.

### What problem does this solve?

When working with a dashboard with multiple charts, it can be frustrating having to scroll back and forth and navigate to the top of the page every time you want to change a filter. This would make it possible for users to change filters more quickly.

**Comment by PriPatel** [comment]
Spoken with @mhawkins-runa and the solution in this ticket: https://github.com/lightdash/lightdash/issues/6314 covers the problem!
