### ISSUE TITLE
All 'Select Table' CTA clicks should open a new tab 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#10606]
<img width="146" alt="Screenshot 2024-07-04 at 13 59 22" src="https://github.com/lightdash/lightdash/assets/12776522/6864040a-ae78-4333-9833-7aed25bb773c">

- [ ] The Select Table/ Select Field CTAs in the sidebar should open in a new tab

**Comment by cooldude6000** [comment]
@PriPatel Can you assign this to me?

**Comment by cooldude6000** [comment]
To whomever it may concern,
Just letting know -- I am working on this issue!

**Comment by cooldude6000** [comment]
I'm leaving this issue since it's part of the milestone & belongs to the internal team! 👋
