### ISSUE TITLE
You should be able to copy the SQL snippet when the SQL panel is closed

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#10602]
> I regularly find myself wishing for the Copy SQL Code button to be available on the SQL banner when it's collapsed.
> I regularly copy the code and paste it in BigQuery to check how much the query costs, and I have to first expand the SQL section, then click on copy, and then collapse it again. So having it on the banner would save a few seconds every time

For users that don't want to actually examine the SQL in Lightdash, but rather copy it over into another tool , having to open the panel , click the copy button, then close the panel feels inefficient. 

**Possible solution**
- [ ] Show a 'copy' button when you hover over the closed SQL panel

**Comment by cooldude6000** [comment]
hey,
To whoever it may concern,
I'm working on this issue.
I will SURELY comment back here if I'm unable to make it with this issue.
Thanks.
