### ISSUE TITLE
table/chart config panel

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#10638]
Goals:
- allow user to change between table and bar chart
- allow user to configure table/bar chart

**Comment by joaoviana** [comment]
I'm looking at how this would work with RTK/Redux and the current Table component config+viz.
I'm using this PR as a base: https://github.com/lightdash/lightdash/pull/10648

At the moment I'm caring about: 
- Consuming the config
- Dispatching an action
- Consuming the altered config

cc @owlas

**Comment by owlas** [comment]
Finished, moving to https://github.com/lightdash/lightdash/issues/10769
