### ISSUE TITLE
Apply same logic as dbt to find profile.yml

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#10649]
### Description

> dbt then checks your [profiles.yml file](https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml) for a profile with the same name. A profile contains all the details required to connect to your data warehouse.
> dbt will search the current working directory for the profiles.yml file and will default to the ~/.dbt/ directory if not found.

[dbt docs](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles)

Bonus points: fix current error message to not show "[object Object]"

### Steps to Reproduce the Bug or Issue

Slack thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1720028998207529

> Couldn't find target "[object Object]" for profile PROJECTNAME in profiles.yml at /root/.dbt/profiles.yml
Seems like lightdash is looking for the profiles.yml at the wrong place (.dbt instead of the current working directory)

### Cloud or self-hosting

None

**Comment by ZeRego** [comment]
Updated ticket from bug to feature requests as it is a change in behavior we had for a long time.

**Comment by calculuslmvt** [comment]
Please assign.
