### ISSUE TITLE
Share SQL Runner url

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#10668]
When user clicks the "share url" button we save the current state in the database and return a state uuid to be used as a URL param. 

Unsaved SQL chart: `https:// ... /sql-runner-new?state={uuid}`
Saved SQL chart: `https:// ... /sql-runner-new/{uuid}?state={uuid}`

When the page loads it checks the URL param `state` and fetches/loads the state based on the uuid.

We don't want to add the entire state to the URL as this as caused issues before with url length limits.

**Comment by rephus** [comment]
What is this `state` ? is this a new table with the sql config ? or just the `sharedUrl` we use on `explore charts`
