### ISSUE TITLE
Env-Variable in profiles.yml not recognized

### ISSUE THREAD

**Issue by timhiebenthal** [lightdash/lightdash#10674]
### Description

Our default-target in the dbt profiles.yml is set by an environmental variable.

Somehow this is not recognised by the Lightdash CLI but I manually need to set `dev`
![image](https://github.com/lightdash/lightdash/assets/57394222/214cb14a-6d90-4edb-997a-b840d08e6323)

Error message:
```
lightdash preview --profiles-dir . --select tag:reporting 
Warning: CLI (0.1161.4) is running a different version than Lightdash (0.1152.0) on https://XXXXXXXX/.
         Some commands may fail, consider upgrading your CLI by doing: npm install -g @lightdash/cli@0.1152.0

✖   Setting up preview environment
Couldn't find target "[object Object]" for profile elmo in profiles.yml at /app/dbt/profiles.yml
```

### Steps to Reproduce the Bug or Issue

Set a templated default target in your profile

### version

v0.1161.4

### Cloud or self-hosting

self-hosting

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey @timhiebenthal 

If you try running your CLI command with `--target dev` does the issue still happen?

**Comment by timhiebenthal** [comment]
Hey @TuringLovesDeathMetal 

That's a good point actually!
adding the target explicitly solves the issue :) Thanks for that

But it might be related to the topic of https://github.com/lightdash/lightdash/issues/10649 , that the handling of the profiles.yml is not in sync with the default behaviour of dbt

**Comment by ZeRego** [comment]
We have code to interpret the env vars in the profile yml like so ```{{ env_var('DBT_TARGET', 'dev') }}```. We might need to update it to support the syntax ```{{ env_var('DBT_TARGET', default='dev') }}```
File: `packages/cli/src/dbt/templating.ts`
