### ISSUE TITLE
Add basic roles and permissions

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1069]
Related issues:
* #49 

### Description: What is it?

Ability for users to have different permissions. The simplest starting point would be role-based access controls, where each user can have one of a select number of roles: `viewer, editor, admin`

### Problem: What problem does this solve?

Currently all users are able to perform any action in Lightdash. This doesn't serve users that need to control how their Lightdash instance is maintained and supported. They need to hide dangerous actions like revoking users or deleting important dashboards.

### (Optional) Why: How do we know this is a real problem and worth solving?

Previous issue and discussions: #49 

### Success: How will we know if we’ve solved this problem?

Lightdash admins begin assigning different permissions to their Lightdash users

### Audience: Who are we building this for?

This would particularly benefit Lightdash admins adding team members that don't need to edit any of the dashboards but need view access. This is a really common pattern for BI.

### What: Roughly, what does this look like in the product?
<img width="594" alt="Screenshot 2022-01-05 at 14 16 13" src="https://user-images.githubusercontent.com/11660098/148232066-3b4cb1a4-ad1b-44bc-81df-902038f00350.png">

Admins can enter the existing users list and assign roles to each user. 

We would also provide useful error messages when users are not authorised to use an action. "You are not able to resize this dashboard because your user has the View-only role. Please contact your admin for help admin@your-co.com)

Additionally we should provide a list of actions available to each role on docs.lightdash.com

Viewers: viewers can see dashboards, charts, and saved queries
Editors: all viewers + can edit dashboards, charts, project settings
Admins: all editors + can edit application settings, user settings

**Comment by owlas** [comment]
@TuringLovesDeathMetal what do you think of the approach? It's quite simple for now, you can nominate some users to be editors (they can't delete users) and others to be viewers (they can only view dashboards / charts). Admins will behave as most users do today.

@ZeRego I like the incremental approach of using the [casl typescript lib](https://casl.js.org) which uses attribute based permissions and a clean syntax. We can start with simple [role based access](https://casl.js.org/v5/en/cookbook/roles-with-static-permissions) and grow the complexity over time if we need it.

I imagine simply amending the `organization_memberships` table with a role column

**Comment by ZeRego** [comment]
> We would also provide useful error messages when users are not authorised to use an action. "You are not able to resize this dashboard because your user has the View-only role. Please contact your admin for help admin@your-co.com)

I think we should hide any area or button if they don't have access to. So they would only see that error if they somehow use the API directly. 

> @ZeRego I like the incremental approach of using the casl typescript lib which uses attribute based permissions and a clean syntax. We can start with simple role based access and grow the complexity over time if we need it.

That lib seems good but doesn't have an integration with knex or express. Need to see how hard it is to integrate with them. 

Note: When a user accepts an invite it should have the 'Viewer' role by default. Future ticket: be able to create invites for a specific role

**Comment by TuringLovesDeathMetal** [comment]
Yep, this sounds good!

I think this is the first step in limiting access. It still feels like we're missing a big chunk of "permissions" here which is "how can you limit who has access to which explores/saved charts/dashboards?". 

So you have `roles` which tell you what you can _**do**_ and then you have `data access` which tells you **_what data you can access_**. 

I'm still not sure how the `data access` should work: should it be explore-based? or should it be "you have access to all of the explores, but only access to saved content made by certain people"?, or a combination?

^I'm going to do some more user research to get a better idea of this then will open a feature request.

**Comment by TuringLovesDeathMetal** [comment]
also, a reminder: we'll need to update the onboarding list on the home page if we introduce these role-based restrictions! (since some users won't be able to save charts/invite other users :) )

**Comment by nathaliabj** [comment]
Where do we envision this screen living ? like an additional option that can be accessed from the settings menu, or as a new page ? also @PriPatel do we have some designs for this, or shall i go with what we have above  👆?

**Comment by ZeRego** [comment]
> Where do we envision this screen living ? like an additional option that can be accessed from the settings menu, or as a new page ? 

I think it's a matter of having a dropdown in the existing user management page. 
![Screenshot 2022-01-18 at 14 01 16](https://user-images.githubusercontent.com/9117144/149951700-ae1264a9-5ad1-4d6e-8b5b-adac4c40900e.png)

**Comment by owlas** [comment]
@ZeRego @nathaliabj we probably want that anyone other than admins cannot see this list?

**Comment by PriPatel** [comment]
@nathaliabj - sorry!! I haven't actually done any design work on this but I agree with Jose's suggestion. I've also done like the quickest sketch suggesting that we keep 'user settings' in one place. It is then however a modal on top of a modal.
![Screenshot 2022-01-18 at 15 53 11](https://user-images.githubusercontent.com/12776522/149971572-84184c04-4235-4f9b-b9b5-147aeaf66465.png)
 
 Maybe when you hit 'edit', the card expands and you can see all the settings.

**Comment by TuringLovesDeathMetal** [comment]
+1 to the idea of the card expanding. Modal on top of modal sounds chaotic 😅 
Then maybe having `cancel` as a secondary action button beside `update` which would bring you back to the list of users?
