### ISSUE TITLE
Change the appearance and position of 'preview' badge in project dropdown

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#10702]
<img width="425" alt="Screenshot 2024-07-11 at 17 08 44" src="https://github.com/lightdash/lightdash/assets/12776522/be5f8f73-5a0d-4422-9ebf-995b271759d8">

**Problems**
- The preview badge is primary blue and draws attention to the project.
- It is hard to read project names when they don't align properly.

---
- [ ] Badge should be on the other side the project name, (so all project names align vertically). Truncate project name to make way for this
- [ ] Badge should have a more minimal appearance (maybe `outline`, and `orange`, rather than primary blue)

**Comment by cooldude6000** [comment]
Hey,
To whomever it may concern, I am currently working on this issue. 
I will **_SURELY_** comment here again if I'm unable to solve this issue.

Thanks!
