### ISSUE TITLE
query error when trying to increase row limit

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10700]
### Description

I get an error any time I try to increase the row limit in my query

### Steps to Reproduce the Bug or Issue

1. create a query
2. increase the row limit
3. see error.

see more info in slack here: https://lightdash.slack.com/archives/C03QX09JLCU/p1720710319921629

### Cloud or self-hosting

None

**Comment by rephus** [comment]
error in sentry: https://lightdash.sentry.io/issues/5594923889/?environment=cloud_beta&environment=production&project=5959292&query=id%3A116f31b677734f59a3864273e457721c&referrer=issue-stream&statsPeriod=24h&stream_index=0

**Comment by rephus** [comment]
related issue https://github.com/lightdash/lightdash/issues/10703

**Comment by rephus** [comment]
The fix is on https://github.com/lightdash/lightdash/issues/10703 , closing this duplicated ticket and I'll do a release right now with the fix.
