### ISSUE TITLE
I want to be able to override the snowflake warehouse configuration in my dbt .yml files. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10714]
### Description

In dbt, I can configure which warehouse a model is run on (in snowflake), like this:

``` 
config {
snowflake­_warehouse: 'MY_WAREHOUSE'
}
```

In the project configuration in Lightdash, you also specify which data warehouse to use for your Snowflake connection. 

But, the Lightdash warehouse is the default, and this gets overridden by the dbt configuration if you've set any. 

For example, if I have a model called `katies_model` with a config like this:

```
config {
snowflake­_warehouse: 'WRONG_WAREHOUSE'
}
```

and then in Lightdash, I set my data warehouse to be `CORRECT_WAREHOUSE`, `katies_model` will be run on `WRONG_WAREHOUSE` (the Lightdash warehouse setting is overwritten by the dbt config). 

This was intentional for some users, but it's causing errors for some other users. 

In the proejct configuration settings in Lightdash, there should be an option (a toggle?) under the `warehouse` which says `always use this warehouse` or something and will _**not get overridden**_ by the dbt model warehouse config. 

More info in Slack here: https://lightdash.slack.com/archives/C06TWBVBN9F/p1720740043667169

### Documentation

Add this info to the project configuration docs

**Comment by cooldude6000** [comment]
Hey,
should i add the info you gave here ? : https://docs.lightdash.com/get-started/setup-lightdash/connect-project

**Comment by rephus** [comment]
> In the proejct configuration settings in Lightdash, there should be an option (a toggle?) under the warehouse which says always use this warehouse or something and will not get overridden by the dbt model warehouse config.

Should this be an option in the UI, or the CLI ? or both
