### ISSUE TITLE
upsertCharts function return charts type not array

### ISSUE THREAD

**Issue by xinlingqudongX** [lightdash/lightdash#10743]
### Description

PromoteService中的函数返回类型不匹配
Function return type mismatch in PromoteService

### Steps to Reproduce the Bug or Issue

在PromoteService.ts中的函数upsertCharts返回的charts数据类型不是数组
The charts data type returned by the function upsertCharts in PromoteService.ts is not an array

![image](https://github.com/user-attachments/assets/c8c4e7e2-68c1-4bd5-a9f8-376424c876bb)
![image](https://github.com/user-attachments/assets/3962595d-7935-483f-8d4c-a9b0f44a435a)

### version

v0.1172.0

### Cloud or self-hosting

None

**Comment by ZeRego** [comment]
@all-contributors add @xinlingqudongX for bug
