### ISSUE TITLE
Month-truncated date filter does not search for correct date if switching from day-level truncation

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#10748]
### Description

When creating the following filter...
![image](https://github.com/user-attachments/assets/cea3c562-cf7d-42f2-b79e-2c8cbffa95cc)

... the SQL compiles as follows:
![image](https://github.com/user-attachments/assets/7a855961-0192-4282-98c4-9a6b148bb627)

The date in the query should be '2024-06-01', but is '2024-06-05'.

I think this only happens if I change an existing date.day filter to a date.month filter as I was previously filtering for date.day = '2024-06-05'. It seems that when the granularity of the filter is changed, it doesn't update to use the correct date value in the filter.

### Steps to Reproduce the Bug or Issue

1. Create a date.day filter (equal to a day that's not the 1st of the month)
2. Change the filter to date.month
3. View the compiled SQL

### version

v0.1172.0

### Cloud or self-hosting

cloud

**Comment by TuringLovesDeathMetal** [comment]
Possible related to https://github.com/lightdash/lightdash/issues/7689 and https://github.com/lightdash/lightdash/issues/9985
