### ISSUE TITLE
Investigate: make SQL data transformers take (and use) a data post processor

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#10750]
### Description

Investigate: make SQL data transformers take (and use) a data post processor. Maybe an object that supports a defined set of data post-processors. These might run on the FE or in DuckDB or somewhere else. 

Maybe:
- Transformer gets a post processor that defines what the functions are
- The config can drawn/set up to show the functions available
- When creating the chart config, the transformer checks the series for post-processed data and calls the post processor.

**Comment by joaoviana** [comment]
This can be closed after work done on: https://github.com/lightdash/lightdash/pull/10837
