### ISSUE TITLE
Add `context` and `chart_id` to all `query_executed` events 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10773]
### Description

Right now, we have some pages where `query_executed` event is triggered, but we don't save the context of where the query executed event is coming from. 

Specifically, we're missing information about:

- SQL runner (does a sql runner query trigger the same `query_executed` event?)
- scheduled charts
- scheduled dashboards
- AI co-pilot queries
- automatic dashboard refresh (in case the query is triggered from the automatic dashboard refresh - is this possible to differentiate from `dashboardView` that we have today?)
- API-triggered query executions (are there multiple ways to do this? Do we need a secondary field wiht more context of which API call is executing this? Or is that overkill?)

We also have information about the project, dashboard, etc. but not about `chart_id`. 

Can we add `chart_id` as a parameter as well? And this value can be NULL (e.g. the query is not coming from a saved chart)

### Acceptance criteria:

- [ ] every query executed event has `context`
  - [ ] we might need to break this out into smaller tickets - e.g. add scheduled delivery to context
- [ ] query executed events for specific charts has a `chart_id` parameter which is filled

**Comment by jpetey75** [comment]
What about API-triggered query executions @TuringLovesDeathMetal ? I assume there are multiple ways to trigger a query executed event via API

**Comment by TuringLovesDeathMetal** [comment]
^yep! Good call!

**Comment by rephus** [comment]
> SQL runner (does a sql runner query trigger the same query_executed event?)

SQL runner queries trigger the `lightdash_server.sql.executed` event, like this old sql runner: 

![image](https://github.com/user-attachments/assets/0801a71f-3ad9-496b-aff6-616f1a0e819f)

On the new sql runner we added `usingStreaming": true`

![image](https://github.com/user-attachments/assets/e9025d54-c321-4d65-851a-b21a199e89fb)

**Comment by rephus** [comment]
I've noticed all scheduled deliveries where sending the wrong `GSHEET` context
