### ISSUE TITLE
Charts and dashboards are displayed in a random order in spaces

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#10809]
### Description

Charts and dashboards are displayed in a random order in spaces

instead, it should be default sorted by last edited date.

bonus: it should also allow custom sorting by name + date by clicking the headers

![CleanShot 2024-07-23 at 19 58 03@2x](https://github.com/user-attachments/assets/81d0f976-fffd-466b-bd17-0bba6674a42d)

### Steps to Reproduce the Bug or Issue

1. go to spaces
2. 💥 

### Cloud or self-hosting

None

**Comment by rephus** [comment]
add sort in the backend (sql) by lastUpdatedAt to the v2 content endpoint 

Note that the order needs to applied after the unionAll ( not in the individual queries)
