### ISSUE TITLE
`sql_filter` that uses fields from other joined tables is not joining tables

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10828]
### Description

I have a `sql_filter` which is using a field from a joined table. 

The joined table is not being included in my `from` bit of the SQL query. So, teh query errors when it's executed. 

This could be because it's using a bridge table to join it. Or, it could be an issue more generally wiht joined tables in the `sql_filter` we need to investigate!

### Steps to Reproduce the Bug or Issue

More context in this thread: https://lightdash.slack.com/archives/C071TU6FZ3P/p1721674501240779?thread_ts=1721674501.240779&cid=C071TU6FZ3P

### Cloud or self-hosting

None

**Comment by IrakliJani** [comment]
workaround: https://docs.lightdash.com/references/joins/#always-join-a-table

**Comment by ZeRego** [comment]
Note that we have logic to join all tables referenced in filters

Check `selectedTables` in `packages/backend/src/queryBuilder.ts`
