### ISSUE TITLE
Table as default chart type in sql runner

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#10855]
Acceptance Criteria
- [ ] By default, if I save SQL chart, and I have made no changes to the layout/styling it should default to TABLE

**Comment by magnew** [comment]
@owlas you think we still want to do this if we are always going to be showing the results table?

**Comment by joaoviana** [comment]
> @owlas you think we still want to do this if we are always going to be showing the results table?

Yup, I agree with @magnew's point, how should it work if we render the bar chart by default?

https://github.com/user-attachments/assets/a8ea2f01-0acb-42dd-807d-f8fbc0e94dbb


If we want to enable the `table` by default, we could do the following flow
- [ ] user types sql and hits `run query`
- [ ] results get populated + SQL editor remains visible
- [ ] default visualization is TABLE

currently, we switch to the bar chart view as soon as the results get fetched.

**Comment by joaoviana** [comment]
done here: https://github.com/lightdash/lightdash/pull/10903
