### ISSUE TITLE
Table calculation modal should have the buttons for `save` and `cancel` appear in the modal (without scrolling)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10884]
### Description

Today, when I try to create/update a table calculation, the `save` and `cancel` buttons are hidden. I need to scroll to see them. 

These buttons should appear in the modal, by default. This may require us to shrink the SQL component. 

### Steps to Reproduce the Bug or Issue

![image](https://github.com/user-attachments/assets/97d82e55-9a7c-4582-873c-5785d3033923)
![image](https://github.com/user-attachments/assets/3816fb2d-07fb-4d41-b427-2604bad63623)

### Cloud or self-hosting

None

**Comment by aayushi1995** [comment]
Hello @ZeRego, 
I want to contribute to this issue.
Could you please assign this issue to me?
