### ISSUE TITLE
Add workaround for pasting filter values that contain commas

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#10950]
### Description

Allow strings that have commas as part of the string to be pasted into filters without breaking them into multiple values. 

### What problem does this solve?

When pasting values into a string filter, if the pasted value has commas in the string, Lightdash breaks the string into multiple pieces. That change was made here: https://github.com/lightdash/lightdash/pull/4899

Sometimes users need to add filter values that contain commas as part of the string, so we should offer a workaround and not force the string to break apart.

**Comment by jpetey75** [comment]
Customer slack convo about this here: https://lightdash.slack.com/archives/C06J7R3HC5C/p1722452478930419

**Comment by joaoviana** [comment]
I believe this was done here: https://github.com/lightdash/lightdash/pull/10970 and it's released.
