### ISSUE TITLE
SQL runner: don't unmount charts when we change the chart type

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#10983]
### Description

SQL runner: don't unmount charts when we change the chart type.

Success looks like: when you view a chart, it stays mounted so when you switch back to it its already loaded. 

### Steps to Reproduce the Bug or Issue

N/A

### Cloud or self-hosting

None

**Comment by magnew** [comment]
I made an attempt at this, but it got a little gnarly and we might want to think about what we want. 

The charts re-render because the chart config gets switched out and the results get re-processed. I tried making it so each chart is always mounted and refers to its own config and changing chart type shows and hides them. But with that change, new data causes the chart config to break because the columns change. 

Do we want to blow away the config when new data comes in?

There's a branch here: https://github.com/lightdash/lightdash/compare/10983-dont-unmount-charts?expand=1

**Comment by joaoviana** [comment]
> Do we want to blow away the config when new data comes in?

I think this is still not solved and we haven't found a way to handle this in a centralised way. 

But yea, the changes look good and seem like a good way to move forward, but understand there's a pre-requisite here before moving forward
