### ISSUE TITLE
All charts in dashboard deleted when editing multiple dashboards in the same tab

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#11018]
Steps to reproduce:
1. Create 2 dashboards
2. Create charts in dashboards for both dashboards
3. Click to edit the chart in one of the dashboards (let's call this, dashboard 1)
4. Copy the **edit** link of the other dashboard (dashboard 2) into the same tab where you were editing the chart of dashboard 1
5. Dashboard 2 opens in edit mode - notice that the title is of dashboard 2 but the charts are from dashboard 1
6. Click "Cancel"

Relates to: [#11016](https://github.com/lightdash/lightdash/pull/11016)

Video with reproduction steps:

https://github.com/user-attachments/assets/92a6f593-713b-4a1e-9931-41f3f4cdefeb

**Comment by ZeRego** [comment]
We are closing this ticket:
- it is an edge case
- we stopped deleting the charts in the DB which was the biggest problem as we couldn't recover the charts
- we are planning to change this entire UI flow and stop relying on session storage
