### ISSUE TITLE
Changing the source table of charts

### ISSUE THREAD

**Issue by bolafadipe** [lightdash/lightdash#11024]
### Description

Ability to point the source table of a chart to another table in Lightdash.

### What problem does this solve?
Whenever I change the name of a dbt model, the charts in Lightdash that uses that source table become broken. 

Recreating the charts is usually frustrating and time consuming. Given the ability to point the charts to a new table will help resolve the challenges in creating a new chart all over.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/5264
