### ISSUE TITLE
Warehouse schema doesn't update after refresh dbt

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1103]
### Describe the bug

Warehouse schema doesn't update after refresh dbt

### To Reproduce

1. Go to SQL runner
2. Click on refresh dbt
4. See that warehouse schema doesnt update

### Expected behavior

It should show new warehouse schame

### Screenshots or Loom video

![Screenshot 2022-01-06 at 14 47 55](https://user-images.githubusercontent.com/9117144/148401297-c0c7db9a-170b-45bc-b05f-61982ae79408.png)

**Comment by TuringLovesDeathMetal** [comment]
closing this issue as not planned. it's no longer relevant with the updates to teh SQL runner (which shows all tables in the warehouse, not just dbt tables)
