### ISSUE TITLE
Default sort in results table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11032]
### Description

The results table is sorted by default depending on the types of fields you select. 

- you can see the field that your results table is sorted by
- The first field you add to your results table will be the field that’s sorted (descending).
- If you only have metrics in your query, then you add a dimension, the default sort is changed to sort on the dimension (descending). I.e. it’s not based on the first field that you added to your results table.
- If there is a date dimension in your query, then that should always be used to sort (descending).
- If there are multiple date dimensions added to your query, then you should sort by the first date dimension that was added to the query (descending).

**Comment by owlas** [comment]
Moved to https://github.com/lightdash/lightdash/issues/11033
