### ISSUE TITLE
We should update the copy in the `ask a question` button

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1106]
### Description: What is it?

We should update the copy on the `ask a question` button to something that makes it seem more like "this is where you go to create something from scratch"

### Problem: What problem does this solve?

The `ask a question` button in the Homepage doesn't make it clear that it's the button you press to get started to create a new chart. 

### (Optional) Why: How do we know this is a real problem and worth solving?

Feedback: If I click the `ask a question` button, I thought I would be asking to get help from the Lightdash team. 

### Success: How will we know if we’ve solved this problem?

More people are clicking on the newly named `ask a question` button in teh homepage.

### Audience: Who are we building this for?

Users who want to build charts/dashboards from scratch. 

### What: Roughly, what does this look like in the product?

We've updated the copy for the `ask a question` button.

**Comment by PriPatel** [comment]
Haven't put much thought into this but it seems like changing `ask a question` to` run a query` is already so much clearer? Quick fix till we revisit this area again? I know it doesn't necessarily make it clearer that you can save a chart/create a dashboard but 'run a query' is pretty true to what that button does!

**Comment by PriPatel** [comment]
Or `Start exploring`?
