### ISSUE TITLE
SQL Runner: table autocomplete isn't complete

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#11066]
### Description

In analytics when I type pages in the sql runner it only suggests base_pages and not the full pages model? Looks like missing entries from the autocomplete

### Steps to Reproduce the Bug or Issue

1. search pages in analytics
2. it doesnt show 'pages'

### Cloud or self-hosting

None

**Comment by owlas** [comment]
This is due to this problem: #11059
