### ISSUE TITLE
Some users are seeing no tables in the SQL runner

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#11078]
### Description

Some users are seeing no tables in the SQL runner.

Probably related to this issue: https://lightdash.sentry.io/issues/5614959971/?alert_rule_id=9333608&alert_type=issue&environment=cloud_beta&notification_uuid=505b6c8c-24f9-412e-b698-9ab3471cba93&project=5959292&referrer=issue_alert-slack

### Steps to Reproduce the Bug or Issue

n/a

### Cloud or self-hosting

None

**Comment by owlas** [comment]
Moving to: https://github.com/lightdash/lightdash/issues/11059
