### ISSUE TITLE
Deleting a dashboard from the resources list doesn't work well

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#11121]
### Description

Deleting a dashboard from the resources list is has frustrating UX. If you delete a dashboard, it stays in the list, then when you try to delete it again you get an error. 

![Kapture 2024-08-13 at 10 01 38](https://github.com/user-attachments/assets/dc8379b7-e63d-4104-a03b-d5c9aece936f)

### Steps to Reproduce the Bug or Issue

1. Delete a dashboard from the users list
2. It stays in the list
3. Try to delete it again
4. Error

See screencap

### Cloud or self-hosting

None

**Comment by ayush3160** [comment]
Hi @magnew , I would to work on this , Can you please assign this to me.

**Comment by ZeRego** [comment]
@ayush3160 On delete, we need to invalidate the dashboard list request to the list refreshes. 
Check react-query (lib) invalidateQueries method
