### ISSUE TITLE
SQL Runner: pre-filled snowflake tables are incorrect

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#11134]
### Description

In the new SQL runner, snowflake tables are populated, but when clicked on, they fill in a sql query that doesnt work. Clicking on payments, for example, prefills 

`SELECT * FROM "snowflake_database_staging"."jaffle"."payments"`

Which doesn't work. The following SQL does work:

SELECT *
     FROM SNOWFLAKE_DATABASE_STAGING.jaffle.payments 
     
    

### Steps to Reproduce the Bug or Issue

See above

### Cloud or self-hosting

None

**Comment by hamzahc1** [comment]
We're not using warehouse specific quotes, we're using double quotes OR casing is wrong
