### ISSUE TITLE
Add support for Firebolt

### ISSUE THREAD

**Issue by kevinmarr** [lightdash/lightdash#1114]
### Description: What is it?

Firebolt is a next-generation cloud data warehouse that offers unprecedented query performance on top of a modern separate-storage-and-compute architecture. It specializes in analytical workloads and complements in-database business intelligence nicely.

### Problem: What problem does this solve?

Query performance, primarily. Allows Firebolt customers to use Lightdash, and vice versa.

### Success: How will we know if we’ve solved this problem?

All "must-have" Lightdash features are working and as many "nice-to-have" features are working, as permitted by Firebolt feature availability. Looking to Lightdash team to own this list and communicate requirements to Firebolt as needed.

**Comment by kevinmarr** [comment]
We finished the first iteration of our Node SDK, which from the looks of your codebase should come in handy. https://www.npmjs.com/package/firebolt-sdk. Let us know if you need anything added to the SDK. We will publish the source code soon under Apache 2.

**Comment by owlas** [comment]
Hey @kevinmarr thanks for opening this and great to hear from the firebolt team!

We'd love to add firebolt, since a couple of Lightdash users have requested this integration already. 

Can I check that this is the official dbt package? I'll use it for testing: https://github.com/firebolt-db/dbt-firebolt and does it work out of the box with the jaffle shop demo?

**Comment by kevinmarr** [comment]
That is the official adapter, indeed. And here is a fork of the jaffle shop project we've been using: https://github.com/firebolt-db/jaffle_shop_firebolt. 

Currently the dbt adapter uses a JDBC wrapper, but within a month we will be upgrading it to use our new Python SDK instead.

**Comment by owlas** [comment]
Is it also compatible with ODBC? I'd prefer to JDBC since we don't have the JRE in the Lightdash docker image but ODBC is already there.

**Comment by kevinmarr** [comment]
Sorry for the late reply - we don't have an ODBC driver. Sounds like it would be best to wait for the Python SDK version, which ought to be coming within a week or so.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue - we only support dbt verified adapters. ONce Firebolt is dbt verified, we'll support it!
