### ISSUE TITLE
Update error message stacking

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11198]
### Description

The warnings that appear in the query builder sometimes pile up and block the user from editing results table (like fixing the table calculation that caused the error). Ideally the warnings would not block any features, or offer a single "dismiss all" option rather than having to click each one.

Part of the problem is that often times multiple errors get thrown when a single field is removed.

### Acceptance criteria:

- [ ] When there is one error message, the behaviour should be exactly like it is today
- [ ] When there is more than one error message, they should collapse into a collapsible list. 
- [ ] There should be a way to open this list
- [ ] There should be a way to `dismiss all errors` on the collapsed version of the list
- [ ] There should be a way to open the list and dismiss the errors one-by-one
- [ ] When the list is collapsed, it should tell you how many errors there are (e.g. `errors (5)`)
- [ ] This number should decrease if you dismiss errors. 

![image](https://github.com/user-attachments/assets/d0f2bf82-46df-4490-b113-02f4216e2612)

**Comment by rephus** [comment]
We could unify these errors by using the `key` argument in the toaster. Some of them (I think this one in particular) are just duplicates that are triggered multiple times.

**Comment by TuringLovesDeathMetal** [comment]
@magnew Small frontend changes: 

- [ ] add margins to the top and bottom of the multiple error box
- [ ] collapse the errors by default if there are more than 1
- [ ] add scrolling within the error messages list (if there are multiple)
- [ ] keep the "collapse" and title pinned at the top
