### ISSUE TITLE
Handle SQL runner limit and improve the results table view

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#11233]
### Description

Hide SQL Runner limit on the button.

Always show a `500` limit on the results table, unless the user applies a limit to it which will be lower(?) - this should be clear in the table! (e.g. `preview 500 rows` or something)

Allow for fine-tuning this limit on the visualization.

The Chart results table should mimic what's being chosen/configured on the chart. For example:
- I select 10 columns with my SQL Query
- But I only choose 3 to build my chart
- Then I should only see these on my chart's table

**Comment by sanjay-sol** [comment]
Hey @joaoviana , Can I work on this ?

**Comment by joaoviana** [comment]
thank you for your interest @sanjay-sol, but this is a task I'll be taking soon. You're more than welcome to look into other issues here: https://github.com/lightdash/lightdash/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%91%8B+open-contribution%22 😄
