### ISSUE TITLE
Support individual user logins for Snowflake connections

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11235]
### Description

We need this: https://github.com/lightdash/lightdash/issues/8630

but for Snowflake

### What problem does this solve?

Allows admins to force all Lightdash users to login with Snowflake credentials so data governance follows permissions in Snowflake rather than needing to set up row-level security in Lightdash.

**Comment by ZeRego** [comment]
This is available if the feature flag `passthrough-login` is enabled.
