### ISSUE TITLE
For some tables, the schema appears to be empty

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#11276]
<img width="435" alt="Screenshot 2024-08-27 at 13 54 29" src="https://github.com/user-attachments/assets/fa7a0475-56bb-48e8-92a8-b8ae83bd65aa">

This works for some tables, but not for others.

**Comment by neehhaa06** [comment]
Hello @PriPatel 

Would you explain me a little bit, what is bug in this problem?
