### ISSUE TITLE
Search bar does not filter out irrelevant tables

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#11278]
<img width="281" alt="Screenshot 2024-08-27 at 14 15 13" src="https://github.com/user-attachments/assets/2caf378e-2a67-4a2a-a9b4-c4b9edf8079a">

The right tables are highlighted, but I don't expect to see the rest of the tables.
They filter out when I hit the spacebar though!

**Comment by neehhaa06** [comment]
Hello @

Update the search bar to use the `input` event instead of `**keyup` or `keydown`**. Ensure the filtering logic trims **whitespace** and processes the input on every change to correctly filter out irrelevant tables as you type.
