### ISSUE TITLE
URL links in embedded dashboard table do not work

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11292]
### Description

URL links in embedded dashboard table are not clickable and do not show the drop-down for clicking through to the link destination.

### Steps to Reproduce the Bug or Issue

Create a table that includes a string field with a URL link defined in the YAML. Add that table to a dashboard and embed the dashboard. The link is not clickable.

### Cloud or self-hosting

cloud

**Comment by sanjay-sol** [comment]
Hey @jpetey75 ! I would like to work on this issue. Can you assign it to me!
