### ISSUE TITLE
 Reset Filters Button

### ISSUE THREAD

**Issue by sanjay-sol** [lightdash/lightdash#11298]
### Description

Currently, there's no "Reset Filters" option, which makes it a bit inconvenient to remove filters one by one. It would be helpful to have a "Reset Filters" button alongside the "Add Filter" button, allowing users to clear all filters with a single click.

### Current Setup:
Right now, the filters section looks like this :
No option to reset or clear all filters at once. Users have to manually remove filters one by one.

![actual](https://github.com/user-attachments/assets/63fe4d07-60a1-4433-ad7a-f7e49638d2c2)

### Proposed Feature:
With the new "Reset All Filters" button, the filter section would look like this:
This button would remove all active filters in one click, saving time and effort for users.

![proposed](https://github.com/user-attachments/assets/8566ee71-dda3-4149-b303-8d561fedbeb5)

### What problem does this solve?

This would improve user experience by simplifying the process of clearing filters, making it quicker and more efficient.

**Comment by sanjay-sol** [comment]
Hey @ZeRego  @joaoviana , can I work on this feature ?

**Comment by ZeRego** [comment]
@sanjay-sol yes, you can work on it. Here are some design instructions:
- minimal 'clear all' button (very small) on the right side
  - let us know if you can find a good icon for it: https://tabler.io/icons . If there isn't a good one we can try with just text.
- tooltip "Clear all filters"

**Comment by sanjay-sol** [comment]
Hey @ZeRego  ,
I’ve added the clear all functionality with plain text instead of an icon. It seems to fit better with the design. Let me know if you'd like any changes or adjustments!


https://github.com/user-attachments/assets/73a96724-1292-4243-b680-95a18662ec98

**Comment by sanjay-sol** [comment]
Hey @ZeRego , Can you please give feedback on above issue?

**Comment by sanjay-sol** [comment]
> Hey @ZeRego , I’ve added the clear all functionality with plain text instead of an icon. It seems to fit better with the design. Let me know if you'd like any changes or adjustments!
> 
>  edited.mp4

Hey @ZeRego , @joaoviana !
Are there any suggestions or improvements you would recommend? I'd like to finalize this and submit a PR to close the issue.

**Comment by sanjay-sol** [comment]
> @sanjay-sol yes, you can work on it. Here are some design instructions:
> 
> * minimal 'clear all' button (very small) on the right side
>   
>   * let us know if you can find a good icon for it: https://tabler.io/icons . If there isn't a good one we can try with just text.
> * tooltip "Clear all filters"

Hey @ZeRego , @joaoviana !!
Are there any suggestions or improvements you would recommend? I'd like to finalize this and submit a PR to close the issue.
Thanks!
