### ISSUE TITLE
Allow fine-tuning the limit on the visualization

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#11305]
### Description

Acceptance criteria
- [ ] When I run a query, I know I'm previewing its first 500 rows (if there are less, I don't see a message stating this)
- [ ] When I go to the visualization/chart tab, I can tune the number of results of my query. I can see there's a default number of 500 rows, but I also know I can change this value to change the limit of the results I want back

**Comment by sanjay-sol** [comment]
Hey @joaoviana 

I’m looking to contribute to Lightdash but noticed there are no recent issues labeled "open-contribution." I’ve already raised a PR for a previous issue under that label. Could you please add some new issues with the "open-contribution" label so I can continue contributing?

Thanks!
