### ISSUE TITLE
Allow more than two levels of nested groups for dimensions and metrics

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11316]
### Description

Let's add **one more level** of metric-group nesting. 

Currently dimensions and metrics can be grouped, but two levels of groups is the max:

- group
  - nested group
    - double nested group (this is not supported)

### What problem does this solve?

For customers with long lists of metrics or dimensions more levels of nesting allows for more organization.

### Documentation

update teh docs here: https://github.com/lightdash/lightdash/issues/12209

and here: https://docs.lightdash.com/references/dimensions#groups

**Comment by jranks123** [comment]
@jpetey75 I can't emphasise how much I'd love this feature. If it's a quick win, this would really enable our strategy
