### ISSUE TITLE
Add support for BigQuery execution project

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11312]
### Description

Add support for what dbt calls `execution_project`: https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#execution-project

dbt Core added support for this here: https://github.com/dbt-labs/dbt-core/pull/3707

### What problem does this solve?

Allows customers to separate billing of queries being executed by a specific client (Lightdash in this case) from GCP billing where the project actually lives (cost of building and storing the models).

**Comment by sanjay-sol** [comment]
Hey @jpetey75 ,

I’m looking to contribute to Lightdash but noticed there are no recent issues labeled "open-contribution." I’ve already raised a PR for a previous issue under that label. Could you please add some new issues with the "open-contribution" label so I can continue contributing?

Thanks!

**Comment by ZeRego** [comment]
Quick investigation:
We would need to change all places were we create a bigquery client to point to the execution_project instead of the project value

```
           this.client = new BigQuery({
                projectId: credentials. execution_project,
                ...
```

Then change the query methods receive the database and schema as arguments and set a `destination` for the bigquery job. 
```
const dataset = bigquery. dataset('my-dataset');
const table = dataset. table('my-table')

await this.client.createQueryJob({
   destination,
   ...
```

what would we pass for SQL runner queries?
Still not sure if the `destination` is needed and if so, why are we making this change instead of setting execution_project value as the project value 🤔

**Comment by ZeRego** [comment]
> Then change the query methods receive the database and schema as arguments and set a destination for the bigquery job.

We shouldn't have to make changes to the jobs as the SQL has the correct database references.

> what would we pass for SQL runner queries? We would omit the destination.

Similar to above, no changes needed.

----

The bigquery client needs to be created with the execution_project value. 
For the methods that need to specify a database(aka project), like `getFields` and `getCatalog` we need to create dataset references with the intended projectId.

```
         const client = new BigQuery({
            projectId: this.credentials.execution_project,
            location: this.credentials.location,
            maxRetries: this.credentials.retries,
            credentials: this.credentials.keyfileContents,
        });


        let ds = new Dataset(client, "schema", {
            projectId: "a-test-project"
        });
```

PR that allowed this: https://github.com/googleapis/nodejs-bigquery/pull/1079/files

**Comment by owlas** [comment]
@ZeRego the new catalog endpoint has support for specifying the database, we just need this on the previous cataloging endpoints!
