### ISSUE TITLE
Cannot use `.` as the project directory root

### ISSUE THREAD

**Issue by davidgasquez** [lightdash/lightdash#1131]
### Describe the bug

When setting up a new connection, the `.` string in the _Project directory path_ configuration should be interpreted as `/`. 

### To Reproduce

1. Go to `https://yourorg.lightdash.cloud/projects/ID/settings`
2. Fill out the details. Set _Project directory path_ to `.`
3. Click _Test and Save Connection_

![1642001329](https://user-images.githubusercontent.com/1682202/149170265-efb4747b-4be4-4927-9716-d489faddf127.png)

### Expected behavior

The setting should accept `.` the same way it accepts `/`.

**Comment by owlas** [comment]
Thanks for opening this @davidgasquez !

I see a few solutions:
1. improve form validation and not allow `.` or `..` or perhaps anything that doesn't start with `/`
2. allow the path to be set to `.` and simply replace it with `/` before saving the configuration
3. allow the path to be set to `.` and adjust the git interface to handle `.`

@ZeRego looking at the [code for the git adapter](https://github.com/lightdash/lightdash/blob/main/packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts) I guess `.` is getting lost somewhere during the shallow clone?

**Comment by ZeRego** [comment]
@owlas @davidgasquez We recently added validation to the form and this field now shows an error if it doesn't start with a `/`. Would you consider that a fix since users know they can't use `.` ?

[PR with validation](https://github.com/lightdash/lightdash/pull/1145)

**Comment by ZeRego** [comment]
Closing this based on previous comment. Feel free to reopen/comment if you feel we should change this.
