### ISSUE TITLE
I'm seeing error icons next to most of my content, but the validator isn't showing any errors

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#11322]
<img width="866" alt="Screenshot 2024-09-02 at 10 00 59" src="https://github.com/user-attachments/assets/3f98b5cf-c10a-49ba-8e06-e7eed552e2a1">
<img width="882" alt="Screenshot 2024-09-02 at 10 01 04" src="https://github.com/user-attachments/assets/95eb06a3-b98f-4ebf-84ba-47efeaa51199">

This affects most content in our Analytics project

**Comment by jpetey75** [comment]
I don't know why this is happening but I can confirm it also happens in the Healthcare Demo project under the Lightdash org.
