### ISSUE TITLE
`First` aggregation method doesn't work (replace with `any value`)

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#11329]
### Description

When selecting a column + its aggregation as `FIRST` then, my chart breaks.

Check what SQL is being generated against the warehouse.

### Steps to Reproduce the Bug or Issue

1. Create chart
2. Select a column that allows `First` aggregation
3. Select it
4. See chart breaking

### Implementation suggestion

Replace it with ANY_VALUE 
https://docs.snowflake.com/en/sql-reference/functions/any_value
https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#any_value
https://www.postgresql.org/docs/16/release-16.html

### Cloud or self-hosting

None

**Comment by rephus** [comment]
any_value on postgres is not a avlid function (only available from v 16+)

https://www.postgresql.org/docs/15/functions-aggregate.html
