### ISSUE TITLE
Allow to duplicate a custom dimension or custom metric

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#11328]
### Description

Allow to duplicate a custom dimension or custom metric via the sidebar options. 
This option is only available in edit mode and if the user has permission.

### What problem does this solve?

There are cases when we want a small variation from an existing custom dimension/metrics.

**Comment by varunguleriaCodes** [comment]
Hi @ZeRego would like to work on this. What exactly copy means as there are multiple fields in custom dimensions and custom metrics? So like they click on copy all those values will get copied and when they add a new metrics or dimensions we give an option to prefill with all the copied fields?

**Comment by ZeRego** [comment]
Hi @varunguleriaCodes 👋 

On the sidebar options (see image ), we should have an option "Duplicate". 
This will automatically add a new custom dimension/metrics to the sidebar with the same properties and the name "Copy of {name}". 

<img width="355" alt="Screenshot 2024-09-09 at 15 00 38" src="https://github.com/user-attachments/assets/88daca03-a916-45d3-88a7-555a3603c699">
