### ISSUE TITLE
Handle permissions issue in SQL charts in dashboards

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#11331]
### Description

Investigate a potential race condition when rendering SQL charts in dashboards.
Users get a permissions error thrown when viewing the chart, and it usually gets fixed by refreshing the page. Could there be a property that is being passed as `undefined`, leading to this?

<img width="766" alt="image" src="https://github.com/user-attachments/assets/6541dffd-ba3d-421d-a648-59237c330b50">

### Steps to Reproduce the Bug or Issue

----- 

### Cloud or self-hosting

None

**Comment by rephus** [comment]
We can't replicate, we thought it might be related with the posthog feature. If we don't see it again, we can close it.

**Comment by owlas** [comment]
Appears to be solved by removing the feature flags
