### ISSUE TITLE
SQL Runner fails when no rows returned

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#11330]
### Description

When there's only one value for the pivot, the chart breaks.

(see `order_status` being only one value `completed`)

before grouping
<img width="1506" alt="Screenshot 2024-09-02 at 11 07 34" src="https://github.com/user-attachments/assets/8d41fc78-0517-4c51-9764-04d551cf60ab">

after
<img width="1492" alt="Screenshot 2024-09-02 at 11 07 39" src="https://github.com/user-attachments/assets/a047d449-3e52-4355-9d63-5ca06903844a">

DEMO query to test

```sql

SELECT
  "orders".status AS "orders_status",
  "orders".customer_id AS "orders_customer_id",
  COUNT(DISTINCT "orders".order_id) AS "orders_unique_order_count"
FROM "postgres"."jaffle"."orders" AS "orders"
WHERE "orders".status = 'completed'


GROUP BY 1,2
ORDER BY "orders_unique_order_count" DESC
LIMIT 500

```

### Steps to Reproduce the Bug or Issue

Follow steps above ^

### Cloud or self-hosting

None

**Comment by rephus** [comment]
I cant' replicate

![image](https://github.com/user-attachments/assets/58677f41-a2ea-45c7-a5f6-bdb3c0594116)

**Comment by rephus** [comment]
I can't replicate, it seems this has been fixed already
