### ISSUE TITLE
Add charts to SQL runner

### ISSUE THREAD

**Issue by nkotlyarov** [lightdash/lightdash#1135]
Hi!

I would like to be able to get charts from SQL Runner.
Is it possible to add a chart view section?

As of today, a table view is only available so I need to go somewhere else (another tool?) in order to get basic charts.

I understand, that it is possible to create a dbt model and then map dimensions and metrics, but what if I already have a query and need to understand something very quickly?

**Comment by TuringLovesDeathMetal** [comment]
This is a great idea - we've chatted a bit about this internally too. 

I think the one thing from making this "super easy" was figuring out how to identify metrics in the query. @owlas @ZeRego do you remember if there was anything else that made this a bit more complicated? 🤔

**Comment by nkotlyarov** [comment]
I have several heuristics in my mind:

**Comment by nkotlyarov** [comment]
I also believe, Tableau did a lot of progress on that topic so it may be a good idea to use their app for inspiration. It looks like they use at least column type, name, and domain.

**Comment by TuringLovesDeathMetal** [comment]
> If type(column) = "float" then it is metric
> If type(column) = "int" and it does not look like a SERIAL or FOREIGN KEY then it is metric.

^neat idea. I like simplifying it like this. Looks like [Looker has done something similar](https://docs.looker.com/data-modeling/learning-lookml/sql-runner-create-queries#:~:text=The%20results%20table%20and%20visualization%20interpret%20any%20numeric%20field%20as%20a%20measure.)

Will also take a look at tableau to see what they've done 👀

**Comment by nkotlyarov** [comment]
> Is this issue still relevant? There have been no updates for 60 days, please close the issue or keep the conversation going!

For sure it is!

@TuringLovesDeathMetal any updates?

**Comment by TuringLovesDeathMetal** [comment]
@nkotlyarov yep! This is one of the first things on the list for supporting a better analytics engineer development workflow 👌 

We'll be starting to work on it in the next 2 weeks :)

**Comment by TuringLovesDeathMetal** [comment]
User acceptance criteria:
- If I run a SQL query in the SQL Runner, I can open a `charts` space and visualize my results. 
- There are default chart settings applied to my results table.
  - I'd expect similar default settings to in the `explore` page. That means we'd need to "guess" which things are metrics/dimensions. I'd expect something like Nikita's suggestion to start off with: 
> If type(column) = "float" then it is metric
> If type(column) = "int" and it does not look like a SERIAL or FOREIGN KEY then it is metric.
> The rest of the columns are treated like dimensions. 
- All of the chart config settings should work in the SQL runner space (except for pivoting tables - this shouldn't be allowed in the SQL Runner space)

Am I missing anything obvious? @owlas

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal Since we changed the chart configuration to allow all fields in the x/y axis we might not need this. 
Is there any limitation/problem if we treat all columns as dimensions ?

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego no, I don't think so - except for default chart configs. 

^I imagine a lot of our default configs do (and will) depend on whether something is a metric vs. dimension?
