### ISSUE TITLE
You can save an invalid chart, and get an error later

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#11486]
### Description

I switched tables and I ended up with an invalid chart, however, the chart was looking fine in edit mode, but in view mode, I got the ìnvalid chart` error 

![image](https://github.com/user-attachments/assets/fba4136f-8ea2-42a1-b778-50f59ce30df7)

![image](https://github.com/user-attachments/assets/c702c8f4-8fc8-483e-a6a2-88d09e7fae85)

Suggested solutions: 
- Do not allow saving chart with errors 
- Show chart error in edit mode. 

### Steps to Reproduce the Bug or Issue

1. generate  a chart from a table
2. change thesql to get errors on fields
3. save
4. get sql error

### Cloud or self-hosting

None

**Comment by joaoviana** [comment]
- The `sql` sent to the backend should be the sql set **after** running a successful query. At the moment, if I just edit the sql, and not run query, it doesn't matter. That newly-typed sql will be sent to the backend
- When running a new / editing a `sql` query, and if there are configuration errors with the selected viz config, we should alert the user that there are errors and that they need to be fixed before saving
