### ISSUE TITLE
The user drop-down blocks the `save` button in user groups

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11495]
### Description

https://www.loom.com/share/5624be70594044dbac111e1adf65f116

When you go to add a member to a group, the dropdown hides the save button so I always click the x the first time I try it and then remember I need to close the dropdown before I hit save.

### Suggested approach:

Maybe we can make teh drop-down appear above the item? Like in table calculations: 
<img width="815" alt="image" src="https://github.com/user-attachments/assets/972fb219-1191-41db-8e2e-81dd48237d2b">

**Comment by sanjay-sol** [comment]
Hey @ZeRego , can I work on this issue?
