### ISSUE TITLE
Metrics have wrong info text

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#115]
The metric info text should be {metric type} {dimension name}. Currently we are showing the dimension info text instead of its name.

**Displayed:** count of This is a unique identifier for an order
**Expected:** count of order

![Screenshot 2021-06-23 at 11 22 10](https://user-images.githubusercontent.com/9117144/123080934-562b1d80-d415-11eb-8d93-d0981bf748c8.png)

**Comment by owlas** [comment]
@all-contributors add @ZeRego for bugs
