### ISSUE TITLE
rename `results` to `query`. and `visualization results` to just `results`

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11506]
### Description

Right now, the naming of things makes it really hard to talk about the different components in the semantic viewer. 

- we should rename `results` to `query`. 
  - Otherwise, there's the results results table, and the chart results table. It's hard to talk about the chart results table if there's a tab called `results` with a table icon. 
- we should rename `visualization results` to just `results`. 

This will make it so that we can talk about the `query results table` and the `chart results table`. 

...the only thing I'm not sure about is that the button says `run query` on the chart page...will it be confusing that we have another thing called `query`?

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal we can call `query` -> `explore` maybe?
