### ISSUE TITLE
Allow password authentication to be disabled

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1150]

**Comment by ZeRego** [comment]
@owlas Do we want this to be a env var ? or in the UI + DB ?

**Comment by owlas** [comment]
I think env is fine for now until we move all oauth config into the app

**Comment by ZeRego** [comment]
@nathaliabj 
`HealthState` will have a `allowPasswordAuthentication` property we can use to hide: 
- the email/password from the login
- forgot password button 
- the email/password from user create form
- password tab in the user settings modal

We can access the `allowPasswordAuthentication` from the useApp context.
```const { health } = useApp(); ```
