### ISSUE TITLE
If I've closed the sidebar before changing to the chart tab, I have no idea how to configure the chart

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#11518]
(for those using the sql runner for the first time)
1. Open SQL runner
2. Close tables sidebar
3. Write sql and run query
4. Change to chart tab
5. "How do I edit my chart configuration?"

**Comment by magnew** [comment]
Added an improvement here where if the sidebar was close and you switch to viz, the sidebar opens. 

We can potentially further improve the behavior, but I am closing this ticket since the behavior is now different.
