### ISSUE TITLE
Allow google SSO domains to be restricted

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1151]

**Comment by ZeRego** [comment]
@owlas @nathaliabj 
I was thinking about adding a tag input field **Allowed user domains** to the organisation form ( in settings ) where users can define multiple domains. 
We can have the org update route/interface to have a `allowedDomains: string[];`.
On user creation the BE will validate the email domain fro the new user agains the allowed domains. This validation would work for user creation with password+email and SSO.

**Comment by owlas** [comment]
How would the validation work for email+password users? I think we can only reliably do this with Google oauth

**Comment by ZeRego** [comment]
@owlas 

> How would the validation work for email+password users? I think we can only reliably do this with Google oauth

true 🤔  but do you see it being useful once we implement email verification ? Is yes, we could keep the property name generic so can reuse it. 

> If it is just for Google OAuth, then I think we can make this an env var too and restrict to a single domain. What do you think?

Won't this be hard to manage/maintain for cloud beta users ? 
If they are running their own Lightdash instance they will provide the oauth credentials and manage the domain restriction in google settings.

**Comment by owlas** [comment]
> true 🤔 but do you see it being useful once we implement email verification ? Is yes, we could keep the property name generic so can reuse it.

Yep that would work really well!

> hard to manage/maintain for cloud beta

We already have to implement custom env per deployment if the user wants Google OAuth

**Comment by owlas** [comment]
This is temporary until the whole oauth flow can be configured in the UI. I see this as essential when we implement SAML too.
