### ISSUE TITLE
Lightdash PWA

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#11519]
### Description

More on PWA: https://web.dev/explore/progressive-web-apps

Add basic support for PWA with https://github.com/vite-pwa/vite-plugin-pwa.

### What problem does this solve?

Be able to install Lightdash on desktop/mobile device for easy access and fullscreen.

**Comment by varunguleriaCodes** [comment]
Hey @ZeRego I will like to work on this.

**Comment by owlas** [comment]
Closing as not required
