### ISSUE TITLE
Update install script to not use deprecated docker-compose command

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#11532]
### Description

`docker-compose` commands should be replaced with `docker compose` 
We can also remove the check to see if docker-compose is installed and rely just on the docker version. Require them to be on a recent version that support `docker compose`

### Steps to Reproduce the Bug or Issue

1. use install script

### Cloud or self-hosting

None

**Comment by sanjay-sol** [comment]
Hey @ZeRego , Can I work on this ?

**Comment by sanjay-sol** [comment]
Hey @ZeRego ! Can I work on this ?

**Comment by sanjay-sol** [comment]
Hey @ZeRego ! I've updated the `install.sh` file to ensure Docker version 20.10 or higher and removed the `install_docker_compose()`)  .
-  Should I also make corresponding updates in the documentation (`docs/docs/self-host/self-host-lightdash-docker-compose.mdx`)?
