### ISSUE TITLE
the list of time grains should be multi-select (i.e. I can pick many time grains for a single query).

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#11585]
(i.e. I can pick many time grains for a single query).

it only allows one at the moment:

![CleanShot 2024-09-17 at 19 57 04@2x](https://github.com/user-attachments/assets/5c93bc27-46d7-4fb0-9b04-da60c734473f)

**Comment by TuringLovesDeathMetal** [comment]
closing this as nt planned
