### ISSUE TITLE
Automatic table calculations often incorrectly round down to zero

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11586]
### Description

The automated table calculations that have percentage outputs often round down to zero because the inputs are integers (like counts) and for most databases when an integer is divided by an integer, the output defaults to integer. 

One way to fix this is to type cast the inputs as decimals, and another way is to multiply by 1.00 so the output changes to a decimal. 

### Steps to Reproduce the Bug or Issue

1. Use percent of column total built-in table calc on a count metric in a snowflake or redshift database
2. The output will be zeros 

link to internal customer convo with example: https://lightdash.slack.com/archives/C06J189BQCR/p1726593076795699

### Cloud or self-hosting

None

**Comment by rephus** [comment]
@jpetey75 do you have a way to replicate this ? I tried with different integer values on snowflake and I always get a decimal % 

![image](https://github.com/user-attachments/assets/7017c327-dba0-4b48-ab79-7d2265a2319c)

**Comment by TuringLovesDeathMetal** [comment]
Looks like the fix didn't work for Redshift. See user's reply here: https://lightdash.slack.com/archives/C07KT7YVDRN/p1725906164341439?thread_ts=1725906164.341439&cid=C07KT7YVDRN

**Comment by rephus** [comment]
This was fixed for quick table calculations, on all warehouses, documentation was not updated, (they will have to introudce the casting manually)
