### ISSUE TITLE
When adding a filter, move the cursor to the input field

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#11590]
### Description
when you add a filter it would be nice to move the cursor straight to the input field.

- [ ] Optionally, it would be nice you could hit CMD+ENTER to run the query while you are in the input field. (currently it captures the enter key)
### What problem does this solve?

 A very common pattern for usersz is to type a string into the filter, scroll down, hit enter. If the cursor then moved to the input, it would be super clean

**Comment by sanjay-sol** [comment]
Hey @rephus ! Can I work on this ?

**Comment by Josephine19001** [comment]
I will like to work on this

**Comment by chidexebere** [comment]
@ZeRego seems this is no longer an issue because following the screen recording I shared above...except I am missing something
