### ISSUE TITLE
Allow editors and viewers to download CSV of charts with Custom dimensions (view mode)

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#11597]
### Description

IF a user is just an editor, he can try downloading a CSV from a chart with custom dimensions, but then he gets an error. 

![image](https://github.com/user-attachments/assets/21a32288-385e-4643-98bf-d1bc0cf76014)

This is kind of  intended

Instead of disabling the button, we change this endpoint to download the CSV from a savedchart, so a metricquery is no longer required, therefore it is secure. 

Thread: https://lightdash.slack.com/archives/C06H50RC4QH/p1726663782200739?thread_ts=1726662712.886939&cid=C06H50RC4QH

### Steps to Reproduce the Bug or Issue

.

### Cloud or self-hosting

None

**Comment by TuringLovesDeathMetal** [comment]
@rephus what are teh security reasons for why this happens? I would expect that someone would be able to download results if the chart has a custom dimension on it 🤔 (since they're not able to actually edit the custom dimension, so it shouldn't matter, right?)
