### ISSUE TITLE
Error: failed to get diff from dashboard

### ISSUE THREAD

**Issue by bramrodenburg** [lightdash/lightdash#11616]
### Description

An error occurs when a user tries to promote a dashboard that has tiles with the same name.

**Error message:**
```
Failed to get diff from dashboard
There are multiple charts with the same identifier tile1
```

Initially, it was a bit hard for us to figure this out, since some of the tiles had a ' ' (space) as their name. Hence, the error message became like this: `There are multiple charts with the same identifier  `. As a result, we couldn't figure out which charts were duplicates, since the tile name was kind of hidden in the error message.

### Steps to Reproduce the Bug or Issue

1. Create a preview project using the CLI.  
    E.g. `lightdash start-preview —name debug —select tag:lightdash`
2. Create a new dashboard
3. Add a tile with the name “tile1”
4. Add another tile with the same name, “tile1” 
5. Promote the dashboard
6. Once the dashboard is promoted, click Promote dashboard again.
7. The error will now appear: 

<img width="459" alt="Failed to get diff from dashboard" src="https://github.com/user-attachments/assets/732ba650-363f-4d57-a019-7946e5d91292">

### version

v0.1265.1

### Cloud or self-hosting

self-hosting

**Comment by rephus** [comment]
My suggestion is to create a (perhaps recursive) method to see if there are clashes on the slug, and add some sufixes to prevent these on creation.
