### ISSUE TITLE
Slack api/v1/slack/install error 502

### ISSUE THREAD

**Issue by Tonyehd** [lightdash/lightdash#11652]
Checked and double checked all my docker compose environment variables, redeployed and still getting 502 error when clicking the add to slack.  
 
Searched the other issues to no avail.  Thoughts?  Anyone else have trouble deploying slack

**Comment by Tonyehd** [comment]
I am running NGINX proxy manager, self hosted, all env variables are set, running cloudflare proxied [tried turning this off did not fix] I am pulling my hair out.  Cannot find any sources on the internet to help.  Followed the guides, checked multiple times for any errors on lightdash side.  

Anyone have any advice or sources to point me towards?  Thanks in advance.

**Comment by thanhENC** [comment]
I also got this error 
![image](https://github.com/user-attachments/assets/44662d06-882d-44f0-82bd-3838a8372bae)

From Cloudflare, I tried on - off proxy but all of them not work correctly

**Comment by Tonyehd** [comment]
Let me know if you get anywhere with this issue.  I have tried different nginx configs, triple checked my env variables for slack, checked any firewall problems, on off proxy with cloudflare, thought maybe it was slacks bolt NPM package and there was a port that needed to be exposed in the container, nothing I have tried thus far has worked.

**Comment by mwindmark** [comment]
There is a thread about the same issue in the Lightdash Community slack, https://lightdash-community.slack.com/archives/C03MG2VTR08/p1727859635070499?thread_ts=1727308538.100729&cid=C03MG2VTR08

I'm experiencing the same issue and posted the following in that thread.

We are experiencing the same issue that api/v1/slack/install/ returns 502 Bad Gateway . Our slack integration was set up and worked successfully when on 0.1072.3 but then didn't work on 0.1227.0  (and still not on 0.1283.0 with latest 1.5.1 helm chart).

We are running this in k8s and important is that we do see logs in the lightdash-backend pod, see below.

```
2024-10-02 08:56:24 [Lightdash] http: GET /api/v1/projects/c029a714-df5a-439f-a913-834b383bfffd/spaces 304 - 30 ms
2024-10-02 08:56:24 [Lightdash] http: GET /api/v1/slack/ 304 - 3 ms
2024-10-02 08:56:25 [Lightdash] http: GET /api/v1/slack/install/ 302 - 5 ms
2024-10-02 08:56:33 [Lightdash] http: GET /api/v1/livez 200 - 0 ms
2024-10-02 08:56:43 [Lightdash] http: GET /api/v1/livez 200 - 0 ms
```

It therefore doesn't seem like a k8s ingress issue but rather lightdash internal nginx.

**Comment by mwindmark** [comment]
Re-posting my message in slack here too.

---

We debugged this further and found an error log in the k8s ingress controller
```
2024/10/11 08:06:23 [error] 29#29: *8601703 upstream sent too big header while reading response header from upstream, client: 10.0.22.10, server: lightdash.<....>, request: "GET /api/v1/slack/install/ HTTP/2.0", upstream: "http://10.244.2.41:8080/api/v1/slack/install/", host: "lightdash.<....>"
```
We then followed https://www.davidpuplava.com/coding-craft/fix-upstream-sent-too-big-header-error to add ingress annotations. This solved the issue for us.

**Comment by Tonyehd** [comment]
100% great catch, very much appreciated.  While I am not utilizing the k8 ingress controller I am using Nginx Proxy Manager.  Adding to the advanced tab the following allows for the slack integration to load and work.

proxy_buffer_size 256k;
proxy_buffering on;
proxy_buffers 4 256k;
proxy_max_temp_file_size 1024m;
