### ISSUE TITLE
Missing space with slug "(...)" to promote

### ISSUE THREAD

**Issue by ceyzeriat** [lightdash/lightdash#11675]
### Description

I was promoting a dashboard and had a red toast pop-up failure `Failed to promote dashboard -- Missing space with slug "company-kpis" to promote`.
The promotion needed to create the space, the dashboard, and the multiple charts.
Interestingly, the Space got created. A second promotion attempt led to the same error, and creating a duplicate space.

### Steps to Reproduce the Bug or Issue

1. Create a dashboard in a Space, with empty spaces in their names
2. Promote the dashboard where the Space + Dashboard need to be created
3. Error

### version

v0.1269.1

### Cloud or self-hosting

cloud

**Comment by rephus** [comment]
Thanks for creating this issue, I've identified the problem and we will fix it soon.
