### ISSUE TITLE
Incorrect Column Sorting in Pivoted Table

### ISSUE THREAD

**Issue by josemcunha** [lightdash/lightdash#11705]
### Description

When pivoting a table with a string column, a timestamp column (truncated to month), and a numeric column (count distinct), the month column is not sorted correctly after pivoting. Sorting the table based on the month column results in only the first column being sorted, while the remaining columns disappeared. I expected to see all columns (months) ordered by the selected option. We are self-hosting and Snowflake is our database.

### Steps to Reproduce the Bug or Issue

1. Create a table with three columns:
	Column 1: String (e.g., "Category")
	Column 2: Date (truncated to month)
	Column 3: Number (count distinct of a specific field)
2. In the chart area, plot a table and pivot with the following structure:
	Set Column 1 as rows.
	Set Column 2 (Date) as column.
	Set Column 3 as metrics.
3. Observe that the Date columns are not sorted correctly.
4. Sort the Date columns and check how only the first column comes up and the remaining columns (months) disappear.

### version

v0.1273.4

### Cloud or self-hosting

self-hosting

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey Jose

Thanks for opening this issue. 

There's an existing issue for this being tracked here already: https://github.com/lightdash/lightdash/issues/5887

So, I'm going to close this as a duplicate. Please add any comments to the other issue if you think anything is missing!
