### ISSUE TITLE
You can authorize Lightdash to write to your GitHub project

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11719]
### Description

There's an oauth flow in Lightdash that lets Lightdash write to your github project.

**Comment by rephus** [comment]
This was implemented some time ago, avaialable on integrations

[Screencast from 30-09-24 15:57:07.webm](https://github.com/user-attachments/assets/3cd93f50-693d-4424-9a91-8fea53a91858)

It requires the following env variables to work: 

```
GITHUB_PRIVATE_KEY
GITHUB_CLIENT_SECRET
GITHUB_CLIENT_ID
GITHUB_APP_ID
```
