### ISSUE TITLE
Viewing longer markdown dbt descriptions

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1174]
### Description: What is it?

Be able to view longer documentation strings in Lightdash and render markdown documentation

### Problem: What problem does this solve?

For complex columns in dbt, some users have very long description fields, even including markdown tables. In Lightdash today the descriptions only show in a small tooltip, which doesn't render markdown and cuts off long descriptions.

### Acceptance criteria

- [ ] I'm able to click `read more` or `see full description` on description boxes. 
- [ ] doing this opens a modal which shows the description with the markdown formatting. 
- [ ] Maybe descriptions which are longer than say 3 lines are cropped and we show this `read more`/`see full description option`? Instead of trying to show the whole description on hover.
- [ ] \

**Comment by IrakliJani** [comment]
still relevant

**Comment by jpjsonic** [comment]
I think the expansion window is a good approach. The one thing I'd keep in mind with the expansion window is that it's pretty common with markdown to use a header followed by plain text.

For example we use the pattern below frequently for our models at Empora:
```
### Purpose
This table rolls up deals to an order level. The order is an umbrella of the deal. You can have situations where a single real estate transaction can have multiple `deals` rows in our system. 

### Filters
None

### Example Use Cases 
1. Revenue reporting is at the file_number grain, so this is the table to use for revenue-order analysis. 
1. Time series of order cancellations over time.
1. Adding order level dimensions to a dashboard. 

### Maintainers
* Jared
{% enddocs %}
```
When people use the headers it could lead to confusion if only the first line is shown. So maybe what you could do is show lines up until and including the first plain text line. So in this case that would look something like:
```
### Purpose
This table rolls up deals to an order level. The order is an umbrella ...
<expand call to action>
```
