### ISSUE TITLE
Check if user is logged in to GitHub before proceeding with dbt write-back

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#11742]
### Description

Acceptance Criteria
- [ ] When I try to create a custom view via dbt write-back (through GitHub), I am asked to login if I haven't already
- [ ] Once I log in and that's verified, I can see that I can go ahead and write it
- [ ] Once I click Save/Next, it opens a new tab with the Lightdash-generated PR

### What problem does this solve?

Helps users understand what they need to do before going ahead.

**Comment by rephus** [comment]
is this no the same as https://github.com/lightdash/lightdash/pull/11778 ?

**Comment by joaoviana** [comment]
I'm wondering if the user is signed out from GitHub what would happen 🤔 

So they install the GitHub integration then after a while they want to write back to dbt and they're signed out from GitHub, would we ask for a log in or would the integration handle everything for us?

**Comment by rephus** [comment]
The PR is created by the bot, so you don't need to be logged in

Tested on incognito

[Screencast from 07-10-24 10:26:46.webm](https://github.com/user-attachments/assets/ce25e2f7-c545-4b1e-b9b6-797df0779703)
