### ISSUE TITLE
Exploration: figure out what happens if the name of a virtual view changes

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11796]
### Description

If a user changes the name of a virtual view, does it break existing content? 

If yes, we should try to make it _**not**_ break existing content. 

Some ideas:
- we could name models with slugs in the backend e.g. katies-virtual-view-1234
- The new virtual view "name" would just be mapped back to the slug?

**Comment by joaoviana** [comment]
related: https://github.com/lightdash/lightdash/issues/11820
