### ISSUE TITLE
Tables are displayed with 'database' icons

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1182]
### Describe the bug

When we display 'tables', they are shown with icons that represent 'databases'. This is confusing - they mean two different things!!

![Screenshot 2022-01-19 at 16 17 44](https://user-images.githubusercontent.com/12776522/150171207-7104008b-3db3-4329-9ea7-9b8b1e9e0219.png)
(from Tom @ airtasker)
### To Reproduce
View tables in explores page

### Expected behavior

**I expect to see an icon that represents 'tables'. Im not sure which icon to replace it with yet! Any ideas welcome**

**Comment by hamzahc1** [comment]
@PriPatel - is there an icon library to pick from?

**Comment by ZeRego** [comment]
There is a 'table' icon in the blueprint icon list https://blueprintjs.com/docs/#icons

**Comment by PriPatel** [comment]
@hamzahc1 
https://blueprintjs.com/docs/#icons

**Comment by PriPatel** [comment]
ahh yeah thanks @ZeRego 
<img width="69" alt="Screenshot 2022-01-21 at 09 53 43" src="https://user-images.githubusercontent.com/12776522/150506113-69b8553c-f949-49cf-93d4-658dec43c5e2.png">

This is the most straightforward one but still open to other suggestions!

**Comment by PriPatel** [comment]
Another area of impact:
![Screenshot 2022-01-21 at 13 15 45](https://user-images.githubusercontent.com/12776522/150533982-0eb111a0-0348-4ef8-b26d-cc7866ea7e2f.png)


The replacement svg has been sent in slack!
