### ISSUE TITLE
The navigation bar is not intuitive

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1183]
### Description: What is it?

The way that tabs are named means it is not exactly clear where the user should go to do what. This affects discovery. 

Some feedback and some outstanding issues below that can be wrapped into one piece of work. It needs to be looked at holisticaly as this will affect guides and cause evenn more confusion if we keep chopping and changing it all the time. 

### Problem: What problem does this solve?

Navbar should indicate where you are at any given time. #889 
Move settings from modal to new page #542
Update copy/naming for explores #1105
Enable deep linking to each tab in 'Settings' modal. #945
"It took me a while to find out that dashboards  are under the browse menu. I would have expected them under Explore ."
"I wanted to play around with the tables filter. It took me a long time to find the settings page for that"
When you hover over 'dashboards', you should be able to see another dropdown list to select the exact dashboard you wish to view. 

### Audience: Who are we building this for?
Everyone
 

### What: Roughly, what does this look like in the product?

Needs design work and also discussion on naming conventions. We have used 'Looker' terms but that doesnt make it right.

**Comment by TuringLovesDeathMetal** [comment]
This could be related!

https://github.com/lightdash/lightdash/issues/1105

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal - amazing..yes! i will add that to the list
