### ISSUE TITLE
New write back tables will not show on explore if you have filtered tables

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#11841]
![image](https://github.com/user-attachments/assets/6159183e-eb72-413a-99a7-18e0e024bef7)

https://lightdash.slack.com/archives/C07P77EG3KR/p1727882247026169?thread_ts=1727881789.594439&cid=C07P77EG3KR

### Implementation suggestions: 

**Bypass write back table filter**
Have a way to tell lightdash this model was created via write back (perhaps just by checking that the folder is lightdash) and add a flag, like we do on virtual explores, and always show these. 

**or**

**Add filter to new model**
- If `show entire project` : do nothing, it works
- if  `show models with tags`: 
    - on Create PR, add a tag (to the SQL) 
- if `show models in list`
    - on Create PR, add `lightdash` (folder) to the `selected tables`

**Comment by TuringLovesDeathMetal** [comment]
ya, I'm not too sure about the best UX for this. 

Here are a couple more options in my mind:

1. We keep the `created-by-lightdash` tag, then just explain in the docs how to use this to show the tables (most shitty experience)
2. When you create your first table using writeback, we ask you if you want to amend your tables configuration to include your new table in Lightdash. 
  - show entire project, nothing changes
  - show models with tags, we add `created-by-lightdash` tag to the list
  - show models in list, we add the model to this list automatically. 

I'm not sure what would happen though once you've set this up? We'd probably need somewhere to change this in the tables configuration? 

3. Each time you add a table using writeback, we ask if you want to include it in Lightdash to explore. This is the option I'm the least sure about...how would this work with the existing tables configuration? (It would be fine if `show entire project` or `show models in list` was the tables configuration, but if it was `show models with tags`, then this could get tricky...)

^I'd love to chat to some users to see how they would want this to work.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned - it's written up in the docs on how to do this. We can always reopen if another user runs into this issue!
