### ISSUE TITLE
SQL Runner Chart doesn't update when changing SQL

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#11842]
### Description

Chart doesn't update when updating the sql, this is most likely because of react `useQuery` and we need to update the query key

https://github.com/user-attachments/assets/42d0a291-621c-4f79-812a-9c860ae200d2

### Steps to Reproduce the Bug or Issue

1. Write SQL
2. Click "Run Query"
3. Open chart tab
4. Change SQL
5. Click "Run Query"
6. Open chart tab - chart is only updated once you change the chart config

### Cloud or self-hosting

None

**Comment by joaoviana** [comment]
this might be fixed already because of the react-query replacement with a `thunk` @magnew, I think this won't be replicable anymore

**Comment by magnew** [comment]
Yea, this is different now. There might be some opportunity to improve what we have now, but this specific issue is fixed.

**Comment by magnew** [comment]
Actually re-opened after some edge case testing.
