### ISSUE TITLE
SQL runner charts should order on date by default when date is the x-axis

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#11840]
### Description

SQL runner charts should order on date by default when date is the x-axis

### Steps to Reproduce the Bug or Issue

See customer thread here: https://lightdash.slack.com/archives/C075JNX28GG/p1728122264977789

### Cloud or self-hosting

cloud

**Comment by TuringLovesDeathMetal** [comment]
Closed by https://github.com/lightdash/lightdash/pull/12572
