### ISSUE TITLE
Pivot Table functionality

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1184]
### Description: What is it?

You should be able to add dimension groups as columns instead of having groups as a second row dimension.

So, you should be able to `pivot` on a dimension so that instead of the values appearing as rows, they appear as columns in the results table. 

### Problem: What problem does this solve?

Scanning through grouped data as rows is more difficult than looking at it as columns. 

### (Optional) Why: How do we know this is a real problem and worth solving?

https://getdbt.slack.com/archives/C026WJE4A69/p1644794904784429
lots of feedback from users

### Success: How will we know if we’ve solved this problem?

- You're able to pivot the results in your table using a dimension. 
- You can order your pivoted dimensions
- You can add multiple pivoted dimensions 

### Audience: Who are we building this for?

Data builders: specifically people analyzing the values in teh results table. 

### What: Roughly, what does this look like in the product?

When you have dimensions in your table, you should be able to interact with them to pivot them (similar to how users can order by results now)

![image](https://user-images.githubusercontent.com/31848148/154244445-e3cc727e-9b07-4cc1-b04f-4528037f86e7.png)

![image](https://user-images.githubusercontent.com/31848148/154244361-f8ed12a0-0c05-4de3-8979-0d528a3f627f.png)

**Comment by PriPatel** [comment]
@djayatillake This was requested by someone in dbt slack last week for the first time but I didn't manage to get much detail from them! Any thoughts on the questions in the template are welcome!!

**Comment by djayatillake** [comment]
This is really exactly the same feature as in Looker where you can choose one or more dimensions to spread horizontally rather than vertically as default. It should affect the viz too when applied.

As opposed to a separate pivot table.

**Comment by colin-nayuta** [comment]
+1 on this one, a basic feature for any data visualisation.

example:

[https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/tables/orders[…]order_date_week%2Corders_unique_order_count%2Corders_status](https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/tables/orders?dimensions=orders_order_date_week%2Corders_status&metrics=orders_unique_order_count&sort=%5B%7B%22fieldId%22%3A%22orders_order_date_week%22%2C%22descending%22%3Atrue%7D%5D&limit=500&column_order=orders_order_date_week%2Corders_unique_order_count%2Corders_status)

can I pivot the Order Status and also get the total sum on a row? (just like pivot table?)

**Comment by TuringLovesDeathMetal** [comment]
> Can you filter on a pivoted column?
Yes, pivoted columns are just like any other dimension, they're just viewed differently in the results table. (i.e. along the top, instead of vertically like we currently force you to show dimensions)

> Can you sort on a pivoted column?

Yes, again, they should be like any other dimension, they're just viewed differently in the results table.

Other question from me:
> Can you pivot by dimensions and metrics?
I say no, you can only pivot by dimensions.

**Comment by JohnRomanski** [comment]
As a longtime (5+ year) user of Looker, I can tell you that the reason that we chose Looker was Pivot tables. As someone who has been looking for an alternative to Looker, I can tell you that any tool without Pivot tables is not an option for us to migrate to.

If you want to make Lightdash into 'Looker without the price tag', pivot table functionality is crucial. It is the most important missing component from the tool today. It's the table stakes, it's what people taking the demo for a test drive will look for first.

As an added benefit, choosing to develop this feature will make the answer to many other questions obvious, like #968, or "what do we do about the group in your chart configs?"

I don't understand how the group in the chart configs works or what it is supposed to do. I looked in the docs, but don't see any explanation of it there. (and I looked https://docs.lightdash.com/guides/visualizing-your-results#configure-your-bar-line-and-scatter-charts) I get the sense that Group might not be necessary and might be replaced by Pivot.

**Comment by Martin-Carlsson** [comment]
This is still relevant

**Comment by owlas** [comment]
This issue is getting split into 3 separate issues, I'm not going to close this until we close #2905 so subscribers aren't mislead!

1. Pivoting the table visualisation (in order to have pivot tables on dashboards + saved charts) (https://github.com/lightdash/lightdash/issues/2905)
2. Pivoting the results (explorer) table, to interact with pivot results when building charts (https://github.com/lightdash/lightdash/issues/2906)
3. Pivoting API - allowing for better control of pivot sort orders and table calculations (https://github.com/lightdash/lightdash/issues/2907)
