### ISSUE TITLE
When I hide a field in table chart types, the field should appear to be disabled.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#11869]
<img width="362" alt="Screenshot 2024-10-09 at 17 12 53" src="https://github.com/user-attachments/assets/cbcd91ee-1afb-4831-9ed6-e4d2445bae02">

Right now, it still looks active

- [ ] When I hide it, it should be disabled and I shouldn't be able to rename it (it feels misleading)

**Comment by Ankush263** [comment]
Hello @PriPatel , I have made the changes, and now it should look like this (with `not-alowed` cursor)
![Screenshot (159)](https://github.com/user-attachments/assets/76120452-f3b9-4175-8016-c15948062add)
I'll raise a PR.
