### ISSUE TITLE
403 error when running `lightdash preview` with org member and project admin

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#11876]

**Comment by LauriLanni** [comment]
I strongly think project previews is a functionality that should be given to the project developers, not just admins. It is a core part of the Lightdash development flow

**Comment by almeidabbm** [comment]
> I strongly think project previews is a functionality that should be given to the project developers, not just admins. It is a core part of the Lightdash development flow

Hello @LauriLanni 👋 

Thank you for sharing your feedback, we've just created a ticket to do this: https://github.com/lightdash/lightdash/issues/11881
