### ISSUE TITLE
Add video on how to setup Lightdash locally

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1187]
### Which docs do you want to update?

https://docs.lightdash.com/get-started/setup-lightdash/install-lightdash#deploy-locally-with-our-installation-script

### What needs updating?

We should add a video showing how to setup Lightdash locally. We get a lot of support requests about things that aren't clear and we think that following a short video could make this easier to follow along.

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal If we added the video from this issue -  https://github.com/lightdash/lightdash/issues/1010, would that work or do we need more?

**Comment by ZeRego** [comment]
@hamzahc1 we should probably wait for this PR to be merged and released https://github.com/lightdash/lightdash/pull/1193 since it is related
