### ISSUE TITLE
Project developers should be able to create preview projects

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#11881]
Currently a user needs to be `admin` of a project to be able to create `preview` project when having `member | viewer` organization role.

`developers` and higher should also be able to create preview project when they have `member | viewer` organization roles

_Originally posted by @LauriLanni in https://github.com/lightdash/lightdash/issues/11876#issuecomment-2404857485_

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of: https://github.com/lightdash/lightdash/issues/11318
