### ISSUE TITLE
changes to exit explore view modal

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11905]
### Description

**I think Priyanka is making changes to these here: https://github.com/lightdash/lightdash/issues/11892, so catch up with her before picking this up!**

![image](https://github.com/user-attachments/assets/6167c193-1e86-4da9-9f6a-df08ccd13820)

Can we adjust the copy a bit so it’s clear that I’ll be losing changes to my chart? Maybe something like: 

Header: `you have unsaved changes.`
Body: `Are you sure you want to leave this page? Changes you've made to your query will not be saved.` 

Also, is the button meant to be orange here? I don't think we use orange anywhere else, normally we use grey, right? 

can we reuse existing modals that we have here?

**Comment by joaoviana** [comment]
Chatted with @PriPatel and for this one, making the copy changes as suggested above ⏫  and changing the orange button to red will be sufficient. The modal used when discard a dashboard change isn't optimal and this one is actually more consistent

![Image](https://github.com/user-attachments/assets/9f029ac2-3c85-4099-aa3e-1aff807d3755)
