### ISSUE TITLE
Editing the title of the virtual view doesn't match the title in edit mode

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11907]
### Description

I can edit the title of the virtual view, but the old title re-appears in edit mode if I reopen it: 

### Steps to Reproduce the Bug or Issue

https://www.loom.com/share/6fbdc635ae0f438fb8f9b898c9d1ebea

### Cloud or self-hosting

None

**Comment by nakul-py** [comment]
hi @TuringLovesDeathMetal  i reads this issue , now tell me what you want in expected result
