### ISSUE TITLE
You should be able to delete saved charts from within the Explore page

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1190]
### Description: What is it?

In the Explore page of a saved chart, there should be the option to `delete` chart in teh chart settings:
![image](https://user-images.githubusercontent.com/31848148/150381505-eb3a4e64-deef-486c-8e3c-87209b0cc8b6.png)

### Problem: What problem does this solve?

It's annoying to have to go back to the saved charts list to delete a chart. 

### Success: How will we know if we’ve solved this problem?

You're able to delete a saved chart within the Explore view.

### Audience: Who are we building this for?

People who are building charts + maintaining their Lightdash project contents

### What: Roughly, what does this look like in the product?

I'd imagine this would exist as another option in the drop-down menu in the chart space: 
![image](https://user-images.githubusercontent.com/31848148/150381714-958d9497-6bf3-4380-86a2-bcb1d2195588.png)

**Comment by bartfoltyn** [comment]
can i take this issue>

**Comment by ZeRego** [comment]
Hi @bartfoltyn yes, go for it :) 
Note that we should display a modal to confirm deletion.

**Comment by PriPatel** [comment]
You can use the same "Delete" item as the one on the Saved Charts page for now. It should behave in the same way and show the same warning modal. 
![Screenshot 2022-04-05 at 12 44 22](https://user-images.githubusercontent.com/12776522/161746757-bc56eed2-8415-4bb3-a5cf-10c1bb8a1027.png)
.
