### ISSUE TITLE
loading state for validation jumps after query executed

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11906]
### Description

the loading state for validating edits in the virtual view feels a bit jumpy.

 I think this is because we load the results from the new query executed before we run the validation? (so it almost looks like it’s validating twice). 

Can we **_not_** load the results from the new query execution on the **_frontend_** when we run the validation? (I think it will make it look less jumpy/confusing that the screen is loading something new on validation). So, the process would be:

- click `validate`
- loading state shows `validating...blah blah`
- in the background, the query re-executes 
- we _**don't**_ show the results on the frontend (in case they change, this causes a weird jump)
- we _**keep**_ the validator spinner going as we go to the next validation step (actualyl validating the query)

https://www.loom.com/share/502a52037ddf44c197209800d2e67be2

**Comment by joaoviana** [comment]
This has been resolved with the changes applied in: https://github.com/lightdash/lightdash/pull/11874
