### ISSUE TITLE
I would like to be able to have 2 series one on the left and one on the right axis

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#11925]
Blocked by: https://github.com/lightdash/lightdash/issues/11939

### Description

![image](https://github.com/user-attachments/assets/7703330a-2365-48af-a723-fdc778382509)

**Comment by joaoviana** [comment]
Blocked by #11611

**Comment by magnew** [comment]
Blocked by #12286

**Comment by hamzahc1** [comment]
if this is blocked - do you want to move it back and work on the blocking ticket instead?
