### ISSUE TITLE
The users list when you're managing access to spaces should be paginated

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12006]
### Description

right now, it breaks if you have lots of users (the modal doesn't even load)

**Comment by Guru6163** [comment]
@TuringLovesDeathMetal  - Do you mean, this user list?
<img width="988" alt="image" src="https://github.com/user-attachments/assets/9edd2b2a-4b87-4316-97df-a23178634c2d">

**Comment by almeidabbm** [comment]
> [@TuringLovesDeathMetal](https://github.com/TuringLovesDeathMetal) - Do you mean, this user list? <img alt="image" width="988" src="https://private-user-images.githubusercontent.com/42559222/379888030-9edd2b2a-4b87-4316-97df-a23178634c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTI1NzgsIm5iZiI6MTcyOTg1MjI3OCwicGF0aCI6Ii80MjU1OTIyMi8zNzk4ODgwMzAtOWVkZDJiMmEtNGI4Ny00MzE2LTk3ZGYtYTIzMTc4NjM0YzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEwMzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNWM4NWI2OTA0YTA5NzhiZjk3Y2FiNzcwMGEyYmE2NGU0MjFjOWE1YjE1MTQ1MWIwYTZjOWM2ZDNmMzEwM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mvm5CDakykx-9ZINQNipPnSTOXo3BhPMF0zl5pQ9iyw">

Hi @Guru6163 👋 

This issue is to fix the user list for space access management (see screenshot below), we have created an [issue](https://github.com/lightdash/lightdash/issues/12098) to apply the same pagination to the search bar filters!

**Comment by Guru6163** [comment]
@almeidabbm , Can I get access to anyother shop, cause in my "Jaffle Shop", I dont see much users.
If i can see the problem/issue - I can try to fix it
