### ISSUE TITLE
I can't save a chart from the SQL runner if there is only one column included

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12007]
### Description

Charts from the SQL runner are not able to be saved when there's only one column of data

### Steps to Reproduce the Bug or Issue

https://www.loom.com/share/df1c64d645ce4553af339e6d33c36fbe

### Cloud or self-hosting

None

**Comment by magnew** [comment]
Closing as a duplicate of #13013
