### ISSUE TITLE
mysql or mariadb connection

### ISSUE THREAD

**Issue by generalistcodes** [lightdash/lightdash#1203]
###  How to add the mariadb/mysql?
Is there something I can do to temporarily connect to my local mysql and use it as my dbt?

**Comment by owlas** [comment]
Hey @generalistcodes thanks for raising this feature request! 

There's nothing that can be done until we add a connector. 

You can drop a vote in the poll for mysql too! https://github.com/lightdash/lightdash/discussions/1112

**Comment by owlas** [comment]
@all-contributors add @generalistcodes for ideas

**Comment by dakshlohar1** [comment]
Hello!
Is there any update on this ?

**Comment by dakshlohar1** [comment]
If anyone has done any research, please share what are the challenges in it. Thanks!

**Comment by TuringLovesDeathMetal** [comment]
Hey @dakshlohar1! I think the only challenge here is time from the team,

We're only 3 engineers, so we have to make a lot of tricky prioritization decisions. Right now, a mysql connection isn't at the top of the list.

We'll keep in mind that it's really important for you and we'll update you once we've picked it up!

**Comment by 12ian34** [comment]
Note that since adding support for [Trino](https://docs.lightdash.com/get-started/setup-lightdash/connect-project#Trino) recently, we can suport MySQL users if they use Trino as a conduit.
