### ISSUE TITLE
"Email already in use" when authenticating with Okta

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#12036]
### Description

User is authenticating with Okta and experiencing an error "Email already in use"

Relevant information in the slack thread: https://lightdash.slack.com/archives/C03MCQ08UKS/p1729508024657139

### Steps to Reproduce the Bug or Issue

-

### Cloud or self-hosting

None

**Comment by Chris20241024** [comment]
![Capture](https://github.com/user-attachments/assets/79384520-59eb-4c54-95e3-15db1203fb0b)
Hi, dear sir. the error still occurs when trying to login with your email at https://collectors.lightdash.cloud/login

Please help with it. Thank you and have a good day.

**Comment by IrakliJani** [comment]
these errors might be relevant

https://lightdash.sentry.io/issues/6015576011/?alert_rule_id=9333608&alert_type=issue&environment=cloud_beta&notification_uuid=63ddd766-796e-4dd0-b1f1-baeea4bc06df&project=5959292&referrer=digest-slack

https://lightdash.sentry.io/issues/6015576011/?alert_rule_id=9333608&alert_type=issue&environment=cloud_beta&notification_uuid=63ddd766-796e-4dd0-b1f1-baeea4bc06df&project=5959292&referrer=digest-slack

**Comment by rephus** [comment]
Changed the `AUTH_ENABLE_OIDC_TO_EMAIL_LINKING` in the pod
