### ISSUE TITLE
SSL - Cannot connect to DigitalOcean Database Cluster

### ISSUE THREAD

**Issue by ab3llini** [lightdash/lightdash#12039]
### Description

DigitalOcean Database Clusters of type PostgreSQL enforce `sslmode=require`, and provide a certificate that must be used to authenticate.

There is no way whatsoever to provide such certificate in lightdash - I only managed to append the certificate to `ca-bundle-aws-rds-global.pem` and make lightdash connect to my db locally, but once the project get successfully created on lightdash cloud, of course nothing works as the deployed version contains bundled certificates that do not work.

<img width="454" alt="image" src="https://github.com/user-attachments/assets/7468c010-8b79-4901-8108-422f0cb1eb71">

[This problem was first observed more than 2 years ago](https://github.com/lightdash/lightdash/issues/1816)

### Steps to Reproduce the Bug or Issue

1. Register a digital ocean account
2. Create a database cluster of type postgres
3. Try to use lightdash with such database 

### version

0.1309.3 

### Cloud or self-hosting

cloud

**Comment by ab3llini** [comment]
Apparently I just needed to set the SSL option to `no-verify`. Apolgoies

**Comment by z333d** [comment]
@ab3llini could you share the method about set the SSL option to no-verify? is it a setting in digitalocean? thanks

**Comment by ab3llini** [comment]
> @ab3llini could you share the method about set the SSL option to no-verify? is it a setting in digitalocean? thanks

It is a parameter you set when connecting to your DB through your client, which is either lightdash CLI or the Web UI. 
In both cases, you need to set it to `no-verify` (even though DigitalOcean does not reccomend it)

**Comment by z333d** [comment]
@ab3llini could you share about how to config this parameter when using lightdash CLI? I have tried these command but not work:
`PGSSLMODE=no-verify lightdash deploy --create`
`lightdash deploy --create --sslmode=no-verify`
`lightdash deploy --create no-verify`
thanks
