### ISSUE TITLE
'Add' button when adding saved charts to a dashboard should be disabled when I haven't selected anything yet.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12048]
<img width="662" alt="Screenshot 2024-10-23 at 15 22 50" src="https://github.com/user-attachments/assets/ea041928-6088-420a-bfbb-eda5de95eb9a">

Right now, it allows me to hit 'Add' and then the modal disappears and nothing happens. Its quite confusing. 

- [ ] The button should be disabled until a chart has been selected

**Comment by Guru6163** [comment]
Can I get this task assigned to me?

**Comment by Guru6163** [comment]
@IrakliJani  @PriPatel Where can I see this in the webapp?
