### ISSUE TITLE
Column name with number character not rendered correctly in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1204]
### Describe the bug

I have a column name: `has_more_than_1_user_in_org` which, when rendered in Lightdash becomes `has more than user in org`

### To Reproduce

Create a column with a number character split by two `_` and no letters (e.g. `test_1_` or `test_7_`)

### Expected behavior

`has_more_than_1_user_in_org` should be rendered as `has more than 1 user in org` in Lightdash.

### Screenshots or Loom video

![image](https://user-images.githubusercontent.com/31848148/150754452-7bd3558a-fc7c-41e5-b570-103da6435d71.png)
![image](https://user-images.githubusercontent.com/31848148/150754488-6dffbdf5-e857-46a2-b75c-22353da7bd09.png)

**Comment by ZeRego** [comment]
Fixed

```
      - name: test_1_number
```
<img width="390" alt="Screenshot 2022-06-08 at 16 31 11" src="https://user-images.githubusercontent.com/9117144/172657044-ad96d93a-9778-4d31-b1c7-18efb6fa5a5f.png">
