### ISSUE TITLE
There should be a `scroll` in the users list in the global search

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12066]
### Description

The list of users has no option to scroll (so you can't scroll through the list of users in the filter)

**Comment by Guru6163** [comment]
@TuringLovesDeathMetal - Fixed Height with scroll feature?

**Comment by Guru6163** [comment]
I have fixed the issue - maybe you can assign it to me @TuringLovesDeathMetal
