### ISSUE TITLE
analytics for scheduled deliveries time zones

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12075]
### Description

- add `time zone` parameter to `scheduler_created`, `scheduled_updated` events which is in the format like `(UTC - 4:00) - America Los Angeles` 
- add new event `default_project_time_zone_updated` which is triggered when the default proejct time zone is updated. 
  - user_id
  - organization_id
  - project_id
  - time_zone  (like `(UTC - 4:00) - America Los Angeles` )

**Comment by rephus** [comment]
@TuringLovesDeathMetal we decided to not update the timezone at the project level (yet),  this is only for schedulers. So I'm renaming the  event to `default_scheduler_time_zone.updated` FYI


![image](https://github.com/user-attachments/assets/f9b17680-88e7-47c1-95d1-684aee96e5cf)
