### ISSUE TITLE
When you finish editing a saved chart from within a dashboard, you should be redirected to the dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1208]
### Describe the bug

When you click `edit chart` from within a dashboard, then you finish editing the chart, you don't get redirected to the dashboard you were working on. 

### To Reproduce

https://www.loom.com/share/98e93f664da649289ae366e0d24fac1f

### Expected behavior

Once you've finished editing your chart and clicked `save`, you should automatically be redirected to the dashboard you were working on, in edit mode. 

And the updated chart should be re-loaded in the page.

**Comment by ZeRego** [comment]
> Once you've finished editing your chart and clicked save, you should automatically be redirected to the dashboard you were working on, in edit mode.

Should we have a breadcrumb somewhere instead of automatically redirecting the user? 
I'm the kind of person that saves multiple times my work so that behaviour would be annoying to me.
And could we go back to the same view/edit mode when the user left the dashboard?

**Comment by rephus** [comment]
ok, how about this @TuringLovesDeathMetal @ZeRego  
- If you click Cancel , it automatically redirects back to dashboard
- if you click save, you can click `go to dashboard` on the `saved chart` toast. but it will not redirect automatically.

Breadcrums are great, but I think we need design for it, so out of scope.
