### ISSUE TITLE
Paginate users list in global search filters

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#12098]
> @TuringLovesDeathMetal  - Do you mean, this user list?
> 
> <img width="988" alt="image" src="https://github.com/user-attachments/assets/9edd2b2a-4b87-4316-97df-a23178634c2d">
> 
>  

 _Originally posted by @Guru6163 in [#12006](https://github.com/lightdash/lightdash/issues/12006#issuecomment-2436042775)_

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - I don't think we want pagination in drop-down lists...just search. (they scroll, so I think that it's fine because they don't all load at once - which is what's breaking the other lists at teh moment)
