### ISSUE TITLE
Add support for Azure DevOps repos

### ISSUE THREAD

**Issue by 2rara** [lightdash/lightdash#1214]
### Description: What is it?

Azure DevOps repos are not supported in Lightdash today.

### Problem: What problem does this solve?

That dbt repos on Azure DevOps cannot be connected to Lightdash

### (Optional) Why: How do we know this is a real problem and worth solving?

Some dbt repos are on Azure DevOps.

### Success: How will we know if we’ve solved this problem?

By seeing Azure DevOps in the list of supported repository types, and one can complete a dbt-Lightdash connection with the option.

### Audience: Who are we building this for?

People who have a dbt repo on Azure DevOps and want to use/try Lightdash for it

### What: Roughly, what does this look like in the product?

Same as other available options, like GitHub

**Comment by owlas** [comment]
Hey @2rara this should be a quick fix! 

Do you have any examples of an Azure DevOps configuration page that you've used in another tool? Something that you've enjoyed using? We can use that to inspire our own design

**Comment by owlas** [comment]
@all-contributors add @2rara for design

**Comment by owlas** [comment]
@all-contributors add @2rara for ideas

**Comment by 2rara** [comment]
> Hey @2rara this should be a quick fix!
> 
> Do you have any examples of an Azure DevOps configuration page that you've used in another tool? Something that you've enjoyed using? We can use that to inspire our own design

That's great to hear :)
Thank you for your prompt action.
I'm afraid I cannot really provide a good example here, simple because I haven't touched DevOps from outside (except VS Code, but it's in sort of the same ecosystem).
