### ISSUE TITLE
Show error when Lightdash can't find the git repository

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#12150]
### Description

Current error message doesn't help the user to fix the problem when the git repository can't be found. 

### Steps to Reproduce the Bug or Issue

1. update project with wrong git repository url
2. try to save / refresh dbt

Expected:
See error `Could not find Git repository name_of_git/repository. Check that your personal access token has access to the repository and that the repository name is correct.`

Actual:
See error `Something went wrong`

### Cloud or self-hosting

None

**Comment by rephus** [comment]
I can't replicate this exact error message , if I type the wrong repo, I get this  error message

![Screenshot from 2024-11-08 11-14-30](https://github.com/user-attachments/assets/3b69053c-66f4-4b96-a78c-627a4a1854a8)
