### ISSUE TITLE
add monitoring for posthog and investigate issues

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12164]
### Description

the nginx proxy for posthog, which was throwing SSL issues 

### Steps to Reproduce the Bug or Issue

see slack thread here: https://lightdash.slack.com/archives/C03MCQ08UKS/p1730275775302379?thread_ts=1730221951.112629&cid=C03MCQ08UKS

### Cloud or self-hosting

None

**Comment by rephus** [comment]
Fixed here https://github.com/lightdash/posthog-nginx-proxy/pull/2
