### ISSUE TITLE
I want to give access to a user on a space who belongs to a group

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#12179]
### Description

IT looks like `member org users`  who are not directly added to a project, but they have `view` access via a group, don't appear on the `user list` when sharing a space

### Steps to Reproduce the Bug or Issue

What I think is happening (needs to be confirmed) 

1. have a member user in an org
2. assign this member to a group
3. give view access to the group to the project
4. create a private space
5. try to find the user in the space

### Cloud or self-hosting

None

**Comment by TuringLovesDeathMetal** [comment]
related to https://github.com/lightdash/lightdash/issues/3273 and https://github.com/lightdash/lightdash/issues/1659

**Comment by TuringLovesDeathMetal** [comment]
I wonder if there's a way to make this flow more obvious? The "flow" being: "you can give a group access to only a space without giving them access to anything else in the project"
