### ISSUE TITLE
Page and container

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12181]
https://www.figma.com/design/AFhGBAKR4kreLZR5uqaSKE/Metrics-Catalog-V1?node-id=0-1&node-type=canvas&t=ybqIEApapOmvbe1O-0

### Page
- [x] Background colour: #FAFAFA
- [x] Change width from 1200 -> max-width:1600px
- [x] Change padding to 2.25rem (from 1.25 rem)

### Page Header
- [x] Add icon (blocked)
- [x] Change styling of Metrics Catalog
- [x] Add subheading (Browse all Metrics & KPIs across this project)
- [x] TBC Refresh button (blocked)
- [x] Respect spacing between top and bottom of header

### Table container
- [x] Change height (lets play on render or ngrok lol) 
- [x] Respect border radius
- [x] Respect padding in container
- [x] Respect border colour and dropshadow
Just a thought: I dont know if it makes snese to tackle this ticket at the same time https://github.com/lightdash/lightdash/issues/12394

### Table header
- [x] Styling of search bar
- [x] Styling of All categories (and all states) eg.. hover and active
- [x] Styling of 'total number of metrics' (grey badge)

### Column headers
- [x] Respect border colour and stroke
- [x] Add icons to each category
- [x] Respect styling of text (size and colour)
- [x] Respect spacing in each header
- [x] Hover states (colours and resize handle) 
- [x] Sort icons and colours

### Footer
- [x] The line separating the table body from footer should be the right colour a
- [x] Respect text size and styling . 
- [x] Text should appear to be vertically centered in the footer

### Global
- [ ] #12436

Once the above is done , I can give the hover tooltips for each column header!

**Comment by joaoviana** [comment]
opened a separate hover transition ticket, closing this one @PriPatel
