### ISSUE TITLE
I can't create a stacked bar chart without first adding a group then removing

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#12184]
### Description

you can't create a stacked bar chart without first adding a group and then removing it 

### Steps to Reproduce the Bug or Issue

https://github.com/user-attachments/assets/f1e2fe18-f091-459b-b8ea-245976fa47f7

### Cloud or self-hosting

cloud

**Comment by TuringLovesDeathMetal** [comment]
closing this as a duplicate of this ticket: https://github.com/lightdash/lightdash/issues/8701
