### ISSUE TITLE
Filters general: Filtering dates by week/month/year should be easier to understand in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1219]
### Description: What is it?

When a user filters on a date timeframe that's longer than a day, it should be really easy to do in the filters because the dates you can filter on should also be chunked into timeframes. 

### Problem: What problem does this solve?

Right now, if you try to filter by month (for example), it's really unclear what you're actually filtering to include (if I pick the 24th of January, is it filtering until teh 24th of February?)

![image](https://user-images.githubusercontent.com/31848148/150805221-d69b7a57-16fe-4e6f-b5ad-afb379f763ea.png)

### (Optional) Why: How do we know this is a real problem and worth solving?

user feedback saying this was confusing. 

### Success: How will we know if we’ve solved this problem?

It's easy to filter by timeframes. 
We don't get any more user feedback on the usability of filters by timeframes. 

### Audience: Who are we building this for?

Anyone interacting with filters (mostly data builders)

### What: Roughly, what does this look like in the product?

**Week filtering**:
I'd imagine that for week filtering, if you hovered over a date, it would highlight the whole week instead of the single date (indicating the week that you'd be filtering on). Then, the date you're filtering on would always be the Sunday of the week you've selected. (E.g. if I picked wednesday, the 25th of January, my filter would be set to Sunday, the 22nd of January). 

**Month filtering:**
For month filtering, we'd remove the calendar and just have the top part of the calendar with the month + year (and not show you the dates). 
![image](https://user-images.githubusercontent.com/31848148/150806004-89085634-6b7e-4445-9209-729a4def362f.png)

**Year filtering:**
Year would be same as month filtering, but with the month removed too.

**Comment by owlas** [comment]
@ZeRego @TuringLovesDeathMetal - two options I can think of;

1. Disable all days in the picker except for the first day of the month
2. Remove the "date picker" all together and just provide two drop-downs (month + year)

**Comment by TuringLovesDeathMetal** [comment]
For the `month`, I'd remove the "date picker" all together. 

For the `week` I've suggested another option (since I don't think people can think of week numbers without a calendar)

**Comment by ZeRego** [comment]
Breaking this work into 2 PRs. 
Week picker work is in this PR https://github.com/lightdash/lightdash/pull/1309
Month and Year pickers will be done under this ticket.
