### ISSUE TITLE
Timestamp/date fields that are of type "no time zone" should not have their time zone converted

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12206]
### Description

More details in thread here: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1729871127813019

I just switched my date field to a timestamp in UTC, and it's still problematic. Filtering by "last completed 14 days" generates SQL like this: `((DATE_TRUNC('DAY', TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('UTC', "orders".placed_on)))) >= ('2024-10-17') AND (DATE_TRUNC('DAY', TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('UTC', "orders".placed_on)))) < ('2024-10-31'))`

So now the date comparisons are midnight UTC.

Furthermore, the dates output in the UI are still being misreported.

`DATE_TRUNC('DAY', TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('UTC', "orders".placed_on))) AS "orders_placed_on_day"`, is truncating the date to `00:00:00` but the UI is still applying a timezone correction. So the dates are shifting back 1 day.

### suggested solution

- [ ] we should not convert timestamp/date fields that are of type "NTZ" (i.e. have no time zone). Instead, we should just query them without converting to UTC. 

- [ ] We would also need to change filters for this to work. i.e. if I have an NTZ field, and I apply a filter to it, the filter should not be in UTC (it should just be NTZ as well).

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal is this still important or do we want to move it off the board for now?

**Comment by TuringLovesDeathMetal** [comment]
@hamzahc1 yes - it was at the bottom because Oliver needed to look into it. We've chatted here: https://lightdash.slack.com/archives/C04E1CCKN64/p1731329111412789

Closing this in favour of this issue: https://github.com/lightdash/lightdash/issues/2945
