### ISSUE TITLE
Investigate explores not being available when syncing DBT

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#12227]
### Description

We've had two customers this week report errors refreshing DBT. Both saw an error in the LD UI saying `Explore <explore_name> does not exist`. Both resolved themselves on subsequent runs. 

Notably, the database persists the status of RUNNING for those jobs, which probably indicate they timed out in some way. 

This ticket is to figure out what might be causing this. 

Internal threads with more details:
https://lightdash.slack.com/archives/C03MCQ08UKS/p1730480731441839

https://lightdash.slack.com/archives/C047XUL7QAZ/p1730392673478779

### Steps to Reproduce the Bug or Issue

See threads

### Cloud or self-hosting

None

**Comment by hamzahc1** [comment]
We believe we've resolved one of the major issues here - closing for now.
