### ISSUE TITLE
The title size in a markdown tile should be H1 or H2 (not H3)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1229]
### Description: What is it?

The title size in a Markdown file should be at least H2. 

### Problem: What problem does this solve?

The fontsize of the titles in markdown tiles are really tiny right now. I actually hack this by just adding a `space` to the title section, then using the header 1 in the markdown part of the tile to get a bigger heading. 

### (Optional) Why: How do we know this is a real problem and worth solving?

I run into this _**every time**_ I write a markdown tile. 

### Success: How will we know if we’ve solved this problem?

The default markdown tile title size is bigger than H3

### Audience: Who are we building this for?

Data builders/people building dashboards

### What: Roughly, what does this look like in the product?

By default, the title should be bigger.

**Comment by TuringLovesDeathMetal** [comment]
Note: if you're working on this, there's another markdown tile issue here: #912

**Comment by ZeRego** [comment]
But do we want to change all the tiles titles as well ? I know @PriPatel has plans to change the tiles header.

**Comment by hamzahc1** [comment]
@ZeRego is this a very quick fix to change the title to default to H1 or H2 rather than H3?

**Comment by hamzahc1** [comment]
H2?

**Comment by TuringLovesDeathMetal** [comment]
Close in favour of #912
