### ISSUE TITLE
Create docs for the AI Analyst

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12307]
- Create v1 of the AI analyst docs (including what's already in the notion doc we have) 
- 

to update: https://docs.lightdash.com/references/slack-integration#ai-bot-channel-mappings

**Comment by IrakliJani** [comment]
notion for onboarding: https://www.notion.so/lightdash/Lightdash-AI-Copilot-Beta-3a1713dc2c354c8cb8579a5d4b65c5d6
