### ISSUE TITLE
Production docker compose doesn't work with SQL runner by default

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#12313]
### Description

The production version of docker compose exposes the Lightdash app on port 8080 by default, but the SITE_URL in the default `.env` is 3000. This causes a problem for the SQL runner which uses port 3000 to try to fetch results, causing an error. It's also confusing since the default `SITE_URL` env variable doesn't work. 

### Steps to Reproduce the Bug or Issue

1. Clone lightdash
2. Run the docker compose command suggested by our docs: `docker compose -p lightdash-app -f docker-compose.yml --env-file .env up --detach --remove-orphans`
3. Try to access `localhost:3000` (the site url specified in env), connection refused
4. You can access the app at `localhost:8080`
5. Run a query in SQL runner, fail

We should update the default SITE_URL to match the production port. 

### Cloud or self-hosting

None

**Comment by owlas** [comment]
We shouldn't change the production port, it's relied on by everybody self hosting, isn't the fix to update the `.env` file to use the correct port 8080 in prod?

**Comment by magnew** [comment]
> We shouldn't change the production port, it's relied on by everybody self hosting, isn't the fix to update the `.env` file to use the correct port 8080 in prod?

Correct. Description updated.
