### ISSUE TITLE
Handle expired GitHub tokens

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1233]
### Describe the bug

When GitHub tokens expire an error message appears showing the token and that password is not valid. This is because the token expires.

### To Reproduce

Compile dbt project with an expired GitHub token

### Screenshots or Loom video

<img width="1534" alt="Screenshot 2022-01-25 at 12 04 36" src="https://user-images.githubusercontent.com/11660098/150973978-64803a57-ce3a-466e-9942-f4be000db6f0.png">

**Comment by ZeRego** [comment]
We could catch this error in the BE and return instead `Personal token wasn't recognised or expired.`
