### ISSUE TITLE
Add documentation on how to setup google authentication

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1242]
### Which docs do you want to update?

SSO settings and auth settings

### What needs updating?

Add page on how to enable Google SSO and disable password authentication

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego is this part of the auth settings?

![image](https://user-images.githubusercontent.com/31848148/152510893-fac533ff-4ca9-4c1f-9257-df7ad2f887d6.png)

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 
Not only the google auth but also for email/password credentials. Right now it is redundant for the email/password since we haven't implemented email verification. We can omit that part from the docs or create a ticket for that and add a note in the docs 🤔

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego so to set up oauth, you don't need to do anything here?

Also, which settings tab do I go to for setting up oauth? (I can't find it... 😅 )

**Comment by ZeRego** [comment]
> @ZeRego so to set up oauth, you don't need to do anything here?
No. This is extra security.

> Also, which settings tab do I go to for setting up oauth? (I can't find it... 😅 )
It cannot be set via the UI. To enable Single Sign-on with Google the user will need to:

- [Create a Google OAuth Client ID](https://console.cloud.google.com/projectselector2/apis/credentials) is their GCP account
- Pass two environment variables to the app:`AUTH_GOOGLE_OAUTH2_CLIENT_ID` and `AUTH_GOOGLE_OAUTH2_CLIENT_SECRET`

They can then disable the email/password authentication, if they want, by setting the following env var:

```AUTH_DISABLE_PASSWORD_AUTHENTICATION=true```

**Comment by TuringLovesDeathMetal** [comment]
Sweet, I might leave this doc for an engineer to take on when they have some time 🙃

**Comment by TuringLovesDeathMetal** [comment]
Clsoing this - I'm assuming this isn't relevant any more since it's been about 1.5 years since we last interacted with it.
