### ISSUE TITLE
Add worker/job execution context to logs

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#12420]
Every log from the workers should include:
- worker id
- job id

Must log when the job starts and is finished by the worker

Following logging levels (https://www.notion.so/lightdash/Logging-and-debug-code-743e6b9e8a77462a85cfca0c6b644a49) this should be an INFO level (to show in production)

**Comment by ZeRego** [comment]
Let's add an execution context similar to how Sentry works.

When a job starts, we add the worker Id, job Id, etc to the context which can be used in the packages/backend/src/logging/winston.ts

Lib to facilitate this:
https://www.npmjs.com/package/node-execution-context

We can also add a context for the API, so all the logs can be related to an endpoint call.
