### ISSUE TITLE
Allow permissions to be assigned to groups of users

### ISSUE THREAD

**Issue by scarrucciu** [lightdash/lightdash#1245]
### Description: What is it?

This is the ability to create a group, add users to that group, and then assign sets of permissions to the group, that would then apply those permissions to the users. This would enable users to not just manage permissions on an individual user basis, but as the user base grows, create groups and manage group permissions and inclusion / exclusion. 

### Problem: What problem does this solve?

This solves the challenges that occur when you get a larger number of users and you would want to update user permissions. If say you wanted to restrict the permission for a dataset for all users who work in operations, without groups you would need to find each user who is in operations and individually update their permissions. With groups, you would assign all of those users to the "operations" group, and then assign and update permissions for the group. 

### Success: How will we know if we’ve solved this problem?

Qualitative: A user has the ability to create a group and assign users.

### Audience: Who are we building this for?

 

The admin who is adding users and updating permissions.

**Comment by TuringLovesDeathMetal** [comment]
Hi again @scarrucciu 👋 

Another great suggestion from you! 

Just wondering, what sorts of permissions are you talking about here? 

We're just about to release basic user roles & permissions (see this issue #1069 ). Would this cover what you're looking for? Or is there something missing from this that you would need?

**Comment by scarrucciu** [comment]
@TuringLovesDeathMetal updated the ticket with a bit more info. For the permissions would want all permissions that can be assigned to an individual users (datasets, apps, etc) be assigned to a group of users. The main benefit is the group construct where you do not have to do individual permissions.

**Comment by TuringLovesDeathMetal** [comment]
@scarrucciu, makes sense!

Right now, we have very coarse permissions (you can only limit who can delete/add users and update the project), but we've started scoping work around creating user groups and how you could add/limit access to things like specific dashboards or specific datasets. 

This sounds like it would fit into there :)

**Comment by scarrucciu** [comment]
Great. This also pairs with #1243 as another type of permission, where you would to be able to set these access controls to work of off some attribute of the group they are assigned to.

**Comment by TuringLovesDeathMetal** [comment]
awesome! thanks for the feedback :)

**Comment by 12ian34** [comment]
A customer via a partner churned - a big concern they had was the lack of this feature

**Comment by ZeRego** [comment]
> Security Related Clarification
> - I added a user as a “Viewer” - in a space - but that user - is able to invite other users. Can we remove that thing?
> - Also, I want to disable - “New Query” and other options of view project settings - for Space Viewer. Is there an option like that
> - I also want to disable - “User Management” - since its leading to un-necessary exposure of information
> - Also, “Table Configuration” - i want to disable for Space Viewers
> - Also, is there a way - I can disable - view - underlying data feature for specific viewers of a Space ?
> 
> I am asking these questions - since i am trying to rollout - Lightdash - org-wide

slack thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1676351898054849

**Comment by TuringLovesDeathMetal** [comment]
This is now resolved! More info in the docs here: https://docs.lightdash.com/references/groups#adding-roles-to-groups
