### ISSUE TITLE
Lightdash shouldn't let you explore if it's going to sign you out

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1248]
### Description: What is it?

Lightdash signs you out automatically but doesn't tell you until you try to run something (then there's an error). There's no way to save what you've done before you have to sign in again. 

Lightdash should force you to sign back in before you start doing any exploring/changing anything so you don't lose your work

### Problem: What problem does this solve?

You can lose a bunch of work if you don't realize you need to sign in until after you've changed a bunch of stuff. 

### Success: How will we know if we’ve solved this problem?

You're forced to sign in before making any unsaved changes to something. 

### Audience: Who are we building this for?

Data builders

### What: Roughly, what does this look like in the product?

It could be that before we force you to sign in again, we save the state. Then we immediately tell you that you have to sign in again (before you do anything else). 

Then once you sign in, it reloads the saved state

**Comment by ZeRego** [comment]
This will be really unlikely to happen with the fix for [Refresh session tokens #280](https://github.com/lightdash/lightdash/issues/280) so I'm closing it.
