### ISSUE TITLE
Spacing in dashboards has changed 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12528]
<img width="1433" alt="Screenshot 2024-11-20 at 09 51 56" src="https://github.com/user-attachments/assets/d3cb36f3-b4b6-4003-afa6-2f0f685944b9">

- [ ] Spacing on left hand side and right hand side of the tiles is uneven
- [ ] The 'add filter' button is offset . It should normally line up with the dashboard title and the start of the tiles.

I think a new change might have accidentally introduced this, so the behaviour needs to go back to how it was

**Comment by ZeRego** [comment]
This was likely introduced with the changes to Dashboard Tabs. Make sure the fix works with both.

**Comment by PriPatel** [comment]
Hmm - I look out for these changes when reviewing tabs. This feels very new, I wonder if there was anything else pushed this week?
