### ISSUE TITLE
Install failure local_dbt

### ISSUE THREAD

**Issue by pixie79** [lightdash/lightdash#1255]
### Describe the bug

If i use the install.sh or run the latest docker image locally and give a full path to my docker directory when on the connecting to your dbt project page in the browser it fails to find my dbt project.

### To Reproduce

1. ./install.sh (pick option 2)
2. enter the full path to the dbt directory /Users/xx/GIT/dbt/dbt_fake_data (dbt_project.yml is in this dir)
3. wait for lightdash to install
4. Go to the start page, register then on the connection page select dbt local server

It fails to find the dbt project dir

### Expected behavior

It should work with the mounted dbt project

**Comment by ZeRego** [comment]
Hi @pixie79, I'm looking into this right now and we should release a fix for it today.

**Comment by ZeRego** [comment]
@all-contributors add @pixie79 for bug

**Comment by ZeRego** [comment]
@pixie79 we just released [0.11.11](https://github.com/lightdash/lightdash/releases/tag/0.11.11) with a fix.
