### ISSUE TITLE
when we wrap a query with `limit` in the SQL runner, the ordering isn't persisted

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12574]
### Description

Right now, when we load 500 rows in the SQL runner, we do this by adding a CTE and a `limit` clause wrapped around the SQL query. 

The issue with this is that the ordering isn't guaranteed to be persisted. 

So, the ordering can become wrong in the results/look jumbled. So far, this has only been reported in Snowflake, but it could also be an issue in other data warehouses.

Some options to resolve this:

1. use the snowflake SDK and the `limit` parameter (?)
2. add a `limit` clause to the end of the query (we would need to make sure there isn't an existing `limit` clause int he query already). 

### Steps to Reproduce the Bug or Issue

1. add a query in the SQL runner using the snowflake warehouse connection
2. add ordering to your SQL query (e.g. order by date)
3. see that the results are in the wrong order
4. run the same query in teh Snowflake query executor
5. see that the query is ordered correctly
6. add a CTE and a limit clause to the query
7. see that the query is ordered incorrectly

### Cloud or self-hosting

None

**Comment by andrewdw** [comment]
@TuringLovesDeathMetal Do you have a sample query I can try in our staging Snowflake instance that I can test against? I'm having a bit of trouble replicating
