### ISSUE TITLE
Period over Period comparison for metrics explorer

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#12609]
### Compare to 'this time last year'

- You can click to compare the selected metric to 'last year'
- A new line gets added to the chart that shows the metric value for the identical period last year (i.e. show the metric for the same timestamps, but subtract 1 from the year). It keeps the chart left-most and right-most date identical
- User can easily clear this comparison

**Comment by yu-iskw** [comment]
+1
