### ISSUE TITLE
conditional formatting rules should show the field name and the colour applied instead of `rule #` in the headers

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12657]
#### Before:

<img width="404" alt="image" src="https://github.com/user-attachments/assets/6436e01a-e0ab-40f1-9013-ae6b4f00d533">

#### After: 

Here's a sketch to use - except instead of this being for reference lines, it shoudl be for `conditional formatting rules` in a table visualization. 

![image](https://github.com/user-attachments/assets/97a0bf25-28b0-4733-9056-2c07644166aa)

### Acceptance criteria:

- [x] add the colour used in the rule beside the field name
- [x] if the rule is a `range`, then can we make the square two colours, split down the middle? If that's too complicated, then just add the start colour as the colour beside the field name. 
- [x] Add the name of the field used as the header
- [ ] If the field name is too long, then it should be cropped. On hover, it should say the field name in full
- [ ] **Bonus:** if there's a way to use the column name in the header instead of the field name, tehn that would be even better. Since users sometimes rename the columns to make them more readable, it could be useful to use the column names here (instead of the field names if they've been updated). On hover, it should always say the field name

**Comment by magnew** [comment]
>  if there's a way to use the column name in the header instead of the field name, tehn that would be even better. Since users sometimes rename the columns to make them more readable, it could be useful to use the column names here (instead of the field names if they've been updated). On hover, it should always say the field name

We can use either one. I'm not sure which is which -- should we use the 'friendly name' or the sql name?
