### ISSUE TITLE
Original Date dimension should be selected/unselected

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1266]
### Describe the bug

The original date dimension can still be used as a column and selected for filters but cannot be selected/unselected from the sidebar. 

### To Reproduce

1. Go to  https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/saved/06dcd27d-155e-4179-be27-3a2ab926c45d
4. See that Order date shows as a column but can't be unselected from the sidebar

### Expected behavior

We can make the original date dimensions selectable from the sidebar. 

### Screenshots or Loom video
![Screenshot 2022-02-01 at 09 16 46](https://user-images.githubusercontent.com/9117144/151941811-896b1def-a6a2-4050-a8aa-179b97eb6166.png)

**Comment by owlas** [comment]
@ZeRego is this equivalent to the `raw` sub dimension?
