### ISSUE TITLE
Use dotted lines for incomplete time periods

### ISSUE THREAD

**Issue by davidgasquez** [lightdash/lightdash#1267]
### Description: What is it?

In timeseries plots, it would be awesome to have a dotted line on the aggregated timeframes that haven't finished. For example, if we're looking at Weekly Active Users, it would be cool to see a different line on this _ongoing_ week.

### Problem: What problem does this solve?

Being able to visually differentiate time periods that will still change on the graph. This helps to reduce confusion overall.

### What: Roughly, what does this look like in the product?

Similar to how other tools approach it. This is an example from Mixpanel:

![1643708031](https://user-images.githubusercontent.com/1682202/151944297-281f50ab-53a3-4c5d-91d3-f9c0ba876c93.png)

**Comment by owlas** [comment]
This is such a great idea @davidgasquez ! And really nice behaviour from mix panel. We have another issue #572 to help users filter out in complete time ranges but I love this visual queue!

**Comment by owlas** [comment]
@all-contributors add @davidgasquez for design, ideas
