### ISSUE TITLE
Update docs for inviting users

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#12683]
These docs (inc screenshots) need to be updated: https://docs.lightdash.com/get-started/setup-lightdash/invite-new-users#inviting-new-users-individually

**Comment by jpetey75** [comment]
i have a local PR just waiting for access to the new docs repo so i can submit the PR

**Comment by jpetey75** [comment]
done https://github.com/lightdash/lightdash-docs/pull/3
