### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12726]
https://www.notion.so/lightdash/Metrics-Catalog-157a63207a7a8059983ff737adfe0935

I've created assets and a rough guide of features in the doc. I have technical questions in red and need help with describing some of the yml examples!

**Comment by joaoviana** [comment]
update roles and permissions table

**Comment by joaoviana** [comment]
PR: https://github.com/lightdash/lightdash-docs/pull/6
