### ISSUE TITLE
The error state for when date is not in the selected range looks broken

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12734]
<img width="919" alt="Screenshot 2024-12-05 at 10 26 38" src="https://github.com/user-attachments/assets/7010a5b7-d1d0-4f87-99de-bde68d34447e">

**Comment by joaoviana** [comment]
will be fixed in: https://github.com/lightdash/lightdash/issues/12739

**Comment by joaoviana** [comment]
closed #12739
