### ISSUE TITLE
New filters break with multiple values added in a single filter field

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1277]
### Describe the bug

When you add multiple values into a single filter field (e.g. filtering a string `is equal to` multiple strings), Lightdash breaks. 

There's a missing `(` in the `IN(` in the rendered SQL 

### To Reproduce

https://www.loom.com/share/3315ac8627f14a8a8903444c955212b1

https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/tables/map_user_organization?dimensions=map_user_organization_organization_id%2Cmap_user_organization_user_id&sort=%5B%7B%22fieldId%22%3A%22map_user_organization_organization_id%22%2C%22descending%22%3Afalse%7D%5D&filters=%7B%22dimensions%22%3A%7B%22id%22%3A%2275e24803-856e-444b-b0e3-3ae04be02b88%22%2C%22and%22%3A%5B%7B%22id%22%3A%2252c10f1c-cd7f-497a-9be9-ec3ee8e88e4c%22%2C%22target%22%3A%7B%22fieldId%22%3A%22map_user_organization_user_id%22%7D%2C%22operator%22%3A%22equals%22%2C%22values%22%3A%5B%22bd30fd8c-10a8-4eb4-8694-809fc1c041c8%22%2C%22c171cbcc-fcf2-4ea8-9bc3-4b58dcbc4d2e%22%5D%7D%5D%7D%7D&limit=500&column_order=map_user_organization_organization_id%2Cmap_user_organization_user_id

### Expected behavior

You should be able to filter for multiple values within a single field.

**Comment by TuringLovesDeathMetal** [comment]
You get the same error if you break out the multiple filter values into different filters:

![image](https://user-images.githubusercontent.com/31848148/152189397-85f081da-703f-465a-996f-6c03ccbed1be.png)

**Comment by ZeRego** [comment]
Fixed by #1276
