### ISSUE TITLE
Legend values should not overlap with charts

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#12801]
### Description

Series values that have longer text fields should be text wrapped or maybe cut off in legends rather than overlapping with the chart. 

### Steps to Reproduce the Bug or Issue

Turn on a vertically stacked Legend in a Pie chart that has long values, or other chart types too (bar chart, etc.)

![CleanShot 2024-12-09 at 16 09 51@2x](https://github.com/user-attachments/assets/507f83e8-2360-4b4f-ada2-7fe3ef6f6809)

### Cloud or self-hosting

None

**Comment by ZeRego** [comment]
@jpetey75 Echarts doesn't have a configuration to avoid this neither provide the information for us to calculate it programmatically.

Echarts ticket: https://github.com/apache/echarts/issues/14252
^ Note that we have left comments about this in 2022 

The chart can also be adjusted to any ratio, so what should happen to the legend?

<img width="747" alt="Image" src="https://github.com/user-attachments/assets/02f505dd-2556-41d3-bc45-396f342e20ca" />

As a compromise, we can limit the labels to 50 characters. Doesn't solve all the cases based on square ratios but will solve the problem where the legend covers the entire chart.
