### ISSUE TITLE
Share SQL Runner button doesn't contain chart configuration

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#12829]
### Description

If I share a table chart from the SQL runner, everything loads well.
If I share a cartesian chart from the SQL runner, the chart doesn't load.

### Steps to Reproduce the Bug or Issue

https://github.com/user-attachments/assets/40634be6-eab3-4565-b8fe-ae2c85e5c847

### Cloud or self-hosting

cloud

**Comment by TuringLovesDeathMetal** [comment]
we need to auto-run the query when you land on that URL! (maybe)
