### ISSUE TITLE
Jobs scheduled at midnight sometimes dont run

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#12837]
### Description

Scheduled deliveries at midnight are sometimes skipped when the job scheduler is very busy. 

The root cause here is that we don't run any jobs before the current miniute and if the job scheduler runs after 00:01:00, things scheduled in the first minute are skipped

### Steps to Reproduce the Bug or Issue

n/a

### Cloud or self-hosting

None

**Comment by hamzahc1** [comment]
was there a customer who requested this @magnew ? I can't see a linked thread from Slack/cloudy
