### ISSUE TITLE
Chart tooltips styling

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12846]
https://www.figma.com/design/AFhGBAKR4kreLZR5uqaSKE/Metrics-First?node-id=1675-826&node-type=frame&t=TQD4obiiQpAIlkOc-0

For the value labels. (indigo and grey)
- [ ] Use colour1 for stroke
- [ ] Use colour0 for fill
- [ ] Use colour7 for text
- [ ] Border radius 8

**Comment by joaoviana** [comment]
done in #12714
