### ISSUE TITLE
`Viewers` should not see `edit` or `create saved content` buttons in the app

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1288]
### Description: What is it?

As a viewer, I can't edit or create saved content in the app, so I shouldn't see these buttons when I'm interacting with charts + dashboards.

I can still see these buttons as a viewer at the moment, even though I can't interact with them:
![image](https://user-images.githubusercontent.com/31848148/152522326-0d6f69e1-c13d-4b23-83f6-cc430f3a4007.png)

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 
We already forbid Viewers from creating or editing content. We could change this issue to a `bug` since we still show those buttons in the UI, even though they throw an error when interacted with.

**Comment by TuringLovesDeathMetal** [comment]
ah, didn't know that. cool! will update the tag
