### ISSUE TITLE
[Trino] invalid query when creating project

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#12916]
### Description

Invalid query when creating project with trino warehouse.

### Steps to Reproduce the Bug or Issue

It has not been replicated yet.

Create project via UI using Trino warehouse throws an error for SQL query:
```
SELECT table­_catalog, table­_schema, table­_name, column­_name, data­_type FROM tpch.information­_schema.columns WHERE table­_catalog;
```
Error
```
SQL Error [58]: Query failed: line 1:115: WHERE clause must evaluate to a boolean: actual type varchar
```

### Cloud or self-hosting

None

**Comment by baruchoxman** [comment]
It was actually a bug on our end - Lightdash is using the `application/x-www-form-urlencoded` header in the protocol and we were not processing it correctly. Closing the bug

**Comment by ZeRego** [comment]
Thank you for the update 🙌
