### ISSUE TITLE
Send reports via email + Slack from Lightdash

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1294]
### Description: What is it?

You should be able to schedule and send reports built-in Lightdash via email or Slack. 

### Problem: What problem does this solve?
A lot of data consumers don't want to open a tool to get their answer, and it's more common to receive a regular (weekly, fortnightly etc) report of the key metrics of your business. This would help those users interact with Lightdash insights more often.  It reduces the need for more people to go through onboarding to get access to their company's data. Also, Slack integrations are just the best when they work well. 

### (Optional) Why: How do we know this is a real problem and worth solving?
The best BI tools have this feature down! It's also something that has been mentioned to us by a couple of users already. 

We want Ligthdash to be a great tool for data consumers too, putting data into places they use everyday makes it a lot easier to interact with. 

### What: Roughly, what does this look like in the product?

- Select a dashboard or chart 
- Add some description or prettifying (might be a nice-to-have)
- Click to share to Slack OR schedule email send (maybe just send immediately via email initially)

**Comment by TuringLovesDeathMetal** [comment]
Good question! 

**Simple answer:** either in 2 weeks, or in 4ish weeks. 

**Long answer:**
We have less than 1 week of build time free before launch week (it's in 3 weeks and we still have V1 & V2 of chart config improvements and saving dashboard filters). 

So we'll have to pick between this, SQL runner charts (#1135 ) and charts+dashboards as code (#1113) 

I'm going to write up the user acceptance criteria for the simplest versions of these three options this week and we can pick which one we'll work on 🙂

**Comment by ZeRego** [comment]
@all-contributors add @hamzahc1  for ideas

**Comment by hamzahc1** [comment]
still relevant!

**Comment by 12ian34** [comment]
This isn't stale. [Milestone #47](https://github.com/lightdash/lightdash/milestone/47) has been created for sharing in slack, but the work for sharing in email hasn't yet been scoped.

**Comment by TuringLovesDeathMetal** [comment]
THis work has been completed!
