### ISSUE TITLE
Cache Metrics Explorer query

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#12969]
### Description

Cache Metrics Explorer queries 

Acceptance Criteria

- [x] 24h cache
- [x] Figure out if stored in Postgres or extend/manipulate the current results cache enabled flag - understand which orgs have it enabled. 
- [x] Generate a key that includes the capabilities that the metrics explorer allows - date filter, metric info, time override, and comparison type 
- [x] Decide if we want a quick solution, for example, improving on-metric-explore load time or **all** interactions

### open questions
1. how often are people exploring a metric - if org A explores a metric on a Monday, will they view it on Tuesday? If not, how relevant is this caching strategy?
2. how often are users exploring a metric on the same day?
3. should we ignore the caching if the model contains user attributes?

**Comment by almeidabbm** [comment]
We decided to use the current caching mechanism which proved to be beneficial during our tests. This is enabled via env variable.
