### ISSUE TITLE
Charts tab constantly shows "Loading Results" spinner before any query has run

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1297]
### Describe the bug

When you open the Charts dropdown in the Explore view before you run a query, it constantly shows the "Loading results" spinner

### To Reproduce

Goto explore --> Tables --> Click on charts drop down

### Expected behavior

It should show a message prompting you to run a query to view a chart 

### Screenshots or Loom video

![Screenshot 2022-02-07 at 14 41 24](https://user-images.githubusercontent.com/14341285/152799084-639f925b-abde-48e2-bb86-def2aba37f0d.png)

**Comment by ZeRego** [comment]
@all-contributors add @hamzahc1 for bugs

**Comment by hamzahc1** [comment]
Seems to have been resolved! Couldn't recreate this anymore
