### ISSUE TITLE
Monitor Metrics Explorer queries

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#12970]
### Description

Acceptance Criteria
- [ ] Monitor how long a metric explorer query takes 
- [ ] Track configuration for the query - this should include: date filters, comparison type (previous period, or another metric), segmentation if so, and granularity
- [ ] How often are people exploring a metric on the same day?
- [ ] How long does a query take from query to results data from the endpoint - basically, we want to know how long it takes to query against the warehouse vs our post-processing
- [ ] Utilise current logging so we can get info from GCP's logs explorer 
- [ ] Consider also adding Sentry metrics so we can get a user journey nicely-outlined.

**Comment by almeidabbm** [comment]
Internal thread: https://lightdash.slack.com/archives/C0741H6LVNY/p1735218379248999
