### ISSUE TITLE
It should be possible to control the SQL runner limit in the UI

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#12988]
### Description

It should be possible to control the SQL runner limit in the UI. There is currently no way to control the limit, but we always set it. 

This used to be included -- why was it removed? Maybe there is a good reason.

**Comment by BhuvaneshPatil** [comment]
Are you talking about limit here ?
<img width="1215" alt="Screenshot 2024-12-23 at 9 38 25 PM" src="https://github.com/user-attachments/assets/6f2d8787-3263-4b5c-84c7-1624703e8b63" />

Or this one, where limit is automatically set to 500?
<img width="1512" alt="Screenshot 2024-12-23 at 9 40 23 PM" src="https://github.com/user-attachments/assets/924a44d5-889c-4122-9d4b-3115dbf71c46" />

**Comment by BhuvaneshPatil** [comment]
I see we have check for showing the limit. 

https://github.com/lightdash/lightdash/blob/45defe551594115df1b71fb46d6e8df11754904f/packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx#L231-L234

We show limit when we are on chart tab/page

**Comment by magnew** [comment]
@BhuvaneshPatil -- the SQL runner is the second screenshot you posted. However, after talking to the team, I see I wasn't understanding how the UI evolved and this ticket isn't quite right. I am going to close this and open a new one that is more clear about what is needed.

**Comment by magnew** [comment]
This ticket isn't quite right -- it is possible to control the post-query limit, but not the limit on the inner query. We need to think about about how the UI/messaging should be for control of the inner limit.
