### ISSUE TITLE
You should be able to search within the saved charts space

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1312]
### Description: What is it?

When you're in the saved charts space, you should be able to search the list of saved charts. 

### Problem: What problem does this solve?

We now have enough saved charts in Lightdash analytics that it's hard to find the one you're looking for. I end up using `CMD` + `F` to search for saved charts. 

### (Optional) Why: How do we know this is a real problem and worth solving?

Both Hamzah and I have complained about how annoying this is 😅 

### Success: How will we know if we’ve solved this problem?

You're able to search for a saved chart within the saved chart space. 

### Audience: Who are we building this for?

Folks exploring saved content. 

### What: Roughly, what does this look like in the product?

Identical to the search in the tables space or the dimensions/metrics:

![image](https://user-images.githubusercontent.com/31848148/153008527-361b6620-4b16-425d-be44-00f20b34f1e3.png)

**Comment by hamzahc1** [comment]
@ZeRego is it possible to do this without backend changes for now? Like if we implemented a really simple search on the FE on the saved charts page? I've had to cmd+f so many times through the list 😢

**Comment by ZeRego** [comment]
Yup, no BE work required.
