### ISSUE TITLE
Big number cards to be shorter as default in the Dashboard

### ISSUE THREAD

**Issue by nathaliabj** [lightdash/lightdash#1327]
### Description: What is it?

The Big Number tiles should be smaller as default in the dashboard

### Problem: What problem does this solve?

Will be visually better

### Success: How will we know if we’ve solved this problem?
 When opening a dashboard with saved Big number chart type, this tiles should have a smaller height than the rest of the chart types.
 
### What: Roughly, what does this look like in the product?

<img width="1439" alt="Screenshot 2022-02-09 at 11 16 19" src="https://user-images.githubusercontent.com/31137824/153248844-f43d2be9-9be9-4778-abbe-9e2e7a76f33d.png">

**Comment by wiksien** [comment]
I will fix that.

**Comment by ZeRego** [comment]
@nathaliabj @PriPatel I have questions about this change. This change is just on tile creation, right? When user adds a new chart tile and is of type big number it should have a smaller height ? But if the user then resize the tile it should keep that size.

**Comment by PriPatel** [comment]
@ZeRego  Yeah, its just the 'default' height. They **should be able to resize it** if they want to but this is more like a 'recommendation' from us, as a tall tile with a big number will look odd.
