### ISSUE TITLE
Wrong SITE_URL on heroku deployments

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1328]
### Describe the bug

When a user deploys using the heroku 1 click button the env is created with the wrong SITE_URL causing problems with invite links. 
Repo: 
https://github.com/lightdash/lightdash-deploy-heroku

### Expected behavior

Set SITE_URL with the url provided by heroku.

**Comment by owlas** [comment]
Can't find a way to find get this from the heroku runtime environment without enabling an additional add-on, which we can't do with `app.json` or `heroku.yml` so would need extra steps.

I think the best we can do is expose the `SITE_URL` during the creation process and let the user specify their preferred SITE_URL?

**Comment by ZeRego** [comment]
> I think the best we can do is expose the SITE_URL during the creation process and let the user specify their preferred SITE_URL?
Yeah, that could work. Would they know the site url at that point ? 🤔

**Comment by owlas** [comment]
I've added a note on how to set it based on the provided app name or to use a custom domain:

Fixed at: https://github.com/lightdash/lightdash-deploy-heroku

Tested ✅
