### ISSUE TITLE
chart isn't cleared when starting a new explore

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#133]
When switching explores, you'll be warned that your existing work is going to disappear (if you've selected some fields).

As expected, the results table clears but the chart doesn't. You end up in the state below:

<img width="1904" alt="Screenshot 2021-06-25 at 10 56 16" src="https://user-images.githubusercontent.com/11660098/123407523-f911a200-d5a3-11eb-94e2-d370768d76d5.png">

Video:
https://www.loom.com/share/1de786d7d75843c388b9322cd1429571

I think we should clear the chart as well as the table when starting a new explore. It doesn't make sense for those to hang around.

**Comment by TuringLovesDeathMetal** [comment]
@owlas @ZeRego is this a copy of #390  ?

**Comment by ZeRego** [comment]
@owlas Not a copy but related
