### ISSUE TITLE
Dashboard filters - Editing the 'field' for a filter that has already been applied

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1340]
The 'Back' button should behave similarly when **adding** a filter and **editing** a filter. It should take you 'back' to select the field. This means the user doesn't have to remove the filter completely and then add a new one. Perhaps the wording doesn't make sense. For now, I propose:

- Remove the 'back' link when the user is **editing** a filter that has already been applied.

- It would be great if when displayed, it has a font-size of 12px so there is nicer hierarchy:
![Screenshot 2022-02-10 at 14 46 24](https://user-images.githubusercontent.com/12776522/153431679-dc23389e-a835-4671-a488-9b2cb0d53539.png)

**Comment by ZeRego** [comment]
@PriPatel 
On edit, could we display the field input above the operator instead ? As a user it just feel like extra steps.

**Comment by PriPatel** [comment]
if thats not hard to do !! If its easier to just remove the 'back', then thats fine but yes, what you have proposed sounds ideal !
