### ISSUE TITLE
Filters - UI bug when popover is open and you scroll down the page

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1347]
### Describe the bug

When the filter popover is open and scroll down the page, it remains in front of the navbar. It makes things look broken. 

![Screenshot 2022-02-11 at 09 48 02](https://user-images.githubusercontent.com/12776522/153570654-e13a6e62-a1ae-487c-9e2f-6d8954bc3411.png)

I would always expect the navbar to be at the front.

**Comment by PriPatel** [comment]
Actually...!
 This is true for all popover elements (eg. configure chart). It is just more obvious with filters because the dropdowns are bigger in height.

**Comment by rephus** [comment]
It also happens one charts tooltips... it might not be easy to solve , maybe we need to fix zindex on navbar ? 
[Screencast from 05-12-22 08:52:12.webm](https://user-images.githubusercontent.com/1983672/205583059-34fbdfb3-d914-4065-831f-7bf0d60f9da1.webm)

**Comment by muhammadjufry** [comment]
Hi @PriPatel, Can i work on this issue, Thanks

**Comment by PriPatel** [comment]
Hey @muhammadjufry - Sorry, this ticket is actually now redundant as we are migrating from Blueprint to Mantine and this should be fixed then. Closing now!

**Comment by muhammadjufry** [comment]
Ok no problem
