### ISSUE TITLE
Add 'help' menu in navbar

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1351]
### Description: What is it?
Currently, users have the option to view docs and open Chatwoot _however_...
the placement of these buttons is not intuitive or consistent. 

Proposal:
[Figma link here
](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1652%3A42780)![Screenshot 2022-02-11 at 11 30 01](https://user-images.githubusercontent.com/12776522/153584215-0a5abc86-8e48-44cd-afe7-9058e23e1726.png)

**1.** The simplest version is an additional dropdown menu in the navbar. (one that behaves like the explores or browse tab.
**2.** Ideally we can have a bit more context explaining where the user should based on what they want to do.

**Contact support** - Triggers Chatwoot window (@owlas is this possible?)
**View docs** - Links to [our documentation](https://docs.lightdash.com/)
**Join the discussion** - Links to [GH discussions](https://github.com/lightdash/lightdash/discussions)

**Lets discuss what is possible to achieve today!** The above are not final designs - we can refine based on our discussion.
@hamzahc1 Let me know any feedback you have on copy, the actual options etc.

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal - We could add a fourth option here for Lightdash University once we have 1 video ready to publish! (That would be the link with a subtitle like: `Tutorials on how to build in Lightdash and best practices in BI`

**Comment by ZeRego** [comment]
Should we have a button to report a bug ? that redirects to the github create bug issue page.

**Comment by hamzahc1** [comment]
The other consideration is the `Contact Support` option - I'm guessing for Cloud Users this should trigger chatwoot to open? But for self-hosted users what should it do...? Let them send us an email?

**Comment by ZeRego** [comment]
Yes we can open it. We already do it for the button in the bottom right.
```
const openChatWindow = () => {
        (window as any).$chatwoot?.toggle('true');
    };
```

**Comment by owlas** [comment]
This looks great to me!
