### ISSUE TITLE
There should be a consistent way for users to add a filter from the sidebar and the results table.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1358]
### What's the problem or idea you want to talk about?
There should be a consistent way for users to add a filter from the sidebar and the results table. We need to introduce a pattern so that these actions become intuitive to the user.
There are a couple of ways we can do this:

**Right click** 
Because we are dealing with secondary actions, we can't do too much visually. ( I can look into it a bit more, but this isn't that common). We need to explain either during onboarding or somewhere on the page that you can right click. We've had users actually request 'right clicking' though. It *seems* to be an intuitive thing to do.

**Menu on hover**
Check out this prototype:
https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1660%3A43307&scaling=min-zoom&page-id=1660%3A42494&starting-point-node-id=1660%3A43307
 We could have a context menu appear on hover for table cells and metrics/dimensions. A couple of issues:
-  Users might want to copy the contents of a table cell and so if there are two many rows and the cell contents is long, the context menu would cover this. 
- In the sidebar, we have too much action going - eg. Descriptions on hover. Maybe the description can be part of a context menu that only appears on hover? 

![Screenshot 2022-02-11 at 16 30 46](https://user-images.githubusercontent.com/12776522/153642960-5f9f80f8-737d-4d92-93a7-b2698eb5c2ca.png)
![Screenshot 2022-02-11 at 17 49 55](https://user-images.githubusercontent.com/12776522/153643018-7b29d291-2b11-4e83-bb37-d6aeb41082d6.png)

**Comment by PriPatel** [comment]
This was before we implemented right-click to apply filter from the **table**. 
I think for consistency, the user should be able to right-click from the **sidebar** to apply filters as well.

**Comment by ZeRego** [comment]
@PriPatel should we remove the `add filter` option + 'view options' button from the sidebar ? And just have the context menu (right click) ?

**Comment by PriPatel** [comment]
@ZeRego yes - I think it should be consistent everywhere (perhaps if its less clear, but its something we can communicate). So if you were to right-click on this, and there was the option to see 'source', that would live under the menu as well, correct?

**Comment by PriPatel** [comment]
super relevant!

**Comment by owlas** [comment]
Closing for https://github.com/lightdash/lightdash/issues/2785
