### ISSUE TITLE
It's unclear that you don't need quotes around your metric definitions

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1379]
### Which docs do you want to update?

https://docs.lightdash.com/get-started/setup-lightdash/add-metrics#2-add-a-metric-to-your-project

### What needs updating?

You don't actually need quotes around the `type` and the `metric name` in the .yml files - we should remove them.

**Comment by colin-nayuta** [comment]
yup i found this confusing as well
to quote or not to quote?
i prefer not to
reason?
no column name in database should have space
use underscore instead

**Comment by TuringLovesDeathMetal** [comment]
totally - you can do either! so I feel like adding no-quotes in the docs is probably a better bet.

Just created a PR for this now - should be merged in a few mins! https://github.com/lightdash/lightdash/pull/1530
