### ISSUE TITLE
Improve prompt for users to upgrade their version of Lightdash

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1394]
### Description: What is it?

Right now, we pop up a little message in the footer letting folks know there's an update, but:
- It's not as obvious as it could be
- It doesn't include any info about what's in the release! 
![Screenshot 2022-02-15 at 16 34 32](https://user-images.githubusercontent.com/14341285/154119324-3d6760ed-5e1f-4485-b02a-355d52471f76.png)
![Screenshot 2022-02-15 at 16 34 39](https://user-images.githubusercontent.com/14341285/154119350-835f5cc7-f96c-4ef4-ab12-2a63cc34b5e7.png)

### Problem: What problem does this solve?
- If people don't upgrade, they don't get good Lightdash 😢

### Success: How will we know if we’ve solved this problem?

- If all our users are using the latest versions of Lightdash! 

### What: Roughly, what does this look like in the product?
Open to suggestions but it should ideally: 
- Be more obvious and bright prompt to update their instance 
- Include details from the release notes! 
- Have a CTA on how to update the version 

Optional...: Force them to update the version but with how often we release 😎, forcing users to update every time might be a bit much... but at least once a day or a couple of times a week they should get an in-app prompt?

**Comment by hamzahc1** [comment]
@PriPatel any implementation/design ideas for this one? Judging by how many self-hosted users seemed to be on older versions, this might be a useful one to improve!

**Comment by PriPatel** [comment]
<img width="312" alt="Screenshot 2022-02-15 at 18 25 59" src="https://user-images.githubusercontent.com/12776522/154125396-5397b14a-21ac-4f1c-8187-9fd5f99f9be0.png">
Also, a notification bell!

**Comment by hamzahc1** [comment]
I like the announcement pop up, but do you think it might get annoying if we release multiple times per day? Or we could only have it pop up for new features rather than bugs, fixes, doc changes etc...

**Comment by ZeRego** [comment]
Is there any open source product/tool that would help us implement this ? like chatwoot.
This would save us coding hours and would prob be a more robust solution.

**Comment by hamzahc1** [comment]
@PriPatel - I actually think we should think about potentially removing this prompt? I've often seen Cloud users click on this but they have no control on updating their version of Cloud. Or if it's possible to disable for Cloud users so only open-source folks will see it, not sure if that's possible

**Comment by PriPatel** [comment]
@hamzahc1 Yeah, we should definitely hide it for Cloud users - I can imagine it being quite frustrating!

**Comment by hamzahc1** [comment]
@ZeRego - is there a way to disable the "new version available" for Cloud users only?

**Comment by ZeRego** [comment]
> @ZeRego - is there a way to disable the "new version available" for Cloud users only?

@hamzahc1 yes. it should be a simple FE change.
