### ISSUE TITLE
You should be able to remove `pages` from the results table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1396]
### Description: What is it?

You should be able to have an option to remove the pages from the results table and just have everything appear in a giant table that you can scroll through. 

### Problem: What problem does this solve?

A lot of times helpful to just look at all rows at once scrolling up / down and get rough idea of row count returned when sorting but not that easy to see when paging and no row number 

### (Optional) Why: How do we know this is a real problem and worth solving?

https://getdbt.slack.com/archives/C026WJE4A69/p1644972891863359?thread_ts=1644794904.784429&cid=C026WJE4A69

### Success: How will we know if we’ve solved this problem?

You're able to un-page your results table 

### Audience: Who are we building this for?

Mostly data builders - people building charts and looking over their results tables. 

### What: Roughly, what does this look like in the product?

A toggle at the bottom where the pages are. Something that says `show results on one page` maybe?

**Comment by hamzahc1** [comment]
I do love a good infinite scroll 🥰

**Comment by owlas** [comment]
Would it be useful to have a "jump to bottom" too? Usually the most interesting rows are the top few and very bottom few

**Comment by ZeRego** [comment]
@PriPatel we might need some quick designs for this 🤔 where do we show the "jump to bottom" button and option to enable/disable pages.

**Comment by PriPatel** [comment]
**A couple of questions:**

1. **Is this is a general setting or only something applied per table?** I imagine you don't want to change the settings for every single table if you have a preference? eg. Sort of like gmail:
<img width="314" alt="Screenshot 2022-02-17 at 17 27 11" src="https://user-images.githubusercontent.com/12776522/154538769-705f8dc1-4e45-4b98-b46a-d9e14ef7ec7a.png">


2. **Does the user need to hit 'run query' after they change their page display preferences?** 
3. **When the results are displayed on one page, does this mean we have one looong page, OR do we have a fixed height container that the user can scroll through?**
4. **Is there a limit to how many results we can display?** 
5. **Will we need a loading spinner to appear after every X results displayed ?**

**Comment by PriPatel** [comment]
![Screenshot 2022-02-17 at 17 42 03](https://user-images.githubusercontent.com/12776522/154539641-68379c11-ef41-4241-ad71-e6497bf35cca.png)
 We could implement a very common pattern like the above image. It solves one of the problems that has come up, where the user wants to know how many results there actually are.
 
One of the options in the dropdown could just be 'show all'.  If we want to be able to `jump to top`, `jump to bottom`, we would need to pin these actions in a fixed position. I'd like to understand some of the constraints and questions in my previous post before coming up with final UI. Thanks :)

**Comment by PriPatel** [comment]
@nathaliabj and I were just discussing this during our virtual desk chat:

**It seems like there are two problems here:**
- The user wants to know how many results there are;
- The user wants to be able to navigate through the results quickly;

**Could a reallly quick first step be to :**
1) show the number of total rows
2) Have a `skip to last` page button 

This would address _some_ of the problems easily, if we find that the original proposed solution is a mammoth of a task.

**Comment by PriPatel** [comment]
thanks @ZeRego - a prototype for this coming up soon!
