### ISSUE TITLE
Field headers feel selectable when they aren't

### ISSUE THREAD

**Issue by jeshuamaxey** [lightdash/lightdash#140]
Hello squire, some UX feedback for ya

I was playing with your demo and got confused by the Dimensions and Metrics sub-headers in the left hand panel. These aren't selectable items, but they have a hover effect which made me think I could click them. I also noticed that the cursor doesn't change into a lil pointy hand (`cursor: pointer`) for  items which are selectable in the list.

The screenshot unfortunately doesn't capture the cursor, but you can see the hover effect (grey bg) where it shouldn't be.

<img width="1440" alt="Screen Shot 2021-06-28 at 14 43 12" src="https://user-images.githubusercontent.com/2297823/123647964-75181e00-d820-11eb-8883-f6ffd49a85bd.png">

**Comment by owlas** [comment]
Cheers @jeshuamaxey - thanks, this is definitely a UX bug. Appreciate the screenshot too.

**Comment by owlas** [comment]
@all-contributors add @jeshuamaxey for bugs

Also thanks for your first contribution!
