### ISSUE TITLE
You should be able to have a mix of markdown and charts in a tile

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1408]
### Description: What is it?
![Screenshot 2022-02-17 at 10 47 40](https://user-images.githubusercontent.com/12776522/154460582-6185af4d-c861-4e1e-8018-7a7e351c0d3c.png)

Super long chart titles are less punchy! 
For impact and hierarchy, the user could have the option to have a subtitle underneath the chart title, stating the goal of 1000 weekly active users.
They could even be able to edit the chart title in this tile only ( and _not_ affect the original saved chart)

**Comment by TuringLovesDeathMetal** [comment]
ooh I like this!

The option to add text, then you could pick where it goes (above, below, left, right of the chart)

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue - there haven't been any user requests for this since it was created!
