### ISSUE TITLE
When you try to edit the operator for a saved dashboard filter, the value disappears.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1410]
### Describe the bug

When you try to change the operator of a filter that has already been applied to a dashboard, the value clears. I think this only affects string values.

### To Reproduce

**To reproduce:**
Add a value filter to the dashboard. eg. order status `equals` completed
Click to edit the filter
Change the operator to `does not equal`
The value is cleared. It should persist.

**Comment by ZeRego** [comment]
Yeah, is a tricky situation where we don’t know if the existing value is still valid when changing to another operator. So we need extra logic to see what value should be there on operator change. 

E.g: Date dimension equals 2022-01-01 
-> change operator to **is in the last**. The value is not compatible so set default value
-> change operator to **is null**. Remove value
-> change operator to **is not equals**. Keep value
