### ISSUE TITLE
new project creation fails when dbt folders are not in root

### ISSUE THREAD

**Issue by captnswing** [lightdash/lightdash#1414]
### Describe the bug

I have modified my `./dbt_profiles.yml` config to group all dbt folders in a subfolder

```
model-paths: [ "dbt/models" ]
seed-paths: ["dbt/seeds"]
analysis-paths: ["dbt/analysis"]
test-paths: ["dbt/tests"]
macro-paths: [ "dbt/macros" ]
snapshot-paths: ["dbt/snapshots"]
docs-paths: ["dbt/docs"]

log-path: "dbt/logs"
packages-install-path: "dbt/packages"

target-path: "dbt/target"  # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "dbt/target"
  - "dbt/modules"
```

I cannot create a lightdash project using this configuration. The project creation fails with the error 

![CleanShot 2022-02-18 at 09 08 23](https://user-images.githubusercontent.com/325377/154643654-5854c168-a782-4468-88c0-97401868ae40.png)

when I change my `./dbt_profiles.yml` config back to the default

```
model-paths: [ "models" ]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: [ "macros" ]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

log-path: "logs"
packages-install-path: "packages"

target-path: "target"  # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "modules"
```

project creation works

### Expected behavior

lightdash finds the configured target folder and the manifest

**Comment by ZeRego** [comment]
Thanks for reporting this @captnswing :) 

Looks like currently we only check for `target-dir` and not `target-path`.
https://github.com/lightdash/lightdash/blob/main/packages/backend/src/dbt/dbtCliClient.ts#L47

We should change our logic to have the following priority: `target-path` > `target-dir` > fallback to value `/target`

**Comment by ZeRego** [comment]
@all-contributors add @captnswing for bug
