### ISSUE TITLE
Improved sidebar design

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#142]
The sidebar is currently quite hard to navigate:

* The scroll bar location is hovering with weird padding
* The hierarchy (tables and dimensions vs. measures) is not visually strong and makes it hard to read
* The info icon is a tiny hover target and not obvious why it is there and repeated for every field.

**Comment by TuringLovesDeathMetal** [comment]
@owlas is this ticket still relevant? 

I might break this down into smaller bugs if they're still lurking about

**Comment by owlas** [comment]
@TuringLovesDeathMetal some of these are solved. I'll close this in favour of separate tickets.
