### ISSUE TITLE
Ability to provide environment variables for dbt project

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1421]
### Description: What is it?

a dbt project might use `{{ env_var('') }}` functions in their jinja - we can't compile dbt projects if those are missing

### Problem: What problem does this solve?

compiling dbt projects with environment variable dependencies

### What: Roughly, what does this look like in the product?

Option in the UI to provide environment variables

**Comment by ZeRego** [comment]
@owlas **How to we want to store this ?** 
```
type ProjectConfig = {
...
env_vars: Record<string, { value: string }>; // using an object so we can add more properties later on if we need them
}
```

Should we treat these env values as secrets ?  If so, we need to make sure we don't return those values to the FE.

**How do we want to display this ?** 

I was imagining a table, like Webstorm does.

![Screenshot 2022-02-25 at 15 52 38](https://user-images.githubusercontent.com/9117144/155745775-d23d8af6-0d21-4c2a-b4ee-ed83e9fda3a7.png)

@PriPatel thoughts?
