### ISSUE TITLE
It's not obvious where to go from the onboarding screen. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1426]
### Description: What is it?

When you open Lightdash, it's not obvious where you should go from the onboarding screen. Maybe we should tell users to go to the `explores` page even before they see the onboarding checklist? 

### Problem: What problem does this solve?

Users see the onboarding screen and don't know where to go. 

### Success: How will we know if we’ve solved this problem?

Users take a consistent action when they hit the home screen for the first time. 

### Audience: Who are we building this for?

New users being onboarded into Lightdash

### What: Roughly, what does this look like in the product?

Maybe for the very first people, we force them to go to the `explore` screen. 

If you have saved content, then maybe we show you this saved content? or push you to the saved charts/dashboards space?

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal 
I have improvements for this! If you think the changes can be implemented during Lightdash day, I can arrange some design specs this week.

**Comment by TuringLovesDeathMetal** [comment]
that would be great @PriPatel !

**Comment by PriPatel** [comment]
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1994%3A42852
