### ISSUE TITLE
The value for a filter should stay if you switch between operators

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1429]
### Description: What is it?

When you try to edit an applied filter where the value is a string, the value disappears once you change the operator. (eg. try changing `order status is equal to completed` to `is not equal to completed`).

If you switch between filter operators, it should keep the `completed` value. 

### Problem: What problem does this solve?

It's annoying for users to have to re-type a value

### (Optional) Why: How do we know this is a real problem and worth solving?

user feedback from usability tests

### Success: How will we know if we’ve solved this problem?

Users are able to switch between operators and not have to re-type their values. 

### Audience: Who are we building this for?

Users who are building things, but also using filters

### What: Roughly, what does this look like in the product?

If you switch between filter operators that filter on the same type (e.g. string filters, number filters) then the value should stay, even if you're changing operators.

**Comment by PriPatel** [comment]
https://github.com/lightdash/lightdash/issues/1410#issuecomment-1042865296
