### ISSUE TITLE
Refactor database to support more complex charts

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1434]
### Description: What is it?

**Saved Chart Config - cartesian**
bar, column, line, scatter charts map to cartesian 
```json
old
{
  ...
  "chartConfig": {
    "chartType": "column",
    "seriesLayout": {
      "xDimension": "base_api_error_week",
      "groupDimension": "base_api_error_name",
      "yMetrics": ["base_api_error_count_distinct_api_errors"]
    }
  }
}


new
{
  ...
  "pivotConfig": {
    "columns": ["base_api_error_name"]
  },
  "chartConfig": {
    "chartType": "cartesian",
    "config": {
      "series": [
        {
          "xField": "base_api_error_week",
          "yField": "base_api_error_count_distinct_api_errors",
          "type": "line"
        }
      ]
    }
  }
}
```

**Saved chart config - big number**
big number no longer needs dimension fields

```json
old
{
  ...
  "chartConfig": {
    "chartType": "big_number",
    "seriesLayout": {
      "xDimension": null,
      "groupDimension": null,
      "yMetrics": ["base_api_error_count_distinct_api_errors"]
    }
  }
}

new
{
  ...
  "pivotConfig": {
    "columns": ["base_api_error_name"]
  },
  "chartConfig": {
    "chartType": "bigNumber",
    "config": {
      "fieldName": "base_api_error_count_distinct_api_errors"
    }
  }
}

```

**saved chart config - table**
table drops any configuration for now

```
old
{
  ...
  "chartConfig": {
    "chartType": "table",
    "seriesLayout": {
      "xDimension": ["organizations_organization_name"],
      "groupDimension": "organizations_app_version",
      "yMetrics": ["base_api_error_count_distinct_api_errors"]
    }
  }
}

new
{
  ...
  "pivotConfig": {
    "columns": ["base_api_error_name"]
  },
  "chartConfig": {
    "chartType": "table",
    "config": {
    }
  }
}
```

### Problem: What problem does this solve?

Blocked implementing new chart features

**Comment by ZeRego** [comment]
@owlas @TuringLovesDeathMetal Do we see a use case where people want to pivot the info in the results table but not on the chart ? and the opposite ?

**Comment by ZeRego** [comment]
@owlas
- For the big number example, should the pivotConfig be empty ?
- For the table example, should the pivotConfig be empty since we don't seem to support that right now ?
- During migration, if there is no `yMetrics` should it use a value from the `xDimension` or skip chart config in that case ?
- Will the `chartConfig` or `config` be optional ? or support partial `config` ? otherwise how will we handle the case where the user saves a chart with only 1 dimension selected ?

**Comment by owlas** [comment]
One thing we can do for both `table` and `big_number` is completely ignore the `groupDimension,xDimension,yMetrics` and rely on the behaviour: table shows all columns, big number shows top left numbe

Given that:

* Since neither `big_number` nor `table` support `groupDimension` then `pivotConfig` will always be empty
* as above ^
* Good question, only applies to `cartesian` charts. Not sure if either is allowed via the UI? But if `yMetrics` or `xDimension` is missing, we'll render `series: []` so no chart will show.
* `chartConfig` won't be optional. 1 dimension works already for `table` and `bigNumber`. Saving a cartesian chart with only 1 dimension should not be possible, I'll make sure to handle this case!

**Comment by owlas** [comment]
@TuringLovesDeathMetal @ZeRego I was going to propose we have them pivot together to keep things simple in the UI.
