### ISSUE TITLE
Table calculation button looks broken

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1437]
### Describe the bug

We used to have a background colour to indicate the click area for adding a table calculation
<img width="260" alt="Screenshot 2022-02-22 at 17 46 27" src="https://user-images.githubusercontent.com/12776522/155189664-d33115c3-a6d7-4f3c-999a-5e5e6bc18d68.png">

It seems to have disappeared after the latest update? It looks broken and not very clear that i have to click on it. It also makes the alignment of the whole table in the panel appear a bit broken too!. 
<img width="189" alt="Screenshot 2022-02-22 at 17 46 30" src="https://user-images.githubusercontent.com/12776522/155189763-49a16a18-89f6-406f-96ad-78a65d29867e.png">

**Comment by zuku1985** [comment]
Hey! I was recently testing Lightdash and to be honest I feel much bigger issue is that is it almost imposible to discover this feature without knowing about it.

**Comment by PriPatel** [comment]
@zuku1985  - Thanks for the great feedback! This is a valid point. 
 I'll take a look to see if there is something we can do to make the discovery of this feature more obvious!
 
 Thanks again and hope you're enjoying Lightdash!
