### ISSUE TITLE
It is not obvious that the table calculation feature exists

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1439]
### Description: What is it?

It is not immediately obvious that this powerful feature exists! Right now it looks like you can 'add column', but that is about it. 

### Success: How will we know if we’ve solved this problem?
Feature awareness: It is clear to first-time users that they are able to carry out this action just by looking at or hovering over something. 

_Originally posted by @zuku1985 in https://github.com/lightdash/lightdash/issues/1437#issuecomment-1048806345_

**Comment by hamzahc1** [comment]
I agree, I often forget this feature! I sometimes think the + is to... add another column? @PriPatel Could a simple solution be to put the `Add table calculation` at the top right of the Results tab, similar to how all the functions to edit charts currently exist in the charts tab?

<img width="993" alt="Screenshot 2022-02-23 at 15 40 37" src="https://user-images.githubusercontent.com/14341285/155354172-d3f6ec65-7037-4663-88b0-da82700838a1.png">

**Comment by ZeRego** [comment]
Do we want to keep the `+` in the table ?

**Comment by PriPatel** [comment]
@ZeRego Yeah lets keep it for now . Its not in the design but lets keep it.
