### ISSUE TITLE
Connecting to custom dbt project throws error - Lightdash timedout trying to connect to dbt. Is dbt running correctly

### ISSUE THREAD

**Issue by srjonemed** [lightdash/lightdash#144]
Following snippet from the docker run instance - 

```
$ docker run -it -p "${LIGHTDASH_PORT}:8080" -v "${DBT_PROJECT_DIR}:/usr/app/dbt" -v "${DBT_PROFILES_DIR}:/usr/app/profiles" lightdash/lightdash
...

{
  timestamp: '2021-06-29T20:59:17.915417Z',
  message: 'sending response (<Response 41076 bytes [200 OK]>) to 127.0.0.1',
  channel: 'dbt',
  level: 11,
  levelname: 'INFO',
  thread_name: 'Thread-61',
  process: 36,
  extra: {
    response_code: 200,
    request_id: 'e96e7de4-1436-4b34-8401-322e9250ef1e',
    addr: '127.0.0.1',
    http_method: 'POST',
    context: 'server',
    run_state: 'internal'
  }
}
NetworkError: Lightdash timedout trying to connect to dbt. Is dbt running correctly?
    at /usr/app/packages/backend/dist/dbt/rpcClient.js:135:24
    at Generator.next (<anonymous>)
    at fulfilled (/usr/app/packages/backend/dist/dbt/rpcClient.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  statusCode: 500,
  data: {}
}
GET /api/v1/status 200 0.492 ms - 33
GET /api/v1/status 304 0.383 ms - -
GET /api/v1/status 304 0.402 ms - -
GET /api/v1/status 304 0.385 ms - -
GET /api/v1/status 304 0.455 ms - -
GET /api/v1/tables 500 1.498 ms - 160
GET /api/v1/status 304 0.714 ms - -
GET /api/v1/tables 500 0.383 ms - 160
GET /api/v1/status 304 0.407 ms - -
GET / 304 3.070 ms - -
GET /api/v1/tables 500 1.956 ms - 160
GET /static/css/2.c6d9bebb.chunk.css 304 1.493 ms - -
GET /static/css/main.a1756aaf.chunk.css 304 1.738 ms - -
GET /static/js/main.6efc40bc.chunk.js 304 2.316 ms - -
GET /static/js/2.2f7f0701.chunk.js 304 2.262 ms - -
GET /api/v1/tables 500 0.458 ms - 160
GET /api/v1/status 304 0.412 ms - -
GET /favicon.ico 200 2.525 ms - 15086
GET /manifest.json 304 0.539 ms - -
GET /apple-touch-icon.png 304 0.355 ms - -
GET /api/v1/tables 500 0.413 ms - 160
GET /api/v1/tables 500 0.401 ms - 160
GET /api/v1/status 304 0.314 ms - -
```

Profiles is set to connect to Snowflake.

**Comment by owlas** [comment]
Thanks for reporting this @srjonemed !

Could you run this command in the same terminal:
`docker run -p "${LIGHTDASH_PORT}:8080" -v "${DBT_PROJECT_DIR}:/usr/app/dbt" -v "${DBT_PROFILES_DIR}:/usr/app/profiles" lightdash/lightdash /bin/bash -c 'cd /usr/app/dbt && dbt debug'`

This will help to debug the dbt `profiles.yml` file. If this looks fine then it could be that the project is quite large and takes a while to generate. How many models are you running? And how big is the snowflake schema?

**Comment by srjonemed** [comment]
Thanks @owlas for looking into this.
The debug command passes with "Connection test: OK connection ok".
The model I'm running is a demo model with just four .sql files. It does have couple of references , macros (dbt deps). 
The production DB schema might have 100s of tables. But then, I also switched to my dev DB where there are only a few tables, but still getting this same error.

**Comment by owlas** [comment]
Could you share the entire set of logs that got printed after you started up Lightdash using `docker run` ?

**Comment by srjonemed** [comment]
Here's screen scraped output and also the output from debug cmd
[dashout.log](https://github.com/lightdash/lightdash/files/6743510/dashout.log)
<img width="1029" alt="Screen Shot 2021-06-29 at 5 52 19 PM" src="https://user-images.githubusercontent.com/34316602/124019911-7c653600-d99e-11eb-8ed2-353e535dca80.png">

**Comment by owlas** [comment]
Sorry I mean the logs following you running lightdash and leading up to the original error message at the top: 
`NetworkError: Lightdash timedout trying to connect to dbt. Is dbt running correctly?`

**Comment by srjonemed** [comment]
[dashout.log](https://github.com/lightdash/lightdash/files/6743888/dashout.log)
Does this capture what you're looking for?

**Comment by owlas** [comment]
That is perfect!!! Thanks @srjonemed just going through this now

**Comment by owlas** [comment]
Hey @srjonemed I've just found this. 

I have some snowflake experience but we haven't tested it with Lightdash. Do you typically set the warehouse inside your `profiles.yml` ?

Are you able to do `dbt docs generate` on the command line?

From dashout.log
```
  timestamp: '2021-06-30T20:38:05.519094Z',
  message: 'Encountered an error while generating catalog: Database Error\n' +
    "  000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.\n" +
    '  ',
  channel: 'dbt',
  level: 13,
  levelname: 'WARNING',
  thread_name: 'MainThread',
  process: 265,
  extra: { context: 'server', run_state: 'internal' }
}
{
  timestamp: '2021-06-30T20:38:05.607651Z',
  message: 'Encountered an error while generating catalog: Database Error\n' +
    "  000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.\n" +
    '  ',
```

**Comment by srjonemed** [comment]
Good catch! I'm able to fix this by granting the wh to the role. I had switched to a new user/role combination since the earlier one was running into different issue. With the earlier user/role lightdash would complain that it was not able to open browser application as it was not supported in the container (using browser based authentication). The current user/role is configured with private-key based auth.

Currently, on the UI I could see the models for my dbt project listed on the left, however there are no results being displayed (although querying the corresponding tables directly on snowflake does return rows). I'll dig into it more later and reach out if I need further assistance. Thanks

**Comment by owlas** [comment]
Created new issues for these:
* browser-based auth (if possible) #153 
* surfacing better snowflake auth issues in UI #154

> there are no results being displayed 

Cool, this could be an error (again haven't tested snowflake rigorously so really appreciate you taking the time). Happy to pair program this on discord if you like: drop me a message: https://discord.gg/eSx33udn

**Comment by owlas** [comment]
@all-contributors add @srjonemed for bugs

**Comment by owlas** [comment]
@srjonemed are you happy for me to resolve this in favour of #153 and #154 - and pending any error you get with the missing data

**Comment by srjonemed** [comment]
Yes please, we can close this issue now. Thanks for your quick help. I'll try and reach out to your discord for UI issue
