### ISSUE TITLE
Creating or updating markdown tiles removes scroll in dashboards

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1446]
### Describe the bug

If you create or update a markdown tile, the ability to scroll is removed from the dashboard. 

Instead, you have to save the dashboard, then click `refresh`. Unfortunately, if you're lower down in the dashboard where the save button isn't in view, then you have to refresh the page and lose any of the changes you made. 

### To Reproduce
https://www.loom.com/share/ea47962996d2447193f0079324caff9f

**Comment by PriPatel** [comment]
nasty! 
This also makes me think that the header bit of each dashboard (with the `save` button and `add tile`) should be pinned to the top of the page?

**Comment by TuringLovesDeathMetal** [comment]
ya, I was thinking that too!

**Comment by TuringLovesDeathMetal** [comment]
Update: this is happening when you add _**any**_ tile type to the dashboard

**Comment by ZeRego** [comment]
The markdown input library seems to have a bug when rendered inside the Blueprintjs popup. 
More details in this thread https://github.com/uiwjs/react-md-editor/issues/309
I'm trying to find a workaround :)

**Comment by jaywcjlove** [comment]
@ZeRego Upgrade [`@uiw/react-md-editor@3.10.0`](https://github.com/uiwjs/react-md-editor/releases/tag/v3.10.0)

**Comment by ZeRego** [comment]
@jaywcjlove Thanks for the fix 😄  Going to upgrade tomorrow 👍
