### ISSUE TITLE
Results table usability

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1447]
### Description: What is it?
The following designs take care of #1396, #1439, #1437 :
[Prototype](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1970%3A46164&scaling=min-zoom&page-id=1970%3A45140&starting-point-node-id=1970%3A46164)
[Figma file](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1970%3A45140)

In addition to this:

- [x] There should be a border-bottom in the last row of each table

- [x] The row number column should have a fixed width - right now it seems to be dependant on the number of columns.

**Comment by ZeRego** [comment]
For the smaller style changes https://github.com/lightdash/lightdash/pull/1448
