### ISSUE TITLE
'Run query' hover state on the 'Tables' page does not match the one 'SQL runner' page.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1449]
### Description: What is it?
On the SQL runner page, when you hover over the 'Run query' button, you see a nice tooltip informing you of the keyboard shortcut you can use instead.

<img width="335" alt="Screenshot 2022-02-25 at 11 02 58" src="https://user-images.githubusercontent.com/12776522/155706584-74c3dcb0-678d-44da-abeb-8b8c11b95be5.png">

The `Run query` button on the `Tables` page does not show the same tooltip. It would be useful if it did as some people may never use 'SQL runner!'.

**Comment by hamzahc1** [comment]
It's also not obvious but if you hit "cmd + ?" - it brings up the shortcut list! 

<img width="1153" alt="Screenshot 2022-02-25 at 13 44 44" src="https://user-images.githubusercontent.com/14341285/155725669-c75d6eb9-3c9c-4f7f-bdb3-3ffa2bb0329a.png">

**Comment by PriPatel** [comment]
@hamzahc1 Mind blown! I did not know this 😮
