### ISSUE TITLE
You can't delete the default number included in the filters

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1452]
### Describe the bug

When you try to change the number to filter by in the filters (e.g. for the `is in the past` date filter, if I want to change it to `4` instead of the default, `1`), you can't delete `1` and replace it with `4`, you have to move the arrows up and down to get to 4. 

This is fine for single digits, but imagine if I wanted to change it to 35? Then I'd have to click through the numbers all the way to 35 (because you can't remove the `1`)

### To Reproduce

https://www.loom.com/share/a88ed267d8e242178af0010e99d4d28a

### Expected behavior

You should be able to delete the default value in the filter.

**Comment by ZeRego** [comment]
Hi @Mohmn 👋  looks like another contributor opened a PR to fix this before you. 
We have plenty of other [good first issues](https://github.com/lightdash/lightdash/labels/good%20first%20issue) we would be happy for you to pick up. Let me know if you want help picking one or setting up the dev environment :)

**Comment by Mohmn** [comment]
@ZeRego I'm getting an error while I'm trying to set up this project locally, specifically when I try to run the yarn install command
after some time I get `Exit code: 1Command: node-pre-gyp install --fallback-to-build` 
can I get a slack invite to resolve this issue

**Comment by ZeRego** [comment]
> can I get a slack invite so that I can further discuss with you how to resolve this issue

@Mohmn We haven't setup our own public slack yet. You can reach out to us in [dbt slack in the tools-lightdash channel](https://getdbt.slack.com/archives/C026WJE4A69). 

> I'm getting an error while I'm trying to set up this project locally, specifically when I try to run the yarn install command
after some time I get Exit code: 1Command: node-pre-gyp install --fallback-to-build

That package relates to Python. Do you have Python installed ?

**Comment by Mohmn** [comment]
yep, I do have python installed, thanks for the hint. I will try to fix the issue from the python point of view

**Comment by ZeRego** [comment]
@Mohmn Also what version of python and what OS are you using ? Is this happening when you run `yarn install` in your machine or inside the docker container ?

Can you open a new issue with all these details ? This way it will be easier to track the conversation and help other people with the same problem.
