### ISSUE TITLE
Table visualization should be available when no metrics are selected

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1468]
### To Reproduce

1. Go to explore a table
2. Select only dimensions
3. Run query
4. See table visualization button disabled

### Expected behavior

Table visualization should be enabled when there are only dimensions selected

### Screenshots or Loom video

![Screenshot 2022-02-28 at 11 40 04](https://user-images.githubusercontent.com/9117144/155977555-d3b70a7c-aa1d-4316-9999-301924532b2e.png)

**Comment by rephus** [comment]
@owlas @TuringLovesDeathMetal looks like this issue has been fixed already ¿?
![Mar-31-2022 16-19-39](https://user-images.githubusercontent.com/1983672/161077619-9e527c86-540f-40c2-8300-8c7ece6095fc.gif)

**Comment by owlas** [comment]
True I just tried this in prod!
