### ISSUE TITLE
Table information is not aligned properly on the 'Explore' page.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1482]
![Screenshot 2022-03-02 at 11 37 19](https://user-images.githubusercontent.com/12776522/156354854-3e269d9a-0412-40d9-a004-abf786d0a2d7.png)

The 'Table' info is not properly left-aligned like the rest of the information. Not sure if theres a reason for this but it looks a tad bit broken!

**Comment by Sync271** [comment]
https://github.com/lightdash/lightdash/blob/83a900f0af1df88975c3396c4fea1120fe6513f0/packages/frontend/src/components/Explorer/ExplorePanel/ExplorePanel.styles.ts#L21-L23
Extra padding has been added to the title, just have to remove the padding.
I can make a PR if assigned.

**Comment by ZeRego** [comment]
@Sync271 yeah, we can get rid of that styled component 👍  you can open a PR :)
