### ISSUE TITLE
Save chart modal should be more helpful and prompt better naming of charts. 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1487]
### Description: What is it?
The modal to save a chart could be more helpful in terms of giving users tips/hints on how to name it properly. This can set them up for success and make them understand how this might be useful to the data consumer eventually. Also, 'Create' as the title is a bit confusing. It should be 'Save chart' for consistency. 

<img width="517" alt="Screenshot 2022-03-02 at 13 45 35" src="https://user-images.githubusercontent.com/12776522/156374569-cd6db67a-4c03-467b-9b40-9e4b14df3dd3.png">

- [ ] **Change Modal title** `Create` -> `Save chart`
- [ ] **Change instruction**  `Name` -> `Enter a memorable name for your chart`.
- [ ] **Add placeholder text** `eg. How many weekly active users do we have?`
- [ ] **Change CTA** `Create` -> `Save`
- [ ] **Change Save button** from `Primary intent` to `Success intent`. (green!)

**Comment by rephus** [comment]
Probably belongs to another ticket already, but the action `Create dashboard with chart` pops up the same modal 
![image](https://user-images.githubusercontent.com/1983672/161766308-f99dd2ba-641c-48c5-9aa7-e37af7c68cb4.png)

![image](https://user-images.githubusercontent.com/1983672/161766218-8b8a4c86-3fbc-490f-b1bc-b9f65e86922e.png)


I modified the modal component to keep it as it is, by adding optional arguments, but we should considering updating that usage too.

**Comment by PriPatel** [comment]
@rephus ok nice! yeah, good point the 'Create dashboard' modal should be different. It is *sort* of covered somewhere else but I think its better to add a new ticket. 

Thanks for this!
