### ISSUE TITLE
You should be able to add users one-by-one instead of with an invite link

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1508]
### Description: What is it?

Instead of adding users using an invite link (that's open for anyone to use), you should be able to add users one-by-one using an email address or some other unique identifier.

### Problem: What problem does this solve?

Invite links can be less secure for inviting people to your BI tool because they can be used by anyone (without you noticing). 

### (Optional) Why: How do we know this is a real problem and worth solving?

https://getdbt.slack.com/archives/C026WJE4A69/p1646632168064199

### Success: How will we know if we’ve solved this problem?

You're able to add users using a unique identifier for that user. 

### Audience: Who are we building this for?

People who are project admins. 

### What: Roughly, what does this look like in the product?

Instead of using an invite link, you should have the option to `add users using email address` or something similar.

**Comment by TuringLovesDeathMetal** [comment]
I think we created the invite link approach because for us to be able to send people emails, on self-hosted, you’d need to set up an email server (which is a bit complicated).

Not sure if this has been simplified at all though since we built the reset password feature?

**Comment by ZeRego** [comment]
Closed by #2267
