### ISSUE TITLE
Adding a dashboard filter breaks the table visualization type

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1515]
### Describe the bug

If you add a dashboard filter that affects a table chart type, then the table chart type breaks. 

### To Reproduce

https://www.loom.com/share/8b46433246524f7a89ebed8df445ed55

### Expected behavior

Dashboard filters should work on table visualization types.

**Comment by ZeRego** [comment]
No longer reproducible
