### ISSUE TITLE
You should be able to easily calculate column totals

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1527]
### Description: What is it?

There should be a way to easily toggle a box on or off to see a column's totals. 

### Problem: What problem does this solve?

Totals are commonly used to just quickly scan over your results. Having a quick option to turn these on or off would help users become more effective at getting the results table they want. 

### (Optional) Why: How do we know this is a real problem and worth solving?

https://getdbt.slack.com/archives/C026WJE4A69/p1646713905352069

### What: Roughly, what does this look like in the product?

<img width="1778" alt="Screenshot 2022-06-06 at 11 09 41" src="https://user-images.githubusercontent.com/11660098/172141205-4d198f98-589d-4c68-a2f0-5351d0e4c0e8.png">

- [ ] If there are multiple pages, the `column totals` represent the totals over _**all**_ the data (not just the data on the page you see)
- [ ] If you click on `scroll page` (i.e. see all results), the `column totals` are summed over the _**entire**_ column.

A toggle near the bottom maybe by the results that lets you turn column totals on/off

<img width="361" alt="image" src="https://user-images.githubusercontent.com/31848148/157261493-2089b3d2-d9c7-4056-b795-70cba8d6d1c8.png">

**Comment by JohnRomanski** [comment]
+1 for this feature.
