### ISSUE TITLE
Support for browser based auth for snowflake on local deployments

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#153]
Haven't tried this auth-flow but if it's similar to gcloud sdk config, it could be possible

Looking here: https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#label-browser-based-sso

this may not be possible

**Comment by TuringLovesDeathMetal** [comment]
nobody's requested this...and we can't figure out how to do this...so this is not being prioritzed at the moment
