### ISSUE TITLE
Colour picker breaks when you try to add custom colour hex

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1531]
### Describe the bug

When you get to the third character of the custom colour hex, it automatically adds the colour you've typed in the first 3 characters (it won't let you finish the 6 characters) 

### To Reproduce

https://www.loom.com/share/e4360cc7c83e4401b0ad256dedf678b6

### Expected behavior

You should be able to add full colour hex codes

**Comment by ZeRego** [comment]
Problem: the component library recognises the first 3 chars as a valid hex ( e.g 000 is the same as 000000 ). The library doesn't seem to have any option to disable this behaviour.

**Comment by rephus** [comment]
I agree with @ZeRego 3 chars are valid, so the component triggers the onChange method when that happens, then we close the popup https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/ChartConfigPanel/Series/SeriesColorPicker.tsx#L27

May I suggest we don't close the popup on change , just by doing blur . like here: 
![Mar-31-2022 16-31-04](https://user-images.githubusercontent.com/1983672/161080445-f85966d6-ebf3-4436-91c4-5a8de1b73cb3.gif)

@TuringLovesDeathMetal @nathaliabj what do you think ?
