### ISSUE TITLE
You should be able to group by many dimensions in a chart

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1537]
### Description: What is it?

You should be able to group by many dimensions. Right now, you can only group by 1.

### Problem: What problem does this solve?

Our charts only let you configure one column to group by. This means that if you have 3 dimensions in your table that you're grouping your metric by, then it's not represented properly in the chart (you have duplicated rows for the grouped dimension)

### (Optional) Why: How do we know this is a real problem and worth solving?

https://getdbt.slack.com/archives/C026WJE4A69/p1646689676278539

### What: Roughly, what does this look like in the product?

- [ ] In the chart configs space, you should be able to add many fields to the `group` (similar to the x & y). 
- [ ] When these groups are added to the chart, the legend label should just have the multiple field values concatenated with a `-` between them. E.g. if I was grouping by product type then by colour, I'd expect my legend labels to be like `shoes - orange`, `shoes - yellow`, `skirts - orange`, etc.

**Comment by JohnRomanski** [comment]
Not sure how grouping compares to 'pivot tables' #1184 (and the docs don't explain grouping well.)

**Comment by ZeRego** [comment]
Ran a few tests manually to have an idea of the impact of the row limit.

Tests when querying 1 column:

|  Rows | Response Size  |  Response time | UI update/unresponsive time  |  
|---|---|---|---|
|500|    63kB |  2.09s | instant  |
|5000  |  613kB | 2.40s  | seconds  |  
|50000   |  7.0 MB |  7.04s | around 1 minute  |  
|100000   |  14.8 MB |  16.09s | around 5 minutes  |  

Tests when querying 2 columns:

|  Rows | Response Size  |  Response time | UI update/unresponsive time  |  
|---|---|---|---|
|500|    110kB |  4.38s | instant  |
|5000  |  1.1MB | 5.76s  | seconds  |  
|50000   |  11.7 MB |  15.50s | around 1 minute  |  
|100000   |  24.1 MB |  24.47s | around 5 minutes  |  

**UI update/unresponsive time** column is not only to load the results but also reflects on each user action that involves data. Example: change chart/table configuration

**5000** seems to be the value that provides the best user experience.
