### ISSUE TITLE
Update the loading state for dashboard filters

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1539]
### Description: What is it?

The loading state for dashboard filters makes it look like there's an error (while refresh dbt is happening)

<img width="638" alt="image" src="https://user-images.githubusercontent.com/31848148/157640803-2296bbde-2590-4d4a-a960-929ab0620187.png">

We should update the loading state so it's just a spinning wheel or there's some indication that `refresh dbt` is happening and that's why it's loading. 

### Problem: What problem does this solve?

It's confusing when it looks like there's an error, but really you just have to wait it out.

### What: Roughly, what does this look like in the product?

Ideally, the loading state would tell you what's happening (e.g. `refreshing dbt - should be ready in a couple of seconds!` or something like that)

**Comment by ZeRego** [comment]
This has been fixed in #2366
