### ISSUE TITLE
When you add a value to a string filter in the dashboard, `apply` doesn't become a primary button colour

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1540]
### Describe the bug

When you add a string filter to a dashboard and you don't change the `is equal to` to any other logic, and you add a value, the `apply` button doesn't get highlighted (but it's still clickable)

### To Reproduce

https://www.loom.com/share/cdfc08891b2a42e9b7fcf1c421828049

### Expected behavior

The `apply` button should become a primary action when you add a value.

**Comment by ZeRego** [comment]
Not sure if this is bug and how we could we change the behaviour. That filter has a multi value input where the values are only recognised on blur (when the input loses focus). 
Example:
https://www.loom.com/share/d5c788dfa3534fe4ba3774ef512dc824

**Comment by PriPatel** [comment]
<img width="964" alt="Screenshot 2022-03-10 at 10 36 52" src="https://user-images.githubusercontent.com/12776522/157645163-36a44703-c3db-4f57-bbe5-af5d61898c14.png">
I guess this is the same behaviour here. It probably needs to be made clear that these are multivalue and the user has to hit 'enter' everytime,
<br>


<br>

@ZeRego are you saying that the apply button can't become active when the field is NOT empty and the user hasn't hit enter?
If so, what if the Apply button is always active instead? If the user hits it when nothing has been selected, we could show an error message? What do you think? 
<img width="338" alt="Screenshot 2022-03-10 at 10 47 01" src="https://user-images.githubusercontent.com/12776522/157646162-d2a92b82-1c32-4d09-bbb3-57f341bab9bd.png">
