### ISSUE TITLE
Replace environment variables with lightdash.yml

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#156]
Config is getting a bit heavy weight for environment variables only. And we have branching code based on some (e.g. `LIGHTDASH_SPAWN_DBT`

It would be better to have a `lightdash.yml` file with basic config.

**Comment by ZeRego** [comment]
We should a `Config` class that has all the logic to identify and merge all the user configs.

Configuration power logic:
**default values** < **yml values** < **environment variables** 

We should also update the documents to mention the default values and all the different combinations to set the configs.
