### ISSUE TITLE
Allow project deletion

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1561]
- Add endpoint to delete project
- Add button to delete project ( with confirmation modal ) 

![Screenshot 2022-03-21 at 18 32 43](https://user-images.githubusercontent.com/9117144/159340602-6a37965c-44aa-404b-9e99-d7bfa1a10988.png)

**Comment by owlas** [comment]
**Backend**
 - [ ] ProjectModel
 - [ ] ProjectService (calls model + add tracking + permissions)
 - [ ] API (router)

**Common**
- [ ] openapi.json

**Frontend**
- [ ] Update hooks for delete project
- [ ] Add UI components

**Comment by ZeRego** [comment]
@rephus another note: we should prevent the user from deleting the last project, similar to what we have for users.

**Comment by rephus** [comment]
> @rephus another note: we should prevent the user from deleting the last project, similar to what we have for users.

That should be a backend check, right ?

**Comment by ZeRego** [comment]
Both. In the BE preferably inside a knex transation to avoid the same race condition we have in the user service. 
The FE should just disable the button if there is only 1 project available.

**Comment by owlas** [comment]
@ZeRego the backend would work fine with no projects right?

Wouldn't we just need a frontend to handle the empty state?

**Comment by rephus** [comment]
If I remove all projects , I get the following response when listing projects `/api/v1/org/projects?`

```
{
    "status": "error",
    "error": {
        "statusCode": 404,
        "name": "NotExistsError",
        "message": "No project exists",
        "data": {}
    }
}
```
And the frontend will redirect to the `createProject` page 

So maybe we don't need any restrictions in frontend or backend.

**Comment by owlas** [comment]
Nice!! Although I'm surprised this 404s rather than 200 with empty list.
