### ISSUE TITLE
Lightdash spinner missaligned

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#1563]
### Describe the bug

Lightdash spinner icon looks missaligned IF there is a browser banner in the browser at the same time (for example, the bitwarden banner)

Tested in both Opera and Chrome with Bitwarden extension

![Mar-22-2022 10-33-16](https://user-images.githubusercontent.com/1983672/159450727-b5f2d82d-da9e-45d2-a4bd-76559b75fca5.gif)

It is relatively easy to spot this issue after registering if you are using a password manager or a similar extension. 

### To Reproduce

0. Use Chrome or Opera with bitwarden extension
1. Register on lightdash (or logout and login again) 
2. Normally after adding a password, bitwarden (or a similar software light lastpass) might ask you to save the password
3. While the banner is active, refresh the page

### Expected behavior

The lightning icon should be centered in the spinner

**Comment by owlas** [comment]
Nice! @rephus were you able to reproduce this in multiple browsers or only opera?

**Comment by rephus** [comment]
> Nice! @rephus were you able to reproduce this in multiple browsers or only opera?

I haven't tried yet, I've only seen it in opera (in both linux and mac) because it is were I got my extension, but I'll try it on chrome too

**Comment by rephus** [comment]
This is also happening in chrome
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1983672/159453790-458202ff-3f8c-4e81-a16c-bb4b08ea2738.png">

**Comment by owlas** [comment]
Awesome thanks!

**Comment by rephus** [comment]
Still happening, I see it everything I login and have the password manager extension enabled.

**Comment by ZeRego** [comment]
I'm seeing this issue in the create project page without a browser banner.
![Screenshot 2022-06-14 at 10 31 58](https://user-images.githubusercontent.com/9117144/173608292-081c7d0e-e265-4f04-9828-5522ee4f6f6f.png)
