### ISSUE TITLE
Set name and colour of individual series, not only metrics

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1565]
### Description: What is it?

Currently I can only rename / colour metrics on the y-axis. However if I group by metrics, I cannot colour the individual series.

User should be able to rename and recolour any of the series on the chart.

### Problem: What problem does this solve?

When I'm using grouped metrics, it's impossible to configure the look and feel of my chart and to colour the individual series how I'd like them

### What: Roughly, what does this look like in the product?

The series tab in the chart config should show all the series when I group. 

**Example without grouping**

<img width="363" alt="Screenshot 2022-03-22 at 14 16 16" src="https://user-images.githubusercontent.com/11660098/159502371-7c290154-83e5-434b-9abd-c3c3d0a7475f.png">

**Example with grouping**
<img width="338" alt="Screenshot 2022-03-22 at 14 16 42" src="https://user-images.githubusercontent.com/11660098/159502453-c389fec6-9306-46d2-a20e-33945f800695.png">

I would expect these to look the same

**Comment by owlas** [comment]
Chatting with @ZeRego we've decided to move the chart configuration object to match exactly eCharts and generate that using the frontend.

I'll post some examples here soon!

**Comment by PriPatel** [comment]
[Prototype ](https://www.figma.com/proto/ayHkLusYRiPx3F33SjrqGP/Chart-config-Wireframes-WIP?node-id=222%3A856&scaling=min-zoom&page-id=128%3A50&starting-point-node-id=222%3A856&show-proto-sidebar=1)

Related design files [here](https://github.com/lightdash/lightdash-internal-work/issues/236)
