### ISSUE TITLE
Replace chart layout buttons with autocomplete fields

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1568]
### Description: What is it?

The buttons to configure the layout of a chart are difficult to use. Looking at the array of buttons is confusing.

Instead we should use an alternative UI (drop downs or drag and drop) to configure which fields are shown on the chart.

<img width="387" alt="Screenshot 2022-03-22 at 14 29 47" src="https://user-images.githubusercontent.com/11660098/159505436-a094f088-4bc4-40d7-9eb0-b731ac388d22.png">

**proposal**

* 1 x-axis field max
* 1 or many y-axis fields
* optional grouping field

https://www.figma.com/file/ayHkLusYRiPx3F33SjrqGP/Chart-config-Wireframes?node-id=146%3A1202 

<img width="415" alt="Screenshot 2022-03-22 at 14 31 24" src="https://user-images.githubusercontent.com/11660098/159505823-a82c7b71-bcb5-4096-ae18-01ae4f88f3fa.png">

**Comment by ZeRego** [comment]
We should fix this bug https://github.com/lightdash/lightdash/issues/1569 when we change this layout
