### ISSUE TITLE
x,y are the wrong way around for horizontal bar charts

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1569]
### Describe the bug

For horizontal bar charts, the chart configuration has the wrong labels for `x` and `y`

<img width="1492" alt="Screenshot 2022-03-22 at 15 01 00" src="https://user-images.githubusercontent.com/11660098/159512478-463d0543-b0df-46ea-b5b9-55ae9cd3864e.png">

### To Reproduce

Create a horizontal bar chart, e.g.: https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/saved/a07dfedc-b013-40ca-a9c3-703460af1685

open the chart configuration panel

#### Change the labels

We could just conditionally change `x` and `y` for horizontal bar charts.

#### Keep labels but allow user to specify the directional axis

Alternatively we could have it so the user can specify:
* chart goes from left to right = 1 x-field + many y-fields = column bar chart
* chart goes from top to bottom = 1 y-field + many x-fields =

**Comment by ZeRego** [comment]
Should be fixed in #1568 changes
