### ISSUE TITLE
You should get a warning/some indication if you're about to change a saved chart that's used in many places

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1575]
### Description: What is it?

When you update a saved chart that's used in a bunch of dashboards, you should get a warning/some indication that your changes will affect many dashboards (not just the one you were on). 

### Problem: What problem does this solve?

It's hard to know if the chart you're changing has an impact beyond your dashboard - e.g. should I create a new saved chart with my changes? or can I just change this saved chart?

### What: Roughly, what does this look like in the product?

Some indicator that is prominent when you're editing a saved chart used in many dashboards. Basically, you should see it before you hit `save`. Ideally, you'd also be able to see which dashboards your changes would be affecting (i.e. the list of hte dashboards that the saved chart is in) and you'd be able to click on these dahsboard links to open them in a new tab+ inspect them. 

Other option would be to have a warning when you hit save, but I think that could get annoying.

**Comment by TuringLovesDeathMetal** [comment]
oooh yes! that's a great idea. Like having some info when you're in `edit` mode (or viewing it from the list) which is like "this chart is used in 5 places" and listing the dashboards it's used in if you click on "more info"

**Comment by 12ian34** [comment]
Still very relevant

**Comment by PriPatel** [comment]
This is solved by https://github.com/lightdash/lightdash/issues/5453 as you would have the information available to you through the information icon.
