### ISSUE TITLE
Error on organizationMemberAbility.mock.ts when recompiling

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#1578]
### Describe the bug
This is a problem we have where tsconfig includes test files and the hot reloading messes up sometimes
When running docker-compose.dev 

![image](https://user-images.githubusercontent.com/1983672/159887277-f46b0ae9-f96a-4681-bd88-ab0fe49f235d.png)

### To Reproduce

1. Run local env using  docker-compose.dev 
2. Work
3. Sometimes, on compile, that error happens

### Expected behavior

No errors on compile

**Comment by rephus** [comment]
will this get fixed by https://github.com/lightdash/lightdash/pull/2969 @IrakliJani  ?

**Comment by IrakliJani** [comment]
@rephus yes
