### ISSUE TITLE
Add LOG_LEVEL config + export log file

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#158]
Lightdash should have a log level config where the user can define what type of logs it want to see in the console. This is going to reduce the current log spam in the console log.
We should also have an easy way to export/download the log file. This is going to help us when people open github issues.

**Values:** info, warning, error
**Default:** error ( with the exception of the server start log )

Work:

- [ ] Documentation: Add guide 'How to debug'
- [ ] Documentation: Update 'Common errors' 
- [ ] Code: handle new config
- [ ] Code: provide way to export/download log file

**Comment by TuringLovesDeathMetal** [comment]
this would be really useful!

**Comment by owlas** [comment]
@ZeRego I think this is solved in #943
