### ISSUE TITLE
Time series charts should be shown in chronological order by default

### ISSUE THREAD

**Issue by JoelAlander** [lightdash/lightdash#1595]
### What's the problem?

If I select a metric + a time/date dimension and I _**don't**_ add any ordering, then I expected my values to be plotted in chronological order by default. 

instead, I have to add ordering, then re-plot my values. 

### What do you want to change? 

- [ ] By default, if I have _**no**_ ordering applied to my results table, and I have a time/date on the x-axis, the values on the y-axis should be plotted in chronological order.
- [ ] If I _**have**_ added ordering to any of the columns in my table, then the time series should be plotted following the ordering I've applied in my table. 

## Original issue:
When choosing line chart visualisation and having time dimension (e.g. month) Lightdash doesn't always draw time series data in chronological order. 

### To Reproduce

In Lightdash go to explore => tables. Select table which has time dimension & at least one metric. Select time dimension, a metric, and optionally second dimension => Run query => Remove sorting by time dimension from results and sort by another column => click charts and select line chart

### Expected behavior

Line chart should always be drawn in chronological order.

### Screenshots or Loom video

![image](https://user-images.githubusercontent.com/33990367/160417497-ad8bdb18-2f32-417c-a475-4a774d15040b.png)

**Comment by TuringLovesDeathMetal** [comment]
ooh, yes - this is definitely what I'd expect to be the default behaviour. Nice catch!

**Comment by TuringLovesDeathMetal** [comment]
@all-contributors add @JoelAlander for bug

**Comment by TuringLovesDeathMetal** [comment]
Note: if we default to ordering your chart in ascending order, there needs to be some way to "turn off" this ordering in teh chart configs I think? 

Maybe not...we can leave it for now, and then if someone complains there's no way to "turn it off", then we can build it :)
