### ISSUE TITLE
Add `project_id` to all analytics events

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1599]
### Description: What is it?

With the implementation of multiple projects, we now need to know which project a user is triggering their events in. 

This is important for use cases where there are different teams using different projects, and we want to know the overall adoption of Lightdash in different teams. 

Every event should have a `user_id` and a `project_id`

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal - can we make the goal for this ticket to be able share a usage report with Joni from Swappie by next Tuesday? Either as part of this ticket or a separate one - but that should be the main reason we do this week!
