### ISSUE TITLE
Axis labels should appear along the axes by default (not above them)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1602]
### Description: What is it?

Axis labels normally are written along the axes, not above the axes. It would be great if this was the default behaviour. 

### Problem: What problem does this solve?
If you add two axes, with labels, and you have a legend, your chart looks _**really**_ messy.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/31848148/160591780-1a911ce8-0ee2-416f-a1d0-a8915cf9bf43.png">

### What: Roughly, what does this look like in the product?

If you override the axes labels, it should add the labels along the axes by default, like this:
![image](https://user-images.githubusercontent.com/31848148/160592014-639fbe3a-7547-46f5-830e-88633ac73240.png)

**Comment by TuringLovesDeathMetal** [comment]
Ya, we only add y-axis labels if users override them right now. 

Related issue: #2702 

^Once we implement #2702, then it should be _**always**_ along the side, by default

**Comment by rephus** [comment]
There is an open issue on echarts about overlapping items when moving legends to the bottom, I can replicate the issue. Should we "wait" until it gets fixed ? 

https://github.com/apache/echarts/issues/14724
![image](https://user-images.githubusercontent.com/1983672/179460152-f73d52ae-944d-4697-8468-f4dc2a6d44e5.png)
