### ISSUE TITLE
Update the defaults for chart configs

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1607]
### Description: What is it?

There should be better defaults for chart configs (now that we've updated a bunch of the chart configurations)

### What: Roughly, what does this look like in the product?

https://github.com/lightdash/lightdash-internal-work/issues/242

**Comment by ZeRego** [comment]
We should only need to change the following hook for this ticket: 
https://github.com/lightdash/lightdash/blob/53a56b7d6fc0e4f73dee3a9016628685eaf61aa5/packages/frontend/src/hooks/useCartesianChartConfig.ts#L189

**Comment by rephus** [comment]
I'm looking into this
