### ISSUE TITLE
You should be able to hide a series within a group from your plot

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1620]
### Description: What is it?

If I have grouped my data, I want to be able to hide one/some of the series from my group in my plot. 

### Problem: What problem does this solve?

Right now, if I group by something, I have to show all of the series in my plot by default. But sometimes, if I'm doing an aggregation over my groups, then I only want to show one of the series. 

For example, in this table. I have the table calculation on the far right which I've aggregated over my dimension groups (so it's the same value for each group). I only want to show _**one**_ of these groups on the chart, since all series in the groups will have the same values. 
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/31848148/160839739-0b8b16ee-f241-449f-8cb8-d11bbb58c38e.png">

Right now, to hack this, I create a series that's white and I override the chart label with `.`

<img width="340" alt="image" src="https://user-images.githubusercontent.com/31848148/160839997-904f8d97-6af9-493a-b7bf-3d03d4c9e299.png">

### What: Roughly, what does this look like in the product?

In the `series` tab, you should be given the option to hide a series. By default, all series should be shown

**Comment by rephus** [comment]
![Peek 2022-04-05 10-52](https://user-images.githubusercontent.com/1983672/161717257-8e2acb7c-c095-4136-a903-28ca11548f00.gif)
