### ISSUE TITLE
Format big number charts

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1624]
### Description: What is it?

If I have a big number chart, I'd like to format it with currency and percentages

**Comment by rephus** [comment]
@owlas I'd like to have a better description so I can work on this ticket. for example: what is a big number ? do we have a sample on jeffle shop ? steps to replicate .

I guess we can just display the new formatted value (only if it is bignumber  ) on charts, right ?

**Comment by owlas** [comment]
<img width="416" alt="Screenshot 2022-04-01 at 11 47 05" src="https://user-images.githubusercontent.com/11660098/161249081-79651421-4a95-415d-a238-aeebb7c8db2b.png">

Yep it's done! Thanks @rephus !!
