### ISSUE TITLE
You should be able to show/hide the legend on your plot.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1629]
### Description: What is it?

You should have the option to show the legend on your plot, or have it hidden

### Problem: What problem does this solve?

If we implement series for ungrouped metrics being shown in your legend, then it will be annoying to have them always shown in the legend. 

### What: Roughly, what does this look like in the product?

there should be an option in the series tab to show/hide legend.

**Comment by TuringLovesDeathMetal** [comment]
kind of related to #1850

**Comment by hamzahc1** [comment]
This has been requested again by a Cloud user! This should be relatively simple to implement as it just requires removing the legend component? cc @ZeRego

**Comment by hamzahc1** [comment]
It's also worth mentioning that the expected behaviour or hiding the legend should be for the chart to take up more of the whitespace
