### ISSUE TITLE
The "chart no longer available" image should have some indication of what chart used to be there

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1630]
### Description: What is it?

<img width="885" alt="image" src="https://user-images.githubusercontent.com/31848148/161022130-2dd7f9c2-5179-4d75-84c0-94d44ca1734c.png">

When a user hits this image, there should be some indication of what chart used to be there (ideally the title of the deleted chart). _**But**_, only if the chart was deleted (not if they don't have permissions to view it). 

### Problem: What problem does this solve?

If you run into one of these deleted charts, it's really hard to know what used to be there/what should replace it. 

Also, you have no idea if it was actually something important that _**shouldn't**_ have been deleted from your dashboard, or if it was an old chart that shouldn't have been there anyways. 

### What: Roughly, what does this look like in the product?

Ideally the title of the old chart would be in greyed-out font at the top and the rest of the copy would stay the same. 

But, this should only happen for deleted charts. Not for charts that you don't have permissions to access (because there could be sensitive information in the title).

**Comment by TuringLovesDeathMetal** [comment]
^This might actually be solved by #1631

**Comment by PriPatel** [comment]
<img width="329" alt="Screenshot 2022-04-04 at 13 54 25" src="https://user-images.githubusercontent.com/12776522/161548289-e4f5eb51-574d-468a-9e3f-c73318820065.png">
At the very least, perhaps just the name of the chart can stay?

**Comment by owlas** [comment]
What about if I deleted it because I didn't want anybody to see it? Including the title name? I'm wondering if #1631 is more helpful?

**Comment by TuringLovesDeathMetal** [comment]
We think that this is a solution, but not the best solution for the problem. 

Instead, we should think about the problem: "I'm confused when I see this chart deleted thing."

- #1631 might solve this (and potentially just removing the charts from the dashboards automatically, not leaving this space holder.)
