### ISSUE TITLE
You should get a warning/indication if you're about to delete a saved chart that's used in many places.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1631]
### Description: What is it?

You should get a warning/indication if you're about to delete a saved chart that's used in multiple dashboards. Maybe listing the dashboards that are using the chart. 

### Problem: What problem does this solve?

If you're deleting a chart, you don't actually know what impacts it's going to have.

### What: Roughly, what does this look like in the product?

similar to #1575 and related to #887 

You should get a modal that tells you the chart name and also the list of dashboards it's used in. 

### Implementation

- [ ] Backend: add new api endpoint to search dashboards by included chart id 
- [ ] Backend: (ALTERNATIVE) add all linked dashboards to `SavedChart` object
- [ ] Frontend: update modal design
- [ ] Frontend: make query for linked dashboards (or access `SavedChart` property, see alternative)

**Comment by PriPatel** [comment]
**Modal when user is about to delete a chart which appears in 1 or more dashboards:**
<img width="518" alt="Screenshot 2022-04-04 at 15 39 56" src="https://user-images.githubusercontent.com/12776522/161568354-6bd4bed1-0c7c-40e3-aa89-e18a7f5c02bb.png">

**Modal when user is about to delete a chart which does not appear in any dashboards:**

<img width="462" alt="Screenshot 2022-04-04 at 15 40 01" src="https://user-images.githubusercontent.com/12776522/161568361-826dff03-9534-498f-9493-362ad71d5ad7.png">

**Comment by owlas** [comment]
@PriPatel in your design, I was confused at first that the modal was asking me "how many new users do we have this week?"

**Comment by PriPatel** [comment]
@owlas Nice - thanks! I've updated my original comment.

**Comment by owlas** [comment]
Beast, looks great!
