### ISSUE TITLE
Hide table information on the Explores page by default. 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1635]
### Description: What is it?
There is way too much content for the user to take in when they try to run a query. They might look at the table information once or twice but it doesn't need to be visible at all times. 

For now we could just hide the info under the dropdown. It makes things much cleaner and gives more space for the user to carry out the primary goals.  (not a final design, just a sketch) 
<img width="831" alt="Screenshot 2022-03-31 at 18 18 24" src="https://user-images.githubusercontent.com/12776522/161113570-2f2f2a90-f366-48db-af4a-3e340d95acbd.png">

**Comment by TuringLovesDeathMetal** [comment]
A user raised this point the other day!

**Comment by ZeRego** [comment]
This PR closes this https://github.com/lightdash/lightdash/pull/2083
