### ISSUE TITLE
All the tooltips say "open documentation" - they should be more helpful

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1641]
### Description: What is it?

All the tooltips in our connections page say "open documentation". This is annoying because it should have 1 - 2 sentences explaining how to fill out that field. It can feel misleading that I'm about to get help but instead I get a message saying open docs (even if it opens to a relevant page, it doesn't feel right). 

<img width="813" alt="Screenshot 2022-04-01 at 10 52 15" src="https://user-images.githubusercontent.com/14341285/161240805-179df5d9-2848-485f-8f61-73072bcb0785.png">

### What: Roughly, what does this look like in the product?

Each field should have help with advice specific to that field rather than always linking out to docs. It can then also have a link out to the docs if you need more help

**Comment by PriPatel** [comment]
I mockup up a potential solution to this a while ago - it could still be relevant!
https://github.com/lightdash/lightdash/issues/1023

**Comment by hamzahc1** [comment]
Perfect! I'll close this in favour of that then
