### ISSUE TITLE
You should be able to add a label for the `total` in a stacked bar chart

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1652]
### Description: What is it?

Right now, when you add value labels to a stacked bar chart, it only adds values for each of the components in the stacked bar. There should also be a way to add a total value label to the stacked bar chart. 

### Problem: What problem does this solve?

It's much easier for end-users to see a stacked total value (if that's what's important in your chart) than trying to sum up the values in their head.

### (Optional) Why: How do we know this is a real problem and worth solving?

Feedback from Colin at Nayuta. 

### What: Roughly, what does this look like in the product?

- There should be a way to add `totals labels` in a stacked bar chart  
- You should also be able to _**only**_ show the totals, and not show the grouped values (by keeping grouped values as "hidden" and having total label as "show")
- you should be able to show the totals _**and**_ the grouped values as well (by having both as "show")
- I'm imagining something at the top-level of a group like a drop-down option for `total label` (the option wouldn't be available at a series level). E.g. in this screenshot, I'd have an option under `Pages Anonymous device count (grouped)` for `show total` or `total label`. This would be the same format as our other labels (i.e. a drop-down with the options "Top", Bottom, etc.)

<img width="345" alt="image" src="https://user-images.githubusercontent.com/31848148/195164571-85890db8-d6e1-42b9-af3e-d8bb46093cd5.png">

**Internal design ticket:** https://github.com/lightdash/lightdash-internal-work/issues/300

**Comment by TuringLovesDeathMetal** [comment]
![image](https://user-images.githubusercontent.com/31848148/165782919-2be3af8e-d0d7-48eb-9964-e2d74b850375.png)

**Comment by TuringLovesDeathMetal** [comment]
This has been de-prioritized because it's actually a lot of work in echarts to try to make this happen

**Comment by hamzahc1** [comment]
Requested again by a user: https://lightdash.slack.com/archives/C044NHRAX0T/p1665506601062809
