### ISSUE TITLE
I want the string filter auto-suggestion to work before I've run my query

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1660]
### Description

The auto-suggestion for a string filter only works once I've run a query _**and**_ my results table contains the field that I want to filter on. 

### To Reproduce

1. Try adding a filter on a string field, then see if auto-suggestion works. 
2. Add some other fields to the results table (**not** your filter field), run it, see if auto-suggestion works. 
3. Add the field you want to filter on to your results table, run it, see if auto-suggestion works (it should!)

### Expected behavior

I know that we can't auto-suggest unless we have the results from a run query, but is there a way to either:
1. make it so we can always auto-suggest
2. make it more clear in the UI/UX _**when**_ you can expect auto-suggest to work.

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal I don't think this is a bug since the behaviour described was what we intended to implement. 

The problem with the solution you'r proposing is that we would need to store all the possible values for each column in our DB. So far I know we don't want to store any data from the user warehouse in our own database since that brings a lot of responsibility to our side. @owlas let me know your thoughts

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal the other option we have is to run a query against their warehouse, to get the top X results, for each string dimension filter. 
What would be the cost impact for users since their warehouse might change for computation/number of calls/etc.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego I think we should do #1995 regardless of what else we add.

>since their warehouse might change for computation/number of calls/etc

Do you mean `charge` not change?

**Comment by 12ian34** [comment]
Has been requested twice by prospects recently.

**Comment by gordonkjlee** [comment]
I would suggest
1. If dbt [accepted_values](https://docs.getdbt.com/reference/resource-properties/tests#accepted_values) test is specified, show those values.
2. lightdash could create a dbt package (configurable) that indexes distinct column values and populates them into some tables that is read by the application. Or perhaps a [dbt package](https://hub.getdbt.com/) already exists for this?
3. or this can be done [within the application](https://github.com/lightdash/lightdash/issues/1660#issuecomment-1167514626) for topX or distinct values
