### ISSUE TITLE
I want to be able to organize my dashboards/saved charts into folders.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1662]
### Description: What is it?

I want to be able to group my saved content into folders in my project.

### Problem: What problem does this solve?

It's hard to navigate a long list of saved charts/dashboards. It's also hard to group saved charts with dashboards into a single space.

### (Optional) Why: How do we know this is a real problem and worth solving?

Colin from Nayuta

### What: Roughly, what does this look like in the product?

- [ ] You can have dashboards + saved charts in the same folder
- [ ] From the saved chart/dashboard space, I should be able to move content to a specific folder. 
- [ ] I should be able to create folders from the space where I'm browsing folders
- [ ] I should be able to save charts/dashboards into a specific folder when I first save them. 
- [ ] I can create a new folder and save a chart into it from within the `save chart` flow (similar to dashboards?)
- [ ] there should be some way to access this folder structure from the navbar
- [ ] saved charts + dashboards can only belong to one folder
- [ ] You can delete folders
- [ ] If you delete a folder, you delete all of the contents in that folder (saved charts + dashboards)
- [ ] you can have a folder within a folder

**Comment by 12ian34** [comment]
This has also come up with another user recently.

**Comment by TuringLovesDeathMetal** [comment]
yep!
