### ISSUE TITLE
"Add chart to an existing dashboard" + "Create dashboard with chart" should both be under one action - "Add to dashboard"

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1665]
In order to make way for a bunch of other changes to the actions a user might carry out to their saved charts, we should group the existing actions appropriately.

![Screenshot 2022-04-04 at 12 54 08](https://user-images.githubusercontent.com/12776522/161538401-5f60b949-42fd-4457-8dd4-dd282a25a985.png)

The first action is to do with saving. The second and third actions are both about dashboards, yet they each have the same hierarchy as 'Save chart as'. 

 They shouldn't be separate actions. There should be one action - `Add to dashboard`. 
 From here, the user will be able to create a new dashboard as well. 
  
![Screenshot 2022-04-04 at 12 53 09](https://user-images.githubusercontent.com/12776522/161538253-ab3f4527-7b28-42b5-b17f-0c9eb4b46088.png)

**Comment by rephus** [comment]
It sounds like this was not needed then https://github.com/lightdash/lightdash/issues/1685 (already in progress)
