### ISSUE TITLE
There should be consistency around the Chart actions everywhere in the app.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1667]
**From the Saved Charts page:**
<img width="859" alt="Screenshot 2022-04-04 at 13 43 05" src="https://user-images.githubusercontent.com/12776522/161546041-2145e232-5e35-43e4-8d6b-c1295b94ad55.png">

<br><br><br>
**From a Saved Chart:**

<img width="520" alt="Screenshot 2022-04-04 at 13 43 41" src="https://user-images.githubusercontent.com/12776522/161546117-aa3f2935-20d9-4b4e-8411-121f248ca79d.png">
If user has not made any changes to the chart, "Save as new chart" should read "Duplicate Chart"

This makes sense once we have implemented #1190, #1654 and #1665

- [x] On the Saved charts page, dropdown items should be `Rename / Duplicate / Add to Dashboard / Delete`
- [x] On a Saved chart, dropdown items should be `Duplicate / Add to Dashboard / Delete` or `Save as new chart / Add to Dashboard / Delete `
- [x] Replacement icons [can be found here](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=2634%3A46887)
- [x] Add the context menu to the` Saved Charts' on the Homepage.
- [x] Change the dropdown component to have a menu divider so that 'Delete' is separate to the rest.
- [x] On an explore page, the first action item should either read `Duplicate`, or `Save as new chart` , depending on whether the user has made any changes to the chart.

**Comment by nathaliabj** [comment]
@PriPatel What do you mean with the 'context menu' ?

**Comment by PriPatel** [comment]
@nathaliabj 

By this I meant the saved charts on the Home page should look the same as the saved charts on the Saved Charts page.
<img width="817" alt="Screenshot 2022-04-11 at 09 09 18" src="https://user-images.githubusercontent.com/12776522/162693020-54d7d45f-b24a-4722-a5ed-71f70dbd385a.png">
 You should be able to see the dots and carry out the same actions:
 
1. Because the user should be familiar with that pattern.
2. Because we often create dummy charts to test things and they appear first on the homepage. It would be nice to delete them from here! 

Let me know what you think :)
