### ISSUE TITLE
I want to be able to export my dashboard 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1669]
### Description: What is it?

We have the ability to export charts, but I want to be able to export my dashboard.

### Problem: What problem does this solve?

You can't export a dashboard right now and share it to anyone outside of Lightdash

### (Optional) Why: How do we know this is a real problem and worth solving?

Colin from Nayuta

### What: Roughly, what does this look like in the product?
(related to #1294 ...kinda)

In the options menu for a dashboard, you should be able to click `export`. 

Then you should have the option to export as: JPEG, PNG, PDF

**Comment by 12ian34** [comment]
still relevant! just been requested by a prospective customer

**Comment by TuringLovesDeathMetal** [comment]
duplicate of #2895
