### ISSUE TITLE
Add more information in `source` for metrics

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#167]
The `source` button for dimensions is great because it includes _**all**_ of the metrics + other things that are joined onto the dimension definition. 

When you click on a metric, you _**only**_ see the source code for the metric. It would be really useful to see information on the _**dimension**_ it's defined from as well (otherwise I'd just have to go to the dbt source code to look at this anyways, so the source code we've displayed becomes a bit less useful). Basically, if the `metrics` source looked the same as the `dimension` source, that would be unreal <3

Dimension `source` view:
![image](https://user-images.githubusercontent.com/31848148/124444390-d55a1300-dd7e-11eb-904d-ffdb2c9eaba6.png)

Metrics `source` view:
![image](https://user-images.githubusercontent.com/31848148/124444439-e73bb600-dd7e-11eb-8696-f04137c2d916.png)

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal we can do that but we should still highlight the metric lines somehow.
What you think about this ?
![Screenshot 2021-07-05 at 11 04 33](https://user-images.githubusercontent.com/9117144/124455027-076c7480-dd81-11eb-8d83-238f84900fef.png)

**Comment by TuringLovesDeathMetal** [comment]
siiiiiick, absolutely LOVE this
