### ISSUE TITLE
I want a way to refresh my dashboard + all the results in it

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1670]
### Description: What is it?

I want a way to easily refresh my dashboard and all of hte charts/tables in it. 

### Problem: What problem does this solve?

I can see the last time my dashboard was updated, but I don't know how to refresh this. 

### (Optional) Why: How do we know this is a real problem and worth solving?

Colin at nayuta

### What: Roughly, what does this look like in the product?

Ideally there should be a `refresh` button on the dashboard. Or some way of refreshing from the options menu.

**Comment by TuringLovesDeathMetal** [comment]
related to #3693

**Comment by PriPatel** [comment]
Clsoed by https://github.com/lightdash/lightdash/issues/6796
