### ISSUE TITLE
If you have no saved charts in your project, there's no button to create a chart

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1674]
### Describe the bug

If there are no saved charts in your project and you navigate to the saved charts page, there's no option to create a chart. This feels like a broken UX. 

### Screenshots or Loom video

<img width="1147" alt="Screenshot 2022-04-04 at 19 29 52" src="https://user-images.githubusercontent.com/14341285/161608518-3d67ddce-9c73-45c9-a2ff-1e0957c52104.png">

**Comment by PriPatel** [comment]
We can use the dashboard message here:
<img width="753" alt="Screenshot 2022-04-04 at 19 44 12" src="https://user-images.githubusercontent.com/12776522/161610746-c4194ee7-b2de-4d66-9976-482eeb76b02e.png">
!
