### ISSUE TITLE
Update copy on "Create dashboard" modal 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1685]
<img width="578" alt="Screenshot 2022-04-05 at 14 55 59" src="https://user-images.githubusercontent.com/12776522/161770274-8ccd7ba8-218a-4b55-829c-0aaee39180a7.png">

- [ ] **Modal heading** `Create` > `Create dashboard`
- [ ] **Placeholder text** - `eg. KPI dashboard`
- [ ] **CTA** - change to `success-intent` (green)

**Comment by rephus** [comment]
@owlas I should refactor this too , right ? like in save chart
