### ISSUE TITLE
The chart panel should be open by default in some cases.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1687]
**The chart panel should be open when:**
- You open a saved chart from a dashboard
- You open a saved chart from the Saved Charts page
- You open a saved chart from a link that has been shared with you

**Chart panel should be closed when:**
- You start from a brand new 'Explore' and you hit `Run query`

**Comment by rephus** [comment]
By: `You open a saved chart from a link that has been shared with you`

Do you mean someone who is opening a link like `http://localhost:3000/projects/3675b69e-8324-4110-bdca-059031aa8da3/saved/ec874280-1e7b-4756-8bea-8da5dee5aa83` ? 

What about hitting refresh?
