### ISSUE TITLE
analytics event for updating the default chart colours

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1690]
### Description: What is it?

Tracking for the colour picker. 

When a user updates their default chart colours, we trigger the event: `lightdash_server_appearance_default_chart_colours_update`

**Comment by rephus** [comment]
afaik we have `useTracking / track` in the frontend and `analytics.track` on the backend, not sure if they do the same. 

This implementation makes more sense in the frontend, am I right ?
