### ISSUE TITLE
Disable some dbt models from appearing in lightdash

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#170]
### Context 
Currently all my dbt models appear in lightdash but I have a bunch of staging tables and things that aren't needed by the end user. 

### Goal
I want to be able to disable some of my models from appearing in lightdash

### Tickets
- [x] #762
- [x] #763
- [x] #764
- [x] #765
- [x] #768
- [x] #766
- [x] #767

**Comment by TuringLovesDeathMetal** [comment]
We should use tags to do this!

By default, _**all**_ models are included in Lightdash. 

But, you can also include a subset of models in `lightdash.yml`.

You'd have something like: 
`include_models` and then the options of `entire_project`, `selection_of_tags` or `selection_of_models`.

By default, you'd use `entire_project`.

`selection_of_tags` would require you to write a list of the tags that you'd want the models in Lightdash to include. 

`selection_of_models` would require you to write a list of the _**model names**_ that you'd want to include in Lightdash.

**Comment by owlas** [comment]
@TuringLovesDeathMetal one thing that might be related here is moving our explore definitions to `exposures`.

This is coming up in the next dbt release: https://github.com/dbt-labs/dbt/releases/tag/v0.20.0rc1 https://github.com/dbt-labs/dbt/pull/3405

Originally this is actually how we wanted explores to work but couldn't because of missing `meta` tag in an exposure.

So it would go like this as an analog to looker:
* dbt model => looker view
* dbt exposure => explore

I can create a separate ticket for this. but it would affect the work here because explores would only appear if you've defined an exposure for them.

**Comment by TuringLovesDeathMetal** [comment]
yep, sounds good to me!

**Comment by TuringLovesDeathMetal** [comment]
https://www.figma.com/file/lTv7iA8w5oQWqtjWtuCR2w/Table-selection?node-id=0%3A1

^here's the design for this. 

We should have this included in onboarding. Then, we should give you the option to update this in the project settings later. 

I'm going to re-jig the project settings a bit so that we can have multiple options within different tabs (e.g. `project management` will have multiple things in it that you can work on). I'll link that ticket in here once it's specced

**Comment by ZeRego** [comment]
@owlas @TuringLovesDeathMetal fyi: This form will need the project to be compiled but we don't compile the project during onboarding. So we need to change the project creation to also try to compile the project. This is going to increase significantly the onboarding time.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego could we _**not**_ include auto-complete + the table list in onboarding, then in the project settings, we include this information? Would that keep it so that we don't need to compile in signup?

**Comment by ZeRego** [comment]
Yeah, we can avoid compiling the project if we don't have the autocomplete during onboarding 👍

**Comment by TuringLovesDeathMetal** [comment]
sweet, let's do that for now!

**Comment by owlas** [comment]
@ZeRego we should actually benchmark running compile. We already have to run `dbt deps` and `dbt parse` to test the connection. I'm not sure running `dbt compile` is going to be that much longer than the first two steps.

We should try it! We can of course not compile the Lightdash metrics etc.

**Comment by ZeRego** [comment]
@owlas @TuringLovesDeathMetal 

Here are some times I recorded:

**Jaffle shop with local dbt  + local postgres**
Time to test: 11.093s
Time to compile: 11.372s
Overall time to test project: 22.483s

**Jaffle shop with gitlab + local postgres**
Time to test: 20.833s
Time to compile: 12.905s
Overall time to test project: 33.768s

**Lightdash analytics with github + bigquery**
Time to test: 19.853s
Time to compile: 21.847s
Overall time to test project: 41.811s

**Comment by owlas** [comment]
Amazing @ZeRego !!! 

Can you explain what's happening "test" and "compile"? e.g. usually compile also parses the project.

**Comment by ZeRego** [comment]
I kept the existing test function + **compileAllExplores()**

Code I used to record those times:
```
    private static async testProjectAdapter(
        data: UpdateProject,
    ): Promise<void> {
        const label = 'Overall time to test project:';
        const testLabel = 'Time to test:';
        const compileLabel = 'Time to compile:';
        console.time(label);
        const adapter = await projectAdapterFromConfig(
            data.dbtConnection,
            data.warehouseConnection,
        );
        try {
            console.time(testLabel);
            await adapter.test();
            console.timeEnd(testLabel);
            console.time(compileLabel);
            await adapter.compileAllExplores();
            console.timeEnd(compileLabel);
        } finally {
            await adapter.destroy();
        }
        console.timeEnd(label);
    }
```

**Comment by owlas** [comment]
@ZeRego nice, in that case I'm pretty sure the `compileAllExplores` does a lot of what `test` does too. Compiling and test both:
* `dbt deps`
* `dbt parse` (since `dbt compile` does a `dbt parse`)

Although I'm suspicious because your second test showed that compiling took less time: Time to test: 20.833s Time to compile: 12.905s
