### ISSUE TITLE
Filter data by date

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#171]
I can't filter date columns, under the filters section date time columns don't show up. 

<img width="337" alt="Screenshot 2021-07-05 at 11 25 57" src="https://user-images.githubusercontent.com/11660098/124457489-c590fd80-dd83-11eb-94ee-8d225f8ab829.png">

Would be fab to add this functionality. 

Specifically, being able to filter:

- [ ]  datetime
    - [ ]  is in the past (i.e. relative time) + datetime unit (seconds, minutes, hours, weeks, months, years)
    - [ ]  is before
    - [ ]  is on or after
    - [ ]  (not) equals
    - [ ]  is (not) empty

    **Not as critical:**

    - [ ]  is in the range

**Comment by TuringLovesDeathMetal** [comment]
## SQL for filters
@ZeRego Here's the SQL query that I'm going to attach example `WHERE` clauses to :) 

```
SELECT 
_fivetran_synced -- this is a timestamp

FROM `alpine-land-278512.segment.identifies`
```

### examples for "date/timestamp is in the past..."
"Date/timestamp is in the past 7 days"
```
WHERE  
DATE(_fivetran_synced) >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)
```

"Date/timestamp is in the past 30 seconds"
```
WHERE 
TIMESTAMP(fivetran_synced) >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 SECOND)
```

### examples for "date/timestamp is before..."
"date/timestamp is before January 30th, 2021, 11:00:00 AM"
Here's a link to BigQuery Timestamp formats: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#canonical_format_4
```
WHERE 
TIMESTAMP(fivetran_synced) < "2021-01-30 11:00:00 UTC"
```

"date/timestamp is before February 15th, 2021"
```
WHERE 
TIMESTAMP(fivetran_synced) < "2021-02-15"
```

### examples for "date/timestamp is on or after..."
"date/timestamp is on or after January 30th, 2021, 11:00:00 AM"
```
WHERE 
TIMESTAMP(fivetran_synced) >= "2021-01-30 11:00:00 UTC"
```

"date/timestamp is on or after February 15th, 2021"
```
WHERE 
TIMESTAMP(fivetran_synced) >= "2021-02-15"
```

### examples for "date/timestamp (not) equals..."
"date/timestamp equals January 30th, 2021, 11:00:00 AM"
```
WHERE 
TIMESTAMP(fivetran_synced) = "2021-01-30 11:00:00 UTC"
```

"date/timestamp does not equal February 15th, 2021"
```
WHERE 
TIMESTAMP(fivetran_synced) != "2021-02-15"
```

### examples for "date/timestamp is (not) null..."
"date/timestamp is null"
```
WHERE 
TIMESTAMP(fivetran_synced) IS NULL"
```

"date/timestamp is not null"
```
WHERE 
TIMESTAMP(fivetran_synced) IS NOT NULL"
```

### examples for "date/timestamp is in the range..."
"date/timestamp is in the range January 30th, 2021 11:00AM and February 15th, 2021, 10:00AM"
```
WHERE 
TIMESTAMP(fivetran_synced) BETWEEN "2021-01-30 11:00:00 UTC" AND "2021-02-15 10:00:00 UTC"
```

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego, @owlas just pointed out that date and time functions vary a lot between different SQL servers:

https://popsql-misc.s3.amazonaws.com/popsql-datetime-cheatsheet.pdf

I think this might make filtering a bit more complicated...

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal Could we avoid using functions ( which might be different ) and use generic operators ? 

Example:
![Screenshot 2021-07-07 at 10 02 06](https://user-images.githubusercontent.com/9117144/124732597-3f072800-df0b-11eb-95aa-7ecb1b79517c.png)


```
SELECT
  orders.order_date AS `orders_order_date`,
  COUNT(orders.order_id) AS `orders_total_orders`
FROM `jaffle-shop-317213`.`dbt_joserego`.`orders` AS orders
LEFT JOIN `jaffle-shop-317213`.`dbt_joserego`.`customers` AS customers
  ON (customers.customer_id) = (orders.customer_id)
WHERE (
  (orders.order_date) IS NULL
   AND (orders.order_date) IS NOT NULL
   AND (orders.order_date) = ("2021-07-07")
   AND (orders.order_date) NOT IN ("2021-07-07"
   AND (orders.order_date) > ("2021-07-07")
   AND (orders.order_date) >= ("2021-07-07")
   AND (orders.order_date) < ("2021-07-07")
   AND (orders.order_date) <= ("2021-07-07")
)
GROUP BY 1
ORDER BY orders_order_date
LIMIT 500
```

**Comment by TuringLovesDeathMetal** [comment]
ooooh, great idea!! You're so smart 🧠 

This also works for timestamps 😍 e.g. `AND (orders.order_date) = ("2021-07-07 11:00:00")`

**Comment by TuringLovesDeathMetal** [comment]
The only thing I'm not sure that this will work with is the "date/time is in the past..." 🤔

**Comment by ZeRego** [comment]
I already tried all those filters for dates and they seem to work fine. Going to have a PR soon for Date filters  and going to create a separate ticket for the times filters. To keep PR's cleaner.

**Comment by TuringLovesDeathMetal** [comment]
> I already tried all those filters for dates and they seem to work fine.

Sorry, are you talking about the 'relative time' filters too? E.g. if I wanted to filter "date_field is in the past 7 days"

I don't think that filter exists in the ones you've listed above 🤔 but I might be totally missing something!

**Comment by TuringLovesDeathMetal** [comment]
^we can also split this out into a separate ticket if this is the only one that's complicated to build! (I don't think we absolutely need it in V1)

**Comment by ZeRego** [comment]
> Sorry, are you talking about the 'relative time' filters too? E.g. if I wanted to filter "date_field is in the past 7 days"

Ah true. If we need to avoid the SQL functions we could have some magic in our BE where we find what is the date from 7 days ago and apply a 'greater than' operator. Probably better to have a separate ticket for that so we can discuss more advanced filters.

**Comment by TuringLovesDeathMetal** [comment]
Sweet, let's do that then, split that puppy out! 🚀

**Comment by owlas** [comment]
@ZeRego so cool! Do we know it's supported across snowflake/postgres/bigquery at least?

**Comment by ZeRego** [comment]
@owlas 
Bigquery works because I already tested all the filters.
Snowflake and postgres have those condition/query operators. Can't find anything in their docs that explicitly say that they don't work on date values. Most of the documentation around dates and conditions is about the use of functions. 
So my assumption is that these filters should work everywhere.
