### ISSUE TITLE
Adding a dashboard filter causes the app to crash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1731]
### Describe the bug

The app crashes any time I try to add a dashboard-level filter. 

Both in `edit` mode and in `view` mode on _**any**_ dashboard.

Filters in Explores are working fine.

### To Reproduce

https://www.loom.com/share/49280aec6dec427b8fd9488e58b2fd7e

### Expected behavior

The app shouldn't crash if I add a dashboard filter.

**Comment by hamzahc1** [comment]
I wasn't able to re-create this in Cloud. Are you running the app locally?

**Comment by rephus** [comment]
I was able to replicate this locally 

```
Uncaught TypeError: Cannot read property 'customers_unique_customer_count' of undefined
    at useBigNumberConfig (useBigNumberConfig.ts:19)
    at VisualizationProvider (VisualizationProvider.tsx:84)
    at renderWithHooks (react-dom.development.js:14969)
    at updateFunctionComponent (react-dom.development.js:17291)
```
I'll take a look

**Comment by rephus** [comment]
See my error
![Peek 2022-04-11 11-42](https://user-images.githubusercontent.com/1983672/162712084-52b74af5-09c0-42d1-a2f2-89544f9f1063.gif)


See my fix 

![Peek 2022-04-11 11-41](https://user-images.githubusercontent.com/1983672/162712097-e03fe8e1-d34b-4e17-b373-5200160165bb.gif)

Not sure if this is fixing Your error, but it is fixing An error :)
I'll make a PR
