### ISSUE TITLE
You should be able to 'Explore from here' on a chart tile in the Dashboard.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1732]
**From a dashboard tile, I should be able to:** 
- Click on the actions menu and select `Explore from here`
- This should take me to a pre-filled Explore page (not the saved chart). 
- I should be able to play around with the filters/ metrics / dimensions/ chart config, without affecting the original chart. 

<img width="724" alt="Screenshot 2022-04-11 at 10 19 52" src="https://user-images.githubusercontent.com/12776522/162708027-2c945e6d-a6ff-42be-9542-4cbd739f6254.png">

https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=2825%3A49414

- [ ] Add 'Explore from here' as an option under the dropdown in Dashboard view mode
- [ ] Add 'Explore from here as an option under the dropdown in Dashboard edit mode
- [ ] Change the layout of the dropdown in Dashboard edit mode to align with the design
- [ ] Redirect user from dashboard to a pre-filled Explore page when they click on this button

**Comment by TuringLovesDeathMetal** [comment]
no difference _**technically**_


But, from a user experience point of view:
- I have forgotten to `save chart as` and just clicked `saved chart` at least 5 times and over-written an existing saved chart by accident. 
- It's wayyyyyy "scarier" to play with a chart that you could break. With `explore from here`, you can't break the underlying saved chart. People like safe spaces, they're more likely to use them :) 

does that make sense?
