### ISSUE TITLE
"Save changes" are always visible on load for a big number

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1737]
### Describe the bug

The `Save Changes` button is always enabled when you first load a big number

### To Reproduce

Open this saved chart in the demo: https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/saved/856def3a-873a-4529-83ec-2a10f61f5398

Notice the saved chart button (even though no changes have been made)

<img width="189" alt="Screenshot 2022-04-11 at 15 32 25" src="https://user-images.githubusercontent.com/11660098/162762397-47a284ed-54ba-468f-97d3-bde747ac8e49.png">

**Comment by rephus** [comment]
mm @owlas I though this was fixed by https://github.com/lightdash/lightdash/issues/1706 , is this still happening ?
