### ISSUE TITLE
Get tables from the data warehouse that don’t have a `yml` file

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1739]
We can get a list of all of the tables from the data warehouse that the Lightdash instance is connected to, even i they aren't included in the dbt project (i.e. they don't have a YAML file)

- **which data warehouse**?
    - the one my Lightdash instance is connected to. 
- **What about the tables that already have a YAML file?**
    - we include _**all**_ of the tables from the data warehouse. That way, even if I'm developing a table that already has a YAML file, but I'm adding a _**lot**_ of new stuff to it, I can play around with the new fields
- **What information do we need about the tables?**
    - we need to know the warehouse, project and table name. We also need to know the types of each of the columns (this will be important for adding metrics later #1742 )

**Comment by TuringLovesDeathMetal** [comment]
@rephus I feel like this might be a duplicate of #1803 ? Just want to double check before I close this one

**Comment by rephus** [comment]
I don't think so, #1803 is about storing in db instead of local memory, but could you confirm @owlas  ?
