### ISSUE TITLE
You can create charts using metrics not defined on your explore

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1742]
**Tasks**

- [x] #1757
- [x] #1758
- [x] #1762
- [x] #1759
- [ ] #1763

### Description: What is it?

If I'm in an Explore view (either for a table that does or doesn't have a YAML file), I can add metrics, on the fly, directly from the dimensions. 

### Problem: What problem does this solve?

It's really time-consuming to add _**all**_ of the metrics that you might need for your dimensions into your YAML files before you go and explore your data. 

We _**could**_ just automatically add all of these metrics to your dbt YAML file, but we think that would be a bit of a nightmare to navigate through in the UI (imagine 100 dimensions, each with 1+ metrics??). Instead, we want to let users add metrics in the UI (then, we'll let them easily add these metrics to their YAML files later on!)

Here's what people are saying: https://lightdash.productboard.com/feature-board/3998990-feature-prioritization/features/11806387/insights

### What: Roughly, what does this look like in the product?

It's [this step in the Figma flow example.](https://www.figma.com/proto/Jk9xEEPfdbTJpYMvGcMzjz/Lightdash-%2B-dbt-Developer-Workflow-v1?node-id=19%3A66&scaling=contain&page-id=0%3A1&starting-point-node-id=19%3A48)

- We remove the `magic metrics` that we have now for users when they don't have metrics defined in their models. 
- I can add metrics through the UI using either dimensions in a table from my dbt project _**or**_ dimensions in a table from my data warehouse (that has no dbt YAML file).
- There's some way of interacting with a dimension in the sidebar so I can apply `default metrics` to it (e.g. right-click, clicking on the `options`. Suggested term for this section: `aggregations`, `speedy metrics`, `default metrics`)
- When I've applied a metric, I see it in the sidebar (similar to #1668)
- These metrics are distinct from `saved metrics` in the UI (they look distinct in some way) --> **This is my opinion! Not sure if other people agree it should be like this!**
- I'm able to save a chart with these default metrics used in it. 
- You should be able to remove a 'temporary metric'
- Unless you save the chart or share the explore with the temporary metric in it, the 'temporary metric' does not persist
- Generate description for the 'temporary metric' (displayed on hover). This should be the same as the descriptions we auto-generate for Lightdash metrics currently. 
- Display the 'temporary metrics' 'outside of the table tree'. (this becomes more relevant when we're dealing with joins'
- The naming convention should be `explore name` - `metric type` - `dimension name`. eg . `users count distinct id` . This applies to every case (not just joins). The `explore name` and `dimension name` are the same as what a user sees in the sidebar (i.e. if there is a `label` applied, then we use this value)

The default metrics available for each dimension type will be:
- **type:** integer/float
    - min, max, sum, average, count_distinct, count
- **type:** string, Boolean
    - count_distinct, count, min, max
- **type:** date/timestamp
    - count_distinct, count, min, max

We **won't** have default metrics available for:
- arrays, structs, JSON, Geography, Interval, 

### How other people do it:
Here's how Looker does it: https://docs.looker.com/exploring-data/adding-fields/custom-measure

Here's how Metabase does it (metrics on the fly is their default way of creating `metrics` -- you get this `summarize` option in the `asking questions` flow.): https://www.metabase.com/docs/latest/users-guide/04-asking-questions.html#summarizing-and-grouping-by

^They also now let you add custom metrics (i.e. `saved metrics`) but it's really not a great experience :/ And they appear at the bottom of the drop-down list under a heading `common metrics`: https://www.metabase.com/docs/latest/administration-guide/07-segments-and-metrics.html#creating-a-metric

Tableau does it a bit differently:
- By default, if you drag in a _**numeric**_ field into your results, they will apply a default aggregation to it. [Basically, Numeric field = metric.](https://help.tableau.com/current/pro/desktop/en-us/datafields_typesandroles.htm#:~:text=Measures%20contain%20numeric%2C%20quantitative%20values%20that%20you%20can%20measure.%20Measures%20can%20be%20aggregated.%20When%20you%20drag%20a%20measure%20into%20the%20view%2C%20Tableau%20applies%20an%20aggregation%20to%20that%20measure%20(by%20default).)
- You can then _**change**_ the aggregation applied to it by right-clicking the dimension and changing it. Either when you've[ already added it to the results table](https://help.tableau.com/current/pro/desktop/en-us/calculations_aggregation.htm#:~:text=You%20can%20change%20the%20aggregation%20for%20a%20measure%20in%20the%20view%20from%20its%20context%20menu%3A), or on the sidebar, [you can change the default aggregation for when it gets added to the results table.](https://help.tableau.com/current/pro/desktop/en-us/calculations_aggregation.htm#:~:text=Right%2Dclick%20(control%2Dclick%20on%20Mac)%20a%20measure%20in%20the%20Data%20pane%20and%20select%20Default%20Properties%20%3E%20Aggregation%2C%20and%20then%20select%20one%20of%20the%20aggregation%20options.)
- Tableau _**also**_ lets you add aggregations to dimensions on the fly (remember, dimensions are _**qualitative**_ fields - i.e. non-numeric). [So, they let you add min, max, count, count_distinct.](https://help.tableau.com/current/pro/desktop/en-us/calculations_aggregation.htm#:~:text=its%20context%20menu%3A-,Aggregating%20Dimensions,-You%20can%20aggregate)
- Tableau had just recently introduced `saved metrics` (in 2020). Before that, all of their metrics were applied on-the-fly by users and then you had the[ option of adding `calculations`](https://help.tableau.com/current/pro/desktop/en-us/calculations_calculatedfields_create.htm) (these are the same concept as our table calculations - except you could build them using fields that were in your table, but _**not**_ included in your results table)

**Comment by PriPatel** [comment]
**User flow and quick mockups:** 
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=2872%3A52425

**Discussion points:**
- You should also be able to remove a 'temporary metric'
- Unless you `save chart` or `share the explore`, the 'temporary metric' does not persist
- Remove magic metrics
- Generate description for the 'temporary metric' (displayed on hover)
- Display the 'temporary metrics' 'outside of the table tree'. (this becomes more relevant when we're dealing with joins'
- The naming convention should be `table - metric - dimension`. eg . `users - count distinct - id` . Does this apply to every case, or just joins? 

**Design considerations:**
- Empty state 
- All the microcopy! What is this called? 'temporary metrics?'. Do you 'add metric?'
- How to communicate to the user that you can do this?
- What happens when you see the temp metric in a saved chart? How do you find it again?
- (possibly) - a better way to show which metrics / dimensions have been applied ? (rather than highlighting them in blue)

**Comment by TuringLovesDeathMetal** [comment]
Adding these discussion points to the ticket! (with some answers :) )
