### ISSUE TITLE
Add `additionalMetrics` to the `runQuery` API

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1757]
Users should be able to inject additional metrics into their explore when running a query.

They should behave exactly like the metric already existed on the explore:
- They can be selected in the `metrics` property (but don't have to be)
- They can be sorted in the `sorts` property
- They can be referenced by `filters`
- They can be referenced by `tableCalculations`

**Existing query type**

Takes a single explore and references metric, dimensions, filters, etc. to build a query

https://github.com/lightdash/lightdash/blob/b101119bcc3bcb0b0383ea5659ba3edb0a276f29/packages/common/src/types/metricQuery.ts#L15-L23

**New query type**

Accepts a list of metrics and injects it into the explore before running the query

```typescript
export type MetricQuery = {
    dimensions: FieldId[]; // Dimensions to group by in the explore
    metrics: FieldId[]; // Metrics to compute in the explore
    filters: Filters;
    sorts: SortField[]; // Sorts for the data
    limit: number; // Max number of rows to return from query
    tableCalculations: TableCalculation[]; // calculations to append to results

    // new type
    additionalMetrics?: Metric[] // existing metric type 
};
```

Use existing Metric type: https://github.com/lightdash/lightdash/blob/b101119bcc3bcb0b0383ea5659ba3edb0a276f29/packages/common/src/types/field.ts#L166-L171

- [x] Database for saved queries
- [x] Query compiler + builder: https://github.com/lightdash/lightdash/blob/b101119bcc3bcb0b0383ea5659ba3edb0a276f29/packages/backend/src/services/ProjectService/ProjectService.ts#L250-L255
- [x] Routers: `runQuery` and `compileQuery` accepts `additionalMetrics` https://github.com/lightdash/lightdash/blob/b101119bcc3bcb0b0383ea5659ba3edb0a276f29/packages/backend/src/routers/projectRouter.ts#L88-L149
- [x] Write new unit test: https://github.com/lightdash/lightdash/blob/b101119bcc3bcb0b0383ea5659ba3edb0a276f29/packages/backend/src/queryBuilder.test.ts#L1-L1

**Comment by rephus** [comment]
@owlas does this includes the db migration ? I guess `Database for saved queries` depends on it
