### ISSUE TITLE
When you duplicate a chart or a dashboard, you should be taken to that saved chart or dashboard

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1767]
### Description: What is it?

When you duplicate a saved chart or dashboard, you should then be taken to that item you've just created. Currently if you duplicate an item, it's created but you're not navigated to it automatically. 

### What: Roughly, what does this look like in the product?

You could either:
-  be taken to the saved chart or dashboard in  the navigation and it should be highlighted 
OR
- open directly into the newly duplicated dashboard or saved chart.

**Comment by hamzahc1** [comment]
@PriPatel - do you have an opinion for what should happen after users duplicate a chart/dashboard?

**Comment by nathaliabj** [comment]
@hamzahc1 @PriPatel This is actually an extremely quick fix, if you decide this should be the behaviour let me know ill do it quickly :)

**Comment by PriPatel** [comment]
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=2634%3A46787
I think that if you're on the Saved Charts, or Dashboards page, then its fine to see the duplicate appear. (this is a common pattern.) 

If you're in a saved chart, you should be directed to the new chart.

**Comment by PriPatel** [comment]
@nathaliabj actually, how about this:

For the toast messages when you are duplicating a dashboard or a saved chart from the 'list' pages, the success toasts can be similar to this toast, where we add a link. 

![Screenshot 2022-04-13 at 11 25 52](https://user-images.githubusercontent.com/12776522/163158825-60e5b21b-711f-456a-945e-13932ed3cdc2.png)

**Comment by PriPatel** [comment]
So :
`Chart successfully duplicated! -> Open chart`
`Dashboard successfully duplicated! -> Open dashboard`

Again, only for the `Saved Charts` and `Dashboards` pages where we display things in list form. (not for individual saved chart explore pages! )
