### ISSUE TITLE
option to show all fields in chart tooltip

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1774]
### Description: What is it?

When I hover over a component of the chart (a bar, a mark on a line) I'd like the tooltip to contain all dimensions/metrics for that row in the data. Currently we only show fields that are on the chart.

Also the dimensions show at the top but they could have the same prominence as other fields too:

For the green bar
```
Payment type: credit card
Total Revenue: 627
Payment count: 39
```

<img width="739" alt="Screenshot 2022-04-13 at 14 55 35" src="https://user-images.githubusercontent.com/11660098/163196565-64e421b9-5dde-42b4-8bb7-c703d57d6aac.png">

**Comment by hamzahc1** [comment]
How would you get human-friendly labels for all the dimensions to appear? Right now you can change the names of the series which appear in the tool-tip 🤔

**Comment by TuringLovesDeathMetal** [comment]
@hamzahc1 I remember talking about this the other week - this would add _**even more**_ values to teh tooltip on hover. 

Right now, you were saying that you _**only want**_ the value you're hovering over to appear on the tooltip. 

Any opinions on this one? 

(I feel like we might need to do some user research here...)

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal - I think this is something that should be configurable. At certain times you will want to see all values plus other info (e.g. like a total etc), whereas for certain charts you may only want to highlight the value you're highlighting.
