### ISSUE TITLE
Support wildcard column names 

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1781]
### Description: What is it?

Some `schema.yml` files use wildcards to add documentation to all columns in a schema file, for example: https://github.com/brooklyn-data/dbt_artifacts/blob/0127c460733299827af3456daa88fa3dc8927bda/models/schemas.yml#L132-L133

This isn't supported by Lightdash, it would be great if it worked!

**Comment by ZeRego** [comment]
Is there a dbt spec on wild cards ? I couldn't find it. 
In terms of implementation we would have to detect wild card fields ( column name includes `*` ) and create a dimension for each match in the warehouse catalog/schema.

**Comment by owlas** [comment]
Yeah I think that's right, do we apply all the `meta` properties to each dimension too? I can imagine that being strange if somebody overrides the `sql` field.

**Comment by ZeRego** [comment]
>  do we apply all the meta properties to each dimension too?
I think it should, that's why they are using the wild card because they want to save time when dealing with multiple columns that behave the same. 

If they want different config they should declare the dimension properly.

**Comment by owlas** [comment]
Yep then in that case I agree with your approach, we need the warehouse schema to generate those fields. It's a shame because I was hoping to get rid of that requirement eventually. So we could statically analyse all the yaml files without needing to know the warehouse schema

**Comment by ZeRego** [comment]
We do have the option to not support wild cards 🤔 And encourage people to use the cli do generate all the dimensions yml. 
The annoying part is that the user would have to manually add the same config to each dimension.

**Comment by TuringLovesDeathMetal** [comment]
I came across a use case for this with a user:

- They have a new column added each month in their dbt model (e.g. revenue_january)
- They don't want to have to remember to add this new column to Lightdash every month (even with the cli generate! They'd have to rerun it)

@owlas why do we want to get rid of that requirement? Is it just annoyign to maintain? or is it making something slower?

> We do have the option to not support wild cards

Ya, this is definitely an option...it's a bit annoying though. @owlas for Brooklyn Data's requirement, would the CLI generator have solved this problem for them? Or was it that the wildcard was creating fields that were constantly being updated and they didn't want to regenerate teh schema file each tiem?

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 
Even if we supported the wild card we would only display the new dimensions when they click `refresh dbt`. 
I imagine this problem being solve by using our CLI in their CI/CD pipeline. Compiling and deploying the latest dbt project each time they merged something into their main branch or with a cron job.

**Comment by TuringLovesDeathMetal** [comment]
Ya, that makes sense. 

`refresh dbt` is much easier than opening + merging a PR each time. 

I'd like to hear why other folks have asked for this option though (like, is their problem solved just using our schema generator)

**Comment by owlas** [comment]
@TuringLovesDeathMetal the bonus for not relying on the warehouse schema is that compile would be wayyyyyy faster without having to get the warehouse schema. Any time we fetch the schema it slows things down a lot and we need to make sure we have the user's warehouse config to successfully compile.

For example, if we removed this, we wouldn't need to parse the user's credentials at compile time (making ci/cd jobs so much simpler)

**Comment by TuringLovesDeathMetal** [comment]
hmm, okay, the benefits of not supporting this seem to heavily outweigh the costs. 

unless a bunch more users request this, I say we put this on hold for now. I'll remove it from the backlog

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue - I haven't heard it requested again and it's not something I think we want to support
