### ISSUE TITLE
hasUnsavedChanges function in the explorer not working as expected

### ISSUE THREAD

**Issue by nathaliabj** [lightdash/lightdash#1782]
### Describe the bug

This function is meant to determine when a saved chart has been updated, however currently it is not returning the correct values.

### To Reproduce
Go to a saved chart from the saved charts list, and do nothing with it, the save chart button should be disabled and the first option in the options menu for the chart should be duplicate instead of save chart as new.

### Expected behaviour

the save chart button should be disabled and the first option in the options menu for the chart should be duplicate instead of save chart as new.

On chart update the save chart button should become available and the save chart as new should appear in the options menu.

### Screenshots or Loom video
https://www.loom.com/share/c820ebf30ee846fdb320ee884d469027

**Comment by owlas** [comment]
I've assigned @ZeRego to take a look at this and refactor the frontend state in the explorer to reduce these bugs. 

I think the main areas of improvement are:

* Tracking more state in the explorer provider, and being more explicit about the diff between the saved backend state, and the frontend draft state before saving. This could be represented by a series of actions (for the reducer) or a flag we set
* I think the frontend state should store the chart config for each chart type separately, so explore provider will have a cartesian config, big number config, table config. The polymorphic type for `chartConfig` is making state management so much more complex, and doesn't allow us to remember each configuration as the user changes types.
