### ISSUE TITLE
Bitbucket form shows wrong values

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1783]
### Describe the bug

When I try to connect with bitbucket:

* the form shows a default host of `GitHub.com`
*  the personal access token should be a http access token
* Documentation links take me to gitlab docs: https://docs.lightdash.com/get-started/setup-lightdash/connect-project

**Comment by rephus** [comment]
Reopening because there was a bug 
![image](https://user-images.githubusercontent.com/1983672/166482854-5172c692-3f8b-455f-8877-13e55075d529.png)
