### ISSUE TITLE
Add `dashboard_title` to `dashboard_created` and `dashboard_updated` events

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1784]
For the activity monitoring dashboard, people want to know what the dashboard title is for the dashboards they created + updated. 

This data should _**only**_ exist in the application database (and never get sent to our data warehouse) because we don't need to be processing this information.

**Comment by 12ian34** [comment]
Closing in favour of https://github.com/lightdash/lightdash/issues/4132
