### ISSUE TITLE
Add `chart_name` to `saved_chart_created` and `saved_chart_updated` and `saved_chart_version_created` in the application database

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1785]
Add `chart_name` to `saved_chart_created` and `saved_chart_updated` and `saved_chart_version_created` in the application database

I don't think we need to process this information in our Rudderstack instance, but just send this data back to their application database so we can add it to the usage dashboard

**Comment by 12ian34** [comment]
Closing in favour of https://github.com/lightdash/lightdash/issues/4132
