### ISSUE TITLE
I want to know what's happening during the compile phase

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1794]
**Tasks**
- [x] #1872
- [ ] #1873
- [ ] #1874
- [ ] #1875

When we submit a request to refresh dbt (already exists), we should return a job id

```
POST /projects/{projectUuid}/refresh

200 {
  status: ok
  results: {
    jobId: ''
  }
}
```

The frontend can use this job id to poll for results:

```
GET /jobs/{jobId}

200 {
  status: 'ok'
  results: {
    jobStatus: 'DONE' | 'RUNNING' | 'ERROR',
    jobResults?: '/projects/{projectUuid}/explores'
    steps: [
      { 
       name: string,
       stepStatus: 'DONE' | 'RUNNING' | 'ERROR' | 'PENDING' | 'SKIPPED',
       error?: { name: string, message: string }
     }
   ]
}
```

`jobResults` only shows on success, and `error` only shows on error.

On success the frontend can trigger a new query to update the explores.

### Description: What is it?

The "refresh dbt" step can take a very long time and I don't really know why. What's happening during this step? It would be very useful to know the individual steps taking place (similar to how dbt cloud shows raw dbt logs during runs:

<img width="779" alt="Screenshot 2022-04-19 at 09 16 12" src="https://user-images.githubusercontent.com/11660098/163957394-b43fa267-7533-4312-a112-e239eaa12d1c.png">

**Comment by PriPatel** [comment]
Unassigning myself from this now!
https://www.notion.so/lightdash/Refresh-dbt-2e15a707f1cf4d99b5d5f03c561eaebb#5cb13b94cb0342c09dfc33f36068f2ea
