### ISSUE TITLE
Cache entire data warehouse schema

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1803]
### Description: What is it?

- [ ] Cache the schema in postgres (similar to #674)

**Comment by rephus** [comment]
@owlas what function is this ? `trigger a refresh to the data warehouse schema`

**Comment by owlas** [comment]
@rephus I've removed that from ticket, I don't think it was actually relevant to the initial problem

So now it's just moving the `warehouseCatalog` which is cached in the `dbtBaseProjectAdapter` to a project-level cache in postgres, similar to the cache we just implemented: https://github.com/lightdash/lightdash/blob/cd7b666ea7a1de02138223400c530c2cde147233/packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts#L67-L68
