### ISSUE TITLE
Design chart description in the frontend

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1819]
**(please give me a shout before you start working on this ticket!!!)**

**Now that we collect chart descriptions and save them to the backend, we can display it to the user in the FE on the saved charts page** :

<img width="509" alt="Screenshot 2022-04-20 at 10 06 42" src="https://user-images.githubusercontent.com/12776522/164193382-462972e6-20ef-4cc7-872a-3fc1501053fa.png">

- [x] Add information icon next to chart title to show the saved chart's description on hover using a tooltip.
- [x] The information icon should not appear when a chart is not saved. 
- [x] When user hit's the `edit` icon, they are shown this modal again. They shouldn't be able to edit the chart name separately.
- [x] When there is no description saved, don't show the tooltip

<img width="525" alt="Screenshot 2022-04-20 at 10 14 25" src="https://user-images.githubusercontent.com/12776522/164194590-8cfb8b67-d795-4b8d-a9ce-7d8ab8663a34.png">

**Comment by hamzahc1** [comment]
@PriPatel would this information icon also appear in the saved charts list? or only in the saved chart itself?

**Comment by PriPatel** [comment]
@hamzahc1
Yes! Same with dashboards (eventually, its just not part of this ticket!)
