### ISSUE TITLE
Cannot de-select `activeFields` if they're invalid

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1825]
### Describe the bug

If I have an explore containing an invalid metric, it stays in the `activeFields` and makes the saved chart unfixable.

### To Reproduce

1. Create a chart based an metric `X`
2. Remove metric `X` from project
3. Load saved chart with metric `X` - you'll get an error "cannot find metric X"
4. The sidebar doesn't contain metric `X`, anything you click will not get rid of the error

**Comment by TuringLovesDeathMetal** [comment]
I feel like this might be solved now? Since we can remove fields from the results table? 

(I ran into this today and was able to just remove the field from the results table...)

@owlas wdyt?

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this because we can now remove fields from the results table - so it's now possible to de-select active fields if they're invalid
