### ISSUE TITLE
Improve documentation getting connected: Github

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1840]
### What needs updating?

- [ ] No documentation for Host domain (for Github Enterprise). The link in the connection page goes to generic docs page
- [ ] Missing documentation for Target name (and missing link to doc in connection page)
- [ ] Missing documentation for Environment variables (and missing link to doc in connection page)
__

**Comment by TuringLovesDeathMetal** [comment]
split adding links to new ticket: https://github.com/lightdash/lightdash/issues/1863

**Comment by TuringLovesDeathMetal** [comment]
split adding links to new ticket: https://github.com/lightdash/lightdash/issues/1863
