### ISSUE TITLE
Improve documentation getting connected: GitLab

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1841]
### What needs updating?

- [ ]  No documentation for Host domain (for self-hosted instances). The link in the connection page goes to the generic docs page
- [ ]  Missing documentation for Target name (and missing link to doc in connection page)
- [ ]  Missing documentation for Environment variables (and missing link to doc in connection page)

**Comment by TuringLovesDeathMetal** [comment]
split adding links to new ticket: https://github.com/lightdash/lightdash/issues/1863
