### ISSUE TITLE
I want to be able to hide the title on a tile in my dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1848]
### Description: What is it?

There should be a way to hide the title of a tile on my dashboard. 

### Problem: What problem does this solve?

If I've written some markdown description or something above the tile, I don't really want the title in my tile. 

### What: Roughly, what does this look like in the product?

- You're able to toggle on/off hiding the title in the tile of a dashboard. 
- This would probably sit in the three-dot `options` menu for a tile. 
- Like with filters, if you clicked on this option in `edit` mode, it would be saved as the configuration for everyone who opened that dashboard

**Comment by rephus** [comment]
In terms of UI, could we implement #2708 and if if title is empty, we don't show it ? @TuringLovesDeathMetal @owlas
