### ISSUE TITLE
I can't write table calculations if I don't know SQL

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1849]
### Description: What is it?

I want to be able to write table calculations in Lightdash without needing to know complex window functions or grouping in SQL. 

### Problem: What problem does this solve?

Only people who know SQL can write table calculations right now. 

Even if you know SQL, the SQL required to write table calculations is really complicated

### What: Roughly, what does this look like in the product?

There are quite a few common functions that people will want to use in table calculations (e.g. rolling averages, running totals, max values, percentage change). Is there a way that we can make these easy to do without needing to know SQL? 

Either we can add formulas that users can plug in

OR we can adopt some other more user-friendly coding language (like Excel!) so people would have some familiar, user-friendly commands to run. 

^A suggestion! We should have these as options in the table calculation config that will populate all of the correct SQL 👀 https://docs.lightdash.com/guides/table-calculations/sql-templates

Better yet - we can add these calculations so that you select them _**from**_ a metric - that way we'd actually know the full SQL to write in it (since we'd know which metric to reference). This covers ~80% of use cases for people!

**Comment by hamzahc1** [comment]
I think the fastest starting point for this would literally be to add SQL templates for the most common calculations we know of (like those you mentioned above @TuringLovesDeathMetal ) and then folks can just update the variables with the fields required. Over time it would be great to think of a different interface. Can we write these up as templates in our docs for now that you can copy + paste?

**Comment by 12ian34** [comment]
Removed stale label since this came up again with a user:

> It would be cool to add in a moving average or trend line without having to write SQL in a table calculation. It’s ok for some, but many self-serve users couldn’t do it

**Comment by robolyst** [comment]
Hey guys,

I agree with this ticket. As a data practitioner myself, people expect me to hide away the technicalities of exploring data. Requiring people to understand window functions to get a simple weekly percentage change is a huge ask.

I'd like to suggest that this ticket could be descoped to help prioritise it.

In my experience, there's a handful of calculations that the majority of use cases for non-power users:

- % of column
- % of previous row
- % change from previous row
- Running column total

A point and click UI for a handful of common calculations I believe would help the most people with the least effort.

**Comment by owlas** [comment]
Great idea @robolyst !! I've opened a separate ticket for just one of these so we can experiment a little with the UI and backend needed to implement this. If it clicks then we can go and add the rest in too! 

I've put this ticket on the to do list so I imagine somebody will pick it up in the next 2 weeks or so: https://github.com/lightdash/lightdash/issues/4370

**Comment by owlas** [comment]
@all-contributors add @robolyst for ideas

**Comment by XiaozhouWang85** [comment]
FYI, I really love the fact that you are using SQL instead of inventing your own pseudo language. Having to learn custom languages is a bit of a pet peeve (e.g. hours spent learning Looker's LiquidML are hours I wish I could get back).

You'll always have a trade off between power / flexibility and simplicity. So in addition to having % and running totals. You can consider adding in stuff like row and column totals as pre-built variables in the formula editor. This allows me to do stuff like (A + B) / A column total. Or also do offsets e.g. (A + B) / B[-1]. So I will need to write formulas for this but not have to understand SQL windowing functions which is quite complex.

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this ticket as not planned! 

We've made some big improvements to table calculations by adding `quick calculations` (which inject SQL for common calculations): https://docs.lightdash.com/guides/table-calculations/adding-table-calculations#using-quick-calculations

This issue is more of a discussion than an actual action, so I'm going to close it for now in favour of some of the other open tickets which have more clear actions :) 

You can follow them here:

- https://github.com/lightdash/lightdash/issues/7974
- https://github.com/lightdash/lightdash/issues/9778
- https://github.com/lightdash/lightdash/issues/1222
