### ISSUE TITLE
Axis labels should be able to be empty

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1850]
### Description: What is it?

I want to be able to have an empty axis label

### Problem: What problem does this solve?

Sometimes, I don't actually want an axis label ( to reduce clutter or something). But, right now, if you click the label to leave it empty, it just puts the default value label in there (instead of leaving it empty). 

To hack this, you can just leave a space.

### What: Roughly, what does this look like in the product?

You're able to leave the axis label empty and it will make an empty label string appear there.

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel do you think that there should be a toggle or something to `remove axis label`? 

Leaving it empty to remove it seems like a bit of a hack...

**Comment by PriPatel** [comment]
cc @ZeRego 
<img width="459" alt="Screenshot 2022-05-12 at 14 34 07" src="https://user-images.githubusercontent.com/12776522/168051803-849c83f0-52f4-4c60-99a1-32d2abde2b46.png">
This was in the original design for chart config but I remember that there are technical issues with this?

**Comment by TuringLovesDeathMetal** [comment]
I think this is related to https://github.com/lightdash/lightdash/issues/2508

**Comment by ZeRego** [comment]
> This was in the original design for chart config but I remember that there are technical issues with this? Or am I recalling something else, Jose?

How echarts [name](https://echarts.apache.org/en/option.html#xAxis.name) configuration works:
- undefined/empty -> shows nothing
- string -> shows value

So we can't track the `name` value and the `show` state independently. 
On top of this, if the name is undefined/empty we default to the field label. 

The only option that I can think of is to save `showName` in the  echarts config but if we keep adding these unofficial properties it will become harder to maintain.

**Comment by TuringLovesDeathMetal** [comment]
hmmm, ya, let's just leave this for now (people can hack it with a whitespace)
