### ISSUE TITLE
Filters general: Add filters for metrics

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#186]
Right now, we can only filter on dimensions. We should be able to filter on metrics and table calculations as well.

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 
Table calculations don't have a type ( string, number, etc ) so we don't know what type of operators we can show. 

Options ( per preference order ): 
1. Only add metric filters for now and create separate ticket for table calculations to be scoped and prioritised. 
2. Assume table calculation result is a number. Shows number filters. 
3. Update table calculation UI and DB so the user can manually set the result type.

**Comment by ZeRego** [comment]
@owlas 
Currently our query builder generates the where clause by using the dimension compiled sql `(${dimensionSql}) IS NULL` but could we just use the field id ? `(${filterRule.target.fieldId}) IS NULL` 
For metrics this will be necessary since we need to reference the column from the cte, but I was wondering if I could do that for dimensions.

**Comment by owlas** [comment]
If I understood correctly: @ZeRego yes we still have to render the dimension sql because `SELECT` aliases are not defined for the `WHERE` clause. 

In other words, this doesn't work

```sql
-- wrong
SELECT my_column + 1 AS another_column
FROM my_table
WHERE another_column > 10   -- ERROR! another_column not defined

-- correct
SELECT my_column + 1 AS another_column
FROM my_table
WHERE my_column +1 > 10
```

**Comment by ZeRego** [comment]
Cool, got it 👍  more work for me then 😅

**Comment by owlas** [comment]
All hail SQL

**Comment by TuringLovesDeathMetal** [comment]
> Table calculations don't have a type ( string, number, etc) so we don't know what type of operators we can show.

> Options ( per preference order ):

> 1. Only add metric filters for now and create separate ticket for table calculations to be scoped and prioritised.
> 2. Assume table calculation result is a number. Shows number filters.
> 3. Update table calculation UI and DB so the user can manually set the result type.

@ZeRego I think 1. is the best option. 

If it's more complicated than just "adding it in with metric filters", then let's keep it as a separate chunk of work. 

Opened a new issue here: https://github.com/lightdash/lightdash/issues/1270
