### ISSUE TITLE
Update links in dbt connection page

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1863]
**- for all dbt connection types add links to `target name` and `environment variables` from the docs**
  - GitHub target name: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#target-name
  - GitHub environment variables: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#environment-variables
  - GitLab target name: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#target-name-1
  - GitLab environment variables: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#environment-variables-1
  - Azure devops target name: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#target-name-2
  - Azure devops environment variables: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#environment-variables-2
  - local dbt project target name: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#target-name-3
  - local dbt project environment variables: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#environment-variables-3
  - Bitbucket target name: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#target-name-3
  - Bitbucket environment variables: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#environment-variables-3

**- for bitbucket dbt connection type add links to all fields**
    - Username: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#username
    - personal access token: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#personal-access-token-3
    - Repository: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#repository-3
    - Branch: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#branch-3
    - Project directory path: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#project-directory-path-3
    - Host domain: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#host-domain-2

**Comment by rephus** [comment]
According to the implementation, `target name` and `environment variables` are not dbt type specific properties (they are set at dbt setting level, not on Project type forms) ,  https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx#L91
does it make sense to keep them separate in our docs ?

**Comment by rephus** [comment]
In here https://github.com/lightdash/lightdash/pull/1963 I'm updating bitbucket docs to show `http access token` instead of `personal access token`

**Comment by rephus** [comment]
@TuringLovesDeathMetal in this description, local dbt are pointing to the bitbucket section, is this ok ? 

```
local dbt project target name: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#target-name-3
local dbt project environment variables: https://docs.lightdash.com/get-started/setup-lightdash/connect-project#environment-variables-3
```

**Comment by TuringLovesDeathMetal** [comment]
@rephus oopsies! that's a mistake from all of my copy-pasting 😅 

I don't think i actually updated the docs for a local dbt project!

So you can ignore those ones!

**Comment by TuringLovesDeathMetal** [comment]
> According to the implementation, target name and environment variables are not dbt type specific properties (they are set at dbt setting level, not on Project type forms) , does it make sense to keep them separate in our docs ?

I don't understand what you mean here :/ But I think that keeping them in the docs to match the format of the connection form is fine for now!
