### ISSUE TITLE
Adding date filters from table uses wrong values

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1867]
### Describe the bug

The SQL generated when filtering by a month is wrong. 
The filter value is YYYY-MM-DD when it shouldn't include the day.

### To Reproduce

1. Go to explore
2. Add filter from table for a date column
3. See filter has added with the wrong year/month/day

### Expected behavior

Should create the filter with the correct value

### Screenshots or Loom video

![Screenshot 2022-04-22 at 09 37 19](https://user-images.githubusercontent.com/9117144/164651641-ab2829ae-29c8-44a5-8985-df5b04f66de7.png)

**Comment by rephus** [comment]
I'm looking into this. 

We were missing the timeInterval for formatDate function, so MONTH was not applied and formatted. https://github.com/lightdash/lightdash/blob/main/packages/common/src/utils/formatting.ts#L36

However, I don't think we use DATE_TRUNC correctly (at least on Postgres), as it does not match the moment.format we use. https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC
Eg: for `order_date=2018-01-05` : `DATE_TRUNC('month', "orders".order_date)` returns `2018-01-01 00:00:00.000 +0100` and not `2018-01`

**Comment by rephus** [comment]
In fact, none of the DATE fields work because of this, not even DAY :

![image](https://user-images.githubusercontent.com/1983672/169510850-a6a0b394-1efc-496f-881f-05927107a9c9.png)

![image](https://user-images.githubusercontent.com/1983672/169510898-ab60c8db-da1a-4bdf-8946-8978bf2cf6f1.png)

**Comment by ZeRego** [comment]
@rephus Isn't the problem that the filter is saving a `string` instead of a `date` value ? That way the sql would be valid, right?

**Comment by rephus** [comment]
> In fact, none of the DATE fields work because of this, not even DAY :

It turns out that the reason why the date filters were not working for me is because this timezone bug https://github.com/lightdash/lightdash/issues/1050

**Comment by ZeRego** [comment]
@rephus I can still replicate the bug in the latest version. The problem is when we add filters from the results table. It must be using the formatted value and the filter can't convert it to a date and then defaults to today's date.

<a href="https://www.loom.com/share/6f6b9401b5ac4ea6a47ae2342a621b64">
    <p>Lightdash - bug adding filters from results table - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/6f6b9401b5ac4ea6a47ae2342a621b64-with-play.gif">
  </a>
