### ISSUE TITLE
You shouldn't be able to stack line charts or Mixed charts

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1868]
### Describe the bug

Right now, you can stack line charts. This shouldn't be an option (it doesn't visually make sense)

### To Reproduce

Make a line chart with many series (i.e. add a group)

Click `stacked`

### Expected behavior

You should only be able to stack charts which have the area below them filled in (i.e. area charts and bar charts). 

Otherwise, it's not clear that the line's value only represents the **_area_** between itself and the line below it. 

### Screenshots or Loom video

This is the line graph unstacked: 
<img width="748" alt="image" src="https://user-images.githubusercontent.com/31848148/164688116-324175f2-2984-4f9f-8704-60ee89310d05.png">

This is the line graph stacked:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/31848148/164688029-4c27317a-86dd-4ab5-9c17-cf3f902985e9.png">

In the stacked version, it looks like the values of the green-ish yellow bar are ~ 800. In reality, they're ~ 200 - they've just been stacked at the top, so the difference between it and the line below it is ~ 200.

**Comment by JohnRomanski** [comment]
> You shouldn't be able to stack line charts

I disagree with this statement. 

>this shouldn't be an option (it doesn't visually make sense)

You are saying it doesn't make sense _to you_.

The line graph stack shows information about the total volume as well as the contribution from each of the contributing parts. This kind of visualization has it place, and it's use case. There may be an additional amount of explanation required by the presenter, but that is the case either way.

Or to solve it another way, often when lines are stacked, an _area chart_ is used (like a line chart but with areas of contiguous color underneath the lines.)

Are _area charts_ on the visualization roadmap?

**Comment by TuringLovesDeathMetal** [comment]
@JohnRomanski yep! Agreed with area charts and they are on the roadmap! (I thought there was an issue open for this, but couldn't find one 🤔 so opened a new one here: https://github.com/lightdash/lightdash/issues/2284). 

Still pretty convinced that stacked line charts _**without**_ the area filled in are a no-go. 

You use stacked charts to compare sizes of groups to one-another. Without filling in the values below the lines, it's not clear that the values are relative to the nearest value below them (and not relative to the baseline). 

Yes, you could add a bunch of explanation to it about how the values are relative to one-another, but the purpose of the chart is to be the most effective _**visual**_ representation of your data (not verbal). If you read a chart wrong before you read the title, it's probably not a great chart!

I'm pretty convinced by this, but would love to hear about where you might want to use them 👀
