### ISSUE TITLE
rename `bar chart` 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1870]
### Description: What is it?

Rename `bar chart` to `horizontal bar chart` or `row chart`

### Problem: What problem does this solve?

People think that bar charts are vertical bars, not horizontal ones. 

This ticket blocks #1869 

- [ ] update `bar chart` name
- [ ] update docs to replace `bar chart` with new chart name

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel any preference for horizontal bar chart vs. row chart? 

I imagine `row chart` might fit better in the chart options drop-down.

But `horizontal bar chart` feels a bit more intuitive. 

I don't have a preference!

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal I agree that `horizontal bar chart` is more intuitive. I think the drop-down will expand to accommodate this, so all good :)

**Comment by PriPatel** [comment]
<img width="198" alt="Screenshot 2022-04-26 at 10 03 44" src="https://user-images.githubusercontent.com/12776522/165264156-561af62a-af79-47ce-931a-92c384d14d89.png">
just made these changes quickly in my browser. looks fine to me!
