### ISSUE TITLE
Track compile status in postgres

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1873]
Current design to handle async project compiling:

Inside the `projectService` there is an in-memory object storing the loading status: https://github.com/lightdash/lightdash/blob/cd7b666ea7a1de02138223400c530c2cde147233/packages/backend/src/services/ProjectService/ProjectService.ts#L68-L69

We want to move this to the jobs api:

- [ ] Create a new `jobs` table containing all job fields from #1872 except for the individual steps (for now)
- [ ] When user `POST /projects/{projectUuid}/refresh` we should create a new `job` entry in the database, with status `compile`
- [ ] Inside `refreshAllTables` if it succeeds, update the `job` in the database to SUCCESS, if it fails update to `error`
- [ ] Update `GET `/porjects/{projectUuid}/status` endpoint to read from the jobs table (for now it can read the most recently created job with the project uuid).

**Comment by rephus** [comment]
>  When user POST /projects/{projectUuid}/refresh we should create a new job entry in the database, with status compile

that status doesn't match one of the possible jobStatus... perhaps the initial status should be `RUNNING` ? 

![image](https://user-images.githubusercontent.com/1983672/165083295-f7947b22-b49c-41fc-a240-4a716e806f65.png)
