### ISSUE TITLE
Saving a chart when you haven't rerun your query saves a different chart to what you see

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1876]
### Describe the bug

There are some changes that you can make in the Explore view that won't be applied to your chart until you run a query. 

For example, adding/removing dimensions or metrics from the results table. Or adding/removing filters. 

Right now, if I add some of these changes, I don't hit `run query`, then I save my chart, the chart that's saved will be different to the chart I see in front of me. 

Why? 

The chart I've saved will be the chart once the query has run and all of my filtering + dimensions/metrics stuff has been applied. That means my saved chart could look different to the chart that I have in front of me when I click `save`. 

### Expected behavior

The chart I see in front of me should be the chart that gets saved. 

There are a few ways we could potentially do this:
1. We could automatically run a query when you click `save chart` and we detect that you've made changes and haven't run a query yet. 
2. We could force you to run a query before you try to save the chart (saved chart button could turn a different colour/have different text on it/have a tooltip on it saying that you need to run your query)
3. We could have the button turn into `run query + save` if we detect that you've made changes and haven't run a query yet. 
4. I'm sure there are other options here too...

**Internal design ticket**: https://github.com/lightdash/lightdash-internal-work/issues/304

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego have I missed anything? 

Also, @PriPatel any preferences on one of those solutions? Or can you think of something else more simple (or is anything unclear)?

**Comment by ZeRego** [comment]
We could only enable the 'save chart' if they ran the query and have a way to show the chart is out of date.

**Comment by ZeRego** [comment]
Demo of the issue: 
1. Remove a dimension/metric used in the chart
2. save the chart
3. reload the page
4. in this case it shows an error because the table calculation needs that metric. It should also happen to show a valid chart but that is different from what the user was seeing when he clicked on 'save chart'

<a href="https://www.loom.com/share/a1419ce419df4a76a88af6366f3896a5">
    <p>Gather.app - lightdash | Gather - 22 April 2022 - Watch Video</p>
    <img style="max-width:300px;" src="null">
  </a>
