### ISSUE TITLE
Filters general: Let people add multiple filters to a dimension using AND or OR (not just AND)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#188]
[https://docs.lightdash.com/references/filters#you-can-add-more-conditions-to-your-filter-by-selecting-the-symbol-on-the-right](https://docs.lightdash.com/references/filters#you-can-add-more-conditions-to-your-filter-by-selecting-the-symbol-on-the-right)

^Should be able to select "AND" or "OR" when adding multiple conditions to a filter

**Comment by owlas** [comment]
@ZeRego is this blocked by #207 ? 

Currently everything is `AND`ed together with the option to add some `OR` logic by providing many values to `equalTo` filters.

If we want to have (`(f1 AND f2) or f3`) we need to redesign the filters, the way they are stored in the DB and represented in the API.

Have I understood that correctly or do we have more flexibility without updating the way we store filters in the DB?

**Comment by ZeRego** [comment]
> is this blocked by #207 ?

I think that ticket is redundant if we are going to redesign how the filters work. 

> Have I understood that correctly or do we have more flexibility without updating the way we store filters in the DB?

I don't see a way to avoid a db migration if we are making significant changes to the filters interface.  Note that if we want to keep the filters as a jsonb in the DB we just need to convert the existing array into the new structure.

**Comment by owlas** [comment]
Sounds good, we can use this ticket to track the structure of filters? Did you previously propose a different structure for the filters?

**Comment by ZeRego** [comment]
I proposed we use this library `https://github.com/react-querybuilder/react-querybuilder` and used their json format https://react-querybuilder.js.org/docs/api/export.

**Comment by owlas** [comment]
Nice. Another more lightweight library for representing logic in json: https://jsonlogic.com

**Comment by owlas** [comment]
Although looking at the filter tickets #205 #572 - we'll need quite a lot of customisation to these schemas

**Comment by ZeRego** [comment]
@owlas What do you think about this structure ? 

```
type FilterRule = {
    target: {
        fieldId: string; 
    }; 
    operator: string;
    values?: any[];
};

type FiltersGroup =
    | {
          or: Array<FiltersGroup | FilterRule>;
      }
    | {
          and: Array<FiltersGroup | FilterRule>;
      };

const example: FiltersGroup = {
    or: [
        {
            target: {
                fieldId: 'a_a',
            },
            operator: 'equals',
            values: ['some'],
        },
        {
            and: [
                {
                    target: {
                        fieldId: 'a_b',
                    },
                    operator: 'equals',
                    values: ['other'],
                },
                {
                    target: {
                        fieldId: 'a_c',
                    },
                    operator: 'null',
                },
            ],
        },
    ],
};
```

The `target` property is an object to easily extend support for different kinds of targets. Once we have dashboard filters we might need to have something like:

```
{
    fieldId: string;
    chartId: string;
}
```

**Comment by owlas** [comment]
Looks good, so I guess we'll have to do some validation on query compile:
1. Does the target field exist
2. Does the target field support the operator type
3. Is the values list compatible with the operator type (actually maybe we can do this statically before query compile?)
4. Have metrics and dimensions been combined in a valid way. Need to figure out the exact restriction here

Just testing some scenarios:

**String**

```
operator: 'contains'
values: ['hello', 'world'] # is this OR / AND ?

operator: 'is null'
values: undefined # works
```

**Number**

```
operator: 'lessThan'
values: [12, 14] # is 13 valid?
```

**Date time ☠️ **
```
operator: 'before'
values: ['2020-11-12'] # works

operator: 'after'
values: [200, 'days', 'ago'] # is that a thing? typing is a bit messy

operator: 'sinceDaysAgo'
values: [200] # stricter but introduces many new operator types
```

**Comment by ZeRego** [comment]
> Is the values list compatible with the operator type 
In the query builder we will have logic for each filter on how to handle the values array. And it will ignore any extra value.

```
operator: 'contains'
values: ['hello', 'world'] # is this OR / AND ?
```
Can you give me an example of `AND` ? How can a dimension value match 2 values 🤔 

```
operator: 'lessThan'
values: [12, 14] # is 13 valid?
```
It would read the first value of the array and ignore the rest.

```
operator: 'after'
values: [200, 'days', 'ago'] # is that a thing? typing is a bit messy
```
I think it will work well, it's the same as arguments for a function.

```
operator: 'sinceDaysAgo'
values: [200] # stricter but introduces many new operator types
```
This is going to make our code bigger since it's less abstract.

**Comment by owlas** [comment]
> Can you give me an example of AND ? How can a dimension value match 2 values 🤔

`"Hello world"` contains both `Hello` and `world` ! 

Our current filters allow the user to specify many filter values: https://github.com/lightdash/lightdash/blob/1d2678418ba6c0edc1de11dfa6372a9b7aacedbe/packages/frontend/src/filters/string-filter/StringFilterForm.tsx#L27-L27

I'm not sure if we still want to support that

**Comment by ZeRego** [comment]
> "Hello world" contains both Hello and world !

Got it, how would the sql look like ? preferably that works on any warehouse. 
I'm wondering if this is needed and if it should be a different operator altogether. 
Looking at other tools docs they don't mention this option. They only have equals/contains as an `or`. 

> Our current filters allow the user to specify many filter values:

Yes I know. Our equals operator maps to `WHERE X IN ( value1, value2)` which I would keep.

**Comment by owlas** [comment]
Got it! Let's stick with that. 

This seems simple and flexible!

**Comment by ZeRego** [comment]
```
operator: 'after'
values: [200, 'days', 'ago'] # is that a thing? typing is a bit messy
```
@owlas I have been thinking about what you said

What do you think if we had a `settings` property where the properties are specific for each operator ? 
- easier to extend and refactor without breaking changes
- clear typing

```
// this is the base filter rule type, we would have a specific on each operator
type FilterRule = { 
    target: {
        fieldId: string; 
    }; 
    operator: string;
    settings?: object; 
    values?: any[];
};

const example = {
    target: {
        fieldId:'a_b',
    },
    operator: 'before',
    settings: {
        measure: 'days',
    },
    values: [200],
};
```

**Comment by ZeRego** [comment]
UX inspiration: 

<img width="994" alt="Screenshot 2022-01-31 at 16 57 35" src="https://user-images.githubusercontent.com/11660098/151838047-fb9fd583-be77-4637-88c2-71d4467ce573.png">

**Comment by owlas** [comment]
@ZeRego yeah I'm up for a settings object. From the last filters complexity I think we need the flexibility, even if it requires lot's of `switch(filter.type)` in the code.

**Comment by ZeRego** [comment]
Note: Dimension filters can't be mixed with metric/table calculation filters. @PriPatel this has an impact on the UI/UX.

```
WITH temp_table AS (
  SELECT product, sum(sales) as total_sales
  FROM table
  WHERE product != 'shoes'  # dimensions only
)
SELECT *
FROM temp_table
WHERE total_sales > 100  # metrics AND table_calculation > 100. # metric and table calculation
```

**Comment by TuringLovesDeathMetal** [comment]
This feels okay? 

@ZeRego @PriPatel I'm not sure if this is useful, but here's some context on how I'd work with filters in Looker:

[Looker only lets you filter on _**one**_ dimension or metric type and include AND/OR's **_within_** them.] (https://docs.looker.com/exploring-data/filtering-and-limiting#:~:text=Click%20the%20%2B%20to%20the%20right%20of%20a%20filter%20to%20add%20another%20option%20to%20the%20filter.%20The%20new%20option%20will%20appear%20as%20either%20an%20OR%20condition%20or%20an%20AND%20condition%2C%20depending%20on%20the%20type%20of%20filter%20option.%20For%20example%3A) _**Between**_ fields was always an `AND`. 

![image](https://user-images.githubusercontent.com/31848148/152129947-07d8b2f9-cac9-40a3-9084-1e60b0fbd1c1.png)

So, I could do this:
```
Users Count unique user IDs: is greater than 10 OR is less than 5. 
AND 
Users Date created: is before January 1st, 2020
```

But I couldn't do this:
```
Users Count unique user IDs: is greater than 0
OR 
Users Date created: is before January 1st, 2020
```

And I couldn't do this:
```
Users Count unique user IDs: is greater than 0 AND Users Date created: is before January 1st, 2020
OR 
Users Count unique user IDs: is less than 5 AND Users Date created: is before January 1st, 2020
```

If I needed to use `OR` logic _**across**_ two fields or groups of filters (so, the last two filtering examples I gave above), I would have to create two explores with the separate join logic, then merge them together ([using Looker's merge functionality](https://docs.looker.com/exploring-data/exploring-data/merged-results)

^This felt like quite a broken user experience (and it sounds like we're building it differently) _**but**_, I probably did this merging fuss about once out of every 100 times I built an explore.

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 
I'm not a big fan of looker approach. I don't think a user should have to know SQL or restructure their explores / join logic so they can have an OR between 2 fields. This restriction seems to be related to their UI where the field can only be defined once in the filters.  

As a user I would prefer to have a few extra clicks, to add multiple filters for the same field, if that meant more flexibility. These extra clicks can also be done by any user while writing SQL for advanced filters wouldn't.

**Comment by ZeRego** [comment]
Saying that, I can imagine us having a toggle between `basic filters` and `advanced filters`. 🤔 
In the basic filters we could have a UI like looker with an implicit `AND` and in advanced mode have the option to change operators, nested rules, etc.

**Comment by TuringLovesDeathMetal** [comment]
totally! I definitely prefer not having to write SQL to be able to get `or` in a filter. The way you've approached it is much better :) 

Also _**love**_ the suggestion of having a toggle between `basic filters` and `advanced filters`

**Comment by PriPatel** [comment]
@ZeRego 

[Walkthrough V1](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1175%3A43264&scaling=min-zoom&page-id=1170%3A42638&starting-point-node-id=1175%3A43264&show-proto-sidebar=1) - And/or filters _without_ nesting. We should talk about what happens when you hit 'add' and how you select fields from the dropdown. Its not clear in the app rn that that the user can search using autocomplete because the dropdown list is so long that it covers everything!


[Walkthrough V2 ](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1175%3A43702&scaling=min-zoom&page-id=1170%3A42638&starting-point-node-id=1175%3A43702&show-proto-sidebar=1) -  This is an idea of nesting _could_ work . As we're not planning on building this right away, maybe I can test this with people. I imagine the visuals might change a bit, but Im happy with how it works and how its an extension of V1! Also I'm unsure about how the text field widths should change as the user keeps adding groups.


Let me know your thoughts :) 

[Figma file](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1170%3A42638)

**Comment by ZeRego** [comment]
@PriPatel Once they select a dimension and a metric we need 2 nested groups, 1 for dimensions an 1 for metrics. Like this:

![Screenshot 2022-02-03 at 09 25 12](https://user-images.githubusercontent.com/9117144/152315502-6f3e96c1-b24f-4e59-9515-b95a3ed8a790.png)

It would be great if we could select the field before/outside of the filter group since it would have a cleaner implementation. 
E.g:

```
Filters:
AND
 - (dimension filter rule ) field input - operator input - value input 
 
[Add field button]
```
User click on 'Add field'
```
Filters:
AND
 - (dimension filter rule ) field input - operator input - value input 
 
[ field input autocomplete ]
```

if user selects dimension
```
Filters:
AND
 - (existing dimension filter rule ) field input - operator input - value input 
 - (existing dimension filter rule ) field input - operator input - value input 
 
[Add field button]
```

if user selects metric
```
Filters:
AND
   AND
       - (dimension filter rule ) field input - operator input - value input 
   AND
       - (metric filter rule ) field input - operator input - value input 
 
[Add field button]
```

**Comment by owlas** [comment]
@ZeRego in that last case, they wouldn't all need to be nested though?

I could have:

```
AND
  dimension filter
  dimension filter
  metric filter
  metric filter
  dimension filter
```

That's no problem right?

I think the frontend can look different to the data structure at the backend. So although it looks like a giant list of `AND` filters to the user, we can separate those out into dimensions and metrics behind the scenes before submitting it to the API.

So using the API would require the full spec, but the frontend provides a better UX.

The complexity comes in these two cases:
 - User wants to mix `OR` and `AND` - now you need nesting (sad face)
 - User wants to `OR` between dimensions and metrics - impossible (even more sad)

**Comment by PriPatel** [comment]
<img width="836" alt="Screenshot 2022-02-03 at 15 14 49" src="https://user-images.githubusercontent.com/12776522/152371120-77403852-59c1-47a0-a556-9028350cc837.png">

Another way of grouping things without the need for nesting?

**Comment by PriPatel** [comment]
I did some rapid prototyping and testing with 2 people. [Here is the outcome](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1288%3A42756&scaling=min-zoom&page-id=1170%3A42638&starting-point-node-id=1288%3A42756&show-proto-sidebar=1) 
-  they preferred indenting the fields as they felt that it read better.
- They preferred being explicit:  `Any of the following * metric * conditions match: `/ `Any of the following * dimension * conditions match:` when we display the two groups.

I could keep going with this but due to time constraints, I propose we go with this as the functionality has already been built.  Let's get feedback and iterate based on use cases!
