### ISSUE TITLE
Inconsistent modals when trying to delete charts / dashboards.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1892]
- [x] You should see the **delete chart modal** when you try to delete a chart from the **`homepage`** / **`saved charts area`** / **`the saved chart` itself**. 
(Right now, this only appears in one place. When you try to delete a chart from the homepage, it shows you the delete dashboard modal.)

- [x] You should see the **delete dashboard modal** when you try to delete a dashboard from the **`homepage`** / **`saved dashboards area`**. 

**Delete chart modal**
<img width="516" alt="Screenshot 2022-04-26 at 09 31 14" src="https://user-images.githubusercontent.com/12776522/165257685-6c216ea6-a835-4d12-ad9c-1fdc96be6044.png">

**Delete dashboard modal**
<img width="511" alt="Screenshot 2022-04-26 at 09 30 15" src="https://user-images.githubusercontent.com/12776522/165257701-e0f512fe-050d-4588-99ea-ff86773d1802.png">

**Comment by hamzahc1** [comment]
This is actually a bigger problem 🚨🚨 - you can't delete any charts from the Home page or Saved charts area as it thinks they're dashboards: 

https://www.loom.com/share/9bc6f0a97ab1464aabc9149b5a2d0b79

**Comment by PriPatel** [comment]
@hamzahc1 Ive updated my original comment.
