### ISSUE TITLE
Cross-filtering should apply to group values (not just x-axis values)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1899]
### Description: What is it?

When I click to cross-filter on my dashboard, I should be able to filter by the group _**or**_ the x-axis value

### What: Roughly, what does this look like in the product?
I'd be able to filter by the group value (not just the date) in this chart

<img width="851" alt="image" src="https://user-images.githubusercontent.com/31848148/165280512-dacc5e75-7cda-4e76-92f1-cbc822edbb91.png">

**Comment by owlas** [comment]
This already exists on #1409 - will close that in favour of this
