### ISSUE TITLE
I want to be able to set my results table to have no row limit

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1908]
### Description: What is it?

I want to be able to set the row limit in my results table to be `none` so it returns _**all**_ the rows in my query

### Problem: What problem does this solve?

If I want to see all of the data from my query, but I don't know how many rows that is, then I want an easy way of making Lightdash query all of my data

### What: Roughly, what does this look like in the product?

in the `row limit` there's some way of setting `no limit`

**Comment by PriPatel** [comment]
![Screenshot 2022-04-26 at 18 14 01](https://user-images.githubusercontent.com/12776522/165355910-89cc8f50-ff40-40d2-a110-ae81b33c45b4.png)
Add a toggle in this popup:  `Limit` / `No Limit`
If `No limit` is selected, disable the number of rows input field.

**Comment by JohnRomanski** [comment]
Shouldn't there be SOME limit on the amount of rows returned to the chart? This can be a lot. (IoT, pageviews) 
(Looker sets a maximum limit of 5000, higher than that the table and charts can have trouble rendering. Looker does allow you to Download all results for use elsewhere, handy when I want a list of 350K subscriber IDs who signed up in March)

**Comment by TuringLovesDeathMetal** [comment]
Closed as I don't think we should do this. Having a no row limit doesn't make sense - like John said, it would cause the app to get super laggy and potentially crash.
