### ISSUE TITLE
Add a link to the table calculation templates to the table calculation modal

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1909]
### Description: What is it?

Now that we have templates for table calculations, we should add a link to this in the modal for table calculations

### Problem: What problem does this solve?

Some users might find it overwhelming to write table calculations - this helps them out.

### What: Roughly, what does this look like in the product?

The `check out our templates` should be linked to: https://docs.lightdash.com/guides/adding-custom-metrics-table-calculations-explore

### Design
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=3500%3A73195
A couple of **nice-to-haves** that will make the addition of this better: 

- Change title from `Save` to `Add table calculation`
- Change appearance and form of 'view full screen mode'.

**Comment by rephus** [comment]
@TuringLovesDeathMetal  I get a 404 on this page https://docs.lightdash.com/guides/adding-custom-metrics-table-calculations-explore

**Comment by rephus** [comment]
I can't see on the design how to change the `fulllscreen`button when it is active (now we have a toggle). For now I'm making the button `active`, but I could also change the icon...

**Comment by TuringLovesDeathMetal** [comment]
@rephus do you mean how to go from fullscreen --> not fullscreen? 

Could we use the `minimize` icon? 
<img width="142" alt="image" src="https://user-images.githubusercontent.com/31848148/166930177-a07f1745-a1ab-427d-9418-5f200d7f2f29.png">
