### ISSUE TITLE
Add Lightdash branding to the User sign up screen  

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1911]
### Description: What is it?

The current sign up screen doesn't include any reference to Lightdash. We could add the logo the sign up screen and update the text to: 

Create account --> Create your Lightdash account

![Screenshot 2022-04-26 at 22 24 08](https://user-images.githubusercontent.com/14341285/165395619-22ea88b9-5290-4164-ad27-63e72b43b4ce.png)

**Comment by PriPatel** [comment]
@hamzahc1 Ill turn this ticket into a design task & assign to myself as part of the work i'm doing on the onboarding screens.
Will hand over in a separate ticket for implementation !

**Comment by PriPatel** [comment]
closing this issue as its been taken care of in the new sign up screens:
