### ISSUE TITLE
You can't reliably access the actions dropdown under a metric/dimension

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1920]
Just found this when doing some user testing. The user was super confused as to why the dropdown kept disappearing! Best demonstrated in a loom:
https://www.loom.com/share/179ffc267ef14087830940b2e147d33c

I've also been experimenting with the speed at which I control the mouse but can't seem to find any patterns - it appears random to me.

**Comment by TuringLovesDeathMetal** [comment]
closed in favour of #1931
