### ISSUE TITLE
I want to land in the last project I was on when I open Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1929]
### Description: What is it?

If I have multiple projects in Lightdash, I don't want to land in the one that's alphabetically at the top. Instead, I want to land in the one I was most recently in.

### Problem: What problem does this solve?

Every time I open Lightdash, I'm put into `jaffle shop` instead of `lightdash` and I have to navigate out of it. It's super annoying. 

### What: Roughly, what does this look like in the product?

- [ ] we "remember" the last project the user was on and it's the project they see when they login/open a new window
- [ ] If there is no "latest project", then we default to showing them the first project in the alphabetically ordered list of projects

**Comment by PriPatel** [comment]
Im working on allowing the user to change the settings! 
However,  I wonder if we can 'remember' the last project the user was on and make that the first project they see when they next log in? It's just that navigation and settings panel is a bit of a mess, so I don't think that this solution is _that_ intuitive. It would be amazing if they just log back into what they left.

**Comment by ZeRego** [comment]
@PriPatel That is possible. We could save that info in the browser to avoid work on the DB and have to constantly update the DB with the latest viewed project. The cons of this approach are small and understandable imo. We would not "remember" if they clear cookies/cache or use a different browser or use a different device.

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal 
Do you think that my above suggestion PLUS [this change to the settings panel](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=3759%3A76359&scaling=min-zoom&page-id=2208%3A45403&starting-point-node-id=3759%3A76359) will suffice? Im really keen to move onto fixing this settings panel, so have suggested what I hope is a cheap solution.

**Comment by TuringLovesDeathMetal** [comment]
nice!

@PriPatel what happens if the last project I was on _**wasn't**_ my default project? 

Do I get sent to the last project I was on, or do I get sent to the default project?

**Comment by TuringLovesDeathMetal** [comment]
My vote is for _**no**_ design changes in the settings panel, and just implementing the change in the backend where we bring you back to the most recent project you had open. WDYT?

**Comment by ZeRego** [comment]
> what happens if the last project I was on wasn't my default project?

The priority order would be:

1. latest project
2. default project
3. first project in the projects list

> My vote is for no design changes in the settings panel, and just implementing the change in the backend where we bring you back to the most recent project you had open. WDYT?

Note that this is still a frontend change, just doesn't need UI changes.
I also prefer implementing the `latest project` since I find it more useful and it would make the default project feature almost insignificant.

**Comment by PriPatel** [comment]
> @PriPatel what happens if the last project I was on wasn't my default project?
In the proposed design , you should only be able to switch projects using the dropdown in the navbar. Changing the default project doesn't mean it will change where you are at the moment. You will get a toast confirming the change in default project, but nothing more. 

However, based on the other comments in this thread, my above point is irrelevant!!- I would prefer the user to always just log back into their latest project. Some people might be working on multiple projects, so a default project wouldn't really help! It would be much nicer to just pick up where you left off!

**Comment by TuringLovesDeathMetal** [comment]
Sweet! I'll update the ticket details then :)

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal Was no trouble,as I said, it was a very cheap solution !!! Im just glad we're not changing the UI!
