### ISSUE TITLE
Dimension options menu sometimes closes unexpectedly

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#1931]
### Describe the bug

I suspect the problem is that the TableTree component is rerendering to often and causes the menu to close.
The component seems to rendender when the user hovers a menu item since it updates the `hoveredFieldId` state.
```const [hoveredFieldId, setHoveredFieldId] = useState<string>('');```

### To Reproduce

Haven't found a way to replicate 100% of the times.

### Screenshots or Loom video

<a href="https://www.loom.com/share/56ce34d901c7426bb9b5a7e165793c90">
    <p>Lightdash - dimension options menu sometimes closes unexpectedly  - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/56ce34d901c7426bb9b5a7e165793c90-with-play.gif">
  </a>

**Comment by PriPatel** [comment]
@ZeRego 
Is this the same as https://github.com/lightdash/lightdash/issues/1920
