### ISSUE TITLE
Add chart description to the Explore view

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1940]
### Description: What is it?

We ask users to give a chart a description when they save it. We should show this in the explore view.

### Problem: What problem does this solve?

The chart description isn't used anywhere and it's helpful to give people context.

### What: Roughly, what does this look like in the product?

Under the chart title, in a non-dominant text, there should be the chart description.

**Comment by PriPatel** [comment]
https://github.com/lightdash/lightdash/issues/1819

**Comment by nathaliabj** [comment]
Closing this issue as it is no longer relevant, descriptions have already been implemented on the explore view.
