### ISSUE TITLE
When a metric/dimension has been selected, the action button should be visible (not just on hover)

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1942]
This helps discoverability for being able to add filters, and if its a dimension, adding custom metrics.

**_**Old:**_**
![Screenshot 2022-04-29 at 10 16 26](https://user-images.githubusercontent.com/12776522/165917335-a483e4ff-3f37-4f37-806f-07c3ecba175c.png)

****Proposed:***
![Screenshot 2022-04-29 at 10 16 29](https://user-images.githubusercontent.com/12776522/165917346-b93b3ecd-96e9-4e92-b2da-1cc9d19f1b42.png)*

**Comment by rephus** [comment]
@PriPatel only when selected, right ?
