### ISSUE TITLE
Panel titles are not aligned properly

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1960]
<img width="249" alt="Screenshot 2022-04-29 at 17 31 14" src="https://user-images.githubusercontent.com/12776522/165986001-ade524d7-b401-4388-a97e-f3280194b757.png">

- 'SQL' title looks pretty vertically unaligned. 
- It also looks like `Filters` `Charts` and `Results` don't align with the dropdown arrow properly. I cant be sure if it was always like this though!

**Comment by nathaliabj** [comment]
@PriPatel i cant reproduce this issue, could you please confirm ?
<img width="286" alt="Screenshot 2022-05-09 at 16 11 21" src="https://user-images.githubusercontent.com/31137824/167443625-41328d8e-7000-462f-8ed0-dcf651780201.png">

**Comment by ZeRego** [comment]
Yeah #2022 fixed that. didn't know we had a ticket for it already
