### ISSUE TITLE
You should have the option to change the `separator style` in big number charts

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1968]
### Description: What is it?

Currently numbers are not formatted with commas which would make them more legible. You should have the option of adding commas (or other separator styles) to your big number charts.

### Problem: What problem does this solve?

It makes charts more readable 

### What: Roughly, what does this look like in the product?

![image](https://user-images.githubusercontent.com/31848148/167093914-f28159b5-5685-4a4f-b1a0-e34805073c76.png)

**Comment by TuringLovesDeathMetal** [comment]
Option: Add `separator style` to Big Number charts.
![image](https://user-images.githubusercontent.com/31848148/166670995-f8efde09-09ef-4932-a58c-31ff68c71ab1.png)
