### ISSUE TITLE
Add friendlier empty states for 'metrics' & 'custom metrics'

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1969]
### **State** : **_No_** metrics defined in dbt project & we _can_ detect magic metrics
- [x] Change placeholder text under `Metrics`
- [ ] ~Add 'magic metrics' back in, but instead, put them under `custom metrics`.~
- [x] Information icon next to `Metrics`, linking to [this doc](https://docs.lightdash.com/get-started/setup-lightdash/add-metrics#2-add-a-metric-to-your-project)
- [x] Information icon next to `Custom Metrics`, with a short description about how to add a custom metric and link it to [this doc (when the doc has been published)](https://deploy-preview-1974--peaceful-bassi-cbf284.netlify.app/guides/adding-custom-metrics)

### **State** : Metrics _**are**_ defined in dbt project

- [x] Remove placeholder text under `Custom metrics`.
- [x] Information icon next to `Custom Metrics`, with a short description about how to add a custom metric. 
- [ ] ~No need to show 'magic metrics'~

### **State** : Metrics _**are not**_ defined in dbt project and we **_can not_** detect magic metrics

- [x] Change placeholder for `custom metrics`

### **All screens here:**
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=3545%3A75955

**Comment by hamzahc1** [comment]
@PriPatel - magic metrics don't always get defined (I believe they rely on an ID column existing), would you still want to have a placeholder text under `Custom metrics` if none are avaialble.

**Comment by PriPatel** [comment]
**Updated to show a third state:**
No metrics defined in dbt project _and_ we can't show magic metrics

**Comment by ZeRego** [comment]
The code that generates magic metrics has been removed 😬  so I propose we create a separate ticket to bring those back.
