### ISSUE TITLE
Big Number charts should have a `style` formatting option

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1983]
### Description: What is it?

There should be a drop-down option for Big Number type chart which is `style` (e.g. if I have 150,000 it would set it to 150K or if I have 1,500,000 I could set it to 1.5M)

### Problem: What problem does this solve?

It's harder to read big numbers that aren't rounded to a different format.

### What: Roughly, what does this look like in the product?

- You can select the `style` from a dropdown menu
- Unit options are: `thousands (K)`, `millions (M)`, `billions (B)`
- This option ONLY appears for `numeric` big number fields (it doesn't appear if you have a date field or a string)

**Comment by rephus** [comment]
In this case, I'm trying to apply the style on top of the format ($) which is already a string. 

![image](https://user-images.githubusercontent.com/1983672/166881654-900f15af-0132-4a9f-99f5-02d34db5d055.png)

It sounds like we need to apply style first on the `raw` and then apply the format there. Unless you think they are not compatible /cc @owlas

**Comment by rephus** [comment]
I'm still not sure how to handle smaller numbers: 

> What happens if a number is not big enough ? 
>  eg: 1,000 M -> 1,000 (no changes) or 0.001M ?

**Comment by rephus** [comment]
I'm building some tests to ensure the format / round / style works as expected, do you think this is what we should expect ? 

```
            expect(formatValue('km', 2, 5000, "k")).toEqual('5.00K km');
            expect(formatValue('mi', 4, 50000, "k")).toEqual('50K mi');
            expect(formatValue('usd', 2, 5000, "k")).toEqual('$5.00K');
            expect(formatValue('usd', 2, 5000000, "k")).toEqual('$5000.00K');
            expect(formatValue('usd', 2, 5000000, "m")).toEqual('$5000.00M');

            expect(formatValue('usd', 0, 5000.0, "k")).toEqual('$5K');
            expect(formatValue('usd', 2, '5.0000', "k")).toEqual('$5.00K');
            expect(formatValue('gbp', 2, 5000, "k")).toEqual('£5.00K');
            expect(formatValue('eur', 2, 5000, "k")).toEqual('€5.00K');
            expect(formatValue('percent', 2, 0.05, "k")).toEqual('5.00%');//No affects percent
            expect(formatValue('', 2, 5000, "k")).toEqual('5.00K');
            ```

**Comment by rephus** [comment]
Preview ![Peek 2022-05-05 10-32](https://user-images.githubusercontent.com/1983672/166888760-19cea902-ac18-4064-ac7f-b36c844a87f2.gif)

**Comment by rephus** [comment]
Preview ![Peek 2022-05-05 10-37](https://user-images.githubusercontent.com/1983672/166888931-a1be9cc1-925b-444a-a654-451df2db0a4f.gif)

**Comment by TuringLovesDeathMetal** [comment]
> Also, what about percent ? that format is already a bit special
I don't think there should be an option to add a `style` to a percentage. 

Only to `number` values and currency values (not percentages). is that possible? 

> I'm still not sure how to handle smaller numbers:
What you've implemented looks good to me! If the number is too small, then I'd expect the user to change the style.

**Comment by rephus** [comment]
small numbers are automatically converted by JS to scientific notation, is this a good thing ? 
![image](https://user-images.githubusercontent.com/1983672/166903879-9ed94bae-0e07-4d23-ba41-1b2339b63826.png)
