### ISSUE TITLE
The styling in the tabs across the Settings modal is inconsistent

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1985]
We've added new tabs separately over time and so there is a bit of inconsistency in the styling.

- [ ] All input fields should follow the same styling as the fields in the `Organization` tab 
- [ ] `Invite users to your organization` should be `h3`, and match the title in the `Appearance` tab

**Comment by IntervalsCM** [comment]
Hi, is this issue still open?

**Comment by TuringLovesDeathMetal** [comment]
@IntervalsCM yep, it is!

**Comment by IntervalsCM** [comment]
I would like to work on this issue @TuringLovesDeathMetal

**Comment by TuringLovesDeathMetal** [comment]
Nice, go for it @IntervalsCM!

If you need any help, feel free to pop a comment in here, or you can [join our Slack community](https://join.slack.com/t/lightdash-community/shared_invite/zt-1bfmfnyfq-nSeTVj0cT7i2ekAHYbBVdQ) and chat to us there 😊

**Comment by crismxiex** [comment]
I'm having some issues trying to set up the local dev environment in a widows 10 machine. Once I manage to get past that will get to this issue.
