### ISSUE TITLE
Support for Trino database

### ISSUE THREAD

**Issue by claudino-kognita** [lightdash/lightdash#1989]
### Description: What is it?

Lightdash should support trino as a data source

### Problem: What problem does this solve?

Trino (and Presto) are common data wareouses for the big data world, it would be useful to use lightdash with them.

### What: Roughly, what does this look like in the product?

It will be just another source for data, like Postgres or Bigquery

**Comment by owlas** [comment]
Hey @claudino-kognita - thanks for opening this feature request! We'd love to support Trino.

**Comment by owlas** [comment]
@all-contributors add @claudino-kognita for ideas

**Comment by Tomme** [comment]
Interested in this too 👀

**Comment by rostykob** [comment]
Anything new happened here ? When we can expect the trino connector? There are lots of interest in it :)

**Comment by owlas** [comment]
Somebody else just voted for this in the community!! We hadn't prioritised it but it looks like it's time to revisit that decision 🙌 

We also want to make it much easier to contribute adapters too

Does anybody here have experience with Trino that could help template some of our queries? Just understanding the right delimiters and functions in Trino. Which SQL dialect is it most similar to?

**Comment by claudino-kognita** [comment]
Oliver, please, include my personal github account in this task:
andreclaudino, then I can receive the messages (this is my work account).

I have experience with trino, the SQL Dialect is close to spark's one (and
a few less close to postgres dialect).

Em qui., 24 de nov. de 2022 às 10:35, Oliver Laslett <
***@***.***> escreveu:

**Comment by claudino-kognita** [comment]
> @owlas
> 
> I've put up [a pull request](https://github.com/lightdash/lightdash/pull/2025) to add @claudino-kognita! tada

Please, change to my personal account `andreclaudino`, then I will be more up-to date to notifications and could colaborate.

**Comment by vapolonio** [comment]
Hi guys, I'm working in this connector in the past days where I'm have obtained good results.
Currently the connector works with dbt-trino extension and can make most general querys over a trino database with basic auth password.
For now I'm working in the tests and with it I will submit the PR 😄
