### ISSUE TITLE
Adapter for dbt cloud scheduler

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#199]
Allow users to use a dbt cloud job as a project source. Instead of using local files, obtain the manifest.json via the dbt cloud api

Requires #198

**Comment by TuringLovesDeathMetal** [comment]
@owlas @ZeRego  I feel like this is supported now, no?

Can we close this?

**Comment by TuringLovesDeathMetal** [comment]
@owlas - we can support a dbt cloud account + environment now, but not a job (e.g. the Nightly job)

Do we still want to do this? I don't think this is a requirement for dbt cloud integration, but I'm not sure if I'm missing something...

**Comment by owlas** [comment]
I don't think it's essential.

There are two benefits to dbt cloud job source: 
1. If you don't use GitHub but you do use dbt cloud, then we can only get information on the production environment from the dbt cloud job. Otherwise we can only access dev branches in dbt cloud. 
2. If you want dbt cloud to refresh only after the nightly job runs. e.g. if you connect lightdash to GitHub, then lightdash will update the instant you merge to `main`. If you connect lightdash to dbt cloud job, then you can merge to main and lightdash **will not update** and will wait until the next dbt cloud job runs, then lightdash will update.

I think (1) is quite uncommon. I think (2) will only matter if users don't do `dbt run` on every merge to `main`

**Comment by TuringLovesDeathMetal** [comment]
Cool. 

Mmm, I would want it to update if I changed my metrics though (not necessarily my dimensions), so I feel like having it synced to a job would be annoying here. 

I'm going to close this issue for now because we're focused on building out the GitHub integration (whether it's with dbt cloud or a non-cloud project). And this doesn't seem like a feature that we'll build any time soon.

**Comment by TuringLovesDeathMetal** [comment]
Sweet, I'll add it to `building stuff in Lightdash is awesome!`

**Comment by TuringLovesDeathMetal** [comment]
Closing this because I don't think we're going to build this anymore (no one has requested it).
