### ISSUE TITLE
Bring back 'magic metrics'

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1993]
This is the second part of the ticket https://github.com/lightdash/lightdash/issues/1969

### **State** : **_No_** metrics defined in dbt project & we _can_ detect magic metrics
- [ ] Add 'magic metrics' back in, but instead, put them under `custom metrics`.

### **State** : Metrics _**are**_ defined in dbt project
- [ ] No need to show 'magic metrics'

All screens here:
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=3545%3A75955

Tech notes:
In the BE only generate magic metrics if there are no metrics in the dbt model. This way we don't need any logic in the FE.

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal what is the probability of us start using table calculations instead of magic/custom metrics ? there have been some discussion about this.

**Comment by TuringLovesDeathMetal** [comment]
I'm not sure!

What could see happening is:
- table calculations + custom metrics become the same thing. 
- BUT we still keep the interactions with them as they are in the app (i.e. we'd keep the custom metrics on the left, still give users magic metrics if they came in with no metrics in their project and the table calculations button above the results table...but we'd just change the copy on all of them to be the same name). 

does that help answer your question?

**Comment by PriPatel** [comment]
> I suggest magic metrics be custom metrics that are generated on the fly when the page loads. This will keep our UX and code simple and consistent.

> Can we make them disappear when users have their own metrics?


Im a bit confused! Both of these are points are part of the original design?
See my first comment:


**State : No metrics defined in dbt project & we can detect magic metrics**
>  Add 'magic metrics' back in, but instead, put them under custom metrics.

**State : Metrics are defined in dbt project**
>  No need to show 'magic metrics'

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel we talked about this over the standup on Friday - all good! We're going with the original design. 

There were questions around being able to delete them, and having them pop back up (because the behaviour of these _**new**_ "magic metrics" is slightly different to the old ones). 

We're sticking to the design!
