### ISSUE TITLE
We can't use tableCalculation on bignumbers

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#1996]
### Describe the bug

I added a table calculation, and I wanted to show that as bigNumber , but the charts says there is no data available. Not sure if this is intended .

![Screenshot from 2022-05-05 09-41-15](https://user-images.githubusercontent.com/1983672/166881145-ea6a7396-f77f-4fcb-a1f5-79bb33485931.png)

![Screenshot from 2022-05-05 09-41-23](https://user-images.githubusercontent.com/1983672/166881131-1966dc6b-b78f-44dd-b6fa-051b872924f1.png)

Maybe related ? it is not currently possible to select which result column I want to display as bignumber 

### To Reproduce

1. Go to Explore
2. Add table calculation (eg: type a number) 
3. Select big number chart

### Expected behavior

I'd like to see my table calculation on bignumber

**Comment by TuringLovesDeathMetal** [comment]
Nice, I thought this was a different issue around not being able to pick the column that you can use (in general) for a table calculation: https://github.com/lightdash/lightdash/issues/1520

But sounds like they're separate issues!
