### ISSUE TITLE
Bignumber label is not updated when column changes 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#2019]
### Describe the bug

Label on bignumber  doesn’t change if you change the columns

Tested on a render without the new bignumber style config change, so unlikely to be related 

### To Reproduce

1. Select bignumber table 
2. change columns so it displays a different column
4. See old column name

### Expected behavior

Label should display the new column name 

### Screenshots or Loom video
![Peek 2022-05-06 12-32](https://user-images.githubusercontent.com/1983672/167115999-2f9ebc1b-4185-49a0-9c3f-f22453292d2e.gif)

**Comment by ZeRego** [comment]
This should work the same way as the chart axis labels. The fallback label should not be saved into the big number config. If the label is undefined or empty string we show the fallback label as the input placeholder.
