### ISSUE TITLE
Add quality/resolution option to chart download 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#203]
Currently the chart download generates an image with the same dimension/quality as the chart in the webpage. 
If you have Lightdash in a small browser window the image downloaded will have poor quality. 

We should have a way to select the dimensions ( keeping the correct ratio ) before download the image. 
After we select the file format we can have a number input where the user can write the width and we calculate the height based on ratio. 

 Example:
 
![Screenshot 2021-07-07 at 12 04 22](https://user-images.githubusercontent.com/9117144/124748844-7f6ea200-df1b-11eb-90eb-aeaf44e07cdb.png)

**Comment by hamzahc1** [comment]
Nice - looks good! Should we add a slider or something that shows it going from low -> high quality or small -> large file size?

**Comment by TuringLovesDeathMetal** [comment]
keep this - not a priority though!

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this - no one has requested it yet so I don't think we'll build it
