### ISSUE TITLE
Support multiple organisations in a Lightdash instance

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2031]
### Description: What is it?

Currently, only one organisation can be created in a Lightdash instance. A single instance could support multiple companies by allowing many organisations to exist on a single instance.

**To do**
- [x] Fields in health endpoint

> Remove org specific `hasProjects` but added `requiresOrgRegistration` instead for redirecting to `/register` 

- [x] Register endpoint should always be available. What's initial user?
The initial user is the first user. When the first user is created we create an org with an empty name.
- [x] Is Google user created on correct org?
- [x] Is regular user created on correct org?

> New users registered vida /register create a new org 

- [ ] Invite links are org specific?
- [ ] Where is /org endpoint used?
- [ ] Anything org specific in user router?
- [ ] Org specific in password reset?
- [x] What does /me/complete do?

> Those are user specific, each user will show its own information

- Is when the user selects their role, marketing/analytics. If it is the first user, they also define the org name

- [ ] What if I'm invited to another org? Can I join 2? I shouldn't be able to
- [ ] Lightdash env vars will affect all orgs ? how are we setting these values for each org ? E.g sso

> Yes, lightdash env vars will affect all orgs, we don't have anything for specific orgs...

- They WILL affect all orgs. So everybody will have the same google auth creds. This is actually a feature for us. If people want to customize anything at the env-var level, they'll need Lightdash Enterprise or self-deploy

- [x] what is the UX/flow to create a new org ? would that be different from creating the first org ? They should only be able to create a new org via invite/token. Otherwise people might spam new orgs.   
I'm thinking to leave the existing flow as it is. So if you create a new user (not invited), you create an org. If you are invited to an org, then you join an existing org without creating one.

- [x] will there be security issues with git/warehouse credentials 
Shouldn't be! All data should never be shared between orgs. Am i missing something?

> Added org level permissions to all endpoints (mainly projects) and also removed sensitive information from github error responses

- running with a local dbt project ? how would that work ?
Everyone would have the same local dbt project, obviously this only works for local dev not for a production use case

> If you have `ALLOW_MULTIPLE_ORGS` you will be able to register new users and orgs under the same `lightdash` instance.

**Comment by ZeRego** [comment]
Can we have a milestone for these changes and make this the discussion ticket ? 
Let's try to break down the work into small PR's otherwise is going to be hard to review.

**Comment by rephus** [comment]
@owlas Should I take a look at the checklist ? are we missing anything else ?
