### ISSUE TITLE
It's not obvious that I can interact with the columns in my results table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2038]
### Description: What is it?

I didn't realize that I could right-click and remove or filter on my columns in my results table. There should be a clear indication that there are "actions" available on the results table

<img width="378" alt="image" src="https://user-images.githubusercontent.com/31848148/167436832-ead166dd-568e-4d77-aad3-661c5beb3808.png">

### Problem: What problem does this solve?

Users don't know they can remove or filter on columns from the results table

### What: Roughly, what does this look like in the product?

Maybe the three-dot options menu like with metrics + dimensions?

**Comment by ZeRego** [comment]
I want to push back on this proposal as this is going to pollute our UI.
There are so many websites and applications where we can right click to see more options and there is no visual indication. eg right click on a email in the gmail inbox.

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal Yup agreed its a problem!
 I think we can close this in favour of https://github.com/lightdash/lightdash/issues/1358, where I agree with Jose's points. I carried out an audit for this and do think its a big piece of work -  I can pick it back up again and prioritise when its in the backlog!

**Comment by TuringLovesDeathMetal** [comment]
Closed in favour of #1358 !
