### ISSUE TITLE
Numbers in tables should be right-aligned

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2040]
### Description: What is it?

Numbers in the results tables and in the table viz should be right-aligned

### Problem: What problem does this solve?

It's hard to compare values that are left-aligned 

### What: Roughly, what does this look like in the product?

Numeric values are right-aligned in the results table + table viz
String + date values are left-aligned in the results table + table viz

**Comment by rephus** [comment]
Do we consider a `formatted percent` a number ?

**Comment by TuringLovesDeathMetal** [comment]
Yes! `formatted percent` should be right-aligned too :) 

And Boolean on left - you got it!
