### ISSUE TITLE
Filters general: Add "in the past" date filters

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#205]
Reference:
#171 
https://github.com/lightdash/lightdash/issues/171#issuecomment-875446493

Example filter: `from last 7 days` 
Proposed implementation:
 - FE: have inputs for `measure` ( years, months, weeks, days ) and `quantity`
 - BE: calculate date ( based on current date, measure and quantity ) and apply a `>=` operator   

TODO:
- What filters do we want ? 
- How can we build a query without using SQL server functions ?

**Comment by owlas** [comment]
@ZeRego now we have access to the target database type, this should be much easier. 

@TuringLovesDeathMetal might be worth solving this in a future release soon?

**Comment by TuringLovesDeathMetal** [comment]
The only filter I think that's missing is `is in the past`.

I'd imagine the filter would look the same as it does now, but with another toggle-list to the right of the input value which lets you select the timeframe from: `seconds`, `minutes`, `hours`,(<-- these would only apply for timestamp fields)`days`, `weeks`, `months`, `years` 

The range of time would _**include**_ the current time/date. For example, if today is October 12th, 2021 and I used the filter "is in the past 3 days", I would want it to look at data where the date was either the 9th, 10th, 11th, or 12th of October

**Comment by TuringLovesDeathMetal** [comment]
still relevant. 

other open filter issues: 

#920  #333 #205 #207 #186 #188

**Comment by TuringLovesDeathMetal** [comment]
Another thing to add to this issue, it should have a `complete` option when selecting the timeframe for teh filter. 

More details in this comment (example 2): https://github.com/lightdash/lightdash/issues/572#issuecomment-1020329373

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal What is your opinion in having the 'completed' like this ? or a checkbox 
![Screenshot 2022-02-03 at 18 15 54](https://user-images.githubusercontent.com/9117144/152404069-d31aae25-90c7-4609-a906-052c205bb88a.png)

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego it feels a bit clunky as an extra drop-down box/ it feels like something is "missing" if I leave it empty. 

Ideally, it would be an option in the drop-down timeframes. 

A check-box could be an okay alternative. I just feel like it should go at the end of the statement if it's a check box, and it doesn't really fit in there. 

If adding it to the drop-down is harder, then let's do a check box (that only pops up when you've selected `is in the past`)

@PriPatel any thoughts on this?

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 
It is possible to have it in the same dropdown 👍  FYI I'm going to leave the 'complete' work for a separate PR under the issue #572

**Comment by ZeRego** [comment]
Preview:
![Screenshot 2022-02-04 at 13 40 20](https://user-images.githubusercontent.com/9117144/152538748-b208aa27-cd22-4d67-a414-cbeca277ed15.png)
