### ISSUE TITLE
Regression: We can select style for Bignumber charts with Date metrics 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#2056]
### Describe the bug

The isNumber method is missing Date metrics here https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/hooks/useBigNumberConfig.ts#L61

Field.type for this is `min` because it is a metric on a Date. 

In the original code I did something like 
```
bigNumberRaw.includes('Z'))
```
To check if the string contains a `Z` (casting to Number doesn't work as it will convert just the year) 

### Expected behavior

We should not see the `style` for dates

### Screenshots or Loom video

![image](https://user-images.githubusercontent.com/1983672/167659251-684bc8e1-b1f8-4a03-81e0-3d2d68873002.png)

**Comment by TuringLovesDeathMetal** [comment]
Weird, @rephus  I'm not able to reproduce this behaviour 🤔 

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/31848148/167793797-58931bf5-11f0-43cd-b334-4dc9cf70d298.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/31848148/167793902-cf2d4861-aa7a-4af0-8882-9b8613400486.png">

**Comment by TuringLovesDeathMetal** [comment]
oooooh, nevermind - mine was looking at date _**dimensions**_ ignore me!

**Comment by ZeRego** [comment]
Related: https://github.com/lightdash/lightdash/pull/2077#issuecomment-1123793068

Basically the problem is that we are trying to determine the value type from the metric type. Our logic assumes the metric with type MIN/MAX is numeric but this can also be used for dates. 

Unsure how we should handle this edge case 🤔
