### ISSUE TITLE
Show possible values for dashboard filters

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2059]
### Description: What is it?

When filtering on a dashboard I would like to see a list of possible values for some fields (like auto-suggestion in chart filters)

### Problem: What problem does this solve?

This is particularly important when the users are less familiar with the underlying data.

We have a ticket #1995 to set these from dbt accepted tests, but if the values are frequently changing it becomes very difficult to maintain the list. It'd be better if it was figured out automatically.

### What: Roughly, what does this look like in the product?

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/31848148/167814521-617eb5be-95b8-41cd-b94b-2ff0ce0711aa.png">

- [ ] The list of suggestions is automatically generated. 
- [ ] The list of suggestions contains a list of the distinct values for that column
- [ ] These auto-suggestions work for every string column.

**Comment by blankartzAMEND** [comment]
This would be a immensely helpful feature.  Would it be possible to also extend this to a dashboard level filter?  The screenshot example seems to be focus on Chart creation.
