### ISSUE TITLE
Error messages in the sidebar logs overflow out of the boxes.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2064]
<img width="346" alt="Screenshot 2022-05-11 at 12 09 58" src="https://user-images.githubusercontent.com/12776522/167801104-2f2f2f8c-83bd-4b90-a87e-4dabffb8d53f.png">

**Comment by rephus** [comment]
@PriPatel could you confirm this is still happening ? I can't replicate locally 

![image](https://user-images.githubusercontent.com/1983672/168011522-9b76ffc1-d71d-4cc1-bc05-082059e1ac75.png)

**Comment by PriPatel** [comment]
This still seems to be a issue. heres a screenshot shared by a user (not from Cohere!) 
<img width="68" alt="Screenshot 2022-08-30 at 17 43 18" src="https://user-images.githubusercontent.com/12776522/187492981-a215ba3a-059a-4d23-b736-9fff0c2990f6.png">

**Comment by ZeRego** [comment]
Note that in @PriPatel's example it was a single word ( no white spaces ) and the browser doesn't break words by default.

**Comment by gordonkjlee** [comment]
I experience this in Project Settings > Project Connections if invalid details are provided.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/7281432/189526076-ebfa4b89-aca7-4524-b9a3-23d980d32013.png">

Windows PC
Chrome: Version 105.0.5195.102 (Official Build) (64-bit)

**Comment by rephus** [comment]
Yep, I can replicate on chrome - linux. It seems to be happening only with `dbt compile` errors. However, most errors are covered by `dbt parse` so it took me a while to get one. 

I'll fix it

![Screenshot from 2022-09-12 09-33-43](https://user-images.githubusercontent.com/1983672/189597978-d4e4df8a-9b29-42ed-b49a-416f585c686d.png)
