### ISSUE TITLE
Change dashboard 'headers' to match those of the new 'saved charts'.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2072]
Dashboard header should show description and last edited information. This component should really be the same. This should take into account a sharing link as well. (tbc)

![image](https://user-images.githubusercontent.com/1983672/183430799-81ffe008-1c71-454d-af53-a11dca7df611.png)

- the options in the three-dot menu are the same between the saved chart + dashboard (including moving to spaces)
    
<img width="139" alt="image" src="https://user-images.githubusercontent.com/31848148/183406369-52cde11e-29f4-4330-8a52-826282e7cdae.png">

**Comment by rephus** [comment]
We will be implementing some of the changes on one PR: 

- [ ] Dashboard header should show description
- [ ] Dashboard header should show  last edited information . Currently dashboard endpoint doesn't expose updatedBy name, so we might need a backend change for htis  
- [ ] Duplicate action
- [ ] Move to space action


Sample dashboard response 
![image](https://user-images.githubusercontent.com/1983672/183429925-ed6e7030-3ac7-4f98-929a-4a7bef3a62f4.png)

I suggest we implement `export` dashboards on a separate PR or issue.

**Comment by TuringLovesDeathMetal** [comment]
kewl - removed it from the spec and opened a new issue for it: https://github.com/lightdash/lightdash/issues/2895
