### ISSUE TITLE
Allow multiple users to register with an organization 

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2094]
New flow:
* If there are no users on the instance, I am shown the register page (because of checking `hasUsers` on the health endpoint)
* After that I'm shown the login page (how it works now)
* However, you can manually navigate to `/register` without being redirected
* You can create a new user with an organization

after this it should still not be possible for a user to be in two organizations since users are only associated with orgs when the user is created (via invite code or via registering)

Introduce a new environment variable:
```
ALLOW_MULTIPLE_ORGS=true
```
which defaults to `false`

When creating an org, we should check if there is an existing org and whether multiple orgs are allowed.

### Registering as a new user

Replace `registerInitialUser` with `registerNewUserWithOrg`

Currently used on `POST /register` - this should not be restricted to only a single user. Many people can register to use Lightdash.

All users that register this way will get their own organization

https://github.com/lightdash/lightdash/blob/7745f86b414c9e07aa83de53d5ae7fd5f1c4d3a0/packages/backend/src/services/UserService.ts#L450-L450

**Comment by rephus** [comment]
So, if `ALLOW_MULTIPLE_ORGS=false` we should not allow new users to `/register` , because they will create a new `org` is that correct ? 
We only allow new users to register if `ALLOW_MULTIPLE_ORGS=true`

**Comment by ZeRego** [comment]
@rephus I suppose the health endpoint needs to return `canRegisterOrg: boolean` so the FE allows to register the first org when ALLOW_MULTIPLE_ORGS=false
```
canRegisterOrg: env.ALLOW_MULTIPLE_ORGS === true || countExistingOrgs() === 0 
```

**Comment by rephus** [comment]
I was thinking just checking the flag on the backend when creating new users
```
    async registerNewUserWithOrg(createUser: CreateUserArgs | OpenIdUser) {
        if (!process.env.ALLOW_MULTIPLE_ORGS && await this.userModel.hasUsers()) {
            throw new ForbiddenError('User already registered');
        }
        ```
        
     Otherwise we need to change the flow

**Comment by ZeRego** [comment]
That works if we don't mind people filling up a form to get an error. 

We also need to:
- delete every use of `needsSetup` returned by the health endpoint. Which currently controls when the register page is available and when to redirect to the register page. 
- delete/update the welcome page. I don't think this page makes sense anymore. 🤔  @PriPatel

**Comment by rephus** [comment]
FYI this is the /welcome page. I think you can only see it if you go directly to /welcome if no project is defined 

![image](https://user-images.githubusercontent.com/1983672/168271509-be09eceb-f533-406a-aba2-66d2ae60421b.png)

**Comment by PriPatel** [comment]
Yeah bin it!
