### ISSUE TITLE
Changing the style in a big number should always round to 2 decimal points

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2095]
### Description: What is it?

If I have a big number and I change the style to millions or thousands, we should always just round the value to the nearest 2 decimal points. 

### Problem: What problem does this solve?

It's really hard to read values that aren't rounded. 

### What: Roughly, what does this look like in the product?
This image
![image](https://user-images.githubusercontent.com/31848148/168078013-8d11939b-7511-4eb5-a30a-bb1d09cd98e0.png)

Would end up looking like this:
`23.56M`

**Comment by hamzahc1** [comment]
What if you selected a number that was less than 1% of a million etc? 

This would show up as 0.00 if it was rounded to 2 decimal places 
<img width="453" alt="Screenshot 2022-05-12 at 14 30 06" src="https://user-images.githubusercontent.com/14341285/168086386-330f5cb8-c10d-458f-aa4b-83fc939c7ce4.png">

**Comment by TuringLovesDeathMetal** [comment]
yep, exactly - that's what I'd expect

@hamzahc1 any reason you wouldn't want this?

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal what if the dimension/metric has a round value ? should we use that value or 2 ?

**Comment by TuringLovesDeathMetal** [comment]
I'd say round to 2 of whatever the rounded value is. 

E.g. I have the number 135,450.3945

In my YAML, I have no changes: `135,450.3945`
In my big number chart, I select `thousands`, so I have: `135.45K`

In my YAML I have round `2`: `135,450.39`
In my big number chart, I select `thousands`, so I have: `135.45K`

In my YAML, I have round `-4`: `140,000.00`
In my big number chart, I select `thousands`, so I have: `140.00K`

Does that make sense? (or is that even possible?)
