### ISSUE TITLE
Sidebar : Don't repeat 'parent' name in 'child' field names

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2098]
<img width="366" alt="Screenshot 2022-05-12 at 18 16 52" src="https://user-images.githubusercontent.com/12776522/168096796-d84e6da4-4812-47f8-867c-34b545daaf0c.png">

There is a lot of unnecessary cognitive load in the above screenshot and it means that some field names are being chopped off. 
I expect the child fields to read `day`, `week`, `year`, and `month`

Ive added the discussion tag as there might be a valid reason for the current implementation!

**Comment by hamzahc1** [comment]
No discussion needed - this suggestion is better 🚀

**Comment by hamzahc1** [comment]
Closed by #2518
