### ISSUE TITLE
Add widgets for date time, dashboard filters

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2099]
### Description: What is it?

When adding dashboard filters, I have the option of filtering dates. The interface would be much simpler if I had a slider or something more friendly. 

I find the current dashboard filters quite technical looking and a bit unfriendly!

<img width="347" alt="Screenshot 2022-05-12 at 17 07 44" src="https://user-images.githubusercontent.com/11660098/168120025-881f398d-3b45-47aa-a44f-30744aaeadd8.png">

**Comment by blankartzAMEND** [comment]
Custom date filters based on Datetime fields would be helpful, especially if we could easily select Date Range, Last X range or from a Calendar context.  Slicing data based on date/time is a common activity that if it is not streamlined, the process will always feel painful.

**Comment by blankartzAMEND** [comment]
@TuringLovesDeathMetal Thanks, double checked this and you are correct!  I must have missed this when I was quickly testing Lightdash out.

**Comment by TuringLovesDeathMetal** [comment]
@blankartzAMEND no worries at all! just wanted to make sure I wasn't missing something :)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue - t hasn't been requested by any users in > 18 months. There are a bunch of other, more recent filter requests with open issues! Will reopen if we think it's important.
