### ISSUE TITLE
The panels (filters / sql / chart / results) should be tabs.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2104]
You should be able to switch between these panels using something like the tab key, and where each panel takes up the full screen height. 

Design work required.

**User feedback:**
> Opening and closing the various accordion sections (Filters, Chart etc.) was a bit of a hassle.

`

**Comment by JohnRomanski** [comment]
My question is, does this provide any additional utility to the end user?

**Comment by PriPatel** [comment]
Its a great question @JohnRomanski 
I think this issue is very much a suggested solution and I should rename it to a problem statement!

The problem is that users find it fiddly having to scroll between each open panel, especially on smaller screens. (filters / sql / chart / results). You want a way to switch between each panel easily. A bigger problem is the panels probably don't really make sense in the first place. The filters panel _affects_ the chart and the results. It is closer to the actions you carry out on the left hand side when building a query.

My assumption is that tackling this bigger problem is going to make things feel more intuitive, but also speed up things. Needs research! Would love your input.

**Comment by JohnRomanski** [comment]
I definitely think that SQL and Results are "tab-able" (as they are in Looker) I generally don't care about the SQL while pulling results (that is what the tool is for), until there is a problem, and I need to 'look under the hood'.

The results and the visualization are things that I most often look at together.

Hiding the filter panel in an empty state, or finding a way to collapse it smaller when active are both options.

Allowing the left sidebar to be toggled into a collapsed state would be a great way to reclaim a bunch of screen real estate when building a visualization.

**Comment by PriPatel** [comment]
@JohnRomanski - thats useful, thanks.

> The results and the visualization are things that I most often look at together.
Can you please explain the user flow here? Why are you looking at both together so often?

**Comment by JohnRomanski** [comment]
@PriPatel the results panel determines what is in the visualization, I am comparing what I see in the panels. the visualization can show the trend, the results show the values.
