### ISSUE TITLE
`Run Query` gets hidden when I scroll

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2127]
### Describe the bug

If I'm on the Explore view page and I have enough tabs open to force scroll to be enabled on the screen, then if I scroll down, `run query` disappears.

### To Reproduce

![image](https://user-images.githubusercontent.com/31848148/168624556-6606892a-d3bd-4d1b-a108-64b9034d33da.png)

### Expected behavior

The `run query` button should always be available to click when I'm in the Explore view

**Comment by ZeRego** [comment]
There is a ticket to redesign where the Run query button should be. https://github.com/lightdash/lightdash-internal-work/issues/334
closing this ticket.
