### ISSUE TITLE
Highlight related series on dashboard

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2134]
### Description: What is it?

When I hover over a series it highlights it, it would be amazing if the same series was highlighted across all tiles on a dashboard, that would help me to compare values across charts.

We can trigger this programatically using the echarts action dispatch API: 
* Listen for the highlight event on one chart: https://echarts.apache.org/en/api.html#events.highlight
* Trigger a highlight event on related charts: https://echarts.apache.org/en/api.html#action.highlight

<img width="1360" alt="Screenshot 2022-05-17 at 09 06 32" src="https://user-images.githubusercontent.com/11660098/168761653-c36a2228-315f-4788-9323-07866cd11900.png">

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue - there's been no requests for this from users in 18 months. WIll reopen if it's something we want to explore!
