### ISSUE TITLE
The way we display dimensions/some metrics doesn’t read well. 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2148]
The way we display dimensions/some metrics doesn’t read well. This makes the sidebar , filters, and results tables kinda hard to navigate. You expect the names to flow and make sense but it takes lot of thought - this might be down to the table name being displayed first, like it is part of the name. 
Some better formatting and a Ui rethink of how we display this could help!
<img width="210" alt="Screenshot 2022-05-18 at 14 07 47" src="https://user-images.githubusercontent.com/12776522/169014895-ef7e6fa1-2ea0-4401-8bdf-48f09fb4b57d.png">

**Comment by JohnRomanski** [comment]
You could start by removing bold from the table name (or the field name). Is there an option to hide the Table Name?

**Comment by PriPatel** [comment]
resolved in #2911
