### ISSUE TITLE
Add rudderstack events to CLI

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2189]
### Description: What is it?

Use rudderstack events in cli usage

Events for when:

- A user tries to install the CLI (`cli_install_started`)
- A user successfully installs the CLI (`cli_install_completed`)
- A user runs `generate` (`cli_generate_started`)
    - include: `num_models_selected` as a parameter
    - This should be triggered if a user does `dbt run` or if they just do `generate`.
    - Include `trigger` as a parameter (with has values `generate` or `dbt` based on whether they ran it from `dbt run` or `generate`)
- a user successfully generates the models (`cli_generate_completed`)
    - include same parameters as in `cli_generate_started`
- A user runs a dbt command  (`cli_dbt_command`)

**Comment by rephus** [comment]
@owlas do we need to move the tracking from backend to common for this ? or just copy-paste some of the basic tracking implmentation into the CLI package

**Comment by rephus** [comment]
These events: 

- A user tries to install the CLI (cli_install_started)
- A user successfully installs the CLI (cli_install_completed)

Are they supposed to run on `preinstall` `postinstall` npm scripts ? 

Not sure if `cli_install_started` can be done, as it will be missing some dependencies for this tracking to work...
