### ISSUE TITLE
Support `-m, --models` flag in cli

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2202]
### Description: What is it?

dbt recently replaced `-m, --models` with `-s, --select` but plenty of dbt users still use `-m, --models` as a reflex, we should allow it and it should behave exactly like `-s, --select`

**Comment by TuringLovesDeathMetal** [comment]
I hadn't realized that dbt replaced `-m` with `-s`. Let's just leave it as `-s` then and only support one of them for simplicity!
