### ISSUE TITLE
Default to String dimensions if column can't be found in the database

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2224]
### Description: What is it?

During compiling, we check the warehouse schema to find each column and detect it's type. This can cause errors during compiling + onboarding.

During compilation, let's remove this error and instead default to a `'string'` dimension type if we can't find anything.

We can later introduce a separate process that verifies that the schema.yml files match the database perfectly.

**Comment by rephus** [comment]
@owlas are you actively working on this ? If not I can take a look
