### ISSUE TITLE
SQl runner and explore pages have really long URLs to the point where they are unusable

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2225]
https://lightdash.slack.com/archives/C02DGV9RWKV/p1653393138556739

**Comment by PriPatel** [comment]
Having the 'copy link to clipboard' might help the user copy the link more easily. IT still looks kinda awful when you paste it to share it with someone though.

**Comment by JohnRomanski** [comment]
Is there an opportunity to add a link shortener into the server? a simple hash with a lookup to the extended URL would do it.

**Comment by TuringLovesDeathMetal** [comment]
^ooh love that idea!

**Comment by hamzahc1** [comment]
@owlas if you generate the links when you click the share button... is this also an opportunity to create better unfurls by updating the relevant meta tags when you create this?? #60

**Comment by owlas** [comment]
the current solution would be to generate a short link from the long URL. So the flow goes:

- Got some explorer work in progress
- Hit the share link button (links to that exact state)
- I share with a friend
- They open the link and see the exact state
- BUT if I then change the explore
- Then someone re-opens the link, they’ll see an old version
- Is that expected?

From @TuringLovesDeathMetal 

Yep, that’s what I would expect. Unless it’s a saved chart.
So:

- explore from here/random explore: every link I share is specific to the state of that explore page. If I change something, the link will change, and I’ll need to copy that link and share it.
- saved chart: this link is specific to the saved chart. If I share the link to the saved chart (link 1), then I edit + save it, and share it again (link 2), then link 1 + link 2 should bring me to the same saved chart
- Saved chart, but in edit mode: this should act like the explore from here behaviour. So, if I share link when I’m in view mode, the chart at the link will always show me the most recent version of the saved chart. If I share a link when I’m in edit mode, that link will bring me to a specific chart (and this could be different from the most recent version of the saved chart)

**Comment by owlas** [comment]
FYI lightdash community voted for this to be implemented using nanoid for the links. e.g.:

`https://mylightdash.com/share/aHe9o1` 

**NOT** with uuids (ugly)

**Comment by hamzahc1** [comment]
Another user ran into this again today 😢 - this does make sharing via URL almost unusable if you've made a few changes to the chart/explore

**Comment by rephus** [comment]
so @owlas is this how it is supposed to work ? 

- I want to share a chart / dashboard , I click on `share` button
- this makes a request to the backend with my `current` URL , the backend stores the full URL in database and returns a `nanoid` 
- I share this `<host>/share/<nanoid>` url 
- My friend goes into that url 
- the frontend asks the backend about that nanoid, the backend returns the full URL stored
- the frontend redirects to the full URL

Anything else ?

**Comment by owlas** [comment]
That's it! It might be safer to accept a chart/dashboard id rather than a raw url, so we can safely return a valid lightdash url. Instead of somebody being able to store an arbitrary url.

The other thing is where the button placement to create a share link goes. I don't think we have a design for that. I'd say a little share icon that says "shareable url copied to clipboard" or something

**Comment by TuringLovesDeathMetal** [comment]
I'd add the `share link` here: 
<img width="338" alt="image" src="https://user-images.githubusercontent.com/31848148/195086733-861f3d4f-df1b-4c4f-adfa-d271f58d8235.png">


And have the copy say `share` with a link icon. Then once you click on the button it says `copied link` and the icon changes to a check mark. (similar to when you copy a link to a code block from our docs, for example: https://docs.lightdash.com/get-started/setup-lightdash/get-project-lightdash-ready#:~:text=To%20install%20the%20Lightdash%20CLI%2C%20run%20the%20following%20on%20your%20command%20line.)

**Comment by TuringLovesDeathMetal** [comment]
^I just realized, we have the same share icon in sharing saved charts: 
<img width="218" alt="image" src="https://user-images.githubusercontent.com/31848148/195175908-78a083db-9572-4df5-82d2-557b67584a23.png">


We should re-use this. Also, are there any scenarios where you'd have both share icons in the same place? (I can't think of any...but that would be a bit icky)
