### ISSUE TITLE
String fields are formatted to numbers

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2233]
### Describe the bug

If I have a string dimension with a value `011490` it will be formatted as `11,490`. I would only expect this formatting on numerical dimensions and metrics, not on any string value.

**Comment by ZeRego** [comment]
![Screenshot 2022-05-24 at 15 53 26](https://user-images.githubusercontent.com/9117144/170066104-7ce4171f-bd3d-464b-bfa6-0e363682a85e.png)

We just need to `return value;` when DimenionType.STRING and MetricType.STRING
