### ISSUE TITLE
Generate new dataset to power the Demo

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2238]
We need a new, much more detailed dataset that can be a better basis for our Demo. We want to exhibit more features, cater to more use cases, and to generally be more expansive and impressive. 

Requirements are currently being finalised.

**Comment by JohnRomanski** [comment]
Common use cases I would suggest are related to the e-commerce or subscription website customer lifecycle.
source | sample events
---- | -----
marketing | email sent, email opened, email clicked
web  |  visited web site from email, visited website from FB, visited website from google, clicked call to action, clicked conversion link
user  |  created account
e-commerce  | added item to cart, hit paywall
checkout | started order, abandoned cart,  completed order,  started subscription
payment | money received, or next payment received, subscription expired
consumption | viewed x minutes of video, listened to y minutes of z podcast
