### ISSUE TITLE
I want to see my whole chart while I'm making changes to its config.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2240]
### Description: What is it?

Right now, the configuration panel drops over my chart. This is a bit annoying when I'm trying to change the left axis label, axis limits, group names, etc. because I can't see the chart while I'm changing things. 

<img width="767" alt="image" src="https://user-images.githubusercontent.com/31848148/170241095-ab978a52-df29-4d50-9ed7-19bd53c2c2a4.png">

I'd love it if I could see my whole chart while I'm making changes to the config.

### What: Roughly, what does this look like in the product?

If we keep the drop-down, we could make the chart shrink to be the size of the uncovered part of the chart screen when you toggle on/off the config.

**Comment by PriPatel** [comment]
We did say ages ago that we would keep chart config in the tiny popover until things get too complex and you're right, its now growing by the day :sweat_smile::joy:

this was a solution I was speccing up but needs dedicated time and a bit of research!
![Screenshot 2022-05-25 at 11 33 42](https://user-images.githubusercontent.com/12776522/170243213-4b4ceb84-1bf6-42e8-83ef-e4b23ed14853.png)

**Comment by JohnRomanski** [comment]
I would keep this on the right hand side, where the popover is. The flow should be consistent from general (fields on left) to specific (chart in middle) to more specific (chart options on right) as a general UI guideline.
