### ISSUE TITLE
The default min value on an axis should be the min value in the series

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2244]
### Description: What is it?

the default range is always min = 0 (not min = min value). 

It should be the Min value in the series (not 0)

E.g. here, I would expect that the min value by default would be the min value in the chart (30), not 0

![image](https://user-images.githubusercontent.com/31848148/170296613-3e145fb6-fb8d-4e6f-9f96-de4805eccdc8.png)

If the min value of the chart changes, I would expect the axis to change (in the default settings)

**Comment by ZeRego** [comment]
Echarts supports the string values `dataMin` and `dataMax`. 
Docs: https://echarts.apache.org/en/option.html#yAxis.min
![dataMin](https://user-images.githubusercontent.com/9117144/170323068-d1711985-9907-480f-929e-9d22d50c096e.gif)

**Comment by ZeRego** [comment]
We decided to only change the range when the gap between 0 and the min value is more than 3 times the gap between the min value and max value. 

Set axis min value if `minValue > ( maxValue - minValue ) * 3` and similar for axis max value when handling negative values.
