### ISSUE TITLE
Tooltips show wrong date

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2257]
### Description

If you open this chart in the demo in UTC-X (where X is greater than zero), then the tool tips and x-axis values are one day behind the values in the table:

https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/tables/orders?create_saved_chart_version=%7B%22tableName%22%3A%22orders%22%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22orders_order_date_week%22%5D%2C%22metrics%22%3A%5B%22orders_average_order_size%22%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22orders_order_date_week%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%5D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22orders_average_order_size%22%2C%22orders_order_date_week%22%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22orders_order_date_week%22%2C%22yField%22%3A%5B%22orders_average_order_size%22%5D%7D%2C%22eChartsConfig%22%3A%7B%22series%22%3A%5B%7B%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22orders_average_order_size%22%7D%7D%2C%22type%22%3A%22bar%22%7D%5D%7D%7D%7D%7D

**Comment by rephus** [comment]
I think this datetime format must be an echarts thing, I tried adding `useUTC: true ` flag https://echarts.apache.org/en/option.html#useUTC and even force `xAxis type` to be `time` but it is still showing me the localtime. Any ideas ? 

On the tooltip, we use `valueformatter` but that is only for the yField value not the tooltip "title"
