### ISSUE TITLE
Chart sorting isn't respected with grouping columns

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2258]
### Description

Normally, the order of the data in the explore table controls the order of the data in the chart. For example in the demo I can sort from 99 -> 1 for customer id

[link to chart](https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/tables/payments?create_saved_chart_version=%7B%22tableName%22%3A%22payments%22%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22orders_customer_id%22%2C%22orders_status%22%5D%2C%22metrics%22%3A%5B%22payments_total_revenue%22%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22orders_customer_id%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%5D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22payments_total_revenue%22%2C%22orders_customer_id%22%2C%22orders_status%22%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22orders_customer_id%22%2C%22yField%22%3A%5B%22payments_total_revenue%22%5D%2C%22flipAxes%22%3Afalse%7D%2C%22eChartsConfig%22%3A%7B%22series%22%3A%5B%7B%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22orders_customer_id%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22payments_total_revenue%22%7D%7D%2C%22type%22%3A%22line%22%7D%5D%7D%7D%7D%7D)

However if I add a grouping field to the chart it reorders:

### To Reproduce

[![hello](https://cdn.loom.com/sessions/thumbnails/61379d7aea2a43a0b22a4a1a7cde45b1-with-play.gif)](https://www.loom.com/share/61379d7aea2a43a0b22a4a1a7cde45b1)

**Comment by rephus** [comment]
I'm not sure I understand what the issue is, the chart Xaxis respects the order of results for me
![Peek 2022-05-30 12-15](https://user-images.githubusercontent.com/1983672/170971568-9f0f5564-e998-41ee-b192-ef11dad0f497.gif)

Or do you mean field grouping (also looks ok to me) ?
![Peek 2022-05-30 12-16](https://user-images.githubusercontent.com/1983672/170971551-d291589c-2d84-4505-8ba2-4e5aa5c2d548.gif)

**Comment by owlas** [comment]
Sorry the loom link didn't work! Here's the behaviour I see: https://www.loom.com/share/61379d7aea2a43a0b22a4a1a7cde45b1

Try sorting descending
