### ISSUE TITLE
A need of arranging the order in the legend of a visualization

### ISSUE THREAD

**Issue by BA-CY** [lightdash/lightdash#2268]
### Description

Sometimes there is a need to keep the categories in a visualization legend in a certain order.

### What problem does this solve?

From an aesthetic or communication perspective, it looks better to put those bars of the relatively higher numbers at the bottom

**Comment by JohnRomanski** [comment]
I am not sure that the topic of this ticket fully described the problem. Could you include images (screenshots or Loom video recording) that more fully capture the desired changes? Thanks!

**Comment by BA-CY** [comment]
<img width="511" alt="the desired chart" src="https://user-images.githubusercontent.com/54427954/170847740-e16b4b5b-964b-41c9-b62a-50130834f7a7.png">
<img width="1099" alt="the current lightdash chart" src="https://user-images.githubusercontent.com/54427954/170847745-36e8c13f-35e6-4d71-b4fb-6be99b54de87.png">
Hi there, sorry I wasn't clear about the request. I just updated two screenshots to show the desired chart and the current Lightdash chart. 

As you can see, the Lightdash stacked chart shows the line between the bars, and in its legend, the lines' names are placed among the bars' names. I hope to put the lines together and then the bars together in the legend and the chart.

I hope these help and please let me know if it is not clear.

**Comment by hamzahc1** [comment]
@all-contributors add @BA-CY for ideas

**Comment by TuringLovesDeathMetal** [comment]
the bug/issue mentioned in the screenshot is related to #2524
