### ISSUE TITLE
You should be able to configure your axis tick labels' rotation

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2272]
### Description

You should be able to adjust how the tick labels on your axes are rotated. E.g. 45 degrees, 90 degrees,  

This is different to #2028. This is manual configuration (instead of default configuration)

Right now, we remove a bunch of tick labels because they overlap. The assumption is that if I can rotate the tick labels, then I can fit more values in (because they won't overlap as much). If rotating the axis tick labels doesn't allow users to fit more labels in, then I would not want to ship it. 

### Acceptance criteria

- [ ] I'm able to specify the rotation of the axis tick labels in my chart config. Either we can do this so it's _**totally**_ custom (i.e. you enter a value), or we can have 3 options to pick from: 0, 45, 90
- [ ] By default, my tick labels have 0 rotation
- [ ] Rotating the tick labels should increase the number of tick labels that are shown in the x-axis. If this does not happen, then we should not ship this. 
- [ ] If I rotate my tick labels, the x-axis label is not overlapped i.e. it shouldn't look like this: 
<img width="226" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/114a8c4b-1735-43f6-ac7c-cba34ada458c">

**Comment by magnew** [comment]
Fixed here: https://github.com/lightdash/lightdash/pull/8657
