### ISSUE TITLE
Area charts

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2284]
### Description

I want an `area` chart type. It's basically a line, with the area filled in beneath it. 

### What problem does this solve?

Sometimes, you want to have connected points (since you're looking at trends), but also have the area under the lines clearly highlighted. this is helpful if you're comparing volumes or quantities of things changing over time.

**Comment by JohnRomanski** [comment]
The good news is that in the echarts implementation, this is a line chart.
> When [`areaStyle`](https://echarts.apache.org/en/option.html#series-line.areaStyle) is set, area chart will be drawn.
