### ISSUE TITLE
Create 'you are in' new sign up step

### ISSUE THREAD

**Issue by nathaliabj** [lightdash/lightdash#2289]
### Description
this page goes before the 'connect a project' page, which is an extra step to ask how the user wants to connect the data.

[Design link](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=4659%3A88113)

<img width="228" alt="Screenshot 2022-05-31 at 19 09 18" src="https://user-images.githubusercontent.com/31137824/171233202-cf082ffb-1c6b-4dae-bd64-4c2c75e36351.png">
<img width="243" alt="Screenshot 2022-05-31 at 19 09 10" src="https://user-images.githubusercontent.com/31137824/171233205-13b79057-ae29-416f-bea5-51eefbd59920.png">

**Comment by PriPatel** [comment]
Only the first time
