### ISSUE TITLE
Lightdash preview should point to docs preview url

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#229]
Lightdash preview should use the docs preview url instead of having 'docs.lightdash.com' hardcoded.

- [ ] Support a `DOCS_BASE_URL` env
- [ ] Default to docs.lightdash.com
- [ ] Remove all hardcoded uses in Lightdash info modal

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego is this still relevant?
