### ISSUE TITLE
invite user : blank

### ISSUE THREAD

**Issue by raphaelauv** [lightdash/lightdash#2293]
### Description

When I click on INVITE USER

it give a blank page

![Screenshot from 2022-06-01 11-46-22](https://user-images.githubusercontent.com/10202690/171376726-349829c3-5573-4538-a77e-a1fa9462f8b2.png)
![Screenshot from 2022-06-01 11-46-14](https://user-images.githubusercontent.com/10202690/171376739-017f7b36-bdf1-43ee-a5c5-a55cf2351c63.png)

lightdash version : 0.126.3

Thanks

**Comment by owlas** [comment]
@all-contributors add @raphaelauv for bugs

**Comment by raphaelauv** [comment]
Only as viewer , then a little message explaining why I can't invite 


or a user invitation request to an admin

 would be great

Thanks again
