### ISSUE TITLE
Upgrade node-odbc to support M1

### ISSUE THREAD

**Issue by jamiedavenport** [lightdash/lightdash#2300]
### Description

Experiencing this issue (https://github.com/markdirish/node-odbc/issues/252) when running `yarn install` which is fixed in [2.4.2](https://github.com/markdirish/node-odbc/releases/tag/v2.4.2).

### To Reproduce

- Own an M1
- `yarn install`

Related https://github.com/lightdash/lightdash/issues/878

**Comment by jamiedavenport** [comment]
Hey @JohnRomanski. Yeah I did change the version to `^2.4.2` and it did indeed fix the issue.

**Comment by JohnRomanski** [comment]
@jamiedavenport you will be happy to know that I have now encountered this on my M1. It occurred when I did a `yarn install` from the project directory.

For me, the fix was to 'brew install unixODBC' as described on [the npm page for odbc](https://www.npmjs.com/package/odbc).

**Comment by jamiedavenport** [comment]
I had run `brew install unixODBC` but still get an error.. strange. It's not a massive issues because I can work in Docker but I'm curious what your thoughts are on upgrading in general. I thought https://github.com/lightdash/lightdash/issues/878 was a great idea but it didn't get much traction.

**Comment by owlas** [comment]
Hey @jamiedavenport thanks for catching this, we're updating this and implementing #878

**Comment by ZeRego** [comment]
@all-contributors add @jamiedavenport for bug

**Comment by ZeRego** [comment]
https://github.com/lightdash/lightdash/issues/1558 might be related to this
