### ISSUE TITLE
Updating username in settings returns only partial menu

### ISSUE THREAD

**Issue by JohnRomanski** [lightdash/lightdash#2303]
### Description

I updated my user name in settings and only a part of the settings menu was returned/replaced when I submitted successfully.

### To Reproduce

Update your username in the settings. Observe that the bottom part of the menu disappears. `Organization` and everything after.

BEFORE:

<img width="364" alt="Screen Shot 2022-06-03 at 10 05 14 AM" src="https://user-images.githubusercontent.com/382382/171870150-792be795-64d8-4ed7-8970-c7e7a1f30c3e.png">

AFTER:
<img width="537" alt="Screen Shot 2022-06-03 at 10 05 33 AM" src="https://user-images.githubusercontent.com/382382/171870276-82ebd69b-cc0a-45aa-9461-a7c93a110b21.png">

**Comment by owlas** [comment]
@JohnRomanski had you recently updated your permissions? e.g. to a viewer? 

I'm wondering if the sidebar isn't updating when somebody's permissions is reduced from an admin/editor to a viewer.

**Comment by ZeRego** [comment]
@all-contributors add @JohnRomanski for bug
