### ISSUE TITLE
Users can update their profile

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#231]
https://www.sketch.com/s/9b590ee8-d7be-4054-a0a5-553fdcc5deaa

Now that we have users, they should be able to update their profile. 

When they update their profile, we should trigger events for this  (see #232 ) and save the updates to the PostGres db where we're storing user information

**Comment by TuringLovesDeathMetal** [comment]
Check out this Sketch file for how the settings bar will look (not sure if we want to implement this now, or after: https://github.com/lightdash/lightdash/issues/233)

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal I changed slightly the UX. Have a look at this video and let me know what you think 
https://www.loom.com/share/7f2379bd37de4f4996f81193aeec68b4

**Comment by TuringLovesDeathMetal** [comment]
siiiiiiick - looks great!
