### ISSUE TITLE
Update generic email pre-header for mobile email invites

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#2317]
### Description

Emails received on mobile devices show a pre-header. Currently this defaults to the generic template in HTML:
![IMG_5176](https://user-images.githubusercontent.com/14341285/172164883-52dad7bc-f138-4e49-9d55-e37a2cd1e08a.PNG)

Line in code in invite template:
https://github.com/lightdash/lightdash/blob/ca6966d746eb6b91dc4868d1b5241dcdd810464a/packages/backend/src/clients/EmailClient/templates/invite.html#L384

Suggested pre-header: `Your team is inviting you to join Lightdash`

Line in code in recovery password: 

https://github.com/lightdash/lightdash/blob/ca6966d746eb6b91dc4868d1b5241dcdd810464a/packages/backend/src/clients/EmailClient/templates/recoverPassword.html#L384

Suggested pre-header: `Reset your Lightdash password`

**Comment by ZeRego** [comment]
@hamzahc1 The invite email text already starts with `You've been invited to join Lightdash!` so I'm just going to delete the placeholder text.
