### ISSUE TITLE
Add a callout to make users aware of CLI tool

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2328]
I think the idea was that this sits more in the Explore area however I have been playing around and the issue I have with this is our callouts are not dismissible and we would be adding to cognitive load.  I would rather us rely onboarding,  marketing and Headway to tell people about the tool initially. Once we are working on 'dev mode', we can think about communicating this in the Explore area. 

For now, some suggestions for where the callout could live. ( I have no idea whether these are appropriate points in the users journey!)

**Adding a new project** (not onboarding!) 
![Screenshot 2022-06-06 at 16 24 15](https://user-images.githubusercontent.com/12776522/172192966-1d95e28a-0772-47a5-b6e7-93a1c740ddb4.png)

**Editing project settings**
![Screenshot 2022-06-06 at 16 24 04](https://user-images.githubusercontent.com/12776522/172192978-63a576bc-b52f-4276-ad24-3f39079baf23.png)

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this - I don't think it's as relevant anymore with the updates to onboarding (might be something to think about for developer workflows! but hopefully it's scattered around enough in our docs for people to discover it)
