### ISSUE TITLE
When the user has not defined any columns, display an error message that is visible from everywhere.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2331]
This is more a discussion for when @TuringLovesDeathMetal is back.
We've discussed loads of areas where we should communicate that you must have columns defined in order to view tables. If it as to be displayed in many places, its better that its just attached to the nav-bar somehow. It applies to the user where ever they are in the app. Something like this sketch ( copy and appearance all up for grabs)  makes more sense than 'redesigning' elements on every page to accommodate this message.

I don't think a toast is appropriate for this, as it can be dismissed. This should always be visible as the user wont be able to do anything at all if this action hasn't been carried out.

![Screenshot 2022-06-06 at 16 54 22](https://user-images.githubusercontent.com/12776522/172198797-26dc5dcb-1692-4259-bcf9-5667ccc07233.png)

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue - I think there's a bigger overhauil needed for onboarding and this will be a part of it! (I don't think we'll work on it as an isolated issue).
