### ISSUE TITLE
Apply dashboard filters to a subset of tiles

### ISSUE THREAD

**Issue by windmark** [lightdash/lightdash#2346]
### Description

A dashboard with multiple tiles should have user customisable filters that apply to a subset of the tiles, even when they originate from the same table/model. For example; a dashboard with tile A and B can have a filter on date applied only to tile A.

This is what this feature looks like in Looker.

![image](https://user-images.githubusercontent.com/3810163/172396990-5c86c0e0-c264-4de4-9f57-4d05324b245b.png)

### What problem does this solve?

A couple of use cases

- Separating metrics of different primary keys into separate tiles
- Showing different filtered metrics; ex. tile A shows events/s and tile B errors/s
- Tiles containing time series data with metrics of various time interval; ex. last hour and last week

**Comment by hamzahc1** [comment]
@all-contributors add @windmark for ideas

**Comment by TuringLovesDeathMetal** [comment]
related to #1617

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel here's an example of when I'd use this:

I have our KPI dashboard. In it, I have:

- Tile A: `date` vs. `total number of users over time`. This is built using the `users daily` table
- Tile B:  `user created date` vs. `total number of users created`. This is also built using the `users daily` table

I want to filter Tile B to have the total number of users created in the last 14 days. But, if I add a dashboard filter for `user created date in the last 14 days`, then Tile A gets the same filter applied. This makes Tile A look really weird because I'm only counting users that were created in the last 14 days, not _**all**_ users.

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel if I use cross-filtering, then I'd expect that by default, _**all**_ charts with the applicable filter would be filtered to this value, by default (so it would work exactly as it does now)

Then, I'd be able to edit the filter once it's been applied to pick & choose which tiles to apply it to.

So this would happen: 

- I select a field to cross-filter by
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/31848148/198067517-79da4100-6d59-481b-ac33-ff003368928a.png">
- It applies the filter on the top to all tiles that have that field
<img width="315" alt="image" src="https://user-images.githubusercontent.com/31848148/198067690-fd4a54bc-9aa4-4cbd-ba6f-3ca593a794b2.png">

- if I click on that filter, I can edit it just like any other filter
<img width="346" alt="image" src="https://user-images.githubusercontent.com/31848148/198068020-0a972102-3984-4a11-9033-0eb3577e10b8.png">
<img width="335" alt="image" src="https://user-images.githubusercontent.com/31848148/198068099-19ddddbe-b1b8-4cbe-ab4b-3a377d491c34.png">

**Comment by TuringLovesDeathMetal** [comment]
Two more things to maybe think about (in case you haven't already!):
1. When I edit existing filters, I want the option to pick which tiles to apply it to (I want access to this panel in `edit` as well as `create` filter flows)
2. If my table is joined to a table with the field I'm filtering on, then the filter should be applied, by default. (this is _**already**_ the behaviour that we have, but I just want to call it out). Here's an example of what I mean:

My table `Users` is joined to `Organizations`. 

You can see in `organizations` that I have a field called `is_7d_active_organization_latest`

If I build a chart using the `users` table (e.g. total number of users over time). Then, I apply a dashboard filter `is 7d active organization latest` = `Yes`

Then, I would expect my `total number of users over time` chart to have the filter applied (even though it's coming from the joined table, not the "original" table) 

^I don't think there are any design changes to make here! But I think that eventually, we'll probably want an option to "only include filters from the primary table" (i.e. you'd automatically un-tick the tiles which are being filtered on a joined dimension or metric)

**Comment by PriPatel** [comment]
@windmark 
Hello! We have been looking at solutions this week. Check out the prototype below! 
A simple first start is to add a 'tiles' tab or something similar where we show you all the tiles that the filter can be applied to. You have the option to select/deselect the tiles, but also pick different fields if you wish if say, you had charts [made from different models. ](https://github.com/lightdash/lightdash/issues/1617)

https://www.figma.com/proto/OHhTBtBHhE1EEiWSjl1Oso/permissions-flows?node-id=627%3A1412&scaling=scale-down-width&page-id=627%3A1411&starting-point-node-id=627%3A1412

Would love to hear your feedback before we start building! Thank you

**Comment by PriPatel** [comment]
This issue will tackled in tackled in this milestone:
https://github.com/lightdash/lightdash/milestone/59
