### ISSUE TITLE
The tooltip on stacked charts repeats the values multiple times 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#2350]
### Description

![Screenshot 2022-06-07 at 20 32 05](https://user-images.githubusercontent.com/14341285/172467981-97828884-704d-40bc-913e-d82c144d34ac.png)

### To Reproduce

Hover on values over a stacked chart 

### App Version 
v0.132.1

**Comment by rephus** [comment]
I can easily replicate this when grouping. I've been looking at the tooltip documentation, I don't think there is an easy fix for this. 
https://echarts.apache.org/en/option.html#tooltip

I can think of 2 solutions . 
- My preference would be to filter duplicated data in results (not sure if this could cause a bug somewhere else) 
- Explore the `formatter` echart option on tooltip that should allow us to customize the whole tooltip, but we will have redesign it manually by scratch. 

Any other ideas ? @nathaliabj @ZeRego @owlas

**Comment by ZeRego** [comment]
> My preference would be to filter duplicated data in results (not sure if this could cause a bug somewhere else)

So you'r saying what is causing this is duplicated series ?

**Comment by rephus** [comment]
> I don't think stacked charts used to act this way, this seems like a bug that was recently introduced thinking

Maybe by https://github.com/lightdash/lightdash/commit/ca6966d746eb6b91dc4868d1b5241dcdd810464a I can take a look

**Comment by rephus** [comment]
Confirmed, that was the issue, let me fix it
