### ISSUE TITLE
Analytics event: `saved_explore_created`

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#236]
When a user saves an explore, we trigger an event. 

This event should appear in `lightdash-raw-events.backend_events.saved_explore_created` 

**parameters:**
- user_id
- explore_link (this is the link that is unique for the explore)
- event_id
- timestamp
- name

**Comment by ZeRego** [comment]
we should keep our event names consistent `name_verb` 
What you think about `explore_saved` or start using *favourite* terminology instead of *saved* `favourite_explore_created`

**Comment by TuringLovesDeathMetal** [comment]
sounds great!

I'd prefer `explore_saved` over `favourite_explore_created` --> the reason being that I feel like you should be able to `favourite` explores that aren't yours (e.g. if you created an Explore, saved it, then put it in a shared folder, I might want to `favourite` that explore...so I feel like saving and favourite-ing will become distinct actions).

Let me know what you think!

**Comment by owlas** [comment]
Analytics naming is so hard haha.

It depends when the entity is here. 

My assumption was: an explore is something coming from the dbt project (base model + joined models, with metrics).

Wouldn't this be like `query_saved` `query_executed` `query_deleted`

**Comment by ZeRego** [comment]
But this also save the chart config right ? so `query` would also be misleading.

**Comment by owlas** [comment]
Oh really? I thought it was just the query. You might want to save many charts off one saved query right?

**Comment by ZeRego** [comment]
See this comment
https://github.com/lightdash/lightdash/issues/237#issuecomment-884007179

**Comment by owlas** [comment]
Thanks! Sorry, don't know how I missed that.

**Comment by TuringLovesDeathMetal** [comment]
> Oh really? I thought it was just the query. You might want to save many charts off one saved query right?

Ya, exactly. 

"Explore" in my mind is this: "an explore is something coming from the dbt project (base model + joined models, with metrics)."

^But that's just the 'raw' state of an explore. You can then _**add**_ things like charts, queries, etc. to these `raw` explores. 

Does that make sense?

**Comment by owlas** [comment]
Closing in favour of #237
