### ISSUE TITLE
Change margins of the divider in markdown tiles

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2363]
![Screenshot 2022-06-08 at 15 49 39](https://user-images.githubusercontent.com/12776522/172647332-d4324906-b321-416f-be82-f8845a3b769e.png)
 There should be equal spacing between the top and bottom of `This is a stacked bar chart`
 
 Looks a bit broken! Anything to just give the title a bit more breathing space at the bottom!

**Comment by JohnRomanski** [comment]
More visually jarring to me in this screenshot is the fact that the headline and horizontal rule seem to have a bigger left margin than the text underneath.
Is there any chance to make this user configurable? themeable?

**Comment by PriPatel** [comment]
Closing in favour #2410
