### ISSUE TITLE
Users can create saved explores

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#237]
Now that we have users, we should try implementing a feature that requires using `user_id` (because we don't just want to have users for the sake of tracking...)

This is also a really important, quite basic feature for the app. 

A user should be able to save an explore. When they save an explore, it appears in their `saved explores` page (see #233 )

Should create event for `saved_explore_created`: #236 

https://www.sketch.com/s/5f6d7184-0fd0-4bde-925f-0f2d043f103b

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal - Does a saved explore include things like: sorts on columns, chart settings OR just the queries?

**Comment by hamzahc1** [comment]
Note: Also think about error handling, what do we do if underlying model changes on a saved explore?

**Comment by TuringLovesDeathMetal** [comment]
@hamzahc1 

> Does a saved explore include things like: sorts on columns, chart settings OR just the queries?

Yes, it should be basically save the `state` that your explore is in the moment that you've saved it (so, I think this is same thing as our current `share link` functionality 🤔 )

> Note: Also think about error handling, what do we do if underlying model changes on a saved explore?

I actually wouldn't worry about this...(for now). I would say that > 90% of model changes will **not** change the overall 'logic' of the model. If anything, changes will fix _**broken logic**_, so it would be really hard to actually give `error handling` because we wouldn't know if the changes were fixing or breaking changes. 
Also, if you change a model, you'll tend to change values _**within**_ a model, and not the overall model structure (e.g. I might change the way I calculate `average time spent in the app` on my `users` table, but it's reeeeallllyyy unlikely that I'd change the fact that the table is one row per user_id)

I guess the one type of error handling we could do is telling the user that the data has changed since the Explore was saved? But I feel like this might do more harm than good...(e.g. how would you then go and figure out what has changed? What happens if multiple columns have changed multiple times since the Explore was saved? etc.)

**Comment by owlas** [comment]
@TuringLovesDeathMetal do you imagine we'll ever want to save queries and charts separately? 

Like if I save a query and then build multiple charts off it? Then those charts go in dashboards somewhere.

In that case, we'll store them separately on the backend (the UX will be the same as you described above though, appearing to just save and load together)

**Comment by ZeRego** [comment]
@owlas @TuringLovesDeathMetal How is the future implementation of dbt exposures going to affect this ?

**Comment by ZeRego** [comment]
> do you imagine we'll ever want to save queries and charts separately?

@owlas Each saved chart would still be linked to a saved query.

This sounds similar to Jira. When you want to build a chart/table in a Jira dashboard you need to select a saved query. 

When fetching the saved query we could get all the linked saved charts. We could apply the first in the list and provide a dropdown in the UI for people to switch between all the saved charts.

**Comment by TuringLovesDeathMetal** [comment]
> do you imagine we'll ever want to save queries and charts separately?


^I feel like I'm being really `traditional` in how I'm thinking about this. But basically, I would imagine no...but the conversation above is making me think that could be interesting to do, actually 🤔 

In my mind, we already "store" a data visualization by default: (we actually just select the first chart option when a user opens the `chart` button, no? So basically every "query" already has a chart associated to it...)

**Comment by TuringLovesDeathMetal** [comment]
I actually quite like the idea of having `saved queries` and then `saved charts that go with those queries` I Think I actually wrote something about this here a long time ago... #192 

Also, I feel like we're having this conversation in two places...can we try to finish talking about it here please ❤️ ? (sorry, I definitely commented on #236 as well!)

**Comment by TuringLovesDeathMetal** [comment]
Okay, so after the chat this morning, this is the thing that we want to be saving (tbd the name):
```
You've just run a query in Lightdash on either a model or an exposure. You've (maybe) changed some of the default plot configurations. You save the state of your screen (basically the query + plot configurations) and add it to your "Saved" space.
``` 

Eventually, your `saved` space will have these objects _**and**_ saved dashboards. You'll be able to have these saved things in a private space, or you'll be able to share them and add them to company spaces/folders/etc.
