### ISSUE TITLE
Create "one-click deployment" for Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#238]
Make a one-click deployment for Lightdash on Heroku so that it's super easy to self-host Lightdash. 

Something similar to this: https://github.com/posthog/posthog#quick-start

**Comment by ZeRego** [comment]
Heroku docs:
https://devcenter.heroku.com/articles/heroku-button

**Comment by owlas** [comment]
@TuringLovesDeathMetal @ZeRego possible to do render.com before heroku? Been a while since I used their build packs, I think we can get out a render example much faster

**Comment by ZeRego** [comment]
@owlas My only counter point is that Heroku is way more popular than Render.

**Comment by owlas** [comment]
.... starts reading the heroku docs ....
