### ISSUE TITLE
You should be able to change the field names in table charts. (through the config panel)

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2393]
**Feedback**

> You can’t change field headings for the table chart type, leading to some potentially ugly headings on a dashboard.

This could look and behave similarly to the input fields in the bar chart config panels when you're changing the value labels.
<img width="304" alt="Screenshot 2022-06-10 at 11 21 16" src="https://user-images.githubusercontent.com/12776522/173045501-eb5e69ed-af02-476f-833a-e55db42da752.png">

**Comment by TuringLovesDeathMetal** [comment]
This is great! Related to #2478 

I'd expect this to be hidden in a toggle or something. Most of the time, I wouldn't need to update the column names, I'd just want to toggle on/off the table names (#2478) so this feels like a LOT of actions that are almost overwhelming if I go to the `config` panel for table visualizations. Especially if I have a table with like 15 columns. 

Maybe living under `custom column headers` or something? Then you toggle it to open and a list of all of these input fields pops up

**Comment by 12ian34** [comment]
Nice work team! So glad to be able to use this in the demo to make it a bit prettier :)
