### ISSUE TITLE
Change window titles so its easier to navigate between many Lightdash tabs

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2395]
Feedback
> Window titles are all just “Lightdash” :( annoying when I have multiple open.

**Dashboards**
 Dashboards - Lightdash

**Specific Dashboard:**
[dashboard name] - Lightdash

**Explore**
Tables - Lightdash
SQL Runner - Lightdash

**Specific table**
[table name] - Lightdash

**Charts**
Saved charts - Lightdash

**Specific chart**
[chart name] - Lightdash

**Project settings**
Project Settings - Lightdash

**Comment by hamzahc1** [comment]
Do we even need the "Lightdash - " before each one? 

Maybe on the menu pages (i.e. dashboards, charts, etc). But when you're in a specific table, dashboard or chart I don't think it's necessary - just put the title in? (Since we have the ⚡ icon anyway :D)

**Comment by TuringLovesDeathMetal** [comment]
Let's add Lightdash at the end - more accessible for visually impaired users I think!

**Comment by ZeRego** [comment]
@yasmin-e we probably need https://www.npmjs.com/package/react-helmet or similar to set a different title for each page
