### ISSUE TITLE
Make numbers monospaced in results table + table viz

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2396]
### Description

Numbers are much harder to read in a column if they aren't monospaced

**Comment by ZeRego** [comment]
I’m in favour of changing all the results to a monospaced font, not just numbers.

**Comment by owlas** [comment]
Any benefit to strings being monospaced though? Readability would (I think?) be worse. But maybe the table would look very inconsistent using two fonts

**Comment by JohnRomanski** [comment]
> Numbers are much harder to read in a column if they aren't monospaced

This seems subjective to me. Are you referring to the result tables? What about the table visualization?

Could you allow this to be user-selectable? themeable? (We have people that spend a lot of time in Excel to get our branded fonts right for presentations.)

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel any preference for a monospaced font here?

**Comment by PriPatel** [comment]
@ZeRego 
My proposal from the UI redesign work from the last couple of months is to use the font `Inter`.
There is some info here about a tabular version:
https://rsms.me/inter/#features/tnum

What are your thoughts? Would this work?

**Comment by ZeRego** [comment]
@PriPatel would that be enabled for the entire website or just in specific places?

**Comment by PriPatel** [comment]
@ZeRego That would be enabled for all results/viz table including letters if needed. (and perhaps any other areas that require this).

**Comment by PriPatel** [comment]
Closing as we've made decisions on the font and [implemented this on pivot tables.](https://github.com/lightdash/lightdash/pull/5960#event-9568739560)  We will be using Inter ( it has a tabular version). We can open extra tickets to roll out this plus other frontend pivot table changes to other table types in the app.
