### ISSUE TITLE
Compatibility issue with dbt 1.0 and dbt-utils 0.7.5

### ISSUE THREAD

**Issue by Fszta** [lightdash/lightdash#2404]
## Description
We're using dbt cloud and [dbt-utils](https://github.com/dbt-labs/dbt-utils) (developed by dbt-labs) which require a dbt version < 1.1.0.
We get a `dbt parse` error, which is the **expected behavior** as lightdash's dbt connection seems to run on dbt 1.1.0. 
The issue is that our project is "compatible with dbt 1.0.0" as indicated on the connection page

<img width="320" alt="lightdash-dbt-connection" src="https://user-images.githubusercontent.com/36471574/173316053-e76ffb4c-ac25-49bc-ad13-5125f9a13683.png">

> NB: the link to dbt docs is dead : https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-1-0-0

## Suggestion
A message indicating that compatibility with any third-party dependency cannot be ensure as dbt connection is perform on dbt 1.1.0

## Output
```
DbtError: Failed to run "dbt parse" 07:51:08 Running with dbt=1.1.0 07:51:08 Start parsing. 
07:51:09 Encountered an error: Runtime Error Failed to read package: Runtime Error This version of dbt is not supported with the 'dbt_utils' package. 
Installed version of dbt: =1.1.0 Required version of dbt for 'dbt_utils': ['>=0.20.0', '<1.1.0']
Check for a different version of the 'dbt_utils' package, or run dbt again with --no-version-check
```

## Versions
* lightdash : latest (0.137.1)
* dbt: 1.0
* dbt-utils: 0.7.5

**Comment by owlas** [comment]
Hey @Fszta thanks so much for noticing this! We'll update guidance now
