### ISSUE TITLE
It's not obvious that I can right-click to cross-filter

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2411]
### Description

Adding dashboard level filters from a chart requires right-clicking but there's no indication whatsoever that it's possible.

**Comment by birkirbj** [comment]
I am used to a user of misc BITools, PowerBI, QlikSense and Tableau for example, to be able to left click on a chart and with that apply cross filtering.  Click on a bar in a barchart selects that context and applies filter.  It would be awesome to be able to click and drag over a few bars or on a linechart etc, or be able to click and hold control or command to be able select many .

**Comment by hamzahc1** [comment]
This is a good point - @owlas, it might make more sense to make the left click the primary action here? wdyt?

**Comment by owlas** [comment]
Definitely! This has caught me out a few times. Let's move the work to drag and select many bars to a new issue. I'll get on it

**Comment by birkirbj** [comment]
Awesome news, happy to test when available :D

**Comment by hamzahc1** [comment]
Should be closed by #2468

**Comment by owlas** [comment]
Closed by #2468 - you can try this out in release `0.149.0` @birkirbj

**Comment by birkirbj** [comment]
Just checked and it works
