### ISSUE TITLE
Add restrictions to the grouping field in chart layout options 

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2419]
### Description

Currently the group field in a chart can be any column and when selected, the y-axis is split into many series. To prepare for visual pivot tables, we should simplify and restrict grouping to the following rules:

* You can only group by a dimension, not by metrics or table calculations
* Metrics and table calculations will be grouped, but dimensions won't be

When grouping on a dimension than has `N` unique values, then each metric column should become `N` metric columns. 

In cartesian charts with a grouped dimension, the following is expected:
* When x (y) is a dimension and y (x) is a metric, expect `N` series all with same x-axis values but different y-axis values per group
* When x and y are both dimensions, expect a single series (group has no effect) (imagine a scatter plot with one colour)
* When x and y are both metrics, expect `N` series with different x-axis values and y-axis values per group (imagine a scatter plot with many colours)

**Comment by ZeRego** [comment]
@owlas 

> You can only group by a dimension, not by metrics or table calculations

What is our plan for existing saved charts pivoted by a metric/table calculation ? Should we have a migration script to remove the pivot value ? ( update value in column `pivot_dimensions` in table `saved_queries_versions`)

> When x and y are both metrics, expect N series with different x-axis values and y-axis values per group (imagine a scatter plot with many colours)

I don't understand how this is different from what we have right now.

Eg:
x axis: exampleX ( metric ) 
y axis: exampleY ( metric )
pivot: exampleW ( dimension )
 
Results
```javascript
[
 { exampleX: 1, exampleY: 2, exampleW: 'bananas'}
 { exampleX: 10, exampleY: 20, exampleW: 'apples'}
]
```

Series: 
- Bananas
- Apples

Pivoted data:
```javascript
[
 { exampleX: 1, exampleY.exampleW.bananas: 2}
 { exampleX: 10, exampleY.exampleW.apples: 20}
]
```

**Comment by owlas** [comment]
> What is our plan for existing saved charts pivoted by a metric/table calculation ? Should we have a migration script to remove the pivot value ? ( update value in column pivot_dimensions in table saved_queries_versions)

When rendering the chart we'd throw an error saying the config isn't valid

> I don't understand how this is different from what we have right now.

It's not different! I just wanted to make clear the behaviour of pivoting, we don't really have that written down anywhere

**Comment by ZeRego** [comment]
> When rendering the chart we'd throw an error saying the config isn't valid

@owlas We never show errors if the chart configuration is invalid, we just fallback to a valid configuration. So we can do the same thing here, if pivot field is not a dimension or no longer in the selected fields, remove the pivot configuration and recalculate the series.
