### ISSUE TITLE
Only admins can invite users with a role

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2428]
Only admins can invite users with a role

Currently an editor can invite a user with the role admin.

This paves the way for project level permissions. But is temporarily a little restrictive.

_Originally posted by @ZeRego in https://github.com/lightdash/lightdash/issues/2178#issuecomment-1155214267_

**Comment by ZeRego** [comment]
https://github.com/lightdash/lightdash/issues/2178#issuecomment-1155232483

**Comment by ZeRego** [comment]
I suggest users can only invite other users up to the role they have. 

Admin -> can invite admin, editor, viewer, member
Editor -> can invite editor, viewer, member
Viewer -> can invite Viewer, member
Member -> can invite member

**Comment by owlas** [comment]
Once we've implemented project permissions, these organization roles are all quite powerful (e.g. seeing all projects). I don't think Org Viewers should be able to create more Org Viewers.

**Comment by owlas** [comment]
Yep that sounds perfect!
