### ISSUE TITLE
Project name should be truncated

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2429]
### Description

Project name should have ellipsis when too bib.

### To Reproduce

![Screenshot 2022-06-14 at 15 37 57](https://user-images.githubusercontent.com/9117144/173605648-f9484bc8-a91d-41de-a368-2e3e1a3e268e.png)

### App Version

0.141.0

**Comment by ZeRego** [comment]
If we keep the same UI/elements, I don't think so.

**Comment by rephus** [comment]
We need to truncate the project selector on navbar too 
![image](https://user-images.githubusercontent.com/1983672/181194430-62daab58-feac-44fd-98e2-b1e623560ccd.png)
