### ISSUE TITLE
"new version available" label overflows

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#243]
<img width="435" alt="Screenshot 2021-07-14 at 14 47 57" src="https://user-images.githubusercontent.com/11660098/125633342-bf3c63b1-4a9d-4602-a22d-6cb2f8f271c9.png">

**Comment by rahul3v** [comment]
@owlas How can i see, The demo interface is locked with login credentials ....!
can you provide any test email !!

**Comment by owlas** [comment]
Yo @rahul3v the demo should be pre-filled with credentials. Can you share a screenshot?

**Comment by ZeRego** [comment]
If you seeded the db the login details are:
``` 
    email: 'demo@lightdash.com',
    password: 'demo_password!',
```
The login is only populated if in the `lightdash.yml` we have `mode: demo` 
We need to update the contribution docs with this.

**Comment by ZeRego** [comment]
For this ticket, a good fix is to change the `new version available` text into a closable tooltip.

**Comment by rahul3v** [comment]
well @owlas  now credentials are off, :)

@ZeRego we can put a notifier tag on available  as `New Update`  with a tooltip  with mini details on hover/click on it like
 `checkout v0.4.1 ` or  `v0.4.1 coming` or  `try v0.4.1`
