### ISSUE TITLE
Can manage roles at the project level

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2438]
### Description

**Database**

- [x] New table joining users to projects with a role

**UI**

- [x] New tab showing Project Access in the project settings page
- [x] Tab contains a list of project access

**Actions**
- [x] Can change users's role
- [x] Can remove user's from a project
- [x] Can add users, this is **only** existing organization members. You can't invite new users... yet

<img width="962" alt="Screenshot 2022-06-15 at 09 30 00" src="https://user-images.githubusercontent.com/11660098/173796427-ecfe5b34-7af3-4006-9a74-63bca88caa8d.png">

<img width="586" alt="Screenshot 2022-06-15 at 11 01 15" src="https://user-images.githubusercontent.com/11660098/173801041-720a3071-b29b-493e-baac-200e33c0470d.png">

**Biz logic**

- [ ] User is granted Project Admin when they create a project

**Authorization logic**

see #2437

**Comment by rephus** [comment]
@owlas I think we should , not only show the users with project permissions, but also show the users from the org that are admin / editors, whoc can view/edit all projects in the org (and maybe show a disabled select with an info tooltip explaining these permissions are from the org)

**Comment by ZeRego** [comment]
@rephus there is a separate ticket for that https://github.com/lightdash/lightdash/issues/2440

**Comment by yu-iskw** [comment]
@owlas Is there any plan to implement an API to manage project-level roles? As far as I am concerned, there is no API to manage project-level roles in the API documentation.

https://docs.lightdash.com/api/v1/#tag/project
