### ISSUE TITLE
You can invite users from the project access management page

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2441]
### Description

Clicking the Add user button on the project access Management page gives you the option to invite a user:

* Autocomplete with all emails of users in the org
* If the email doesn't exist, provide an action to invite the user + set their permissions
*

**Comment by rephus** [comment]
I think a way to implement this is to make a call to `invite` directly from project settings, and add a flag to `create rpoject access` to skip the second email .

My only question is how to set the right ORG permission for the invitation, should we make a popup saying something like "this user does not exist, do you want to invite it with role (select) ?`  /cc @PriPatel

**Comment by PriPatel** [comment]
Hmm @rephus  off the top of my head:
when you try to invite a user to a page in Notion, you see a dropdown with all the existing people
. Once the user has started to type in a name that doesnt exist, the UI changes. You can set the permission in the input field itself. 

<img width="494" alt="Screenshot 2022-06-22 at 12 46 04" src="https://user-images.githubusercontent.com/12776522/175021681-5a516ab9-6f7d-4aa6-bba3-22692bf78e81.png">


Sorry - maybe this is not helpful at all:( I can take a look next week for sure, but maybe the popup works for now?
