### ISSUE TITLE
Allow organization members to create projects

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2443]
### Description

All members should be able to create their own projects. This is an ability for everybody.

- Change permissions so anyone can create project
- Change error page to have CTA to create a project

**Comment by TuringLovesDeathMetal** [comment]
@owlas is this including people with `editor` and `viewer` access?

**Comment by ZeRego** [comment]
>  is this including people with editor and viewer access?
@TuringLovesDeathMetal Yes. https://docs.lightdash.com/references/roles/

**Comment by TuringLovesDeathMetal** [comment]
@owlas creating a project feels like it should be an admin setting 🤔 (or at least an editor setting)

It feels really "powerful" that a viewer can create a new project.
