### ISSUE TITLE
Send an email when a user gets new project access

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2444]
### Description

If project access is granted to a user, that user should receive an email notifying them with a link to the project.

**Comment by rephus** [comment]
@owlas @PriPatel do we have a template / copy for this email ?

**Comment by PriPatel** [comment]
<img width="1015" alt="Screenshot 2022-06-21 at 10 09 40" src="https://user-images.githubusercontent.com/12776522/174762911-9504131b-92b2-4a3f-927c-4157de21254f.png">
@rephus - sorry, I haven't done any design work for this feature. Ive made some rough edits in the browser for the above screenshot using the email template we already use for inviting people to Lightdash & when the user wants to reset their password.

My suggestion would be to say whether the user has been invited to view a project or collaborate on a project.  Open to feedback though, I havent had a proper chance to think about it!
