### ISSUE TITLE
Timezones not handled by date picker

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2457]
### Description

When you enter a date into the date-time picker, it snaps to a different timezone:

**Before**
<img width="182" alt="Screenshot 2022-06-16 at 15 26 31" src="https://user-images.githubusercontent.com/11660098/174092245-b89c7407-60b3-43e4-9f45-e6b5763239ef.png">

**after** (clicked millisecond field)

<img width="181" alt="Screenshot 2022-06-16 at 15 26 49" src="https://user-images.githubusercontent.com/11660098/174092324-1449b935-6b95-4b40-b40a-0d397f9ce7cf.png">

This happens for dates and date-times

**Comment by ZeRego** [comment]
@owlas Looks like we made a [fix](https://github.com/lightdash/lightdash/pull/2180) recently to convert the time to UTC on change but the component seems to be using the user timezone. 

Looks like the new [date-input2](https://blueprintjs.com/docs/#datetime2/date-input2) blueprintjs component handles better timezones and allows us to force the UTC timezone. Would that work ?

**Comment by owlas** [comment]
@ZeRego yep forcing UTC makes sense for now!
