### ISSUE TITLE
Open drill down view from explorer rows

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2460]
### Description

Adds the option to drill into metrics by clicking values in the explore table:

1. Click a metric value in the explore table
2. Opens a new modal
3. Modal runs a new query with all dimensions on the base table in the explore
4. Data is filtered to the dimensions on the row that was clicked + all filters applied to explore
5. User can close the modal to return to the original view6. 

Component should be re-usable, since later we'll allow clicking a chart segment to open the same view.

### Design

![drill](https://user-images.githubusercontent.com/11660098/174270659-102036ad-b5c5-4986-bb82-a78adbb05ce9.png)

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel how would you feel if we moved the filter option to left-click as well? 

So, a user hovers on a value - it gets underlined. You left-click on the value, and you get the options `filter`, `drill down`.
