### ISSUE TITLE
Option to exclude table names in table visualizations

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2478]
### Description

In table visualisations, the header can get very busy with the lengths of the names from the table.

You should be able to show/hide the table names from table visualizations using a toggle. 

This is related somewhat to https://github.com/lightdash/lightdash/issues/2393

I'd expect that if I added a custom label, it would override the selection I made in this toggle for that column label (e.g. I put `include table name` in this setting, but I added a custom label for `% of WAU`. I wouldn't expect that to become `Users % WAU` in the table viz)

**Comment by hamzahc1** [comment]
That makes sense - I think there might be a tidier way of showing it in that case than the current set-up 🤔 Maybe something on hover or click etc, or even written below it etc.
