### ISSUE TITLE
I'd like to download a csv containing even more results than the query

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2481]
### Description

If I set the query limit to 500, I'd like to have the option to download all results (not just 500) for further analysis

**Comment by Martin-Carlsson** [comment]
I was just about to create a feature request on this one.

I would say that this is a somewhat important feature since the end user often uses BI tools to get data out of a data warehouse so that they can use in their reports or preferred tools, like Excel.

**Comment by TuringLovesDeathMetal** [comment]
Closed in favour of #3571 (it's a duplicate, but the other one has more detail)
