### ISSUE TITLE
Option to show column totals for all rows (even outside the query limit)

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2483]
### Description

Currently the column totals show the total of the column returned by the query, but due to the LIMIT clause, we may not get the entire column. I'd like the option to see the column total without the limit.

**Comment by TuringLovesDeathMetal** [comment]
hmmm @owlas this one seems a bit weird to me. 

Like, I get it, but I also don't understand why if you're querying the data already, you wouldn't just return all of the data in the Lightdash UI. 

I feel like setting no limit (#1908) and then being able to set a row limit in your visualization could also solve this!

**Comment by TuringLovesDeathMetal** [comment]
closing this issue - it's already how we're calculating column totals now
