### ISSUE TITLE
Docs on using lightdash with dbt and local packages

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#249]
If a dbt project contains a `packages.yml` then the user needs to run `dbt deps` to populate their `dbt_modules` prior to launching lightdash.

The problem is that if the `packages.yml` contains paths to local package, the generated symlinks are absolute paths on the host system, not relative. So docker ignores them and all local packages are missing in lightdash.

**Comment by TuringLovesDeathMetal** [comment]
@owlas

**Comment by owlas** [comment]
Yep this is solved as we now run dbt deps for the user!
