### ISSUE TITLE
Show dimension types in the explore sidebar

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2493]
### Description

This would help people understand where we’ve inferred the wrong dimension type.

Blueprint has some reasonable icons for this

<img width="595" alt="Screenshot 2022-06-22 at 10 30 24" src="https://user-images.githubusercontent.com/11660098/175008214-78c65e29-f1f7-4e2e-9995-e505bae3e92e.png">
<img width="136" alt="Screenshot 2022-06-22 at 10 29 40" src="https://user-images.githubusercontent.com/11660098/175008225-0d71a077-fb61-4997-93e7-7b91105169bb.png">

<img width="208" alt="Screenshot 2022-06-22 at 10 29 20" src="https://user-images.githubusercontent.com/11660098/175008236-08b18d2f-efe1-4ac3-89a7-b4120030c033.png">

**Comment by hamzahc1** [comment]
Now that I see this here - this would be SO helpful.
