### ISSUE TITLE
Show all explorer compile errors locally before deploy

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2499]
### Description

When you run `lightdash compile` it will create `ExplorerError` objects and push them to Lightdash. 

We should show all the errors in the CLI.

- [x] When `lightdash compile` runs, if it runs into an error, then the compile continues, but we print an error message on the CLI. Can we just make this look like dbt's compile logs? 
    - [ ] Each explore is printed on the command line as it's processed
    - [x] You get a pass or fail on each compile line
    - [x] At the end of the compile, you get a summary of the test results (num fails, num passes)

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/31848148/196465249-b3c9ec79-9e80-4659-92c6-7afba06f3d23.png">
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/31848148/196465318-dd0efb35-fab0-4a9b-bb01-3e308773f401.png">

[console_output.log](https://github.com/lightdash/lightdash/files/9811789/console_output.log)

- [x] When `lightdash compile` is run before `lightdash deploy` or `lightdash preview`, this output is printed on the command line. 
- [x] If there are any failures in `lightdash compile` before running `lightdash deploy`, then, by default, we _**don't**_ deploy (the deploy fails and exits if there are any errors.)
- [x] There is an option in `lightdash deploy` to deploy, even with failures. E.g. `lightdash deploy --accept-failures` (I'm not sure if there's a better word/flag name for this) 
    - [x] If you run `lightdash deploy --accept failures`, then your project is deployed, even if there are failing explores. 
- [x] If there are any failures in `lightdash compile` before running `lightdash preview`, then by default, we _**do**_ build the preview anyways. 
    - [x] We print the failures/compilation process on the command line before the preview is shown. But, the preview is still created. 

### Other things to consider
- How does this affect Github actions/automation of these commands? (I think what I've described above makes it so that things will happen without input - i.e. we have defaults with flags instead of needing user input)

**Comment by rephus** [comment]
Do you mean checking the response type `const explores: (Explore | ExploreError)[]` in here https://github.com/lightdash/lightdash/blob/main/packages/cli/src/handlers/compile.ts#L51

and show an error if at least one of the explores is ExploreError ?
