### ISSUE TITLE
SQL generated for a dbt style metric with SQL expression adds table prefix in wrong place

### ISSUE THREAD

**Issue by gary-beautypie** [lightdash/lightdash#2502]
### Description

Generated SQL for a dbt style metric puts the column name in the wrong place if a SQL expression is used rather than just a column name

### To Reproduce

```
  - name: metric
    label: Test Metric
    model: ref('my_model')
    description: "Test metric"

    type: average
    sql: (COLUMN_1 + COLUMN_2) * COLUMN_3

    timestamp: DATE
    time_grains: [day]
```

Evaluates to:
```
AVG("my_model".(COLUMN_1 + COLUMN_2) * COLUMN_3) AS "my_model_metric"
```

### App Version

v0.136.0

**Comment by ZeRego** [comment]
Thanks for raising this @gary-beautypie. We might need to change or logic to not apply the table name if `sql` field was defined and has white spaces. So we would only apply the table name if the `sql` is a simple string.
