### ISSUE TITLE
Save chart button is enabled when there is nothing to save

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2506]
### To Reproduce

1. Go to tables page 
2. Click 'save chart'

![Screenshot 2022-06-22 at 16 52 28](https://user-images.githubusercontent.com/9117144/175076529-ef5e039b-2e57-490c-a31a-14ffb4c88d60.png)

### App Version

0.156.0

**Comment by muhsinkamil** [comment]
Hi @ZeRego I would like to work on this issue

**Comment by ZeRego** [comment]
@muhsinkamil awesome :) let us know if you need help settings up the dev environment. 
The button should be disabled if `isValidQuery` from `useExplorer`  is false.

**Comment by muhsinkamil** [comment]
I see, I thought to check activeFields.size, seems both the same :) 
Thank you !
