### ISSUE TITLE
Have the option to remove grid lines as well as the entire axes from charts 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#2508]
### Description

To remove whitespace around a chart - removing grid lines and the axes can focus more attention on the chart. This should be a chart config.

**Comment by hamzahc1** [comment]
See comment in Slack for reference: https://lightdash.slack.com/archives/C03EC7PCW8H/p1655909960620289

**Comment by ZeRego** [comment]
@hamzahc1 yes 👍

**Comment by TuringLovesDeathMetal** [comment]
This is related to #1850

**Comment by ZeRego** [comment]
@hamzahc1 by "removing the axes" you mean everything related to the axis right? not just the name. 
![show axis](https://user-images.githubusercontent.com/9117144/179189619-1fe674ba-83cd-4b57-9921-58ffd7f1cee5.gif)

**Comment by hamzahc1** [comment]
So the original idea for removing axes actually came from this post: https://lightdash.slack.com/archives/C03EC7PCW8H/p1655909960620289

**Comment by rephus** [comment]
So is this what we want @hamzahc1 ? I'm just removing the lines on axes using splitLine property . Do we need any other axes (like y-axis right) ?

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1983672/179539454-49338459-9893-46bf-930c-569ffce4a475.png">

**Comment by TuringLovesDeathMetal** [comment]
Yes to the defaults! x-axis disabled, y-axis enabled

**Comment by TuringLovesDeathMetal** [comment]
I think that what we want is:

- the numbers show.
- the line that the x-axis is on is hidden (so the horizontal line at the bottom with all the ticks would disappear, but the numbers remain)

This config would be called `show axis line` and `show ticks` and to get the result you want, you'd set them both to `false`

I think it's these two features in Echarts:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/31848148/179737095-d9f63f5d-737a-41eb-b69c-b6d6cbe30132.png">
<img width="816" alt="image" src="https://user-images.githubusercontent.com/31848148/179737141-3711eeaa-c59a-44d2-be24-caa4dab4ca42.png">
<img width="624" alt="image" src="https://user-images.githubusercontent.com/31848148/179737167-0499ae51-64bc-4021-a40c-8094fdeca1d7.png">

**Comment by TuringLovesDeathMetal** [comment]
By default, these would be:

x-axis: show line = True, show ticks = True
y-axis: show line = False, show ticks = False
