### ISSUE TITLE
In line charts, have the option to remove the "points" to produce a cleaner looking line chart

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#2509]
### Description

If you have a lot of information on a chart, having lots of points on the chart can make it look cluttered. Instead you should be able to see the vlaues on hover, but have the option to remove the points from the line chart visualisation.

**Comment by ZeRego** [comment]
Add '[smoothing](https://echarts.apache.org/en/option.html#series-line.smooth)' and '[symbol](https://echarts.apache.org/en/option.html#series-line.symbol)' config options.
Example: https://echarts.apache.org/examples/en/editor.html?c=area-pieces
