### ISSUE TITLE
Update the hierarchy + navigation in the settings space.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2517]
### Description

Right now, you get thrown into organization settings by default. With multiple projects, you really want to end up in the project settings by default. 

Navigating between project/organization/personal settings is quite confusing. This needs a bit of an overhaul.

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal I think this issue can be closed now as the design work for this has been done!
