### ISSUE TITLE
Error editing saved chart name

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2519]
### To Reproduce

![Jun-23-2022 14-22-12](https://user-images.githubusercontent.com/9117144/175309282-17aeee6c-dee7-4984-ac4c-c921e688412d.gif)

### App Version

0.157.2

**Comment by hamzahc1** [comment]
I wasn't able to replicate this 🤔

**Comment by ZeRego** [comment]
Happening on development env where we have request validation. We need to fix the openapi schema to mark the description property as optional.
