### ISSUE TITLE
I want to be able to duplicate my dashboard from within my dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2521]
### Description

I want to be able to duplicate my dashboard when I'm in my dashboard (not only when I'm on the list of dashboards).

### What problem does this solve?

Sometimes, before you duplicate a dashboard, you want to check to make sure that it's the right one. So I open it, then I want to be able to duplicate it from within the dashboard. 

I imagine that if I did this, it would redirect me into the newly duplicated dashboard.

**For design:** just not too sure where we'd put this button 🤔

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal - perfect!
There are some tickets to make the dashboard headers behave like saved chart headers. Youd be able to duplicate from the header.
<img width="1440" alt="Screenshot 2022-06-23 at 14 57 13" src="https://user-images.githubusercontent.com/12776522/175317127-8238e577-5d4f-4086-b969-4a121e6a3d0a.png">
The tickets are under the `Managing dashboards and saved charts` milestone!

**Comment by TuringLovesDeathMetal** [comment]
beautiful!

**Comment by TuringLovesDeathMetal** [comment]
This is a duplcate of #2072
