### ISSUE TITLE
regresion : we can no longer see what's the current project on project setttings

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#2530]
### Description
We can't see what's the current project on the new settings page 

![image](https://user-images.githubusercontent.com/1983672/175486989-d2c1be35-7d89-4c7e-b832-492b79d3eabb.png)

### To Reproduce

1. select a project
2. go to settings
3. you don't know which project is the current one

**Comment by TuringLovesDeathMetal** [comment]
related to #2517

**Comment by rephus** [comment]
Fixed
