### ISSUE TITLE
Plot lines-of-best-fit on charts

### ISSUE THREAD

**Issue by TiFaBl** [lightdash/lightdash#2533]
### Description

Provide the possibility to interface with existing python or R libraries to extend the plotting capabilities.

### What problem does this solve?

Our specific problem is that we need to create fitting curves and plot them in the graphs with the data points. As an example:
![image](https://user-images.githubusercontent.com/38563080/175499327-6f21bcab-affa-4087-9ed8-805de29ff18d.png)

In general, there are many plots available in libraries (or other tools like PowerBI/Excel) which are currently not possible in Lightdash. Having the possibility to create an additional layer in the Graph using external libraries could close that gap.

**Comment by owlas** [comment]
This is an interesting idea @TiFaBl - from excel/sheets I'm also used to have some basic curve fitting available!

**Comment by owlas** [comment]
@all-contributors add @TiFaBl for ideas

**Comment by TuringLovesDeathMetal** [comment]
Related to #2728

**Comment by owlas** [comment]
@TuringLovesDeathMetal shall we close one? Unless @TiFaBl you'd like this issue to specifically be about using external plotting libraries. Although in that case I'm not sure it's on the near-term roadmap. How would you imagine that working?

**Comment by TuringLovesDeathMetal** [comment]
Closed in favour of #2728
