### ISSUE TITLE
Add `lightdash validate`

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2535]
### Description

Add a new command `lightdash validate` that will compile the project and determine if any existing saved charts would be broken (because they reference dimensions/metrics that are missing in the newly compiled representation)

I imagine this would be a backend job and an endpoint like `POST /api/v1/projects/{projectUuid}/validate` and post a list of explores. 

The user should get a very friendly looking output that makes it easy to see what would break, why it would break, and a URL to that resource in the Lightdash project.

**Comment by TuringLovesDeathMetal** [comment]
I wonder if by default, we could run lightdash validate before lightdash deploy (and if it errors, we exit).

Then there could be some way to only do deploy without validating (if you really wanted to) like `lightdash deploy --validate false`

**Comment by TuringLovesDeathMetal** [comment]
I wonder if by default, we could run lightdash validate before lightdash deploy (and if it errors, we exit).

Then there could be some way to only do deploy without validating (if you really wanted to) like `lightdash deploy --validate false`

**Comment by hamzahc1** [comment]
Shouldn't this be complete now @TuringLovesDeathMetal ?
