### ISSUE TITLE
4. Create a GitHub action for lightdash ci/cd for `lightdash deploy` on push to connected project branch

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2537]
### Description

GitHub Actions for... (these will probably live in another repo):

- [ ] compile project on push to any branch
- [ ] deploy project on push to `main`

This should be an app that can be installed. 

We'll need:
- [ ] instructions on how to add this GitHub Action to your instance
- [ ] a new button / link in the `project connection settings` page that tells you to `automatically update Lightdash` ([source](https://miro.com/app/board/uXjVPc-3lVU=/))
<img width="878" alt="image" src="https://user-images.githubusercontent.com/31848148/189686353-31bfaccf-f465-439d-86b4-e97c9bf84eb8.png">

**Comment by rephus** [comment]
Why does it need to run in another repo ?

**Comment by rephus** [comment]
I made a "working" github action that will deploy my project from my dbt repo.  https://github.com/rephus/dbt_solar_panels/blob/master/.github/workflows/cd.yml . There are a few details left to implement about oauth, but it should work on existing valid warehouses (I'll confirm once we know exactly what we want) 

Config files and credentials are using Github secrets like `config: ${{ secrets.CLI_CONFIG }}  ` (I think we want to keep this) 

How far do we want to go with this implementation ? 

- It looks good for now , people will copy paste this and we'll keep iterating in the future.  
- we can move some logic (not dependencies) into a `bash` script we can `wget` and run 
- Create an official `github action` on the marketplace
- Other... 

Where is the documentation for this going to be ? maybe on a brand new repo, next to the script to copypaste ?

**Comment by TuringLovesDeathMetal** [comment]
> Where is the documentation for this going to be ? maybe on a brand new repo, next to the script to copypaste ?

We should have documentation for "what it is" and "how it works" in docs.lightdash.com, but this should redirect you to the repo readme (if this is going to be a repo that they need to clone/do something with). 

I don't 100% understand how this is going to work so I'd need to get a better idea before being sure we shouldn't just include all the instructions in docs.lightdash.com (and just redirect you to those instructions from the readme in the repo)

**Comment by TuringLovesDeathMetal** [comment]
Will it install the CLI each time? Or just install it once on your repo? 

But yes, can we disable tracking on the installation, but "just" for the GitHub actions?

**Comment by rephus** [comment]
right now, it will install the CLI each time, unless it is cached by github somehow, because we don't have any base image with the CLI already installed (yet) 

I can easily disable analytics just for github actions :+1:
