### ISSUE TITLE
cli reports missing columns even though they are there

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2538]
### Description

Running `lightdash preview` with snowflake in a dbt project gives:

```
 lightdash preview
Column "uuid" from model "stg_amplitude__events" does not exist.
 "stg_amplitude__events.uuid" was not found in your target warehouse at dev.dbt_pedram.stg_amplitude__events. Try rerunning dbt to update your warehouse.
```

even though this works:

```
select 
uuid 
from dev.dbt_pedram.stg_amplitude__events
limit 1
```

AND the same project compiles when hitting "refresh dbt" in the UI. So it's something different about the compile process with the CLI. 

We recently merged a PR to automatically use string dimensions when we can't find the column. So I see 2 problems:
* Why can't lightdash find the column?
* And if we can't find the column, why is it throwing an error instead of assuming a string type dimension?

**Comment by rephus** [comment]
Could this be related with my `lightdash generate` issue I got ? Does it work after `lightdash dbt run` ?
