### ISSUE TITLE
Lightdash fails to launch when you have dbt_utils in your packages.yml file

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#254]
![image](https://user-images.githubusercontent.com/31848148/126521425-89b48916-eede-422f-9340-bbdb78b213a8.png)

In the `lightdas/lightdash-analytics` project, I use the `dbt_utils` package. This package requires dbt to be between versions: ['>=0.18.0', '<0.20.0']

The way I get around this on my local machine + on dbt Cloud is by running the command `--no-version-check` whenever I run dbt. i.e.:
```
dbt run -m --no-version-check
```

When I try to use Lightdash with this dbt project, it fails the compile at the `dbt_utils` package in my project.

^The weird thing about this is that the `tap-github` project also uses `dbt_utils` and **_doesn't_** have this failure 🤔 so I'm not sure what's happening here...

**Comment by owlas** [comment]
Hot dang! This is as annoying one, you need bump the version of `dbt_utils` used in `packages.yml`

Latest version is `0.7.0` : https://github.com/dbt-labs/dbt-utils

Is the tap using an earlier version?

**Comment by TuringLovesDeathMetal** [comment]
https://github.com/lightdash/tap-github-dbt/blob/master/packages.yml

looks like it!

**Comment by TuringLovesDeathMetal** [comment]
works now!!! 🚀
