### ISSUE TITLE
I keep thinking that the totals are part of my results table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2540]
I keep scrolling to the bottom and thinking that the totals are part of my results table. 

Suggestion: make the line between teh totals + the rest of hte results table bolder

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/31848148/175508232-acf7e958-40e3-408c-a3ee-703c94b38420.png">

**Comment by ZeRego** [comment]
![Screenshot 2022-06-28 at 14 36 51](https://user-images.githubusercontent.com/9117144/176192491-6255f656-9e8f-45c7-ae06-b8f60094dcff.png)

Having a darker border just there looks bad :/

**Comment by TuringLovesDeathMetal** [comment]
> Having a darker border there looks bad

Really? @ZeRego I find it looks totally fine! 

Bold values might be a bit confusing...it's not like totals are particularly more important than the values themselves... 🤔

**Comment by PriPatel** [comment]
Totals tend to be bold in other applications when displayed. I agree with @ZeRego that the black line doesn't feel consistent with everything else, however, the white background makes a difference to me. 

I was thinking that eventually you should be able to pick a dropdown on the 'total' number and change it to average or max/min so bolder values makes sense to me!
