### ISSUE TITLE
Auto-generated doc blocks confirmation in the CLI tool are confusing/look broken

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2548]
### Description

I'd expect to be able to `add all` or `add some` in the doc blocks confirmation. 

Right now, I have the option to add some, but it doesn't actually let me? I have to just add all of them 🤔 it's confusing

https://www.loom.com/share/0d354e4cc6dc4a60b286b22c32fdfd73

### To Reproduce

- create some doc blocks
- run `lightdash dbt run -s model` 
- get the request asking if you want to update your doc blocks. 

What I'd love the behaviour to be like:
- I create some doc blocks for `user_id` and `company_id` + do `lightdash dbt run -s company` and get this command. 
- the command says: 
```
📄 Found existing doc files for columns in the following models:
users:
  - user_id
  - company_id

companies:
  - user_id
  - company_id

Would you like to update these descriptions with the doc files (y/N)?
```

**Comment by owlas** [comment]
Hey @TuringLovesDeathMetal what does this bit mean?

>^It would be neat if it also added to the existing descriptions (if there was an existing one) instead of fully replacing it. But that's not totally required :)

**Comment by TuringLovesDeathMetal** [comment]
nevermind! I take it back - I don't think that it's actually useful

**Comment by TuringLovesDeathMetal** [comment]
I've just done `lightdash generate` again today. 

I realize that we're adding docs _**on the go**_ (i.e. as each model compiles) rather than compiling all the models, then asking about the docs at the end. 

So the format I've suggested above won't work unless we do `compile all things`, then `add all docs` as two steps. 

^This feels nicer to me since I can then go away and do other things while my models are compiling (it doesn't keep stopping and needing actions from me as it goes). But if this is really hard to do, then let's just keep it as-is and then we can think of a different format of presenting the doc blocks

**Comment by TuringLovesDeathMetal** [comment]
Some more feedback from using it this morning: 

Right now, it's really unclear which models you're getting suggested to add doc blocks to. 

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/31848148/175883714-8695f553-76bb-4eaa-8c30-201be80cbbec.png">

E.g. on this last line: am I adding descriptions to `lightdash_cloud_interest_signups_pii`? (the answer: no). There's no indication of what model I'm being asked to add descriptions to.

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/31848148/175885192-3cebcabd-8f36-43de-a67a-ca68b987a0f1.png">
