### ISSUE TITLE
`lightdash compile` is not recognizing changes to my `.yml` files

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2563]
### Description

When I ran `lightdash compile`, I got an error saying `this column doesn't exist`. Fair enough. 

I went to the dbt .yml file for the model, removed the column from the .yml file, and re-ran `lightdash compile`

It's still giving me the same error, even though the column is no longer in the `.yml` file. 

I'd expect `lightdash compile` to notice these changes.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/31848148/175890777-41b79b75-668b-4643-a245-0f63b26b6e83.png">

**Comment by TuringLovesDeathMetal** [comment]
Update: to get `lightdash compile` to work, I had to run `dbt compile`, then run `lightdash compile`

**Comment by ZeRego** [comment]
> or giving the option to run dbt compile first if you run lightdash compile? ("would you like to do dbt compile (Y/N)?"))

I like this. Brings awareness so they know why is taking so long and they can skip it if they want to. We can even have the option `--skip-dbt-compile` for cli purposes

**Comment by owlas** [comment]
Yeah sounds good, will the user always know when they should dbt compile?

**Comment by TuringLovesDeathMetal** [comment]
I definitely wouldn't...

More specifically, I can't think of an example where I'd run `lightdash compile` without needing to run `dbt compile` first 🤔 

Maybe I'm missing something obvious though?

**Comment by owlas** [comment]
Since we run `lightdash compile` before `lightdash deploy` and `lightdash preview`

would we also be happy for `dbt compile` to trigger before all these actions above? Just trying to figure out the best UX!
