### ISSUE TITLE
Sharing a link to a Lightdash explore in Slack is blocked by Slack

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2570]
### Description

I tried to share a link to a chart in Lightdash, but when I tried to send it in Slack, it says:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/31848148/175917271-26fcacf8-4b7f-45da-9269-4d72de03775e.png">

https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/tables/organization_events?create_saved_chart_version=%7B%22uuid%22%3A%22509d77ca-de0f-408e-9997-4dbc504cf89f%22%2C%22projectUuid%22%3A%2221eef0b9-5bae-40f3-851e-9554588e71a6%22%2C%22name%22%3A%22Top+20+Organizations+%22%2C%22description%22%3Anull%2C%22tableName%22%3A%22organization_events%22%2C%22updatedAt%22%3A%222022-06-27T08%3A57%3A02.757Z%22%2C%22updatedByUser%22%3A%7B%22userUuid%22%3A%227f902d08-0f93-4c61-9161-9c838ec27d04%22%2C%22firstName%22%3A%22Jose%22%2C%22lastName%22%3A%22Rego%22%7D%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22organizations_query_executed_num_total%22%2C%22organizations_organization_name%22%5D%2C%22metrics%22%3A%5B%22organization_events_count_unique_event_names%22%5D%2C%22filters%22%3A%7B%22dimensions%22%3A%7B%22id%22%3A%229925a7fe-8347-48ee-8355-118c966e8c78%22%2C%22and%22%3A%5B%7B%22id%22%3A%22a80823fc-7645-4b3f-9274-2defc0739ff1%22%2C%22target%22%3A%7B%22fieldId%22%3A%22organization_events_event%22%7D%2C%22values%22%3A%5B%22lightdash_server%22%5D%2C%22operator%22%3A%22include%22%7D%2C%7B%22id%22%3A%22c66e3b6a-76f7-4d87-8021-282605880cc8%22%2C%22target%22%3A%7B%22fieldId%22%3A%22organizations_organization_name%22%7D%2C%22values%22%3A%5B%22Lightdash%22%5D%2C%22operator%22%3A%22notEquals%22%7D%5D%7D%7D%2C%22sorts%22%3A%5B%5D%2C%22limit%22%3A20%2C%22tableCalculations%22%3A%5B%7B%22name%22%3A%22top_twenty%22%2C%22displayName%22%3A%22top+twenty%22%2C%22sql%22%3A%22IF%28ROW_NUMBER%28%29+OVER%28ORDER+BY+%24%7Borganizations.query_executed_num_total%7D+DESC%29+%3E+20%2C+0%2C+1%29%22%7D%5D%2C%22additionalMetrics%22%3A%5B%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22organizations_query_executed_num_total%22%2C%22yField%22%3A%5B%22organization_events_count_unique_event_names%22%5D%2C%22flipAxes%22%3Afalse%7D%2C%22eChartsConfig%22%3A%7B%22xAxis%22%3Anull%2C%22yAxis%22%3Anull%2C%22series%22%3A%5B%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22AnyMove%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22PublicSq%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22ServiceTrade%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Manual.co%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Thyme+to+Shine+Market%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Talea+Pflege+GmbH%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Mockingbird%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22MixMax%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Travbula+AS%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22inocon+solutions+GmbH%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Nomad+Homes%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22GravityData%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Tesla%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22ashby%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Atoms%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22deepskydata+ApS%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Galiot%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22X-Equipment%22%7D%5D%7D%7D%7D%2C%7B%22type%22%3A%22scatter%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22organizations_query_executed_num_total%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22organization_events_count_unique_event_names%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22organizations_organization_name%22%2C%22value%22%3A%22Summer%22%7D%5D%7D%7D%7D%5D%7D%7D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22organizations_query_executed_num_total%22%2C%22organizations_organization_name%22%2C%22organization_events_count_unique_event_names%22%2C%22top_twenty%22%5D%7D%2C%22organizationUuid%22%3A%22d413dcea-4c8f-46b6-baa5-23885490e08b%22%2C%22pivotConfig%22%3A%7B%22columns%22%3A%5B%22organizations_organization_name%22%5D%7D%7D

**Comment by owlas** [comment]
@ZeRego what do you think about generating a uuid for each query, then when you request a share link, it creates a short link and stores the state in the backend?

**Comment by ZeRego** [comment]
@owlas 👍 yup, something like that.
Closing this ticket in favour of #60
