### ISSUE TITLE
Add standard event properties

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#258]
We capture events on the backend and frontend. We should differentiate between them. A good way would be using event properties:

`track(anon_id, event_name, {'app': 'frontend'})`  - for example

**Comment by TuringLovesDeathMetal** [comment]
@owlas only event properties that are missing from the current payload are:
- `project_id` : the unique ID for the project where the event was triggered (can be NULL if the user has not created a project yet? 🤔 )
- `organization_id`: unique ID for the organization the user is a part of when the event is triggered
- `page_id` : unique ID for the page where the event is triggered (either page in the app or page on the website)
- `page_name`: human-readable name of the page where the event is triggered.

**Comment by ZeRego** [comment]
This work seems to be related to #344

**Comment by owlas** [comment]
Closed with #359
