### ISSUE TITLE
Have Google SSO as a way to login to the Lightdash CLI

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2584]
### Description

Sign in via Google SSO (not username + password). Otherwise, if the org has Google SSO enabled, they have to create a new user in their project for them to be able to use teh CLI tool.

**Comment by ZeRego** [comment]
We can already authenticate using a personal access token instead of the email/password. https://github.com/lightdash/lightdash/issues/2495

Just need to update docs to explain how to do this.
