### ISSUE TITLE
Update snowflake timestamp/date output format

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2589]
### Description

To fix https://github.com/lightdash/lightdash/issues/2475 we introduced a workaround which parses all snowflake date objects.

Snowflake recommends altering the timestamp/dates format at the session level.

You can read the discussion in this [thread](https://github.com/snowflakedb/snowflake-connector-nodejs/issues/317)

Solution: 
1. Find a format that matches JS date. `value.toJSON(); // should return "2017-02-11T03:00:00.000Z"`
2. after creating a snowflake connection, run a query to update the timestamp/date output format
3. remove workaround

### What problem does this solve?

Remove tech debt as we no longer need a workaround.
Improve performance since we don't need need to loop over all the data.

**Comment by TuringLovesDeathMetal** [comment]
I'm gonna close this issue...it's been 1.5 years without any activity, so I think that it's probably not worth keeping it in the backlog!
