### ISSUE TITLE
Setting min and max values for y axis on a chart doesn't always work.

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2592]
### Description

Setting min and max values for y axis on a chart didn't work. Creating on behalf of a user.

### To Reproduce

I cannot seem to reproduce this but it has 100% happened to me personally before as well.

### App Version

0.165.2

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this until we have an example of this happening. Otherwise, it's sort of a hard bug to fix!
