### ISSUE TITLE
I would like a Funnel chart type

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2594]
### Description

- I would like to have a Funnel chart type available in the chart builder. 

![image](https://github.com/lightdash/lightdash/assets/31848148/3506a837-985c-46c6-9c66-e9d9b9f91e14)

### Acceptance criteria

- [ ] There is an option to select a `funnel chart` type in the chart type selector
- [ ] There are two tabs: `layout` and `series`
- [ ] Like with a pie chart, in the `layout` tab, there is only the option to select one group and one metric in the configuration (unlike the pie chart, there's no option to `add group`)
<img width="412" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/a10b8ae3-f6d5-4cdd-8275-ab01ad045dce">

- [ ] Like a pie chart, in the `series` tab, you have the options to show/hide the labels, and to adjust the colour + label names in the chart. (there is no  `show percentage` and `show value` tickboxes in this first version)
<img width="400" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/50971dfa-03e8-4b2a-a58e-4c65578976f9">

- [ ] I'm able to build a funnel chart using a single dimension (of any type) and a single metric or table calculation that are of numeric type
- [ ] The ordering in my funnel chart matches the ordering that I have in my results table. 
- [ ] My funnel chart can increase in size as well as decrease between steps (i.e. we don't care to check if it's actually a "correct" funnel, you can build whatever you want here). 

- [ ] ?? Should i be able to manually re-order the series in the chart config? Maybe we leave that out for now? (I'm just worried how it will affect the percent of previous/percent of total calculations that we'll build later on...)

### Out of scope in this ticket

- [ ] adding % of first step as a value label
- [ ] adding % change from previous to each step

**Comment by 12ian34** [comment]
Still relevant, just requested by a prospect

**Comment by 12ian34** [comment]
definitely not stale - a paying customer, and a couple of prospects are very keen for this feature

**Comment by 12ian34** [comment]
Another prospect has requested this

**Comment by 12ian34** [comment]
Indeed I believe most of the requests were related to product analytics, or marketing campaigns etc..

And yep, makes sense regarding this not just being a simple chart type.

**Comment by Martin-Carlsson** [comment]
I would also request this
