### ISSUE TITLE
Mixed chart type is disabled until you've picked two y-axis values

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2595]
The mixed chart type should appear in the list of chart types but disabled until the user picks two y-axis values. 

There should be a tooltip saying "You can only use mixed charts with two or more series on the y-axis"

**Comment by PriPatel** [comment]
In the product itself , we could show the mixed chart type and keep it disabled until the user pics two y-axis values (and show a tooltip telling them why its disabled) . but then, what would the default config be? @TuringLovesDeathMetal

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel 
> we could show the mixed chart type and keep it disabled until the user pics two y-axis values (and show a tooltip telling them why its disabled)

^This also sounds like a great idea! I'd much prefer for it to be obvious _**in**_ the product instead of needing you to go in the docs

**Comment by 12ian34** [comment]
New title makes more sense thanks @TuringLovesDeathMetal
