### ISSUE TITLE
Update help drop-down to include link to Slack community and create bug report 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#2597]
### Description

![Screenshot 2022-06-29 at 10 12 08](https://user-images.githubusercontent.com/14341285/176399463-7b925c19-5253-4501-aa5b-499fadd57f0f.png)

- [ ] The drop-down for "Join the discussion" should instead read: "Join Slack community" 
- [ ] Link for Join Slack community should be updated to: https://join.slack.com/t/lightdash-community/shared_invite/zt-16q953ork-NZr1qdEqxSwB17E2ckUe7A 
- [ ] We should add another drop-down which links to open a GitHub issue if they have a bug or feature request

**Comment by muhsinkamil** [comment]
@hamzahc1 Can I take up this. 
2. Unfortunately Slack logo is not available :( 
https://blueprintjs.com/docs/#icons

**Comment by hamzahc1** [comment]
@muhsinkamil - I updated the ticket to remove the requirement for the Slack logo

- Title for Github option: Feedback on Lightdash
- Description:  Submit a feature request or bug report in our GitHub repo
- Link: https://github.com/lightdash/lightdash/issues/new/choose
