### ISSUE TITLE
ilogical behaviour when using filters with number fields  (greater/less then)

### ISSUE THREAD

**Issue by rahul3v** [lightdash/lightdash#260]
try to experiment with number fields on filters, 
like add or delete new filters,  test few greater/less than  options then  perform add or delete

same will happen if use date related fields as well 

![illogical_behaviour](https://user-images.githubusercontent.com/24385409/126820946-ad6f1403-2ef3-4d63-9bac-c001711e6bee.gif)

You see every time something very unusual results on UI , nothing very specifx

**Comment by owlas** [comment]
Confirm this is a bug with all filters types
