### ISSUE TITLE
Improve CLI spinners and logging

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2606]
The `ora` lib doesn't allow multiple spinners or logging anything else while the spinner is running.  I suggest we change lib to `https://github.com/jcarpanelli/spinnies` or `https://www.npmjs.com/package/listr`.

_Originally posted by @ZeRego in https://github.com/lightdash/lightdash/pull/2600#discussion_r911960212_

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - it's been more than 2 years since there has been any acitivty on it
