### ISSUE TITLE
Support Bigquery oauth method for authenticating with the cli

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2614]
### Description

If you use a bigquery dbt profile with `type: oauth` you get this message from the CLI

<img width="638" alt="Screenshot 2022-07-04 at 09 17 15" src="https://user-images.githubusercontent.com/11660098/177116008-221008cd-7538-47c8-998b-39790f3b1794.png">

### Implementation

`type: oauth` in dbt just means the user has logged in with `gcloud login` which creates a local keyfile and sets `APPLICATION_DEFAULT_CREDENTIALS` (so it's still keyfile based). So we don't actually need to implement an oauth flow. https://docs.getdbt.com/reference/warehouse-profiles/bigquery-profile#oauth-via-gcloud

The node bigquery adapter should pick up application default credentials automatically. I think we'll just need to update the warehouse adapter and the types for `CreateBigqueryWarehouseClient`

### What problem does this solve?

Users that authenticate via `gcloud` for dbt when they try out the CLI

**Comment by rephus** [comment]
in  profiles.yml , if we replace `method: oauth` with `method: service-account` it works with the right credentials . 

![image](https://user-images.githubusercontent.com/1983672/178291068-5459a841-ea76-4088-a233-c0f042f3ca32.png)

![image](https://user-images.githubusercontent.com/1983672/178291037-b05a5507-fce7-4c0b-8777-0368f8ba870c.png)

I can make a change to support `oauth`
