### ISSUE TITLE
Add onboarding docs in-app 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2618]
### Description

When you first login to Lightdash, we should suggest that you check out the onboarding tutorials. 

### What problem does this solve?

Users won't know that we have onboarding tutorials unless we tell them about it. 

https://docs.lightdash.com/get-started/intro

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal
![Screenshot 2022-07-07 at 12 28 10](https://user-images.githubusercontent.com/12776522/177763217-296e4769-d931-4ea2-903b-140c57ccff1d.png)
 I feel like this is the last page in the onboarding state. Are you thinking we should tell them about docs here or elsewhere in the connect a project phase? We already link them to several docs while they're connecting a project. 
 
 Or do you mean here before they even start?
![Screenshot 2022-07-07 at 12 31 29](https://user-images.githubusercontent.com/12776522/177763653-6e8788d3-24a3-4b1d-bab1-38a2b9b921ea.png)


Thanks!

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel I think there are two flows:

1. if you're onboarding into a totally new project, then I'd almost want to link them to the docs _**before**_ the `have you added columns to your .yml` screen. Like, `create a user + org` --> `tell them to go to the onboarding docs` --> when the onboarding docs tell you to come back to the app, you'd click `next` and keep going through the flow
2. If you're onboarding into an _**existing project**_, but you're a _**new user**_ then we show you that `run your first query` onboarding state, right? If yes, then I'd expect a link to the docs in there. <-- this is great, because if you're onboarding into a totally new project and you ignored the docs the first time around, then you see them again 🙃 

does that make sense? 

I'm really keen to test this with some new users though before we start chucking the docs in everywhere - if the onboarding with the CLI doesn't work, then we shouldn't be shoving it in people's faces 😅

**Comment by PriPatel** [comment]
Ahh ok understood, I'll hold this piece of work off till then!
