### ISSUE TITLE
export from Look ML feature

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#262]
could use something like spectacles or otherwise, essentially converting Look ML models to required code in dbt

**Comment by owlas** [comment]
Oh @djayatillake this is great idea!

So we already have `dbt2looker` https://github.com/lightdash/dbt2looker which generates `lookml` from lightdash config in dbt.

But you're thinking of the reverse where you could generate the lightdash config for a dbt model that's equivalent to a view in lookml?

**Comment by djayatillake** [comment]
Exactly, the reverse. Will  allow for faster migrations from Looker.

**Comment by TuringLovesDeathMetal** [comment]
We should still do this - but I think this will become a priority when we're focused on growth and looking for growth levers to pull :)

**Comment by TuringLovesDeathMetal** [comment]
Closing as we have `dbt to lookml` and `lookml to dbt`
