### ISSUE TITLE
Can't onboard and unsure why

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2621]
### Description

When I onboard to Lightdash I got the following message when compiling my project. I don't know if this is from my database, GitHub connection, or from Lightdash auth.

![Screen Shot 2022-07-04 at 11 57 58 AM](https://user-images.githubusercontent.com/11660098/177188997-6e075fc1-44e9-456e-9489-60c7053ece35.png)

**Comment by rephus** [comment]
@owlas How can I replicate this ?

**Comment by owlas** [comment]
Ah great question. This is a generic error message in a few places. In this case it was from the data warehouse but it looks like it's a lightdash auth error.

I was thinking to grep for this error in the project and insert more helpful messages (unless that would leak auth implementation)

**Comment by owlas** [comment]
I can't think why this happened. I wasn't able to capture enough information to determine the root cause. Closing
