### ISSUE TITLE
Show data quality statistics

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#263]
use of this package to show things like data freshness, anomalies in row counts, daily null percentages of fields... and as re_data features expand with more data quality measurements include also

**Comment by owlas** [comment]
@djayatillake just clearing up the issue backlog and renaming this one. Not sure if we'll use re_data but it would be great to have data quality statistics and summaries from dbt too.

**Comment by djayatillake** [comment]
yeah I would agree, it looks like there is more native dbt functionality in this space and many more third party providers who we may want to integrate with too. Monte Carlo data have made it possible to define data quality tests using their platform in dbt yaml too.

**Comment by owlas** [comment]
Oh cool! I didn't know that, dbt meta has become a hot bed haha.

**Comment by djayatillake** [comment]
still relevant but not probably not high priority for now to get MVP featureset.

**Comment by owlas** [comment]
This is definitely an interesting one, I can see that having in this in the UI would be helpful. But I can imagine it would be mostly targeted toward developers rather than to data consumers using Lightdash.

Do you think it would be sufficient to show dbt test results, which would then allow data analysts to use dbt tests for tracking data quality (such as using re_data or great expectations dbt package)

**Comment by djayatillake** [comment]
Yes definitely towards developers, I think showing the test results, last run, success state of last run would be more useful to data consumers, also some level of understanding if joined tables have varying level's of freshness. We have an open issue that @hamzahc1 raised for that and I've commented on.

**Comment by owlas** [comment]
Perfect! Sounds like we can merge some of these issues together. with a design around how to include test data.

We have that on the roadmap coming in the next few months. I'll revisit this then!

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue - we haven't had any user requests for this in about 2 years, so I'll reopen if it becomes a user issue again!
