### ISSUE TITLE
not recording event when user links their Google account at signin

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2634]
### Description

We are not recording the event `lightdash_server_user_identity_linked ` when the user accepts an invite and uses gmail
Tech note: should be recorded in `activateUserFromInvite`

**Comment by rephus** [comment]
@TuringLovesDeathMetal  we are tracking user.created on activateUsersFromInvite. Do you want to replace this event ? or add a new one. 

`lightdash_server_user_identity_linked` is used on login via Google, it feels like  a completely different event, not related with invites.

**Comment by TuringLovesDeathMetal** [comment]
ya, sorry, I totally misunderstood this. 

I'm going to close this issue - I don't really understand what was meant to be tracked here 😅 I thought we weren't tracking `user_created` events if someone accepted an invite and created a user - which is not true.
