### ISSUE TITLE
Simplify repo Readme

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2644]
Our Readme is quite long, with huge walls of text, and we don't promote the Community as prominently as we'd like.

It should be simple enough not to be intimidating, whilst still serving up all relevant use cases for readme readers. We should spend a short amount of time (~1 hour) thinking of what those use cases are and what content in our readme solves each one, and cutting out irrelevant parts. 

Done when:
- The readme is shorter whilst still serving all use cases
- The link to the community is more prominent

**Comment by hamzahc1** [comment]
@12ian34 - do you still have ideas for what we can do to improve this?

**Comment by ZeRego** [comment]
I like the read me in this project https://github.com/ToolJet/ToolJet 

- Cool marketing images at the top ( but they have way to many. imo 3 is the max )
- Useful sections and links
- Small text blocks, mainly one lines or bullet points/table
- No emojis

**Comment by 12ian34** [comment]
I don't think it's stale. We've also recently had a user ask what "dbt" means from our readme - we don't explain it or even have a link to it, so we should include that.
