### ISSUE TITLE
Support ssh tunnelling for redshift connections

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2650]
### Description

If I'm using redshift, I may have my database only accessible in a VPC and to get access I need to Lightdash to use an SSH tunnel into my VPC before trying to connect.

### In scope ? 
Lightdash *should generate the SSH keypair* and store the private key, while returning the public key for the user to copy (see comments on how to generate an openssh compatible keypair). This might add some complexity to the onboarding process / API because we'd need to generate the keypair _first_ before the user runs saves their credentials and show them the public key.

Should this be in scope for the first PR or should we ship v1 without it? 

## Example

**Update - ssh tunnel config example**

I got this working with an SSH proxy into our render instance to access a private database. We'd need to add this to the postgres warehouse client in `@lightdash/warehouses` package. We might need to move the pool creation to `runQuery` instead of the constructor, so we can `await` the tunnel creation:

```typescript
import { PoolConfig } from 'pg';

import SSH2Promise from 'ssh2-promise';
import SSHConfig from 'ssh2-promise/lib/sshConfig';

        const remoteMachineConfig: SSHConfig = {
            host: 'ssh.oregon.render.com', // host of remote machine
            port: 22, // ssh port on remote machine
            username: '...', // username for remote machine
            privateKey:'-----BEGIN OPENSSH PRIVATE KEY-----', // openssh formatted private ssh key
            passphrase: '...', // optional passphrase for an encrypted privateKey
        } as SSHConfig;

        const sshCon = new SSH2Promise(remoteMachineConfig);

        const tunnel = await sshCon.addTunnel({
            remoteAddr: 'dpg-...', // host for the database (as seen by the remote machine)
            remotePort: 5432, // port for the database (as seen by the remote machine)
        });

        const credentials: PoolConfig = {
            port: tunnel.localPort, // port on lightdash server forwarded from ssh (this will now be the db)
            host: 'localhost', // host on lightdash server with port forwarded from ssh
            // standard postgres config...
            user: '...',
            password: '...',
            database: '...',
        };
```

To support this we'll need the following configuration for postgres/redshift warehouses:
- ssh host
- ssh port
- ssh username
- ssh password (optional)
- private key (optional)
- private key passphrase (optional)

Also to update:
- [ ] Frontend forms for Postgres / redshift
- [ ] Ensure these fields are added to the`sensitiveCredentials` list so they aren't returned by the API
- [ ] 

```

**Comment by owlas** [comment]
After trying to implement this, I recommend we wait until the warehouse code has been refactored. Otherwise we'll 
introduce more tech debt and the PR will bloat into changing a lot of the existing warehouse code.

Code improvements that would make this simpler:
* Co-locating warehouse logic
  * Many places in the code `switch` on the warehouse type, making it hard to robustly change logic for a warehouse
* Warehouse credentials API
  * The API to create, update, and store warehouse credentials has some confusing magic
  * Types are incorrect and forced (using `as`) for partial updates
  * API does no validation on incoming data
  * Secret fields magic strips secrets from the response but also responsible for partial update logic
* Decoupling projects from warehouse credentials
  * Warehouses and projects are closely connected
  * API is more complex than it needs to be
  * Updating warehouse requires triggering a full dbt compile and testing also requires git to be functioning
* `dbt compile`
  * Unsure if we can actually fix this, but we also need the tunnel to be available when we run `dbt compile`
  * Unsure if there is a better way to "convert" warehouse credentials (with tunelling) into a valid dbt environment
* Security
  * Exposing multiple databases on `localhost`
* `ssh2` library has an unexpected behaviour that might make an annoying UX: https://github.com/mscdex/ssh2/issues/989
  * Users using new ssh servers might have to change server configuration to allow us to connect even if it works for them on the CLI

## Implementation

To speed up future PRs here's some snippets from my draft PR

### Creating credentials flow

The most secure way to connect is to generate SSH private & public keys for the user and show them the public key, 
while storing the private key. The user needs to see this **before** we test the connection, so this pair needs to 
exist first:

1. User goes to warehouse credentials UI
2. Opts into setting up an SSH tunnel
3. User is shown a public SSH key and instructions for where to install it
4. User continues to configure the tunnel
5. Does the user test the tunnel works before continuing with warehouse credentials setup?
6. User finishes warehouse credentials
7. User tests and saves warehouse credentials

### Storing private keys

I created a table with the primary key being the public key and a column with an encrypted private key. This would 
temporarily store the SSH keypairs (step 3 above) before the credentials are finally created (step 7). I stored the 
final public&private keys along with the warehouse credentials on save. Not sure if that's needed.

### Generating SSH Keypairs

Important to generate an `ssh-rsa` syle key (old openssh style) rather than providing the raw RSA key. Although this 
key causes problems with `ss2` (see link at top)

```typescript
import { generateKeyPair } from 'crypto';
import { promisify } from 'util';
import sshpk from 'sshpk';

const openSSHFromPEM = (key: string): string => {
    const parsed = sshpk.parseKey(key);
    parsed.comment = 'Generated by Lightdash';
    return parsed.toString('ssh');
};

export const generateOpenSSHKeyPair = async () => {
    const generate = promisify(generateKeyPair);
    const { publicKey, privateKey } = await generate('rsa', {
        modulusLength: 4096,
        publicKeyEncoding: {
            type: 'spki',
            format: 'pem',
        },
        privateKeyEncoding: {
            type: 'pkcs1',
            format: 'pem',
        },
    });
    return {
        publicKey: openSSHFromPEM(publicKey),
        privateKey,
    };
};
```

### Setting up the tunnel

Worked well for the WarehouseAdapters, not sure how to reliably wrap this around `dbt compile` commands

```typescript
const sshConfig: SSHConfig = {
    username: sshTunnel.username,
    privateKey: sshTunnel.privateKey,
    port: sshTunnel.port,
    host: sshTunnel.host,
} as SSHConfig; // force type, ssh2 not recognising these arguments
const ssh = new SSH2Promise(sshConfig);
await ssh.connect();
tunnel = await ssh.addTunnel({
    remoteAddr: warehouseConfig.host,
    remotePort: warehouseConfig.port,
});
warehouseConfig.host = 'localhost';

// randomly assigned local port
warehouseConfig.port = tunnel.localPort;

// Essential to set connection timeout, otherwise wrong tunnel configuration can hang forever
pool = new pg.Pool({
    ...warehouseConfig,
    connectionTimeoutMillis: 2000,
});
```

**Comment by hamzahc1** [comment]
@owlas has the refactor you mentioned here happened yet? Someone asked me about this ticket today
