### ISSUE TITLE
Chart config and export should be disabled when query is invalid

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2652]
### Description

Chart config and export should be disabled when query is invalid

### To Reproduce

- go to table
- buttons are enabled

![Screenshot 2022-07-07 at 18 09 24](https://user-images.githubusercontent.com/9117144/177831124-fdfda61b-4389-4099-9873-321c656a13cf.png)

### App Version

0.174.0

**Comment by muhsinkamil** [comment]
Hey @ZeRego I would like to work on this.
Can we use `useEcharts` to determine if we should enable these options similar to the check to show empty chart. Even when there is an empty chart display, Options ( Chart, configure, Export as ) are available.

<img width="1415" alt="Screenshot 2022-08-21 at 5 46 40 PM" src="https://user-images.githubusercontent.com/62111075/185790445-168ec273-0232-46e9-9847-33863fa20c23.png">
