### ISSUE TITLE
If I leave the UI open for a while in the background I see an error

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2653]
### Description

If I leave the UI open for a while in the background I see this error:

<img width="1465" alt="Screenshot 2022-07-08 at 09 38 13" src="https://user-images.githubusercontent.com/11660098/177952884-c4dd7d8e-8cbb-459c-9f41-335014cfff57.png">

**Comment by hamzahc1** [comment]
How long do you have to leave it open to see an error?
