### ISSUE TITLE
The CLI tool isn't auto-populating the schemas with doc blocks. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2654]
### Description

The CLI tool isn't auto-populating the schemas with doc blocks. 

When I generate a schema for a new model (tracks.sql), I have some columns that have docs files defined in my dbt project. 

For example, `organization_id`.

These fields aren't getting auto-populated, and I'm no longer being asked by the CLI if I want to have these populated 🤔 

### To Reproduce

<img width="515" alt="image" src="https://user-images.githubusercontent.com/31848148/177954929-4811031b-85dd-4874-95cb-3ee330f92167.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/31848148/177955256-d8dbf0ed-42ca-4a0c-bc9b-9ab3a1b6e8fc.png">
<img width="763" alt="image" src="https://user-images.githubusercontent.com/31848148/177955315-b2842d27-7403-457c-972c-07e288309a89.png">

**Comment by rephus** [comment]
I think in this case is because the docs is inside a `docs` folder. Do you have docs-paths specified in your yml file ? https://docs.getdbt.com/reference/project-configs/docs-paths  . https://docs.getdbt.com/docs/building-a-dbt-project/documentation#using-docs-blocks

**Comment by rephus** [comment]
If I add `docs-paths: ["models"]` to my dbt_project.yml it will show the doc in my `/models/docs` subfolder 

![image](https://user-images.githubusercontent.com/1983672/178748862-62d31a75-bf8f-4eb1-ae17-73ddca8239d1.png)
![image](https://user-images.githubusercontent.com/1983672/178749055-07ad0707-1a80-485d-8b7f-5e09d0d84471.png)

Let me know if that solves your issue

**Comment by TuringLovesDeathMetal** [comment]
It works if I change the docs-paths!

Weird that it doesn't see it if I have it in a `docs` folder though 🤔

**Comment by rephus** [comment]
![](https://c.tenor.com/n4ZSObw-hzgAAAAM/simpsons-leonardo-nimoy.gif)
