### ISSUE TITLE
Prevent value labels overlapping between series

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2659]
### Description

When I show value labels for two series, they might overlap. Can they be separated better?

### Implementation

We can avoid overlap IN series by using this config in echarts:

```
      labelLayout: function (params) {
        return {
          x: params.rect.x,
          moveOverlap: 'shiftY'
        };
      },
```

^ not actually sure why `x: ` is needed in there it seems like a bug.

**Before**
<img width="1062" alt="Screenshot 2022-07-08 at 15 47 25" src="https://user-images.githubusercontent.com/11660098/178016986-b4398cab-b378-49bf-a01b-ed94608d5f1e.png">

**After**
<img width="1020" alt="Screenshot 2022-07-08 at 15 48 18" src="https://user-images.githubusercontent.com/11660098/178016975-fd1f090b-181a-4509-8cbe-8ae05cde79ab.png">

**Comment by rephus** [comment]
This can maximize labels, but some labels are missing 

```
 labelLayout:  function (params: any) {
                return {
                  hideOverlap: true, 
                  rotate: 45, 
                  y: params.rect.y,
                  moveOverlap : 'shiftY',
                };
              },
```

![image](https://user-images.githubusercontent.com/1983672/178955390-6a7a6efd-d3e5-4b5c-8c25-89e084361ea0.png)

**Comment by rephus** [comment]
labelLayout:  function (params: any) {
                return {
                  dy: -params.dataIndex%5 * 20 ,
                };
              },

:grimacing: 

![image](https://user-images.githubusercontent.com/1983672/178957321-d79b7471-9554-40bb-ba60-818ea61ed9d9.png)

**Comment by TuringLovesDeathMetal** [comment]
Ya, hiding on overlap seems like a good option!

Then, I'm assuming that more labels would appear if I stretched or shrunk my chart, right? (like, by stretching the window my chart is in)

**Comment by TuringLovesDeathMetal** [comment]
sweet! sounds good.

**Comment by TuringLovesDeathMetal** [comment]
@rephus I ran into this again today:

<img width="415" alt="image" src="https://user-images.githubusercontent.com/31848148/182798863-741863b1-c18a-4494-a571-56d22dc5e2bd.png">

Wondering what might be happening here 🤔

**Comment by TuringLovesDeathMetal** [comment]
https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/dashboards/e2b82df2-4b66-4238-8535-796b942ff3a0/view

**Comment by ZeRego** [comment]
> Wondering what might be happening here 🤔

@TuringLovesDeathMetal iirc echarts only avoids overlap of labels from the same series. It doesn't calculate overlap between series like in that screenshot 😢

**Comment by TuringLovesDeathMetal** [comment]
womp womp - silly echarts
