### ISSUE TITLE
Users can move charts/dashboards while you're viewing/editing them

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2666]
### Description

You're able to move a saved chart/dashboard to another space while you're viewing or editing it.

User acceptance criteria:

- you know which space the saved chart/dashboard belongs to when you're in edit mode. 
- you're able to move things when you're in edit mode _**or**_ in view mode.

**Comment by rephus** [comment]
@PriPatel do we need design for this ? where to place this `space name` labels or how to edit that..

**Comment by PriPatel** [comment]
@rephus 
I haven't had time to design for this but this is a really quick suggestion:
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=6133%3A82606


I have no idea how this would work fro dashboards as we have not yet prioritised making the dashboard header work similarly to the saved chart header!

**Comment by rephus** [comment]
I like your suggestion for charts, but looks like the dashboard needs a bit more work, so if we want, we can split this issue and ship charts first

**Comment by rephus** [comment]
> I like your suggestion for charts, but looks like the dashboard needs a bit more work, so if we want, we can split this issue and ship charts first

@TuringLovesDeathMetal what do you think ?

**Comment by TuringLovesDeathMetal** [comment]
Ya, let's ship charts first!

I think there's another open issue about making the header for dashboards match chart which will become important v soon: #2072

**Comment by TuringLovesDeathMetal** [comment]
I'll update that issue to include moving spaces ^
