### ISSUE TITLE
We have an omnibar for adding items to a space

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2671]
### Description

We have an omnibar we can use to search all saved charts, dashboards, folders, and descriptions at the same time

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal Can you provide more details about this feature ? the description doesn't seem to match the title.

**Comment by TuringLovesDeathMetal** [comment]
ya, this isn't relevant anymore
