### ISSUE TITLE
Stacking resets after changing series type

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2676]
### To Reproduce

<a href="https://www.loom.com/share/4ee4456e91174e64a9df726c64436fd2">
    <p>Lightdash - bug stacking - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/4ee4456e91174e64a9df726c64436fd2-1657553075265-with-play.gif">
  </a>

![https://www.loom.com/share/4ee4456e91174e64a9df726c64436fd2](https://cdn.loom.com/sessions/thumbnails/4ee4456e91174e64a9df726c64436fd2-1657553075265-with-play.gif)

### App Version

0.177.0

**Comment by rephus** [comment]
Probably related: If I change the filters on dashboard, stacking also resets 

![Peek 2022-07-12 09-40](https://user-images.githubusercontent.com/1983672/178436207-d4b2fdd0-85e2-4e73-b016-e5e6bde521bf.gif)
