### ISSUE TITLE
UI changes to the sidebar

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2685]
- [x] `Dimensions` should be displayed before `Metrics`. 
- [x] - Change the background colour of selected dimensions / metrics (to match the colours of the results table)
- [x] - Get rid of dead space near table name
- [x] - Move table information icon next to table name
- [x] - Groups to look like different items to fields. They should not have icons. They should have a heavier weight.
- [x] Change icons of fields to be coloured so that they look more selectable than the group names.
- [x] Add 10px between each 'section'. (metrics / dimensions / custom metrics)

[Figma file]
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=5716%3A91309

**Comment by ZeRego** [comment]
It's time to stop using blueprintjs tree component and build our own using a TreeProvider so all items can easily access the state to how what is being hovered or selected and avoid flickering and constant rerenders.
