### ISSUE TITLE
Option to sum stacked series value labels

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2687]
Currently, when showing value labels for a series that has been stacked, the label is shown by default for each constituent value.

It would be useful to have the option to have this summed across the whole stack.

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/9979944/178545407-4dd68ffc-f67d-45ef-aa04-b0a288eb95bc.png">

**Comment by TuringLovesDeathMetal** [comment]
I think this is a duplicate!

https://github.com/lightdash/lightdash/issues/1652
