### ISSUE TITLE
Replace 'citation' icons when displaying certain dimensions

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2688]
Two options here - I think it will need some trial and error to see which suits best:

![image](https://user-images.githubusercontent.com/12776522/178547937-5f6d94c0-cb77-4ef1-aa6a-c99c56b12411.svg)
![image](https://user-images.githubusercontent.com/12776522/178547939-4324e416-68d4-468e-a660-332ce5c31966.svg)

**Comment by TuringLovesDeathMetal** [comment]
^Forewarning for anyone using GitHub in dark mode...the text is in black, so you just need to highlight it to see it!

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel I'm not too sure where this is meant to be implemented 🤔 do you have an example of what you want to replace in the app? (just to make it easier for someone to pick this up)

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal I feel like this is now redundant -  I'm going to close this as we hope to move to a new icon library soon!
