### ISSUE TITLE
Update the screen when you're on mobile

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2689]
I've had some feedback where someone has somehow ended up on the demo on mobile (even though the marketing site hides the links to the demo when the screen size is too small)... 
- The logo is not up to date
- The text needs updating
- It currently is a dead end so we should provide some CTAs
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=815%3A33194

**Comment by hamzahc1** [comment]
Maybe a link to the demo video instead?

**Comment by PriPatel** [comment]
Relevant - I think at the very least, the logo needs to be updated!
