### ISSUE TITLE
Users can create a project in the UI (instead of needing to configure this before deploying)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#270]
- Users can create a project in the UI (being able to configure things in the UI). This means that 1 click deploy would now have a flow of `create an account` —> `configure your project in the Lightdash UI`. Having this project configuration in the UI would eventually allow us to:
    - Give multiple options for the "source" of your project (e.g. connect Lightdash to GitHub repo or to a project in dbt cloud)
    - Give users the option to change the project once they've picked one (right now, that's not possible)
    - Eventually, users could have multiple projects

**Comment by owlas** [comment]
**Checklist**

- [ ] Create db schema + migration to store projects
- [ ] Use lightdash.yml project configuration to seed the database if empty
- [ ] Allow user to create new projects through the UI
- [ ] Allow empty lightdash.yml and only create projects through the UI

**Comment by TuringLovesDeathMetal** [comment]
We've decided to archive this ticket for now because we're prioritizing defining config as code (no config in the UI....for now...). 

What this means is:
1.  if you do a one-click-deploy to Heroku, when you input your project config, we save this to a `lightdash.yml` file in your container...it will be really hard to update your project in this case: you'll have to be a Heroku wiz 🧙 . But, most people won't update their project...and if you absolutely have to, then you can delete the Heroku project + restart. 
2. if you are setting up Lightdash locally, then you can update your project in your `lightdash.yml` file wherever you have it. 


@owlas  two questions:
1. above, I say: "you can delete the Heroku project + restart." --> This won't delete the Lightdash project (I don't think...). So, if they delete the Heroku project + create a new one, then there will be an org with multiple projects. Can a single org have multiple projects? Or will this break stuff? 
2. I feel like point 2 above is worded incorrectly 😅 Would you mind just checking to see if this matches what we talked about before? The bit I'm unsure about is the `setting up Lightdash locally` --> I think this might actually be `setting up dbt cloud with Lightdash` (or something completely different)

**Comment by owlas** [comment]
@TuringLovesDeathMetal 

1. not sure I understand what you're asking.
2. setting up lightdash locally means you have lightdash sitting on top of the raw project on your laptop and you could easily change the lightdash.yml with your editor and restart lightdash no problem

**Comment by TuringLovesDeathMetal** [comment]
for 1. I'm saying, imagine a situation where I don't know how to update my lightdash.yml file in my app (because I've done one-click-deploy). 

So, I just delete my Heroku app and create a new one with my new project information. 

Now, what we have in the db of deployments is:
- project_name, org_name, user_name
- project 1, my org name, katie
- project 2, my org name, katie

Will this break anything at the moment? Like, if I try to open `project 2 app` will it break because it's like "wait, your user + org is associated to this other project, `project 1` 💣 "

Does that make sense?

**Comment by owlas** [comment]
Actually if you do that you will delete everything in your existing deployment. When you redeploy the whole heroku template, it'll start with a fresh database.

**Comment by TuringLovesDeathMetal** [comment]
perfection 😗 👌

**Comment by TuringLovesDeathMetal** [comment]
closing this because it's a duplicate of #438
