### ISSUE TITLE
Hiding series from a chart causes the colours to get mixed up

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2703]
### Description

When you have a chart with a grouped dimension in it, then you try to hide some of the series, the colours get mixed up in the not-hidden series. 

Basically, you keep the colour of the first series and just use it for the other series. It's weird...

### To Reproduce

https://www.loom.com/share/1075d15d64a848cca77bf77528d8babb

### App Version

0.179.0

**Comment by rephus** [comment]
![image](https://user-images.githubusercontent.com/1983672/182581857-eb722429-d8f3-4315-b3c7-a52eb0e18024.png)

I think what is happening on the chart is right, basically, we keep the same color ordering on the non hidden series. 

What's wrong is the color in the `chart config menu` it should gray out disabled series, and keep the right color ordering on the enabled series. 

what do you think ? @TuringLovesDeathMetal @PriPatel

**Comment by TuringLovesDeathMetal** [comment]
I don't think we should keep the same colour ordering. I think it should disable the colour you've clicked in the chart. 

Reason being: imagine I'm 'exploring from' a chart where  I've colour coded my series to specific values (cloud = purple, self hosted = yellow, enterprise = blue). I want to hide self-hosted from this chart. 

I do that, but now all the colours get mixed up, so enterprise is now yellow and doesn't match the colour-coding anywhere else (annoying!) I have to manually change it back to the right colour

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 
Problem: 
The series don't have a saved colour by default. In the UI we guess the colour echarts is going to use based on the series index. 

To implement your solution we would have to stop guessing the colour and have to save a specific colour for each series.
If we save colours, it will stop inheriting the org colours.

@rephus correct me if you thought about a different approach.

**Comment by rephus** [comment]
This seems to work @ZeRego https://github.com/lightdash/lightdash/pull/2840

**Comment by ZeRego** [comment]
Ignore my last comment, @rephus found a smart way to avoid all of that 💪 🎉

**Comment by TuringLovesDeathMetal** [comment]
classic @rephus
