### ISSUE TITLE
Manage spaces from the spaces page

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2704]
### Description

Users should be able to rename and delete spaces from the spaces detail page.

<img width="533" alt="Screenshot 2022-07-13 at 16 19 41" src="https://user-images.githubusercontent.com/11660098/178770138-b9f47f84-d8ed-45e9-8f14-e8cf3c246c8f.png">

Rename could use this pattern again. Delete with a button

<img width="724" alt="image" src="https://user-images.githubusercontent.com/31848148/178245526-2dae2722-879c-4680-8581-a33f19c69376.png">

**Comment by ZeRego** [comment]
Closing in favour of #2859
