### ISSUE TITLE
I can view all charts and dashboards for a single space

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2707]
### Description

A new page for each space, which shows the charts/dashboards saved in it. Use existing components from the all charts / all dashboards pages

<img width="517" alt="Screenshot 2022-07-13 at 16 37 14" src="https://user-images.githubusercontent.com/11660098/178773950-2e56a2c4-008d-43c7-b91d-6131b1460f86.png">

**Comment by TuringLovesDeathMetal** [comment]
@owlas is adding charts/dashboards to the space included in the scope of this ticket?
