### ISSUE TITLE
Rename dashboard tile titles

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2708]
### Description

Related to https://github.com/lightdash/lightdash/issues/1848 - I want to be able to rename a chart tile title. For example I might give it a long unique name for searching "my bar chart that is very important and should be looked at every day" but in the context of a dashboard I might have it say "All customers".

### Acceptance criteria

Miro sketch: https://miro.com/app/board/uXjVM5_vIl0=/?share_link_id=339879375259

- [ ] I'm able to rename a chart title using the three-dot-menu on a chart when I'm in `edit` mode on a dashboard. There is an option which is `Edit title`
- [ ] Rename the `edit tile content` option to say `replace chart in tile` and update the icon to use a "replace" type icon
- [ ] If I rename a chart in a dashboard, when I search for the chart in search, it will appear in search using the original chart title.

**Comment by PriPatel** [comment]
Really relevant. Now that we allow users to add multiple copies of the same chart on their dashboards, it is getting hard for them to manage (especially in the tiles tab of filters) 
<img width="521" alt="Screenshot 2023-06-28 at 12 29 09" src="https://github.com/lightdash/lightdash/assets/12776522/9893aa61-e8c1-4d15-8b62-bba8cc299849">
Suggestion:

 When you're 'editing tile content', add a field here to change the title. Default should be the chart name.
