### ISSUE TITLE
Set a default chart config for 2+ dimensions but just 1 metric 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#2711]
### Description

If you select 2+ dimensions but only 1 metric, we don't default any chart

![img](https://user-images.githubusercontent.com/1983672/179172539-0cc72d0c-6f65-4884-ae0e-53b014cd0fa5.png)

I'd expect to see a chart, even a simple one. we could apply the same chart we have with 2 dimensions and 2metrics: 

```
x = dimension[0]
y = metric[0]
pivot = dimension[1]
```

### App Version

 v0.181.1

**Comment by TuringLovesDeathMetal** [comment]
This is kind of related to #1537 

I'd expect the default to be dimension on x-axis, then two dimensions as groups, then metric as y-axis

If I had two dimensions and two metrics, I'd expect to see the dimension 1 on the x-axis, dimension 2 as a group, then both metric 1 + metric 2 plotted. 

In general, I'd expect _**all**_ of the things in my results table to be plotted the first time I hit `run query`. 

I'd want dimensions to be x-axis + the rest as `group`
I'd want all of my metrics + table calculations plotted on teh y-axis

**Comment by TuringLovesDeathMetal** [comment]
Given thatn #1537 doesn't exist yet, I think we should just plot the first dimension, then all of the metrics + table calculations

**Comment by TuringLovesDeathMetal** [comment]
^Also kind of relates to #1698
