### ISSUE TITLE
When I add a filter, I should be brought up to the filters tab, opened

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2715]
### Description

When you add a filter from the sidebar, or from the results table, you need to immediately fill out that filter. 

Right now, we don't automatically bring you to the filter, with the toggle open. 

Whenever a user adds a filter, they should be brought up to the filter bar, and the filter toggle should open. 

https://www.loom.com/share/9240b5710b094058a68da8a2a3e88adc

### What problem does this solve?

As soon as you add a filter, you need to adjust the filter values. So, if I add a filter, I should be brought up to the filter I've just added so that it's really easy to take the next step: editing it.

**Comment by rephus** [comment]
How it works currently: 
![Peek 2022-08-08 10-06](https://user-images.githubusercontent.com/1983672/183370353-970018ab-824c-46d2-89a6-4ebb61b22e2d.gif)

**Comment by rephus** [comment]
I can open the `filters` panel, but I don't know how to add focus to the field nicely. I'm not even sure if this is a requirement, or just opening the panel (when closed) is enough. 

![Peek 2022-08-08 12-25](https://user-images.githubusercontent.com/1983672/183397603-3299aa13-9fcc-45c7-818f-51abd1566623.gif)


@ZeRego ideas ? I think it should be here https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/common/Filters/index.tsx#L199

**Comment by ZeRego** [comment]
@rephus it would be in `DateFilterInputs.tsx`
