### ISSUE TITLE
App freezes when changing chart configuration

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2725]
### Description

Sometimes the app freezes when changing the layout configuration.

### To Reproduce

In this case I changed the axis from a boolean dimension to a date dimension. 

![Screenshot 2022-07-15 at 16 46 15](https://user-images.githubusercontent.com/9117144/179259344-08286719-b222-47a1-9696-64ec7f3c01f8.png)

After a bit I was able to change the page again but the chart configuration is out of sync with the echarts.

![Screenshot 2022-07-15 at 16 47 55](https://user-images.githubusercontent.com/9117144/179259701-d75f708e-4b6e-4007-a35a-2ee96d139ac2.png)

There might be a problem when we check if the layout is valid or regenerating the series causing a infinite loop 🤔 

### App Version

0.181.1

**Comment by TuringLovesDeathMetal** [comment]
This happened to me yesterday!

**Comment by ZeRego** [comment]
Closing this in favour of [2997](https://github.com/lightdash/lightdash/issues/2997)
