### ISSUE TITLE
I can see what space a saved chart/dashboard belongs to when I'm browsing the `all charts` and `all dashboards` lists

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2734]
### Description

When I'm browsing `all charts` or `all dashboards`, there's a parameter in the entry showing which space (if any) the chart or dashboard is in. 

![image](https://user-images.githubusercontent.com/31848148/179705450-5f31d79a-068b-4648-a08a-ca8963506eeb.png)

### What problem does this solve?

If I want to do #2665, then I'll need to know which space something is already in before I try to move it. Also, the space that a chart/dashboard is in adds a lot of context to it.

**Comment by rephus** [comment]
Cuyrrently the selected space appears disabled with a :white_check_mark: . Is this enough @TuringLovesDeathMetal  ? 
![image](https://user-images.githubusercontent.com/1983672/183403092-abb93e58-943f-43f2-aca2-74f56eb5fa79.png)

**Comment by TuringLovesDeathMetal** [comment]
nice! yep, that works :)
