### ISSUE TITLE
Webapp event when cross-filtering is applied

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2758]
### Description

When someone clicks on a data point to apply cross-filtering to a dashboard, this should trigger a webapp event. 

`cross_filtering_apply_click`

**Comment by rephus** [comment]
By cross filtering do you mean adding a afilter like this to dashboard ? Do you want to trigger it when `clicking filter` ? or when a successful filter is applied  ![image](https://user-images.githubusercontent.com/1983672/186371027-dde27149-0fa0-40dd-a741-8f31a8fe6968.png) @TuringLovesDeathMetal

**Comment by TuringLovesDeathMetal** [comment]
no, sorry, I mean when you click on a value in a chart and filter by it: 

<img width="969" alt="image" src="https://user-images.githubusercontent.com/31848148/186401122-bdf10b78-e2c1-4b98-9574-1d8218e487e8.png">
