### ISSUE TITLE
Stacked area chart displays weird with NULL value

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2759]
### Description

When I have a stacked area chart, and it tries to stack a `null` value, it doesn't add a `0` value to the stack, instead it brings the line down to 0 on the y-axis:

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/31848148/180247169-d3762e0c-e2a1-49ed-8886-e60b6778398e.png">

<img width="522" alt="image" src="https://user-images.githubusercontent.com/31848148/180247202-5e77e823-7892-442b-96c1-a9afb1cf86fc.png">

[Link to chart here.
](https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/tables/dbt_orders?create_saved_chart_version=%7B%22uuid%22%3A%2230cf58e5-9e06-4a43-99b8-c2900345b914%22%2C%22projectUuid%22%3A%222014e038-ff4b-4761-ae6f-fbf551e7b468%22%2C%22name%22%3A%22How+much+revenue+does+each+referrer+bring+us+in+per+week%3F%22%2C%22description%22%3Anull%2C%22tableName%22%3A%22dbt_orders%22%2C%22updatedAt%22%3A%222022-06-08T09%3A55%3A20.977Z%22%2C%22updatedByUser%22%3A%7B%22userUuid%22%3A%2291f99cdd-d160-4584-aa38-0eda0aaf7b73%22%2C%22firstName%22%3A%22Ian%22%2C%22lastName%22%3A%22Ahuja%22%7D%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22dbt_orders_order_date_week%22%2C%22dbt_orders_referrer%22%5D%2C%22metrics%22%3A%5B%22dbt_orders_sum_of_basket_total%22%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22dbt_orders_order_date_week%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%7B%22table%22%3A%22dbt_orders%22%2C%22name%22%3A%22user_id_count_distinct%22%2C%22type%22%3A%22count_distinct%22%2C%22label%22%3A%22Count+distinct+of+User+id%22%2C%22description%22%3A%22Count+distinct+of+User+id+on+the+table+Dbt+orders.+Lightdash+has+created+this+metric+automatically.%22%2C%22sql%22%3A%22%24%7BTABLE%7D.user_id%22%7D%2C%7B%22table%22%3A%22dbt_orders%22%2C%22name%22%3A%22order_id_count_distinct%22%2C%22type%22%3A%22count_distinct%22%2C%22label%22%3A%22Count+distinct+of+Order+id%22%2C%22description%22%3A%22Count+distinct+of+Order+id+on+the+table+Dbt+orders.+Lightdash+has+created+this+metric+automatically.%22%2C%22sql%22%3A%22%24%7BTABLE%7D.order_id%22%7D%2C%7B%22table%22%3A%22dbt_orders%22%2C%22name%22%3A%22partner_id_count_distinct%22%2C%22type%22%3A%22count_distinct%22%2C%22label%22%3A%22Count+distinct+of+Partner+id%22%2C%22description%22%3A%22Count+distinct+of+Partner+id+on+the+table+Dbt+orders.+Lightdash+has+created+this+metric+automatically.%22%2C%22sql%22%3A%22%24%7BTABLE%7D.partner_id%22%7D%2C%7B%22table%22%3A%22dbt_orders%22%2C%22name%22%3A%22basket_total_sum%22%2C%22type%22%3A%22sum%22%2C%22label%22%3A%22Sum+of+Basket+total%22%2C%22description%22%3A%22Sum+of+Basket+total+on+the+table+Dbt+orders%22%2C%22sql%22%3A%22%24%7BTABLE%7D.basket_total%22%7D%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22dbt_orders_order_date_week%22%2C%22yField%22%3A%5B%22dbt_orders_sum_of_basket_total%22%5D%2C%22flipAxes%22%3Afalse%7D%2C%22eChartsConfig%22%3A%7B%22xAxis%22%3A%5B%7B%22name%22%3A%22Week%22%7D%5D%2C%22yAxis%22%3A%5B%7B%22name%22%3A%22Revenue%22%7D%2C%7B%7D%5D%2C%22series%22%3A%5B%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22direct%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22instagram%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22organic%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22ppc%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22twitter%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22facebook%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%5D%7D%7D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22dbt_orders_order_date_week%22%2C%22dbt_orders_referrer%22%2C%22dbt_orders_sum_of_basket_total%22%5D%7D%2C%22organizationUuid%22%3A%22e12c2f9f-6dc6-473d-be18-fdb4556c100d%22%2C%22pivotConfig%22%3A%7B%22columns%22%3A%5B%22dbt_orders_referrer%22%5D%7D%7Dhttps://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/tables/dbt_orders?create_saved_chart_version=%7B%22uuid%22%3A%2230cf58e5-9e06-4a43-99b8-c2900345b914%22%2C%22projectUuid%22%3A%222014e038-ff4b-4761-ae6f-fbf551e7b468%22%2C%22name%22%3A%22How+much+revenue+does+each+referrer+bring+us+in+per+week%3F%22%2C%22description%22%3Anull%2C%22tableName%22%3A%22dbt_orders%22%2C%22updatedAt%22%3A%222022-06-08T09%3A55%3A20.977Z%22%2C%22updatedByUser%22%3A%7B%22userUuid%22%3A%2291f99cdd-d160-4584-aa38-0eda0aaf7b73%22%2C%22firstName%22%3A%22Ian%22%2C%22lastName%22%3A%22Ahuja%22%7D%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22dbt_orders_order_date_week%22%2C%22dbt_orders_referrer%22%5D%2C%22metrics%22%3A%5B%22dbt_orders_sum_of_basket_total%22%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22dbt_orders_order_date_week%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%7B%22table%22%3A%22dbt_orders%22%2C%22name%22%3A%22user_id_count_distinct%22%2C%22type%22%3A%22count_distinct%22%2C%22label%22%3A%22Count+distinct+of+User+id%22%2C%22description%22%3A%22Count+distinct+of+User+id+on+the+table+Dbt+orders.+Lightdash+has+created+this+metric+automatically.%22%2C%22sql%22%3A%22%24%7BTABLE%7D.user_id%22%7D%2C%7B%22table%22%3A%22dbt_orders%22%2C%22name%22%3A%22order_id_count_distinct%22%2C%22type%22%3A%22count_distinct%22%2C%22label%22%3A%22Count+distinct+of+Order+id%22%2C%22description%22%3A%22Count+distinct+of+Order+id+on+the+table+Dbt+orders.+Lightdash+has+created+this+metric+automatically.%22%2C%22sql%22%3A%22%24%7BTABLE%7D.order_id%22%7D%2C%7B%22table%22%3A%22dbt_orders%22%2C%22name%22%3A%22partner_id_count_distinct%22%2C%22type%22%3A%22count_distinct%22%2C%22label%22%3A%22Count+distinct+of+Partner+id%22%2C%22description%22%3A%22Count+distinct+of+Partner+id+on+the+table+Dbt+orders.+Lightdash+has+created+this+metric+automatically.%22%2C%22sql%22%3A%22%24%7BTABLE%7D.partner_id%22%7D%2C%7B%22table%22%3A%22dbt_orders%22%2C%22name%22%3A%22basket_total_sum%22%2C%22type%22%3A%22sum%22%2C%22label%22%3A%22Sum+of+Basket+total%22%2C%22description%22%3A%22Sum+of+Basket+total+on+the+table+Dbt+orders%22%2C%22sql%22%3A%22%24%7BTABLE%7D.basket_total%22%7D%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22dbt_orders_order_date_week%22%2C%22yField%22%3A%5B%22dbt_orders_sum_of_basket_total%22%5D%2C%22flipAxes%22%3Afalse%7D%2C%22eChartsConfig%22%3A%7B%22xAxis%22%3A%5B%7B%22name%22%3A%22Week%22%7D%5D%2C%22yAxis%22%3A%5B%7B%22name%22%3A%22Revenue%22%7D%2C%7B%7D%5D%2C%22series%22%3A%5B%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22direct%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22instagram%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22organic%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22ppc%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22twitter%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22stack%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%2C%22pivotValues%22%3A%5B%7B%22field%22%3A%22dbt_orders_referrer%22%2C%22value%22%3A%22facebook%22%7D%5D%7D%7D%2C%22areaStyle%22%3A%7B%7D%7D%5D%7D%7D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22dbt_orders_order_date_week%22%2C%22dbt_orders_referrer%22%2C%22dbt_orders_sum_of_basket_total%22%5D%7D%2C%22organizationUuid%22%3A%22e12c2f9f-6dc6-473d-be18-fdb4556c100d%22%2C%22pivotConfig%22%3A%7B%22columns%22%3A%5B%22dbt_orders_referrer%22%5D%7D%7D)

It should stack a 0 value on top of the rest of the areas.

**Comment by ZeRego** [comment]
Closing in favour of #2422
