### ISSUE TITLE
SOC2 Compliance

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2761]
### Description

A customer has mentioned that they are only able to partner with vendors that are [SOC 2 compliant](https://www.imperva.com/learn/data-security/soc-2-compliance/) if they want to go with the Cloud option. Whilst an alternative for this customer could be to self-host Lightdash, it does require more resources and potentially an integration with another vendor.

### What problem does this solve?

To broaden our potential user base, it would be great to get SOC2 certification ourselves!

**Comment by hamzahc1** [comment]
What's step 1 here @12ian34 ? Do we need to speak to someone like Vanta to understand how big an undertaking it would be?

**Comment by 12ian34** [comment]
This involves getting an external org to give us a consultancy session to describe what is required for our business to become SOC2 compliant. Then we'd need to implement the recommendations. Then we'd need to get that (or another) external auditor to do an SOC2 audit on our implementation to get formally certified. Then we'd need to organise an annual review to stay certified.

This is kinda a huge undertaking. I don't think this is something we want to focus on now, or even in the near future - just getting this in to keep it in mind. It has blocked at least one customer from us now. Once we start hearing about this from a sizeable chunk more, then it's probably worth thinking about.

**Comment by 12ian34** [comment]
still relevant

**Comment by 12ian34** [comment]
@hamzahc1 mentioned that another similar company has opted to just go for SOC 2 Type 1, which is a cheaper, one-off audit than SOC 2 Type 2 (which is a continual annual audit). We should go for this for now.

**Comment by hamzahc1** [comment]
Completed! https://security.lightdash.com/
