### ISSUE TITLE
Show underlying values on any point in a chart.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2764]
[#2460](https://github.com/lightdash/lightdash/issues/2784) but for charts!

Rough walkthrough:
https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=5839%3A78946&scaling=min-zoom&page-id=5795%3A81300&starting-point-node-id=5839%3A78946

**Not in scope:**
Clickable dimensions links - ignore this for now! 

**Open questions:**
How does this work for each chart type?

**Comment by rephus** [comment]
What should I expect if I have a chart like this ? and pivots ? multiple series ? 

![image](https://user-images.githubusercontent.com/1983672/184078066-5a88c2d5-e821-4d69-b28c-3bcc02a4826a.png)

**Comment by PriPatel** [comment]
@rephus Filter by is not in scope. we already have this for charts in dashboards where you can cross filter . So no need to think about` filter by` :)

**Comment by rephus** [comment]
@TuringLovesDeathMetal @PriPatel is this valid for all different chart types, including table, bignumber and area charts ?

**Comment by TuringLovesDeathMetal** [comment]
yep!
