### ISSUE TITLE
refresh dbt   -> Forbidden error

### ISSUE THREAD

**Issue by raphaelauv** [lightdash/lightdash#2766]
### Description

I click on refresh_dbt

![Screenshot from 2022-07-22 15-27-23](https://user-images.githubusercontent.com/10202690/180449022-f54d6a58-7b42-489b-87e3-71010f27d9ce.png)

Error syncing dbt project

Forbidden error

### App Version

`0.187.0`

(I just updated from `0.176.0`)

**Comment by owlas** [comment]
Hey @raphaelauv thanks for opening this

Could you confirm your user role on the project and organization level under settings:

<img width="534" alt="Screenshot 2022-07-22 at 14 45 23" src="https://user-images.githubusercontent.com/11660098/180452330-5acb1f11-1bdb-4583-a6ea-ff6b8ddc89ee.png">

**Comment by raphaelauv** [comment]
user is not admin.

would be great to disable the button for non admin users than throwing an error msg
