### ISSUE TITLE
After adding the first filter option, the Apply button is hidden

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2767]
When adding a filter option, e.g. to a chart in a dashboard, the Apply button is hidden. If you click outside the filter modal, the whole filtering modal clears and closes meaning you have to start again. This means that after you add the first filter, and say you only want to do one filter (which I presume accounts for most of the usage), then you need to carefully click on a whitespace inside the modal to hide the filter list option popup so that you can then click Apply. Also, hitting `Escape` just closes the whole modal, clearing your selection.

It would be easier if, after you select your first filter option, the filter list popup doesn't re-show by default until you click again inside the filter input box OR start typing a new filter. Alternatively, we could consider allowing `Escape` to close the filter list popup rather than the whole filter modal (or that could be done in conjunction with the previous suggestion).

Happily selecting my first filter. all is well.
![image](https://user-images.githubusercontent.com/9979944/180449781-eda80128-c641-4b63-bb95-5a198fc63b42.png)

Oh no! I can't click Apply, how do i get rid of this filter list? Clicking outside the modal closes the whole thing and cancels my filter option. Hitting Escape does that too :(
![image](https://user-images.githubusercontent.com/9979944/180449904-8ba8579b-241e-4695-ab13-bef787fd9ed6.png)

Oh ok, I need to click inside the modal, in the small whitespace to hide it to be able to select Apply!
![image](https://user-images.githubusercontent.com/9979944/180449951-fb57290c-299c-46c1-9d62-081ccfda03bb.png)

**Comment by TuringLovesDeathMetal** [comment]
+1 for it not reappearing until you start typing a new filter

**Comment by TuringLovesDeathMetal** [comment]
Just ran into this as well - super annoying 😅 it took me like 3 tries to click on the tiny space and get the filter to not cancel

**Comment by ZeRego** [comment]
@12ian34 @TuringLovesDeathMetal I'm not a fan of that behaviour when is a multi select dropdown. I want to select all the options I need in 1 go. With the behaviour you are describing I need open the dropdown multiple times.

**Comment by rephus** [comment]
Pressing `ESC` does not just close the dropdonw, but it closes the whole popup. This could be a solution if we're able to capture the key 

[Screencast from 10-10-22 15:32:27.webm](https://user-images.githubusercontent.com/1983672/194878276-f49baca1-0ee1-4a71-9a41-a887fdebad46.webm)

**Comment by ZeRego** [comment]
@rephus there is a prop `canEscapeKeyClose` for the popover https://blueprintjs.com/docs/#popover2-package/popover2 that we could disable if the dropdown is open 🤔
