### ISSUE TITLE
By default, you have a space in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2768]
### Description

By default, you have a space in Lightdash called `Shared` - you can delete/rename/etc. this space. But, you will always have a space in your project, from the start.

**Comment by rephus** [comment]
Question, should we allow to delete "all spaces " ?, eg:  I could prevent from deleting all spaces, so at least you always have one

**Comment by TuringLovesDeathMetal** [comment]
^I think deleting all spaces is fine!

Sorry, I meant "at the start, you will always have a space"
