### ISSUE TITLE
Ability to disable total in the table chart + results table

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#2772]
### Description

Ability to disable total in the table chart

### What problem does this solve?

Not all numeric fields can be summed, like, id's and averages. 

For some tables, a total row isn't necessary.

**Comment by TuringLovesDeathMetal** [comment]
@Martin-Carlsson I'm assuming you mean disable totals for _**all**_ of the columns here - not just the ones that can't be summed

**Comment by Martin-Carlsson** [comment]
@TuringLovesDeathMetal 

Yes for all columns.

The entire total row.

**Comment by ZeRego** [comment]
Should the totals in the table viz be opt-in or opt-out ?

**Comment by TuringLovesDeathMetal** [comment]
ah! sorry, meant to reply to this in the morning but totally forgot. 

hmm, I feel like opt-in?

**Comment by Martin-Carlsson** [comment]
@ZeRego 
I would also say opt-in.

In the future it could be even more elaborate, like ability to choose calculations, _average, count, or sum,_  on individual columns. 

But for now I could go with either opt-in or opt-out. I do think that this is an important feature, since the total row are giving unexpected results.
