### ISSUE TITLE
Ordering of "Select a dimension to filter" on Dashboards should be alphabetical

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#2773]
### Description

The **Select a dimension to filter** could be ordered to make finding the wanted dimension on a dashboard easier. 

The dimensions and metrics should be ordered by:

- alphabetically by table name in dashboard filters
- in the Explore View, the tables should be ordered the same as they are in the sidebar (i.e. the primary table comes first, then the joined tables are listed after)
- then alphabetically by field name

e.g. if I had a table `users` that was joined to `pages`, the fields: `Users - user_id`, `Pages - page_id`, `Users - date` would appear like:

`Users - date`, `Users - user_id`, `Pages - page_id`

### What problem does this solve?

It is difficult for the end user to get an overview of the filters—especially the date filters, since they are not united.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/7769335/180692654-7f649e9e-8f1c-46a0-807f-1d0bdca6759d.png">

**Comment by TuringLovesDeathMetal** [comment]
@Martin-Carlsson are you think of it being ordered a bit more like what you see in the sidebar?

**Comment by Martin-Carlsson** [comment]
@TuringLovesDeathMetal of cause ordering like in the `table explorer` would be amazing. I just thought that would be a larger task since it might require some changes in the UI 😄

So, with this issue I just asked for alphabetic ordering, since that would give 70% of the value 😊

**Comment by Martin-Carlsson** [comment]
Yes, still relevant

Maybe alphabetical ordering isn't the best approach, but it would be nice if there were some logic.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/7769335/192097083-dcb8dbf5-34a5-42dc-98d3-28e818b49cc8.png">
