### ISSUE TITLE
Improve error message when dbt or warehouse credentials are missing 

### ISSUE THREAD

**Issue by raphaelauv** [lightdash/lightdash#2780]
### Description

Error message for missing credentials doesn't make sense and is hard to track back to the original error. in this case the personal access token was missing but the message said "could not read Password..." 
```
Compiling

Error 00:00:01

UnexpectedServerError: Error: Cloning into '/tmp/git_fa8eb50cbaf2d97a4cb80bdffeefa998'... fatal: could not read Password for 'https://*****@github.com': terminal prompts disabled 
```

![Screenshot from 2022-07-25 17-12-13](https://user-images.githubusercontent.com/10202690/180813242-ec1b946d-de87-4eb5-9aa2-1d4b14c3f85c.png)

### App Version
v.187.0

**Comment by raphaelauv** [comment]
Personal access token 
![Screenshot from 2022-07-25 17-22-33](https://user-images.githubusercontent.com/10202690/180815301-8647134c-ad47-4c80-82c5-3d2f206648f5.png)
was empty, back to running

**Comment by hamzahc1** [comment]
Was this resolved @raphaelauv ? Let me know if you're happy for me to close if so!

**Comment by raphaelauv** [comment]
the error is not obvious , so my problem is solve but not how it's manage by lightdash

**Comment by hamzahc1** [comment]
Understood! I'll open a new issue that should improve the error message here to make it more obvious where the error is coming from and link to this issue
