### ISSUE TITLE
Update the empty state for a Space

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2782]
### Description

- update dashboard copy in empty space
- add `add dashboards` button to empty space. This button disappears as soon as there's at least one dashboard in the space.
- update saved charts copy in empty space.
- add `add saved charts` button to empty space. This button disappears as soon as there's at least one dashboard in the space. 
- add `create saved chart` button. This button just brings you to the list of tables page when you click it. This button doesn't disappear as soon as there are saved charts (it persists there).

<img width="815" alt="Screenshot 2022-07-26 at 11 01 26" src="https://user-images.githubusercontent.com/31848148/180969409-cd8f3d99-1aa2-46ca-a70c-6c725e64218f.png">

- clicking on `add saved charts` or `add dashboards` uses the same modal as adding a saved chart in a dashboard:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/31848148/180970021-bdfee6bd-115e-4931-bf12-c16620fd114a.png">

**Comment by rephus** [comment]
is this `add dashboard/charts` suppose dto "move dashboards" from another space into this one ? not sure if that is even more confusing...

**Comment by TuringLovesDeathMetal** [comment]
yep, I'd expect it to do that!

**Comment by TuringLovesDeathMetal** [comment]
@rephus let's ship this to users as-is though and then we can collect feedback and see what folks think! 

I'm sure there will be other changes that we'll need to make too :) But this is a great start!

**Comment by TuringLovesDeathMetal** [comment]
Closing in favour of #2806
