### ISSUE TITLE
Show underlying values for a cell in a table.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2784]
If you click on value (metric or dimension), you can see the most granular details of a given result set, i.e. it shows the un-aggregated view. This feature lets you understand what an answer consists of. 

- [x] This should affect results tables only in both modes - `View` and `Edit`
- [x] Show the right-click context menu with a new option to "View underlying data". This should come before the `Filter` option.
- [x] Add icons to the context menu for `View underlying data` and` Filter by`.
- [x] Opening the window should show the raw data and _not_ the measures. 
- [x] You should be able to download a .csv 

**Rough walkthrough:**
https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=6581%3A81278&scaling=min-zoom&page-id=6581%3A81277&starting-point-node-id=6581%3A81278

**Comment by PriPatel** [comment]
This is the same as https://github.com/lightdash/lightdash/issues/2460 but with a few additions!

**Comment by rephus** [comment]
is this `view underlying data` available for both `dimension` and `metric` columns ? or just dimensions @TuringLovesDeathMetal @PriPatel

**Comment by TuringLovesDeathMetal** [comment]
https://docs.google.com/spreadsheets/d/1xJSTTppJhGAMCs-quHszrZwV5IVa8S116bPS-134-zE/edit?usp=sharing

I think the jist of it is:
- if clicking on a dimension, use all existing filters + add a filter for the dimension’s value you’re clicking on
- if clicking on a metric, use all of the existing filters + add filters for all of the dimensions’ values in the row you’re clicking on.

So, in the example google sheet above:
- If I click on a dimension (for example, `product 1`), then I'd apply all the existing filters + `product_id` = `product 1`
- If I click on a metric (for example, `total revenue`  for `product 3`), I'd apply all the existing filters  + `product_id` = `product 3` and `cost` = `40`.

Does that make sense?
