### ISSUE TITLE
numeric dimensions are treated as categorical on the x-axis (not continuous or discrete)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2790]
### Description

When you put a numeric dimension on the x-axis, it gets treated as a categorical variable, not a discrete or continuous variable. 

What I expect if I have a numeric value on the x-axis:
- by default, the tick values are ordered from decreasing --> increasing on the axis
- the distance between the ticks is equal (e.g. increasing by a value of 1 each tick)

<img width="974" alt="image" src="https://user-images.githubusercontent.com/31848148/181047519-9f16b2b1-3776-4891-bd77-1dc0745e7b97.png">

### To Reproduce

- Click on an explore
- Add a numeric value to the x-axis
- add some metric to the y-axis
- order the values on the x-axis, increasing. 
- see the results 

For example, here, it goes 11, 12, 13, 16 (it skips 3 values on the x-axis).

<img width="957" alt="image" src="https://user-images.githubusercontent.com/31848148/181047795-c259a9b1-4b3f-4219-bc4a-ceedef7eacb7.png">

[source](https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/tables/community_stats_daily?create_saved_chart_version=%7B%22tableName%22%3A%22community_stats_daily%22%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22community_stats_daily_github_stars_added_num%22%5D%2C%22metrics%22%3A%5B%22community_stats_daily_new_twitter_followers_num_total%22%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22community_stats_daily_github_stars_added_num%22%2C%22descending%22%3Afalse%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%5D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22community_stats_daily_github_stars_added_num%22%2C%22community_stats_daily_new_twitter_followers_num_total%22%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22community_stats_daily_github_stars_added_num%22%2C%22yField%22%3A%5B%22community_stats_daily_new_twitter_followers_num_total%22%5D%7D%2C%22eChartsConfig%22%3A%7B%22series%22%3A%5B%7B%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22community_stats_daily_github_stars_added_num%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22community_stats_daily_new_twitter_followers_num_total%22%7D%7D%2C%22type%22%3A%22bar%22%7D%5D%7D%7D%7D%7D)

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal @owlas 

The reason why we force one of the axis types to be 'category' is because of the horizontal bar chart. It doesn't render properly when both axis type are 'value'. 
<img width="1237" alt="Screenshot 2022-08-02 at 15 07 07" src="https://user-images.githubusercontent.com/9117144/182395511-d32b51ba-128e-4a97-960d-1700c2e17eff.png">

You can see this [echarts ticket](https://github.com/apache/echarts/issues/15960) where devs say it is not a bug. If we want to support such use case we need to provide echarts custom render logic.

Low effort option:
Stop forcing type 'category' in one of the axis. Horizontal bar chart will be unusable when using both axis with type 'value'.

High effort option:
Add echarts custom render logic when both axis have type 'value' and chart type is horizontal bar chart.

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 

Just found other problems. When using the bar chart with a category y axis it automatically becomes a horizontal chart.

<img width="1245" alt="Screenshot 2022-08-02 at 16 55 30" src="https://user-images.githubusercontent.com/9117144/182420062-72cdf4f4-fbf1-4d01-8dc3-d0fe7fe62f98.png">

I think the main problem is that we want to treat the horizontal bar chart as a unique chart type when in fact it is a combination of the bar type with flipped axis. We have logic in multiple places in our codebase to handle this behaviour. 

Could we remove the horizontal bar chart option ? Users would just select the bar type and the vertical/horizontal bars would render depending on the types of the fields selected for each axis. 

This way we simplify the codebase and be closer to echarts.

**Comment by TuringLovesDeathMetal** [comment]
awe man, silly echarts. 

I would totally be up for having just bar charts, and having them flip automatically, but I think that most people have been trained to think of them as "different chart types". So I can imagine most people looking for them in the chart types, then asking why we don't have horizontal bar charts. 

Can we force create bar charts with a category y-axis and numeric x-axis? Or does echarts just make this not possible becuase it restricts bar charts to have a numeric y-axis?
