### ISSUE TITLE
Date filter includes future dates

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2793]
### Description

If I select `in the last 30 days` (not completed days) this compiles to >= 30 days ago to the minute but this includes future dates also so it acts as a greater than filter.

**Comment by ZeRego** [comment]
So should also add another filter `< end of current day` ?

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego here's a bit more context:

- in the last 30 days = today and the 30 complete days before it (so 30 and a bit days)
- in the last 30 completed days = not today, only the 30 complete days before it (exactly 30 days until the start of today)

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal cool, we already do it right for the completed days. I just need to add the `< end of current day` when is not completed days.
