### ISSUE TITLE
Refresh session tokens

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#280]
Not sure if this is possible with passport + sessions. But would be good to refresh session tokens on each request to improve security.

**Comment by owlas** [comment]
https://www.npmjs.com/package/keygrip

**Comment by ZeRego** [comment]
I remember seeing documentation for the refresh option so it is possible. If I recall we just need to set a setting to `true` and what is the incremental value ( ex: extend cookie expire date by 1 day )`
