### ISSUE TITLE
:x:  Mysql connector for dbt project.

### ISSUE THREAD

**Issue by dakshlohar1** [lightdash/lightdash#2807]
### Description

Right now I am not able to connect `mysql` database using the `lightdash cli`.
**Please provide a `mysql` connector.**

### What problem does this solve?

**Will be able to connect to Mysql database with `dbt` and `lightdash`.**

> Recreating stale issue #1203 .

**Comment by TuringLovesDeathMetal** [comment]
Closing in favour of #1203 (duplicate)

I've responded to your comments in the other ticket, @dakshlohar1 :)
