### ISSUE TITLE
Lightdash is giving me a blank screen in my `preview` environment

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2824]
### Description

When I click on anything, Lightdash is giving me a blank screen. 

Before this, I had a separate issue which was this:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/31848148/182190423-eeda1579-8ee4-41ef-b0dc-a062f4fb1738.png">

I then logged in again using username + password (I'm assuming I was using env variable + personal access token last time? 🤔 )

Now, `lightdash preview` runs, but when I open it and click on anything, I get redirected to a blank, white screen. 

https://www.loom.com/share/1f410bf2960c41aeb5cf869c66ec8f5b

**Comment by ZeRego** [comment]
Might be related to this error 
`https://sentry.io/organizations/lightdash/issues/3470031061/?project=5959292`
