### ISSUE TITLE
`group` should be unavailable if you only have dimensions in your chart

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2829]
### Description

Grouping doesn't actually work with only dimensions in your chart. This is because in Lightdash, when you hit “group” only the metrics are grouped and in this case there are none.

[See more details in this Slack thread.](https://lightdash.slack.com/archives/C03NLNTT79P/p1659365728657259)

[Here's an example chart](https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/tables/dbt_baskets?create_saved_chart_version=%7B%22tableName%22%3A%22dbt_baskets%22%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22dbt_baskets_basket_item_id%22%2C%22dbt_baskets_basket_total%22%2C%22dbt_baskets_item_price%22%5D%2C%22metrics%22%3A%5B%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22dbt_baskets_basket_item_id%22%2C%22descending%22%3Afalse%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%5D%7D%2C%22pivotConfig%22%3A%7B%22columns%22%3A%5B%22dbt_baskets_item_price%22%5D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22dbt_baskets_basket_item_id%22%2C%22dbt_baskets_basket_total%22%2C%22dbt_baskets_item_price%22%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22dbt_baskets_basket_item_id%22%2C%22yField%22%3A%5B%22dbt_baskets_basket_total%22%5D%7D%2C%22eChartsConfig%22%3A%7B%22series%22%3A%5B%7B%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_baskets_basket_item_id%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_baskets_basket_total%22%7D%7D%2C%22type%22%3A%22bar%22%7D%5D%7D%7D%7D%7D)

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/31848148/182372020-bc7c32b7-0754-4d82-90fa-bcdb9ecc5b99.png">

We want to change the behaviour so that:
- If you have only selected dimensions in your x & y axes, then `groups` gets greyed out with a helpful message: "you need at least one metric in your chart to add a group"

### What problem does this solve?

It's confusing to people why the grouping "works" in the chart config, but doesn't actually do anything.

**Comment by muhsinkamil** [comment]
>It's confusing to people why the grouping "works" in the chart config, but doesn't actually do anything.

Well it's a feature, not a bug 😃 

@TuringLovesDeathMetal Let me try this issue, How about we add a [Callout](https://blueprintjs.com/docs/#core/components/callout) for displaying message ?

**Comment by ZeRego** [comment]
@muhsinkamil callout might take too much space here, what about a [tooltip2](https://blueprintjs.com/docs/#popover2-package/tooltip2) when the input is disabled ?

**Comment by muhsinkamil** [comment]
@ZeRego yep, we can do that. Let me try that out
