### ISSUE TITLE
Error messages don't change when you click refresh dbt or re-run query 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#283]
When you re-run a query or refresh dbt, the red error box doesn't clear or change - so it's unclear if the error is old or a new one that is occurring again. 

<img width="407" alt="Screenshot 2021-07-28 at 13 48 49" src="https://user-images.githubusercontent.com/14341285/127324831-bd9120a9-f262-4638-a998-59a0e4d0351a.png">

We could either clear the error message or add a "new" error box above the previous one if there is a new error on refresh/run query.

**Comment by hamzahc1** [comment]
Correction to this - It seems like error messages do build (see below screenshot) - however seems to only work if the new error is different to the previous one which can be confusing. 

<img width="563" alt="Screenshot 2021-07-28 at 17 24 07" src="https://user-images.githubusercontent.com/14341285/127360074-8ffd07f7-50c4-4bc8-af88-c81a47db76d4.png">

**Comment by ZeRego** [comment]
Possible fix/solution: 
BE can define errors in markdown and then FE can render them properly. This way BE has more control over the error output.

**Comment by owlas** [comment]
I remember I added this logic that if the same error string comes up then the app won't duplicate the toast. 

This was to stop an endless stream of identical toasts. 

But we could just set a max of 5 or something and have it show duplicates

**Comment by ZeRego** [comment]
I think we should also default the messages to disappear after some time
Maybe 5 seconds for successes 10 seconds for errors.

**Comment by TuringLovesDeathMetal** [comment]
split out into: #313 and #315

**Comment by TuringLovesDeathMetal** [comment]
split out into: #313 and #315
