### ISSUE TITLE
Before you add an item into a space, you should be able to see it's current space. 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2839]
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=6189%3A84433

- [ ] Stack results so that `Chart name` is on the first line, and `Space name` (+ left icon)  is on the second line 
- [ ] Ensure that the results dropdown takes up the full width of the search bar (it currently doesnt!) 
- [ ] Repeat for dashboards

**Comment by ZeRego** [comment]
@rephus go for it and see if it breaks something obvious. iirc we added that css mainly for the max-height.

**Comment by ZeRego** [comment]
@rephus I just found a blueprint property `matchTargetWidth ` that might solve this problem and make the menu always match the input.
https://blueprintjs.com/docs/#popover2-package/popover2
