### ISSUE TITLE
ClickHouse support

### ISSUE THREAD

**Issue by toinbis** [lightdash/lightdash#2848]
Would love to see ClickHouse amongst the supported databases. Thanks!

**Comment by TuringLovesDeathMetal** [comment]
@all-contributors add @toinbis for ideas

**Comment by TuringLovesDeathMetal** [comment]
Thanks for opening the issue, @toinbis! we've had a couple of people request ClickHouse support now 👀 it's not something we've planned for the immediate term, but definitely something we'll build in the next 3-6 months

**Comment by phantom943** [comment]
I would also definitely benefit from support for clickhouse!

**Comment by TuringLovesDeathMetal** [comment]
hey @mike-luabase - right now, we're only supporting the verified dbt adapters (see the list here: https://docs.getdbt.com/docs/supported-data-platforms#verified-adapters)

We've had some difficulties in the past with unverified integrations (e.g. issues that are causing bugs in Lightdash aren't being resolved in other repos, so we've had to remove integrations), so we've decide to keep to verified adapter support for now. 

Once Clickhouse is in there, we'll definitely make sure it gets added to the supported warehouses in Lightdash!

**Comment by b-radouani** [comment]
Is there any updates for this subject ? We need a support for clickhouse datawharhouse

**Comment by wasd171** [comment]
@TuringLovesDeathMetal is there any chance of putting unverified integrations behind some experimental flag? I think that focus on stability is completely reasonable, but at the same time experimental flag would
a) Make it clear for the users that YMMV
b) Will help to bridge the gap between verified and unverified adapters in Lightdash

I am sure that in this case people and companies using ClickHouse for their data warehouses could contribute to Lightdash / dbt-clickhouse to make things work for them ;) Otherwise for now there is no incentive for it

**Comment by snikch** [comment]
I agree with @wasd171's sentiment here. It would be great to see an option to opt in to unverified integrations. We're heavy clickhouse users.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as unplanned!

Unfortunately, we still only support dbt-verified adapters with Lightdash. 

WE don't have the capacity to manage adapters that are unverified (even behind an experimental flag). We've been burned a bit before by unverified adapters not upgrading dbt versions quickly enough, so the entire app was blocked from upgrading. 

In the meantime, we support Trino, so you can use this to connect to Clickhouse!

**Comment by msomaschiniiliad** [comment]
Hello, since the last response to this thread it looks like Clickhouse is now listed along side Trino and other verified adapters (now called '[trusted](https://docs.getdbt.com/docs/trusted-adapters)'). Is there any chance for Clickhouse to be supported by Lightdash now?

**Comment by msomaschiniiliad** [comment]
Thanks! 👍
