### ISSUE TITLE
In the 1-click deploy to Heroku, the link to the docs should be earlier in the instructions

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#285]
We link the docs in the last dbt config description - it would be great if they were linked in the description for `DBT_CLOUD_ACCOUNT_ID` :) 

<img width="949" alt="Screenshot 2021-07-28 at 17 30 45" src="https://user-images.githubusercontent.com/31848148/127351230-0f4af4ab-4bb9-42ce-bd2f-4a68540474a0.png">

**Comment by owlas** [comment]
Thanks! Looks like it's alphabetically ordered by default, I'll update this!

**Comment by owlas** [comment]
Closed: https://github.com/lightdash/lightdash-deploy-heroku/commit/61795bb0ad0e17ea0bed37e3a95f69d9aa467c2a
