### ISSUE TITLE
Searching for a value in a group label should open the group label

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2854]
### Description

When you search for a value in the sidebar in the Explore view, if the value exists inside of a group label, the group label should be expanded by default (showing the value being matched)

This is what it's like now:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/31848148/182790023-ca339601-5919-4617-955f-d49cf8fb9d41.png">

This is what I'd expect it to look like:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/31848148/182790106-4fb959bc-0a7e-472c-b1ad-547c5f5f0500.png">

**Comment by ZeRego** [comment]
Let's fix this as part of [#2685](https://github.com/lightdash/lightdash/issues/2685)
