### ISSUE TITLE
In `server not connected` error message, instructions are incomplete

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#286]
When you don't have a browser window open with the dbt cloud developer mode, Lightdash throws an error. 

The error message is good at telling you what's gone wrong, but I think it's just missing a tiny addition :)

- Have the existing message (basically, open your browser). 
- Once your browser is open with dbt cloud, click `refresh dbt`
- ^ I _think_ you might have to actually refresh your browser as well after this step...trying to reproduce the error now, but it's persisting my dbt connection even with the browser shut 😅 

(I kept on trying to refresh the webpage and figure out what was going wrong)

**Comment by hamzahc1** [comment]
Linked to this - a suggestion would be to make the links in the error clickable (open in new tab) to make it bit more decipherable . 

<img width="522" alt="Screenshot 2021-07-28 at 17 21 26" src="https://user-images.githubusercontent.com/14341285/127359753-da335bfa-878d-4bce-9993-41fa5053aa94.png">

**Comment by ZeRego** [comment]
Possible fix/solution for the link in the error messages:
BE can define errors in markdown and then FE can render them properly. This way BE has more control over the error output.

**Comment by ZeRego** [comment]
cc: @TuringLovesDeathMetal @owlas 

Making the urls clickable is possible like I mentioned in the previous comment. 

The tricky part is to display `click the refresh button` message for this specific error since the error messages come from dbt. So we would have to check if the error message contains the text `No server running!` which makes our code really fragile since at any point in time they can change the text.

My suggestion is to show the `After fixing the problem click the refresh dbt button` after any DBT error since it would be useful in those cases and our code with be consistent.

**Comment by TuringLovesDeathMetal** [comment]
+1 that sounds like a really great solution. Elegant, simple. me likey

**Comment by owlas** [comment]
@ZeRego if it helps I actually catch this error and re-raise it with my own error message, I could introduce a new Error type if you want to trigger behaviour for this explicit error

**Comment by owlas** [comment]
https://github.com/lightdash/lightdash/blob/88648f0f1468abbe4120a4a6b4b1235b30293f91/packages/backend/src/dbt/dbtCloudV2RpcClient.ts#L47-L50

**Comment by ZeRego** [comment]
I think this error comes from here:
https://github.com/lightdash/lightdash/blob/88648f0f1468abbe4120a4a6b4b1235b30293f91/packages/backend/src/dbt/dbtRpcClientBase.ts#L153-L156

**Comment by ZeRego** [comment]
>  I could introduce a new Error type if you want to trigger behaviour for this explicit error
But we still need that extra message for any of the dbt errors. Anytime there is a dbt error people need to refresh dbt. Or am I wrong ?

**Comment by owlas** [comment]
Ah I see, for all dbt errors? I'm not sure actually. It would probably be fine but a bit trigger-happy to refresh after these errors come up. Also user may need time to fix them

**Comment by ZeRego** [comment]
WIP branch: https://github.com/lightdash/lightdash/tree/lightdash-286
What is done:
- renders links properly ( we don't need to change anything in the BE for this )  
What is missing:
- show the extra message informing the user to click the refresh dbt button

**Comment by owlas** [comment]
This is even worse now after the most recent release and shows this for me: 
<img width="582" alt="Screenshot 2021-08-05 at 19 57 16" src="https://user-images.githubusercontent.com/11660098/128408763-c1dddba4-9281-4f25-97c2-7181ed9563f9.png">
