### ISSUE TITLE
I'm able to change my x-axis to increasing or decreasing for numerical values

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2878]
### Description

We recently changed numeric x-axis values to be treated as numeric (and not categorical) https://github.com/lightdash/lightdash/issues/2790

The problem with this is if I have numeric x-axis values that I want to sort descending, I can't do this anymore (e.g. number of days remaining in the quarter)

I suggest that we have an option to `sort ascending` or `sort descending` in the x-axis config.

**Comment by rephus** [comment]
@TuringLovesDeathMetal something like this ? 
![image](https://user-images.githubusercontent.com/1983672/183606213-8a2e425c-a115-4265-9615-39b7052194d6.png)
