### ISSUE TITLE
default otka endpoints are wrong for certain okta orgs

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2886]
### Description

Lightdash appends `/default` to the auth_url, token_url, and userinfo_url in the openid connect settings. This is only needed for Okta users with custom authorisation servers.

For other users it should be:

```
auth_url: https://<myco>.okta.com/oauth2/v1/authorize
token_url: https://<myco>.okta.com/oauth2/v1/token
user_info_url: https://<myco>.okta.com/oauth2/v1/userinfo
```

**Comment by swiftsam** [comment]
Our team is potentially interested in submitting a PR for this issue. Seems like a good candidate for external contribution in that it could be relatively simple and we're motivated to get it working for our Okta config. Would that be helpful?

**Comment by owlas** [comment]
Hey @swiftsam Yes that sounds good! From what I can tell the base url for the auth, token, and user_info urls are issuer_url. Do you know if that's right?

The best way to do this would be to look at the previous PR and see where the configuration is set.

Let me know if you want to pair on it!
