### ISSUE TITLE
I want to be able to toggle on/off column totals in view mode for a table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2889]
### Description

We made it so that you can turn off column totals for a table: https://github.com/lightdash/lightdash/pull/2888#pullrequestreview-1065041461

This is great, because a bunch of columns don't make sense with totals. 

But, now that this is a default-off feature, someone might want to be able to see a total in view-mode and that's not really possible. 

I think it would be really useful if we had the `column totals` toggle beside the `export as` option in teh view mode:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/31848148/183411082-3aeedc37-b904-4629-b715-78f027f74abf.png">

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal - What if you wanted the total shown for 1 column but not another in the same results table?

**Comment by TuringLovesDeathMetal** [comment]
That's not possible right now. Do you think it should be? (or can you give an example of where you'd want that to happen)?

**Comment by hamzahc1** [comment]
See message in Slack from a user: https://lightdash.slack.com/archives/C03SB7JSGMC/p1660064917708449?thread_ts=1659991200.521939&cid=C03SB7JSGMC

**Comment by TuringLovesDeathMetal** [comment]
ah, got it. I think that's solved by this issue! https://github.com/lightdash/lightdash/issues/2922
