### ISSUE TITLE
Make empty dashboard state more helpful

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2891]
On creating a dashboard from scratch, the empty state could be more helpful. Currently, it shows a prompt to "Edit dashboard" to add a tile. If I am creating the dashboard first, to then add charts into, then it would be much easier if there was a "new chart" button or something to that effect. Currently, it is not obvious that the next step would be clicking "Explore" --> "Tables" to start creating a chart.

I imagine something designed similar to the empty state we have now, but with an additional box in the centre prompting you to create a new chart. This would link you to the table explore view. 

![image](https://user-images.githubusercontent.com/9979944/183427660-a7cdcb29-e488-42e7-8279-fb9fc9b46f67.png)

**Comment by TuringLovesDeathMetal** [comment]
duplicate of #3017
