### ISSUE TITLE
Update "includes" to "contains" in filter conditions.

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#2893]
Nearly every other filter condition input box uses "contains". I am not aware of any reason we should use "includes" instead. I guess that we got it from the js method `.includes()` (which serves a similar purpose!)?

There is extra cognitive overload when you don't see something you expect as a user - and with filter conditions being common across software/web, it's important that we follow convention.

**Comment by TuringLovesDeathMetal** [comment]
weirdly I actually thought the exact same thing today! I had to re-scan the options to try to find `contains`

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this because I think it's not going to happen 😅 if a bunch of other people complain, then maybe we change it!
