### ISSUE TITLE
Dashboards can be exported

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2895]
### Description

- Dashboards can be exported as an image (same file type as in email scheduled deliveries)
- You can access the dashboard export action from the three-dot-menu on the dashboard
<img width="321" alt="image" src="https://user-images.githubusercontent.com/31848148/220655934-f8ed1e62-f8a0-44b8-9562-4a9b2b3c2607.png">

- The name of the exported file is the title of the dashboard (I think we can keep the whitespace? Or maybe replace the whitespace with `-` and remove any special characters that aren't alphanumeric? I'll leave this up to whoever implements this to play around with 👀 )
- Viewers, Editors and Admins can export dashboards.

**Comment by TuringLovesDeathMetal** [comment]
^Ya, I feel like let's keep it simple for now and do that? 

Also, let's remove the option for PDF (if that's too difficult, like you mentioned). 

I've also removed the requirement for charts splitting across pages

**Comment by 12ian34** [comment]
not stale, requested by a customer!
