### ISSUE TITLE
Ability to pivot the results table in the Explore view

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2906]
### Description

The user should be able to pivot the results table in the explorer by a dimension. For details on pivoting see #1184 and #2905 

This allows the user to sort interact with pivoted tables such as: 
* Drill down
* adding filters
* Sorting
* Re-ordering columns

**Note:** One thing this also does is it fills in empty values. For example, if I have data that looks like this:

<img width="1533" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/43200428-1d54-4623-99e2-ab5c2c5c525a">

You can see in my results table that there are no `empty` values, but in the pivoted table visualization, there are. 

This solves an issue if users can actually interact with these pivoted, empty values. 

For example, if I have a cumulative total, I want the cumulative total to still appear even for values where there is no row. 

E.g. if you imagine that I have a time series with cumulative sales split by country. Even if there are no sales in the current month in Canada, but historically, there was $5000 in sales, I would want that $5000 to be carried over to the latest month. Instead, with the current set up, the value is shown as empty on the chart (because there's "no value" to plot).

<img width="1125" alt="Screenshot 2024-04-04 at 09 43 22" src="https://github.com/lightdash/lightdash/assets/31848148/e680cc61-419f-4828-bd3c-3932b1ba3a3f">

**Comment by Kobold** [comment]
Not stale.

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned. 

We are planning to migrate the existing explorer to behave more like the new SQL runner chart results table and this pivoting in the results table is already included in there.
