### ISSUE TITLE
Only show the table name in the 'Results Table', if there are joins

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2909]
To reduce clutter, there is no need to show the `Table name` before the `field name` if the Explore is only made up of one table. 

![image](https://user-images.githubusercontent.com/12776522/183696577-62a9baeb-cce3-4be4-8927-c9761d692249.png)

**Comment by rephus** [comment]
Do you mean if there are joins in the Resulting SQL or in the expore? eg: Would you expect to see `tablename` on this Results table if I make a request to only payment fields ? (payments explore has 2 joins) 

![image](https://user-images.githubusercontent.com/1983672/185873577-1164f0f5-1b60-4ebf-9de1-370c511b7a34.png)


I also assume you want this to be applied to `table viz` `table results` and `underlying data table`

**Comment by PriPatel** [comment]
@rephus  Definitely the explore, so that you don't get confused!
