### ISSUE TITLE
Update styling on Column headers when there is a join

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2911]
<img width="1170" alt="Screenshot 2022-08-09 at 18 02 50" src="https://user-images.githubusercontent.com/12776522/183712923-242a6657-550c-4045-8b60-9943006a770f.png">

Reduce font-weight of Table name and separate with a dash. This should be done after #2909

**Comment by rephus** [comment]
https://github.com/lightdash/lightdash/issues/2909 is merged, you can do this now @IrakliJani
