### ISSUE TITLE
Update the appearance of the chart and dashboard components in Spaces

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2914]
- [ ] Display them in table format, where the user can sort by name and time/last modified. We may need to experiment with column widths a bit. 
- [ ] Add chart / dashboard icons
- [ ] Remove the chart/dashboard description icon from these components. Instead, show the descriptions on hover of the component.

<img width="565" alt="Screenshot 2022-08-23 at 02 17 49" src="https://user-images.githubusercontent.com/12776522/186046978-20af0830-d38d-44a0-8f48-2cd19e90382c.png">

https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=6801%3A80773

**Comment by PriPatel** [comment]
@IrakliJani Im going to say we should remove it as we have global search!

**Comment by IrakliJani** [comment]
good 👍🏻
