### ISSUE TITLE
Upgrade dbt to 1.2.0

### ISSUE THREAD

**Issue by lyogev** [lightdash/lightdash#2918]
Unable to run lightdash on top of jaffle_shop_metrics:
https://github.com/dbt-labs/jaffle_shop_metrics/

I tried to downgrade the project's version but some of the features used there are unsupported by previous DBT versions.

I think lightdash on top of dbt-metrics can be a huge win for lightdash.

**Comment by owlas** [comment]
Hey @lyogev - thanks we've just opened a PR for this.

Lightdash does support dbt metrics! https://docs.lightdash.com/references/metrics#2-using-dbts-metrics-tag

**Comment by owlas** [comment]
Blocked by https://github.com/databricks/dbt-databricks/issues/127
