### ISSUE TITLE
Only include totals for dimensions, counts, and sums

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2922]
### Description

Only include totals in table visualizations + the results table for dimensions, counts, and sums. 

### What problem does this solve?

Totals for % metrics or average metrics don't make sense.

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal I don't know how I feel about this. Feels like we are being too opinionated and still keep assumptions 🤔 

Isn't it a valid case to have a % metric and see a 100% as the total ?

imo, we need a opt-in/out in the yml. So people can control their use case.
