### ISSUE TITLE
Broken chart when a selected field is no longer in the dbt yml

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2924]
### Description

There is no way to edit a chart and remove the field that no longer exist in dbt yml.

<img width="1680" alt="Screenshot 2022-08-10 at 14 17 40" src="https://user-images.githubusercontent.com/9117144/183911650-cc6b89be-ef30-4ebf-91a6-5b15a83da4fb.png">
<img width="1666" alt="Screenshot 2022-08-10 at 14 17 56" src="https://user-images.githubusercontent.com/9117144/183911670-5f5d9fc1-a191-45af-9ce8-4b218690417a.png">

### To Reproduce

1. Create chart with dimension X
2. Remove dimension from dbt yml
3. Click 'refresh dbt'
3. See error

### App Version

0.209.3

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego if I rename something in dbt, but I want it to not break my charts/dashboards, would there be some way of specifying an `alias` in the dbt .yaml file? 

E.g. I rename `user_id` to `user_identifier` in my underlying dbt model:

```
columns:
  name: user_identifier
    meta:
      dimension:
        alias: user_id
```

^If the alias was used somewhere in a query, then it would still run. 

Does that make sense? Basically it gives users the flexibility to rename things in dbt without it breaking in Lightdash

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal Not without a big refactor as our codebase relies on a 1 to 1 mapping. We would have to change everything to have a 1 to many mapping. 
Independently of that, the UI needs to have an option to remove the invalid fields because we can't guaranty they would use alias of if they actually removed the field from dbt.
