### ISSUE TITLE
Renaming Spaces from home modal only affects last Space

### ISSUE THREAD

**Issue by swiftsam** [lightdash/lightdash#2936]
### Description

When renaming a Space from the project home page, the `Edit Space` --> `Rename`  modal is always populated with and updates the last Space, regardless of which Space was clicked on.  

When renaming the name of a space from the /spaces/ page, the rename works as expected. 

https://user-images.githubusercontent.com/658203/184274775-46042a8c-f16f-47f9-8bef-5f781d0b8e39.mov

### To Reproduce
- Create a space (`Space A`)
- Create another space (`Space B`)
- From the project home page, click the three-dot menu of (`Space A`)
- Choose `Rename Space`
- Note: the text input is populated with the name of `Space B`
- Update the text and click `Update`
- Note: the name of `Space B` is now updated

### App Version

Observed on version v0.209.3.  I know that's not quite latest, but I checked the changelog and didn't see any changes that seemed relevant. 

I searched open issues, recent PRs, and the slack community for "Spaces", and "rename Spaces" and couldn't find any clues that this was already identified. Let me know if I can help further reproduce or anything

**Comment by TuringLovesDeathMetal** [comment]
Thanks for opening the issue @swiftsam ! we'll take a look at it today 👀

**Comment by swiftsam** [comment]
Wow, so fast, thank you!
