### ISSUE TITLE
Fields sidebar - Stress test long table names 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2939]
![Screenshot 2022-08-12 at 12 50 28](https://user-images.githubusercontent.com/12776522/184370597-5638539d-95c7-4e36-80de-e5f1b513b284.png)

- [ ] `All tables` names should not span 2 lines. Table name should be truncated.

**Comment by ZeRego** [comment]
Related issue in blueprint https://github.com/palantir/blueprint/issues/4946
