### ISSUE TITLE
When you switch the timestamp filter type the value changes to now

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2953]
### Description

When I change the value of a timestamp filter from "equals to" to "on or after" it resets the value to the current time in UTC

![Aug-15-2022 15-48-09](https://user-images.githubusercontent.com/11660098/184658089-847cb9c3-01c9-44fd-b470-3f0e4eecb85e.gif)

**Comment by rephus** [comment]
This is also happening on all DATEs and all Filter operators
![Peek 2022-08-25 15-20](https://user-images.githubusercontent.com/1983672/186675849-845e3c1f-68bb-4625-b5c2-f9b0fb7cf973.gif)

**Comment by rephus** [comment]
Also happening for other non-date types... basically the value is always resetted
![Peek 2022-08-25 15-31](https://user-images.githubusercontent.com/1983672/186678149-0bca4111-f5a0-445b-bdbc-09d981cdacf2.gif)
