### ISSUE TITLE
Add project type to project-related events

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2955]
### Description

When we create a project, we don't send hte project type information to Rudderstack/BigQuery. We want to do this so we can tell which projects are development vs. default project types. 

Right now, we also don't trigger a backend event for `project created` with projects created using the CLI. This is _**good**_ because it keeps the `project created` event quite "clean" with actual projects. 

Is there any way to create different events depending on the `project type`? 

e.g. The preview ones have the prefix `preview` in their event names:

`lightdash_server_preview_project_created`, `lightdash_server_preview_project_deleted`

**Comment by rephus** [comment]
@TuringLovesDeathMetal do you prefer a separate event for `preview_project.created` ? or just an extra flag to existing project.created with `isPreview=true` ?

**Comment by TuringLovesDeathMetal** [comment]
ya, I think that's fine - I can just "make" them into separate events in the data models :) (i.e. filter by preview vs. non-preview project created and create two base tables for this)
