### ISSUE TITLE
Remove table information dropdown in the 'Fields sidebar'

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2963]
The table information dropdown in the Fields sidebar which shows `Schema`, `database`, `description` and sometimes `lineage` doesn't feel useful at the stage where the user is picking fields and building a query. This information should be shown in the Tables sidebar instead, where a user might browse through table information before picking one. 

- [ ] Remove table information dropdown in the 'Fields sidebar'
<img width="401" alt="Screenshot 2022-08-16 at 15 33 21" src="https://user-images.githubusercontent.com/12776522/184913246-b1ebc1c7-8e7a-4eb1-89b4-cf84596f88e6.png">

- [ ] Show table `description` in the Table sidebar on hover in a tooltip. We don't need to show `schema` or `database`

<img width="372" alt="Screenshot 2022-08-19 at 10 25 00" src="https://user-images.githubusercontent.com/12776522/185588582-dea92723-d991-43da-98de-1ccb6538705f.png">

what do you think? @owlas @TuringLovesDeathMetal

**Comment by owlas** [comment]
I think the table location (database, warehouse, schema) is fairly useless to the end user as is the lineage. I think the explore description could be useful!

**Comment by PriPatel** [comment]
Nice! So description on hover? 
That could work nicely. Fewer clutters <3

**Comment by owlas** [comment]
beautiful
