### ISSUE TITLE
Stacking doesn't automatically update with new group values

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2972]
### Description

In a stacked bar chart, if a new `group` appears in my data, the new group isn't included in the stack, it's included outside of the stack. 

I edited + saved the chart before I took a video 😢 so this isn't a complete example, but in here, you can see what the chart looked like on the dashboard. Then, when I opened it, I had to click `no stack`, then `stack` to reset the stack to include the new groups. 

https://www.loom.com/share/da6e8f1474324e64a0e62f9bc89b7b14

**Comment by rephus** [comment]
Not exactly sure how to replicate this... 
![Peek 2022-08-25 08-54](https://user-images.githubusercontent.com/1983672/186595844-25fd4e01-a65a-4d73-93e2-db2b83ce1607.gif)

**Comment by TuringLovesDeathMetal** [comment]
ya, it's tricky. 

You'd need to:

1. create a chart that has a grouped value in it (e.g. the `orders - status`) and make it `stacked`
2. save the chart
3. add a group to your grouped value in your data model (i.e. in dbt, add another status type, like `withdrawn`)
4. go and look at your chart (`withdrawn` should be unstacked)

**Comment by rephus** [comment]
This bug makes it hard to test it https://github.com/lightdash/lightdash/issues/3076

**Comment by rephus** [comment]
I am still unable to replicate this... 
![Peek 2022-08-25 15-03](https://user-images.githubusercontent.com/1983672/186674181-75cdf963-bc14-4c49-a261-b7a2682ed1b1.gif)
