### ISSUE TITLE
Add analytics events for permissions

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2980]
### Description

- Webapp events for people interacting with the permissions page (how many people are clicking on the `permission_updated` in the settings sidebar?)

- I'd love to have a server event which is `permission_updated` which is triggered whenever a user's permissions is updated. This would happen when a user was _**created**_ and when a user's permissions were updated after that. It would include:
      - the user_id of the person updating the permissions (`user_id`)
      - the user_id of the person whose permissions was updated (`user_id_updated`)
      - the new org-level permissions of the user (`organization_permissions`)

- a "nice to have" would be just a json blob of the user's permissions, like this: 

```
{
  user_id: my_user_id,
  organization_permissions: editor,
  project_permissions: {
    name: lightdash_analytics
    role: editor
    spaces:
      {
        name: kts_kewl_space
        role: editor
      }
    katie_dev: admin
  }
}
```

**Comment by rephus** [comment]
Is this for `org permission levels` ? do we want to create a different event for `project level permissions` or maybe a flag ?

**Comment by rephus** [comment]
I don't think this makes any sense, we don't have space permission levels yet 

```
    spaces:
      {
        name: kts_kewl_space
        role: editor
      }
      ```
