### ISSUE TITLE
Implement nested filter on querybuild for metrics

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#2981]
### Description

I initially implemented nested filters for dimensions , then I did it for metrics, but it was not working as expected (was breaking dashboards with a `)` syntax error)  https://github.com/lightdash/lightdash/pull/2970

So I reverted the metric nested filter https://github.com/lightdash/lightdash/pull/2979
and the empty list of filters #2984

Figure out what was wrong in the metric impelementation and do it right

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned - we have nested flters now, so I'm assuming this works as expected?
