### ISSUE TITLE
oauth via glcoud doesn't work with lightdash (for BigQuery users)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3]
currently, if a user is using BigQuery and has their dbt profile set up with oauth via gcloud, lookdash will fail. 

The work around is [quite complex for this](https://app.gitbook.com/@ligthdash/s/lightdash/faqs#i-have-a-bigquery-service-account-that-i-use-to-connect-to-my-database) (and requires users to have a service account/know where to find it). 

It would be great if lookdash "just works" for users with oauth via gcloud.

<img width="827" alt="Screenshot 2021-05-18 at 15 58 24" src="https://user-images.githubusercontent.com/31848148/118674407-0d6ebc00-b7fa-11eb-8f1a-518ea9859dfd.png">
<img width="938" alt="Screenshot 2021-05-18 at 16 10 59" src="https://user-images.githubusercontent.com/31848148/118674425-0fd11600-b7fa-11eb-87e7-96d0fe28ca5e.png">

**Comment by owlas** [comment]
Cool, I think we can get this to work by bundling `gcloud` into the docker image and asking bigquery users to mount their gcloud config

**Comment by owlas** [comment]
Fixed on `main`
