### ISSUE TITLE
Improve contributing guide

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#300]
* [ ] how to fork - edit - open PR - rebase on upstream - force push - merge
* [ ] do not change documentation slugs in docs PRs 
* [ ] username and password for running locally (and more about seed data)
* [ ] cloning with submodules and updating submodules (for jaffle shop dbt project)

From @ZeRego:

Commands I have been using to run docker in dev mode
start:
`sudo docker compose --env-file ./docker/.env.dev -f ./docker/docker-compose.dev.yml up --detach --remove-orphans`
destroy:
` sudo docker compose --env-file ./docker/.env.dev -f ./docker/docker-compose.dev.yml down
`

**Comment by ZeRego** [comment]
Some other topics we can cover:

- changing the DB 
  - how to create/rollback/migrate knex
  - how to seed data
- mention that contributors need to update the CHANGELOG.md

```
// create new migration file
cd packages/backend/src/database
knex migrate:make migration_name 
// rollback just 1 migration
knex migrate:down
// migrate to latest
knex migrate:latest
```

**Comment by TuringLovesDeathMetal** [comment]
Update the core contributing guide:

 - [ ] Break large document down into smaller documents
 - [ ] Add notes from @rephus 's onboarding
 - [ ] @ZeRego add notes about tracking events

**Comment by TuringLovesDeathMetal** [comment]
@owlas @ZeRego is this issue still relevant?
