### ISSUE TITLE
When you add a file to the connections page, it should tell you that the file has been uploaded

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3003]
### Description

When you upload a file to the connections page, it should tell you that the file has been uploaded successfully + the name of the file.

Something like this: 
![image](https://user-images.githubusercontent.com/31848148/185590561-dba49e4b-8340-421a-b904-e5ff97106f78.png)

or like this:
![image](https://user-images.githubusercontent.com/31848148/185590596-68320247-1035-45b6-8ee3-af435858fe41.png)

at 2:22:
https://www.loom.com/share/03803a30331548d2b98d3a2ee35f5414

**Comment by muhsinkamil** [comment]
Hey @rephus / @TuringLovesDeathMetal , Can I take this up

**Comment by TuringLovesDeathMetal** [comment]
@muhsinkamil totally! go for it :)
