### ISSUE TITLE
Improve clarity of the "Create dashboard" flow

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#3012]
### Description

We've had feedback that the "add a dashboard" flow, e.g. from the homepage of a space is confusing.

When you select "Add a dashboard", you get this:

![image](https://user-images.githubusercontent.com/9979944/185614499-311d4b8b-f1a4-4d84-8163-5f3728499fb3.png)

Without thinking, it's easy to just assume that the text box is just for entering the name of the new dashboard, when in fact, it is a search box for existing dashboards to be added to the Space. The "Create new dashboard" button below isn't very prominent. 

It would be great to reduce the friction in this flow, whilst fulfilling both use cases: 1. adding an existing dashboard to a space and 2. creating a new dashboard for the space.

### What problem does this solve?

Improving the flow here would reduce the friction involved with creating/adding a dashboard into a space.

**Comment by 12ian34** [comment]
Some options to start off with:
- on the space homepage, perhaps we could have two buttons, one for "Move a dashboard to this space" and another for "Create a new dashboard within this space". Perhaps this is visual overload, but at least it would be more clear.
- Keep the current "add dashboard" button, but the modal that pops up should only present you with two equally standing out options "create new dashboard" and "add existing dashboard", and depending which one you select, you are shown either a search input box or the dashboard name input box.

**Comment by TuringLovesDeathMetal** [comment]
^Pedram did exactly this too when he opened the `add dashboard` box!

**Comment by TuringLovesDeathMetal** [comment]
This has been fixed
