### ISSUE TITLE
When I create a dashboard, I should be redirected to it, open in `edit` mode

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3016]
### Description

When I create a new dashboard, the first thing I'm going to want to do is edit it. 

Clicking `create new dashboard` should create a new dashboard, redirect me to that new dashboard, opened in `edit` mode.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/31848148/185629659-7051ee65-845b-453a-867f-ce95e421128d.png">

**Comment by chavda-bhavik** [comment]
@TuringLovesDeathMetal I would like to work on it. Is this issue still relevant?

**Comment by TuringLovesDeathMetal** [comment]
@chavda-bhavik, sorry was on holidays. Yep, go for it!

**Comment by rephus** [comment]
This is how it works when we create a dashboard from `spaces` and from `dashboards` . Are we missing any other ? 

[Screencast from 07-12-22 12:20:33.webm](https://user-images.githubusercontent.com/1983672/206166417-1f3fc738-87f6-4190-9847-f54c71f218a2.webm)
