### ISSUE TITLE
Date filtering not working for `in the last` filter but working for `is equal to` filter

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3034]
### Description

I tried to filter my `week` dimension using the `in the last` filter and there's some problem with casting. But, if I try filtering using `is equal to`, it works fine

### To Reproduce

[here's the link to the chart. ](https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/saved/48319e16-df47-4b91-846b-8efa1cac08f3/view)

https://www.loom.com/share/54d2fb925a3b4084b1c227e0b23f4b49

**Comment by rephus** [comment]
Chart does not exist

**Comment by rephus** [comment]
I don't see anything bad here... I'm testing against my own dataset (jaffle shop doesn't have recent dates so it is harder to test) 

In here I'm filtering `week` in the last `1 week` so it is showing data from Sunday 21st (this week) until now (not 7 days) 
![image](https://user-images.githubusercontent.com/1983672/186599476-e29638f6-ac08-45dd-af0c-143e02b0a365.png)

If I'm filtering by last 1 completed weeks, it will show 7 days from last week 

![image](https://user-images.githubusercontent.com/1983672/186599829-fd634bee-1f19-4f4d-9394-d1a76e9d6d88.png)

It's true that this behaviour changes depending on the field `day or timestamp` does something different, but that's kind of expected given the data (already casted) I think. 

Am I missing something ?

**Comment by TuringLovesDeathMetal** [comment]
hmmmm, I think it might just be for hte `pages` table in our instance 🤔 I'll look into the date types in there and see if I can find anything fishy
