### ISSUE TITLE
SQL runner errors on the second run

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3055]
### Description

SQL runner errors on the second run

### To Reproduce

1. go to Sql runner
2. select "Orders" table and click "run query"
3. click "run query" again"
4. 💥 

> NOTE that some tables do not fail.

https://www.loom.com/share/07d326f5ef094d748bc6f59fad91aefb

### App Version

v0.224.0+

**Comment by rephus** [comment]
Damn, another displayName error, I think it is related with pivots . 
This could fix it: #3011
Similar ticket : https://github.com/lightdash/lightdash/issues/3039
