### ISSUE TITLE
On SQLRunner table viz is grouped and can't be configured

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3059]
### Description

![image](https://user-images.githubusercontent.com/1983672/186167388-2449ccb1-cfc1-4579-95f4-ee825006110f.png)

I don't think we should default to pivot tables on sqlrunner ...

### To Reproduce

1- go to sqlrunner
2 - select orders
3- run query
4- select table viz
5- get pivot table that can't be configured

### App Version

v0.227.0

**Comment by rephus** [comment]
@TuringLovesDeathMetal pivots are shared between charts and tables, I could remove pivots completely on sqlrunner, but this will also affect default charts... is that ok ? can you think of another solution ?

**Comment by TuringLovesDeathMetal** [comment]
Ya, let's do it.

I think we're going to remove pivots from the default charts in the Explore view in the coming weeks because once we make pivots + grouping match between the results table + the charts config it'll be a bit wild to automatically pivot the results table.
