### ISSUE TITLE
Make it clearer when results are truncated (row limit results table)

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#3067]
### Description

A user has highlighted a usability issue with the results limit for tables. When you run a search, there is a default limit of 500 records returned. Quote:

>One different idea I had is around the limiting. Often I am not aware that there is a limit of 500 (I mean I just forget about it, as I don’t have to actively set a limit). Do you think it make sense to have some indication that if the number of returned rows equals the limit there is a little notification next to the limit field that states that the results are truncated? It would avoid people making an analysis and then not knowing they are getting the incomplete results because they weren’t aware of the limit (edited) 

Taking a look at the screenshot below, it is indeed not super obvious that the results are being limited to only 500 records and that there are more records hidden from the table.

Perhaps we could add a badge when the number of records returned is over the limit.

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/9979944/186424766-34635759-f96f-46b3-a68d-8081a1c7db95.png">

### What problem does this solve?

It's easy to miss important data out of tables when the number of records available is greater than the limit - which isn't shown to the user in a clear way.

### Acceptance criteria

- [ ] move the run query button to the bottom left in the explore view 

![Image](https://github.com/lightdash/lightdash/assets/31848148/81f52acd-7ca4-422c-a598-edbce57909b2)

design: https://www.figma.com/proto/btY2rdBe5I2W4xLR3upmQG/Untitled?type=design&node-id=1062-72152&t=5Gv2mTts6ipwIPxo-0&scaling=min-zoom&page-id=1062%3A71863&starting-point-node-id=1062%3A72152

- [ ] alert the users if the number of rows = the limit
- [ ] WE know that this will show the wrong notificaiton if you have exactly the number of rows as the limit, but that's fine. 
- [ ] The warning could be "The number of results is bigger than the limit you've set - there may be results that are missing"
- [ ] Show the warning message by/beside the limit so that it's obvious where to go interact with it to change it

**Comment by 12ian34** [comment]
related: https://github.com/lightdash/lightdash/issues/1908

**Comment by 12ian34** [comment]
Yes, still relevant!

**Comment by PriPatel** [comment]
+1 
This was bought up by another user!

**Comment by PriPatel** [comment]
Do we know the number of total results at this point? Could we do something like `Showing XX of XXX results`?
