### ISSUE TITLE
Stacking bar chart shifts the X axis values

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3076]
### Description

We can't stack correctly Stack charts when x-Axis are numbers (Ids) 

![Peek 2022-08-25 13-48](https://user-images.githubusercontent.com/1983672/186658095-96b0e5e8-cc01-4dfc-9704-5741198d66d1.gif)

This can be replicated on [demo](https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/tables/dbt_orders?create_saved_chart_version=%7B) or [analytics](https://analytics.lightdash.cloud/projects/d4a98e19-d9a3-4bed-8e7b-c07af3e42686/tables/stg_orders?create_saved_chart_version=%7B"tableName"%3A"stg_orders"%2C"metricQuery"%3A%7B"dimensions"%3A%5B"stg_orders_order_id"%2C"stg_orders_status"%5D%2C"metrics"%3A%5B"stg_orders_order_id_count_distinct"%5D%2C"filters"%3A%7B%7D%2C"sorts"%3A%5B%7B"fieldId"%3A"stg_orders_order_id"%2C"descending"%3Afalse%7D%5D%2C"limit"%3A500%2C"tableCalculations"%3A%5B%5D%2C"additionalMetrics"%3A%5B%7B"name"%3A"order_id_count_distinct"%2C"label"%3A"Count+distinct+of+Order+id"%2C"description"%3A"Count+distinct+of+Order+id+on+the+table+Stg+orders.+Lightdash+has+created+this+metric+automatically."%2C"table"%3A"stg_orders"%2C"sql"%3A"%24%7BTABLE%7D.order_id"%2C"type"%3A"count_distinct"%7D%5D%7D%2C"pivotConfig"%3A%7B"columns"%3A%5B"stg_orders_status"%5D%7D%2C"tableConfig"%3A%7B"columnOrder"%3A%5B"stg_orders_order_id"%2C"stg_orders_status"%2C"stg_orders_order_id_count_distinct"%5D%7D%2C"chartConfig"%3A%7B"type"%3A"cartesian"%2C"config"%3A%7B"layout"%3A%7B"xField"%3A"stg_orders_order_id"%2C"yField"%3A%5B"stg_orders_order_id_count_distinct"%5D%7D%2C"eChartsConfig"%3A%7B"series"%3A%5B%7B"type"%3A"bar"%2C"encode"%3A%7B"xRef"%3A%7B"field"%3A"stg_orders_order_id"%7D%2C"yRef"%3A%7B"field"%3A"stg_orders_order_id_count_distinct"%2C"pivotValues"%3A%5B%7B"field"%3A"stg_orders_status"%2C"value"%3A"returned"%7D%5D%7D%7D%2C"stack"%3A"stg_orders_order_id_count_distinct"%7D%2C%7B"type"%3A"bar"%2C"encode"%3A%7B"xRef"%3A%7B"field"%3A"stg_orders_order_id"%7D%2C"yRef"%3A%7B"field"%3A"stg_orders_order_id_count_distinct"%2C"pivotValues"%3A%5B%7B"field"%3A"stg_orders_status"%2C"value"%3A"completed"%7D%5D%7D%7D%2C"stack"%3A"stg_orders_order_id_count_distinct"%7D%2C%7B"type"%3A"bar"%2C"encode"%3A%7B"xRef"%3A%7B"field"%3A"stg_orders_order_id"%7D%2C"yRef"%3A%7B"field"%3A"stg_orders_order_id_count_distinct"%2C"pivotValues"%3A%5B%7B"field"%3A"stg_orders_status"%2C"value"%3A"return_pending"%7D%5D%7D%7D%2C"stack"%3A"stg_orders_order_id_count_distinct"%7D%2C%7B"type"%3A"bar"%2C"encode"%3A%7B"xRef"%3A%7B"field"%3A"stg_orders_order_id"%7D%2C"yRef"%3A%7B"field"%3A"stg_orders_order_id_count_distinct"%2C"pivotValues"%3A%5B%7B"field"%3A"stg_orders_status"%2C"value"%3A"shipped"%7D%5D%7D%7D%2C"stack"%3A"stg_orders_order_id_count_distinct"%7D%2C%7B"type"%3A"bar"%2C"encode"%3A%7B"xRef"%3A%7B"field"%3A"stg_orders_order_id"%7D%2C"yRef"%3A%7B"field"%3A"stg_orders_order_id_count_distinct"%2C"pivotValues"%3A%5B%7B"field"%3A"stg_orders_status"%2C"value"%3A"placed"%7D%5D%7D%7D%2C"stack"%3A"stg_orders_order_id_count_distinct"%7D%5D%7D%7D%7D%7D)

### App Version

0.233.1 

I rolled back (including dependencies) to version 
[0.226.1](https://github.com/lightdash/lightdash/commit/56ecf64756a54d27fb7090f16f9b562343d97be8) and it was still happening... :/

**Comment by rephus** [comment]
This is an open issue in echarts about this, I added a comment to their thread. There is not much we can do unless we want to apply Max value to xAxis : https://github.com/apache/echarts/issues/17522#issuecomment-1231466022

**Comment by TuringLovesDeathMetal** [comment]
going to close this as not planned (hasn't been flagged by users and hasn't had activity in over 2 years)
