### ISSUE TITLE
1. `lightdash deploy` should work if there are no projects in the connected instance

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3077]
### Description

Right now, if I have an organization with no projects, I can login to the CLI and run `lightdash preview` and get a preview of my local dbt project available in Lightdash. 

But, if I try to do `lightdash deploy`, it errors. 

I want to be able to run `lightdash deploy --create` and this would create a Lightdash project for me in my connected organization.

This is what I'd expect it to be like:

```shell
$~ lightdash deploy --create
Add a project name or press enter to use the default: [Tasteful Toad] # there would be an auto-generated name like we have now for projects that people can just press `enter` to accept

✅ Your project Tasteful Toad is ready at: https://app.lightdash.cloud/projects/my-project-id/tables
```

**Comment by ZeRego** [comment]
Suggestion, have a new project type `none` when creating a project from the cli. This is going to help us show a message in the UI for https://github.com/lightdash/lightdash/issues/3092
