### ISSUE TITLE
Add onboarding screen when first project is deployed

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3082]
### Description

Once a user has deployed their first project, we should send them to this onboarding screen:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/31848148/186675609-02f7817a-aea6-4d48-a4a7-297e4da5e9c7.png">

see the full flow outlined here: https://miro.com/welcomeonboard/SDAwYWZQUXg5N1dCbWZLeHd3d3N0R0ZqZEgxSk9VbW15Wk91RVhaWVpJQ3J2anBjdUVMb2haQXZneUxRZE9zNXwzNDU4NzY0NTE2NDE1MzI5MTg3?share_link_id=94182932101

**Comment by ZeRego** [comment]
FE can use polling to fetch all projects in the org until it gets a non empty array.
