### ISSUE TITLE
Table chart in dashboard returns no results but looks ok on Explore

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3083]
### Description

Another potential performance issue. 

A table chart, no pivots, with 10K row limit, looks ok (and it seems fast) on explore. 

However, the same chart on dashboard returns no results. Changing the row limit from 10k to 500 fixes th eissue though. 

 I could be related with performance Or because we deal with data/columns differently on explore and dashboards (Tableconfig?) 

![image](https://user-images.githubusercontent.com/1983672/186682669-bc4efba4-3779-43fc-8c94-945e79b8f75e.png)

### App Version

v0.233.1

**Comment by ZeRego** [comment]
I haven't been able to replicate the issue. Can you provide a url to a dashboard with this problem ?

**Comment by hamzahc1** [comment]
@rephus - to ask if this is still a problem for the customer!

**Comment by ZeRego** [comment]
Haven't been able to reproduce anymore. Feel free to reopen if you can find replication steps.
