### ISSUE TITLE
Text box colors bullets black and other text gray

### ISSUE THREAD

**Issue by KristyMayer** [lightdash/lightdash#3088]
### Description

Text boxes automatically show bullet text in black and other text in gray and do not allow those colors to be overridden.

In contrast, I would expect:
- same default text color for all text, regardless of formatting
- default color to be black (preferred)
- ability to override text color selection (this is a nice-to-have feature is all text is default the same color. if text is a different color by default, this seems like a necessary accompaniment)

### To Reproduce

1. Make a text box
2. Create some unformatted text and some bullet text
3. Save text box. 

![Screen Shot 2022-08-25 at 3 12 13 PM](https://user-images.githubusercontent.com/107724505/186777928-2317db20-6f5c-404e-98db-bc74279823c8.png)

### App Version

v0.227

**Comment by TuringLovesDeathMetal** [comment]
@all-contributors add @KristyMayer for bug

**Comment by TuringLovesDeathMetal** [comment]
Ya, this definitely looks weird!

Let's see if we can change it to make it all black by default 👀 we'll look into this today or some time next week for you!

**Comment by rephus** [comment]
I'm fixing the default color text, it should be ready soon. 

> ability to override text color selection (this is a nice-to-have feature is all text is default the same color. if text is a different color by default, this seems like a necessary accompaniment)


@KristyMayer you can already do this by adding some HTML styling to the text. Like in here: 
![Screenshot from 2022-08-30 09-25-31](https://user-images.githubusercontent.com/1983672/187375982-fa41393d-8e42-4292-82c4-4f4752d52433.png)

![Screenshot from 2022-08-30 09-25-25](https://user-images.githubusercontent.com/1983672/187375980-6a2d5e49-53ae-4116-af16-179c1e2e27e9.png)

But let me know if you have another requirement.
