### ISSUE TITLE
Refresh dbt is not refreshing the tables/error state in the UI

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#309]
When you make changes to a dbt project connected to Lightdash and you click `refresh dbt`, you have to refresh the webpage for the tables/error state to update in the UI. 

Here are two videos showing what I mean:

**video 1**: I made a breaking change to the dbt project. So, I refresh dbt, then I have to refresh the webpage for it to show the error message/remove the ability to click on any tables.
https://www.loom.com/share/bbe487140a454c07a24319e0b96e72df

**video 2**: I fix the breaking change, refresh dbt, then have to refresh the webpage for it to show the tables/the fixed dbt project.
https://www.loom.com/share/8471de74e39347c09683d73d448ed26f

**Comment by owlas** [comment]
Hey I just ran into this too and it suuuucks. Will take a look
