### ISSUE TITLE
Integrate with cube.js

### ISSUE THREAD

**Issue by rahulstomar08** [lightdash/lightdash#3097]
### Description

API Integration with cube.js 

By API integration we can directly pull the metrics in Lightdash

cube.js is a tool through which we can create API of different combinations of measures & dimensions.  Currently, PowerBI has the capability to integrate these API into it.

**Comment by owlas** [comment]
@all-contributors add @rahulstomar08 for ideas

**Comment by davidvermeersch** [comment]
Hey guys, any reflections on this integration?
Alternatively, what would be the best way today to integrate cube with Lightdash where Lighdash would be the UI layer across the data tables and metrics in Cube?
