### ISSUE TITLE
Add `space_id` to spaces events

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3101]
### Description

Add a unique identifier for a space to the `space_created`, `space_updated`, and `space_deleted` events. 

`space_id` should be consistent across the events so we can identify when a space was created / changed / deleted

**Comment by muhsinkamil** [comment]
@TuringLovesDeathMetal I can take this up !

**Comment by TuringLovesDeathMetal** [comment]
@muhsinkamil yes, that would be great! :) you're absolutely blasting through issues 💪
