### ISSUE TITLE
I'm able to have more columns in my pivot table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3117]
### Description

Right now, the number of columns in the pivot table is limited to 20. 

We should have a much higher limit for this (e.g. if I have 2 years of data and I pivot on year and month, then I already exceed that 20 column limit)

We could make this "unlimited", or we could set a limit that's _**basically**_ unlimited but restricts some wild computation (e.g. 200 columns)

I'm not sure what the technical reasons for limiting the number of columns is, so would be good to hear from someone on the engineering team what they think!

(pulled out from #3114 )

**Comment by Martin-Carlsson** [comment]
**_Basically_** unlimited is definitely fine.

**Comment by rephus** [comment]
@ZeRego what do you think ?  is there any technical limitation or a performance reason for limiting the number of columns ?

**Comment by Martin-Carlsson** [comment]
@rephus 
Or at least 60, since that would allow for every month in 5 years
