### ISSUE TITLE
When I have many dimensions, I want to be able to collapse my groups (subtotals)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3120]
### Description

If I have many pivots, I want to be able to collapse the groups in my pivots. Doing this should re-aggregate the metrics shown in my cells based on the new grouping. 

### User acceptance criteria:

Miro sketch of the whole flow: https://miro.com/app/board/uXjVN6GxSOI=/?moveToWidget=3458764579463536132&cot=14

- [ ] Subtotals are calculated for all dimensions other than the rightmost dimension. 
- [ ] when I enable subtotals, toggles appear for all of my "groupable" dimensions. They are "open" by default. 
- [ ] I'm able to collapse/expand values in a "groupable" dimension column 
- [ ] Only dimension column types have grouping applied (not for metrics or table calculations) 
- [ ] To change the dimensions that are subtotalled, the user needs to reposition the dimensions in the table
Here's a video explaining the three criteria above: https://www.loom.com/share/ab8997f6d0d24df49e8d76a9ed62442f

See miro sketch for the criteria below here: https://miro.com/app/board/uXjVN6GxSOI=/?moveToWidget=3458764579459713948&cot=14
- [ ] This feature is only available for table chart types that are NOT pivoted (we'll deal with this in pivoted charts another time). 
  - [ ] When the table is pivoted, the subtotals option is disabled with a helpful message on hover. 

Miro sketch of these two criteria below here: https://miro.com/app/board/uXjVN6GxSOI=/?moveToWidget=3458764579465742749&cot=14
- [ ] Subtotals only appear for `count` and `sum` metric types.
- [ ] For other metric types and table calculations, the columns appear empty when toggled "shut"  

.
- [ ] Collapsing a group results in only showing the subtotal for that group.  
- [ ] These expanded/collapsed configurations are saved when I save my table or share my table with someone else
- [ ] Subtotals that sum to `0` should show as `0` (not as `-`)
- [ ] NULL values should be treated like `0`s in subtotals
- [ ] Grouping a dimension shouldn't aggregate its values, it should just show the group value. (e.g. for numeric dimensions, I shouldn't sum the values - I should just have the option to group unique values)
- [ ] If there is only one dimension in the table, then turning on `show subtotals` shouldn't affect the table (you need at least 2 or more dimensions for some sort of `collapsing`/`groups` to appear)

**Comment by TuringLovesDeathMetal** [comment]
^This was pulled out from #3114

**Comment by TuringLovesDeathMetal** [comment]
See demo here of this feature: https://www.loom.com/share/80cf373216824d3bb4255981ccd70052

**Comment by IrakliJani** [comment]
@totallynotwd maybe this will help

**Comment by agha4to** [comment]
Test from a different GH account...

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1711034740042889?thread_ts=1711034740.042889&cid=C03MG2VTR08
