### ISSUE TITLE
Can't change visualization type

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3122]
### To Reproduce

1. Load explore with table visuzalization eg: [demo example](https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/tables/dbt_orders?create_saved_chart_version=%7B%22tableName%22%3A%22dbt_orders%22%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22dbt_orders_basket_total%22%2C%22dbt_orders_currency%22%5D%2C%22metrics%22%3A%5B%22dbt_orders_average_of_basket_total%22%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22dbt_orders_average_of_basket_total%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%5D%7D%2C%22pivotConfig%22%3A%7B%22columns%22%3A%5B%22dbt_orders_currency%22%5D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22dbt_orders_basket_total%22%2C%22dbt_orders_currency%22%2C%22dbt_orders_average_of_basket_total%22%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22table%22%2C%22config%22%3A%7B%22showColumnCalculation%22%3Afalse%2C%22showTableNames%22%3Afalse%2C%22columns%22%3A%7B%7D%7D%7D%7D)
2. visualization type dropdown and export buttons are disableded

![Screenshot 2022-08-31 at 16 39 59](https://user-images.githubusercontent.com/9117144/187720869-1e634ede-4e8b-42e8-8e21-37f6f9316919.png)

`packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx` 
`packages/frontend/src/components/ChartDownload.tsx`
Disable logic in these files shouldn't disable if echart options is undefined when the type isn't chart.

```
   const disabled =
        isLoading ||
        (resultsData && resultsData.rows.length <= 0) ||
        !eChartsOptions;
```

Looks like this logic was introduced recently in this PR https://github.com/lightdash/lightdash/pull/3026

### App Version

0.236.0

**Comment by muhsinkamil** [comment]
Hey @ZeRego I have created a fix PR https://github.com/lightdash/lightdash/pull/3146, Let me know if you have suggestions. Thanks !
