### ISSUE TITLE
Remove "magic metrics" from Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3142]
### Description

By default, we add custom metrics to an instance so that people understand "metrics" and how to get them. 

This used to be really important when you needed to define metrics in the YAML, but since we've got custom metrics, it's so easy to add metrics to Lightdash that these "magic metrics" are a bit unnecessary (and [also a pain for some users](https://lightdash.slack.com/archives/C03HJ10UYQK/p1662112651163369). 

We should remove them now that metrics are so easy to discover!

![image](https://user-images.githubusercontent.com/31848148/188157331-6dd2cff7-9a69-49f4-a255-f7a4f5d73040.png)

**Comment by owlas** [comment]
We could also bring these back if `lightdash generate --add-metrics` added a default metric or two to the generated yaml

**Comment by TuringLovesDeathMetal** [comment]
^ya, I like this idea way more. If you're "opting into" metrics instead of having them forced on you

**Comment by swiftsam** [comment]
Our team expressed this need to me today. We are feeling so positive about our curation of metrics, that the Custom Metrics presented by default are a bit of a confusing threat to our carefully tended experience.

Relatedly, we noticed that even though you're able to "remove" them via the three-dot menu, they don't actually stay removed which is unexpected behavior.  

We would support removing the automatically presented custom metrics entirely.

**Comment by TuringLovesDeathMetal** [comment]
I think this one is quite quick! @swiftsam added it to the backlog 👀
