### ISSUE TITLE
[Close at end of milestone] Integrate Lightdash with Google Sheets

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3145]
### Description

I want to be able to get data in Lightdash and export it to Google Sheets or Excel. 

### What problem does this solve?

This means that I would be able to use Lightdash as a "spring board" to other analyses that might actually work better in Excel spreadsheets (things like forecasting or business scenario comparisons with lots of manual number-adding and on the fly calculations) 

### Other requests?
- Ideally, in Google Sheets, you'd be able to connect some results from Lightdash to a Google sheet and it would automatically update if the results table updated in Lightdash. Think something like the "connected data" sources in Google Sheets right now.

**Comment by hamzahc1** [comment]
This makes sense - I know you can use the Sheets API to do things like `Open in Google Sheets` and the table should appear there. You can also keep them synced so if the results table in Lightdash updates, you can get the latest numbers in GSheets. This is a pretty slick integration (it all happens via API). 

Doing this with Excel is almost certainly trickier with it being offline 💀

**Comment by 12ian34** [comment]
This has just been requested by a prospect. I've asked for any additional requirements they'd add, or their specific use cases.

**Comment by jw-aleksandr-zolotukhin** [comment]
+1 to that
our users can't live without Gsheets. No way there's any BI platform out there can replace them for 100%.
This would be really nice feature to have.

**Comment by yileeZAVA** [comment]
+1. A use case is that our marketing team use google spreadsheets to integrate our reports with Google Ads in Google Studio. Without this option, we won't be able to export data to google spreadsheet then connect it with data from Google Ads. This serves as our main marketing report to drive new customers. Another case is that in our company, we don't use excels anymore. Most of data sharing is either in google spreadsheet or directly on BI platforms.   It would be really great to have this features. Thank you!

**Comment by etadelta222** [comment]
+1 
We are evaluating Lightdash as a replacement for Looker and one of the features in Looker is the ability to schedule deliveries via email as excel attachments. The option would be nice in Lightdash

**Comment by 12ian34** [comment]
Hey @etadelta222 , we do actually have the feature to schedule deliveries via email as CSV files! You can check out our [docs here](https://docs.lightdash.com/guides/how-to-create-scheduled-deliveries/) to learn more. Would that work for you?

**Comment by etadelta222** [comment]
Thanks @12ian34 . It will work however an option to export as Excel would be great for our external end users.

**Comment by yileeZAVA** [comment]
Hello team, do you know if there is any update on this feature?  It would be really great if we can have this feature to rebuild our reporting pipelines integrating with other sources. Thanks!

**Comment by hamzahc1** [comment]
@yileeZAVA - We're working on this right now, hoping to release it in the next few days!

**Comment by hamzahc1** [comment]
Update for folks - this feature is waiting to be approved by Google's Trust & Safety team. Once this is complete, it will be released 🚀

**Comment by yileeZAVA** [comment]
Hello team, does this mean that this feature is available in Lightdash now? Thanks!

**Comment by hamzahc1** [comment]
Hi @yileeZAVA - yes it's available if you upgrade to the latest version! You can check out the docs here: https://docs.lightdash.com/guides/how-to-create-syncs
