### ISSUE TITLE
If you get the same error message multiple times, it should stack on your screen in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#315]
Currently, if the same error string comes up then the app won't duplicate the toast. 
This was to stop an endless stream of identical toasts. 

We should set it to a max of 5 or something and have it show duplicates

**Comment by TuringLovesDeathMetal** [comment]
See #283

**Comment by owlas** [comment]
@TuringLovesDeathMetal can you test this out. Let's reopen if the UX doesn't right

**Comment by TuringLovesDeathMetal** [comment]
Ya, I think it's fine! My instinct is to actually `dismiss` the issue once I've read it, so it sort of clears the issue and then pops up again. 

So let's leave it as-is for now :)
