### ISSUE TITLE
Dashboard list always shows "last edited" as "few seconds ago"

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3157]
### Description

Dashboard list always shows "last edited" as "few seconds ago".

### To Reproduce

1. Go to any space spaces

![image](https://user-images.githubusercontent.com/962095/188437638-4482ec73-529e-47c8-a382-c09d7b79b2f9.png)

![image](https://user-images.githubusercontent.com/962095/188437657-0727b97e-7a2f-4474-b415-1de4e3c71584.png)

### App Version
v0.241.0

**Comment by TuringLovesDeathMetal** [comment]
^its weird as well because the `see all dashboards` list has the correct date/time on it:

<img width="777" alt="image" src="https://user-images.githubusercontent.com/31848148/188448303-6f997a5e-03f7-4cac-ba66-4ec589a9974f.png">
