### ISSUE TITLE
I can't plot anything with only one dimension or metric

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3160]
### Description

When you only have a single metric or dimension in your results table, you can't make a plot. 

You should still be able to have a table chart type or a big number chart type with only one field selected. 

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/31848148/188450316-73b0155c-0363-4df4-ba4c-8c429bdd76e9.png">

**Comment by muhsinkamil** [comment]
Relates to https://github.com/lightdash/lightdash/issues/3122

( should be fixed after https://github.com/lightdash/lightdash/pull/3146 )
