### ISSUE TITLE
Table visualization header overlaps the nav bar on scroll

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3166]
### Description

When scrolling on a dashboard, the table header overlaps the navbar.

https://www.loom.com/share/c43477ba5e8b450f8097d07c6ac2e170?from_recorder=1&focus_title=1

**Comment by IrakliJani** [comment]
this has been addressed by https://github.com/lightdash/lightdash/pull/3139
closing
