### ISSUE TITLE
When a user selects a saved chart to add to a dashboard, we shouldn't scroll back up to the top of the list

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3169]
### Description

When a user selects a saved chart to add to a dashboard, we automatically scroll back up to the top of the list. This can be frustrating because typically, you'll be scrolling through a list top-to-bottom and adding charts along the way. So, each time you add a chart, you lose your place in the list. 

https://www.loom.com/share/1d0ece7e09394f9ca8f0b27959991ec0

Proposed changes: when a user selects an item from the list, the list remains in that position (we don't scroll back to the top each time)

**Comment by la55u** [comment]
I tried to reproduce this issue on the [demo app](https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/dashboards/587b3317-18c2-4048-b7ce-c51e3f25d0d5/edit) but it doesn't seem to be happening anymore, the list stays in place. Can this issue be closed?

**Comment by TuringLovesDeathMetal** [comment]
This issue has been resolved ✅
