### ISSUE TITLE
Support date parts as time intervals

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3185]
### Description

Add more timeframe options that don't return dates. 

E.g. if I had the date `2022-09-07`, then I would get:

- `day_of_week`: `wednesday`
- `day_of_week_index`: `3` (maybe 2...it depends if we think weeks start on sunday or monday 😅 )
- `day_of_month`: `7`
- `quarter`: `2022-Q3`
- `quarter_of_year`: `Q3`

I think we should just copy-paste the Looker timeframe options here (instead of trying to figure this out for ourselves): https://cloud.google.com/looker/docs/reference/param-field-dimension-group#timeframes

Related to #3184

**Comment by gordonkjlee** [comment]
It might be that this request (date part?) is separate to the existing time interval feature (which changes the granularity of dates and timestamps). I would suggest that `day_of_week` is an integer for consistency with `day_of_month` - with the index (1 as Monday or 1 as Sunday) either being controlled within the database (e.g. `alter session set week_start = 7;`) or via a parameter for `day_of_week`.

The business use case for this request is to facilitate Cumulative graphs - where `dayofmonth` is on the x-axis and a running sum (table calculation) on the y axis. This is very much used for sales analytics.
<img width="179" alt="image" src="https://user-images.githubusercontent.com/7281432/188916910-97221d9c-6a44-45f0-a1a4-381147697829.png">

**Comment by ZeRego** [comment]
We should also add similar options for other measures (day of month, month of year, quarter of year, etc  )
eg:
**QUARTER_OF_YEAR** would return the strings: Q1, Q2, Q3, Q4. 
**QUARTER_OF_YEAR_INDEX** would return the numbers: 1,2,3,4.

**Comment by gordonkjlee** [comment]
The options and how these are named should be aligned with sql databases e.g. Snowflake FOLGA
515 392 674
https://maps.app.goo.gl/o8HPJnrHn3Yhp41MA
