### ISSUE TITLE
Improvements to loading states

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3191]
There are some times when you're loading up pages where the experience could feel a bit slicker: 

- When you first access a lightdash url, there appears to be two loading spinners. Could it becomes just one to start off with?
- the loading spinner that is displayed when you're loading up a dashboard is cropped at the top! (image attached in comment below)
![Screenshot 2023-02-14 at 10 55 07](https://user-images.githubusercontent.com/12776522/218714497-db0d03cf-824c-4477-a822-fd98760a3200.png)

**Comment by TuringLovesDeathMetal** [comment]
Related to #2217
