### ISSUE TITLE
Sidebar titles in settings pages need equal spacing above and below

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3192]
<img width="408" alt="Screenshot 2022-09-08 at 10 38 09" src="https://user-images.githubusercontent.com/12776522/189089063-0a92f280-2122-40c9-b1f6-65eacf96f13d.png">
<img width="422" alt="Screenshot 2022-09-08 at 10 38 03" src="https://user-images.githubusercontent.com/12776522/189089072-eb14fea3-1b9b-4ad0-ab22-ce1ec3677f9d.png">

**Comment by IrakliJani** [comment]
@PriPatel closing this as we've already updated project settings page.
