### ISSUE TITLE
Some 'big number' tiles in the demo need breathing space

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3194]
The three number tiles feel unaligned and a bit squashed!

<img width="720" alt="Screenshot 2022-09-08 at 10 59 26" src="https://user-images.githubusercontent.com/12776522/189093797-ea9d11f1-23d1-47f1-8cfc-e1e45823dae2.png">

Suggestion: Make the `food for thought` tile smaller
<img width="1440" alt="Screenshot 2022-09-08 at 10 55 55" src="https://user-images.githubusercontent.com/12776522/189093609-6aa125e4-53cd-4bab-a9f7-9b441412ee3e.png">

**Comment by IrakliJani** [comment]
@PriPatel this is resolved by #3649 

<img width="1023" alt="CleanShot 2022-11-10 at 10 42 17@2x" src="https://user-images.githubusercontent.com/962095/201018949-904e976e-7505-4ddb-bb0e-80380a9a46ad.png">
