### ISSUE TITLE
I want to be able to access TV mode from the dashboard or chart header

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3195]
#3195 - users should be able to access the TV mode for a chart/dashboard from the header. 

As a business user, there are elements of the app that Im not really interested in seeing when browsing dashboards. Seeing the dashboard in full-screen without the build tools / actions / navbar would be ideal. I guess this would help in presentations as well.

**MVP**

Add a 'View in TV mode' option under the context menu. Use a 'screen icon'
When user hits the TV mode, Lightdash navigation disappears (for now)
A message reminding users to hit 'esc' to leave TV mode appears for a few seconds.
<img width="324" alt="Screenshot 2023-02-23 at 14 05 09" src="https://user-images.githubusercontent.com/12776522/220934184-e39f532a-fb85-4864-b418-31d64951049d.png">

**Comment by IrakliJani** [comment]
zen mode

**Comment by PriPatel** [comment]
🧘‍♀️, exactly. No distractions pls.

**Comment by hamzahc1** [comment]
I like this - I think hiding the app navbar, the edit dashboard buttons and displaying the new dashboard filters would be a vibe ☮️ (You could even move the Title so that in TV mode the charts start higher up the page)

**Comment by 12ian34** [comment]
A prospect has requested that the TV mode includes a configurable refresh schedule

**Comment by PriPatel** [comment]
we could have something like this in the header
<img width="339" alt="Screenshot 2023-02-08 at 14 27 09" src="https://user-images.githubusercontent.com/12776522/217503027-46a05b4d-a893-4bd1-b4e2-340b25794065.png">

**Comment by ZeRego** [comment]
Could we add the auto-refresh UI and functionality in a separate PR ? We have an open ticket for that btw https://github.com/lightdash/lightdash/issues/3693 ?

**Comment by 12ian34** [comment]
This isn't stale! We'll definitely be working on this at some point!
