### ISSUE TITLE
Add `calendar months` as a date filtering option

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3198]
### Description

Right now, we're able to filter in the last 6 months (e.g. if today is 08-09-2022, then I would filter dates between `08-09-2022` - `08-03-2022`), we're also able to filter in the last 6 complete months (e.g. if today is `08-09-2022`, then I would filter `01-08-2022` - `01-02-2022`). 

But, there's no way to filter in the last 6 _**calendar months**_. E.g. if today is `08-09-2022`, I want to filter from `01-02-2022` --> `08-09-2022`. 

^I want to filter in the last 6 complete months _**and**_ the dates in this month.

We should add a filter option for `month` and `year` which is `complete month` or `complete year` which applies the logic above.

Once this is done, be sure to add this to the filters reference doc here: https://docs.lightdash.com/references/filters

**Comment by gordonkjlee** [comment]
In the meantime, I found a workaround to achieve this. If the dimension has a `MONTH` `time_interval` specified, a filter for the last x months can be applied on this.

**Comment by TuringLovesDeathMetal** [comment]
^so smart! ya, that makes sense. 

Do you still feel like this is a "missing feature" then? (since we default to including week, month, and year time intervals for all date values)?

**Comment by gordonkjlee** [comment]
Now that I've got a solution, I'm okay with this. The question is whether this is a common use case for other users, and how easy it is for them to find the same solution. If it's a common problem that users struggle to find a solution to, there this would either mean training/documentation, or a feature to improve UX.

**Comment by TuringLovesDeathMetal** [comment]
Closing as not planned since there is a workaround adn no one else has requested this in over a year!
