### ISSUE TITLE
Charts appear off the screen in small tiles

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3199]
### Description
For the first two charts, teh charts are cropped, and appear off the screen:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/31848148/189297746-5ccac471-f808-47c4-b662-b3967bb66677.png">

https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/dashboards/cff3e1b0-34c1-4b22-93b0-751068f96aa7/view

**Comment by rephus** [comment]
I can see 2 issues here: 

- The first chart label is cropped, we should probably increase the padding on left and right sides. 
- Both charts are cropped at the bottom, I guess what we want to do here is to scale the chart so it fits the panel, eg: 
![image](https://user-images.githubusercontent.com/1983672/189604143-05e2e640-75ba-4fc2-b7ed-30f188c75f32.png)

Is there a min-height we want to force ? currently we can resize the panel to only show the title.. 

![image](https://user-images.githubusercontent.com/1983672/189604374-1228ed10-2c0b-4b1d-9027-82d0f6fcd68d.png)

**Comment by rephus** [comment]
Just removing the `echarts-for-react` `height:300px` property makes it more dynamic. Is there any reason why we want to force its height @ZeRego  ? (maybe set max-height instead on dashboard only) 

[Screencast from 12-09-22 10:14:50.webm](https://user-images.githubusercontent.com/1983672/189605408-18aba257-9de5-434a-882f-410d70c295cf.webm)

**Comment by rephus** [comment]
> The first chart label is cropped, we should probably increase the padding on left and right sides.

Mmmm, this is also going to be harder than I expected, because it is cropped by echarts within the svg

![Screenshot from 2022-09-12 10-29-15](https://user-images.githubusercontent.com/1983672/189608229-64a23bfc-0f95-4bfd-804d-ba15f91ce7b6.png)

**Comment by ZeRego** [comment]
> Just removing the echarts-for-react height:300px property makes it more dynamic. Is there any reason why we want to force its height @ZeRego ? (maybe set max-height instead on dashboard only)
@rephus I think the 300px height was needed for the collapsing section in the explore page. Might not be needed anymore or we might only apply the height when used in the explore page.
