### ISSUE TITLE
Sorts persist when you remove a column in the UI

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#321]
In the following screen shot, I have previously sorted by `github_daily_date` and then removed it from my explore. it's still listed as a group by on the query, causing an error.

<img width="1479" alt="Screenshot 2021-08-06 at 16 50 42" src="https://user-images.githubusercontent.com/11660098/128537501-a5b0b5d0-36c3-4b57-bcbd-383781e4a91b.png">

**Comment by TuringLovesDeathMetal** [comment]
+1 ran into this issue...it _**seriously**_ sucks because it's super unclear what's happening. 

I've added it to the backlog as one of our bugs to squash
