### ISSUE TITLE
Lightdash CLI error on Node v12.22.12

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3211]
### Description

CLI should be compatible with older Node versions.

### To Reproduce

<img width="634" alt="image" src="https://user-images.githubusercontent.com/9117144/189396151-44f5ccb1-182f-4ddb-a898-2b6388d44e8b.png">

### App Version

0.247.0

**Comment by rephus** [comment]
This particular issue is comming from `inquirer-press-to-continue` which is a recent repo without too much maintenance. I'd suggest to remove this dependency and try to achieve this by using inquirer directly. It is only used on preview (waiting for key)
