### ISSUE TITLE
[Close me at the end of the default value filter work] Include an "any value" for filters

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3212]
Include an "all" values for filters. This would effectively display the filter, but not apply any filters on the field.

### Acceptance criteria

- [ ] There is an operator option which is `any value` that you can select from the drop-down list
<img width="355" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/7cb5706b-1021-49fe-865e-096251f07536">

- [ ] This operator value works for numbers, dates, booleans, strings, etc. (all field types)
- [ ] When the `any value` operator is selected, it removes any other input fields. 
- [ ] Fields that have `any value` selected as the operator appear like `Field Name: any value` when added to a dashboard.

### Documentation

- [ ] update filters reference doc to include new filter type: https://docs.lightdash.com/references/filters

**Comment by gordonkjlee** [comment]
When I create a dashboard (in any BI tool), I would typically include some filters on the dashboard to make it easy for business users. These could be often-used filters, or filters that I think would be useful for them that they may not even think of applying.

**Comment by TuringLovesDeathMetal** [comment]
cool, so is this different to #1735  where you would apply filters that would appear as default in an Explore? 

^If people were able to remove these filters as well?

**Comment by gordonkjlee** [comment]
[#1735](https://github.com/lightdash/lightdash/issues/1735) is about specifying default filters in dbt. I love this idea.

My suggestion is for the UI, where dashboard creators can specify filters at the top of the dashboard, but without having to specify a value. These are almost suggested filters (but where the values are not suggested) for dashboard consumers.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/7281432/189861166-6350ab58-8796-4d09-afb8-c87dee5a77cb.png">

**Comment by TuringLovesDeathMetal** [comment]
aaah, right sorry 🤦‍♀️ you're talking about dashboards - I'm talking about explores. 

So you want to have a dashboard filter that you can add in edit mode that just selects `all` - basically, it's just a placeholder for a filter.

**Comment by suebeet** [comment]
Hi, little addition to the above. The option in filtering where you would choose `all values` or `any value` (depends how you are going to call it) should include NULL as well as EMPTY fields.

_Why?_ We have some instances where the value in a dimension can either be NULL/EMPTY or a very long list of (for example) names. We would like to ensure that we can show the filter in the default dashboard view, but do not want to miss out on what we show, i.e. to show any value.

**Comment by gordonkjlee** [comment]
I suggest that `NULL` and `EMPTY` should be treated in the same way in the lightdash UI. But when compiled to SQL, it should become `is null` or `= ''`

**Comment by suebeet** [comment]
Yes, agree that in the UI it should be treated as equals. No need to add extra complexity for the end-user in this case.

**Comment by rephus** [comment]
@gordonkjlee @suebeet I've been thinking about how to implement this "all" filter. I'd like to hear what you think

- Adding `all` to a value, keeping the field and operator: 
- 
I think this was the original idea, but this option is very tricky to achieve in the UI, because we change the input field depending on the field selected (numbers, booleans, dates...) , so it is hard to keep it consistent across different types.

![Screenshot from 2022-10-06 15-15-41](https://user-images.githubusercontent.com/1983672/194330235-a4a8102b-50e0-4f85-b7a7-a87f700bfbc6.png)

For example, it is not possible to add a `all` string to a number field, and accepting `undefined` values on field is not great, even if we use placeholders.

![Screenshot from 2022-10-06 15-26-06](https://user-images.githubusercontent.com/1983672/194330192-91d949dd-af90-4b6e-a4e2-64aad870a8ce.png)

- Adding a new `is any value`  operator. Like `is null` but without filtering anything. It will be just a placeholder with a Field type. You are missing the operator here though.

**Comment by rephus** [comment]
Slack thread here: https://lightdash.slack.com/archives/C02NPFHF4F6/p1665064793198719

From Priyanka: 

> We should stick to  empty states, I just have no idea how to deal with cases like: 

![image](https://user-images.githubusercontent.com/1983672/194880340-4d43e73f-ad97-488e-9b2d-0dbcc0d1f4a8.png)

**Comment by TuringLovesDeathMetal** [comment]
https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=7396%3A90363&scaling=scale-down-width&page-id=1097%3A37682&starting-point-node-id=1097%3A38515

**Comment by ZeRego** [comment]
Needs more design work/investigation

**Comment by hamzahc1** [comment]
Related to #6377

**Comment by joaoviana** [comment]
This feature is now enabled on Dashboard filters! 

See https://docs.lightdash.com/guides/limiting-data-using-filters#adding-saved-filters-to-your-dashboard (relevant issue: https://github.com/lightdash/lightdash/issues/6377)
Changelog: https://changelog.lightdash.com/

Opening a ticket for filters allowed to be empty when interacting with them on Charts/Explore: https://github.com/lightdash/lightdash/issues/6617
