### ISSUE TITLE
Ability to reorder columns by drag and drop

### ISSUE THREAD

**Issue by bala-office** [lightdash/lightdash#322]
Currently the Dimensions when selected are added from left and any metrics added from right. If the ordering of any column has to be changed we have to unselect all the affected columns and re-select them.

**Comment by owlas** [comment]
Thanks for opening this issue @bala-office - this is a really important missing feature! It's quite frustrating not being able to lay out the columns how you'd like

**Comment by owlas** [comment]
Example with `react-table`
