### ISSUE TITLE
Specify OAuth Scope required for one-click-deploy with GitHub

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#323]
![image](https://user-images.githubusercontent.com/31848148/128689263-5e9313aa-432b-48d3-912c-a90259f12d53.png)
When you try to create a personal access token, it asks you for:
1. The expiration (we should tell the user to set this to `No expiration`)
2. The scope required for the token (I don't know what scope we actually need here, but this should be included in the instructions). Here are teh options:

![image](https://user-images.githubusercontent.com/31848148/128689593-94a2602d-d29c-41df-b015-f80b72514f36.png)
![image](https://user-images.githubusercontent.com/31848148/128689624-91497da8-c06b-42ac-9022-fb060fba68c8.png)

**Comment by owlas** [comment]
@TuringLovesDeathMetal I started a PR here: https://github.com/lightdash/lightdash-deploy-heroku-github/pull/1

**Comment by owlas** [comment]
We should also add this to docs.lightdash.com

**Comment by owlas** [comment]
Also add this to `LIGHTDASH_SECRET`

> Heroku generates a secret key for us that you can’t access. This is to secure everyone’s individual deployment (it encrypts the session tokens used to log you in)

**Comment by owlas** [comment]
Closed https://github.com/lightdash/lightdash-deploy-heroku-github/pull/1

**Comment by owlas** [comment]
<img width="1160" alt="Screenshot 2021-08-10 at 11 20 41" src="https://user-images.githubusercontent.com/11660098/128850642-ddf05a7e-3e4f-4ea9-84b2-0c38cc6dcf6d.png">

Example screenshot with correct permissions @TuringLovesDeathMetal

**Comment by TuringLovesDeathMetal** [comment]
ya! @owlas I'm going to update a couple of things in docs (I think there are three tickets in the backlog, so was just going to smash through them all in one PR). 

DIdn't get around to this today, but will do it tomorrow if that's cool!

**Comment by TuringLovesDeathMetal** [comment]
closed by #341
