### ISSUE TITLE
Column names should be wrapped in quotes

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3231]
### Description

Lightdash doesn't respect the columns that are case sensitive. 
Eg. in a postges table I have the column "Region" but when queried via Lightdash is trying to get "region". Resulting in the following error:
![1](https://user-images.githubusercontent.com/9117144/189912404-034a1a33-84d6-422d-a04b-7ff0ba811539.png)

### To Reproduce

SQL Lightdash generates
```
SELECT
  "new_demo_data".Region AS "new_demo_data_Region",
  AVG("new_demo_data".Profit) AS "new_demo_data_average_of_profit"
FROM "postgres"."dbt_lightdash"."new_demo_data" AS "new_demo_data"


GROUP BY 1
ORDER BY "new_demo_data_average_of_profit" DESC
LIMIT 500
```

SQL it should generate:
```
SELECT
  "new_demo_data"."Region" AS "new_demo_data_Region",
  AVG("new_demo_data"."Profit") AS "new_demo_data_average_of_profit"
FROM "postgres"."dbt_lightdash"."new_demo_data" AS "new_demo_data"


GROUP BY 1
ORDER BY "new_demo_data_average_of_profit" DESC
LIMIT 500
```

### App Version

0.251.2

**Comment by ZeRego** [comment]
Should we use the dbt quoting config to decide if we should wrap in quotes or not ?

**Comment by rephus** [comment]
Another option is to let them handle this by using `sql` on their schema. It does not require any change. /cc @TuringLovesDeathMetal  @owlas  


![Screenshot from 2022-09-21 11-30-45](https://user-images.githubusercontent.com/1983672/191469686-bddc300c-94ff-4ae6-9773-dd7c08a092b5.png)

![image](https://user-images.githubusercontent.com/1983672/191469782-672fe1c0-ab46-475b-817a-6a2b369dd768.png)

**Comment by TuringLovesDeathMetal** [comment]
> Another option is to let them handle this by using sql on their schema.

Don't love this option - it feels a bit broken that it doesn't "just work" for my columns (even if some of them are upper case)
