### ISSUE TITLE
Publish CLI deploy script on github marketplace

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3240]
### Description

The script is ready to be published on the marketplace

https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

![image](https://user-images.githubusercontent.com/1983672/190117297-bfd65cff-12ed-4ce2-b87c-92dad84076d2.png)

It would be nice to publish this, so people just need to add a single line script (that we can update) instead of copy-pasting the whole script. 

It should look like : 

```
- name: Deploy lightdash
  uses: actions/deploy-lightdash@v1
```

**Comment by rephus** [comment]
@owlas we need admin permissions on github to do this . not urgent

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned - I think we need to do a bigger revamp of our GitHub integration in Lightdash and there hasn't been any action on this in more than a  year. Will reopen if needed!
