### ISSUE TITLE
Ability to freeze X first columns in table visualization

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3244]
### Description

Sometimes the number of columns requires you to scroll right to view more data, therefore, you lose track of which row you're looking at. Freezing the first X columns would allow you to keep track of what you're viewing.
This configuration should be saved so all users can take advantage of it.

### What problem does this solve?

User can keep track of important columns while exploring a big table visualization in the dashboard.

### User acceptance criteria:

- we could add a snowflake icon beside the column name to freeze it 👀 similar to the show/hide option
image
![image](https://user-images.githubusercontent.com/31848148/195054989-bb705772-7a1d-4ed3-a255-77b9a7e11894.png)
- frozen columns should always be shown as the left-most columns.

**Comment by TuringLovesDeathMetal** [comment]
we could add a snowflake icon beside the column name to freeze it 👀 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/31848148/194502407-6d8d2c55-c939-4b5c-938c-813805fa4bdd.png">

**Comment by rephus** [comment]
https://github.com/TanStack/table/issues/848
