### ISSUE TITLE
Row Totals

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3245]
### Description

Be able to see row totals. Specifically on pivoted tables.

### User story

I have a table that has the revenue per product, monthly which is pivoted on `product`. I want to know the total revenue that we have per month (so I need the row total for each month).
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/31848148/206405206-76d28245-d59b-4409-a17c-d9147f6bd9dc.png">

### Acceptance Criteria

- [ ] There is an tick-box option for `show row totals` in the Table Visualization type config: 
<img width="232" alt="image" src="https://user-images.githubusercontent.com/31848148/212281133-f3eeac95-d977-4e63-aeaa-644d0771158c.png">

- [ ] This only shows up on the table visualization chart type
- [ ] I can only `show row totals` if I have at least one group selected (i.e. the table _**must**_ be pivoted). If it's not pivoted, then the option to `show row totals` is greyed out with help text on hover (saying something like `you need to add at least one group to use row totals`)
- [ ] Row totals calculate the sum of the values that are pivoted (i.e. the values from the metrics). 
- [ ] There is one row total that appears per metric
 For example, in this table, only `count page views` would be summed. So you'd have a `Total count page views` column that would be the sum of hte count page views.
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/31848148/221844129-76074eb4-41e9-464c-a8b6-d36cd33fb64d.png">
([source](https://analytics.lightdash.cloud/share/2IbtngalySkCnBI-sGyJ3))

If I added another metric for `anonymous device count`, then I would get another column called `Total anonymous device count` in my row totals
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/31848148/221844866-918d5c5c-4639-4376-8cdb-00e7d7618a36.png">
([source](https://analytics.lightdash.cloud/share/2OXXs6DsiC2-kxToUxjXF))

- [ ] If I've selected `row totals` then I select `metrics as rows`, my `row totals` become `column totals` and the label in the chart config changes to reflect this (i.e. the `show row totals` becomes `show column totals`)

**Comment by tallensick** [comment]
+1 for this feature please!

**Comment by rephus** [comment]
I think this has been already implemented @TuringLovesDeathMetal @ZeRego are we missing anything ? 
![image](https://user-images.githubusercontent.com/1983672/208373543-fed096ab-9d46-40e2-bf66-097adbe0a75b.png)

**Comment by PriPatel** [comment]
- For now, this can behave the same as 'frozen columns', but instead, the column is pinned to the right. There is a separate ticket to improve the appearance of that, so both should follow the same rule as a start. 

>  I can only show row totals if I have at least one group selected (i.e. the table must be pivoted). If it's not pivoted, then the option to show row totals is greyed out with help text on hover (saying something like you need to add at least one group to use row totals)
- We don't need to grey it out, we can just hide it as thats the pattern the current chart config panel uses when features are NA

**Comment by Martin-Carlsson** [comment]
+1 for this feature please! 🤩
