### ISSUE TITLE
"could not cast literal to type date" error when using `in the last` for a date field

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3249]
### Description

I have a date field in my data model called `date`. It's been cast as a date in my .yaml

<img width="261" alt="image" src="https://user-images.githubusercontent.com/31848148/190258889-8f4446d1-34f5-485f-a6c9-75608754a8aa.png">

When I try to filter `in the last` on this date field, it returns an error. 

https://www.loom.com/share/88b1d1ea7b19407ea478c8c66df5c22c

I'm using the `pages` explore in Lightdash Analytics

**Comment by rephus** [comment]
Ok, I know what's happening... BIgquery cannot cast the full timestamp as DAY when doing `in the last` filtering

![image](https://user-images.githubusercontent.com/1983672/191494097-b2f5a815-7380-4bf3-95c8-39ef0e84b5b0.png)

We should handle the casting ourselves... 

- Should we do it for all warehouses ? or just Bigquery (for now) (postgres seems to be happy with this filtering) 
- When casting , what should we do ? eg:

1.     AND (`pages`.date) <= ('2022-09-21')) -- equal 
2.     AND (`pages`.date) < ('2022-09-22')) -- tomorrow

**Comment by TuringLovesDeathMetal** [comment]
> Should we do it for all warehouses ? 
BigQuery for now...and Snowflake? (if it's a problem there too?)

> Should we do it for all units of time ? (week , month, year)
I'm not sure I understand what you mean here? 


> When casting , what should we do ? 
Option 1: include today in the "in the last" filter. It _**should not**_ be included if it's `in the last` _x_ `complete days` though. For complete days, it should filter using option 3.

**Comment by rephus** [comment]
Snowflake works, tested agains snowflake staging db 

![image](https://user-images.githubusercontent.com/1983672/191514596-c6aa29aa-53c5-42c1-a5fb-861819796e75.png)

**Comment by TuringLovesDeathMetal** [comment]
niiiiice!
