### ISSUE TITLE
Update modal should not save if missing required fields

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3250]
Should we show an error if the name is empty and trying to save ? 

![image](https://user-images.githubusercontent.com/1983672/190096681-a9024fb7-4f15-4fbc-b3db-2c4710f284a1.png)

_Originally posted by @rephus in https://github.com/lightdash/lightdash/issues/3235#issuecomment-1246392479_

**Comment by TuringLovesDeathMetal** [comment]
> Should we show an error if the name is empty and trying to save ?

Ya, definitely 

I ran into this with an app the other day actually: it's _**super**_ helpful if you give context on what's wrong/broken above the field that's wrong/broken (i.e. above the `name` field) - not just by the `cancel` button or something with a generic error message.
