### ISSUE TITLE
Grey out the Space name and icons in the chart/dashboard dropdowns for items that already exist in the Space.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3269]
The name of the dashboards that are already in the space (eg KPI dashboard) are greyed out but their Space names look the same. The whole item including the icons should look greyed out. 
<img width="511" alt="Screenshot 2022-09-20 at 14 17 37" src="https://user-images.githubusercontent.com/12776522/191287558-3e5dcc5e-decf-4e07-9fba-0c3784183be9.png">

**Comment by vibhuti019** [comment]
I would like to work on this issue.
