### ISSUE TITLE
improve heroku docs for `LIGHTDASH_SECRET`

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#327]
Add this to `LIGHTDASH_SECRET`

> Heroku generates a secret key for us that you can’t access. This is to secure everyone’s individual deployment (it encrypts the session tokens used to log you in)

_Originally posted by @owlas in https://github.com/lightdash/lightdash/issues/323#issuecomment-895106392_

**Comment by TuringLovesDeathMetal** [comment]
closed by #341
