### ISSUE TITLE
Cell menu not working in View underlying data

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#3280]
### Description

Cell menu not working in View underlying data.

### To Reproduce

 - Click View underlying data in a chart
 - Click on a cell

https://user-images.githubusercontent.com/7769335/191502797-57ba1325-41dc-4912-9cb3-fad348655273.mov

### App Version

Version: 0.258.0

**Comment by TuringLovesDeathMetal** [comment]
@Martin-Carlsson thanks for spotting this! 👀 

I'm assuming that you're expecting the underlined value to have the same `options menu` as in the results table? (so you'd be able to click on the link it looks like you've attached to it)

**Comment by Martin-Carlsson** [comment]
@TuringLovesDeathMetal 
Yes 🏄‍♂️
