### ISSUE TITLE
Users can be deleted from an organization

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#329]
You're able to delete a user from an organization. Any user in the organization has the option to do this. 

https://www.sketch.com/s/86fc5f09-0025-4894-8a6d-0f71eaa9f8ce

**Comment by ZeRego** [comment]
Are we planning to restrict access to this action or are we going to let any user delete users ?

**Comment by TuringLovesDeathMetal** [comment]
We're taking off the training wheels here: anyone can delete anyone. 

Definitely something that will get updated once we introduce different user access/roles, but for now, I think that this should be fine 🤞 (famous last words)

![CoolLavishAlabamamapturtle-small](https://user-images.githubusercontent.com/31848148/129866876-d369cec0-0cfc-4d28-9245-808c2226bc61.gif)
