### ISSUE TITLE
Config for removing row number in table chart

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#3295]
### Description

Add an option for removing row number in table chart

### What problem does this solve?

Space is a precious resource in a dashboard.
It would be nice if it was possible to disable the row numbers in table chart.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/7769335/191765621-927a4572-6de7-401c-b06d-b9406bf0b8f8.png">

**Comment by TuringLovesDeathMetal** [comment]
- [ ] add a toggle in the table visualization which is `hide row numbers`
<img width="334" alt="image" src="https://user-images.githubusercontent.com/31848148/199229623-cf029c89-3350-4bca-bdd9-e543d244d8b1.png">
