### ISSUE TITLE
Autocomplete - display spinning wheel when autocomplete values are being fetched

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3302]
### Description
When a field is selected, it could take several seconds for autocomplete values to show. In the meantime, the greyed out text "No suggestions." is displayed in the downdown. This is fairly unnerving.

From a UX perspective, it would be nice if a spinning wheel (or some text) is displayed to provide comfort that suggested values are being fetched. Only when no values can be returned (e.g. timeout, or the field comprises all null values) that "No suggestions." should be displayed.

### What problem does this solve?

Provide comfort to the user around autocomplete.

**Comment by hamzahc1** [comment]
@rephus is this similar to the recent fix we made for the same issue related to global search?
