### ISSUE TITLE
Charts in dashboards default to less than half-width

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3303]
### Description

When a chart is added to a dashboard, it takes on a width that is just under 50%.

I'm not sure if there's a reason for this, but the UX would be more streamlined if it were automatically added as 50% width (assuming most users tile charts two-across).

### To Reproduce

Add chart to dashboard.

### App Version

 v0.263.1

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned - the width of the chart depends on your screen size. And no other requests have been made for this since it was created. Will reopen if needed!
