### ISSUE TITLE
Unable to add user in Self-hosted Lightdash app in Heroku

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3305]
### Description

Error in trying to add a user in a self-hosted Lightdash app in Heroku.

### To Reproduce
1. Hosting a lightdash instance on xyz.herokuapp.com using the one-click deployment
2. Head to https://xyz.herokuapp.com/generalSettings/userManagement
3. Click on "Add user" button, provide email address, and click "Generate invite"
4. The error message says "TypeError [ERR_INVALID_URL]: Invalid URL: xyz"
![image](https://user-images.githubusercontent.com/7281432/191964533-287d66da-b43c-403e-8c9a-ff0ff5d286d6.png)
5. Click "Back to all users"
6. The user is not there
7. Refresh the page, and the user displays with a "Pending flag". However, the user does not receive an email invite.
![image](https://user-images.githubusercontent.com/7281432/191965000-12233c1d-e5db-4cbf-92de-e5dccc55a559.png)
9. Click on "Get new link" against the user, and the same error message appears
![image](https://user-images.githubusercontent.com/7281432/191965292-72cfa7e9-b2a4-456a-831e-6fb05cf5753d.png)
10. Try to reset the password for the user by going to xyz.herokuapp.com/recover-password but get an error message "Failed to send password recovery email. TypeError [ERR_INVALID_URL]: Invalid URL: xyz"
![image](https://user-images.githubusercontent.com/7281432/191965541-3490c15a-854c-436c-993d-196b6da7c703.png)
11. However the user can be deleted from user management
![image](https://user-images.githubusercontent.com/7281432/191965933-4525f433-7e49-47c8-8531-1c06c25c3804.png)

### App Version
v0.263.1

**Comment by TuringLovesDeathMetal** [comment]
#3200 --> wonder if this is at all related? 🤔

**Comment by gordonkjlee** [comment]
I believe it's not reading the URL correctly.

When deployed on https://**xyz**.herokuapp.com/ , it's expecting **xyz** to be a url, and returning the error
"TypeError [ERR_INVALID_URL]: Invalid URL: xyz"

**Comment by hamzahc1** [comment]
@ZeRego I'm guessing this might actually be related to the email server config for self-hosting?

**Comment by ZeRego** [comment]
@gordonkjlee 
I wasn't able to reproduce the error when inviting a user.
What did you write in the `SITE_URL` input when setting up the Heroku app ?
It should be something like this: `https://jose-lightdash.herokuapp.com`  
![Screenshot 2022-10-07 at 17 03 58](https://user-images.githubusercontent.com/9117144/194598110-cb09bd22-053f-4dbb-b57a-2474e20471fc.png)

I opened a separate issue for the reset password error since that feature shouldn't be available since there is no email server configured. #3430

**Comment by gordonkjlee** [comment]
@ZeRego It's https://knoma-lightdash.herokuapp.com/ - Happy to take you through this via a call if it helps

**Comment by ZeRego** [comment]
We were able to fix the SITE_URL value. I'm opening a separate ticket to update that input description to make more obvious as this problem as happened with other users.

**Comment by gordonkjlee** [comment]
Resolved with the help of @ZeRego Thanks!

Solution:

1. Head to heroku app settings (https://dashboard.heroku.com/apps/knoma-lightdash/settings)
2. Reveal Config Vars
3. Change SITE_URL from `knoma-lightdash` to `https://knoma-lightdash.herokuapp.com`
