### ISSUE TITLE
Revert "move refresh dbt"

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3310]
### Description

Users aren't able to find `refresh dbt`, and until we have GitHub actions working _**and**_ deploys to your Lightdash instance are automatically updated, then having this more than one click away is disruptive. 

https://github.com/lightdash/lightdash/pull/3260

https://lightdash.slack.com/archives/C02DGV9RWKV/p1663837964004469

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal - we might not need to revert it. This might be a comms issue if we add it to Headway etc. so people know how to do it. And maybe we can add a shortcut that triggers Refresh dbt if we don't want to clutter the Explore view instead.

**Comment by TuringLovesDeathMetal** [comment]
@hamzahc1 the trouble is that it's multiple clicks away now. 

So if you have work in progress, then you go to click `refresh dbt`, you have to leave the page (oh no! all my unfinished work is now gone :( ) and then go to `settings` to refresh dbt. 

I think it will move from where it was originally, but until we have a better idea of where, we should just move it back. 

Does that make sense?

**Comment by rephus** [comment]
I agree with Katie, I find it a bit annoying now that I need to leave the explore when I'm testing locally my schema.
