### ISSUE TITLE
Add Date Filter Operator "is NOT in the last"

### ISSUE THREAD

**Issue by IsaiahALeBlanc** [lightdash/lightdash#3315]
### Description

Add date filter to include `is not in the last` time period.

### What problem does this solve?

This allows users to create line graphs that represent rolling averages in which every time period represented in the graph has completed. Currently, there is no way to exclude the "last X time periods from current day" which shows incomplete data on the chart that users would like to exclude (ex. If the x-axis on a chart is in weekly intervals, I would like to exclude the last 1-week from current day to avoid showing data for a non-complete week).

Lightdash currently supports "in the last"  as shown in the screenshot below.
![Screen Shot 2022-09-26 at 11 37 50 AM](https://user-images.githubusercontent.com/96076287/192320725-198af47f-9d86-4afd-af68-22509257d1c6.png)

Lightdash may be able to add a date FilterOperator to the [queryBuilder.ts](https://github.com/lightdash/lightdash/blob/f4978f5b6779be0dcefa0f92d5bf3e64d4ee33df/packages/backend/src/queryBuilder.ts#L134)

as well as update the Front end [DateFilterInputs.tsx ](https://github.com/lightdash/lightdash/blob/f3346b727337c663625cb867424fc9115a3e4335/packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx#L152)

to allow this updated change to display in the front end.

### Acceptance critiera

- [ ] there is a new operator for date/timestamp values which is `is not in the last`
- [ ] If today is June 14th, I'd expect `not in the last 7 days` to filter for data that is not in June 8th - June 14th. 
- [ ] If today is June 14th, I'd expect `not in the last 7 completed days` to filter for data that is not in June 7th - June 13th. There would still be data for June 14th included (i.e. June 14th would not be filtered).

### Documentation

- [ ] update filter reference docs with new filter type: https://docs.lightdash.com/references/filters

**Comment by ZeRego** [comment]
I think we need to change the scope of this ticket.
We should have the option NOT in all operators instead of duplicating all operators
