### ISSUE TITLE
Viewing underlying data from chart only filters by dimension value

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3318]
### Description

Currently viewing the underlying data from a chart is the same as viewing the underlying data from the dimension in the results table. 
If should be the same as viewing the underlying data from the metric in the results table.

### App Version

0.265.0

**Comment by rephus** [comment]
I'm not sure I understand this issue... 

[Screencast from 30-09-22 12:36:36.webm](https://user-images.githubusercontent.com/1983672/193252354-bb17a8ab-205a-482f-af5e-dadb9d4bfca9.webm)

**Comment by TuringLovesDeathMetal** [comment]
@rephus here's the issue reported by the user 👀 https://lightdash.slack.com/archives/C03EC7PCW8H/p1664216391947369?thread_ts=1664216150.711599&cid=C03EC7PCW8H

Not sure if this is helpful at all?

**Comment by rephus** [comment]
@ZeRego are you taking this ? I'm happy to do it otherwise
