### ISSUE TITLE
I want to be able to remove the option to show hidden tables in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3322]
### Description

Right now, we have the option to show specific models as the "main" models in Lightdash. But, you can click on `show hidden tables` and see _**all**_ of the dbt models in Lightdash. 

this is great, but sometimes, we don't want some specific tables appearing in Lightdash at all (e.g. PII data)

I want to be able to hide the `show hidden models` option from the app. 

- [ ] I'd imagine it would live here:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/31848148/192752001-4d5d9d82-bc67-452e-a54a-ef70e0443f06.png">

- [ ] There would be a toggle under `table selection`, `show entire project...etc.` which says  **Option to show hidden tables**. This has a toggle for `on` and `off` (by default, this would be set to `on`)

- [ ] Only project admins would have access to this toggle

**Comment by Martin-Carlsson** [comment]
@hamzahc1 @TuringLovesDeathMetal 
I was just about to say that 
See: #3111

However, I would like to give *nearly* all users the **Editor** role ... because, all users would need to have access to the **Table Explorer**

**Comment by hamzahc1** [comment]
>I don't think viewers have show hidden tables 🤔

They do today 😊 but we should remove this. Also looking at Martin's suggestion in #3111 for more differentiation in the editor roles makes sense - where there are folks you'd want to be able to create content with what's already been set up for them (i.e. an editor) but not run raw SQL or have further access to data or tables (maybe even limit which spaces they can save to?) VS a project developer who would (i.e. the current permissions level for an editor in Lightdash)

**Comment by TuringLovesDeathMetal** [comment]
It sounds like having an option to `remove option to show hidden tables` might actually be what you're looking for 🤔

**Comment by Martin-Carlsson** [comment]
> 
It sounds like having an option to remove option to show hidden tables might actually be what you're looking for 🤔

Yes, I 100% agree

**Comment by TuringLovesDeathMetal** [comment]
Cool - I might update this ticket then!

**Comment by owlas** [comment]
Splitting this into two tickets:

- (this ticket) removing the ability to show all tables
- (new ticket) adding `hidden: true` to models in dbt
