### ISSUE TITLE
Unreadable errors in CLI

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3323]
### Description

CLI error shows `[object Object]` instead of useful message.

### To Reproduce

1. set wrong token during login
2. run set project command
```
lightdash config set-project --verbose
> Making HTTP query to: https://lightdash.arcadia.com/api/v1/org/projects
[object Object]
Error: [object Object]
    at /opt/homebrew/lib/node_modules/@lightdash/cli/dist/handlers/dbt/apiClient.js:126:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: [object Object]
    at /opt/homebrew/lib/node_modules/@lightdash/cli/dist/handlers/dbt/apiClient.js:126:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### App Version

0.266.0

**Comment by rephus** [comment]
I think this error was fixed already on a previous version. 

![image](https://user-images.githubusercontent.com/1983672/193996921-19dd6746-4763-4714-b098-76714b145099.png)

Closing
