### ISSUE TITLE
Prevent number styling 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3325]
### Description

Config a column in yml to have no styling with `style: NONE` or `format: NONE` 

```name: year
     meta:
        dimension:
          type: number
          style: NONE
```

### What problem does this solve?

![Screenshot 2022-09-28 at 09 31 56](https://user-images.githubusercontent.com/9117144/192730165-21220e20-302e-4c6c-a4f5-6bbfe3a6703a.png)

All numbers are being styled like this but there are cases where we don't want that. Example: year and ids 

This might be related to the ticket #1990

**Comment by TuringLovesDeathMetal** [comment]
Can we make this `separator` = `None`

The reason being, I think that eventually we'll have a set of different "style" parameters for numbers:

- decimal places
- prefix
- suffix
- thousands separator
- compact (100k, 10k, 1k, 1million, 100million, etc.)
- scientific notation
- percentage
- rounding

We can set `style` = `none` to turn off _**all**_ of these style options 🤔 or I think we can just set `None` for each of them manually?

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal Yup, that's why I mention this might related to #1990. 

Should we close this ticket and discuss all the styling configurations in that ticket ?

**Comment by TuringLovesDeathMetal** [comment]
sure! 

Other option would be to have a ticket-per-styling and then have them all under a `number styling` milestone? 

I just feel like there will be separate discussions for each one (and how they're implemented/what are the edge cases)

**Comment by TuringLovesDeathMetal** [comment]
we also have this open issue: #2216

**Comment by TuringLovesDeathMetal** [comment]
So I feel like this might actually be a duplicate
