### ISSUE TITLE
If I have no projects, I shouldn't get the project selection prompt in the CLI when I login

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3329]
### Description

When I first create a project on the CLI, I don't have any existing projects. But, when I login, I get the project selection prompt
<img width="646" alt="image" src="https://user-images.githubusercontent.com/31848148/192779568-891e9c78-b6b9-4521-91f6-f849c853a852.png">

I should only be prompted to select a project if I login and there is at least one existing project.

**Comment by rephus** [comment]
I thought I fixed this, but let me test it again..

**Comment by rephus** [comment]
I get this on a new account 

![image](https://user-images.githubusercontent.com/1983672/192964309-a3f13544-6842-40b8-8c3d-6eaa5d71e2c5.png)

We should probably change it to `there are no projects, create one using deploy --create` or similar if this is going to be the first thing they see.

**Comment by rephus** [comment]
Also, could you take screenthos with --verbose flag ? so I can see what's the URL we're using and everything

**Comment by rephus** [comment]
Right, is it possible that the org has projects, but you don't have access ?
