### ISSUE TITLE
Filters general: Inconsistent styling on filters form

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#333]
<img width="854" alt="Screenshot 2021-08-10 at 11 25 43" src="https://user-images.githubusercontent.com/11660098/128851304-d53d9715-0a76-415f-a626-af016c381983.png">

* Text size of values in input boxes is inconsistent
* Increment buttons on number input box are not aligned correctly

**Comment by ZeRego** [comment]
Closed by: #207
