### ISSUE TITLE
Analytics events for new onboarding flow

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3332]
### Description

1. webapp event: `onboarding_getting_started_docs_click`
2. Webapp event: `onboarding_create_project_manually_click`
3. If we add a `copy` button for the code, can we add a webapp event: `onboarding_copy_code_block_click`
4. Can we add a parameter to the `project_created` event where we have a `method` field that's set to `manual` or `cli` depending on how the project was created (this would be for onboarding + new projects created _**not**_ in onboarding as well!)
<img width="457" alt="Screenshot 2022-09-28 at 15 45 39" src="https://user-images.githubusercontent.com/31848148/192810406-0d11e68e-50f0-4a7c-b5f2-7628b0076c1c.png">

^same event as (2), but for creating a new project _**not**_ in onboarding
- webapp event: `new_project_create_project_manually_click`
<img width="416" alt="image" src="https://user-images.githubusercontent.com/31848148/192812439-ca5f38e6-ff07-4b86-8f6e-d12ef9f06911.png">

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal do we also want events to indicate that project creation has started. something like: 

`onboarding_started_creating_project`
`new_project_started_creating_project`

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani when would we trigger these? When they hit that `copy these commands` screen?

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal when they land on this screen

![image](https://user-images.githubusercontent.com/962095/193248168-3f1fc06f-8d95-42f0-8a67-0ed78b8e50a0.png)

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani nice! ya, that would be great :) 

Would this be a backend event? (i.e. lightdash_server)

If yes, let's maybe try to keep it a name similar to project created. Something like `start_project_created` and then we can include a parameter in it called `page` or `path` which is tells us the path where this was triggered? (so I can figure out if it's been triggered in onboarding or after onboarding)

**Comment by ZeRego** [comment]
We do have the event when the create project page loads ( FE event ) so we could diff that event time with project created time. 
I don't think there is any BE event triggered at this point beside the token creation, do we want to have some flag in this event to distinguish between when user did it and when we auto generated it in this page ?

**Comment by TuringLovesDeathMetal** [comment]
^ooh @ZeRego smart idea. 

in the `token created` could we add a parameter for this? I can't think of a good name 😅  `location` sounds terrible

>We do have the event when the create project page loads ( FE event ) so we could diff that event time with project created time.

This is great, except FE events only trigger for ~60% of users 😢 so if we had an event that was a BE event, that would be ideal.

If we can't, I'll survive with a FE event for the page load (as long as it includes the `project_id` as a parameter!)

**Comment by IrakliJani** [comment]
@ZeRego @TuringLovesDeathMetal how do we distinguish onboarding vs existing users?
is it `is_setup_complete` field in the db?

**Comment by IrakliJani** [comment]
if so, does that happen once the user completes filling in user/org details or after user creates first project. if not then I have to add a new field in the DB. because checking if user has no projects is not good enough (if user deletes all existing projects and tries to add a new one is not onboarding))

**Comment by ZeRego** [comment]
> If we can't, I'll survive with a FE event for the page load (as long as it includes the project_id as a parameter!)

Page events dont have the project id.

> in the token created could we add a parameter for this? I can't think of a good name 😅 location sounds terrible

Currently the `personal_access_token.created` doesn't have any metadata, so we could change it to have:
`userId: string`
`auto_generated: boolean`

**Comment by ZeRego** [comment]
>  how do we distinguish onboarding vs existing users?

We can check if the org never had a project_created event.

**Comment by TuringLovesDeathMetal** [comment]
> Page events dont have the project id.

hmm....how complicated is it to add it? 

> We can check if the org never had a project_created event.

Yep, that's fine - but once you've created your first project, there's no way of tracking how long it takes to create other projects (since there's no way of linking a `project create started` to a `project created` using the `project_id`)

**Comment by TuringLovesDeathMetal** [comment]
Okay, summary of what we want to do so far:

1. FE event for `onboarding_start_project_created` + `new_project_start_project_created`. If they're FE, we may as well create separate events for them since it's weird to have one FE event for multiple pages in the app in case one of them changes but the other doesn't.
2. Can we add `project_id` to FE events?
3. for `personal_access_token_created` we want to add `user_id` + `auto_generated` (boolean)

am I missing anything?

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani two things:

1. is there a way of knowing whether the project was created from the CLI or from the `manually create project` page? (if yes, can we please add this to the `project created` event 🙏 ). Something like `method` = `cli` or `manual`

2. Right now there's an `is_preview` parameter in the `project_created` server event. Will the CLI-created projects be set to `is_preview` = `true`? (I want them to have `is_preview` = `FALSE` because I filter `is_preview` = `TRUE` from our data right now)
