### ISSUE TITLE
Support private dbt packages

### ISSUE THREAD

**Issue by Aylr** [lightdash/lightdash#3335]
### Description

Some method to authenticate to private dbt packages hosted in GitHub repositories. dbt Cloud supports this via environment variables: https://docs.getdbt.com/docs/building-a-dbt-project/package-management#private-packages

### What problem does this solve?

This would allow projects with private packages to use Lightdash.

**Comment by TuringLovesDeathMetal** [comment]
Hey @Aylr! Thanks for raising this issue :) 

We actually support dbt environment variables! They're just a bit hidden in the project connection page 👀 (I also just noticed when you search `environment variables` in docs.lightdash.com, it brings up a page about `lightdash.yml`...not very helpful 😓 )

You can add environment variables in the `advanced settings` option in your project connection. 

Here's a quick video showing you where to find them: https://www.loom.com/share/0967a544e8ba42b3bd4394c03e167c6f

Let me know if that doesn't work!

**Comment by ZeRego** [comment]
Closing this ticket since we have users using private packages already.
