### ISSUE TITLE
Creating spaces is tricky when you're not on the homepage.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3339]
### Description

It actually took me a few seconds to recall how to create a space. I was hovering around the list of spaces (i remembered that it was under browse). But was like, should I be able to see a list of all spaces somewhere like full screen (all spaces?…)

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/31848148/192980340-9c26c5c5-442e-43c3-92c6-a38efd37ca6b.png">

Then I remembered the action only exists on the homepage! So had to click the lightdash icon then saw the option.
Is that actually correct? Or is there another way.

Edit: just discovered there’s an action under the move to space menu (see screenshot below)

<img width="997" alt="image" src="https://user-images.githubusercontent.com/31848148/192980403-0865224f-fb99-4fb3-8c1e-d16f415464c9.png">

**Comment by PriPatel** [comment]
You can now create a space from anywhere in the app from the Navbar!
There is a separate open ticket to create a new page for "All Spaces".
