### ISSUE TITLE
GitHub action for `lightdash deploy` should work even if my dbt project isn't in my root directory

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3345]
### Description

Right now, if I have a dbt project that I'm trying to connect our `lightdash deploy` GitHub action to and it's not in the root repo (i.e. it's in `my-repo/dbt/models` instead of `dbt/models`), then I get this error:

`invalid project dir`

We should add some default folders, or use a find script to locate the yaml file inside the repo so that this error doesn't happen.

**Comment by rephus** [comment]
I think there are a few ways of doing this (sorted by preference ASC) 

1 - The user must update the action.yml file manually to add the folders in different places (lightdash / dbt command) by following the documentation. Not great for the user. I'd like to avoid updating that file 

2 - The user must add a new secret DBT_FOLDER that we can use on the script (if empty, we assume the config is on the root) 

3 - Add some common folder names we can support (eg: dbt, schema, lightdash, etc...) then we do || to run them (this can make the command run and fail several times... ) 

3 - Modify the CLI to find in subfolders the `dbt_project.yml` and use it as a folder if the file can't be found on root (i don't think this should be solved on the CLI)

4 (my reference) - use `find` to locate teh dbt_project.yml and use it as default folder (could cause some issues if there are many files ? what do we do in that case ? )

```
$/home/rephus/work/lightdash-analytics 
>find . -name "dbt_project.yml" 
./dbt/dbt_project.yml
```

**Comment by IrakliJani** [comment]
@rephus ➕ to 5. we can use .gitignore and sane ignore file for the search. fallback to 3 (show instructions within the CLI) if search takes too long or dbt_project.yml is not found.

**Comment by owlas** [comment]
Would 5 work if I had multiple dbt projects in a mono repo structure??

**Comment by rephus** [comment]
> Would 5 work if I had multiple dbt projects in a mono repo structure??

I'd take the first result in that case

**Comment by IrakliJani** [comment]
@rephus  what about showing all projects and letting the user select

**Comment by rephus** [comment]
> @rephus what about showing all projects and letting the user select

We're talking about github actions, so the action can't be interactive

**Comment by rephus** [comment]
Tested 3 here : https://github.com/rephus/dbt_solar_panels/pull/2

I agree it is a safer option than 5. and users can skip this step if they don't have subfolders

**Comment by IrakliJani** [comment]
oh I see, that would be a nice UX for users who execute CLI `lightdash deploy` locally

**Comment by rephus** [comment]
so in the standup we decided to go with option 5. We can't support multiple projects with option 5, but we can't support multiple actions when using secrets on option 3 anyway. So it is a reasonable limitation for now.

**Comment by rephus** [comment]
Tested option 5 https://github.com/rephus/dbt_solar_panels/actions/runs/3158347054/jobs/5140278661
![image](https://user-images.githubusercontent.com/1983672/193258822-036aac9b-f9c2-4004-9cb6-38221bef79dc.png)

**Comment by ZeRego** [comment]
@rephus that looks good 👍 I would go with that right now and ignore the cases of multiple dbt projects in the same repo.
