### ISSUE TITLE
Be able to configure hiding models in .yml

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3348]
I want to hide certain dbt models in Lightdash. I can this through the UI using table filtering, but I want to manage it as code.

Example:

```yaml
models:
  - name: users
    meta:
      show_in_tables_list: false
```

### Questions: 

Right now, we use `hidden: true` for metrics + dimensions to hide them. The reason I changed the wording to `show in tables list` for models is because the tables can still be used in joins/shown in the list of tables if it's joined in the explore view, but it's just hidden from the tables list. So, `hidden` felt a bit unclear. 

But, maybe it would be more useful to name it something similar to the page in the UI? Like `table_selection_include` or something? Or maybe we just rename the stuff in the UI to match (so `show in tables list`)?

### User story

I want to be able to include a table in a joined model (e.g. I want to join `users` to `companies`), but I don't want the joined model to appear in the sidebar list of explores. (e.g. I don't want `users` to appear as an option to explore independently)

### Acceptance criteria:

- [ ] I'm able to hide models from the `tables` list, but have them appear in joins in Lightdash using the meta parameter `show_in_tables_list: false`.
- [ ] The default value is `true`
- [ ] If a model is hidden using the meta parameter in the .yml, but it isn't included in the list of hidden tables in the UI, then it is still hidden from the `tables` list, but can still appear as a joined table in Lightdash. 
- [ ] if a model is hidden using the meta parameter in the .yml, but it's not included in the list of hidden tables in the UI, then it's still shown in the list of "selected models" in the `Table configuration` in the project settings page:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/31848148/230335893-40369fe5-df30-4725-8626-cec2ae1b3ade.png">

**Comment by olly-writes-code** [comment]
+1 on this!

**Comment by jw-aleksandr-zolotukhin** [comment]
+1

**Comment by owlas** [comment]
@TuringLovesDeathMetal is this the same as #4596 ?

**Comment by ZeRego** [comment]
@owlas not really. 
That ticket is specifically to hide joined tables. eg: A joins to B and B joins to C. I only want the user to pick dimensions/metrics from A and C. B is only relevant to build the join in the SQL.

**Comment by Kobold** [comment]
Still relevant.
