### ISSUE TITLE
I want to be able to make some tables in Lightdash less prominent than others (group labels for tables)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3353]
### Description

I want to be able to streamline the `tables` page so that people can see which models they should be prioritizing to explore from when they first land in Lightdash!

I want to minimize the amount of content overload for folks who aren't on hte data team and are seeing hte company data for the first time in Lightdash. 

Example of where I'd use this: I have some complicated tables that analysts use for specific purposes/requests/dashboards. But, these aren't really useful to the rest of the people at my company (they're too complicated!)

Related to https://github.com/lightdash/lightdash/issues/858

Some ideas considered:
- Folder for explores?
- Group labels (similar to dimensions/metrics in the sidebar) and some are default collapsed vs. default expanded 

^I'd prefer option 2 - folders feels like it's too "group-y" and permanent. I'd also expect to add permissions based on these folders, and I don't want that. Group labels feel like a more lightweight thing for a more lightweight problem especially if there's a `toggle` option that you can set to be default on or off. 

Here's what I imagine it would look like in the .yml:

```yaml
models:
  name: users
    meta:
      group_label: "Key company tables"
```

### Acceptance criteria

- [ ] I'm able to group tables together using `group_label` in my .yml
- [ ] I imagine it would look similar to the toggles/nesting we have in the sidebar of a table
<img width="264" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/7029e2d0-83ec-4e63-83e7-b0135eb386b7">

- [ ] group labels appear first in the list of tables, alphabetically
- [ ] Then, ungrouped tables appear after the grouped tables in the sidebar, alphabetically
- [ ] Tables within the groups are ordered alphabetically

For example, this is how I'd expect my sidebar to look:

```
> Accounting tables
> Finance tables
V Sales tables
    - EMEA Sales table
    - Revenue table
    - Very important sales table
- American products table
- Chinese products table
- Some other table
- Table called table
```

### Documentation

- [ ] add docs for `group_label` with tables to the tables reference doc here: https://docs.lightdash.com/references/tables
- [ ] add it to the table of config options (like int eh dimension reference sheet [here](https://docs.lightdash.com/references/dimensions#:~:text=millions%27%2C%20%27billions%27%2C%20%27trillions%27%5D-,group_label,in%20the%20sidebar%20with%20other%20dimensions%20with%20the%20same%20group%20label.,-urls))
- [ ] Add a sub-section in the docs (and link this to the table entry in the config table) describing what it does + a picture showing how the group labels for tables is formatted in the sidebar.

### Analytics events

- [ ] add `tables_group_label_count` to `project_compiled` event. This gives you the total number of tables that have group labels included in the project when it's compiled.

**Comment by Martin-Carlsson** [comment]
Another option could be labels/tags similar to those:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/7769335/193413921-980ffa60-0056-4d5e-a0bb-55f037efb633.png">

Also, I think that the table icon can be removed or changed to something else. Icons are great for letting users distinguish different objects. But in the Table list, we only have tables.

<img width="51" alt="image" src="https://user-images.githubusercontent.com/7769335/193413947-c56b8249-0e51-4d34-ba6c-d024e447647c.png">

**Comment by TuringLovesDeathMetal** [comment]
ooh great suggestions!

**Comment by mark-ogrady** [comment]
Great suggestions, I love the idea of using different icons - it is really effective in other tools like Notion to help separate content out from a list. 

The main use case for us is being able to collapse lists of tables under a heading (could be tag or even icon). 

Like @TuringLovesDeathMetal I prefer labels to folders - just want a way to simplify what business users see when logging on

**Comment by TuringLovesDeathMetal** [comment]
I'm imagining that this config would live in your .yml

So really similar to what we have now for `group_label` for dimensions + metrics. 

So something like:

```
version: 2
models:
  - name: users_daily
    description: >-
      Gapless date table which has daily summary stats about users. One row per
      user per day since the user was created.
    meta:
      group_label: 'Users'
```

Then this would pop up under a `Users` label which is just a collapsible group (just like in a table sidebar)

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel just wondering how this fits in with some ideas you have for the new navbar!

**Comment by XiaozhouWang85** [comment]
When choosing which table to use, the right hand panel is not actually used.

After selecting an explore, Lightdash jumps to a different page anyway.
<img width="832" alt="Screenshot 2023-04-07 at 09 48 28" src="https://user-images.githubusercontent.com/42941066/230576899-8b5f6c86-5a62-424d-8131-577f14356042.png">

Potentially using the full page would open up more options for styling in terms of icons, grouping etc

**Comment by PriPatel** [comment]
We've had another user request for this:

> It would be great to have some sort of organisation in the Tables menu on the LHS of the query window. Eg I have several Tables that relate to revenue. An option to organise these to live under a drop down called ‘Revenue’ would be ideal, to de-clutter the list.

**Comment by Martin-Carlsson** [comment]
> Another option could be labels/tags similar to those:
> 
> <img alt="image" width="249" src="https://user-images.githubusercontent.com/7769335/193413921-980ffa60-0056-4d5e-a0bb-55f037efb633.png">
> 

A follow up on my [previous comment:](https://github.com/lightdash/lightdash/issues/3353#issuecomment-1264380729)

If a group structure is implemented, then I **can't** think of any good reason to use properties, tags, or labels.

**Comment by Martin-Carlsson** [comment]
Something to consider:

Should `group_level` have **description**?

So you get a informations when you hover over a `group_level`.
