### ISSUE TITLE
I am able to create a project using wrong oauth credentials

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3356]
### Description

I tried creating a project on bigquery (with a location: EU) , but it failed  

![image](https://user-images.githubusercontent.com/1983672/193277581-62ebfe76-c056-4c5a-8ad0-215092791541.png)

On settings, I get an error if I try to  `Test & compile project` 

but if I reupload the credentials.json, it works 

![image](https://user-images.githubusercontent.com/1983672/193277748-388b2413-593d-4981-953a-c3eab34cfd43.png)

It seems to be an issue with the credentials , it is probably taking by default some credentials in my home directory, unless I specify `GOOGLE_APPLICATION_CREDENTIALS`

we should make sure we can handle the errors gracefuly . Probably check if the connection works before creating the project . Or check that profiles.projectId matches credentials.projectId (add verbose if makes sense) 

### App Version

- v0.268.0

**Comment by rephus** [comment]
I think we are probably missing some details on the credentials here: https://github.com/lightdash/lightdash/blob/main/packages/cli/src/dbt/targets/Bigquery/oauth.ts#L28

**Comment by ZeRego** [comment]
You might need to look into the JWT object returned by google-auth-library.
I assume we need all the properties in there.  

node_modules/google-auth-library/build/src/auth/jwtclient.d.ts

```
export interface JWTOptions extends RefreshOptions {
    email?: string;
    keyFile?: string;
    key?: string;
    keyId?: string;
    scopes?: string | string[];
    subject?: string;
    additionalClaims?: {};
}
```

**Comment by ZeRego** [comment]
> It seems to be an issue with the credentials , it is probably taking by default some credentials in my home directory, unless I specify GOOGLE_APPLICATION_CREDENTIALS
@rephus but doesn't this also happen with dbt ? google lib picks the credentials from the default path unless a GOOGLE_APPLICATION_CREDENTIALS was specified.
