### ISSUE TITLE
Add error for `.com` instead of `.cloud` URL in Lightdash CLI login

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#3362]
### Description

Tried to log in to lightdash CLI but failed because I used https://eu1.lightdash.com instead of .cloud

We should warn people if they use the wrong domain.

**Comment by ZeRego** [comment]
@rephus that is a good idea, just a simple warning if domain ends in `lightdash.com`

**Comment by djayatillake** [comment]
ah yes exactly I'll close this issue, I typed in manually.

**Comment by TuringLovesDeathMetal** [comment]
Going to re-open!

I think it would be good to add a warning here 👍
