### ISSUE TITLE
I can add a single constant value reference line for a numeric field.

### ISSUE THREAD

**Issue by olly-writes-code** [lightdash/lightdash#3380]
### Description

A horizontal or vertical line used for reference vs the data visualized 

### Example user story

When I was doing analyses for demo week, I wanted to add lines to the chart showing when different events were so that people could easily pick them out in the graph. Here's an example of what I ended up building in Google Sheets:
https://www.loom.com/share/755c8cad166c48bf86bcaf855b6f66aa

Another example: Each quarter, we set goals for our KPIs. These are targets that we want to hit by the end of hte quarter. I really want to add these constant values to my chart so that we can see how we're progressing towards our goal.

### Sketch

Here's a sketch of how this could work in Miro: 
https://miro.com/app/board/uXjVP9qJWMk=/?share_link_id=624411838486

### Acceptance Criteria

- [ ] I'm able to plot lines that are constant values on my chart
- [ ] These lines can be vertical or horizontal
- [ ] I can only add reference lines to numeric series in my chart. 
- [ ] I can only add reference lines based on the fields that are selected to plot on the x-axis or y-axis in my chart (i.e. I can't use fields in my results table that aren't in my chart and I can't use fields that are selected in `groups`).
- [ ] I can only add one reference line to my plot

**Comment by TuringLovesDeathMetal** [comment]
We have an open issue that's similar here: #2728 

This feels like one of the types of trend lines. Maybe it'd be easier to break it up into the specific trend lines like you've done here?

Here's my dream list ordered from highest to lowest "I want this!":
1. a horizontal reference line that's a static value (e.g. goal num users = 500)
2. a vertical reference line that's a static value (e.g. date of launch = `2022-01-01` - kind of related to https://github.com/lightdash/lightdash/issues/2647)
3. a horizontal reference line that's variable (this is a straight line, but it's variable - I'd want this for average, median, max, min)
4. line of best fit (e.g. trend line fitting number of signups over time)

Do you think anything's missing here? Or the ordering of any of them is different for you??

**Comment by olly-writes-code** [comment]
@TuringLovesDeathMetal - very much agreed with that ordering!

I think that reference lines (points 1-3 might) be a bit different from trend lines.

Looker documentation characterizes them as distinct.

[Looker on reference lines](https://cloud.google.com/looker/docs/line-options#add_reference_line)

[Looker on trend lines](https://cloud.google.com/looker/docs/line-options#add_trend_line)

**Comment by TuringLovesDeathMetal** [comment]
interesting! ya, there's probably a reason why they define them separately. Will take a look 👀

**Comment by TuringLovesDeathMetal** [comment]
@olly-writes-code I've updated the spec on the issue. Let me know if this would solve your problem!

**Comment by owlas** [comment]
@TuringLovesDeathMetal would it be too simplistic to simply add the reference lines to the axes (e.g. on the x or y axis), rather than applying them to fields and they may or may not show on the plot depending on the layout?

It seems more complex is there any benefit?

**Comment by TuringLovesDeathMetal** [comment]
oooh interesting idea @owlas 👀 

I guess I was thinking about how this might fit into `trend line` eventually (e.g. you'd be able to have `average` instead of `constant`). And for those, you'd need to base it off of a field.

Not sure if we should be thinking about that now though

**Comment by olly-writes-code** [comment]
> @olly-writes-code I've updated the spec on the issue. Let me know if this would solve your problem!

agreed with the spec changes. Thanks @TuringLovesDeathMetal !

**Comment by ZeRego** [comment]
For reference, echarts mark lines configuration: https://echarts.apache.org/en/option.html#series-line.markLine

**Comment by rephus** [comment]
:point_up: just what @ZeRego said, this is another example. https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpAC2jBwA1gAyvd7uCR7-jABGVP5ucbPoAGacw2AsHHTDYz19sNCMg_1r6yDAeBCQMAS0gxACAv6X6wlnF3QseGBeFcPA5gaQhGARDEwR4Zl8PM5cNEAET5dLImGkUHw0hwnGYFzRNQaYL42DY-G2L52OI09C2OwAbiAA

and https://echarts.apache.org/examples/en/editor.html?c=line-markline&reset=1&edit=1

**Comment by olly-writes-code** [comment]
Thank you!
