### ISSUE TITLE
Can't set password after signing up using SSO

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3415]
### Description

Can't set password after signing up using SSO

### To Reproduce

1. signup using sso
2. go to Password settings
3. try to set new password 💥

<img width="1254" alt="CleanShot 2022-10-06 at 12 31 59@2x" src="https://user-images.githubusercontent.com/962095/194262927-6e883ea9-b153-4334-841d-2b9826855dfa.png">

### App Version
v0.275.0

**Comment by TuringLovesDeathMetal** [comment]
#2846 

^I feel like this was similar 🤔 but maybe I'm wrong...

**Comment by ZeRego** [comment]
The ideal solution described by @owlas was: if the user has no password, display a button to reset the password ( same email as to recover the password ). We would need to have a endpoint that returns a boolean ( hasPassword: boolean )
