### ISSUE TITLE
If you have date on the x-axis, there should be a quick way to change the granularity

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3420]
### Description

If I have `date` or `timestamp` on my x-axis, I should be able to quickly change the granularity of a metric. 

- this would only work for metrics on the y-axis (not dimensions or table calculations)
- you need to have a timestamp or date on the x-axis
- We would have a default set of time intervals: day, month, year

Here's how it works in Google Analytics: 
![image](https://user-images.githubusercontent.com/31848148/194501097-ea4e198c-5b5d-4c2c-bfa4-ef721444292e.png)

**Comment by JakeC-MyT** [comment]
@TuringLovesDeathMetal Just to add a big plus-one to this one! Having to make 4 charts for daily/weekly/monthly/quarterly for any given metric is a big time-sink and ends up taking up 4x as much space on the dashboard, so I would LOVE to see something like this feature rolled out

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate in favour of https://github.com/lightdash/lightdash/issues/6119
