### ISSUE TITLE
The settings icon in the navbar should provide you options for which type of settings you want to update

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3426]
If you are an org admin, you should see an option to access the **current** project settings directly, or access the organization settings.  This saves the user several clicks to get to the project settings. 

If you are just a viewer, the settings icon doesnt need a dropdown and can take you straight to your profile. 
<img width="268" alt="Screenshot 2022-10-07 at 15 45 32" src="https://user-images.githubusercontent.com/12776522/194581025-1d301360-d6cd-4d12-824f-0efa2eee9465.png">

**Comment by IrakliJani** [comment]
@PriPatel slight change idea. what if we always put profile settings under profile menu and hide the gear icon when you don't have enough permissions?

![image](https://user-images.githubusercontent.com/962095/197817120-291fd650-9874-4658-8ca1-5b94b73ab341.png)

**Comment by PriPatel** [comment]
AHHH I was just about to you message you something similar. Great minds!

I was going to say maybe under the avatar, you have a link to the user settings as well! Because I would look under the avatar to update my password for example, but Org settings and Project Settings might not cover it!

Love the idea of hiding the gear when you dont have org or project setting access!
