### ISSUE TITLE
Unable to access Saved Charts

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3443]
### Description

No longer able to view or edit certain Saved charts (split by month). However, these Saved Charts can still be added to a Dashboard and viewed from there.

I suspect this has to do with some backward incompatibility with a breaking change of [Date Intervals](https://github.com/lightdash/lightdash/pull/3306) or perhaps a different feature. Unfortunately I can't access the chart to view configuration.

Solution:
I don't think there is going to be much demand for backward compatibility, however, something with longer term value might be:
1. Ability to access the chart even if there are errors.
2. Ability to edit the code of a chart (which might be part of larger ask to be able to export and import charts between deployments)

### To Reproduce
https://user-images.githubusercontent.com/7281432/194908115-d363c85f-eecc-4590-9035-0a7236e6f893.mp4

### App Version
v0.280.1
Cloud version of Lightdash eu1.lightdash.cloud

**Comment by ZeRego** [comment]
Most likely related to this error https://github.com/lightdash/lightdash/issues/3444

**Comment by ZeRego** [comment]
@gordonkjlee what interval values do you have in your YML ?

**Comment by gordonkjlee** [comment]
```
time_intervals:
            - day
            - week
            - month
            - quarter
            - year
```
            
Even when I create a new chart, and I expand my timestamp field, the chart redirects to a blank page.

I'm going to remove the time_intervals from my .yml file and resync the dbt project.

However, I think this might suggest a wider conversation about possible developments:
1 Ability to access the chart even if there are errors.
2. Ability to edit the code of a chart (which might be part of larger ask to be able to export and import charts between deployments)

**Comment by gordonkjlee** [comment]
I've done this, and am now able to access the charts.

**Comment by ZeRego** [comment]
>Ability to access the chart even if there are errors.

I do agree that the entire page shouldn't go blank. Created an issue to add error boundaries so only parts of the page would display an error. https://github.com/lightdash/lightdash/issues/3459


> 2. Ability to edit the code of a chart (which might be part of larger ask to be able to export and import charts between deployments)

There is an open discussion to have every content as code:
https://github.com/lightdash/lightdash/issues/369
