### ISSUE TITLE
It's not obvious that you need npm on createProject/cli

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#3445]
Problem:
- A user today had difficulty onboarding.
- They were relatively new to working in the terminal. 
- On the createProject/cli screen after signing up for Lightdash, they copied the code block under "Inside your dbt project, run:" and pasted it into the terminal.
- It didn't work because they didn't have `npm` installed. They were using a mac, and `npm` isn't installed by default on macs.
- As we have made the beta public, we are going to get more users of this ilk.

Solution:
- We should make it clear at this stage that npm is required for the CLI, and ideally, provide instructions on how to install it for a variety of operating systems.
- Alternatively (or in conjunction with the above), we could make it clearer for people who aren't experienced with the terminal that they don't need to do this, and can just create the project manually without the CLI. The CTA beneath the code block isn't very obvious.
- In any case, in our getting started docs, we should also add npm installation instructions.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/9979944/194915785-0a950bd4-4344-4d31-8949-d176d4be21f9.png">

**Comment by IrakliJani** [comment]
getting started docs instructions in this PR https://github.com/lightdash/lightdash/pull/3475#issuecomment-1277688758
