### ISSUE TITLE
Allow to colour a series based on a different dimension

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3449]
### Description

I have a filter on a chart for the last 6 months.
<img width="377" alt="image" src="https://user-images.githubusercontent.com/7281432/194940123-2db08b87-83a1-48a7-8a55-083c462e4e24.png">

I have also sorted the series by month in new-old order.

Last month (in 2022-09), I had coloured the then-current month in Orange. However, when this month (2022-10) came around, 2022-09 was still coloured in Orange, and the current month was at the bottom of the legend with a new colour. This is not expected behaviour.
<img width="322" alt="image" src="https://user-images.githubusercontent.com/7281432/194940245-dbd8889a-6193-4d38-905f-351be771b7d1.png">

I gather that in many cases, we will want to colour items based on their name, i.e. for series "Books" to always be Blue even if new items are introduced that could change the order. As such, the solution is probably to allow the ability to colour a Series based on a different dimension.

### What problem does this solve?
For my use case, I could colour month (2022-10, 2022-09) etc based not on their names, but on a separate dimension that contains values such as "M0", "M-1", "M-2", etc.

Other use cases off being able to colour a series based on a different dimension:
1. Colour items based on whether they are above or below a target
2. Colour items based on whether they have increased or decreased from last month
3. Colour based on categories

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. 

Instead, I think there are a few other issues which are related/very similar (this feels a bit like a duplicate)? 

There's an issue around adding conditional formatting to bar charts/charts: https://github.com/lightdash/lightdash/issues/9761

And there's an existing feature where you can create constant colours for dimension values in your .yml files (described here): https://docs.lightdash.com/references/dimensions#colors

Will reopen if its requested by more users!
