### ISSUE TITLE
Disable `refresh dbt` button for certain setups

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3460]
### Description
If you're:
- connected to a warehouse
- not connected to a hosted dbt project (i.e. local dbt project)
- Then, disable the refresh dbt button

The "disabled" state should be greyed out text, with text on hover that says:

> You're still connected to a local dbt project. To keep your Lightdash project in sync, you need to update your dbt connection. [Find out how to do that here](https://docs.lightdash.com/get-started/setup-lightdash/connect-project#2-import-a-dbt-project). 

### What problem does this solve?

People are clicking on `refresh dbt` and it's giving them an error

Having the button disabled instead of disappeared means that we have another entrypoint for getting people to update their connection information (instead of just relying on the intro tour in Intercom).

**Comment by ZeRego** [comment]
Technical note:
1. We should add a `DbtProjectType.NONE` or similar
2. Support that type in the form (UI) and a callout saying they will have to sync their explores via the command `lightdash deploy` 
3. Use that type when creating projects from the CLI ( also previews )

**Comment by rephus** [comment]
ok, I think I understand now. This is supposed to affect only those who created the project from the CLI, on cloud, right ? 

I'm happy as long as it doesn't change our local environment (so we need to ensure it is only happening on cloud)

**Comment by ZeRego** [comment]
> ok, I think I understand now. This is supposed to affect only those who created the project from the CLI, on cloud, right ?

correct 👍 

> I'm happy as long as it doesn't change our local environment (so we need to ensure it is only happening on cloud)

Agree, dev env and users using the `DBT_PROJECT_DIR` env var should still be able to use the "local dbt server" option and have "refresh dbt" button.

**Comment by rephus** [comment]
I also need a new panel to replace this @TuringLovesDeathMetal 
We can do it on a separate issue if you like 
![image](https://user-images.githubusercontent.com/1983672/195527333-ec3f26db-7db9-4066-9854-65fe90387e43.png)
