### ISSUE TITLE
I want to specify the type for my table calculation

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3469]
### Description

By default, if we can't guess the type of a table calculation, we assume it's a `value` ( aka number). This can lead to some weird things happening in charts (e.g. when you make a table calculation where the output should be a date). 

But, we also assume that a table calculation is a `string` whne you use it in a filter. 

Users should have the option to specify the `type` in the table calculation config. 

This is kind of related to #3454 . I imagine the `format` options would change depending on the `type` you select. 

This is a comment from a user which is a good thought! We should try to get the format once the query is fetched (if you leave it as `default`) but I'm wondering if that will actually work with how we do table calculations today? (becasue you create teh table calculation, _**then**_ you run it - so we'd only fetch the first results after you created the calc).

> without results, i would argue that the state of the app is of little concern to the end user. you can certainly work around it with UX. for formatting options - i’m pretty sure most/all queries are required to run before they can show anything useful, so storing NULLas formatting specific options, then setting the default on first retrieval would probably work quite well. then the end user can choose any specific formatting options that they might want. i would certainly say using the response to choose an appropriate “default” type (maybe the user can override) is a better user experience.

### User acceptance criteria
- there is a drop-down menu in the table calculation where I can select the `type` I want
- By default, the type is `default` (I think that we assume table calculations are numbers? Except in table calculation filters where they're assumed to be strings by default...)
- The options match what we have as `types` available in yaml: string, number, timestamp, date, boolean
- if the values cannot be wrangled into the given type, then we give users an error at query runtime (e.g. `type selected for table calculation is not compatible with the values returned` or something like that)
- `formatting` options are limited depending on the type you select (you can only format numbers, not any other types)

**Comment by magnew** [comment]
We were asked about this today: https://lightdash.slack.com/archives/C04FQQU4RL7/p1690800331208779
