### ISSUE TITLE
Can't select September as a month filter

### ISSUE THREAD

**Issue by olly-writes-code** [lightdash/lightdash#3481]
### Description

I'm using the month filter, trying to select September. When I select September the SQL chooses the wrong month (October). 

<img width="963" alt="image" src="https://user-images.githubusercontent.com/7778402/195437439-cc757461-de4d-4668-b082-cc0411d8abef.png">

If I select August it changes to the correct month. Then if I try to re-select September it won't let me. If I then select October it sets the month as September (in the SQL).

The day date picker is also funky. It keeps putting the previous day in the SQL.

### To Reproduce

Add a month filter. Select September 2022. View the SQL.

### App Version
0.284.2

**Comment by TuringLovesDeathMetal** [comment]
![image](https://user-images.githubusercontent.com/31848148/195544152-806db36c-9f08-4173-acc9-e8ca57fdf4fb.png)

**Comment by TuringLovesDeathMetal** [comment]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/31848148/195544402-f6e6f107-8f9e-4a1a-aac3-f0812db883a1.png">

**Comment by TuringLovesDeathMetal** [comment]
That's definitely not the behaviour that's meant to happen. 

Someone else had a really similar issue the other week and we couldn't reproduce it. 

@olly-writes-code what data warehouse type are you using?

**Comment by rephus** [comment]
I'm trying to replicate this on our staging env against all different warehouses on a date and datetime month fields, it looks alright

<img width="885" alt="image" src="https://user-images.githubusercontent.com/1983672/195554452-461b07b5-a16f-4db4-a165-b74419ff342e.png">

What type of field you're trying to filter ? Do you get also get October on the SQL if you select a differnt month ? I'd like to know if it is doing Month + 1, or just defaulting to the current month

**Comment by olly-writes-code** [comment]
I'm querying redshift. Browsing on Chrome 106.0.5249.103. 

One thing that might be important. This is when using preview mode (if that makes any difference). I haven't tested it in normal deployed mode.

Let me see if I can catch some errors from the browser.

**Comment by olly-writes-code** [comment]
The data type is a timestamp

**Comment by olly-writes-code** [comment]
I can't see any obvious errors being thrown from the console. 

Another data point: 

When I click the column I want to filter on and select month and then select add filter (see images below). The default value in the filter is set to September in the visual (IDK why?), buuut the SQL says October
<img width="507" alt="image" src="https://user-images.githubusercontent.com/7778402/195705225-41fabd61-4de2-4e9a-a368-554e54d8b4f0.png">
 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/7778402/195705406-280e7121-3db4-41ce-9f15-3b1f16670f71.png">

<img width="701" alt="image" src="https://user-images.githubusercontent.com/7778402/195705492-6657149d-bf54-4ca9-96c5-605548954a51.png">

**Comment by olly-writes-code** [comment]
Confirmed this still exists on lightdash v0.287.0 and chrome 106.0.5249.119 (both the latest as of this message)

**Comment by rephus** [comment]
Nice ! thanks for sharing all your details. I'm able to reproduce it now ! I'll fix it asap :raised_hands:

**Comment by olly-writes-code** [comment]
Wow what an edge case!
