### ISSUE TITLE
Clicking `explore from here` in show underlying values should default to no fields selected

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3490]
### Description

When I click `explore from here` from the `show underlying values` table, by default, none of the fields should be selected. 

The filters from the original chart should still be applied (including the dashboard filters).

But, the `results` table should be empty

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal what if there are [underlying_values](https://docs.lightdash.com/references/metrics#show-underlying-values) defined? I think we should have those selected by default

**Comment by rephus** [comment]
I don't understand the problem you're trying to solve. If you don't select any field, what's the point of the `explore from here` . Do you mean on `results` table ? or perhaps on the `selected dimensions/metrics` on the chart

**Comment by ZeRego** [comment]
@rephus slack thread https://lightdash.slack.com/archives/C02DGV9RWKV/p1665662972274389

> if you don't select any field, what's the point of the explore from here

Going to an explore with the correct filters preset and then select the fields they want to see.

**Comment by TuringLovesDeathMetal** [comment]
^ya, eventually, I imagine you'll be able to select the columns in the UI that you want to `explore from here` with. But for now, having none selected, but the filters added
