### ISSUE TITLE
Rounding values to 1000 using round: -3 produces an error for numbers less than 1000

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3495]
### Description

I want to round my values to appear as thousands in my results table. 

To do this, I choose `round: -3`. 

But, if I have a value < 1000, then I get an error. 

If I have a value <1000, I'd just expect it to return `0`, not error.

**Comment by ZeRego** [comment]
Closing this in favour of the compact config https://github.com/lightdash/lightdash/issues/1990
