### ISSUE TITLE
Error when requesting a large amount of rows

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3498]
### To Reproduce

1. Increase query limit to 1000000. ( or similar )
2. Run query
3. server crashes or times out ( needs more investigation )
![Screenshot 2022-10-14 at 14 03 31](https://user-images.githubusercontent.com/9117144/195853780-e2589b49-bfeb-4c7c-b16c-1b32cb9e0d54.png)

### App Version

0.287.1

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal @owlas should we have a max row limit? We can have this configurable at the instance level where we can also increase the instance memory to handle a higher row limit.
What would be a reasonable limit? 

Looker seems to have a limit of 5000 https://help.looker.com/hc/en-us/articles/4419736340371-Filtering-and-limiting-data#:~:text=Looker%20supports%20up%20to%205%2C000,or%20fewer%20columns%20is%20recommended.

**Comment by TuringLovesDeathMetal** [comment]
If the app crashes, or performance seriously sucked above a certain level of rows, then we should set a row limit in the app to be less than that

**Comment by TuringLovesDeathMetal** [comment]
^It seems like this is standard in BI. 

Metabase has a 2000 row limit for unaggregated data: https://discourse.metabase.com/t/metabase-rows-limitation/6730

Supposedly there are no limits in Tableau 🤔 but I'm not too sure about this...

**Comment by ZeRego** [comment]
Ran a few tests manually to have an idea of the impact of the row limit.

Tests when querying 1 column:

|  Rows | Response Size  |  Response time | UI update/unresponsive time  |  
|---|---|---|---|
|500|    63kB |  2.09s | instant  |
|5000  |  613kB | 2.40s  | seconds  |  
|50000   |  7.0 MB |  7.04s | around 1 minute  |  
|100000   |  14.8 MB |  16.09s | around 5 minutes  |  

Tests when querying 2 columns:

|  Rows | Response Size  |  Response time | UI update/unresponsive time  |  
|---|---|---|---|
|500|    110kB |  4.38s | instant  |
|5000  |  1.1MB | 5.76s  | seconds  |  
|50000   |  11.7 MB |  15.50s | around 1 minute  |  
|100000   |  24.1 MB |  24.47s | around 5 minutes  |  

**UI update/unresponsive time** column is not only to load the results but also reflects on each user action that involves data. Example: change chart/table configuration

**5000** seems to be the value that provides the best user experience.

**Comment by TuringLovesDeathMetal** [comment]
^let's stick to 5000 then!
