### ISSUE TITLE
Filter input should "save" value when field focus changes

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3500]
### Description

Is common for users to write something in the filter input and run the query without pressing enter. 
When user focus moves away from the input field it should "save" the filter value.

### To Reproduce

![have to click enter](https://user-images.githubusercontent.com/9117144/195893784-11141082-5926-49fc-b970-dbaea6952352.gif)

### App Version

0.287.1

**Comment by hamzahc1** [comment]
I also find this really annoying on dashboard filters!! Will this fix update it there too?

**Comment by IrakliJani** [comment]
@hamzahc1 yep, its the same component. 👀 video in a linked pr

**Comment by jesshitchcock** [comment]
Regression of this in a dashboard here: 

<img width="800" height="241" alt="Image" src="https://github.com/user-attachments/assets/87aafa2a-d5b5-4012-ac7c-fc5231f51cb8" />
