### ISSUE TITLE
lightdash generate command ignores model custom alias

### ISSUE THREAD

**Issue by davidpeitinho** [lightdash/lightdash#3505]
### Description

Aliases and custom names using macros are ignored when using the `lightdash generate` command.

### To Reproduce

1. add an alias to the config block on a model
2. execute `dbt run`
3. execute `lightdash generate`
4. the yml file generation will fail with the message "Expected to find materialised model at [original model path] but couldn't find (or cannot access) database [original database name]

### App Version

v0.287.3

**Comment by TuringLovesDeathMetal** [comment]
Thanks for opening this bug @davidpeitinho 👀 good catch. 

For the person who picks this up, here's the docs on dbt's aliases: https://docs.getdbt.com/docs/build/custom-aliases

**Comment by TuringLovesDeathMetal** [comment]
@all-contributors add @davidpeitinho for bug
