### ISSUE TITLE
"group by" in SQL generated in table explore is counter-intuitive?

### ISSUE THREAD

**Issue by captnswing** [lightdash/lightdash#3506]
### Description

Thanks for making Lightdash!! (not sure this is a bug, probably more a newbie question)

Say I have this table

```sql
create table table_name
    (id int, name varchar(4), date timestamp, value int)

insert into table_name
    (id, name, date, value)
values
    (1, 'john', '2022-02-01 00:00:00', 27),
    (2, 'john', '2022-02-01 00:00:00', 27),
    (3, 'john', '2022-01-31 00:00:00', -12),
    (4, 'john', '2021-12-15 00:00:00', 32),
    (5, 'tom', '2021-10-22 00:00:00', 11),
    (6, 'tom', '2021-05-05 00:00:00', 201),
    (7, 'tom', '2021-05-05 00:00:00', 201),
    (8, 'bob', '2022-01-07 00:00:00', 43),
    (9, 'bob', '2021-08-26 00:00:00', 3),
    (10, 'bob', '2021-05-13 00:00:00', 12),
    (11, 'bob', '2021-03-08 00:00:00', 2)
```

When I explore it by selecting only the `name`, `date` and `value` columns, the query returns 9 rows, and not 11. Naively I would this explore action to correspond to 

```
select name, date, value from table_name
```

which of course returns 11 rows. But looking at the SQL that is generated, I see the sql to actually contain the `group by` clause

```
select name, date, value from table_name
group by name, date, value
```

Is this behavior configurable? Is it documented somewhere (so I can learn more about the reason/motivation)? 

I need to remember to select a primary key or id column in all my table charts, to get all the data listed as I expected, and not have duplicate rows being suppressed by the "group by"

and if I do, the table view now contains **two** ID columns, the Lightdash-generated, user-friendly `#` column, and my ugly `pk` column....

### App Version

Version: v0.287.3

**Comment by TuringLovesDeathMetal** [comment]
Hey @captnswing thanks for opening up this issue!

> Is this behavior configurable? Is it documented somewhere (so I can learn more about the reason/motivation)?

this is not configurable behaviour. There's also no docs on it specifically, but it's kind of explained in this dimensions and metrics introduction doc here: https://docs.lightdash.com/get-started/setup-lightdash/intro-metrics-dimensions

And also in this "How to use Explores" doc here: https://docs.lightdash.com/get-started/exploring-data/using-explores

The gist of it is:`dimensions` are fields that are used to _**group**_ the data. Then metrics give **_aggregations_** of those groups. 

Does that make sense? If not, then I can try to explain it a bit more!
