### ISSUE TITLE
Redesign recover-password form 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3508]
![Screenshot from 2022-10-17 16-15-03](https://user-images.githubusercontent.com/1983672/196201020-d2c33d69-2d5e-4e04-a087-ddc228b313da.png)
![Screenshot from 2022-10-17 16-15-48](https://user-images.githubusercontent.com/1983672/196201028-917ade22-e87a-4c03-8523-61d3b4b359be.png)

centered bullet list is bit weird. maybe we can remove bulletlist and update copy in one sentence. something like this:

If you have not received anything yet try checking your spam folder or [request password reset] again.

_Originally posted by @IrakliJani in https://github.com/lightdash/lightdash/pull/3501#pullrequestreview-1144209076_

**Comment by PriPatel** [comment]
Yup - good points, both!

- [ ] First heading (the grey text):  `We have emailed you instructions about how to reset your password`
- [ ] Para to replace bullet points : `Haven't received anything yet? Check your spam folder or [request password reset] again!`

- [ ] Bonus : Get rid of the green tick and monkey emoji. (as this now feels a bit random. We don't use emojis in the app as much)
