### ISSUE TITLE
I want to have multiple values for the `includes` string filter

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3509]
### Description

When I'm using the `includes` option for a string filter, I want to check if many different variables are included. 

For example, if I have an article where the tags are stuck together all in a single string, like this:
`fantastic-four,marvel,john-krasinski,mcu,doctor-strange-in-the-multiverse-of-madness,reed-richards`

Then I want to be able to have `includes` =`four`, `strange`, et.c - these should be joined by `OR`s in the SQL query

This should work like the many values when you have `is equal to` for a string.

**Comment by muhsinkamil** [comment]
@TuringLovesDeathMetal Same change intended for `not includes` too ?

**Comment by ZeRego** [comment]
> @TuringLovesDeathMetal Same change intended for `not includes` too ?

@muhsinkamil yes :)

**Comment by IrakliJani** [comment]
this also requires a frontend change.
- `includes`
- `not includes`
- `starts with`

should be converted from `AutoComplete` to `MultiAutoComplete` component
