### ISSUE TITLE
Cache data first before making table calcs.

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#351]
Are you sure you would want to cache the query result in your infra instead of storing it as a temp table in the users DWH, that you can then query as much as you like in that session?

__Originally posted by @djayatillake in https://github.com/lightdash/lightdash/issues/266#issuecomment-901100107__

**Comment by djayatillake** [comment]
New issue here which encompasses this one:

https://github.com/lightdash/lightdash/issues/353

**Comment by owlas** [comment]
thanks @djayatillake. Closing in favour of #353
