### ISSUE TITLE
Upgrade uuid and querystring on CLI

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3511]
### Description

Installing CLI throws warnings about `uuid` and `querystring`,  we should upgrade those

```
 >npm install -g @lightdash/cli
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

```
![image](https://user-images.githubusercontent.com/1983672/196364038-ba28ebc2-2fda-4d8b-bd4c-0786e66aaa06.png)

![image](https://user-images.githubusercontent.com/1983672/196363966-b5106710-b761-4b68-a1e5-0e2fa23dbb1a.png)

Snowflake-sdk , used on @lightdash/warehouses has a lot of outdated packages https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/package.json#L35

**Comment by TuringLovesDeathMetal** [comment]
Closign as not planned - I haven't heard about this bug since this issue was opened.
