### ISSUE TITLE
Disable "Download CSV" option

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3512]
### Description

![Screenshot 2022-10-18 at 09 15 06](https://user-images.githubusercontent.com/9117144/196375147-147b0591-b016-4545-b926-3b181285d73e.png)
![Screenshot 2022-10-18 at 09 15 17](https://user-images.githubusercontent.com/9117144/196375151-4901db2f-e5e8-4d7a-bf98-457c8b69071f.png)

Don't allow some users to download the results in CSV format.
Maybe have an option at the org level on what roles can see the option.

### What problem does this solve?

Mainly for security purposes.
Users might not want to share the actual data (only the visualization of them) with all the viewers of the dashboard.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego what about copying all of hte values from the table just by highlighting/dragging across the table? Would we also disable that?

**Comment by ZeRego** [comment]
Slack thread where this was requested https://lightdash-community.slack.com/archives/C039GAKTPMK/p1666080306398729

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. 

I don't think it makes sense to limit access to CSV download (we've now allowed viewers to download .csv's). They can see the results anyways, so they could just copy-paste those into excel if we didn't give them a download option
