### ISSUE TITLE
Add content metadata to queries

### ISSUE THREAD

**Issue by XiaozhouWang85** [lightdash/lightdash#3518]
### Description

Add content metadata as SQL comments to queries submitted to underlying database

### What problem does this solve?

Ideally data teams are data driven about data. Part of this is tracking things like unused content. A quick and easy way to enable this is to add metadata to queries as SQL comments. e.g.
```
/* 
--Lightdash metadata start--
{
   content_id: abc,
   content_type: dashboard,
   trigger: dashboard_open
}
--Lightdash metadata end--
*/
```
Most databases will track this in some kind of query log and it can be extracted using regex fairly easily and allows a data analyst to use dbt + lightdash to track things like unused content / user activity, most expensive dashboard etc etc.
Looker had a built in feature to do this but it wasn't great. Only admins could see it and it always ran very slowly because it's hitting whatever database Looker has for its internal functions. It was also not possible to merge Looker usage data with other data e.g. Bigquery costs.

In general, allowing users to use existing tools (i.e. dbt / lightdash) to do this is better than building a single use feature within Lightdash. An alternative might be to solve this with outbound webhooks that push events out of Lightdash. However, this is likely harder to implement both for lightdash and for lightdash users. While hacking some regex is likely within each of pretty much all lightdash users.

**Comment by XiaozhouWang85** [comment]
One thing I forgot to mention was consideration for query caching in the DB layer. Looker is super unhelpful in only adding in a query_id in the comments which by definition is always going to be different causing issues for caching.
Ideally the info contained will be relatively static i.e. which bit of content triggered the query.

**Comment by ZeRego** [comment]
Hey @XiaozhouWang85 👋 Can you confirm this would be covered by the following ticket? if so, we can close this one. https://github.com/lightdash/lightdash/issues/3379
