### ISSUE TITLE
update docs for detailed instruction how to install node before installing lightdash cli

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3525]
**Changes?**

need to mention how to install nodejs with different OS-s
take into account that users are installing packages globally - so they might experience permission errors if node is a systemwide installation (not an installation from a version manager)

resources:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by rifkiamil** [comment]
I will leave more feedback when I have time, considering developers are uploading security keys to GitHub. We must presume they don't know the best way to set up the development environment on the mac. The way I got introduced to node/npm was via https://reactjs.org/docs/create-a-new-react-app.html. Most users will download node via https://nodejs.org/en/download/

![Screenshot 2022-10-19 at 13 08 22](https://user-images.githubusercontent.com/1672403/196686901-3c9bc4da-88e3-4709-bf3c-40c7f7a7ac3e.png)

**Comment by IrakliJani** [comment]
also need to update this page → https://docs.lightdash.com/guides/cli/how-to-install-the-lightdash-cli
