### ISSUE TITLE
Usin negative round numbers throws an error

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3542]
### Description

I used this round on my YML like documentation suggests: 

![image](https://user-images.githubusercontent.com/1983672/197207901-83b7c1ab-1529-44b1-9c7f-016fb5c8e9a6.png)

https://docs.lightdash.com/guides/formatting-your-fields#rounding-your-metrics-and-dimensions

I got this error when Running query 

![image](https://user-images.githubusercontent.com/1983672/197208059-bb6bb9e5-2860-465d-8c70-0b20a5f41d3d.png)

`RangeError: minimumFractionDigits value is out of range.`

2022-10-21 13:31:52 [Lightdash] error: Handled error of type UnexpectedServerError on [POST] /api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/explores/events/runQuery RangeError: minimumFractionDigits value is out of range.

**Comment by TuringLovesDeathMetal** [comment]
maybe related to this? https://github.com/lightdash/lightdash/issues/3495
