### ISSUE TITLE
lightdash generate assigns wrong model name on models with aliases

### ISSUE THREAD

**Issue by davidpeitinho** [lightdash/lightdash#3543]
### Description

specific for the release 0.295.1

When I execute the `lightdash generate` command on models with alias it will:

1. create a yml file with the alias name, not the model file name
2. in the yml file, the model name is the alias, it breaks the lightdash table dimensions/metrics connections (suggestion, just add the alias on the meta/label field)

### To Reproduce

1. add a alias to the config block for a model
2. execute `lightdash dbt run`
3. verify that the generated yml file has the wrong filename, and the models/name field has the alias name and not the actual model name 
4. verify that the connection to the table in the lightdash ui is broken

### App Version

v0.295.1

**Comment by TuringLovesDeathMetal** [comment]
ooh good spot. Thanks for opening the issue @davidpeitinho 

Have you used joins with aliased models yet? I'm wondering if that works with Lightdash or if it also breaks things 🤔

**Comment by TuringLovesDeathMetal** [comment]
@all-contributors add @davidpeitinho for bug

**Comment by davidpeitinho** [comment]
> 

@TuringLovesDeathMetal tested two scenarios for joins:

1. if i don't replace the alias on the names within the yml files the queries won't work, but the compilation works fine. 
2. if i replace the alias the names in the yml files with their model names, the join will it will use the Alias of the current model and compares with the Model name of the joining table, which are completely unmatched and will result in a compilation error.
