### ISSUE TITLE
Usage reporting

### ISSUE THREAD

**Issue by thedataguy-official** [lightdash/lightdash#3549]
### Description

I woud like to understand how which users are logging in, when, and which dashboard/charts they are accessing.

### What problem does this solve?

Allow me to understand BI engagement by user and dashboard/charts.

**Comment by TuringLovesDeathMetal** [comment]
Just realized, all of the work for this is captured in this milestone: https://github.com/lightdash/lightdash/milestone/27

But we don't actually have an open issue for creating the dashboard once we've done all of the pre-required work 😅 

Adding this into that milestone!

**Comment by ZeRego** [comment]
This can be partially solve by https://github.com/lightdash/lightdash/issues/3379

**Comment by 12ian34** [comment]
This issue is being closed in favour of the overall milestone for Usage Analytics, which covers this request: https://github.com/lightdash/lightdash/milestone/68
