### ISSUE TITLE
Email user invite for Open Source version

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3550]
### Description

I understand that for the Open Source version of lightdash, there is no email server configured and therefore no user invite emails will be sent.

Options
1. A fix is needed (configuring an email server?), or
2. Remove references to an email invite being sent

### To Reproduce

1. Settings > Organization Settings > User Management
3. Add a user
4. No email invite is sent

### App Version
v0.295.1

**Comment by TuringLovesDeathMetal** [comment]
I'd vote for 1!

^leaving the email stuff in-app, but requiring that users setup an email server (if they haven't)

We'd need docs for this (could we link to somewhere that has docs on setting up an email server already?)

We'd also need the place where you send an email to be greyed out/unavailable with a help message saying `you need to setup an email server to do this`

**Comment by owlas** [comment]
Closing this as it is the intended behaviour that the OSS app can run without an email server. For example, when inviting a user you should be offered an invite URL to share with the user.

However if folks spot something in the UI that suggests that an email is being sent, but it isn't. Please reopen.
