### ISSUE TITLE
New date filter options

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#3551]
### Description

New date filter options needed in the UI.

Existing options
![image](https://user-images.githubusercontent.com/7281432/197264749-f52d5c86-0f9f-40c5-9df1-7b37241cb161.png)

Proposed additional options
1. `not in the last`
2. `between` (relative dates, e.g. between -12 months and -2 months)
3. `is before` / `is on or before` - can we also include relative dates (e.g. is before -5 days)
4. `is after` / `is on or after` - can we also include relative dates (e.g. is after -5 days)

### What problem does this solve?
`not in the last` - I am trying to report on certain financial metrics, but I would like to exclude recent statistics (e.g. data in the last 7 days).

Relative dates also make reporting far more flexible for multiple user cases.

**Comment by TuringLovesDeathMetal** [comment]
thanks for opening this one @gordonkjlee !

A few questions:

- between: #3599 (it sounds like you want relative dates though 🤔 can you not accomplish that with two relative filters?)
- for using negative relative dates. I understand this for `is before` but for `is after`, can you not just use `is in the last`. E.g. if today is October 27th, then I said "the date is after -5 days". This would return dates in the last 5 days (October 23rd, October 24th, October 25th, October 26th, October 27th). This is the same as what would be returned if you said "the date is in the last 4 days". Unless you also want to include future dates, I think they're the same thing, no?

**Comment by gordonkjlee** [comment]
In the example you provided, I'll want to report on records not in the past 5 days. So anything prior to October 22. I don't think there's anything that can facilitate this at the moment

**Comment by TuringLovesDeathMetal** [comment]
cool, so if we had `not in the last` as an option, then you wouldn't need the negative relative dates for `is after`?

**Comment by gordonkjlee** [comment]
That's right! However, I would suggest reviewing all date filter options since there are some relative date options at the moment.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. We haven't had more requests for this, and if we do, we can break out each filter logical option into a separate issue.
