### ISSUE TITLE
Plot bars with empty x-axis value

### ISSUE THREAD

**Issue by thedataguy-official** [lightdash/lightdash#3553]
### Description

I want to plot multiple metrics as bars, but Lightdash UI expects a selection on the x-axis.

In the demo, I don't see a way to plot 2 metrics (Average of Basket Total; Average of Item Profit) as two bars in the bar chart

![image](https://user-images.githubusercontent.com/7281432/197269083-c47dbf37-9793-4103-ba00-b742fab03a56.png)

The UI expects a selection on the x axis and the y axis.
![image](https://user-images.githubusercontent.com/7281432/197269274-94a76dfc-3cf2-49ad-8dc2-60310f63fcee.png)

### What problem does this solve?
Allow multiple metrics to be graphed as bars, without a selection on the x axis.

**Comment by TuringLovesDeathMetal** [comment]
totally! I've just updated the title of this a bit - but I understand the goal!

**Comment by TuringLovesDeathMetal** [comment]
Here's another example of this (imagine this is plotted vertically though...the `placeholder` is there because that's the only way to make it work)
![image](https://user-images.githubusercontent.com/31848148/214346822-d46cc3e8-3ecd-483d-88bb-e8efc2c6df1e.png)
