### ISSUE TITLE
Add show_underlying_values property to dimensions

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3555]
### Description

Now we use `show_underlying_values` property on metrics for more than just showing specific fields on the results table , it makes sense to also apply these to `dimensions`, not just metrics 

- [ ] Show on results table only the fields selected on `show_underlying_values` 
- [ ] Keep selected fields when doing `explore from here`
- [ ] Sort dimensions https://github.com/lightdash/lightdash/issues/3545

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. I get what you're saying, but also don't think dimensions really have "underlying values" (since they're not aggregates, unlike metrics).
