### ISSUE TITLE
Support time intervals where start of the week is Monday

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3557]
### Description

Option 1:
Add a project level setting or field level setting to set the start of the week day. 

Option 2:
Support ISO time intervals
> DOW numbers Sunday (0) through Saturday (6), while ISODOW, which adheres to the ISO 8601 standard, numbers Monday (1) through Sunday (7).

The implementation will vary from warehouse to warehouse.

Bigquery: start of the week at configuration at the SQL level
https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#extract

Snowflake: start of the week configuration at the session level 
https://docs.snowflake.com/en/sql-reference/parameters.html#label-week-start

Postgres/Redshift: ISO
https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT

Databricks: ISO
https://docs.databricks.com/spark/latest/spark-sql/language-manual/functions/extract.html

### What problem does this solve?

Slack community thread https://lightdash-community.slack.com/archives/C03MG2VTR08/p1666450693264599

> Thoughts on adding week start options to time intervals? e.g.time_intervals: ['DAY', 'WEEK(MONDAY)', 'MONTH', 'QUARTER']
or, just a global option.
standard reporting for us has week starts on Mondays, Ligthdash is grabbing Sundays (BQ), so creates some misalignment. Imagine that's pretty common.
As far as I can tell the current alternative is creating an additional week(monday) column for each time dimension but let me know if I'm missing anything! (

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego I'm not too sure I understand the difference between (1) and (2)? 🤔 Where would option (2) be defined/live?

**Comment by ZeRego** [comment]
> Small note but just to clarify--on BQ you linked extract, which will return the week num.

This feature would cover all the week-related time intervals.

> @ZeRego I'm not too sure I understand the difference between (1) and (2)? 🤔 Where would option (2) be defined/live?

In **Option 1** we keep the existing time intervals and have a "Start of the week" config at the project level.
In **Option 2** we add more time intervals that adheres to the ISO 8601 standard. Eg: DOW numbers Sunday (0) through Saturday (6), while ISODOW, which adheres to the ISO 8601 standard, numbers Monday (1) through Sunday (7).

**Comment by ZeRego** [comment]
Note that we should also update the week picker in the filters. So I'm now inclined for option 1.
