### ISSUE TITLE
I want to be able to copy cells from Excel or .csv and paste them into the filters box

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3587]
### Description

When I copy a set of cells from Excel or google sheets, I want to be able to past them into the filters box and have them entered as separate values. 

- this would only work for numeric and string filters
- this would only work for `is equal to`, `is not equal to` filter logic

For example, if I copied these cells:
<img width="170" alt="image" src="https://user-images.githubusercontent.com/31848148/197990041-bcb1f4f8-70b8-4e19-ac59-2e829e90c7a1.png">

And pasted them in Lightdash, they would appear like this:
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/31848148/198000525-b3f43679-3a99-4d41-a15c-a240a9b0d970.png">

**Comment by ZeRego** [comment]
This has been resolved

<img width="475" alt="Screenshot 2024-08-19 at 13 34 07" src="https://github.com/user-attachments/assets/1f14cbfe-3510-49b9-992a-717e9bc93ddb">
