### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by phillipwilhelm** [lightdash/lightdash#3589]
### Description

Add Maria DB support for available integrations

### What problem does this solve?

Adding another RDMS to utilize in LightDash

**Comment by TuringLovesDeathMetal** [comment]
Hey @phillipwilhelm! Thanks for opening an issue for this :) 

Just letting you know that we only support dbt verified adapters for now. You can check out the list here: https://docs.getdbt.com/docs/supported-data-platforms#verified-adapters

Once MariaDB gets onto that list, we'll add support for it in Lightdash! But we probably won't prioritize this until then.

**Comment by TuringLovesDeathMetal** [comment]
@all-contributors add @phillipwilhelm for ideas

**Comment by 12ian34** [comment]
We now support Trino which has a [MariaDB connector](https://trino.io/docs/current/connector/mariadb.html). Would this work for you @phillipwilhelm ?

**Comment by TuringLovesDeathMetal** [comment]
Not planned until MariaDB is a dbt-verified adapter
