### ISSUE TITLE
I want to be able to adjust the sorting on a table chart in a dashboard in view mode

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3591]
### Description

When I'm viewing a table chart in a dashboard, or in view mode, I want to be able to adjust the sorting. 

- [ ] The sorting functionality should work like it does now, but it should be available to users in `view` mode of a dashboard and a chart
- [ ] The sorting isn't saved once the user refreshes the page, or exits the dashboard (just like dashboard filters in view mode)

**Comment by hamzahc1** [comment]
Closing in favour of #6315
