### ISSUE TITLE
We should have `is between` as a filter option for dates

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3599]
### Description

We have the option to filter `is on or after` and then include `is on or before`, but right now, because we don't have nested filtering options, this means I'm forced to have any other filters I might choose have the `all filters apply` logic to them. 

Also, it's a bit annoying that I need to apply `is on or after` and `is on or before` as two separate filters (a user actually didn't know how to do this...they were looking for a `range` option - that's how unintuitive it was)

We should add an option for `is between` for date + timestamp filters. 

<img width="175" alt="image" src="https://user-images.githubusercontent.com/31848148/198223075-07392b06-afcc-49c9-9b00-db63aabb3bcc.png">

- [ ] selecting the options should be the exact same behaviour as when you're filtering using `is on or before`
<img width="623" alt="image" src="https://user-images.githubusercontent.com/31848148/198223331-bdc82839-b284-450e-a610-bf4dbd652fc2.png">

- [ ] except now, you'll have two boxes to fill in. They should be joined with `and` like this:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/31848148/198224037-6a942e39-f102-4116-b9ac-1468842a60d4.png">

- [ ]  the filter logic will be `is on or after` _xxx_ AND `is on or before` _yyyy_ (i.e. we include the ranges like this [date1, date2] not like this (date1, date2))

- [ ] we need to update the docs to include these changes (and add details about how it _**includes**_ the boundary dates)

**Comment by PriPatel** [comment]
<img width="865" alt="Screenshot 2022-11-28 at 11 24 01" src="https://user-images.githubusercontent.com/12776522/204265663-56173a49-96b3-4407-95fb-1bcdfb050a16.png">
