### ISSUE TITLE
Replace deprecated `set-output` command

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3639]
### Description

Github is deprecating a command we use in our CLI/github actions templates

Warning we get in our github actions:
```Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

**Comment by rephus** [comment]
Apparently this has been removed already, which could cause issues on some commands 

The underlying set-out is being removed from 1st June 2023. Instead of set-output the $GITHUB_OUTPUT should be used instead.

**Comment by rephus** [comment]
I can't find any reference to `set-output` on the CLI or https://github.com/lightdash/cli-actions . The only place where we used it was fixed in https://github.com/lightdash/lightdash/pull/7063
