### ISSUE TITLE
I want to specify if my space is restricted or shared when I create it

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3641]
### Description

When I create a space, I want to specify if it's restricted or shared on creation. 

### User Acceptance Criteria
- [ ] When I create a space, I can choose whether it's restricted or shared. 
- [ ] If I create a restricted space, then it's just available to me and the space is created. I can always add more people to the space after.
- [ ] If I choose to create a shared space, then it gets created, and it's available to everyone who has access to the project that the space is in.

**Comment by PriPatel** [comment]
<img width="662" alt="Screenshot 2022-11-10 at 16 19 21" src="https://user-images.githubusercontent.com/12776522/201149516-2a3eafb8-df0d-416e-b928-bbc910c536b5.png">

It would be great to get some feedback on terminology here.

I thought that Private = just for me and Shared = more than 1 other person. 
I guess I imagine the next step after 'hitting' Shared would be to see the permissions modal and then select what I want to do from there. 

If we don't want the above flow, what should the two options be? 
Private = Only you can access this space
Shared with all [Project Name] members = Everyone in [Project name] can access this space

**Comment by TuringLovesDeathMetal** [comment]
Yep, that makes sense to me!

**Comment by hamzahc1** [comment]
I think that makes sense! There are probably 3 states (Similar to Notion's sharing settings):
- Private (only me)
- Shared (Shared with select people added individually - if you add someone to a private space it'd automatically move from private to shared)
- Team space (Everyone in org has access)
