### ISSUE TITLE
New users should be able to join an existing Lightdash org without an invite if they have an allowed email domain

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#3646]
### Description

Users of the same domain should be able to join an existing organization without an invite. 

### What problem does this solve?
Often users create a new organization without realising someone else has already created one in their company. This can cause a lot of confusion when folks are getting set up. A much nicer UX would be for them to see that an org has already been created that they can join (if the admin has allowed this when setting it up), and then they can verify their email to join! 

e.g. below example from Deepnote when onboarding (after email verification is complete): 
 

<img width="515" alt="Screenshot 2022-11-01 at 15 55 38" src="https://user-images.githubusercontent.com/14341285/199278319-410b32c7-0c80-4c13-a8d9-a1953be85bd1.png">

### Acceptance criteria

miro sketch here for overview of the flow in onboarding: https://miro.com/app/board/uXjVPlK5W4Y=/?moveToWidget=3458764546747957536&cot=14)

- [ ] Once you've verified your email, if there are organizations that allow you to join based on your domain, then you're shown these organizations
- [ ] Even if you have organizations you can join based on your domain, you're still able to create a new organization
- [ ] You're able to see how many members are in each organization when you're picking an org to join. 
- [ ] If there are no organizations to join, then you are redirected automatically to create a new organization (i.e. you skip the "join an existing org" screen)
- [ ] If you join an existing workspace, you're not asked to add a name for your organization.

**Comment by owlas** [comment]
To do this we need to add email verification. This will be possible if:

- the user signed in with SSO
- the user is signed in with email/password AND the instance is configured with a mail client so we can send a verification email

I think we can break this down into two separate tickets:

- [ ] Add verified emails
- [ ] Add option to auto-invite people with a matching email domain (this ticket)

I'll add a spec for both

**Comment by owlas** [comment]
My proposal for the new flow would depend on whether the person is registering from scratch or from an existing invite. If they've been invited to an org and they click the link, they'll automatically join the org. But if they signup without an invite, then after verifying their email, we'll show them the option to "Create a new organization" or "Select from a list of existing Organisations" that are configured (by an admin) to allow anybody with their email domain to join. 

The overall flow looks like this

```mermaid
flowchart TD
  invite?{Clicked invite link?}
  newreg(Register user without invite)
  invreg(Register user with an invite link)
  verify(Email verification flow)
  verify2(Email verification flow)
  find-org(Find existing orgs accepting the verified email domain)
  create-org{Choose existing org or create new org?}
  join-existing(join existing org)
  create-new(create new)

style create-new fill: green
style join-existing fill: green
  
invite? -- yes --> invreg
invite? -- no --> newreg
invreg --> verify
newreg --> verify2
verify --> join-existing
verify2 --> find-org
find-org --> create-org
create-org -- no --> join-existing
create-org -- yes --> create-new
```

**Comment by PriPatel** [comment]
Is the design work here just to design one additional screen?

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel yes! I think two screens though:

- one for the verify email flow (click here to verify, or whatever)
- one for joining an existing workspace (the list of workspaces and being able to click on one)

**Comment by TuringLovesDeathMetal** [comment]
If you have one of the email domains included in the `allowed email domains` that you list here, then you go through this invite flow, is that correct @owlas ?

I think one of the big problems we're trying to solve here is when people just get started. And I think if you're just starting, you won't fill this out right away. 

Maybe we can by-default add the domain name of the first person who joined to this list? What do you think?

**Comment by owlas** [comment]
^ I think it should be opt-in. Otherwise if you join with @gmail.com or something less ridiculously generic, then all gmail users will be able to join your project. Which I really think wouldn't be expected

**Comment by hamzahc1** [comment]
We should definitely filter out major email providers to stop someone from doing that ^^ (i.e. any personal emails: @gmail, @outlook, @hotmail @yahoo etc. )

**Comment by PriPatel** [comment]
For reference:
https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=7925%3A117709&scaling=min-zoom&page-id=4234%3A82407&starting-point-node-id=4659%3A88199

**Comment by TuringLovesDeathMetal** [comment]
@owlas does a user need to verify their email address if they're being invited to an org from an invite link?

**Comment by ZeRego** [comment]
Note: Email verification is only available if the server has an email server configured.
We can check that in the FE with
```
const { health } = useApp();
health.data?.hasEmailClient // boolean
```
In this case, the user would skip the verification step and be created with an unverified email in a new organisation.
