### ISSUE TITLE
Verify user emails in signup

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3650]
### Description

We need to verify the users email address for 2 reasons:

- Improved security for password reset emails
- For feature #3646 of allowing auto-joining organisations

### The verification flow 

Unsure whether to use clickable links or short one-time passcodes (OTPs) for verifying, I prefer OTPs for the UX: you don't have to open another browser tab and you can check it the email on another device.

```mermaid
flowchart LR

sso?{Logged in\n with SSO?}
send(Send email to unverified\n email address with an OTP)
open(User opens email and sees OTP)
enter(User enters the OTP in the UI)
verified(Verified!)
style verified fill: green

sso? -- no --> send
sso? -- yes --> verified
send --> open
open --> enter
enter --> verified
```

### Starting the verification flow

There are three ways to trigger the verification flow. Trigger (1) will be what most users experience. Existing users or users changing their email address would use trigger (2) or (3).

1. During registration. After the user signs up with email/password we trigger the flow. If they sign up with SSO they are automatically verified
2. Logging in with SSO: whenever the user logs in with SSO we get an update of their email address used to sign in. At this point we can mark that email as verified for the user (if they have it set as their primary email)
3. In the user settings page. The user can always verify their email address in the settings page

### Implementation

- [x] Additional column in emails database table to mark as verified
- [ ] New logic preventing auto-joining orgs if email isn't verified
- [ ]  New screens for starting and completing the verification flow:: https://miro.com/app/board/uXjVPlK5W4Y=/?moveToWidget=3458764546746191089&cot=14
- [ ] New email templates for emails: Figma sketch here: https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=9635%3A129426&t=wTjI8S3TgRrpsEfS-0

**Comment by owlas** [comment]
not sure why the flow chart isn't rendering, here's a static image:

<img width="1121" alt="Screenshot 2022-11-07 at 16 12 57" src="https://user-images.githubusercontent.com/11660098/200359214-69ee0ef2-e432-4e88-a83d-8400adf0cfef.png">

**Comment by TuringLovesDeathMetal** [comment]
> who has to have their email verified?

- existing users stay as unverified. 
- new users who have an email server setup must verify their emails during onboarding

**Comment by TuringLovesDeathMetal** [comment]
> How many tries do you get before you can no longer use that verification code? 

- maybe 5 minutes? maybe a certain number of tries?
