### ISSUE TITLE
Improve filter autocomplete for multiple filters

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3651]
### Description

Currently when we provide autocomplete for filters we scan the whole table for distinct values. But if you've already setup a filter that segments to the last week or a certain geography, then the list of possible values may well be much shorter!

We should be smarter when we check for unique values by rescanning the table if the filters have changed, and finding unique values after applying the first filters.

For example, if I chose the country `canada` in my dashboard filter. Then, I went to add a new filter for `city`, it would only suggest cities in Canada (e.g. `Toronto`, `Vancouver`, etc.)

**Comment by ZeRego** [comment]
At the moment the endpoint for the autocomplete relies on the project uuid, explore name, and field id. 
Having access to the explore metadata it builds the SQL query the same way it builds a query for the explore page.

Relevant code in  `packages/backend/src/services/ProjectService/ProjectService.ts` -> `searchFieldUniqueValues()`

To implement this feature we need to know how to join the fields from the other filters.

**Option 1:** We only apply the filters that match the existing joins

BE receives all filters and only joins the ones where the filter field table matches one of the joined tables.
Keep using the existing logic to build a SQL query from a single explore.

**Option 2:** We scavenge joins from all explores 

BE receives all filters and checks in all explores if there are matching joins with the main explore.
Write a new function to build the SQL query with information from multiple explores.

**In my option, Option 1 is the most stable and maintainable approach and it solves 80% of the use cases.**

**Comment by owlas** [comment]
Even simpler than option 1 you could say it'll only take filters from the exact table!

Feels like doing this on charts would be even simpler right? because we don't have the complication of different tile targets

**Comment by ZeRego** [comment]
Yup, that sounds like a good first step :)
