### ISSUE TITLE
There should be a way to tell if a filter has already been applied to a field when you are in the 'tabs' field.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3659]
eg. if a date filter is already applied to `Organizations daily Date Week`, there should be some sort of visual indication. Both filters can still be applied.

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal 
Why is it necessary to know if a filter has already been applied at this point under the 'Tiles' tab?

Today,  I can do this in Lightdash -  I can create 2 separate date filters that apply to the same tile but there is nothing visual indicating this unless I hover over 'dashboard filters applied' and see the info in the tooltip. This doesn't seem to be a problem?

**Comment by TuringLovesDeathMetal** [comment]
Ya, I don't think this is a problem. 

I'm going to close this issue!
