### ISSUE TITLE
Add OneLogin SSO

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3668]
### Description

I want to be able to use OneLogin for SSO in Lightdash.

**Comment by ZeRego** [comment]
Is better for us to add support for SAML instead of specifically OneLogin.

Passport strategy lib:
http://www.passportjs.org/packages/passport-saml/
> Passport-SAML has been tested to work with Onelogin, Okta, Shibboleth, [SimpleSAMLphp](http://simplesamlphp.org/) based Identity Providers, and with [Active Directory Federation Services](http://en.wikipedia.org/wiki/Active_Directory_Federation_Services).
