### ISSUE TITLE
Make clear that margins in chart config panel can be in either (px or %)

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3670]
Suggestion - replace the word `Margins` with `(px or %)`, as it is already clear we are looking at margins because of the tab name 
![Screenshot 2022-11-03 at 15 39 36](https://user-images.githubusercontent.com/12776522/199765862-4fadf0ab-6423-4ea1-ac84-01725011f9fe.png)

**Comment by IrakliJani** [comment]
@PriPatel what do you think of this:

<img width="260" alt="CleanShot 2022-11-14 at 13 07 57@2x" src="https://user-images.githubusercontent.com/962095/201619911-6a546422-04e1-49c1-b300-77d9ef00f725.png">

input element with the right "tag" element which says % or px. you can toggle between them by clicking.

**Comment by PriPatel** [comment]
even better!
