### ISSUE TITLE
Styling update to the 'show column total' toggle on a table chart (in view mode) 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3674]
<img width="409" alt="Screenshot 2022-11-03 at 16 05 44" src="https://user-images.githubusercontent.com/12776522/199772485-1507d6c5-8bb3-4ff4-a43a-839540f097a9.png">

The font size could match the 'Export as' button (14px)  and it can also be a checkbox, rather than a toggle

**Comment by IrakliJani** [comment]
this was already fixed by me here https://github.com/lightdash/lightdash/pull/3649

<img width="393" alt="CleanShot 2022-11-14 at 12 54 33@2x" src="https://user-images.githubusercontent.com/962095/201617033-a7579c50-337e-4a3d-85e6-5d7f291abb28.png">
