### ISSUE TITLE
Error state for when you try and view a space you no longer have access to

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3678]
I have access to the Finance space and have saved the link to it in my bookmarks because I want to access it frequently.
Katie restricts my access to the Finance space because Lightdash have now implemented Space permissions.
I login to Lightdash and can't see the Finance space anymore. Whats happening ?! I go to my bookmarks and open the link.
I should see an error message telling me that I don't have access to the Space. 

I don't know if we could just copy what we have for when the same thing happens to projects. 

**TBC**
- The error message itself
- The CTA - What do we want the user to do at this point? Redirecting them back to the homepage makes most sense.

**Comment by rephus** [comment]
On dashboards, I'm redirecting to `/no-access` page that we already use  
![image](https://user-images.githubusercontent.com/1983672/202397329-f6400577-9037-46e5-bb4e-68de15650b19.png)

**Comment by PriPatel** [comment]
@rephus yep :)
