### ISSUE TITLE
Change the colour of icons in 'empty' states

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3691]
The colour of the icons we use in the non-ideal states is a bit dark and intense. (and kind of makes the panel look not-so-empty!) The text should be the main bit that stands out.

**Before**
<img width="808" alt="Screenshot 2022-11-04 at 15 46 32" src="https://user-images.githubusercontent.com/12776522/200017962-fa485498-d54b-4087-8988-80073c57ccc6.png">

**After**
<img width="846" alt="Screenshot 2022-11-04 at 15 45 30" src="https://user-images.githubusercontent.com/12776522/200017964-864c0953-d41f-42e0-b545-c4389ddb517e.png">

Q. Is it possible to update all the empty state icons in one so that they are all @gray 4?

**Comment by IrakliJani** [comment]
@PriPatel Second one seems to be Light Gray 1 no?

**Comment by PriPatel** [comment]
@IrakliJani  - Yes, you're right!
