### ISSUE TITLE
Auto refresh dashboard 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3693]
### Description

There should be a way to configure a dashboard to refresh each X minutes/hours/other.

Acceptance Criteria: 

- [ ] There should be a timer in the header of the dashboard showing when the dashboard was last refreshed (e.g. seconds ago, 1 3 minutes ago etc.) 
- [ ] Dashboards can be configured to refresh every X minutes or hours 
- [ ] When an auto-refresh is set, you can see this on-hover over the time (e.g. refreshes every 10 minutes) 
- [ ] Auto-refresh only applies while dashboard is opened (if you close the tab or navigate away, you'll need to configure it again) 

### What problem does this solve?

Make sure users are always seeing the latest data.
This might also require #621 to be solved since it doesn't matter if the dashboard refresh if dbt data didn't update the data.

**Comment by jw-aleksandr-zolotukhin** [comment]
Would be great. So we can put some Lightdash charts on wall-displays in the office :-)

**Comment by yasmin-e** [comment]
Would be nice to have a refresh button to trigger manual refresh too!
