### ISSUE TITLE
Clean up dashboard tiles by hiding unnecessary elements under a hover state

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3696]
<img width="377" alt="Screenshot 2022-12-07 at 13 09 54" src="https://user-images.githubusercontent.com/12776522/206187171-4e1cd0f2-de28-4792-9fa4-0e17dd08bc82.png">

- Right now, the title wraps two lines because the buttons are in the way. If the buttons only appeared on hover, overlaying the title, the tile will look more appealing and less busy. 
- This makes it very obvious what you can interact with.
- This ticket would unblock #3592.

Some quick changes that we could make: 

**In edit mode**
- [x] Add hover state to dashboard tile (suggestion : drop shadow) 
- [x] Add selected state to dashboard tile (suggestion : blue border)

**In view mode**
- [x] The context menu and info icon should only show on hover.

**Comment by TuringLovesDeathMetal** [comment]
Would also be helpful for something like #1678

**Comment by PriPatel** [comment]
@rephus and @yasmin-e 
I put this in the backlog as I think it's a useful and impactful change that Yasmine could work on. Let me know if you have any questions.
