### ISSUE TITLE
I want to be able to nest and/or filters in the same filter block

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3700]
### Description

Right now, I can use `any` and `all` to switch between joining all of my filters by `AND` or `OR`. But, I can't mix and match and/or within a filter block. 

Here are some examples of filters I can't do right now with our filter structure:

I can do this:
```
Users Count unique user IDs: is greater than 10 
AND 
Users Date created: is before January 1st, 2020
```

But I can't do this:
```
Users Count unique user IDs: is greater than 10 OR is less than 5. 
AND 
Users Date created: is before January 1st, 2020
```

And I can't do this:
```
Users Count unique user IDs: is greater than 0 AND Users Date created: is before January 1st, 2020
OR 
Users Count unique user IDs: is less than 5 AND Users Date created: is before January 1st, 2020
```

Being able to nest and/or filters in the same block is important for analyses where I'm creating "groups" of users using filters. E.g. "I want to compare weekly active users who are under 20 with weekly active users who are over 50". To do this, I need nested filters:

```
is_7d_active: is TRUE 
AND age: is < 20 OR age: is > 50
```

### Acceptance criteria
Here's a sketch: 
<img width="915" alt="Screenshot 2022-11-24 at 10 48 22" src="https://user-images.githubusercontent.com/12776522/203774311-b1611383-e274-4d23-8060-d52a8bcbdf21.png">

- [ ] I'm able to add `groups` and `new rules` to my filters. 
- [ ] All of the groups of conditions are joined with `AND`. 
- [ ] Conditions within groups can be joined with `AND` or `OR` (depending on if the group is using `ALL` or `ANY`)
- [ ] Adding a group adds a nested set of filters with `any` or `all` rules applied. For example, if I add a group here, I would get a nested group within the `all` filters 
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/31848148/220148941-e8a44e73-5ad6-4758-82ed-14fc17947bcb.png">
- [ ] adding a rule to a group means that rule is added to the `any` or `all` set of rules for that group. For example, if I add a rule to the outer `all` group, it would be added like this:
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/31848148/220149767-229c547f-ff8c-4d9b-a69b-b83c169929bd.png">
Adding a group the the inner `any` group would look like this:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/31848148/220150218-29620d5d-f22c-441c-bd52-dd0395ceca1f.png">

- [ ] I can add multiple layers of nesting in my filters. For example, I can add a group to my nested `any` group, like this:
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/31848148/220150952-a8563aa3-b30a-47ce-bdf0-2cbb315e7dd9.png">

**Comment by PriPatel** [comment]
Sketch!
<img width="915" alt="Screenshot 2022-11-24 at 10 48 22" src="https://user-images.githubusercontent.com/12776522/203774311-b1611383-e274-4d23-8060-d52a8bcbdf21.png">

**Comment by ZeRego** [comment]
There is a workaround to achieve nested filters, with the following steps:

1. Select fields
2. Set a filter
3. Run query
4. Select a cell
5. Click to open underlying data
6. Click to 'explore from here'

Now you have nested filters and can edit them as you want

**Comment by PriPatel** [comment]
**Design spec**:
-Wording could be clearer. Filters, conditions, rules , groups (in the mockup that I created), so we should consolidate these!
-We should move buttons around and just restrict the options we show. so if you cant add a dimension to the group, only show metrics in the dropdown
- We shouldn't make life for people who _**don't**_ want to use nesting harder, so don't want to mess with the current way filters work too much
