### ISSUE TITLE
Table charts in dashboards should be aligned with the tile's title

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3705]
The chart has 10px padding but it could be removed for the left and right side. 
In narrow tiles, this makes all the difference!

<img width="901" alt="Screenshot 2022-11-07 at 10 37 32" src="https://user-images.githubusercontent.com/12776522/200289492-e72bd2f9-dbbb-4b57-b5c4-89c70249d043.png">

**Comment by IrakliJani** [comment]
gonna start this after https://github.com/lightdash/lightdash/pull/3649
marking as 🚫 blcked
