### ISSUE TITLE
Custom/non-standard dbt adapters (e.g. AWS Athena)

### ISSUE THREAD

**Issue by aaronsteers** [lightdash/lightdash#371]
Our project uses the custom Athena dbt adapter so instead of `pip install dbt` we pip install via `git+https://github.com/Tomme/dbt-athena.git`. Is this supported?

**Comment by owlas** [comment]
Hey @aaronsteers - thanks for opening the issue

We should be able to get this setup, how are you running Lightdash? Are you using the docker image?

@ZeRego I'm wondering if we should have some documentation on how to extend the base docker container with a custom dbt adapter. It seems a few people are wanting to try it out. The alternative would be to add native support for custom dbt adapters (at least the most common adapters).

**Comment by owlas** [comment]
Hey @aaronsteers I've found a bug that might be causing this error. The issue is to do with how we select the right character for quoting. we're using ` by default but Athena requires `"`

**Comment by aaronsteers** [comment]
@owlas - Thanks for your work on this! I have not had a chance to test or dive into debugging yet but your explanation makes sense and I plan to do so in then coming week.

**Comment by owlas** [comment]
Hey @aaronsteers we now have explicit support for various warehouses but that doesn't include Athena! Making a separate issue.
