### ISSUE TITLE
bug: On hover row colouring doesn't work on frozen columns

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3710]
On hover row colouring doesn't work ... 

[Screencast from 07-11-22 16:11:21.webm](https://user-images.githubusercontent.com/1983672/200345129-fe99a87b-f229-40b4-8751-eceb404d387a.webm)

_Originally posted by @rephus in https://github.com/lightdash/lightdash/issues/3645#issuecomment-1305758990_

**Comment by TuringLovesDeathMetal** [comment]
I'm also going to close this issue...we're making quite significant changes to the table visualization component soon...and no one's reported this since it's been opened.
