### ISSUE TITLE
Custom Schema causing issues

### ISSUE THREAD

**Issue by neo-kyleprigotzke** [lightdash/lightdash#3716]
### Description
We are using [custom defined schemas](https://docs.getdbt.com/docs/build/custom-schemas) which depending on the target we have defined in our profiles will change where certain directories in our dbt project are written to. 
If we supply a full, single schema in the project config, it compiles and saves correctly. However when you then try and run a query it doesn't work because it is appending the custom schema to the defined full schema making it look for a schema that doesn't exists. 
Example: 
Project define the full proper schema as: `abc_project_one`
Then go to Explore > Tables and select a table and try and run a query and it'll return an error as it's trying to find a schema of `abc_project_one_one` which doesn't exist. 
Then if you just try to set the schema in the project to `abc_project` it passes the compile stag to save and gives an error of "Didn't expect to get here" 

### To Reproduce

1. setup a custom schema in your dbt project. 
  a. In our profiles we have the schema defined as `abc_project`
  b. in the dbt project say everything in a subdirectory called one we'll add the schema of `one` to it.
  c. when you run dbt run using this defined profile, the models of the `one` folder should be materialized to a schema of `abc_project_one`
2. Connect/adjust a project to connect to your models in abc_project_one, save the project configuration - it should be successful
3. Go to Explore > Tables - select a table and try and run a query (can even check the SQL to see the full name in the from clause) - you'll get an error as it's trying to find the table/field in `abc_project_one_one` which it can't find. 
4. Change project config to only set the schema to `abc_project`, click save - this will fail after trying to compile

### App Version
v0.299.0

**Comment by neo-kyleprigotzke** [comment]
Possibly work around, would be to set in the project yml to not use a custom schema if target == prod
``` 
 +schema: |
          {%- if target.name == 'prod' -%}
          {%- else -%} one
          {%- endif -%}
```
I tried to set target to something other than it's default of prod in the project config but also end up with the same error.

**Comment by ZeRego** [comment]
Lightdash uses **prod** as the profile name by default but it can be changed in the project settings.

![Screenshot 2022-11-08 at 09 12 51](https://user-images.githubusercontent.com/9117144/200524471-d8fdbad4-3fd2-4231-b2e0-95dbf67b707d.png)

Let us know if that fixes your issue.

**Comment by neo-kyleprigotzke** [comment]
When I change the target to something else it breaks, having the same error
message unfortunately

Kyle PrigotzkeLead, Data Analytics Engineer(587) 585 8195neofinancial.com
<https://www.neofinancial.com/>

–––––

**Comment by neo-kyleprigotzke** [comment]
This issue was resolved with - https://github.com/lightdash/lightdash/issues/3731
