### ISSUE TITLE
Optimise Github actions depending on what files changed

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3719]
### Description

We can skip GitHub actions depending on what files changed in the PR. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files
We should find out if render&netlify can be skipped based on that as well.
If so, if docs files change: create netlify env, lint & build. 
If anything besides docs change: create render env, lint & build & test, run e2e tests.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. Has been open for almost two years with no new activity or requests.
