### ISSUE TITLE
Can't pivot on a newly selected field until I run the query

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3727]
### Description

Can't pivot on a newly selected field until I run the query

### To Reproduce

1. Go to explore
2. select fields
3. run query
4. select new field (without running the query)
5. select table in viz dropdown
6. click configure
7. "group" dropdown does not show a newly selected field 💥

### expected behavior
- select field
- group dropdown shows selected field
- clicking field runs query and shows a pivoted result in the viz

https://user-images.githubusercontent.com/962095/200591870-0fa00cb1-8ab3-454d-b114-ec558a38b790.mp4

### App Version
v0.315.0

**Comment by ZeRego** [comment]
The existing behaviour was the one we intended as the chart was built from the last queried data and the config was based on the last query settings. 
What if we changed the ticket from bug to feature request?

**Comment by IrakliJani** [comment]
@ZeRego updated

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned - no users have complained about it since the ticket was opened almost 2 years ago.
