### ISSUE TITLE
Question: offline DBT models

### ISSUE THREAD

**Issue by TriStarGod** [lightdash/lightdash#3730]
Hi,
This looks like a great project. Due to the sensitivity of our data, we want to use this project offline. However, most topics refer to cloud DBT models. Is there a way to create DBT models offline to use with this project?
Thanks

**Comment by owlas** [comment]
Hey @TriStarGod absolutely! 

You can run Lightdash locally with no public access. You can also use dbt locally, there's no requirement to use dbt cloud to use Lightdash.

These docs should walk you through the steps, if you need help you can also ask for support in our community.

Docs: https://docs.lightdash.com/get-started/setup-lightdash/intro
Community: https://join.slack.com/t/lightdash-community/shared_invite/zt-1hwnltic3-oPLdVgVHwdgDYtkIJig1ig
