### ISSUE TITLE
The password settings tab shows the wrong options

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3745]
<img width="848" alt="Screenshot 2022-11-09 at 16 21 08" src="https://user-images.githubusercontent.com/12776522/200884122-5104e932-4ce6-480a-ae90-b428fa10155a.png">

In terms of styling it should still look like the form we show when the user has a password, but update the title to say `create password`
<img width="344" alt="Screenshot 2022-11-09 at 16 24 27" src="https://user-images.githubusercontent.com/12776522/200884351-da8479ec-a58a-409b-b177-16f6400bdc06.png">

**Comment by ZeRego** [comment]
@PriPatel
If a user has a password we show the form with the current/new password.
If the user doesn't have a password we show the form to reset a password. ( perhaps we shouldn't have the "forgot you password" title in this page )

**Comment by PriPatel** [comment]
@ZeRego 
Ah ok - and they wouldn't have a password because they signed up with something like gmail right?
Ok I think in terms of styling it should still look like the form we should when the user has a password, but update the titles of everything?

**Comment by ZeRego** [comment]
> and they wouldn't have a password because they signed up with something like gmail right?

correct.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego if someone adds a password to their account, does OAuth still work? Or can they now only sign in with a username + password?

**Comment by ZeRego** [comment]
> @ZeRego if someone adds a password to their account, does OAuth still work? Or can they now only sign in with a username + password?

Yes, the oauth still works
