### ISSUE TITLE
UI bug at the bottom of any 'Project' settings page 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3746]
I think that the` Test & Compile` button was pinned to the bottom of this page before. Now when I scroll to the bottom of the page, there seems to be a UI bug.

<img width="1439" alt="Screenshot 2022-11-09 at 16 29 38" src="https://user-images.githubusercontent.com/12776522/200885727-823aba85-f69d-4881-9996-80297b067ce2.png">

**Comment by IrakliJani** [comment]
@PriPatel can't reproduce this anymore. 

https://user-images.githubusercontent.com/962095/205244961-9bf45285-792a-4e4c-9c00-ade5b4a30bcd.mp4

should I pin the test & compile button again?

**Comment by PriPatel** [comment]
Hey - oh weird. I can't reproduce either! That's good.
Yes, I think it's helpful seeing the button pinned because the form is soo long and you might only want to change one field at the top.
