### ISSUE TITLE
Hide buttons from the UI that viewers don't have permissions to use 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#3747]
### Description

Users with viewer permissions shouldn't be able to see such as:

- Edit dashboard
- Edit saved chart
- Save charts

**Comment by IrakliJani** [comment]
@hamzahc1 can't find the ways to perform those actions. can you share more details?

https://user-images.githubusercontent.com/962095/201018268-b9e9c17d-a051-4d35-b1e4-3b4fd4e59f7e.mp4

**Comment by hamzahc1** [comment]
Closing for now as we couldn't replicate the issue
