### ISSUE TITLE
improve a way to copy the value from the table cell

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3750]
### Description

we need to improve a way to copy the value from the table cell. current UX is pretty bad.

### To Reproduce
https://user-images.githubusercontent.com/962095/201107296-08322a88-20d5-47c9-9b28-8c061cdb3ff4.mp4

### Possible solutions

- allow double clicking the string (native select)
- allow mod+c on selected cell
- add a menu item in the cell context menu

### App Version
v0.318.0

**Comment by IrakliJani** [comment]
I am in favour of both "allowing mod+c on selected cell" and "adding a menu item in the cell context menu"

@PriPatel @TuringLovesDeathMetal thoughts?

**Comment by PriPatel** [comment]
@IrakliJani is allowing double clicking an option?

**Comment by IrakliJani** [comment]
@PriPatel I'll try, will be a little bit tricky with blueprint

**Comment by PriPatel** [comment]
I can select the cell contents after 4 quick clicks 😂
