### ISSUE TITLE
Some filtering conditions break with non-date dimensions

### ISSUE THREAD

**Issue by rsanjabi** [lightdash/lightdash#3760]
### Description

Within a table explore, clicking on some of the options for drop down conditions on non-date dimensions causes the screen to go blank. 

### To Reproduce

1. From explore, select a table.
2. Add a filter (either three dots on a dimension or within filter section and select a dimension from drop down) being sure to select a non-date type.
3. Click on the conditional options
<img width="793" alt="image" src="https://user-images.githubusercontent.com/47192430/201267137-3cc42bb0-846b-4a81-afb5-03a83a744612.png">

5. Selecting `is null`, `is not null` behaves as expected for tables I tested this on. Selecting `is not equal to`, `starts with`, `includes`, `does not include` results in a blank screen. If `is null` or `is not null` was previously selected, clicking on `is equal to` will also resulting in a blank screen. 

### App Version

v0.318.0

**Comment by TuringLovesDeathMetal** [comment]
woah, that's a weird one. Thanks so much for opening an issue for this @rsanjabi ! We'll get this fixed ASAP 

Here's a recording of the bug for whoever picks up the ticket 👀 

https://www.loom.com/share/eb0c2780bf5946c7847ac5b031e84749

**Comment by TuringLovesDeathMetal** [comment]
@all-contributors add @rsanjabi for bug

**Comment by ZeRego** [comment]
Was fixed yesterday by #3758
