### ISSUE TITLE
Mysql and MSSQL connectors options, or maybe custom connector option?

### ISSUE THREAD

**Issue by rostykob** [lightdash/lightdash#3769]
### Description

As a lightdash user I would like to be able connect to different warehouses  I have in company and create a dashboards for it.

### What problem does this solve?

It will extend the existing supported technologies and will help you resolve customer needs where, there are different types of warehouses existing in the company

---
Your tool looking really great so I just wanted to know how your plans looking like with extending the list of supported technologies

**Comment by hamzahc1** [comment]
@rostykob - just FYI, we added support for trino this week: https://github.com/lightdash/lightdash/pull/4101!

**Comment by TuringLovesDeathMetal** [comment]
not planned - we've added support for Trino and until it is a verified dbt adapter, we won't support it. Will re-open if needed!
