### ISSUE TITLE
Docs: Adding Restack as a way to deploy Lightdash on K8s

### ISSUE THREAD

**Issue by kuberaspeaking** [lightdash/lightdash#3779]
**Link to existing docs:** 
[Self-host Lightdash](https://github.com/lightdash/lightdash/blob/main/docs/docs/get-started/setup-lightdash/install-lightdash.mdx)

**Changes?**
I wish to add Restack as a way to deploy Lightdash on kubernetes on the user's AWS infrastructure.
I propose to add it on the same level as the option with Heroku under Setting up a new project/ Self hosting Lightdash
Please let me know if you have any suggestions.

**Comment by TuringLovesDeathMetal** [comment]
Sounds great @kuberaspeaking !

Let me know if you need any help with this :)

**Comment by kuberaspeaking** [comment]
Hi @TuringLovesDeathMetal, how do I navigate to the docs in the locally hosted version? The links lead to docs.lightdash.com. I am trying to render the docs locally.
