### ISSUE TITLE
Add a cheat sheet for writing derived columns

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#378]
Since we're using raw sql for derived columns, there are some things (like running totals) that aren't obvious if you don't know SQL. 

Simple solution would be to embed some nice examples in the UI.

_Originally posted by @owlas in https://github.com/lightdash/lightdash/issues/266#issuecomment-905599307_

**Comment by owlas** [comment]
@TuringLovesDeathMetal I've labelled this as nice-to-have feel free to remove from the milestone/project if we don't want it in the current workload

**Comment by TuringLovesDeathMetal** [comment]
closed: broken into two subtasks #504 and #505

**Comment by TuringLovesDeathMetal** [comment]
closed: broken into two subtasks #504 and #505
