### ISSUE TITLE
I want to use the keyboard shortcut to copy table cell value

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3781]
### Description

I want to be able to copy the value from the cell with `mod+c` once I select table cell.

<img width="318" alt="CleanShot 2022-11-14 at 15 37 31@2x" src="https://user-images.githubusercontent.com/962095/201650577-2111dabf-7425-4731-99de-4af63ac6c426.png">

### What problem does this solve?

improves UX

**Comment by TuringLovesDeathMetal** [comment]
Maybe we could add some text as well to tell users how to do this? 

Like `cmd + c to copy` in text? (I'm also worried it might look a bit gross/cluttered...so maybe not...)

**Comment by TuringLovesDeathMetal** [comment]
Or even a `copy value` option in the drop-down?

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal where do you suggest add that tip/text to "use cmd+c to copy"
we discussed somewhere to add a menu item but I think it's going to add an unwanted clutter. so best option might be to have a native copy (browser context menu on selected text (which the linked PR solved) and keyboard shortcut to do cmd+c on the selected cell
