### ISSUE TITLE
Auto-provision users with SSO

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3782]
### Description

I'd like to auto add users from my organisation (Okta, google, or other provider) without manually configuring Lightdash. This could be done using either SCIM Provisioning or JIT (just in time) provisioning.

Ideally you would be able to map users to groups and roles depending on their role within the SSO provider.

**Comment by swiftsam** [comment]
This issue just came up again as desired by our team. We have an long-running slack channel manned by the analytics team creating accounts for people that they can then Okta-enable for future log-ins, but it slows adoption as other platforms can be granted to all employees.

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as completed - we've now added the option to manage user roles and attributes using user groups and syncing them with groups in Okta. 

you can read more about it in the docs here: https://docs.lightdash.com/references/groups#using-okta-to-manage-groups-in-lightdash
