### ISSUE TITLE
Create tooling/documentation to deploy to AWS ECS

### ISSUE THREAD

**Issue by ckdake** [lightdash/lightdash#3784]
### Description

Instead of using docker-compose or helm/k8ts, I'd like to be able to run lightdash on ECS (potentially with RDS instead of a postgres container too!).  

### What problem does this solve?

This allows people using AWS with ECS to more easily run lightdash, without having to 'go full k8s' but still use some cloud niceties without having to run docker compose on a VM somewhere.

---> If you'd be open to this being included in the code/docs, I'd be open to doing the work! Please comment and let me know if you'd consider merging in something like this.

**Comment by ZeRego** [comment]
Hi @ckdake 👋 we welcome pull requests 🥳 what kind of tooling were you thinking of? would that require a separate repo as we have for helm charts? And if we didn't have tooling how complicated would the documentation be? 
Trying to understand if we should just start with documentation or if tooling is a must. 
cc @owlas

**Comment by ckdake** [comment]
To deploy on ECS, you need a built docker container of the app pushed to a repo somewhere, and could either use a docker container of the database server or another aws service (e.g. RDS). 

More generally, this can be done "by hand" on AWS by click/create the cluster/task(s)/service(s),  by using terraform, by using cloudformation, or by using something else. 

This wouldn't require a separate repo, unless you really wanted to host/maintain terraform modules or a cloudformation template. Either of these would be enough for someone to "one click" get lightdash running in isolation, but neither would be great for "in production" since everyone's "production" setup using these higher level AWS building blocks is different.

I did some tinkering yesterday and some more poking around here, the best bet is probably documentation with some sample/gist code inline, adjacent to https://docs.lightdash.com/guides/how-to-deploy-to-kubernetes. (a how-to-deploy-to-ecs.md in https://github.com/lightdash/lightdash/tree/main/docs/docs/guides ?)

Hows that sound?

**Comment by owlas** [comment]
Hey @ckdake - I think providing docs for running with ECS + RDS would be awesome, we would definitely welcome those in the documentation if you're willing to open a PR for that.

Let me know if you have any trouble getting started, you'll just need to update the `/docs/docs` directory. You can run `yarn start` to render the documentation site locally while you're writing them.

The images are available on docker hub in the `lightdash/lightdash` repository. Is that accessible from within your AWS infra? It should be publicly accessible.

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned since it hasn't been requested by any other users since being opened and hasn't had any activity for almost two years!

Will reopen if it's requested again :)
