### ISSUE TITLE
Adding many columns increases results table without scrolling

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3811]
### Description

when I add more than ~10 columns, instead of adding horizontal scrolling to the SQL results table, the page gets bigger, but without horizontal scrolling

tested on Firefox Linux

![image](https://user-images.githubusercontent.com/1983672/203535848-eb10d2dc-fc7a-4986-b5aa-fc99cf1102bc.png)

### How to fix

Results table should have a fixed width, with scrolling if we add more columns. 

### App Version

v0.324.0

**Comment by TuringLovesDeathMetal** [comment]
@rephus is this in the Explore view? or in the SQL runner?

**Comment by rephus** [comment]
In explore view (I haven't tested in slq runner)
