### ISSUE TITLE
Improve SITE_URL error message on Heroku

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3816]
### Description

Related ticket:  #3442

If we don't not have the right SITE_URL set, we get this error: 

```
[31merror[39m: [31mHandled error of type UnexpectedServerError on [POST] /api/v1/invite-links TypeError [ERR_INVALID_URL]: Invalid URL
```

This error message is not obvious, we should catch the error and show a more meaningful message like:  

```
We can't generate URL for your SITE_URL ${SITE_URL} , update it with  valid http(s):// URL
```

**Comment by ZeRego** [comment]
We no longer support quick install on heroku
