### ISSUE TITLE
Remove space "owner" from permissions modal in full access

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3818]
![Screenshot 2022-11-21 at 17 20 43](https://user-images.githubusercontent.com/12776522/203119588-79336c44-2fed-4844-998b-12ce3fa70206.png)

The user at the bottom of the modal should not be there in full access. User lists should only appear in `restricted access`

**Comment by rephus** [comment]
Yeah, we had a quick chat about this on slack (https://lightdash.slack.com/archives/C02GQKJK84Q/p1667989664203979) , we currently don't have a "created by" attribute on spaces, specially on old spaces that were created before this feature. The user that is showing there is the , and there always should be at least one (unless it is an old space) 

If we really want to have an `owner` we need to add a created-by column on space (that will only be applied to future spaces), and maybe modify the existing logic to always allow owners (or not, if we want to allow "transfer ownership" )

**Comment by PriPatel** [comment]
Got it - thanks. Totally missed the rest of that chat on slack - my bad!

Ok, so the thing that is confusing me is if I go in and change the permissions to be restricted access on a space, does that mean that Im the only one who has access to it now? (despite the fact that I didn't create the space in the first place?)

**Comment by rephus** [comment]
My suggestion is to add `created_by` column (requires backend migration) and use it only to identify the owner of the space. But keep using `the list of access` for the access logic. what do you think @owlas  ?

**Comment by PriPatel** [comment]
I find it really confusing when I see my name and "admin"  in the space when everyone in the project has access (and in this case, everyone is an admin) . It makes me feel like Im special or that I own the space. Maybe we should just get rid of it? The og design's intention was to show the Space creator but maybe we should forget about this and keep it simple.

**Comment by rephus** [comment]
so, we only show the list (including you) if the space is set to private , right ?

**Comment by PriPatel** [comment]
I'll leave the decision up to @owlas and @TuringLovesDeathMetal !

**Comment by TuringLovesDeathMetal** [comment]
Was just about to open an issue for this. 

I say we remove it for now! So the list of users only appears if its a restricted access space. 

@rephus I feel like we're going to use `created by` information for spaces for features in the future. Can we add that column to the data now? (even if we're not using it anywhere). 

I can open a separate issue for it!

**Comment by TuringLovesDeathMetal** [comment]
@rephus @PriPatel if you both agree, then I'll update the issue description!

**Comment by PriPatel** [comment]
Yep, I think we should remove it
