### ISSUE TITLE
Show error on dashboard

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#3820]
We introduced a `division by zero` error in a `table calculation`.

However, we didn’t get any error, when that error was in a `chart` on a `dashboard`.

What happened was: when we changed a `filter` on a `dashboard`, that would trigger the error, the results in the `charts` on the `dashboard` just defaulted to the last non error results.

**As a feature request, I think it is better if we just get an error on the `dashboard`. IMO it is always better to get no data than wrong data.**

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey Martin

I haven't heard of this issue again since it was opened 👀 I'm going to assume it's been resolved with some things like the validator and some improvements in error handling. 

if this happens again, we can reopen it!
