### ISSUE TITLE
Add filter for current time interval

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3832]
### Description

Right now, to filter on `today`, you need to add a filter for `is in the last 0 days`. This isn't really intuitive, but it's manageable. 

But, if you try to use this same logic with a month/week filter, it actually doesn't even work. e.g. the date today is the 23rd of November, 2022. If I try to add `date is in the last 0 months`, it gives me this SQL logic:

```
...
WHERE ((
  ((DATE_TRUNC(`pages`.date, DAY)) >= ('2022-11-23') AND (DATE_TRUNC(`pages`.date, DAY)) <= ('2022-11-23'))
))
```

So, I think that we should add an option to filter on the current timeframe. 

### Acceptance Criteria:
- I can filter a date to be in the current day, week, month, quarter, year. 
- E.g. If the date today is November 23rd, 2022, there's a way for me to filter my results table to November 1st - November 30th 2022. Then, on December 3rd, 2022, that same filter would filter my results table to December 1st - December 31st, 2022. 

### Some ideas for solutions

I imagine this would be an option in this list:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/31848148/203554758-56938e5a-6e6d-4040-b3a8-193c838dd1f7.png">

And we could add:
`is today`
`is in current month`
`is in current quarter`
`is in current year`

^This feels like we might get too many options in that dropdown. 

Maybe another way of breaking it out is adding an option for `is in this` or `is in current` then you'd be able to pick `day, week, month, quarter, year` from another drop down , like this:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/31848148/203555475-a860a404-5057-45a4-9054-5746572a5cfd.png">

^Another another option is to have the `is in the current`/`is in this`, and then also `today` (I feel like the "is in current day" is the only one that sounds a bit weird...)

**Comment by warora** [comment]
This will be very useful - thank you

**Comment by deepskydata** [comment]
Excellent. That would help. Google Analytics and some other analytics platforms are doing quite a good job concerning date selection for analytical purposes. Maybe this can help to get a better overall idea.
