### ISSUE TITLE
Input field suggestions should not overlap action buttons 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3841]
### Description

This affects all modals with inputs

If I type something, it will autocomplete with some results. 

![Screenshot from 2022-11-24 10-03-33](https://user-images.githubusercontent.com/1983672/203741547-bb8e373d-4a13-4881-9e6f-b43d0ce5c1cc.png)

![Screenshot from 2022-11-24 10-03-44](https://user-images.githubusercontent.com/1983672/203741565-e474070b-ebca-4354-9644-cc65b1eeb3d8.png)

The problem is that if I want to save I need to click `save` button, which is behind the result list. To hide the result list I need to click somewhere in the modal . Clicking outside of the modal closes the modal 

Pressing ESC closes the modal  entirely, not just the popup (this could be another issue) 

My suggestion might be to have a fixed width for the results that will not overlap the buttons.

**Comment by rephus** [comment]
@PriPatel what do you think ?

**Comment by IrakliJani** [comment]
@rephus is that a native text input history?

**Comment by ZeRego** [comment]
> @rephus is that a native text input history?

@IrakliJani yes

@rephus what browser you using ?

How it looks in chrome:

![Screenshot 2022-12-08 at 10 42 20](https://user-images.githubusercontent.com/9117144/206426526-de3d2ccf-ff06-4419-996c-9e71eff946a2.png)
![Screenshot 2022-12-08 at 10 43 32](https://user-images.githubusercontent.com/9117144/206426757-9a8802e5-3c66-4cfc-8726-1682b010998a.png)

Should we fix this by preventing browsers from showing the text input history in those inputs?

**Comment by IrakliJani** [comment]
@ZeRego yeah, maybe we start with inputs inside Select2 components?

**Comment by rephus** [comment]
I'm using firefox on linux. 
![image](https://user-images.githubusercontent.com/1983672/206491337-0719f257-920c-44be-b72b-179de5532010.png)
Now that the space creation modal is bigger, is not a problem anymore here... .maybe we just need to limit the results we show instead of disabling it completely.... We should check other modals .

**Comment by IrakliJani** [comment]
Do we need the history on inputs at all? @TuringLovesDeathMetal @PriPatel 
Turns out I always disable that from settings when I install chrome 😄

**Comment by TuringLovesDeathMetal** [comment]
^For naming stuff, I don't think so...I don't think I'd want to name my chart or dashboard or space the same thing twice? 🤔 so it feels a bit weird.

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani if the solution is just "remove the thing that's breaking it", then you are the winner of today 😂

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal to be honest, I thought that browser feature was already dead. turns out I just disable "autofill" settings when I install the browser 😂 
I might be opinionated here but can we completely disable it? or we only need to address issues for specific inputs? maybe modals only?

**Comment by PriPatel** [comment]
@IrakliJani I can't think of any cases where this feature is usefu (?!) l so I'd be up for disabling it.

**Comment by PriPatel** [comment]
![Screenshot 2022-12-09 at 15 47 51](https://user-images.githubusercontent.com/12776522/206739469-00c493c7-a836-4497-b649-2a32003fffbf.png)
Oops - this is an issue when adding charts to a dashboard, correct? Or is that a different issue?

**Comment by rephus** [comment]
ahh , good point, that list is not from browser history, but a list of charts we display, and yes, it has the same issue. So even if we disable browser history, it will not fix some other modals

**Comment by PriPatel** [comment]
@rephus 
Could the first step could be to click anywhere to close the dropdown?

**Comment by rephus** [comment]
Yeah, that works, we'll have to make sure clicking outside the modal doesn't close the modal, but only while selection is open...

**Comment by IrakliJani** [comment]
agreed to keep all modals open even if you click outside. that should be a simple fix
