### ISSUE TITLE
better yml syntax parsing error

### ISSUE THREAD

**Issue by halacsy** [lightdash/lightdash#3846]
### Description

I made the same mistake the second time. I wanted to add a single filter to a metric but I forgot `-`. I got an error from lightdash: ` - ERROR> tuition_fees : rawFilters.reduce` is not a function. 

I understand the error (i gave a non list where list was expected) but took me 3 minutes to figure out. A better error message might be helpful for others. 

### What problem does this solve?

Until I learning and practicing yml syntax of metrics and dimensions I could be lead by lightdash to find my mistakes.
<img width="688" alt="Screenshot 2022-11-25 at 8 39 38" src="https://user-images.githubusercontent.com/1827287/203927964-6250634e-77da-4c97-bb3f-7cf0d508cec4.png">

**Comment by owlas** [comment]
Great spot @halacsy we need to have better yaml validation before we even try to compile the project. We already have a schema for checking this stuff. We'll make improvements!

**Comment by owlas** [comment]
Just noticed we have validation logic already here running on the server: https://github.com/lightdash/lightdash/blob/ffd99f92810111a4fbdab9c2752a868af49b4f77/packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts#L32-L51

we just don't use it on the CLI
