### ISSUE TITLE
Build new sidebars

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3861]
**Replace top navbar with expanded sidebar on:**
Homepage, all spaces, individual space page, all dashboards , all charts and settings page.

**Replace top navbar with minimised sidebar on:**
Explore / SQL runner / Dashboard page

Remove spaces from the homepage.

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel is this issue part of the migration to the new component library? (from what I remember, we're not going to touch the sidebar until we've done the component library migration?)

**Comment by PriPatel** [comment]
Yep! I still need to remove the unnecessary tickets from this milestone - I'm going to close this completely actually(!) because we will need two new milestones eventually, one for the navigation, and one for the component library and we'll probably break this task down differently (this made sense when the milestone was 'Content management pages')
