### ISSUE TITLE
Update access token documentation with instructions for fine-grained tokens

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#3866]
**Link to existing docs:** 

Existing link: https://docs.lightdash.com/get-started/setup-lightdash/connect-project/#personal-access-token-1

We should add instructions for how to do this with fine grained tokens

**Changes?**

**Comment by TuringLovesDeathMetal** [comment]
@hamzahc1 what do you mean by "do this with fine grained tokens"??

**Comment by hamzahc1** [comment]
Blocked by #3869
