### ISSUE TITLE
Rename dbt Cloud page in project settings to "integrations" 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#3867]
### Description

I think the dbt Cloud tab name is misleading to folks who expect it to be related to project configuration. For now I would just rename it to integrations, for now the only one we have is dbt Semantic Layer (which is the right term anyway, not dbt Cloud)

**Comment by hamzahc1** [comment]
Or rename to Semantic Layer or something like "Beta features" etc.

**Comment by TuringLovesDeathMetal** [comment]
@rephus this might be related to the Slack unfurl setup? 

Where were you thinking of putting that in the app?

**Comment by TuringLovesDeathMetal** [comment]
this has been renamed to semantic layer
