### ISSUE TITLE
Add support for fine-grained tokens on projects 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3869]
### Description

I added a fine -grained token to my dbt project, 
I gave it `contents permission

![image](https://user-images.githubusercontent.com/1983672/204584309-17e18f11-068c-43bf-b1c1-b88428f95fee.png)

If I update a project or create a new project with this new token, I get the following error

![image](https://user-images.githubusercontent.com/1983672/204584426-628fd831-0fb6-4932-88ca-7e2c6e313210.png)

**Comment by rephus** [comment]
Fine grained tokens require user along with the token, so it should look like this 
![image](https://user-images.githubusercontent.com/1983672/204742857-4f9fc8a1-8a57-4335-bb40-2af8026b6622.png)

In terms of UI, we could `detect` if the user adds a fine graine dtoken (starts with `github_pat_` ) and automatically display a new field called `user` and give that extra ragument to the `DbtGithubProjectAdapter`. But this form is not very flexible... so it is high effort, low impact. What do you think @TuringLovesDeathMetal @owlas  ?

I think for now I'll make a comment in the "new" docs to add `user` next to the token.

**Comment by hamzahc1** [comment]
Why is this blocked?

**Comment by TuringLovesDeathMetal** [comment]
Is there a way to improve the error message instead of improving the form? Or would that also be high effort? 

(e.g. we could detect if the user used `github_pat_` and didn't include `user:` and then could trigger that error message before any github-driven error messages?)

**Comment by ZeRego** [comment]
> Fine grained tokens require user along with the token

This seems to be a bug on their part 🤔 

Note that github doesn't seem to be validating the username when using a token (classic or fine-grained). 
https://github.com/community/community/discussions/36441#discussioncomment-4313583


@rephus what do you think if we changed the `DbtGithubProjectAdapter` to apply a mock username (eg: lightdash)?   

```
const remoteRepositoryUrl = `https://lightdash:${githubPersonalAccessToken}@${
            hostDomain || DEFAULT_GITHUB_HOST_DOMAIN
        }/${githubRepository}.git`;
```

This means we don't need extra validation. It will break project connections for users that have used our fine-grained instructions.
