### ISSUE TITLE
I want an easy way to know which dashboards/charts are stale

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3885]
I can do this already by looking at when they were last updated, but perhaps another way of being prompting to take action could help me keep things tidy.

**Comment by hamzahc1** [comment]
I think a general setting of all charts+dashboards should auto-archive after a period of time would help here with cleanliness. You could configure the time OR you have to explicitly say "don't ever archive this". Would go really well with something like #3872

**Comment by 12ian34** [comment]
I think "stale" here could mean a few different things:
- The dashboard/chart hasn't been changed (e.g. config or dimensions) recently
- The data behind the dashboard/chart hasn't been updated recently.
- The dashboard/chart has low views recently.

Let's be clear about which one we mean - I think it's the first one here you mean, but surely there are loads of dashboards which are indeed just perfect and don't need to be changed for a while?

Anyway, the closest thing I can think of for now is the Unused Apps features in iOS and Android. You get a periodic notification which you can tap into to get a list of unused applications along with the date they were last used. 

Perhaps we could think about incorporating this kind of thing into the notifications for admins, or maybe a panel on the home screen which only appears when there are stale dashboards/charts.

**Comment by PriPatel** [comment]
Nice!
@12ian34 Yeah I think I mean `The dashboard/chart hasn't been changed (e.g. config or dimensions) recently`.
This was based on a user's comment in this [thread](https://lightdash-community.slack.com/archives/C039GAKTPMK/p1669820096494659?thread_ts=1669810838.155549&cid=C039GAKTPMK) 
I thought it was interesting that they would be more inclined to look at a folder with more 'actively updated' dashboards/charts. But you're right - what if it's just perfect? 

+1 for notifications and auto-archive.

**Comment by hamzahc1** [comment]
@PriPatel - in the same thread you linked someone else mentioned stale-ness by how popular it is in the org - which leans more towards `The dashboard/chart has low views recently.` as the stale-ness measure. How recently a dashboard has been updated is an odd one since you could set up a dashboard that doesn't need to be changed ever (Weekly Active Users), but is viewed all the time

**Comment by TuringLovesDeathMetal** [comment]
+1 for stale-ness being based on views!

**Comment by hamzahc1** [comment]
@ZeRego - does any data for when a dashboard was last viewed (I guess queried or loaded as a proxy?) exist in our tracking today?

**Comment by TuringLovesDeathMetal** [comment]
^I don't think we actually have a `dashboard_id` included in our query events 🤔 

Also, I don't think we have a `dashboard_viewed` event. So I think we'd need to add something here?

**Comment by TuringLovesDeathMetal** [comment]
I imagine a `dashboard_viewed` event would be triggered once any charts are loading in the dashboard. 

This would mean that it would trigger on a page refresh, or if we eventually cache data, then I'd expect it to trigger if someone `clears cache and refreshes`. Otherwise, I think it might be tricky to define what "viewing" a dashboard actually means in terms of actions happening in the app? But maybe you have some better ideas @ZeRego

**Comment by TuringLovesDeathMetal** [comment]
We'd also need a way of measuring `chart_viewed` events (if we want to archive stale charts). 

I guess this could be a similar logic? If a chart is loaded in a dashboard, it triggers a chart_viewed event. If a chart is loaded in the explore view, it also triggers a chart_viewed event.

**Comment by ZeRego** [comment]
> @ZeRego - does any data for when a dashboard was last viewed (I guess queried or loaded as a proxy?) exist in our tracking today?

@hamzahc1 We don't keep information on what resources have been viewed/requested in the app database.

> I can't think of another way of defining what "viewing" a dashboard actually means in terms of actions happening in the app? But maybe you have some better ideas @ZeRego

@TuringLovesDeathMetal We shouldn't think about the actions in the UI that would trigger this but what endpoints in the BE mean "viewing" the dashboard.
Eg:
The endpoint to get dashboard metadata **wouldn't** add a "view" record.
The endpoint to get the entire dashboard data **would** add a "view" record.

We can add a "last_viewed_at" column to the dashboard and chart tables to keep track of this date.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego ah, sorry, I thought that loading a chart would trigger a backend event.

> We can add a "last_viewed_at" column to the dashboard and chart tables to keep track of this date.

Ideally, we also have a way of tracking individual views (we'll need this for features like tracking "most popular" charts and dashboards by views). 

Also having a `last viewed at` would be great. If there's a way to add both at the same time, that would be ideal - so when we get around to thinking about "most popular" features, we'll already have been tracking the data.

**Comment by 12ian34** [comment]
Superseded by https://github.com/lightdash/lightdash/issues/4058 and scoped/explained in https://www.notion.so/lightdash/Usage-Analytics-e6788f72ad874b3eb7a64aec481a43b3

**Comment by 12ian34** [comment]
Superseded by https://github.com/lightdash/lightdash/issues/4058 and scoped/explained in https://www.notion.so/lightdash/Usage-Analytics-e6788f72ad874b3eb7a64aec481a43b3
