### ISSUE TITLE
Server error when loading an echarts asset

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#3889]
### Description

server crashes/returns 500 error when requesting an asset.

![CleanShot 2022-12-01 at 16 54 37](https://user-images.githubusercontent.com/962095/205058248-04dba1c8-c8b4-4b64-8ef1-c4be12fca9fa.png)

### To Reproduce
❓❓❓

**Comment by ZeRego** [comment]
@IrakliJani was this while running the app in development mode?

**Comment by IrakliJani** [comment]
@ZeRego production, cloud user

thread: https://lightdash.slack.com/archives/C04C3PPR54K/p1669802829387359
