### ISSUE TITLE
Enable drill by dimension on charts

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3891]
## Description

A common flow that users take is:

- Click a chart element to get the context menu
- Click "show underlying values"
- Then "explore from here" - which launches a blank explore with the correct filters applied from the chart segment
- And then in the sidebar, change the dimensions to explore that segment by a different dimension

We could make this journey substantially shorter by allowing the user to choose a dimension directly from the context menu. The new flow:

- Click a chart element to get the context menu
- Choose "Drill by..." and show a list of available dimensions for that chart
- Click a dimension (e.g. country)
- Launch a new explore (in a new tab) with the correct filters **AND** the original metrics from the chart and selected dimensions.

## Example

From demo.lightdash.com

**Exploring**: support requests (each row is a single support request)

Starting chart shows the number of requests created per month

* Metric: total requests
* Dimension: created date month

Link: https://lightdash-demo-thyme.onrender.com/share/-Vp7tr3UkBOdTmCoGtCJu

The chart has 4 months of data. And 2022-01 is a big outlier (so many requests!!). So I click on the bar and see "view underlying data". **I would also like to see Drill By...** 

<img width="1497" alt="Screenshot 2022-12-01 at 14 35 17" src="https://user-images.githubusercontent.com/11660098/205079946-de195f48-3ef9-4c51-9410-49bfd6da3fe7.png">

Next I click **drill by "reason"** - "reason" is a category we attach to support tickets. So I'm saying "I want to further drill that bar by reason".

This would launch me into a new chart showing:

* Metric: total requests (same metric)
* Dimension: reason (the selected drill field)
* Filter: created date month = 2022-01 (the selected segment)

Link: https://lightdash-demo-thyme.onrender.com/share/NNC-IQ4tx-T0ocDvCE-BT

<img width="1486" alt="Screenshot 2022-12-01 at 14 37 41" src="https://user-images.githubusercontent.com/11660098/205080496-541b56a1-7ef8-4b23-a889-6b648ef953fa.png">

Now I can see that there were many product related queries and delivery issues during that month. That might explain the spike in the bar!

## Implementation

This is very similar to the existing implementation for view underlying values, where we're basically constructing a new explore.

See this file for logic: https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/UnderlyingData/UnderlyingDataModalContent.tsx#L42-L42

This logic should live in common along with other functions that generate explores / metric queries (e.g. applying dashboard filters to a query, getting query for underlying data, generating drill by queries etc.).

## A summary of the acceptance criteria

- [ ] Any chart element that encodes a single metric will now have the option to `drill by` in the context menu. 
- [ ] You need to select a dimension to `drill by` 
- [ ] You can select a dimension from any of the table's available dimensions (both the primary model and the joined models).
- [ ] There's a way to search for which dimension you want to add (similar to the filter selection component?)
- [ ] `drill by` launches a new explore (in a new tab) with:
    - the same filters as the original chart
    - an added filter for the x-axis value from the original chart value you clicked `drill by` on
    - if your chart was grouped, then there's an added filter for the group the value belonged to (e.g. if I had grouped my chart by `cloud` and `self-hosted`, but clicked `drill by` on the `self-hosted` part of the bar, then we'd add a `self-hosted` filter to the new chart)
    - the same y-axis values as the original chart
    - the x-axis value now becomes the dimension that you selected to `drill by`
- [ ] see an example of how this would work from a value in the results table [here](https://github.com/lightdash/lightdash/issues/3891#issuecomment-1339059091)
- [ ] The chart that is opened from a `drill by` is just the default chart configurations (we don't keep any of the config that was changed from the original chart). 
- [ ] You can drill into any chart element that encodes a single metric. So points on a line, bars, bar segments, big numbers, value in a table. As long as the value clicked encodes a single metric
- [ ] Things you can't drill into:
    - Point on a scatter chart of a dimension vs dimension
    - Point on a scatter chart of a metric vs metric
    - Value in a table that is a dimension
    - Any point that's a table calculation

**Comment by TuringLovesDeathMetal** [comment]
A few questions:
- Can I "drill down" on a dimension? Or only metrics?
- Do we use the same chart type as the existing chart? Or do we use a bar chart, by default?

**Comment by owlas** [comment]
Good questions!! 

> Can I "drill down" on a dimension? Or only metrics?

> Can I drill down from a point...

You can drill into any chart element that encodes a single metric. So points on a line, bars, bar segments, big numbers, value in a table. As long as the value clicked encodes a single metric

Things you **can't** drill into:
* Point on a scatter chart of a dimension vs dimension
* Point on a scatter chart of a metric vs metric
* Value in a table that is a dimension
* Any point that's a table calculation

> Do we use the same chart type

v1 I would use a blank explore with the default chart

**Comment by TuringLovesDeathMetal** [comment]
@owlas last question: 

> Choose "Drill by..." and show a list of available dimensions for that chart

^does this include _**all**_ of the dimensions available in the explore? If yes, do we want a search bar or something like in the filters menu so I can search for the dimension I want?

**Comment by owlas** [comment]
> Does this include all / joined

Yes I think so! It could be a long list so...

> Search bar

Seems like a great idea

> Drill into table

It should be possible to drill into a metric in a table:

1. The row defines the filters applied to the chart (like above) so apply filters for all dimensions on the chart row
2. y-axis is the metric clicked in the table
3. x-axis is the dimension selected in the drill context menu

So if I had

| dim 1 | dim 2 | my-metric |
|---|---|---|
| hello | Katie | 22 |

Then clicking `22` -> `drill by` -> `my new dimension` would give me:

* Filters: `dim 1 = hello` and `dim 2 = Katie`
* y-axis: `my-metric`
* x-axis: `my-new-dimension`

**Comment by TuringLovesDeathMetal** [comment]
nice! make sense. 

Sorry, one last question: would groups also be kept in the new chart? ([here's what I've defined so far in the acceptance criteria](https://github.com/lightdash/lightdash/issues/3891#:~:text=drill%20by%20launches%20a%20new%20explore%20(in%20a%20new%20tab)%20with%3A))

**Comment by owlas** [comment]
Ah I missed out groups! They would be become part of the filters just like in "show underlying values" so the result is always an ungrouped chart.

**Comment by TuringLovesDeathMetal** [comment]
ah, totally! that makes sense, duh. You select a value in a group (not the whole value without the groups) so that makes sense! 

Sweet, I'll add it in :)
