### ISSUE TITLE
Add user attributes

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3895]
### Description

This is blocking three requested features:

1. Row-level security (i.e. using fixed filters depending on the user in)
2. Dashboard UX (default filters depend on the user logged in)
3. Dynamic warehouse credentials (adjusting the warehouse credentials depending on user logged in)

User attributes are tags that can be applied to users such as "team: sales" or "default_warehouse: large_X2" or "favourite_colour: red" - the name and value of the tags are customisable.

To support all use cases there should be three types of user attributes:

* Regular user attributes, which the user can freely set and change. Modifying their behaviour around the app
* Secret attributes, which can be set but never viewed again by anyone.
* Admin-controlled user attributes, only the admin can set these attributes, the user is unable to change them

Once we have those set, we'll be able to start templating queries, yaml, and configuration with attributes such as:

```yaml
metrics:
  my_sales_target:
    type: sum
    filters:
      closed_by: "${user.attributes.sales_id}"
```

Or warehouse credentials like:

```
type: snowflake
username: "${user.attributes.warehouse_user}"
```

**Comment by 12ian34** [comment]
Would this rough proposal be able to support configuring user attributes by code or via a public API endpoint in the future?

**Comment by jw-aleksandr-zolotukhin** [comment]
+100!!!
`Row-level security (i.e. using fixed filters depending on the user in)`

Missing this might be a blocker for some to commit to Lightdash without a second thought. Like for us currently...

**Comment by jainanuj07** [comment]
This is a fundamental feature we are looking for as we have ranger integration with our metadata layer, and without user attribution, we are not able to support RBAC at the warehouse layer.

**Comment by TuringLovesDeathMetal** [comment]
THis is closed!
