### ISSUE TITLE
[CLOSE this at the end of the milestone] Support an embeddable view for iframes

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3897]
### Description

I want to have my charts and dashboards in an `iframe` so I can embed them into salesforce or notion or any other tool. However if the embed window is small I'm told that Lightdash doesn't work on mobile. And when it's large enough, there is a lot on the dashboard that I don't want to see (such as the navigation bar, lightdash branding, and save/edit actions).

I'd like a clean embed view for charts and dashboards so they can fit neatly with other content on a 3rd party website.

**Comment by francescomucio** [comment]
still relevant

**Comment by 12ian34** [comment]
+1 just been requested in the community!

**Comment by 12ian34** [comment]
sometimes referred to as "embedding". adding for searchability. definitely not stale.
