### ISSUE TITLE
Clicking back on Explore panel resets the state

### ISSUE THREAD

**Issue by silentninja** [lightdash/lightdash#390]
Clicking the back button on the Explore panel is resetting the state and clears out the table and the charts, not sure if this is the intended behavior.
Seems to be related to [Line](https://github.com/lightdash/lightdash/blob/4639abfc7ae46d1f41e26e8d386b51e608c0e633/packages/frontend/src/components/ExploreSideBar.tsx#L239)

**Comment by silentninja** [comment]
https://www.loom.com/share/4263ba82be5c4bea9dbf0fbf027dffc1

**Comment by owlas** [comment]
Hey @silentninja thanks for catching this! 

It's unexpected but we are also considering changing this behaviour too.

@ZeRego is the intention still to hold the explorer state when the user navigates back to the table list in the sidebar?

**Comment by ZeRego** [comment]
It is intentional for the state to clear when the user leaves the table page. I think we can improve the UI/UX by showing a message on the right side instead of the results/chart/etc components.
We could use the `<NonIdealState />` component with a message `Select a table to explore`.

**Comment by ZeRego** [comment]
@owlas  We could have a popup, similar to the one we once had, but the popup should be displayed when the user is leaving the table page instead of when is accessing a new one. 
Should we also implement a popup when leaving a saved chart with unsaved changes ?

**Comment by owlas** [comment]
Alternative: 

We could not have the list of explores in the sidebar. Rather have that as a separate view. So there is a much stronger feeling of entering and exiting the explorer. 

Rather than just a sidebar change.

**Comment by silentninja** [comment]
> It is intentional for the state to clear when the user leaves the table page ( even though the chart isn't clearing 🤔 ). 

`keepPreviousData` is set to `true`, retaining the previous data. 

Results Table shows empty because it uses explorer state for the check instead of the query data. For the state to be cleared properly, everything should rely on Explorer state instead of queryResults.

 I would prefer to keep the data unless there is a good reason. Wont be a good UX if the user has to decide between losing a query vs looking at other table

**Comment by ZeRego** [comment]
> Alternative:
> 
> We could not have the list of explores in the sidebar. Rather have that as a separate view. So there is a much stronger feeling of entering and exiting the explorer.
> 
> Rather than just a sidebar change.

@owlas Having a left sidebar and a right panel is the default page structure. I would avoid steering away from this (until we get a completely redesign ) since it makes our UI consistent. 

That's why I suggested using a `<NonIdealState />` component on the right panel instead of the current `<Explorer />` component.


> I would prefer to keep the data unless there is a good reason. Wont be a good UX if the user has to decide between losing a query vs looking at other table

@silentninja The explorer provider only supports 1 query state so it would be overwritten when the user selects a new table. 
We could change the provider to support a state for each table. This way the user can jump from one to the other without loosing his work ( until he closes the browser page ).

**Comment by silentninja** [comment]
I think a confirmation popup appears when changing the table. [The popup is still there](https://github.com/lightdash/lightdash/blob/d90d2b87f111674cef6573bbc71e561d4b976a47/packages/frontend/src/components/ExploreSideBar.tsx#L100)

**Comment by silentninja** [comment]
Love that idea and can see myself using it to compare queries. I remember having to use multiple tabs occasionally.
