### ISSUE TITLE
Markdown and Loom tiles should not show up as options in the 'tiles' tab of Dashboard filters

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3901]
<img width="1396" alt="Screenshot 2022-12-02 at 23 09 37" src="https://user-images.githubusercontent.com/12776522/205404609-2fd20e4e-7bb2-4935-958e-6ffa6ccd22b6.png">

**Comment by PriPatel** [comment]
@IrakliJani  We can close this, right? I feel like this was fixed recently..

**Comment by IrakliJani** [comment]
correct, fixed by https://github.com/lightdash/lightdash/pull/3952
