### ISSUE TITLE
Copy on invite user success is confusing

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3909]
### Description

When I invite a new user, it says "invite successful" but then it also tells me to copy a link. This made me think that the user didn't get an email sent to them as well. 

Instead, the copy should say: 
> We've just sent xxxx an email with their invite! You can also share their invite link with them to join your organization. This link will expire in 3 days.

<img width="851" alt="Screenshot 2022-12-05 at 16 41 51" src="https://user-images.githubusercontent.com/31848148/205679473-f7cf1646-a4ff-4266-bc70-581b9f45e4ab.png">

### Things to watch out for:
- we need to make sure that this `email` copy only appears if someone is invited in an instance that has an email server (some self-hosted instances might not have one!)

**Comment by rephus** [comment]
If the service doesn't have EMAIL provider, then we don't send the email, the only way is to share the link. Should we change the copy based on that ?

**Comment by TuringLovesDeathMetal** [comment]
Yep! I think I made a comment about that at the bottom. 

@rephus can we tell if the service has an email provider or not?
