### ISSUE TITLE
Move the dashboard filter tabs to the right-hand side

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3910]
<img width="360" alt="Screenshot 2022-12-05 at 17 24 56" src="https://user-images.githubusercontent.com/12776522/205701797-20985c6f-a74d-4080-84e3-f7f736374a2c.png">

This filter should naturally read 
" `Orders Email ` is equal to xxx ", but instead, there is a set of tabs in the way. 

It is not ideal, but for now, I think we should move the tabs to the right-hand side, as the 'tiles' tab isn't going to be applicable to everyone. It's also in MVP stage so it is best we don't get too in the way of people's existing workflows.

**Comment by hamzahc1** [comment]
Why is this blocked?

**Comment by PriPatel** [comment]
We found some issues with this so some more design decisions need to be made by me today.

**Comment by PriPatel** [comment]
Blocked by https://github.com/lightdash/lightdash-internal-work/issues/578

**Comment by hamzahc1** [comment]
What if we swapped the tabs + the filter? So the filter appears below the tab? 

<img width="489" alt="Screenshot 2022-12-19 at 11 33 37" src="https://user-images.githubusercontent.com/14341285/208417014-41c1a6fb-bdda-4f50-9f8d-350e6a0bd5d8.png">

**Comment by PriPatel** [comment]
Moving the tabs to the right-hand side causes issues when the field name is too long. Also, because the panel takes different widths on each tab, the transition between the two feels a bit jumpy and broken.

Moving the tabs to the very top _could_ work, but the field name should really be at the top as it is the constant between the two tabs. 

In https://github.com/lightdash/lightdash/issues/4008 , we have introduced a new label to the value inputs, which means we don't have the issue of the broken "Orders Email  is equal to xxx" sentence. 
@IrakliJani what do you think ? Maybe we can just close this ticket now?

**Comment by IrakliJani** [comment]
@PriPatel yep, https://github.com/lightdash/lightdash/issues/4008 addresses it so let's close this one.
