### ISSUE TITLE
Update notifications icon styles

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3918]
<img width="253" alt="Screenshot 2022-12-06 at 12 53 30" src="https://user-images.githubusercontent.com/12776522/205917593-7374fb4c-0e2d-4672-a90b-bf62859f2574.png">

The `bell` is a different colour compared to the `help` and `settings` icon. It should match them!
#abb3bf

**Comment by 12ian34** [comment]
now i can't unsee this

**Comment by IrakliJani** [comment]
- [ ] remove weird animations
![CleanShot 2022-12-20 at 14 26 44](https://user-images.githubusercontent.com/962095/208645082-8bb148b5-9e32-4dbf-ad84-029a783b5d16.gif)

![CleanShot 2022-12-20 at 14 22 27](https://user-images.githubusercontent.com/962095/208644751-610262f5-d498-47de-bda9-0c562d76fd4d.gif)


- [ ] remove inconsistent background widths
![CleanShot 2022-12-20 at 14 28 25](https://user-images.githubusercontent.com/962095/208645370-1773e7e7-b8ba-4e10-9468-2ba938abdd29.gif)

**Comment by PriPatel** [comment]
Lol thanks for the 'remove animations' one. They do my head in.
