### ISSUE TITLE
Feat: store slack snapshots on S3

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3925]
it seems that the AWS S3 API is basically the standard for cloud storage APIs. So we should use the node.js AWS client: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-node-examples.html

Then we can configure this for:
- AWS S3 (default)
- GCP GCS
- Azure storage
- MinIO for kubernetes / local storage in dev

_Originally posted by @owlas in https://github.com/lightdash/lightdash/pull/3852#discussion_r1041908064_

**Comment by rephus** [comment]
@owlas do we have already an AWS account ?

**Comment by rephus** [comment]
This is currently blocking eu1 (we have pod replication there) . And it will solve the problem of missing images after deploy

**Comment by owlas** [comment]
@rephus we should do this using GCP cloud storage rather than with AWS
