### ISSUE TITLE
Docs: Test and document how to install Lightdash Share (aka slackbot) on self-hosting

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3928]
### Description

This is mostly a doc ticket, I don't think we need to change the code to make this happen (all slack parameters are set in env variables) 

- First we'll have to create a doc about how to install lightdash share on your own slack workspace (similar to the original description of this ticket https://github.com/lightdash/lightdash/issues/2776) 
- Export slack app manifest. 
- Then we'll have to explain how to configure it on lightdash (which variables need to be set / how to get them) 

```
SLACK_APP_TOKEN
SLACK_SIGNING_SECRET
SLACK_CLIENT_ID
SLACK_CLIENT_SECRET
SLACK_STATE_SECRET
```

**Comment by TuringLovesDeathMetal** [comment]
Niiiice! @rephus I can test this on my app.lightdash.cloud instance with your help? Then I'm happy to write some docs for it too after? wdyt?

**Comment by rephus** [comment]
> I can test this on my app.lightdash.cloud instance with your help? Then I'm happy to write some docs for it too after?

Sounds great to me, once this is deployed we can give it a try

**Comment by rephus** [comment]
This was done a long ago
