### ISSUE TITLE
I want to be able to include colour ranges in my table conditional formatting rules

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3936]
### User story

I have a cohort retention table. It looks like this (but imagine it without the colours 🌚 )

![image](https://user-images.githubusercontent.com/31848148/206213892-81b1870d-9b70-4122-b994-d2de44bc8e76.png)

I want to add colours so it's easy to see at what stage users are retaining the most vs. churning the most. 

I could do this by adding a bunch of rules to my conditional formatting. But, it would be really nice if Lightdash would just "make these rules" for me automatically (basically, automatically building buckets/a scale for my colours). 

### Acceptance Criteria 

here's an example sketch: https://miro.com/app/board/uXjVPE1t3As=/?moveToWidget=3458764540678815107&cot=14

- [ ] when I create a rule, I can pick if it's a `single color` rule or a `color range` rule
- [ ] For a range of colours rule, you need to apply the following settings:
    - [ ] Select a colour that you want to have for the minimum values in your colour range
    - [ ] Select a colour that you want to have for the maximum values in your colour range.
    - [ ] Select the minimum value that you want the range to start at.
    - [ ] Select the maximum value for the range. 
- [ ] Ranges are set to 5 colours (separate issue for setting a custom number of values in the colour range here: https://github.com/lightdash/lightdash/issues/3764).
- [ ] for now, you can only set the min and max colour.

**Comment by rohan-thakur** [comment]
For this feature, it would be great if the `min` and `max` values didn't have to be fixed and by default just applied to the minimum and maximum values in the result set. I see this in the Miro sketch but wanted to say that that would probably make it easiest for the end-user as a default.

**Comment by IrakliJani** [comment]
> For this feature, it would be great if the `min` and `max` values didn't have to be fixed and by default just applied to the minimum and maximum values in the result set. I see this in the Miro sketch but wanted to say that that would probably make it easiest for the end-user as a default.

@rohan-thakur specced another ticket for auto min/max values 🙌  https://github.com/lightdash/lightdash/issues/6406
