### ISSUE TITLE
Autocomplete available columns for  table calculations

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#394]
It's extremely hard to decipher the correct reference for a column in a results table when writing a table calculation.

for example with these columns:

<img width="1371" alt="Screenshot 2021-08-31 at 16 01 38" src="https://user-images.githubusercontent.com/11660098/131526919-a645da8e-e749-4369-9234-8cb59eac65db.png">

The correct references would be `${payments.payment_method}` or `${payments.payment_count}`

e.g. in a table calculation I would use this:

<img width="548" alt="Screenshot 2021-08-31 at 16 02 42" src="https://user-images.githubusercontent.com/11660098/131527154-4bbef6c4-f9cc-40ad-b922-dbd48ddb5c9f.png">

If a Lightdash user isn't familiar with the template syntax, they'll never figure this out. 

My best shot for fixing this would be to use autocomplete in the sql box using a code editor component (e.g. [ace](https://ace.c9.io)). But would be interested to hear any other ideas for this UX bug

**Comment by ZeRego** [comment]
This looks more like an improvement than a bug.
