### ISSUE TITLE
Dashboard filters are showing me the wrong fields for my tiles

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3948]
### Description

On the KPI dashboard, I have a tile for `number of production instances, weekly`. It's only showing Github Daily fields as the fields I can filter on...but I know that the explore includes `organizations daily, date`. 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/31848148/206430959-031eeb6a-defa-4e5c-872a-a31748c549e9.png">

<img width="482" alt="image" src="https://user-images.githubusercontent.com/31848148/206431014-d56d703e-89d8-4875-896e-43f5ba502f3c.png">

(If I `explore from here` from the tile):
<img width="409" alt="image" src="https://user-images.githubusercontent.com/31848148/206431129-88686128-73e9-4b68-8288-f4544e34b240.png">

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal this should have been fixed by https://github.com/lightdash/lightdash/pull/3952 but I'll confirm (and close this ticket) once we get the deployment out

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal as I suspected this has already been fixed in #3952 
can you confirm and we can close the ticket

https://user-images.githubusercontent.com/962095/208429404-88321237-9561-4f8a-a142-ffcef581a0a4.mp4

**Comment by TuringLovesDeathMetal** [comment]
niiiice! @IrakliJani going to close this one then :)
