### ISSUE TITLE
Pressing "save query as" makes the chart view open

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#395]
If I save a query while the chart view is hidden, the chart pops over.

I was expecting the chart view to stay hidden.

https://www.loom.com/share/20ea2863bace45c8a7b215791ab002a3

**Comment by ZeRego** [comment]
@owlas This happens because we redirect to the saved chart page. That page opens the chart view and runs the query automatically on load.
We can use url params or similar to prevent that behaviour after save.
