### ISSUE TITLE
Threshold alerting (slack)

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#3961]
### Description

I would like to be alerted in some way when certain metrics reach thresholds that I can define myself on a per metric basis.

### What problem does this solve?

This is a common feature request from our customers that some other tools provide. This solves a problem of needing to repeatedly check charts or dashboards for metrics. For example, if your Sales revenue was falling below a certain threshold, it would be great to just be alerted about that when it happens, rather than to keep checking the Sales dashboard every day.

### MVP criteria
**How do I access the feature?**
- [ ] You should be able to create one or more alerts for any saved chart using the three-dot menu

**How do I set up the threshold?**
- [ ] You should be able to name your threshold alert
- [ ] You should be able to pick any numeric field that is used in the selected chart (metric / custom metric / dimension) to set the threshold on. 
- [ ] You should be able to pick from two conditions - `is greater than (or equal to) xxx` or `is less than (or equal to) xxx` 
- [ ] You should be able to pick the value from a number input field

**How do I pick the destination?**
- [ ] You should be able to pick one or more Slack channels to send the alert to. This should work similarly to the way you pick slack channels in the `scheduled deliveries` form

**What happens next?**
- [ ] Lightdash will run a daily query to check if the threshold has been crossed (when exactly?) 
- [ ] If the threshold has been crossed, the relevant Slack channels will be sent a message 

**What if I want to update the delivery?**
- [ ] You can see a complete list of alerts per chart when you click on 'alerts' from the 3-dot menu
- [ ] You can edit the alert by clicking on it
- [ ] You can delete the alert

**Comment by 12ian34** [comment]
This has been requested by a few customers!

**Comment by yu-iskw** [comment]
I would like the feature too. I don't think Lightdash supports something like anomaly detection. But, it would be useful to send notifications if a monitored value meets defined conditions.

**Comment by tlfbrito** [comment]
We would also like to see this implemented 👍

**Comment by tlfbrito** [comment]
We want to create a set of rules that once they reach to a certain threshold, we want to send alerts/notifications.
