### ISSUE TITLE
The "Create new Dashboard" flow should be similar to the "Create new Space" flow. 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3964]
When you `Create New Dashboard`, the dashboard is created right away and you're redirected immediately. This can be confusing and feels a lot more alarming now that you can create dashboards from the navbar! I also can't count the amount of times I have accidentally created an "Untitled" dashboard and forgotten to delete it. 

<img width="949" alt="Screenshot 2022-12-09 at 14 58 21" src="https://user-images.githubusercontent.com/12776522/206730143-e3f23fa3-ec89-4886-8a59-ff59cd4c68cc.png">

- [x] When you 'Create a new dashboard', you should see a modal prompting you to name the dashboard (and give it a description, but this is optional). This is the same modal you see when you rename the dashboard, but instead, the title should say `Name your dashboard`. Instead of `Save`, it says `Create`.

- [x] Once you hit `Create` the dashboard is created, you are redirected and see the success toast. 

- [x] This should affect the `+Add Dashboard` button in the navbar, and the `+Create dashboard` button on the "`All dashboards`" page

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel it would be great if when you created the dashboard, it opened into that dashboard in edit mode (see this issue: #3016 )
