### ISSUE TITLE
Dashboard as code

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3974]
### Description

Create and update dashboards from YML.

### Acceptance criteria

[ ] The CLI will find dashboards yml inside space folders that contain `.space.yml` ( if folder doesn't have`.space.yml`, ignore those files )
[ ] dashboard yml contains ...
[ ] resources should be created/updated when running the commands `deploy`, `preview`, `preview-start`
[ ] Migrate `dashboard` table to have a `slug` and `project_uuid` columns with unique constrain + change space_uuid constrain to also depend on project uuid
[ ] DB changes need to be in a single transaction

Example folder structure:
```
lightdash
└── spaces
    ├── marketing
    │   ├── .space.yml
    │   └── dashboard1.yml
    └── sales
        ├── .space.yml
        └── dashboard2.yml
```

Example `dashboard1.yml`:

```
resource: v1/dashboards

slug: my-chart
label: My chart
description: My chart description
tiles:  ** todo ** 
filters: ** todo (horrible api) **
```

### Technical implementation

1. CLI gets all the resources info and sends to BE endpoint
2. BE converts those objects to latest type and saves in DB

**Comment by tnightengale** [comment]
I am very interested in this as well. @TuringLovesDeathMetal any plans for this?

**Comment by jw-aleksandr-zolotukhin** [comment]
This feature would be a game changer IMO and very remarkable functionality. 
I'd probably not even think twice RN and just commit to Lightdash if this would be possible already.
Reports/dashboards in as code (in git) are the dream for many BI people that suffered without that for decades.

P.S.:
this should not replace though ability to create reports in GUI for simple peasant users.
