### ISSUE TITLE
Display time-interval format in tooltip rather than raw date 

### ISSUE THREAD

**Issue by serene-capybara** [lightdash/lightdash#3979]
### Description

If I select `Quarter` or `Year` as my time interval for a date dimension, I would like the tooltips to display the same format as my axis labels, i.e. `YYYY-QQ` for quarter and just `YYYY` for year.

Also, the time interval format should display on the axis label on hover (right now, it changes to the full format on hover)

https://www.loom.com/share/385840e9d1cf4b498b2e4aba4433abcc

**Comment by TuringLovesDeathMetal** [comment]
Hey @serene-capybara - would you mind sending a screenshot of the problem? 

When I select Year, it just shows the year as YYYY on the axis tick label 🤔 

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/31848148/210345861-dc843149-bf9a-48c3-951d-7a2f7e0fbf62.png">

**Comment by serene-capybara** [comment]
Hey Katie,

It's actually not the axis labels I'm referring to, but the tooltip or "hover text" when the cursor is hovering over the chart. Sorry, I won't be able to provide a screen shot for a couple of weeks when I am back in the office.

As always, thank you for the reply!

Best,
Ethan

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TuringLovesDeathMetal** [comment]
ah, okay, I get it. Sorry, my mistake!

Cool, I've added a Loom recording of the issue in the description 👀 and I've updated the issue title!

**Comment by IrakliJani** [comment]
this is still relevant. another user is having the similar issue

![CleanShot 2023-09-18 at 17 01 50@2x](https://github.com/lightdash/lightdash/assets/962095/ae36b348-7f2e-435f-ae7f-9f6031fa4f52)

**Comment by ZeRego** [comment]
Open ticket in echarts repo on 'How do you specify date format in tooltip?':
https://github.com/apache/echarts/issues/16703#issuecomment-1135375182
