### ISSUE TITLE
Table chart roll-up rows

### ISSUE THREAD

**Issue by serene-capybara** [lightdash/lightdash#3990]
### Description

Add table configuration option to show a roll-up total of a set of dimensions.

### What problem does this solve?
This would combine related information into a single table, rather than requiring two graphs with different dimensions.

**Comment by TuringLovesDeathMetal** [comment]
Hey @serene-capybara - can you give an example of when you'd use something like this? I'm having a hard time imagining what it could look like 🤔

**Comment by serene-capybara** [comment]
Here is an example of how our org would use this feature.

![image](https://user-images.githubusercontent.com/116363294/208153663-c6daa455-fbfb-40e2-9ee0-ced2aec068fd.png)

Thanks!

**Comment by TuringLovesDeathMetal** [comment]
CLosing this as a duplicate of: #7992
