### ISSUE TITLE
Metric Filters page needs examples of inequality filters

### ISSUE THREAD

**Issue by serene-capybara** [lightdash/lightdash#3991]
**Link to existing docs:** 
https://docs.lightdash.com/references/metrics/#filters
**Changes?**
Needs examples for filters beyond basic equality. The code examples in the table for inequality result in invalid yaml.

**Comment by TuringLovesDeathMetal** [comment]
@serene-capybara 

- for the invalid yaml...oh no! that's not great. Would you mind showing me the example of what your yaml looked like so we can try to debug it? 
- For the "needs examples" bit, do you mean that the examples in[ this table](https://docs.lightdash.com/references/metrics/#available-filter-types) weren't enough to understand what the filters were doing? Or do you mean that there were some filter types that weren't in that table which you needed?

**Comment by serene-capybara** [comment]
> @serene-capybara
> 
> * for the invalid yaml...oh no! that's not great. Would you mind showing me the example of what your yaml looked like so we can try to debug it?
> * For the "needs examples" bit, do you mean that the examples in[ this table](https://docs.lightdash.com/references/metrics/#available-filter-types) weren't enough to understand what the filters were doing? Or do you mean that there were some filter types that weren't in that table which you needed?

![image](https://user-images.githubusercontent.com/116363294/208148146-ad7ae247-840f-4317-8a76-9d580daf5eec.png) for instance

I have tried wrapping portions of the yaml in strings, liquid expressions, etc. to no avail.

I think the "Example (as code)" column of that table is not correct, at least for the inequality operators, not that I don't understand what they're meant to do.

Thanks for the reply, @TuringLovesDeathMetal !

**Comment by TuringLovesDeathMetal** [comment]
we've fixed the docs here!

Sorry for such a delayed reply. You need "" around metric flters (as shown here: https://docs.lightdash.com/references/metrics#available-filter-types)
