### ISSUE TITLE
Table chart numeric column formatting

### ISSUE THREAD

**Issue by serene-capybara** [lightdash/lightdash#3992]
### Description

Table chart gives user the ability to format numeric values.
Examples: Format decimal values as percentages; Format positive/negative values as (black/red) or (green/red).

### What problem does this solve?
UX: Allows clearer presentation of numeric values.
DX: Saves developer from verbose table calculations.

**Comment by TuringLovesDeathMetal** [comment]
Nice @serene-capybara ! 

I think we have a few open issues for this already. 

Here's a milestone for formatting things in yaml and in the table calculation (I know, not what you're talking about here, but it's the precursor to adding this in the chart config/table calculation config): https://github.com/lightdash/lightdash/milestone/58

Then there's another open issue here for formatting values in the UI: https://github.com/lightdash/lightdash/issues/1836

I'm going to close this issue as a duplicate! But let me know if you think there's anything missing from the other issues I've linked above 👀
