### ISSUE TITLE
Add/Remove Dimensions from Dashboard

### ISSUE THREAD

**Issue by serene-capybara** [lightdash/lightdash#3995]
### Description
_this is probably a big ask..._

When viewing a dashboard, the user may add, remove, reorder, relabel, and group dimensions across multiple charts. Giving a chart the ability to be selected in this way in a dashboard might be a exposed as a new generic config option for charts, like "Metric Template."

### What problem does this solve?

This will essentially act as an explore view at the dashboard level, and greatly enhance the reuseability of charts.

**Comment by TuringLovesDeathMetal** [comment]
@serene-capybara interesting!

We have the option to cross-filter, drill-down, and a couple of other dashboard interactivity features listed here: https://docs.lightdash.com/guides/interactive-dashboards

Is this the kind of thing you're talking about? 

Or do you mean more that you have saved charts, and they can be added to dashboards, but you can "customize" those base charts in each dashboard? (e.g. change the label of a chart in a dashboard, or the colours, etc.) but it won't change the "underlying" saved chart?

**Comment by serene-capybara** [comment]
> @serene-capybara interesting!
> 
> We have the option to cross-filter, drill-down, and a couple of other dashboard interactivity features listed here: https://docs.lightdash.com/guides/interactive-dashboards
> 
> Is this the kind of thing you're talking about?
> 
> Or do you mean more that you have saved charts, and they can be added to dashboards, but you can "customize" those saved charts in each dashboard? (e.g. change the label of a chart in a dashboard, or the colours, etc.) but it won't change the "underlying" saved chart?

Like the global filtering options in the dashboard view, I am talking about inserting Dimensions into all charts within a dashboard, without needing to edit each individual chart.

It is possible to do this in Grafana through SQL templating, e.g.
```sql
SELECT
....
FROM table
GROUP BY ${ selectedColumns }
```
Where `selectedColumns` is a drop-down selection on the dashboard interface.

I hope that is more clear...

Thanks for the response @TuringLovesDeathMetal !

**Comment by serene-capybara** [comment]
@TuringLovesDeathMetal, I'll add one more use case that I've run into frequently. This might be a more modest ask because it's limited in scope:

When viewing a dashboard, I often want to view the same data, with the same categorical dimensions, but I want to view it at different time grains, (e.g. Fiscal Year, Fiscal Quarter, Month). Currently the only way to do that is to produce 3x as many charts, 3x as many dashboards, or drill-by each time I want to see a different time grain. If I could select the most granular time field as a dimension when creating the chart, then have the option at the dashboard interface to roll it up to a coarser time grain, this would enhance the versatility of the charts created.

Cheers!

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned!

We've added date zoom more recently so you can do something similar to your latest request. 👀 

We'll also be adding tabs so that you can add multiple "versions" of a dashboard that are related to each other. 

I think that we'll have more ideas of flexibility in the future, but this feels like quite a big change that can be picked at by smaller features (like date zoom!)
