### ISSUE TITLE
Build a scheduler to trigger tasks, required for sending email/slack notifications

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4013]
We want to enable time-based alerting, for that we need to schedule jobs:

> **Time-based alerting:** A lot of data consumers don't want to open a tool to get their answer, and it's more common to receive a regular (weekly, fortnightly etc) report of the key metrics of your business. This would help those users interact with Lightdash insights more often. It reduces the need for more people to go through onboarding to get access to their company's data.

## Scheduler architecture

Building a simple loop that will check if `now === scheduled` time and trigger tasks will not be enough, as it will run into `missing` or even `duplicated` jobs. 

![image](https://user-images.githubusercontent.com/1983672/208642734-59310517-6a5f-4ac0-9108-f68db446ce2a.png)

We'll have to have a `schedule` object (stored in database) , that will contain at least the following information: 

- frequency: it will contain how often we need to trigger the job (we will probably have to transform the UI (hourly, daily) into a [cron format](https://crontab.guru/) or similar.  https://www.npmjs.com/package/cron-converter (in UTC) 
- action: the action to perform, it could be send an email to X recipients, or send to slack 
- content: the object we want to share (dashboard/ chart) 

Then we will have a "single" scheduler service running (it could be a setInterval) will have to check the scheduled jobs , and it will create `Jobs` (if they don't exist) in the database that will convert the frequency into a timestamp, and will have a boolean flag to confirm if the task was executed or not. with the following information: 

- time: timestamp for the job to run 
- action: same as scheduler
- content: same as scheduler
- triggered: boolean flag to tell if we've triggered this already, to avoid duplications or missed jobs. 

## Example

I want to have a task called `Send me an email at 9am and 6pm on weekdays about jaffle dashboard`

Schedule will look like: 

| Frequency  | Action | Content |
| ------------- | ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/1983672/208638357-075db500-ff6a-450b-bc59-de87732b78aa.png)  | Send email to  [javier@lightdash.com]  |  type: dashboard, Jaffle dashboard uuid |

This scheduler service will check on database if we have already daily jobs for this schedule, if not, it will create the following jobs: 

| Time  | Action | Content | Triggered | 
| ------------- | ------------- | ------------- | ------------- |
| 2022-12-21T04:00:00Z  | Send email to  [javier@lightdash.com] | type: dashboard, Jaffle dashboard uuid | false | 
| 2022-12-21T06:00:00Z  | Send email to  [javier@lightdash.com] | type: dashboard, Jaffle dashboard uuid | false | 

Then a job service will go through all pending tasks (triggered==false) and trigger them when time is right (or it has happened)

 
## Acceptance criteria 

- [ ] I want to have a service that will trigger actions based on my schedule
- [ ] Cron and job times are in UTC. local timezone should be converted to UTC so they get emails at the right time.
- [ ] Make sure only 1 scheduler is CREATING jobs. This is important if we have replication. Two ways of solving this: 
     - better: implement db lock or transaction, so only 1 pod can read and write jobs at the same time
     - easier: only 1 pod can run scheduler
- [ ] Make sure only 1 job service is RUNNING jobs. Similar to scheduler. 
- [ ] Make sure scheduler  and jobs can run even if server goes down . For example, if we're in a middle of a release, we don't want to skip jobs, this can be done by checking if `scheduled time <= now`
- [ ] We already have  the concept of `jobs` , for async actions on the backend, like creating a project, use `task` instead for one of these jobs (to test the scheduler). E.g. sending emails or compiling a project.

**Comment by owlas** [comment]
I think it would be a good time to have jobs managed by a separate service, since we'll eventually have to build so much of the scheduling stuff in case of failures, or to scale up the job workers separately from the API server. Managing state is also going to be annoying, the current jobs api we have for doing the explore compile job is quite complex.

2 that come to mind:

- This is very popular and battle tested but it will add 4 (!!!) micro services to our deployment. Enterprise ready but maybe too heavy? https://temporal.io
- This fits our stack very nicely (it's node + postgres) and is much simpler but unsure if we can scale it separately to the API server: https://github.com/timgit/pg-boss

We would run either of these as a separate service that the API server can call out to

**Comment by ZeRego** [comment]
>Just found this which seems like a more modern (100% typescript, more stars, updated yesterday, Netflix sponsored) alternative to pg-boss above: https://github.com/graphile/worker

^ also has better docs showing examples of how to run a worker (containing task definitions) and separately how to use the library to queue a job from another service (e.g. our api server)

Read their docs and seems to have everything we need 🥳 

Use their docker image and setup a single cronjob that runs once a day ( supported by the library ). This task will fetch all schedulers from our table and create all jobs for that day.

The only part we need to figure out is how to update and delete jobs when a user edits/deletes the scheduler. Didn't see an obvious way to relate/identify what jobs belong to what scheduler. There might be a metadata property we can use or we might need to keep that information in our own table.
