### ISSUE TITLE
UI Improvements to the 'Projects' dropdown

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4016]
- [ ] If there is only one project, this element should not look like a dropdown, as it is misleading to click on it and feels weird. 

- [ ] The project dropdown should have a fixed width and if the project name is too long, it should be truncated. You can still see the full project name when you click on the dropdown.

<img width="351" alt="Screenshot 2022-12-20 at 12 56 49" src="https://user-images.githubusercontent.com/12776522/208672297-239a8764-9074-4358-815f-64b079e429f8.png">
<img width="301" alt="Screenshot 2022-12-20 at 12 56 53" src="https://user-images.githubusercontent.com/12776522/208672304-4dc593cf-2e05-4aba-84cf-6ac6359fd9af.png">
It looks really wide and weird here!

**Comment by TuringLovesDeathMetal** [comment]
yes! If there's only one project, then you shouldn't see any dropdown.

85% of orgs have only one project (and 70% of weekly active orgs only have one project). So we should definitely make it look a bit nicer for the majority of people :)  

@PriPatel the only thing is preview environments spin up/spin down - I guess if there is a preview environment, then it would look like a drop-down again?

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal 
Yea! So we have two options: 
either hide the dropdown completely and show it when the environment has been spun up, OR just have the current project name as text which turns into a dropdown when the new environment has been spun up.

**Comment by TuringLovesDeathMetal** [comment]
hmmm...I feel like hide the dropdown completely? what do you think?

**Comment by PriPatel** [comment]
This has been taken care through the Mantine migration
