### ISSUE TITLE
Error migrating the database when setting up lightdash using install script

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4018]
### Description

getting an error with knex when running the migration

```
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

### To Reproduce

thread 1: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1670344609483369
thread 2: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1666927757498709

**Comment by ZeRego** [comment]
Looks like a user solved this issue by setting timeouts in knex configuration.

https://lightdash-community.slack.com/archives/C03MG2VTR08/p1675272520539599?thread_ts=1674741673.750629&cid=C03MG2VTR08

> Sebastian Okser
>   [26 days ago](https://lightdash-community.slack.com/archives/C03MG2VTR08/p1675272520539599?thread_ts=1674741673.750629&cid=C03MG2VTR08)
> So I don't think that is it, as we're only using a single container for connecting and we have 100 connections available. However, from a forum on another tool called Strapi we found that we have to update the knxexfile.ts to add timeouts. We're currently testing:

```
/**
 * Switch behaviour of database connector depending on environment
 */
import { Knex } from 'knex';
import path from 'path';
import { parse } from 'pg-connection-string';
import { lightdashConfig } from '../config/lightdashConfig';

const CONNECTION = lightdashConfig.database.connectionUri
    ? parse(lightdashConfig.database.connectionUri)
    : {};

export const development: Knex.Config = {
    client: 'pg',
    connection: CONNECTION,
    pool: {
        min: lightdashConfig.database.minConnections || 1,
        max: lightdashConfig.database.maxConnections || 3,
        acquireTimeoutMillis: 300000,
        createTimeoutMillis: 300000,
        destroyTimeoutMillis: 300000,
        idleTimeoutMillis: 30000,
        reapIntervalMillis: 1000,
        createRetryIntervalMillis: 2000,
    },
    acquireConnectionTimeout: 1000000,

    migrations: {
        directory: path.join(__dirname, './migrations'),
        tableName: 'knex_migrations',
        extension: 'ts',
        loadExtensions: ['.ts'],
    },
    seeds: {
        directory: './seeds/development',
        loadExtensions: ['.ts'],
    },
};
```
