### ISSUE TITLE
feature: Make slack unfurls dynamically and more responsive

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4019]
### Description

Right now, it takes several seconds (we even get some timeouts) to fetch a screenshot for the unfurl. Currently, until the screenshot is generatd, we don't unfurl anything, but that can change. 

We could dynamically expose the content available on slack as soon as it is available (showing the dashboard name/description can take just a few miliseconds) , so we don't have to do it in one go. I think it the result looks very cool. 

[Screencast from 20-12-22 15:18:04.webm](https://user-images.githubusercontent.com/1983672/208689180-02a884e3-882b-4374-8ba6-5ea0a1155d0a.webm)

This will require a bit of refactoring. We'll have to split the current process (getDashboard, saveScreenshot, etc...) and make different requests to slack (with different sets of blocks)

**Comment by rephus** [comment]
@TuringLovesDeathMetal @hamzahc1 I think you might like this

**Comment by hamzahc1** [comment]
I really like this! It also guarantees the user they'll get their preview, right now if it doesn't appear after a few seconds you'd probably thing it's broken.
