### ISSUE TITLE
we should mention that DBT is required to run the Lightdash CLI

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4021]
**Link to existing docs:** https://docs.lightdash.com/get-started/setup-lightdash/get-project-lightdash-ready#step-1-install-the-lightdash-cli-tool

**Changes?**
we should update the docs and we should also update the onboarding screen

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned - I think we should have this made clear even earlier on (i.e. you shouldn't even be trying to use Lightdash if you don't have dbt based on our website/marketing/etc.)
