### ISSUE TITLE
Add login with Google screen is confusing

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#4028]
### Description
current:
![image](https://user-images.githubusercontent.com/67699259/208912163-0d7fc731-68c7-493f-903d-beca9276e291.png)

expected:
![image](https://user-images.githubusercontent.com/67699259/208910901-51eabad4-9168-4082-b206-d862d712a0f2.png)

**Comment by owlas** [comment]
This looks much better!! Great job @yasmin-e

**Comment by yasmin-e** [comment]
all credit goes to @PriPatel for the beautiful and non-confusing design
