### ISSUE TITLE
On the dashboard, clicking on a chart title should redirect to the explorer in view mode

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#4030]
### Description

Adding interactivity to the title.
Currently, the only way to get to a chart is by using either `explore from here` or `edit chart`.

- [ ] when you click on a chart dashboard tile title you should be redirected to the chart in `view` mode

### What problem does this solve?

Bad UX

**Comment by PriPatel** [comment]
Let's add a hover state so that when you hover over the title, as well as seeing the description (if there is one,), the title is underlined.
