### ISSUE TITLE
Update the copy on drill by

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4034]
### Description

The sub-menu should say `drill into "___"`. For example, here, it would say `drill into "924"`

<img width="226" alt="image" src="https://user-images.githubusercontent.com/31848148/208947730-d3278f6f-5dfc-4e17-9285-584cab348440.png">

The modal that pops up should say 
`Drill by dimension` --> `Drill into "924"`
`pick dimension to drill by` --> `pick a dimension to segment your metric by`

<img width="508" alt="image" src="https://user-images.githubusercontent.com/31848148/208948363-c1d588b2-66b4-45e4-9011-7d021961d484.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/31848148/208947820-6cf0ee15-9ab9-4000-96dc-6693f226b39f.png">

**Comment by PriPatel** [comment]
Nice ! I'd reference the actual metric somehow in the modal as well as a reminder. So maybe the title is "Drill into '432'" or something.
