### ISSUE TITLE
Run models from CLI by folder with `lightdash generate`

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#4046]
### Description

Espen Arnøy requested:
Is there a way to tell `lightdash generate` to generate only for models in a specific folder?

*[It's supported by dbt](https://datacaffee.com/wp-content/uploads/2021/03/dbt-_commands.pdf).

**Comment by yasmin-e** [comment]
@rephus

**Comment by TuringLovesDeathMetal** [comment]
This works using selection flags. 

Lightdash CLI supports all the same selection flags as dbt. I'd suggest using tags or model selection syntax
