### ISSUE TITLE
Tooltips' text doesn't wrap and takes full width

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#4048]
### Description
using this screen as an example, but it's actually **NOT** the case for the description tooltip on title hover in dashboard tiles 

![image](https://user-images.githubusercontent.com/67699259/209178855-e87c383c-1264-484c-9eb3-bdfd8f5e3b28.png)

The fix for this is to wrap the content of tooltips in a styled component because Blueprint's tooltip has no support for it
Maybe Mantine does @IrakliJani

**Comment by joaoviana** [comment]
After mantine migration this is no longer the case

<img width="1164" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/33658dac-1478-4ab9-95b6-6985105c6c61">
