### ISSUE TITLE
Charts API: view charts without query api

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4053]
### Description

The **current flow** to view a chart goes like this:

1. Get saved chart/query definition
2. Submit this definition to the run query end point
3. get results and build the chart

The problem with this is that the API used in step 2 is very flexible. This makes it very hard to restrict what data a user should have access to if they have access to the chart.

The proposed simpler flow is:

1. Request saved chart/query with results
2. Build chart with the returned results

This new endpoint would return the saved query, chart, and results data. This would allow a user to get a rendered chart and set of results without needing access to the run query api.

The api could also accept a list of dashboard filters etc., which could be resolved on the backend instead of the frontend.

**Comment by owlas** [comment]
Removing from the iframes milestone because we can achieve it with a new API endpoint and and not refactoring the old one for now.

**Comment by dvyach** [comment]
Any update on this please?

**Comment by ZeRego** [comment]
Closing this issue since we already have and use this endpoint in the app.

```[POST] /api/v1/saved/{chartUuid}/chart-and-results```

Docs: https://docs.lightdash.com/api/v1#tag/Charts/operation/postChartResults
