### ISSUE TITLE
API to create and view public charts

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4055]
### Description

Allow users to generate a public URL for viewing a chart. Anyone with the link will be able to view the rendered chart without authenticating with Lightdash.

### Flow for internal user creating a public link

- User must be logged in
- User must have edit access to a chart
- Create token

```
# Request
POST /api/v1/saved/{chartUuid}/publicTokens
{}

# Response
{
  "public_token": "xyz123",
  "public_url": "https://my.lightdash.com/public/chart/xyz123"
}
```

```mermaid
graph LR
    Start(Start)
    Login
    viewAccess{View access?}
    nope[Not allowed]
    Start-- chartUuid -->Login
    Login-- userUuid -->viewAccess
    viewAccess -- No --> nope

    viewAccess -- Yes --> Chart

    Chart[View chart internally]
    Chart --> editAccess
    editAccess{Edit access?}
    editAccess -- No --> nope
    Publish[Publish to web]
    editAccess -- Yes --> Publish
    publicToken(Public token: xyz123)
    Publish --> publicToken
```

### Flow for external user viewing a chart

- Given a public chart token
- Get the chart definition
- Get the chart results

```
# Request
GET /api/v1/public/charts/xyz123

# Response
{ chart definition } // do we need to redact some fields?

---

# Request
POST /api/v1/public/charts/xyz123/results
{}

# Response
{ results }
```

```mermaid
graph LR
    Start(Start)
    Start -- public_token --> Chart
    Chart[View chart externally]
```

**Comment by ZeRego** [comment]
What is the advantage of getting the results in a separate endpoint?

**Comment by owlas** [comment]
We need an endpoint to delete the token and list the tokens

**Comment by TuringLovesDeathMetal** [comment]
Closed as not planned (work is being tracked in this milestone for embedding: https://github.com/lightdash/lightdash/milestone/132
