### ISSUE TITLE
After editing a chart title or description and hitting save (from dashboard), the success toast message doesn't contain a `go to dashboard`  button

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#4056]
### Description
https://user-images.githubusercontent.com/67699259/209346385-12fc0d71-f8b9-426b-8ad4-9b73c0bcd7f9.mov

**Comment by PrashantIndurkar** [comment]
hello i want to work on this bug but not understand where should be the button got to go to dashboard is it on the toast? not sure
