### ISSUE TITLE
Track the number of views for charts and dashboards

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#4058]
### Description

As described in the [Usage Analytics proposal](https://www.notion.so/lightdash/Usage-Analytics-e6788f72ad874b3eb7a64aec481a43b3), this is the first step toward solving the problem.

### What problem does this solve?

The completion of this issue will allow the frontend in Lightdash to be able to read the total view counts for each chart and dashboard in the project. This enables a most popular charts/dashboards section for the homepage redesign. This also enables future work in this milestone for a usage analytics dashboard and modal.

#### Backend

- We need a  new table (or tables) to track analytics (views, created, last_updated, dashboard_uuid/chart_uuid) (we can replicate the value of created and last_updated, or we can populate this field from the same data in dashboard/chart table). We'll need to differentiate between successful and failed views, because when a user tries to view a chart or dashboard they don’t have access to, this will count as a view, but we don't want to count these views in any usage analytics.
- Analytics model
- Analytics service
- Analytics router
- GET endpoints (update should be done in the backend)

**Comment by 12ian34** [comment]
This issue has superseded: https://github.com/lightdash/lightdash/issues/3885

**Comment by TuringLovesDeathMetal** [comment]
Can we please have these as analytics events as well? (i.e. they get sent to BigQuery)

Happy to open another issue for this if it's separate :)

**Comment by TuringLovesDeathMetal** [comment]
Another thing: Is there an easy way to map a chart/dashboard's UUID to the chart/dashboard's name? 

Just thinking that when we build a dashboard showing these views, people will want to see the name of the chart or dashboard, probably not the ID (since that won't mean anything to them)

**Comment by 12ian34** [comment]
> Can we please have these as analytics events as well? (i.e. they get sent to BigQuery)
> 
> Happy to open another issue for this if it's separate :)

While @rephus is away, @ZeRego - is sending more event data to bigquery a relatively trivial task that you think could be conducted as part of this issue?

> Another thing: Is there an easy way to map a chart/dashboard's UUID to the chart/dashboard's name?

Great question! We should indeed definitely show human readable names rather than UUIDs to users in their Usage Analytics, but I'm not sure where or how exactly this mapping should be performed.

**Comment by ZeRego** [comment]
> Can we please have these as analytics events as well? (i.e. they get sent to BigQuery)

We should allow the org admin to set up an analytics webbook. This way the users can connect and consume it with anything they want ( slack, warehouse, CI/CD pipeline, etc ) even if they need zapier/tray.io in the middle.

**Comment by ZeRego** [comment]
> > Another thing: Is there an easy way to map a chart/dashboard's UUID to the chart/dashboard's name?
> 
> Great question @TuringLovesDeathMetal! We should indeed definitely show human readable names rather than UUIDs to users in their Usage Analytics, but I'm not sure where or how exactly this mapping should be performed. Again, any idea @ZeRego ?

I would only keep the IDs in the analytics data to avoid PII in there. We can map the ids to the names in our server when necessary. What do you think?

**Comment by 12ian34** [comment]
> > Can we please have these as analytics events as well? (i.e. they get sent to BigQuery)
> 
> We should allow the org admin to set up an analytics webbook. This way the users can connect and consume it with anything they want ( slack, warehouse, CI/CD pipeline, etc ) even if they need zapier/tray.io in the middle.

This would be cool! I do think it could be out of scope for the first version of this work.

**Comment by 12ian34** [comment]
This issue is pending further discussion, which is all being done here: https://www.notion.so/lightdash/Usage-Analytics-e6788f72ad874b3eb7a64aec481a43b3

**Comment by 12ian34** [comment]
Closing in favour of https://github.com/lightdash/lightdash/issues/4131
