### ISSUE TITLE
Generate dbt exposures for charts and dashboards

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4062]
### Description

Add charts and dashboards as exposures in dbt lineage.
How to declare exposures: https://docs.getdbt.com/docs/build/exposures
Right now, users can write these manually but is a pain to maintain.

Once we complete the [Content as code v1]( https://github.com/lightdash/lightdash/milestone/65) milestone, we could improve the new CLI commands to also create these exposure files. 
 
We could also have a dedicated CLI command to create exposures but if the content is not as code it would constantly get out of sync. 

### What problem does this solve?

https://lightdash-community.slack.com/archives/C03MG2VTR08/p1672242961994369
> Hello! Is there an easy way to see integrated dbt lineage using Lightdash? I want to know which downstream Lightdash dashboards might break when I change an upstream dbt model.

> We'd like to have every Lightdash dashboard appear as an "exposure" in a DBT lineage graph.
Right now, new dashboards built off of a given table aren't automagically populated within the lineage graph.
We'd like to see all downstream dashboards to a given table.

**Comment by leighewarner** [comment]
We would love this feature! Hightouch has a great feature where if you build a sync, it will automatically push up to an exposures.yml file, which ensures that any new sync is auto-documented. Having the ability to have lightdash automatically push up an exposures.yml file when it detects a dashboard is ref'ing from a dbt table would be awesome. Is this something in the roadmap?

**Comment by matthewtpowers** [comment]
+1 to this feature!

**Comment by yu-iskw** [comment]
I'm for the proposed feature.

**Comment by tlfbrito** [comment]
👍
