### ISSUE TITLE
metric uniqueness and similarity

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#407]
When metrics are made in yaml for use in LightDash, at some point whether that is compile or CI, there should be a process that checks whether new metrics added to files or PRs are exactly the same in terms of SQL as other metrics:

In this case I believe they should be disallowed, with the existing metric sited.

When metrics are made in yaml for use in LightDash, at some point whether that is compile or CI, there should be a process that checks whether new metrics added to files or PRs are very similar in terms of SQL as other metrics:

In this case I believe a warning should appear so that the approvers to the PR can decide at that point whether the new metric is too similar.

**Comment by TuringLovesDeathMetal** [comment]
oooooh! Love this idea! 

@djayatillake Do you imagine this metric testing/checking happening _**across**_ models? Or just within models?

For example: if you have users that have a `user_id`, then you'll likely have `count_unique_users` in a load of models defined in exactly the same way. Unless these models have been joined together in Lightdash you'll probably want this metric to appear in all of the models where you've put it.

**Comment by djayatillake** [comment]
I think probably just within models to start with for the reasons you mentioned above. 

Interestingly between models, you would want metrics that have the same name to have very similar sql (if not the same) and vice versa, to ensure consistency.

Should we have a way to define metrics than span many models... for example if a model has user_id if we defined count_unique_users at the project level then all models which have the field user_id could have it available.

**Comment by TuringLovesDeathMetal** [comment]
> Should we have a way to define metrics than span many models...

I _love_ the idea of "project-level metrics" that you could apply to explores/models. 

I imagine you'd have this Lightdash directory where you have your saved metrics, saved charts, saved dashboards, etc. Saved metrics could be referenced in your YAML files and, on compile, Lightdash would throw an error if the fields you needed for the saved metric didn't exist in the model + joined models you've put it in.

The other thing that could fit into this "saved Lightdash" space is segments ([I thought about this a while back](https://github.com/lightdash/lightdash/issues/192)). 

For example, at Monzo, I had a Notion document where I'd written up all of the filters we had to use when selecting users for user research/surveys (e.g. doesn't have financial difficulties, is not suspected of financial crime, is a weekly active user, etc.). In Lightdash, we could have these segments saved and then reference them in models, and surface them in the UI so everyone was using the same segments for things.

**Comment by TuringLovesDeathMetal** [comment]
Sweet, I think this fits in quite well with two milestones in our roadmap:
- [You can validate Lightdash YAML](https://www.notion.so/lightdash/Product-Roadmap-49e980c97bb44aa5a78ee2618851f11f?p=eefb0935fc1a4c41b4f708956efe8eea)
- [You can save content as code](https://www.notion.so/lightdash/Product-Roadmap-49e980c97bb44aa5a78ee2618851f11f?p=7d30599d56654ecd9a0e8187634b74e3)

^I've referenced this issue in them, so when they get moved into GitHub to be specced, I'll pull out the work that we've talked about 🚀

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue - we're connecting to other semantic layers, so I think this is a functionality that should be implemented in the semantic layer (not in Lightdash)
