### ISSUE TITLE
Filter by millisecond doesn't work

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4074]
### To Reproduce

Steps & screenshot/gif/loom to reproduce the behavior
1. Go to explore
2. Add filter for timestamp
3. Select 'in the last' or 'is equals'
4. Select milliseconds as the unit of time
5. See SQL filter condition only contains time up to seconds

![Screenshot 2023-01-03 at 14 19 30](https://user-images.githubusercontent.com/9117144/210375427-d206cb5c-59e7-4166-bc78-83b11970f3b1.png)

![Screenshot 2023-01-03 at 14 20 04](https://user-images.githubusercontent.com/9117144/210375518-d91b9cc1-b4e3-490d-881f-323e2bb38f11.png)

### App Version

0.358.0

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - no one has complained about this yet 👀 we can always reopen if needed!
