### ISSUE TITLE
cli preview should clean up even if you ctrl+c in terminal instead of using [enter]

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4075]
### Description

right now preview environment is only cleaned up after hitting enter
but I unconsciously just use ctrl+c

and ended up with a bunch of preview projects

<img width="276" alt="CleanShot 2023-01-03 at 19 18 18@2x" src="https://user-images.githubusercontent.com/962095/210386677-467e2ee8-fe50-46b0-ab52-5b3cdbe42119.png">

### App Version
0.358.0

**Comment by 12ian34** [comment]
This is related to #3783, which notes the CTRL-C issue and proposes a couple of solutions

**Comment by IrakliJani** [comment]
@12ian34 right, closing this one in favour of ttps://github.com/lightdash/lightdash/issues/3733
