### ISSUE TITLE
extend dbt docs to include lightdash/standardised format metrics

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#408]
When generate docs happens with a dbt project that has metrics used in lightdash, these metrics should be put into a new section of dbt docs.

**Comment by djayatillake** [comment]
I reckon we don't need to think about this with the decision to include metrics by dbt, they will almost certainly extend docs to include this if they support metrics in core.

**Comment by TuringLovesDeathMetal** [comment]
🤞 let's hope so!
