### ISSUE TITLE
Validate dbt changes against Lightdash resources

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4090]
### Description

As a developer, I was to know if my dbt changes are going to break charts/dashboards.

This could be a CLI command that can check if all the dimensions and metrics used in the charts/dashboards are still present in the dbt project. We could start by checking only the charts and dashboards that are in YML.

### What problem does this solve?

Validate dbt changes won't break charts/dashboards.

### Acceptance criteria

[] available via CLI command
[] use it as a GitHub action to validate PR with dbt changes
[] provide a detailed list of what is broken 
[] should validate all project resources, even private ones.

### Questions

- How can dbt changes brake resources in Lightdash? is it just missing dimensions/metrics in charts/dashboards?
- Should it expose details from private resources or just generic message ?

### Example validation message

```shell


 Broken dashboards found:
       - uuid-acbd-1235 
              Dimensions not found: user_name


       Resource                                 Passing  Failing
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  charts                   03:39              6        -                                                                                         |
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  dashboards               00:23              1        1                                                                          |
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 8 failed            08:19              7        1   

```

**Comment by djayatillake** [comment]
Do you know when this will be worked on? It feels like table-stakes to use Lightdash safely in production.

**Comment by ZeRego** [comment]
We’ve started exploring the "content as code" milestone and how we’ll implement this, so it’s likely that we’ll start working on it by the end of this quarter.

**Comment by tnightengale** [comment]
> Is this issue still relevant? There have been no updates for 60 days, please close the issue or keep the conversation going!

Still relevant!

**Comment by TuringLovesDeathMetal** [comment]
closing this issue in favour of the new milestones around content validation + creating/sving content from preview environments
