### ISSUE TITLE
Support multiple active jobs for create/update projects

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4093]
question (out of the scope of this PR): do we need to convert active job to be a job queue so we can have access to completed/ongoing jobs and its results?

_Originally posted by @IrakliJani in https://github.com/lightdash/lightdash/pull/4089#discussion_r1062539934_
      

Problem:
1. At the moment if I update a project ( don't wait for update/job to finish )
2. Create a project 
3. The update job disappears so the user never knows if it succeeded or not

We should change the active job provider to support multiple active jobs. And show a toast for each active job.

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned - it hasn't had any activity in over a year and a half and no users have requested it. Can always reopen if needed!
