### ISSUE TITLE
`MONTH_NAME` and `DAY OF WEEK NAME` should be ordered sequentially instead of alphabetically

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4095]
### Description

Right now, if you order by a date which is in the time interval `MONTH_NAME`, it orders teh months alphabetically (since it's a string). 

Really, we'd want these to be ordered sequentially (i.e. January, February, March, etc.). 

One way we can do this is to use `CASE` statements in the ordering (instead of just `ORDER BY 1`). 

So something like this (if the order selected is `ascending`).

```
SELECT
month_name,
COUNT(id) AS count

FROM stg

GROUP BY 1
ORDER BY  (
  CASE 
    WHEN month_name='January' THEN 1
    WHEN month_name='February' THEN 2
    WHEN month_name='March' THEN 3
    WHEN month_name = 'April' THEN 4
    WHEN month_name = 'May' THEN 5
    WHEN month_name = 'June' THEN 6
    WHEN month_name = 'July' THEN 7
    WHEN month_name = 'August' THEN 8
    WHEN month_name = 'September' THEN 9
    WHEN month_name = 'October' THEN 10
    WHEN month_name = 'November' THEN 11
    WHEN month_name = 'December' THEN 12
  END
)
```
### Acceptance criteria

- [ ] Ordering for `month_name` and `day of week name` works sequentially instead of alphabetically
- [ ] The ordering option for `month_name` type in the toggle appears like a date (instead of a string). So, like this:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/31848148/210961814-3c524d20-de44-40d1-9182-01548a208906.png">
- [ ] We also apply this sequential instead of alphabetical filtering to `DAY_OF_WEEK`

**Comment by rephus** [comment]
Why not using `https://docs.lightdash.com/references/dimensions#numeric-options` MONTH_NUM if you're planning to sort by month ?
