### ISSUE TITLE
I want to be able to have `percentile` metrics in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4103]
### Description

I want to be able to include `percentile` metrics in Lightdash. 

Right now, the `average` metric type calculates the mean, not the median, and I have no way to look at percentiles. But, if I have data with pretty massive outliers, then I want to use median to get a more representative summary of my data. 

Median is just the 50th percentile, so really, we should be able to do all percentiles in Lightdash as metrics at the same time, then we can implement a `median` option later.

The problem with percentile calculations in SQL is that they are window functions, not functions applied on aggregates (i.e. `group by`)

In BigQuery and Snowflake, there is `PERCENTILE_CONT` (continuous percentile) and `PERCENTILE_DISC` (discrete percentile). To calculate the median of cost, the SQL would look something like this:

```
SELECT
PERCENTILE_CONT(cost, 0.5) OVER() AS median_cost

FROM table
```

If I wanted to get the median cost for each product group, the SQL would look something like this:

```
SELECT
PERCENTILE_CONT(cost, 0.5) OVER(PARTITION BY product_group) AS median_cost

FROM table
```

If I wanted to get the 75th percentile cost for each product group, the SQL would look something like this:

```
SELECT
PERCENTILE_CONT(cost, 0.75) OVER(PARTITION BY product_group) AS median_cost

FROM table
```

### Suggested approach

I suggest that we add two metric types to the yaml: median, percentile. Let's just add the percentile first, then median in another ticket. They'd look something like this:

```yaml
- name: cost
    meta:
      metrics:
        median_cost:
          type: percentile
          percentile: 50
        percentile_75_cost:
          type: percentile
          percentile: 75
```

Then, in the SQL, we would need to add a new CTE before the metrics, and it would look like this: 

```sql
WITH stg AS (
SELECT 
product_id,
PERCENTILE_CONT(cost, 0.5) OVER(PARTITION BY product_id) AS median_cost,
PERCENTILE_CONT(cost, 0.75) OVER(PARTITION BY product_id) AS percentile_75_cost,
FROM my_table
)

SELECT
product_id,
MAX(median_cost) AS median_cost,
MAX(percentile_75_cost) AS percentile_75_cost

FROM stg
GROUP BY 1
```

### Acceptance criteria

- [ ] I'm able to create a metric for `percentile` inside my .yml
- [ ] I'm able to use the percentile metric on grouped data in my results table (e.g. 75th percentile cost for each product group)

**Comment by rohan-thakur** [comment]
Thanks for creating this team! 

As the submitter of this request, I wanted to stress that a generalized `percentile` metric is as important for us as `median` - the description describes this accurately but the `percentile` bit isn't in the Acceptance Criteria so just making sure. Thanks!

**Comment by TuringLovesDeathMetal** [comment]
whoops! Thanks for spotting that @rohan-thakur 👀 

I'm actually going to make this ticket into just `percentile`, then I'll add a new ticket for `median` :) (since they're kinda separate features...so smaller PRs)

Then if we ship this first, you can just do `median` using `50th percentile` until we implement `median`

**Comment by ZeRego** [comment]
In the last example, where does the `product_id` in the partition by comes from?
What would the SQL look like if the user selects multiple dimensions?

**Comment by owlas** [comment]
The CTE above is a bigquery specific workaround because they don't actually have a `percentile` or `median` aggregate function (i.e. a function that can be used in a group by like `select class, percentile(score) from T group by 1`.

However this is available in other warehouses! 

**Snowflake**
- median: `MEDIAN(score)`
- percentile: `PERCENTILE_CONT(95) WITHIN GROUP (ORDER BY score)`

**Postgres**
- median: `PERCENTILE_CONT(50) WITHIN GROUP (ORDER BY score)`
- percentile: `PERCENTILE_CONT(95) WITHIN GROUP (ORDER BY score)`

**Bigquery**

We can use APPROX_QUANTILES but it's only approximate. I'm not sure how accurate or fast the calculation is

- median: `APPROX_QUANTILES(score, 100)[OFFSET(50)]`
- percentile: `APPROX_QUANTILES(score, 100)[OFFSET(95)]`
