### ISSUE TITLE
Github action that fails if dbt project doesn't compile correctly

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4111]
`lightdash compile` should throw an error that can be used in github actions.

It should be possible to ignore models that weren't compiled. 

Validation should check:
- SQL references are available in the dbt project
- dimensions in metric filters are available in the dbt project
- dimensions in underlying_values are available in the dbt project

**Comment by TuringLovesDeathMetal** [comment]
> tables exist in the warehouse ( I can see this result being misleading if they are using different credentials locally )

^i'd say let's ignore this one in the validation for now. it's the easiest to fix from a data point of view (just rerun my models instead of yaml changes which require me to go back to dbt, change something, push the changes, open a pr, etc.)

**Comment by ZeRego** [comment]
fyi: Updated ticket to be about setting up a github action that fails if project doesn't compile.
