### ISSUE TITLE
Adding reference line causes shift in legend

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4116]
### Description

https://www.loom.com/share/d3cd4d60e0cb458a8a211b1b93c57da1

Adding a reference line causes the legend to shift to the far left of the chart

**Comment by rephus** [comment]
I think any refresh on the chart causes this issue, so it doesn't seem related with reference lines. 

[Screencast from 10-01-23 09:52:05.webm](https://user-images.githubusercontent.com/1983672/211505315-d92aeef1-1afd-466b-b2bd-582cb28a29b9.webm)
