### ISSUE TITLE
ability to export csv without limits from the chart

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4136]
### Description
right now there is no way to export a table as csv without limits from the dashboard (nor from explore)

from dashboard
![CleanShot 2023-01-10 at 20 40 16@2x](https://user-images.githubusercontent.com/962095/211610383-ccb80df3-244a-4194-9cb4-2bbce0516f3f.png)

from explore
<img width="1105" alt="CleanShot 2023-01-10 at 20 41 12@2x" src="https://user-images.githubusercontent.com/962095/211610637-df9549a5-9772-4272-b311-2a341c0a83bd.png">

but there is an option to do that from the results table
![CleanShot 2023-01-10 at 20 41 46@2x](https://user-images.githubusercontent.com/962095/211610738-c9b1c510-9d43-430f-aa58-0bcde1b37391.png)

**Comment by PriPatel** [comment]
@IrakliJani Could we put all the content from the results table popover into a modal and then trigger that modal for all 3 places mentioned above?

**Comment by IrakliJani** [comment]
@PriPatel yes! That's what I had in mind
