### ISSUE TITLE
Ui bug - The 'is between' field does not align with other date filter fields

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4147]
**Is between:** 
<img width="970" alt="Screenshot 2023-01-09 at 11 48 19" src="https://user-images.githubusercontent.com/12776522/211811961-76db8bbc-4325-4fae-ba7a-e8260b70cb97.png">

**All other filter types:**
<img width="1027" alt="Screenshot 2023-01-09 at 11 48 15" src="https://user-images.githubusercontent.com/12776522/211811966-847c251d-b8ae-4035-b961-69b14cdc7a28.png">

When you switch between any filter type and `is between`, the width of the field varies and 'jumps around'.

The width of the field input should be the same and it should be in the same position, regardless of the filter chosen. 

CC @IrakliJani and @yasmin-e !

**Comment by IrakliJani** [comment]
@PriPatel @yasmin-e I can take this and see if I can fix
