### ISSUE TITLE
Loading spinners on tiles should be responsive

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4171]
<img width="616" alt="Screenshot 2023-01-16 at 12 22 23" src="https://user-images.githubusercontent.com/12776522/212676665-4cd726ae-d11a-4db2-9b5f-8905e2b857a5.png">

1. We could rid of `Loading Chart` as that feels a bit redundant being displayed on every single tile/
2. When the dashboard tile is at a certain width, the spinner becomes smaller (the size needs to be defined)

**Comment by anjola-adeuyi** [comment]
Hi @PriPatel @owlas Please, I have been working on addressing these [issues](https://github.com/lightdash/lightdash/issues/4171) above, but encountered some difficulties in understanding and reproducing one of them.

The first issue I was able to understand and fix was "We could rid of 'Loading Chart' as that feels a bit redundant being displayed on every single tile". I was able to understand the problem and provide a solution that removed the redundant "Loading Chart" message.

However, I ran into some difficulties with the second issue, "At a certain width, the spinner becomes smaller (needs to be defined)". Despite my best efforts, I was unable to reproduce the issue or understand the problem being described. **I would greatly appreciate more context or guidance on what exactly this issue means and how to reproduce it.**

**Comment by PriPatel** [comment]
Thanks @anjola-adeuyi!
When the user resizes the dashboard tile to make it smaller, the [spinner](https://blueprintjs.com/docs/#core/components/spinner) could be responsive in size so that it doesn't get cut off.  I'm not sure how hard this is to do. 
https://www.loom.com/share/6c7e40d4e6f14b1087d2cc1e654b3570

**Comment by PriPatel** [comment]
Redundant - I don't think responsiveness is the real issue here -  I wonder if a skeleton empty state works instead.
