### ISSUE TITLE
Update the appearance of charts and dashboards in list view

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4184]
### Changes
- [ ] Introduce new icon library https://tabler-icons.io/
- [ ] Match new icons to the chart type and dashboards 
- [ ] This should affect the list items in the individual `Space` pages as well as `All charts` and `All dashboards`
- [ ] Show number of views and chart type

### Figma file
https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=8750%3A132725&t=8Of43KrBlSWImDAa-0

### Icon information
Item type | Tabler icon | Bg colour | Icon colour
-- | -- | -- | --
Dashboard | `layout-dashboard` | @green5  10% opacity | @green5
Vertical bar chart | `chart-bar` | @blue5 10% opacity | @blue5
Horizontal bar chart | ^ can we flip the above?  I’ll provide an svg if not | “ | “
Big number chart | `123` | “ | “
Area chart | `chart-area` | “ | “
Scatter chart | `chart-dots` | “ | “
Line chart | `chart-line` | “ | “
Table | `table` | “ | “
Mixed chart | `chart-area-line` | “ | “

### Notes
- The 'final' homepage redesign involves increasing the width of the content on the page. After this task, for a short time, some long chart names may be cut off. 
- There will be a short time where we have 2 icon libraries existing at the same time. After testing this out, we can open new tickets to ensure that the chart icons are consistent throughout

**Comment by owlas** [comment]
Requires:
* Get chart/dashboard to have view numbers (#4187)
* Get chart/dashboard type (needs new issue)

Use Mantine @IrakliJani?

**Comment by IrakliJani** [comment]
@owlas I don't think it's a good idea yet. even if I merge mantine today I still need to have some time to make sure we are not breaking some parts of the app in prod
