### ISSUE TITLE
filter on boolean dimension

### ISSUE THREAD

**Issue by soltanianalytics** [lightdash/lightdash#419]
I have a table with a dimension that is a boolean. I seem to be able to filter on all dimensions in this table _except_ the boolean. Is this by design? The boolean is specifically built to be filtered on...

DWH: PostgreSQL

**Comment by owlas** [comment]
Hey @soltanianalytics thanks for raising this. We've been adding filters types one by one and the boolean one seems like it got missed!

@ZeRego is updating the filtering behaviour currently to support metrics and table calculations. We'll take the opportunity to add boolean support now.

Should be fixed soon!

**Comment by soltanianalytics** [comment]
Awesome, thanks!
