### ISSUE TITLE
Add chart settings space

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#42]
If you have more than one dimension + one measure in your table, you should be able to pick which things you want to have as the x, y and series.

![image](https://user-images.githubusercontent.com/11660098/120778170-f4664a80-c51d-11eb-98c8-111b6598d51b.png)

![image](https://user-images.githubusercontent.com/11660098/120778219-fdefb280-c51d-11eb-8a9e-c3890d7a9704.png)
![image](https://user-images.githubusercontent.com/11660098/120778246-0516c080-c51e-11eb-8ff5-b699704e47a2.png)
![image](https://user-images.githubusercontent.com/11660098/120778258-0942de00-c51e-11eb-9c24-0d3e3ba2eead.png)
![image](https://user-images.githubusercontent.com/11660098/120778303-18299080-c51e-11eb-8cd9-273aa4d4e2d3.png)

**Comment by owlas** [comment]
@TuringLovesDeathMetal - this looks awesome! Definitely the right minimum config we need to make this useful.

Focussing on the mapping of columns to x/y/series on the axes:

1. For some chart types, we might actually want a metric on x rather than y (e.g. horizontal bars)
2. In the Series tab, is the idea that group by only shows as available if there's a single metric? I wonder if we should make series / y on the same tab/pane?

**Comment by TuringLovesDeathMetal** [comment]
@owlas 

1. I think that it might actually make sense to just keep x and y representing "dependent" and "independent" variables (even if x is actually on the y axis). The reason being: I feel like it would be confusing to switch between a horizontal bar chart and a vertical bar chart or a line plot or something and then have the settings tabs switch on you too. As a user, I would expect to see the x-settings always in the x tab (even if the x axis has actually become the y axis). Does that make sense?

2. Group by only shows as available if there is **more than one dimension**. If you have more than one metric and more than one dimension, you would default group **both metrics** by the second dimension. I'll add an example of this to the spec (this is something that gets confusing without visual examples 😅)

**Comment by owlas** [comment]
@TuringLovesDeathMetal sorry I meant dimensions for 2)

Makes sense thanks! I'll implement this today

**Comment by owlas** [comment]
Implemented a basic version in #75 

Created new tickets in place of this one (it's getting quite big):

* #74
* #81
* #82
* #83
* #84
