### ISSUE TITLE
Copy change - dashboard tile context menu

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4204]
Change `Replace chart` to  `Edit tile content`

<img width="148" alt="Screenshot 2023-01-18 at 09 57 09" src="https://user-images.githubusercontent.com/12776522/213140273-f2e87545-f767-4c30-be84-cb66174a2fd9.png">

**Comment by IrakliJani** [comment]
this has already been fixed here https://github.com/lightdash/lightdash/pull/4208
PR was not linked with the issue

![CleanShot 2023-01-31 at 13 29 37@2x](https://user-images.githubusercontent.com/962095/215721801-e56b2329-7f0a-4713-9774-38bdf57673cc.png)
