### ISSUE TITLE
we should collect credentials in the UI for setting up Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#421]
Right now, users have to enter their credentials for Lightdash in a not-so-nice way. 

The majority of dbt projects don't include a profiles.yml in their GitHub repo IMO. So we should optimise the UX for users that will provide profiles.yml information in the UI

**Comment by TuringLovesDeathMetal** [comment]
@owlas 
Do you think we do this for just cloud users? Or should we also implement this for 1-click-deploy to Heroku?

**Comment by owlas** [comment]
I think this should work for everybody. With the option of still providing a `profiles.yml` as code if you prefer.

**Comment by TuringLovesDeathMetal** [comment]
great have updated :)

**Comment by TuringLovesDeathMetal** [comment]
sick! Do you imagine us being able to write to their GitHub repo? 🤔 (as in, we can configure their profiles.yml file in their repo for them?)

Or will this just be stored in teh application database?

**Comment by owlas** [comment]
Yeah we'll just put together the `profiles.yml` locally rather than writing it back to their project
