### ISSUE TITLE
I want to be able to collapse groups in my Explore sidebar even if there's a field selected in them

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4210]
### Description

In the Explore sidebar, when you select a field from the toggle list, the toggle list can no longer be collapsed. This is a bit annoying if you have really wide tables with loads of dimensions. 

![image](https://user-images.githubusercontent.com/31848148/213249470-3cbd9510-4a82-4ac4-b701-2a4c5d450387.png)

Maybe we could allow them to be collapsed then add some number indicator on the collapsed list to show the number of fields used from that list?

**Comment by PriPatel** [comment]
**Suggestion!:** 

<img width="367" alt="Screenshot 2023-01-18 at 17 00 22" src="https://user-images.githubusercontent.com/12776522/213249932-f9a7d74e-93e7-4f47-a6a5-13c2c66e77f2.png">
When group is open : Week is highlighted
When group is collapsed : Created date is highlighted. When you click on it, the group expands.

If a field is selected, *something* must be highlighted, whether its the field itself, or the group that contains it.
