### ISSUE TITLE
Allow tables to be in Lightdash project but not show in explore view

### ISSUE THREAD

**Issue by XiaozhouWang85** [lightdash/lightdash#4214]
### Description

It should be possible to have tables that are available in Lightdash as part of joins to other explores but not available standalone. For example when a many to many mapping table is used to join two explores, it doesn't make sense for it to be available to explore standalone

### What problem does this solve?

Reduces the clutter when users use the explore function.

Possible implementation:
For dimensions, it is possible to add a hidden: true property
https://docs.lightdash.com/references/dimensions#dimension-configuration.

Potentially "hiding" the table would achieve this result

**Comment by TuringLovesDeathMetal** [comment]
This is supported now!

See the docs here on how to accomplish this: https://docs.lightdash.com/references/joins#hide-joined-tables
