### ISSUE TITLE
I want to be able to open `Explore from here` in a new tab

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4226]
### Description

I want to be able to click `Explore from here` and open it in a new tab. 

### What problem does this solve?

If I'm looking at a dashboard, and I want to explore a chart further, it's really annoying that I can't open the chart in a new tab (I want to keep the dashboard to keep looking at it, but want to just open the chart and dig into it somehwere else).

**Comment by ZeRego** [comment]
Note that we changed recently the link behaviour because it throws an error when the url is too long.
https://github.com/lightdash/lightdash/issues/4137
Slack thread with more details https://lightdash.slack.com/archives/C02GQKJK84Q/p1674214427930709
