### ISSUE TITLE
[CLOSE AT THE END OF MILESTONE] ability to specify user permissions on a space level

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4242]
**This ticket will be closed when the milestone is finished https://github.com/lightdash/lightdash/milestone/135**

# Main tickets

- [x] #8655
- [x] #8747
- [x] #8717
- [x] #9319
- [x] #8656
- [x] #9320
- [x] #9531

# Context 

### What tech/libraries do we use?

We use [[@casl](https://casl.js.org/v6/en/)](https://casl.js.org/v6/en/) library to handle permissions in both the frontend and the backend. 

---

### How are permissions applied to a user?

Each user has a list of “**abilities**”, aka permissions, that include an action, a subject and a set of properties that need to match.

An example of an ability where a user can manage projects that belong to the organization with the id ‘org1. 

```jsx
can('manage', 'Project', { organizationUuid: 'org1' });
```

You can see all the possible actions and subjects in `packages/common/src/authorization/types.ts`

**User permissions are accumulative!** The abilities of each role accumulate instead of overriding each other.

Users can have:

- Organization role
- Project role at user level ( per project )
- Project role at group level ( per project )

Example

- Organization role = Viewer
- Project role at user level = Editor
- Project role at group level = Viewer

```jsx
// ability from Organisation role
can('view', 'Dashboard', { organizationUuid: 'org1' });

// ability from Project role at user level
can('manage', 'Dashboard', { projectUuid: 'proj1' });

// ability from Project role at group level
can('view', 'Dashboard', { projectUuid: 'proj1' });
```

In this case, the user can manage dashboards in the project with the id ‘proj1’ and view dashboards in the organization with the id ‘org1’.

You can find the code related to “abilities” in `packages/common/src/authorization/index.ts` 

---

### How do we check a user permission?

In the frontend, the `useUser` hook provides us with the user object with all its abilities.

We apply the check:

- when loading a page/route
- when displaying the button to access the feature

Example of how to check if a user can update a project.

```jsx
const canUpdateProject = ability.can(
    'update',
    subject('Project', {
        organizationUuid: project.organizationUuid,
        projectUuid: project.projectUuid,
    }),
);
```

Same example using JSX

```jsx
<Can
    I="update"
    this={subject('Project', {
        organizationUuid: project.organizationUuid,
				projectUuid: project.projectUuid,
    })}
>
...
</Can>

```

In the backend, the express request contains the user with all its abilities. 

We check permissions only in the `service` layer!

Example 

```jsx
if (user.ability.cannot('view', subject('Dashboard', dashboard))) {
    throw new ForbiddenError();
}
```

<aside>
ℹ️ **Note that is crucial that we pass the attributes so they can match the correct abilities!**

</aside>

---

### How does space access work?

Spaces can be set to “private”, making them only available to a list of users and admins.

Since space access was not implemented with abilities 😭 , each time we interact with a resource that can be part of a space ( charts and dashboards ) we have to check if the space is private and if the user has access to it. 

In the backend, we have a util function called `hasSpaceAccess` which includes all the logic for this. 

This milestone is going to improve this as we move space access to @casl.

**Comment by etburklow** [comment]
+1 - this would be extremely helpful for my team. We have non-power users who want to create views and save for their teams to use in their own Space, but we don't want those users to be able to edit the our canonical dashboards in the full company Space.

**Comment by menno-vandebron** [comment]
for the same reasons, this would be very helpful for us as well!

**Comment by tfaber** [comment]
Defo +1 on this one

**Comment by lavanya-arulmozhi** [comment]
rooting for this feature

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C065AQZF5CG/p1704470271136919?thread_ts=1704470271.136919&cid=C065AQZF5CG

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1711366539633989?thread_ts=1711366539.633989&cid=C053ESBT36V
