### ISSUE TITLE
You should be able to get an overview of what the different org roles mean without needing to view docs

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4243]
When you're inviting new users or managing existing permissions, its hard to get a sense of what the 4 options actually mean.
<img width="733" alt="Screenshot 2023-01-24 at 13 52 50" src="https://user-images.githubusercontent.com/12776522/214260489-af331c92-56fb-4f8f-8cab-785d3183695b.png">

We should use the same dropdown we use for Space Permissions because we can then display a short description of the roles.
<img width="239" alt="Screenshot 2023-01-24 at 13 51 46" src="https://user-images.githubusercontent.com/12776522/214260483-964b99f1-d223-441a-b234-3443182113e9.png">

Short description for each: 
`Member` - `No access to projects by default. Project level permissions to be set separately`
`Viewer` - `Has view only access to all projects`
`Interactive Viewer` - `Has view access to all projects and can create new projects but cannot edit existing projects`
`Editor` - `Can create, edit and delete projects`
`Developer` - `Can create, edit and delete projects`
`Admin` - `Full access to entire project, manage all projects and user access`

**Comment by PriPatel** [comment]
Use Mantine `select` (https://mantine.dev/core/select/) with a `description`

**Comment by jayanand05** [comment]
Hi @PriPatel, I got the issue i didn't use the Mantine though check it out wdyt?

https://github.com/lightdash/lightdash/assets/113882904/31d9bd5c-7a96-42e0-b4f1-11a84312cce7

**Comment by PriPatel** [comment]
Hey @jayanand05 
Thanks for picking this up! Hmm it seems like you're on an older version? The select component should already be a mantine one.
<img width="887" alt="Screenshot 2023-06-21 at 14 22 01" src="https://github.com/lightdash/lightdash/assets/12776522/1c27988b-f106-4014-b469-5d03a6b8f3d1">

**Comment by jayanand05** [comment]
Hi @PriPatel , I updated the code and made changes request you to look at it?

https://github.com/lightdash/lightdash/assets/113882904/e7470336-b474-4eff-9406-9c2fcec5d859

**Comment by jayanand05** [comment]
Hi @PriPatel , @ZeRego does the solution provided above looks relevant with the issue mentioned or is it necessary to use mantine??

**Comment by PriPatel** [comment]
Hi @jayanand05 
Would it be possible to add a question mark icon next to each item , which when you hover over will show the tooltip with the description in it? 

We are using this pattern elsewhere, screenshot attached. (Sorry its a bit blurry. Its not live yet)
<img width="231" alt="Screenshot 2023-07-07 at 13 00 18" src="https://github.com/lightdash/lightdash/assets/12776522/e2320761-fdd6-43fa-9ab7-2330ceab9f4d">

**Comment by jayanand05** [comment]
hi @PriPatel, thanks for looking into this. Yeah I think that would be perfect, I am getting into this.
