### ISSUE TITLE
Remove references to `root_path`

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4290]
### Description

Many dbt nodes in the `manifest.json` contain a `root_path` variable that shows the root of the dbt project (`dbt_project.yml`) this has been removed in 1.4 causing errors in Lightdash.

We can get this information from knowing the location of the `dbt_project.yml` file and fixing that would support both 1.3 and 1.4.

**Comment by rephus** [comment]
Fixed in PR: https://github.com/lightdash/lightdash/pull/4319
Release: 0.398.0
