### ISSUE TITLE
Please add ability to configure logging location

### ISSUE THREAD

**Issue by spacecowboy** [lightdash/lightdash#4291]
### Description

I'm trying to deploy lightdash in kubernetes using a `readonlyfilesystem`. In this case Lightdash can't start because it can't
create the `logs` directory.

```
Error: ENOENT: no such file or directory, mkdir 'logs'
    at Object.mkdirSync (node:fs:1382:3)
    at File._createLogDirIfNotExist (/usr/app/node_modules/winston/lib/winston/transports/file.js:691:10)
    at new File (/usr/app/node_modules/winston/lib/winston/transports/file.js:92:28)
    at Object.<anonymous> (/usr/app/packages/backend/dist/logger.js:36:5)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
```

The logs are created here I think:
https://github.com/lightdash/lightdash/blob/b46be9e6bf1ed4675d0f7cb2819d92a34c4e4d2c/packages/backend/src/logger.ts#L49

which just uses the current working directory.

If lightdash accepted, for example, an environment variable with a path where it could write its logs then that would be great.

### What problem does this solve?

Would allow lightdash to run in kubernetes with tighter security. See this blog post for an example with nginx: https://www.thorsten-hans.com/read-only-filesystems-in-docker-and-kubernetes/

**Comment by spacecowboy** [comment]
go away bot

**Comment by spacecowboy** [comment]
go away bot

**Comment by owlas** [comment]
Hey @spacecowboy picking this up this week.

**Comment by owlas** [comment]
@spacecowboy are there any other logging requirements you have while we're updating this? 

Options you'll have:
- `LIGHTDASH_LOG_LEVEL` (error, warning, info, debug) - default warning
- `LIGHTDASH_LOG_FORMAT` (plain, pretty, json) - default pretty
- `LIGHTDASH_LOG_OUTPUTS` (console, file) - default console and file
- `LIGHTDASH_LOG_CONSOLE_FORMAT` (optional overrides above for console)
- `LIGHTDASH_LOG_CONSOLE_LEVEL`(optional overrides above for console)
- `LIGHTDASH_LOG_FILE_FORMAT` (optional overrides above for file)
- `LIGHTDASH_LOG_FILE_LEVEL` (optional overrides above for file)
- `LIGHTDASH_LOG_FILE_PATH` (path) - default `./logs/error.log`

**Comment by spacecowboy** [comment]
> @spacecowboy are there any other logging requirements you have while we're updating this?
> 
> Options you'll have:
> 
> * `LIGHTDASH_LOG_LEVEL` (error, warning, info, debug) - default warning
> * `LIGHTDASH_LOG_FORMAT` (plain, pretty, json) - default pretty
> * `LIGHTDASH_LOG_OUTPUTS` (console, file) - default console **and** file
> * `LIGHTDASH_LOG_CONSOLE_FORMAT` (optional overrides above for console)
> * `LIGHTDASH_LOG_CONSOLE_LEVEL`(optional overrides above for console)
> * `LIGHTDASH_LOG_FILE_FORMAT` (optional overrides above for file)
> * `LIGHTDASH_LOG_FILE_LEVEL` (optional overrides above for file)
> * `LIGHTDASH_LOG_FILE_PATH` (path) - default `./logs/error.log`

Sounds great. Thank you!
