### ISSUE TITLE
Make a `table` type visualization

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#430]
Right now, we force you to have a visual representation of your results. 

We should offer a table type visualization. That way, if you actually just want to show the numbers, then you can do this (instead of being forced to show a line graph or something)

**Comment by owlas** [comment]
@nathaliabj I think for the frontend we can just utilise the [results table component](https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/ResultsTable/ResultsTable.tsx) which might need refactoring slightly.

The logic to render a chart lives in [SimpleChart](https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/SimpleChart/index.tsx) which I think you were already working on! 

This is the first time that the chart type will render without the eCharts component. I think `SimpleChart` assumes that it's building an echarts config.


-----

On the backend: I can add a new chart type with configuration. 

@TuringLovesDeathMetal is there any specific configuration you think we need for the table type? I think we could delegate most of that to the explore view (e.g. max views, what columns are visible etc.).

**Comment by nathaliabj** [comment]
@owlas I have added a new button to select the table type within the `charts` card also added  a new `DBChartTypes` of `TABLE`, i was thinking that instead of disturbing the peace of the `SimpleCharts` component as it is something that eCharts doesnt handle. we could instead add a check within the explorer. something like.

```
 {activeVizTab === DBChartTypes.TABLE  ?  <>[Results table here]</>   :  <>[simple chart here]</>   }
 
```

What do you think ?

**Comment by owlas** [comment]
Yeah great idea @nathaliabj like a higher level component:

`LightdashVisualisation` that uses `SimpleChart` and `ResultsTable`.

The response from the API is here: https://github.com/lightdash/lightdash/blob/1d2678418ba6c0edc1de11dfa6372a9b7aacedbe/packages/common/src/index.ts#L957-L957

I imagine `LightdashVisualisation` would take this api response and render it.

One problem we have is that the `seriesLayout` is not that relevant to the table layout. I'll have a think about that

**Comment by nathaliabj** [comment]
@TuringLovesDeathMetal @owlas, Do we want a simpler version of this table? 
I mean do we want this table in the charts card to still have the functionality to drag and drop, and do table calculations? 

I feel that at this stage it should be a purely static table as all the configuration would occur on the results card ? 

What do you think ?

**Comment by owlas** [comment]
Yes @nathaliabj ! That makes perfect sense. If it's completely stateless then maybe there's nothing useful in `ResultsTable` to repurpose?

**Comment by TuringLovesDeathMetal** [comment]
@nathaliabj I'd expect it to be a fully static table when it's a chart :) 

@owlas 
> is there any specific configuration you think we need for the table type? I think we could delegate most of that to the explore view (e.g. max views, what columns are visible etc.).

I'd imagine we'll eventually want:
-  conditional formatting (e.g. I can make some cells green or red based on the values they have)
- limit to the number of rows shown in the table (that's already covered in this issue #481 )
- resizing the column width (you can turn it off, you can set the number of characters you want to fit, or you can set it to `fit values`)
- choose whether or not to show the row numbers

^All of these are nice-to-have, so I wouldn't expect them in the V1 (but not sure if thinking about these for the future will affect how you decide to build this!)

**Comment by ZeRego** [comment]
When grouping by dimension should it look something like this ? 
![Screenshot 2022-01-26 at 16 41 14](https://user-images.githubusercontent.com/9117144/151207072-e6a58705-7a44-47fc-baac-f239ade1d08d.png)

**Comment by TuringLovesDeathMetal** [comment]
hmmm, I think there are two ways of doing this (we should build whichever is easiest/fastest for now). 

What you've just drawn up is a pivot table (#1184 ) - which I think we're going to need to build into the results table eventually. So the options are:
1. The table looks exactly how your results table looks. So that means, for now, you can't group dimensions in a table type of visualization. (when we build pivot tables, you'll be able to see the pivots in the chart)
2. You can group dimensions and it looks exactly like what you've made above. 

If 2 is just as easy as 1, then let's build 2. If it's not, then let's build 1.
