### ISSUE TITLE
add `num_filters` to dashboard_created and updated events

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4303]
Add `num_filters` parameter to the dashboard_created and updated events. 

This should count the total number of filters at the top of the dashboard. 

For example, this dashboard would have `2` as the num filters

<img width="847" alt="image" src="https://user-images.githubusercontent.com/31848148/215119814-a72908f1-3d25-49af-80e0-5377130a959d.png">

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal the events 'dashboard.created', 'dashboard_version.created' already have a `filterCount`.

**Comment by TuringLovesDeathMetal** [comment]
oh sweet! I didn't see that!
