### ISSUE TITLE
When `Edit tile content` in markdown tiles, the cursor affects what is beneath the tile

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4312]
### Description

Minor bug: when editing a Markdown tile ("Edit tile content" screen). The cursor affects what is underneath the screen. E.g. when I click and drag to select a portion of text, the tile underneath the window is moved. 

The cursor shouldn't be able to interact with things behind the markdown tile edit modal. 

https://www.loom.com/share/6846c3abca9d41cd85e6d05de0cc0cfd

**Comment by hamzahc1** [comment]
Also when trying to higlight text in a  markdown tile, it instead moves the tile on the dashboard  - reported by a community member

https://www.loom.com/share/7c438971636647fc98f689a0d03635c4
