### ISSUE TITLE
When I edit a table calculation, the fieeld is remove from the table config, along with all the customization (color, labels..)

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4313]
### Description

[Screencast from 30-01-23 09:41:34.webm](https://user-images.githubusercontent.com/1983672/215431806-b5d41179-c91b-4946-8965-db2d551adf87.webm)

### App Version

v0.395.1 @ eu1

**Comment by TuringLovesDeathMetal** [comment]
ya, this one is realllllyyyy annoying 😅 I just thought it was a feature, not a bug.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/7996
