### ISSUE TITLE
I got a filter error on a dashboard : 500 WarehouseQueryError , Syntax error: Unexpected keyword AND

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4314]
### Description

I got this error, I'm not sure how that happened , and I can't replicate it now, but I'll add some debugging details here in case it happens again. 

On a dashboard, I had a few charts and a dashboard `date` filter. One of my charts was showing `no data`

![Screenshot from 2023-01-30 09-52-44](https://user-images.githubusercontent.com/1983672/215433366-0e2a77d2-3d15-428a-aaff-132613364bb9.png)

It was failing because of this error : 

```
{"status":"error",
"error":{"statusCode":500,
"name":"WarehouseQueryError",
"message":"Syntax error: Unexpected keyword AND at [7:9]",
"data":{}}}
```

The request for the chart was the following: 

```
{"dimensions":["data_timestamp_week"],"metrics":["data_sum_consumption"],
"filters":{
"dimensions":{"id":"yes",
"and":[{"id":"yes","and":[]},
{"id":"99a4099f-3193-44dd-aee5-c034668056e2",
"target":{"fieldId":"data_timestamp_day","tableName":"data"},"values":["2022-08-15"],"operator":"greaterThan"}]},
"metrics":{"id":"no","and":[{"id":"no","and":[]}]}},
"sorts":[{"fieldId":"data_timestamp_week","descending":true}],
"limit":500,
"tableCalculations":[{"name":"daily_cost_in_kwh_1","displayName":"daily cost in Kwh","sql":"- ROUND(( ((${data.sum_consumption} / 6)  ) / 1000 ) * 0.130, 2)"}],
"additionalMetrics":[]}
```

Note the `empty filter on my chart` 

The chart was running file when going into `edit chart`, but the chart was throwing the same error when going into `explore from here` 

I fixed this by:
- going into `edit chart`
- add a filter
- remove filter
- save chart

It seems there was an empty filter in the way, not sure how we got into that state. 

### App Version

v0.395.1 on eu1

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. Hasn't been reported again since.
