### ISSUE TITLE
Accept plurals and singulars for meta strings

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#432]
I've now seen a few errors with dbt projects where users use `model:` instead of `models:` or `tag:` instead of `tags:`

These errors are annoying as heck. It would be great if we can mitigate it by having sensible aliases in our yaml schemas.

Example:
 * `metrics` should accept `metric,measure,measures`

**Comment by TuringLovesDeathMetal** [comment]
@owlas - I remember you talking about this in a standup last week...is this done?
