### ISSUE TITLE
conditional formatting and cell hover interaction is broken

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4320]
### Description

- [ ] hover state does not exist for conditionally formatted cells
- [ ] cell active background does not reset text colour to black

https://user-images.githubusercontent.com/962095/215462920-9022b43d-f4e8-4dc5-a95f-a20c5fe884e6.mp4

**Comment by PriPatel** [comment]
**Changes to all table viz**

- [ ] Change table column header colour to `light-grey 2`
- [ ] Keep alternate row colour but `alpha 0.7`
- [ ] On hover, change cell bg to `filter: brightness(0.9)`
- [ ] On click, don't change the background colour, but keep the blue border (I think? Would be good to see how it feels if we keep the `filter: brightness(0.9)` or even change that slightly.

**Pivot tables**
- [ ] level 1 `light-grey 4`
- [ ] level 2 `light-grey 2` (the darker row)
<img width="882" alt="Screenshot 2023-01-31 at 21 02 39" src="https://user-images.githubusercontent.com/12776522/215830812-a62f6738-bd6b-47e6-95a7-e104bc28245f.png">


**View underlying data**

**Comment by hamzahc1** [comment]
What is this blocked by?

**Comment by PriPatel** [comment]
It was blocked by some design decisions, but not any more! Moving it back to 'To Do'.
