### ISSUE TITLE
Unauthenticated view for public charts

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4326]
### Description

The public chart view only shows the chart panel and doesn't have the ability to drill down / explore from here etc. This view is also used for embedding

Remove:
- Nav bar components except the logo
- Actions bar
- Filters
- Results
- Sql

Keep:
- chart panel

Add:
- Simpler title bar

This page should be accessible without being authenticated. By knowing the URL you have access to the chart and its data.

Blocked by #4055 

<img width="1685" alt="Screenshot 2023-01-30 at 15 48 18" src="https://user-images.githubusercontent.com/11660098/215524975-abe36cb9-6b05-4309-b0a0-7eed441ce6d3.png">

**Comment by ZeRego** [comment]
> An edit button if the user is logged in only

+ if user has permission to manage that chart

**Comment by TuringLovesDeathMetal** [comment]
We're closing this issue because we're tracking work in a separate milestone for embedding here: https://github.com/lightdash/lightdash/milestone/132
