### ISSUE TITLE
project settings should set "Start of week" automatically after setting up a warehouse connection

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4338]
### Description

it's very confusing right now to match Lightdash's "Start of week" configuration with Warehouse's "Start of week"  configuration

Auto option is misleading and probably should be removed.

When user sets up a project and connects to the warehouse - Lightdash should automatically get Start of week from the Warehouse configuration and insert it to project configuration settings.

If warehouse config changes regarding "Start of week" user can update the setting manually

<img width="460" alt="CleanShot 2023-01-31 at 15 03 10@2x" src="https://user-images.githubusercontent.com/962095/215743196-9dc6a70e-967e-4b7b-81f0-61c254506600.png">

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this as not planned (can reopen if someone else complains abou it!)
