### ISSUE TITLE
UI for creating a public chart link

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4340]
### Description

A button to publish a chart externally. Design is WIP.

- [ ] It's very obvious when a chart is publicly accessible
- [ ] I can publish a chart to the web and get a shareable public link
- [ ] I can revoke public access to the chart

Figma: https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=8534%3A123417&starting-point-node-id=8534%3A123417

<img width="582" alt="Screenshot 2023-01-31 at 12 46 23" src="https://user-images.githubusercontent.com/11660098/215763760-ddef05b0-1e2f-4029-99a4-eeef2a5328cc.png">

**Comment by TuringLovesDeathMetal** [comment]
CLosing this as not planned - we're working on privately embedded dashboard here: https://github.com/lightdash/lightdash/milestone/132
