### ISSUE TITLE
`configure` on table type charts in the SQL runner causes Lightdash to crash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4344]
### Description

https://www.loom.com/share/993cea321d5341bbae905579a59c0bb6

**Comment by rephus** [comment]
Sentry issue: https://lightdash.sentry.io/issues/3920833564/?referrer=issue_alert-slack

[Screencast from 07-02-23 10:39:28.webm](https://user-images.githubusercontent.com/1983672/217208022-432ef337-589d-43a3-993d-5cc1409c6009.webm)
