### ISSUE TITLE
update DBT compile from the project settings for the CLI setup

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4356]
### Description

Projects that are created using the CLI fails to run "Test & compile project" because it includes dbt compiling step.

project settings should be changed to allow updating project settings like warehouse credentials.

CTA button should say something like: "Test warehouse connection and update"

![CleanShot 2023-02-01 at 15 20 11@2x](https://user-images.githubusercontent.com/962095/216028893-09b7f90d-3012-40c3-bc15-1b171829bc45.png)

Error:
<img width="1438" alt="Screenshot 2023-02-20 at 5 39 56 PM" src="https://user-images.githubusercontent.com/9117144/220111982-e1bebb89-08da-4d6b-9bd3-a234397b26d4.png">

### App Version

v0.400.0

**Comment by owlas** [comment]
@rephus just found the adapter for the CLI project, it has logic in it and extends `DbtlocalProjectAdapter` my guess is that this adapter should actually do nothing at all? https://github.com/lightdash/lightdash/blob/bf9ec0d003e056b913091997b71f869185060dde/packages/backend/src/projectAdapters/dbtNoneCredentialsProjectAdapter.ts#L28-L28

**Comment by rephus** [comment]
> @rephus just found the adapter for the CLI project, it has logic in it and extends `DbtlocalProjectAdapter` my guess is that this adapter should actually do nothing at all?

I think you are right, when I added this `DbtNoneCredentialsProjectAdapter` I probably added some extra logic we don't need
