### ISSUE TITLE
CLI authentication code snippet in Personal access token

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#4365]
### Description
An authentication code snippet after generation a personal access token.

_Something prettier than this:_
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/7769335/216230082-e0a408f5-cc65-4cfd-8fcc-612d0ca294aa.png">

### What problem does this solve?

To make it easier to login to the CLI.

_yes, I did delete the shown token_

**Comment by Ifunanyacollins** [comment]
I'm working on this at the moment.

**Comment by Martin-Carlsson** [comment]
Thanks @Ifunanyacollins 💪
