### ISSUE TITLE
You should be able to hide dbt models in your Lightdash project

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#437]
Right now, every model in your dbt project is included as a table in yoru Lightdash instance. 

We were thinking that building exposures #202 would solve this problem (since you'd specify exposures, and just keep all models available to browse). 

But, I think it's still a good idea to be able to hide certain tables. 

It gives us a "tie-over" until exposures happen and they could still also be useful even if we have exposures (e.g. if you ahve sensitive tables in your project that you don't want to be available in Lightdash)

**Comment by hamzahc1** [comment]
Is this related to #170 or #194 ?

**Comment by TuringLovesDeathMetal** [comment]
oops, yep this is a copy of #170. I was trying to find it yesterday, but couldn't find it, so wrote it again. 

Close because it's a copy of #170
