### ISSUE TITLE
Be able to manually trigger the scheduled delivery

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4380]
### Description

Add "send now" button. 

https://miro.com/app/board/uXjVP1D_L4w=/?moveToWidget=3458764564476305389&cot=14

### What problem does this solve?

Be able to quickly get the report and test the scheduler. 

### Acceptance criteria

- [ ] there is an option to `send now` in the buttons at the bottom of hte scheduler creation
- [ ] `send now` sends the delivery to whatever destinations have been selected in step 4
- [ ] These deliveries appear in the scheduled deliveries dashboard

### Documentation

- [ ] add a section above this: https://docs.lightdash.com/guides/how-to-create-scheduled-deliveries#editing-and-deleting-your-scheduled-deliveries
- [ ] Section called: "'Send now' option for a delivery"
- [ ] Add info like: "You can test that your scheduled deliveries are working as expected or send content to users immediately using the "send now" button in your scheduled delivery setup. This will send the content you've selected to the destinations you've added immediately."

**Comment by PriPatel** [comment]
Regarding the use case we spoke about in stand up., I think seeing something like this in the modal itself when Im creating the report would be more useful as I wouldn't necessarily think to look at the 3-dots to do this _after_ I've set it up.
<img width="261" alt="Screenshot 2023-02-16 at 15 30 49" src="https://user-images.githubusercontent.com/12776522/219411447-8e95ac4a-a012-4be3-afd0-9d38ff9bd595.png">

**Comment by ZeRego** [comment]
Questions:
- would that button send it to all destinations or can the user choose?
- if this is for test purposes, should this button be in the scheduler creation/update form?
