### ISSUE TITLE
57 views, but since when?

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#4386]
### Description

It is very, very cool that Lightdash shows how many views an object has.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/7769335/217152750-248d5370-1063-42e0-83ff-dcc8409de743.png">

However, we need context. Is it 57 views since yesterday, in the last month, since it was created?

### Acceptance criteria

- [ ] view counts should display a tooltip showing views since date
- [ ]  take into consideration that view count has been started since we released the feature "view counts"

**Comment by owlas** [comment]
Great idea! Right now it means "since you created the chart OR since we implemented the feature, which ever is the more recent". 

How are you using the view counts now @Martin-Carlsson ? Is it to figure out how stale content is? maybe in that case " the last month" would be the most useful?
