### ISSUE TITLE
Getting a timeout error when exporting a large CSV data

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4390]
### Description

Cloud user getting a timeout response when exporting a large CSV data

![image](https://user-images.githubusercontent.com/962095/217217878-506ce4e0-b2cf-462a-b93b-f957a17e13d0.png)

```
<html><head>
<meta http-equiv=“content-type” content=“text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

**Comment by hamzahc1** [comment]
This might be a bigger piece of work but what if we sent the csv via email when it's ready so it doesn't block the whole app for the user? That way it could run in the background
