### ISSUE TITLE
Hide table names from chart labels

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4391]
### Description

Table names can make labels and legends confusing, even when joining other tables it might be unhelpful. There should be an option to disable the table names from the axis/tooltips/legends, as we have in the table config. 

![Captura de ecrã 2023-02-07, às 09 30 04](https://user-images.githubusercontent.com/9117144/217274531-3d5b87e5-649d-41f3-827b-e0bc52a7242b.png)

### What problem does this solve?

Table names can make labels and legends confusing.

**Comment by PriPatel** [comment]
@ZeRego Do you think these should be hidden by default?

**Comment by ZeRego** [comment]
@PriPatel I would say yes.
