### ISSUE TITLE
Key File doesn't recognise new file with same name

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4392]
### Description

The key file input only recognises the file the first time. If you select another file with the same name it will use the first file selected.

### To Reproduce

Steps & screenshot/gif/loom to reproduce the behaviour
1. Go to project settings -> bigquery warehouse
2. Click on 'browse'
3. Pick a file with name 'A' that is invalid
4. Then edit the file contents to be valid
5. Go to UI and pick the same file 'A'
6. Click on 'Test & compile'
7. See error ( because it is using the first uploaded file that is invalid )

### App Version

0.404.0

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned (has not come up in more than a year)
