### ISSUE TITLE
Explore runs query multiple times on page load

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4393]
### Description

Explore page seems to be running the same query multiple times on page load.

### To Reproduce

1. Open network tab
2. Go to saved chart
2. See 3 requests to run the query

![Captura de ecrã 2023-02-07, às 15 13 24](https://user-images.githubusercontent.com/9117144/217284615-2ded68f9-09c7-410c-9ec9-a6df4c49713c.png)

### App Version
0.404.0

**Comment by pvanderlinden** [comment]
Sometimes it even requests the query more then 3 times.

**Comment by ZeRego** [comment]
@all-contributors add @pvanderlinden for bugs
