### ISSUE TITLE
Pinned items should show whether they're available to everyone in the project or not 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#4398]
### Description

Right now if I pin a chart or dashboard that is from a private space, I can see it on my homepage, but other users might not. This is kind of cool as I can add things no one else can see and customise my home page BUT it would be helpful to have an icon or some sort of context that lets me know which items I've pinned that others may or may not have access to.

**Comment by PriPatel** [comment]
Closing as this will be covered by https://github.com/lightdash/lightdash/issues/4442 !
