### ISSUE TITLE
[Close at end of Milestone] User Comments on content

### ISSUE THREAD

**Issue by gavin-myT** [lightdash/lightdash#4399]
### Description

As a lighdash user I'd like the ability to comment on dashboards in order to keep communication about data close to it's visualisation and accelerate iteration.

### What problem does this solve?

Simpler discussion about data and visualisation

**Comment by 12ian34** [comment]
Updated title to cover both dashboards and charts and perhaps other content

**Comment by 12ian34** [comment]
We have another use case from Coalesce:
Imagine a table with some revenue info in it, have an interface for the business user such that they can add inline comments to each row in the table, just like adding another column in an excel sheet.
