### ISSUE TITLE
Add context menu to 'Table Viz'

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4401]
We've had feedback that some actions that can be carried out in the Table Viz chart config panel are not intuitive to carry out in the panel itself.
<img width="769" alt="Screenshot 2023-02-08 at 12 03 58" src="https://user-images.githubusercontent.com/12776522/217469530-9d05d656-2c6e-4133-94b5-8861681e286f.png">

- [x] Add a context menu to the columns (dropdown, rather than ellipsis)
- [ ] Add two options - `Pivot Column` and `Freeze Column`
- [ ] If column is already frozen, give the option to 'Unfreeze Column'.
- [ ] If a column has been pivoted, there should be an option to 'Remove Pivot'
- [ ] Update the Results table context menu to be a dropdown rather than ellipsis
- [ ] You shouldn't see this change reflected in dashboards.

- Open question - when you're viewing the Table Viz in a dashboard, should you be able to see these controls?
- Should we leave the controls in the panel as well for flexibility?

**Comment by IrakliJani** [comment]
"when you're viewing the Table Viz in a dashboard, should you be able to see these controls?"
I think you should only be able to see those controls in edit mode only

"Should we leave the controls in the panel as well for flexibility?"
it will be a nice addition to have those options in the menus but we should probably leave the controls in the config panel as well

**Comment by PriPatel** [comment]
Thanks @IrakliJani . I agree.
Just double checking that everything I've mentioned in the ticket is frontend stuff right? Because you're basically carrying out the same functions as the one in the panel?

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned... 

Can reopen if you think it's still relevant @PriPatel !
