### ISSUE TITLE
Some CSV files are corrupt because the data contains `,` or `;` 🐞 

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#4417]
### Description

<img width="973" alt="Screenshot 2023-02-08 at 19 47 21" src="https://user-images.githubusercontent.com/67699259/217623799-3b700ee1-1b10-4fca-8b61-4f9aab7bc214.png">

**Comment by ZeRego** [comment]
We should use a library to create the CSV in the BE that escapes the cell values.

**Comment by ZeRego** [comment]
Also happening for big numbers that have commas
![Captura de ecrã 2023-02-09, às 12 18 34](https://user-images.githubusercontent.com/9117144/217811088-bf30bf8d-fe9b-4009-b57e-60f929f44f98.png)
