### ISSUE TITLE
  Update slack blocks on scheduler to include update scheduler footer

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4419]
### Description

UPdate blocks to include a link on the footer to update the scheduler . like in design

![image](https://user-images.githubusercontent.com/1983672/217746075-11e8783f-bda1-418a-a3ca-b9a9049766a6.png)

**Comment by hamzahc1** [comment]
A couple of other things: 

- The title of the update should be the Scheduler title, not the dashboard/ chart title. (e.g. If I save the scheduler as "Daily Sales Update" - that's what should be the header in the slack message.
- Can the footer be dynamic? e.g. "This is a  _scheduled delivery_ every Monday at 9am from Lightdash" 
- The chart/dashboard title should still be included but should be below the scheduler title
- If there's no description available can we remove the "-"?

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal should we have a link to the scheduled delivery even though most users can't access it?
