### ISSUE TITLE
Empty dashboard allows to add tile in view mode

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4423]
### To Reproduce

![Captura de ecrã 2023-02-09, às 10 05 11](https://user-images.githubusercontent.com/9117144/217781784-1be3562d-0820-4a13-8870-724d262e3dc3.png)

### App Version
0.407.2

**Comment by Chrischuck** [comment]
I can take a look at this!

**Comment by Chrischuck** [comment]
I see in the dashboard header, the `AddTileButton` there also checks `userCanManageDashboard`.

Does this apply here as well?

**Comment by IrakliJani** [comment]
> I see in the dashboard header, the `AddTileButton` there also checks `userCanManageDashboard`.
> 
> Does this apply here as well?

yes, userCanManageDashboard should be checked before rendering the Add tile button
