### ISSUE TITLE
Custom filters on scheduled delivery dashboards

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4425]
### Description

When I create a scheduled delivery for a dashboard, there is an option to update the existing dashboard filters in the scheduled delivery

### Acceptance criteria

Miro sketch: https://miro.com/app/board/uXjVNUPGKr0=/?share_link_id=792869617470

- [x] There is a third tab in the scheduled delivery modal called `filters`
- [x] The filters tab includes a list of all of the existing dashboard filters
- [x] You cannot add more filters or delete filters from the dashboard, only adjust the values. 
- [x] When you click on a filter, you see the same "adjustment" modal as appears when you're in `view` mode on a dashboard
- [ ] The filters are listed using the `label` value (not the filter field value). 
- [ ] The `label` value appears when you go to edit the filter (this should also exist in view mode in a dashboard when we do this issue: #7746, so it will match `view mode` filter interaction in a dashboard once that's changed - or we can fix the component in dashboard view mode and then just reuse it here!)
- [x] Adjusting the filter has the same behaviour as adjusting saved filters in a dashboard. E.g.:
  - [x] if the filter is applied to different fields on different tiles, tehn this is still the case for the scheduled delivery
  - [x] all the filter conditions are joined using `AND` 
  - [x] You can override the operator
  - [x] you can override the value
  - [x] you CANNOT override the field that's being filtered
- [x] temporary filters that you add in `view` mode are _**not**_ included _**or**_ able to be adjusted in the scheduled delivery  (they _**have**_ to be saved filters)
- [x] If you remove a saved filter from a dashboard, then it would also get removed fromt eh scheduled delivery (even if you overrode it or something)

**Comment by TuringLovesDeathMetal** [comment]
Nice! I've added a spec for this here: https://miro.com/app/board/uXjVP1D_L4w=/?moveToWidget=3458764542491754845&cot=14

@owlas I have one question about how we would redirect people to these charts/dashboards with added filters though: https://miro.com/app/board/uXjVP1D_L4w=/?moveToWidget=3458764546051005231&cot=14

**Comment by joaoviana** [comment]
My next focus: passing the `filters` to the Scheduled Deliveries form and sending that info to the API endpoint

**Comment by joaoviana** [comment]
Done and rolled out to all users
