### ISSUE TITLE
Restrict access to certain metrics/dimensions depending on users

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4426]
### Description

Use case: I have an explore but some dimensions contain PII - some users should have access to that and others not.

Another use case: I want financial data metrics available to execs but not the rest of the org.

Depending on the user I'd like to conditionally show metrics/dimensions.

**Unknowns**

- How would we handle charts/dashboards that reference metrics/dimensions that the user cannot access?
- How would we restrict drill-down/underlying values if user can't see metrics but can access underlying data?
- Is it sufficient to restrict the tables covered in this issue #3798 rather than needing to do this for specific metrics/dimensions

**Comment by TuringLovesDeathMetal** [comment]
This issue has been resolved. See the docs here on how to implement this: https://docs.lightdash.com/references/user-attributes#column-filtering-with-required_attributes
