### ISSUE TITLE
New role: viewer unable to explore data

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4427]
### Description
Rename the existing `Viewer` role to `Interactive viewer`

Introduce a new `Viewer` role, which cannot drill/view underlying values/explore

**Unknowns** 

- Do we need to refactor API calls on dashboards / charts to not use `/runQuery` endpoint?
- Can they open unsaved explores shared with them? Or can they only view saved charts and dashboards?

### What problem does this solve?

For example, if I have a table with aggregate finance details, I don't want people being able to see the row-level information for this.

### Acceptance criteria:

- [ ] rename existing `viewer` role to `interactive viewer`
  - [ ] Update copy in App: permissions, organization allowed email domains
  - [ ] Update copy in the docs. 
- [ ] create new `viewer` role 
- [ ] Add `interactive viewer` and `viewer` roles as options in `organizations` and `project` permissions.
- [ ] the new role role is limited to the same actions as a viewer, but also:
    - [ ] Can't explore tables (either creating a new explore from the `new` tab, or open an unsaved explore shared with them)
    - [ ] Can't use the SQL runner
    - [ ] Can't use "explore from here" for a chart in a dashboard
    - [ ] Can't "explore from here" from a saved chart in view mode
    - [ ] Can't use "drill down" from a dashboard
    - [ ] Can't use "drill down" from the results table in a saved chart
    - [ ] Can't use "view underlying data" from a dashboard
    - [ ] CAn't use "view underlying data" from the results table in a saved chart
    - [ ] Can't invite other users.
    - [ ] Can't create new projects
    - [ ] can't "export to .csv" from the results table
<img width="344" alt="image" src="https://user-images.githubusercontent.com/31848148/220857536-db3b6934-797b-4bc0-8f49-113eaac1ddf3.png">

 - [ ] The header has the `new` tab removed (since none of these actions are available to this new viewer role)
<img width="432" alt="image" src="https://user-images.githubusercontent.com/31848148/220857135-03233047-e772-4722-aa39-4c8d90b6b7f8.png">

- [ ] the settings button from the tab is removed (since none of these actions are available to this new viewer role)
<img width="622" alt="image" src="https://user-images.githubusercontent.com/31848148/220857307-a9a0b7d5-e6b9-487b-8744-388f1a74a21d.png">

- [ ] Only `user settings` is visible in the settings menu. They can only access this menu by clicking on their profile image --> user settings.
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/31848148/220857422-7fb451c4-7f1e-47da-9564-fd9e4c050f30.png">

- [ ] In the `organization allowed email domains` setting, you're able to select `organization viewer`, `organization member`, `organization interactive viewer` as the default role. 
- [ ] If you select `organization member`, then the copy says `project viewer access` and the users are made to be non-interactive project viewers by default.

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal I'd add here that they should't be able to export to CSV either (or create scheduled sends!)

**Comment by TuringLovesDeathMetal** [comment]
@hamzahc1 they're already not able to create scheduled deliveries (only editors can do this :) )

But good to know on the export CSV! Javi asked about this and I said I thought they should be able to 👀 

CC: @rephus sorry, I take it back about the exporting .csv's! I hope that's okay 🤞 I totally forgot that you can `export all results` (not just the ones in the table)
