### ISSUE TITLE
Allow models not deployed to Lightdash to be used in joins

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4429]
### Description

If I try to deploy one table that's joined to 7 models, those 7 joined models aren't available in the UI.

**Comment by rephus** [comment]
Is this not how it works riight now ? 

I've only have these models on my project: `orders` and `payment` 

![image](https://user-images.githubusercontent.com/1983672/218692454-9daee9b9-9a0c-4d8e-b315-3c92347179dc.png)

When I go to explore, I only see those 2

![image](https://user-images.githubusercontent.com/1983672/218692547-7d9667a3-25a1-437c-9944-a64fe0b53c7f.png)


But I can select `customers` inside `orders` and make queries 

![image](https://user-images.githubusercontent.com/1983672/218692680-ca0af0eb-6e97-4363-b54b-11893d40c756.png)

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned. More info about tables + joins and showing them in the tables sidebar here: https://lightdash-knowledge-base.help.usepylon.com/articles/3073401434-how-do-i-hide-specific-tables
