### ISSUE TITLE
Pinning or Unpinning a chart/dashboard does not update the action menu copy

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#4433]
### Description

When pinning or unpinning a chart or dashboard, if you select the action menu again, the copy won't have updated and will be suggesting the opposite, incorrect action. 

e.g. when you've just pinned a dashbord, the action menu still has the item "Pin to homepage" instead of "Unpin from homepage". Likewise (but inverse) with unpinning. 

### To Reproduce

![Kapture 2023-02-09 at 16 31 45](https://user-images.githubusercontent.com/9979944/217877941-ef90f657-f13c-4c31-a704-7de639981ef2.gif)

### App Version

v0.407.5

**Comment by yasmin-e** [comment]
I tested this and couldn't reproduce

https://user-images.githubusercontent.com/67699259/218394026-1142c183-8761-462f-a715-1d32b4bb8e44.mov

**Comment by PriPatel** [comment]
@yasmin-e 
I think this is fine on the homepage and All Charts and All Dashboard pages.
It doesn't work on 'Space' pages. ( I think!) Maybe you can reproduce there?
