### ISSUE TITLE
remove mentions of `lightdash.yml` from the docs and codebase

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4439]
**Link to existing docs:** 
https://docs.lightdash.com/references/lightdashyaml

**Changes?**
get rid of the `lightdash.yml` file and related mentions in the doc

**Comment by jpetey75** [comment]
is this still needed @IrakliJani ?

I see it only mentioned on this page in docs https://docs.lightdash.com/self-host/customize-deployment/environment-variables

![CleanShot 2024-07-18 at 09 45 49@2x](https://github.com/user-attachments/assets/f7c97629-a6a0-4cfd-b9c0-942eeb7c08a7)

should it be removed from that page in docs?

**Comment by IrakliJani** [comment]
@jpetey75 I just checked and this actually needs a backend change. Feel free to move it to the "Selected for Development" board and assign it to me since I'm on support rota from Tuesday
