### ISSUE TITLE
Add an information icon in the Pinned panel to give the different types of users more context

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4444]
<img width="613" alt="Screenshot 2023-02-10 at 18 41 06" src="https://user-images.githubusercontent.com/12776522/218118501-c818689d-cdcd-4e2a-b678-41503b3f25a6.png">

- [x] **General information icon (for admins/editors)**
`Pin Spaces, Dashboards and Charts to the top of the homepage to guide your business users to the right content.`

- [x] **General information icon (for viewers)**
`Your data team have pinned these items to help guide you towards the most relevant content!`

- [x] Use Tabler Icon `question-circle`

- [x] Change `Pinned` to `Pinned for you` for users that don't have ability to pin. (viewers)

**Comment by Ifunanyacollins** [comment]
Hi @PriPatel, is anyone working on this at the moment?

**Comment by yasmin-e** [comment]
> Hi @PriPatel, is anyone working on this at the moment?

Hi @Ifunanyacollins, yes the team is working on it atm! 🚀
