### ISSUE TITLE
Custom metrics are automatically selected on Big number chart

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#4449]
### Description
Any custom metrics added to the side bar are listed in the available fields for a big number chart even if I haven’t selected them. This isn’t the case for other charts.
![image](https://user-images.githubusercontent.com/67699259/218446212-bb714f60-3ea3-4e42-bd59-e64df3a943c0.png)

**Comment by karan0handa** [comment]
This seems to happen on all charts. Code (TOGGLE_METRIC) also confirms this (`ExplorerProvider:1047`).
```typescript
    const addAdditionalMetric = useCallback(
        (additionalMetric: AdditionalMetric) => {
            dispatch({
                type: ActionType.ADD_ADDITIONAL_METRIC,
                payload: additionalMetric,
            });
            dispatch({
                type: ActionType.TOGGLE_METRIC,
                payload: getFieldId(additionalMetric),
            });
        },
        [],
    );
```
Seems like it was built according to spec: https://github.com/lightdash/lightdash/pull/1788, https://github.com/lightdash/lightdash/issues/1758

**Comment by TuringLovesDeathMetal** [comment]
This seems to no longer be an issue - will reopen if needed!
