### ISSUE TITLE
I want to be able to have my results included in a scheduled delivery.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4452]
### Description

I want to be able to include a CSV attached of the results from the chart(s) in my scheduled delivery.

### Acceptance criteria:

Miro sketch here: https://miro.com/app/board/uXjVP1D_L4w=/?moveToWidget=3458764546073253136&cot=14

- [ ] I can choose the format for my scheduled delivery (either `image` or `CSV`). This option is available in both Slack and email. 
- [ ] If I select `CSV` format, then my delivery has the results from the charts included as .csv files in my scheduled delivery as a link in my slack message or email.
- [ ] Each chart has its own .csv link attached (if sending a dashboard)
- [ ] By default, the results included in the .csv file are whatever results are shown in the chart. E.g. if I opened the chart in `view` mode, my .csv file should look like the `results` table.
- [ ] By default, the results tables are sent in the format that they appear in the results table. 
- [ ] The links expire after 24 hours. (we should include this in the messages for the scheduled delivery somewhere...)

**Comment by rephus** [comment]
is downloading all CSVs for all charts in a dashboard in scope ?

**Comment by TuringLovesDeathMetal** [comment]
Yes! sorry, I'll add that to the acceptance criteria (it's in the Miro sketch)

**Comment by TuringLovesDeathMetal** [comment]
Unless you think we should break it out into a separate task? @rephus let me know your thoughts 👀

**Comment by TuringLovesDeathMetal** [comment]
cool!

I also just realized it was already in there I think (point 2)

**Comment by TuringLovesDeathMetal** [comment]
oops, point 3:  Each chart has its own .csv file attachment (if sending a dashboard)

Is that not clear? Or should I add something else?
