### ISSUE TITLE
Require at least one scheduler destination

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4500]
> Not related with this PR, but should we allow schedulers without targets ?
> [Screencast from 16-02-23 11:30:44.webm](https://user-images.githubusercontent.com/1983672/219340567-5f14a551-6b73-424e-89cd-686b09da597e.webm)

We need to upgrade `react-hook-form` to the latest version to be able to validate arrays. 

And then we can apply the following rule and display the error.
```rules: { minLength: 1 }```

https://react-hook-form.com/api/usefieldarray

_Originally posted by @ZeRego in https://github.com/lightdash/lightdash/issues/4470#issuecomment-1433344862_

**Comment by ZeRego** [comment]
Updating the library to the latest version causes lots of our forms to error because we are not mapping correctly the input ref. So we need to change all the input components in the ReactHookForm folder.

Reference: 
https://github.com/react-hook-form/react-hook-form/issues/9398
https://github.com/react-hook-form/react-hook-form/issues/9608

Here is a WIP branch: [fix/require-scheduler-destinations](https://github.com/lightdash/lightdash/tree/fix/require-scheduler-destinations)

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned
