### ISSUE TITLE
Multiple datasets for dbt connection in bigquery

### ISSUE THREAD

**Issue by danielshipas** [lightdash/lightdash#4503]
### Description

In settings>> Organization settings >> Project Management >> Dbt connection, currently we can connect only one dataset from bigquery, my final datamart models are in multiple datasets from bigquery, and not just only one

### What problem does this solve?

To use lightdash now I need to make a single dataset only for lightdash, with multiples views, what makes the benefit of using dbt as the source for lightdash kinda useless, because I have to repeat the same table in another place.

**Comment by TuringLovesDeathMetal** [comment]
👋 hey @danielshipas 

This field in the connection form is a bit misleading. Basically, the "dataset" is the dataset value that you have in your profiles.yml file in dbt. This is the _**default**_ dataset that your models are put in, unless it's been specified in the model's config block that they're meant to be put somewhere else. You can read more about it [in our docs here.](https://docs.lightdash.com/get-started/setup-lightdash/connect-project#data-set)

So, Lightdash does work across multiple datasets. You'll just need to make sure that the service account you're using has access to all of hte datasets that you want to show in Lightdash. 

Let me know if you still have any questions!

**Comment by danielshipas** [comment]
Hello, the problem is, I have a config block in each model that overrides the default production dataset, so I can't query the datasets in these tables.
<img width="330" alt="image" src="https://user-images.githubusercontent.com/52090522/221199200-bb68f0db-b2a0-4a51-a9e3-43da26e34c7b.png">
