### ISSUE TITLE
Define custom metrics with filters in the UI

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4523]
### Description

Sometimes I want my users to have the ability to create custom metrics in the UI with filters. The current custom metrics only allow me to have simple metrics.

This saves the data team some time defining additional metrics as code.

### Acceptance criteria

Miro board with sketch: https://miro.com/app/board/uXjVPlE0Ow8=/?moveToWidget=3458764546742412818&cot=14

- [ ] When a user creates a custom metric, they are shown a modal. In this modal, you can:
    - [ ] You can update the name of a custom metric
    - [ ] You can add filters to a custom metric
- [ ] The default name for the custom metric is the same as we have now
- [ ] By default, the filters toggle is toggled closed
- [ ] The filtering options use the same filter UX/UI as the explore filter. 
- [ ] There is a toast confirmation once the user hits the 'create' CTA (in the bottom right, like when someone creates/saves a dashboard successfully)
- [ ] #5972

### Documentation

- [ ] add docs here: https://docs.lightdash.com/guides/how-to-create-metrics#adding-custom-metrics-in-the-explore-view
- [ ] add a section called `adding filters to your custom metrics` after `creating a custom metric from a dimension` and before `Custom metrics are different from the metrics defined in your YAML` 
- [ ] Let me know if you need help with creating a screenshot that shows the flow going from `create metric` --> `add filter` (I use Miro!)

### Analytics events

- [ ] add parameter to `query_executed` event which is `custom_metric_filter_count`. This counts the total number of custom metrics which have a filter included.

**Comment by PriPatel** [comment]
Option 1 makes most sense for discoverability! I would add a toast confirmation once the user hits the 'create' CTA. That's about it!

**Comment by tnightengale** [comment]
Hi, would love to this feature! Could unblock using Lightdash with a major client I working with!
