### ISSUE TITLE
Get rid of divider in side panel

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4540]
![Screenshot 2023-02-21 at 12 46 03](https://user-images.githubusercontent.com/12776522/220347802-92c82929-6efe-4c24-bd9e-9666862a3e14.png)

This should affect `Explore` mode and `Edit` mode

**Comment by PriPatel** [comment]
@IrakliJani - can I close this? :D

**Comment by IrakliJani** [comment]
not yet! but I'll link this with a PR!
