### ISSUE TITLE
Select project access when inviting a member to the organisation

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4567]
### Description

When inviting a user to the organisation, if they select the role "member" if should show extra configuration. 
The user should be able to pick what projects that user is going to have access.
eg: select `Project A` with role `Editor, select `Project B` with role `viewer` 

### What problem does this solve?

Fix the existing flow of inviting a user as a member and then go to each project settings page to give them access.

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this as not planned - we're planning to combine org + project access assignment in the near future, so this will be solved (but slightly differently to how the ticket is suggesting).
