### ISSUE TITLE
Update API to have separate endpoints for explore interactions

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4569]
### Description

Right now, the API uses a single endpoint for `run query` and this is used for all of our exploring interactions (e.g. view underlying data, drill by, explore from here)

For us to be able to implement this issue: #4427 , we need to be able to limit access to these exploring interactions, so they need to be separate endpoints. 

### Acceptance criteria

We're able to limit access to:

- [ ]  `view underlying data` from a dashboard
- [ ]  `view underlying data` from the results table in a saved chart

### Queries not affected by this: 

- [ ] `explore from here` from a tile in a dashboard -> This opens an explore page
- [ ] `explore from here` from a saved chart in view mode  -> This opens an explore page
- [ ]  explore tables (either creating a new explore from the `new` tab, or open an unsaved explore shared with them) -> This should be pointing to /runQuery 
- [ ]  using the SQL runner  -> We already have an endpoint for it
- [ ]  `drill down` from a dashboard  -> This opens an explore page
- [ ] `drill down` from the results table in a saved chart  -> This opens an explore page

So these features should be limited in the frontend

### Questions

> If these become their own endpoints, can we make the front-end events that these features normally trigger into backend events?

Yes, we should be able to add a new `underlyingData` query event on the backend.

**Comment by owlas** [comment]
To do this we need to make the following changes to roles:
- Rename the current "viewer" role to "explorer" (name tbd!)
- Introduce a new "viewer" role

Then here are the changes to the API
- Restrict `runQuery` access to the new "explorer" role only (so viewers can't use all the features listed above, which rely on this endpoint)
- Add a new endpoint that allows users to get a chart + results, without using `/runQuery` but allows using dashboard filters (I have WIP for this)

Finally changes to the UI:
- Use the new endpoint for charts in view mode
- Use the new endpoint for tiles on dashboards
- Check for permissions to conditionally hide
    - explorer / chart edit mod
    - explore from here actions
    - drill down actions
    - view underlying data actions 
    - sql runner

**Comment by TuringLovesDeathMetal** [comment]
@owlas I think a bunch of those actions are in this issue: #4427 

I was thinking that we split this out into two things:

Step 1: make changes to the endpoint
Step 2: make changes to the roles, using those endpoint changes

**Comment by owlas** [comment]
Would we include making UI changes when we update the API too? Or should we have those as a separate ticket?

**Comment by TuringLovesDeathMetal** [comment]
They are currently a separate ticket (https://github.com/lightdash/lightdash/issues/4427)

Do you think we should split this work differently @owlas ?
