### ISSUE TITLE
Regarding ontology/naming of 'dimensions'

### ISSUE THREAD

**Issue by aaronsteers** [lightdash/lightdash#457]
I wanted to propose an alternative naming for what currently are called 'dimensions' - instead calling them 'facts', 'attributes', or 'properties'.

So, on the docs page [here](https://docs.lightdash.com/guides/how-to-create-dimensions), we'd go from

> The **dimensions** you see in Lightdash are the columns that you've defined in your model's dbt YAML file. If you include descriptions for your columns, these will be pulled into Lightdash automatically!

to:

> The **attributes** you see in Lightdash are the columns that you've defined in your model's dbt YAML file. If you include descriptions for your columns, these will be pulled into Lightdash automatically!

This gives Lightdash the ability to make 'dimensions' a higher-order element with intelligence such as 'dimension_type': `time`, `enum`, `hierarchy`, `discretized`, etc.

This also keeps us out of a sticky situation where a column like `sales_revenue` is a categorized as a dimension by default. Certainly, after bucketizing, `sales_revenue` could be used as a `sales_revenue_tier` dimension, but that requires applying a certain treatment, similar to how a certain treatment or calc may be needed to applied to metrics.

Another benefit is that `day`-`month`-`quarter` - `year` can roll up to a hierarchical dimension named `time period` or similar without themselves being 'dimensions' on their own.

**Comment by owlas** [comment]
Hey @aaronsteers this is great!

> propose an alternative naming for what currently are called 'dimensions' - instead calling them 'facts', 'attributes', or 'properties'.

We've been thinking a lot how we can replace the words 'dimensions' and 'measures' with something that makes more sense. I really like `attribute`.

> ability to make 'dimensions' a higher-order element

So you would see `attributes` and `dimensions` as different? Is the idea that attributes might be transformed into dimension types?

Our philosophy is to push as much work to dbt as is sensible, so minimising the amount of transforming from columns -> dimensions inside the app (unless where really useful, like date types, but maybe creating tiers should be possible too?).

> sticky situation where a column like sales_revenue

We've actually hit this problem a couple of times now. Since every column by default becomes a dimension, it can be quite confusing in the UI (e.g. why would be grouping by sales_revenue)

**Comment by aaronsteers** [comment]
> So you would see attributes and dimensions as different? Is the idea that attributes might be transformed into dimension types?

Yes, that's what I was thinking originally but perhaps "attribute type" would be better when adding additional customizations. I like that all columns can automatically be imported as ~~dimensions~~ attributes 🙂 and it might just be more confusing to use both terms.

If we just ditched the`dimensions` term, then the ontology would be something like: all columns are `attributes` and you can customize the attribute type; `metrics` are built by defining a calculation over existing `attributes`.

I'm just riffing here, but to me this seems to be fairly intuitive. And it completely removes the awkwardness around columns like `sales_revenue` - which can comfortably _also_ be attributes, even if they are not "dimensions".

The only terms I can think that might be problematic in the future would be hierarchies like "region->division->office" and bucketized groups like "sales tier". Even for those advanced cases, I think the term `attribute hierarchies` or just `hierarchies` could be introduced in the future with no need to bring back the "dimensions" term per se.



I really appreciate this discussion and all your work on this product.

**Comment by TuringLovesDeathMetal** [comment]
I've just run into this again. 

I really like the word `properties` here - I feel like this is how I would talk about the columns in a table to a random person who's never used Looker before.
