### ISSUE TITLE
The scheduled deliveries are being sent really late (and sometimes with a broken image)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4572]
### Description

I sent a scheduled delivery via email and via Slack. There are a few things going on (so bare with me 😅 )

**First delivery:** The first time I sent it (so scheduled at 4:33PM France time - so, UTC + 1), the Slack message was sent ~7 minutes after the delivery was scheduled and it worked. The email was delivered at 8:28PM France time.

**Second delivery:** The second time I sent it (so, scheduled at 4:45 France time), the Slack message was sent at 12:35AM. The email was delivered at 8:35PM France time. 

**Both deliveries:** The first Slack message that succeeded had an image attached (yay!) but now, when I look at the Slack message, it's a broken image. I'm assuming this is because I'm looking at it > 1 hour after it was sent? 
<img width="811" alt="image" src="https://user-images.githubusercontent.com/31848148/220872888-44397b47-2055-4a8a-8b92-80bd72629e7c.png">

Both of the email deliveries don't have images in them. Again, not sure if this is because I'm looking at them > 1 hour after they were sent? 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/31848148/220872851-dec8e68f-e020-438c-a7f5-9bb15b83c88b.png">

**Comment by rephus** [comment]
Some debugging: https://lightdash.slack.com/archives/C03MCQ08UKS/p1677167586549819?thread_ts=1677080618.725139&cid=C03MCQ08UKS
