### ISSUE TITLE
Failed scheduled jobs are not retried

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4583]
### Description

I got 4 scheduled jobs (KPI dashboard) that failed with 

```
2023-02-23 15:38:04 [Lightdash] error: Unable to fetch screenshots from headless chrome connect ECONNREFUSED 10.109.3.157:80

```

But I can still see it in the DB, and it hasn't been retried . 

![image](https://user-images.githubusercontent.com/1983672/220961187-61cefa8d-8860-494d-b096-8d20962829de.png)

Is there a default locked period ?

https://github.com/graphile/worker#what-if-something-goes-wrong

**Comment by owlas** [comment]
Looks like locked period is 4 hours and it'll be unlocked as long as a worker is available to scan for locks (happens on a 8-10 min interval)

> If the worker completely dies unexpectedly (e.g. process.exit(), segfault, SIGKILL) then the jobs that that worker was executing remain locked for at least 4 hours. Every 8-10 minutes a worker will sweep for jobs that have been locked for more than 4 hours and will make them available to be processed again automatically. If you run many workers, each worker will do this, so it's likely that jobs will be released closer to the 4 hour mark. You can unlock jobs earlier than this by clearing the locked_at and locked_by columns on the relevant tables.

**Comment by rephus** [comment]
I can't replicate this locally, failed tasks are retried 

![image](https://user-images.githubusercontent.com/1983672/221157567-983ded09-fa5b-4d3d-8f3a-ba52cc2ff120.png)

**Comment by ZeRego** [comment]
We should remove the retry logic from the unfurling once this is fixed 
https://github.com/lightdash/lightdash/pull/4589#discussion_r1116658153

**Comment by ZeRego** [comment]
@owlas At the moment we have we have all jobs with only 1 attempt. Do we want to increase it to 3 and verify that the retry works ?
