### ISSUE TITLE
Replace `/runQuery` in chart "view mode"

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4591]
### Description

Blocked by #4569 

Once we have a more restricted API for viewing charts without needing `/runQuery` we need to update the current chart view mode to use APIs available only to the "viewer" role. The current component uses the `<ExploreProvider>` with a flag set to view. However this depends on many APIs that are only available to "Interactive viewer" roles.

The page should function for "viewers"

**Comment by TuringLovesDeathMetal** [comment]
I think everything else is fine for now! 

We can make changes based on feedback from users once we ship the first version :)
