### ISSUE TITLE
Maintain a job run history for scheduled deliveries

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4601]
Maintain a job run history for scheduled deliveries

This is needed to power a UI for debugging failed jobs: #4505 

We want to track events for `scheduled delivery started`, `scheduled delivery completed` and `scheduled delivery failed`

For `scheduled delivery started` we want to track:
- [ ] scheduled delivery name
- [ ] scheduled delivery ID
- [ ] scheduled delivery time of planned delivery
- [ ] number of destinations
- [ ] destination type(s)
- [ ] project ID

For `scheduled delivery completed`, this would trigger if _**all**_ destinations of a delivery were successfully delivered. we want to track:
- [ ] scheduled delivery ID
- [ ] time when delivery was successfully completed (i.e. all destinations received their deliveries)

For `scheduled delivery failed`, this would triger if _**any**_ destination for a delivery failed. We want to track:
- [ ] scheduled delivery ID
- [ ] time when delivery failed (i.e. when the _**first**_ failure for any destination happened)
- [ ] some blob of failed destinations, like this:
```
{
  "destinations": [
    {
      type: "slack"
      destination: "#general"
      status: "failed"
      completed_time: 09:00:00-2023-02-23 UTC
    },
    {
      type: "email"
      destination: "katie@lightdash.com"
      status: "success"
      completed_time: 09:00:00-2023-02-23 UTC
    }
]
}
```

**Comment by rephus** [comment]
We run each destination in its own background job, that it will run independently. So I would create  a separate entry per destination, otherwise it is going to be hard to collect and create a single entry for all destinations. What do you think @ZeRego @TuringLovesDeathMetal ?

**Comment by ZeRego** [comment]
@rephus we could track both jobs and relate them in the UI if needed. Have the main "row" show success/partial success/failure and then click to expand and see all the notification jobs info.
