### ISSUE TITLE
Styling changes to Pinned info icon

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4616]
- [ ] Move icon up by 1px
- [ ] change the colour to `gray3`

<img width="562" alt="Screenshot 2023-02-27 at 16 17 54" src="https://user-images.githubusercontent.com/12776522/221618273-e263019f-31b1-4a20-ac0b-23d142826b18.png">

**Comment by IrakliJani** [comment]
this has been fixed here https://github.com/lightdash/lightdash/pull/4586
