### ISSUE TITLE
Update appearance of Mantine empty states

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4624]
<img width="1037" alt="Screenshot 2023-02-28 at 14 18 07" src="https://user-images.githubusercontent.com/12776522/221883253-58ffeba4-c79d-4f3e-8b22-9731010e129f.png">

- Main titles should be 16px;
- Icon could should be Mantine grey4

**Comment by Chrischuck** [comment]
It looks like the main titles are already 16px.

I opened up a PR to change the color of the icon though.

**Comment by IrakliJani** [comment]
@Chrischuck linked PR will fix close this as well 👍
