### ISSUE TITLE
Export to csv for table visualization doesn't work on Explore page

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4628]
### Description

https://www.loom.com/share/9a02f704f1e14778ad59c8cb7537bb91?from_recorder=1&focus_title=1

**Comment by Chrischuck** [comment]
Looks like `projectUuid` is undefined.

I __think__ [this](https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx#L98) should be `unsavedChartVersion.projectUuid`

I am not sure the cases if/when `projectUuid` would not be undefined and which uuid should take precedence.

If I could get some potential guidance on the different states that are possible on this page, I think I could get a pr up for this. Apologies in advance, still learning the system/codebase!
