### ISSUE TITLE
When you export a table, then navigate somewhere else on the page, it's not clear that the export is still happening

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4631]
### Description

If you export a table to .csv and it takes a while, you see a little loading spinner on the `export csv` toggle menu. 

But, if you exit that toggle then re-enter it, there's no indication that there's a current export in progress.

https://www.loom.com/share/5b6852eef2214e5eb22dceebf3121de2

### What did you expect?

I'd expect that if I exit and re-enter the export csv toggle, there's some indication that an export is still happening. 

Alternatively, we could make the export action into a toast. This is what BigQuery does:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/31848148/221909475-f9c3b7fc-382f-4189-99f1-0e2b088dcd3a.png">

Then when it's exported, the toast turns to a success (like our chart success toast)
<img width="370" alt="image" src="https://user-images.githubusercontent.com/31848148/221909658-221d8aeb-3fae-4f31-8ebb-e889a71f15de.png">

**Comment by Chrischuck** [comment]
I can make a pr for this. Seems straight forward enough.

**Comment by the-watchmaker** [comment]
Data export is async. It's always nice to have a notification for that. So users can come back to complete the action. 

You can't expect a user to keep opening that dropdown to check if it's ready to download.
