### ISSUE TITLE
Show last edited + created information for saved charts and dashboards

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#465]
I want to easily be able to see when a chart/dashboard was created + who by. Also, when a chart/dashboard was last updated + who by. 

Having this context can be useful because I can quickly understand:
1. Is this a person that I trust/know that they will be building the most relevant thing? (e.g. is it someone on the data team)
2. Is this chart out of date? (has it not been updated for a considerable amount of time)
3. If I don't understand something, I know who I can message because I can see who created/last updated it. 

**user acceptance criteria:**
- there's a way to see when + who last updated a chart easily from the saved charts/dashboards space. 
- there's a way to see who created + when it was created easily from the saved charts/dashboards space. 

### Implementation

- [ ] Database: add new column to `saved_query_versions` with `created_by` and a foreign key to a user (on delete set null)
- [ ] Backend: Add new info to `SavedChart` object (last edited date and last edited by user uuid and name)
- [ ] Frontend: render new information in list view

**Comment by TuringLovesDeathMetal** [comment]
related to #1675

**Comment by owlas** [comment]
I think that looks great 👍

**Comment by owlas** [comment]
I think we should add users! It’s available in the service when the method is called so it’s easy to add.

Adding it to the database means it must be nullable, so we’ll need to show it conditionally in the UI.

There are two tables to update saved_queries for created_by and saved_query_versions for edited_by
