### ISSUE TITLE
table virtualization issues

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4652]
### Description

when you are using large screen and scroll

- [x] virtual placeholder row should not be interactive (fixed by https://github.com/lightdash/lightdash/pull/4662)
- [ ] it should set overlooking rows by screen height
- [ ] fix bug with last row (see the video above)

https://user-images.githubusercontent.com/962095/222224425-bba80c5f-6567-4830-a851-7a292b389038.mp4

**Comment by Chrischuck** [comment]
I'd love to take a peek at this, I've had to fix something similar at a previous company.

Do you have a test csv and some documentation on how to make this csv consumable by the dev app?

**Comment by Chrischuck** [comment]
@IrakliJani I was able to get 5k rows displayed but I'm having trouble reproing this issue.

**Comment by IrakliJani** [comment]
hi @Chrischuck thanks for the interest and opening a PR 🙌 

this happens when you have a lot of rows and open a website on a large screen. 

I suspect this happens because there is a configuration in our virtualizer library that we use in `packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx`

```
const rowVirtualizer = useVirtual({
    parentRef: tableContainerRef,
    size: rows.length,
    overscan: 25, <<< 👀 👀 👀 👀
});
```

see the picture below how it looks on my browser:
![CleanShot 2023-03-03 at 16 15 08@2x](https://user-images.githubusercontent.com/962095/222718857-b2898332-62d1-4339-8e40-f23034454871.png)

if you have 5k rows displayed that will be enough to reproduce the problem. I myself use the same seed data that is provided by the dev environment.

**Comment by Chrischuck** [comment]
@IrakliJani I see, Unfortunately, I only think I can fix the `virtual placeholder row should not be interactive` portion of this bug. I only have my 13in mac and no monitor to test on :(
