### ISSUE TITLE
Move the helper text for metrics and custom metrics into the popover

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4663]
### Description

Right now, if I have no metrics defined (and I don't want to include metrics in a table), the helper text for metrics takes up loads of space. 

Sometimes, I have tables joined which include dimensions that are helper dimensions, so I actually don't want to have metrics for that table. This makes the sidebar quite jammed and filled with stuff that isn't helpful to me. 

![image](https://user-images.githubusercontent.com/31848148/222675227-b56db7f6-4ecd-46d6-ab6a-585e893dba47.png)

### Acceptance criteria:

- [ ] the grey text below `metrics` and `custom metrics` is removed.
- [ ] The helper text appears in the pop-over menus (i.e. in the question mark icon) for custom metrics and metrics. (I think that custom metrics already has this? 🤔 )

**Comment by Chrischuck** [comment]
I can work on this tomorrow.

**Comment by Chrischuck** [comment]
Hi @TuringLovesDeathMetal, I made a pr to add this request. Would you be able to take a loop and my sure the copy for `metrics` is good?
