### ISSUE TITLE
When I'm in the 'All Spaces' page and I delete a space, I get redirected to the homepage

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4665]
1. Go to 'All Spaces'
2. Create a test Space to delete 
3. Delete the Space using the 3-dot context menu
4. You are redirected to the homepage and see the 'space has been deleted' success toast there

This is not expected behaviour - you should stay on the 'All Spaces' page.

**Comment by Chrischuck** [comment]
I can work on this!
