### ISSUE TITLE
Changing the default colour palette causes an error in my organization settings

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4673]
### Description

Changing teh default colour palette causes an errror in my organization settings. It says "cannot save organization settings"

https://www.loom.com/share/71838b2fa3af41aba943ac6865f577ef

**Comment by Chrischuck** [comment]
Looks like a simple type error. I can make a pr for this.

**Comment by owlas** [comment]
![Screenshot 2023-03-03 at 19 01 57](https://user-images.githubusercontent.com/11660098/222812509-eda5a44f-286c-48ca-a5d9-5dec0a3d324c.png)

API spec in `OrganizationController` is out of sync with the frontend API request
