### ISSUE TITLE
Update verify email template

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4706]
Use the new email template layout and make small changes to show the code.

Concept: https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=9635%3A129426&t=t76vsQplGFTVVdNY-0

**Comment by PriPatel** [comment]
@ZeRego I've added the template to all the emails here:
https://www.notion.so/lightdash/Email-templates-d4362e33ac46492b94375a0337a7fa85

Should make things easier
