### ISSUE TITLE
Time interval "YEAR_NUM" wrong format

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4707]
### Description

Year should be displayed as `2022` instead of `2,022` 

### To Reproduce

![Captura de ecrã 2023-03-07, às 11 46 45](https://user-images.githubusercontent.com/9117144/223413562-661aacab-147b-490e-b993-cbd8d262ce08.png)

### App Version

0.448.0

**Comment by hamzahc1** [comment]
I couldn't reproduce this with a year column from a date-time dimension 🤔

**Comment by ZeRego** [comment]
@hamzahc1 you probably used the `YEAR` time interval that returns a date. You need to use the `YEAR_NUM` time interval that returns a number. By default, we format numbers to have commas in the thousands.
