### ISSUE TITLE
Update the Settings sidebar

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4719]
### Description

Update the settings sidebar to include icons and new titles (the design uses Blueprint icons, but we should be using Tabler icons instead!)

https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=9635%3A129426&t=RnBfGn3Z53D2DlpN-0

### Acceptance criteria:

- [ ] The sidebar in the settings page is updated with the new icons and copy
- [ ] the `integrations` links to a page which has a list of integrations. So, `https://analytics.lightdash.cloud/generalSettings/slack` this link should be updated to: `https://analytics.lightdash.cloud/generalSettings/integrations/slack` For right now, clicking on `integrations` can just redirect to `https://analytics.lightdash.cloud/generalSettings/integrations/slack` (so the same page as when you click on `slack` from integrations today)

**Comment by PriPatel** [comment]
Note : the icons in that file are BP and redundant. We need the new tabler icons in there - thanks!!
