### ISSUE TITLE
Metric labels ignore special characters

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#472]
![image](https://user-images.githubusercontent.com/31848148/134680877-85c49ef4-be75-464a-80bc-1b55d07819d0.png)

^In the example above, the metric label should read `% weekly active organizations` but it's missing hte `%` symbol

**Comment by owlas** [comment]
Uh oh! @ZeRego this is because the display name is actually just derived from the unique id, which can't include special symbols.

I think we either need to:
1. Change the UI to validate that the name contains only legal characters
2. Actually include a `displayName` attribute on metrics (this would impact backend / storage)

**Comment by owlas** [comment]
@ZeRego @jaybe78 

It would actually be great to support `displayName` in the yaml for all metrics and dimensions as well as table calculations but until then for consistency I think we shouldn't allow special characters on table calculations. This is consistent with metrics and dimensions. So all names are `snake_case` 

I think the main changes we need to support that:
* Have validation in the `name` field in table calculations modal to flag any issues with special characters
* On submit: change name to `snake_case` and if it exists already, warn the user
* When loading saved table calculations in the DB, we should strip special chars

**Comment by jaybe78** [comment]
> Have validation in the name field in table calculations modal to flag any issues with special characters
https://user-images.githubusercontent.com/3605098/135856486-1b0f1e77-9cf7-4e90-983a-615e5b3dc870.mov
