### ISSUE TITLE
Email avatars should contain the Lightdash logo 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4725]
<img width="336" alt="Screenshot 2023-03-08 at 11 08 10" src="https://user-images.githubusercontent.com/12776522/223698045-9a7204f4-e186-416e-8a92-405110395838.png">

The 'anonymous' avatar feels a bit spammy. It would be nice if the avatar was a Lightdash logo!

**Comment by hamzahc1** [comment]
We'll need to implement something like this: https://www.litmus.com/blog/how-to-set-up-bimi/

**Comment by hamzahc1** [comment]
@PriPatel do we have an SVG of our logo that meets these requirements? https://bimigroup.org/creating-bimi-svg-logo-files/

**Comment by PriPatel** [comment]
Cool - This following .svg fits the 'general' conditions:
![bolt-purple](https://user-images.githubusercontent.com/12776522/224333498-28e39261-7228-4190-aa68-68ccac686cf3.svg) 

> The general rules of thumb are:
> 
> Square aspect ratio
> Solid background color
> Center your image (it may appear in a rounded frame)
> Keep it under 32 kilobytes

I would need some help updating the code bit in the file itself to match these conditions:

> The “baseProfile” attribute set to “tiny-ps”
> The “version” attribute set to “1.2”
> A <title> element must be included that reflects the company name, though there are no strict requirements for the content of the element.
> A <desc> (i.e. the “description”) element is not required, but this should be included to support accessibility.
>

**Comment by owlas** [comment]
<img width="1270" alt="Screenshot 2023-03-28 at 16 08 20" src="https://user-images.githubusercontent.com/11660098/228283027-d953dd38-ca2e-4378-a185-459eb8ea84c7.png">

Completed for:
- ✅ Google Mail
- ✅ Gravatar
- ❌ BIMI

BIMI requires making some domain changes that could affect whether emails are delivered by lightdash cloud. I'm opening a separate issue as lower priority, as the others should cover most use cases.
