### ISSUE TITLE
Time interval values in wrong order in pivot table

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4727]
### Description

When dealing with string time intervals, we should have a different order instead of A-Z.

### To Reproduce

https://user-images.githubusercontent.com/9117144/223715522-a38b599d-fc82-4801-8cb2-45b470748864.mp4

### App Version

0.448.0

**Comment by TuringLovesDeathMetal** [comment]
Kind of related to https://github.com/lightdash/lightdash/issues/4095

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this as not planned...I think we can tackle these one-by-one (like the issue linked above).
