### ISSUE TITLE
Request to move the `refresh dbt` button

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#473]
I keep hitting the `refresh dbt` button by accident (instead of `run query`). This is particularly annoying because there's no way to cancel a refresh, so I have to wait for it to finish every time I do this 😅 

This is a request to move the dbt refresh button to somewhere less accident-prone for pressing 🤞 

I don't have any suggestions yet, but I can think of some ideas if we decide this is something we want to do!

**Comment by silentninja** [comment]
I would suggest it should be under the options menu (three dots) or the settings menu, as I guess it is not something that is used often, unless you are writing yml files, which I assume is quite rare.
