### ISSUE TITLE
Error handling for disappearing table is weird

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#474]
I had an explore: `organizations_daily`

I had a chart open in Lightdash that was built on that explore. 

I added a new column to the model `organizations_daily`. 

I refreshed dbt in Lightdash. 

It threw this error: 
![image](https://user-images.githubusercontent.com/31848148/134682822-c6932c14-30e3-4404-a19c-2c79c04dd6a3.png)

This is a weird error message. The table does "exist" it just now had an error in compiling in Lightdash (because I forgot to do `dbt run` to add the new data to teh table). 

![image](https://user-images.githubusercontent.com/31848148/134682997-f22efdfd-95a2-4a30-84fc-1072c6cfabd2.png)

If this happens, I think that there should be an error that says `failed to compile organizations_daily. This sentence would be the error that's causing the failure to compile`

So, in my example, it would be:
```
Failed to compile organizations_daily. Could not automatically find type for the column organization_name. Check your warehouse for the column or add the type manually.
```

**Comment by owlas** [comment]
Thanks @TuringLovesDeathMetal - pretty uninformative error message, sorry!

What's happening in your example:
1. `organizations_daily` can't find the table in the warehouse and fails to compile 
2. This doesn't cause an error but instead makes the table unavailable
3. When the chart looks for the table it simply doesn't exist

The sidebar with the list of all explores (including ones that failed to compile e.g. `organizations_daily`) is kind of a special case, it's the only place that has an idea of "failed to compile but does technically exist" - everywhere else in the app just has no idea about `organizations_daily`

I think we can fix this by updating the `getExplore(exploreName)` function to be aware of models that fail to compile and raise a more useful error

**Comment by TuringLovesDeathMetal** [comment]
niiiice -  ya, that makes a lot of sense!

**Comment by TuringLovesDeathMetal** [comment]
closing this - no longer relevant
