### ISSUE TITLE
Scatter plot "group" feature expects at least 1 metric to work 

### ISSUE THREAD

**Issue by Robin-C** [lightdash/lightdash#4751]
### Description

I created a scatter chart and wanted to add the field "REGION" to the group so that each dot would be one of a few colors depending on the region.

When hovering above "Group", it says "You need at least one metric in your chart to add a group".

![image](https://user-images.githubusercontent.com/19736664/224384834-76d6ff0a-74d0-45c4-bda4-e91ae553932e.png)

I don't think this limitation should apply to scatter plots since we usually do not aggregate data when using the scatter plot. We usually are trying to get an idea of the correlation between 2 variables of the raw data.

### To Reproduce

Create any scatter plot with 3 dimensions (2 numerical ones and 1 actual group by dimension) and no metric.

### App Version

0.438.0

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned (solution was suggested in comments)
