### ISSUE TITLE
Typo in email scheduled delivery modal

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#4755]
### Description
Should say email rather than slack

<img width="745" alt="image (19)" src="https://user-images.githubusercontent.com/14341285/224559291-30f1b4eb-ae49-4616-a0a2-ecf3fd4319a3.png">

**Comment by mwanjajoel** [comment]
Hey, @hamzahc1 I can tackle this issue since there is no one else working on it.

**Comment by ZeRego** [comment]
This has been fixed already by https://github.com/lightdash/lightdash/pull/4753
