### ISSUE TITLE
Add a link to Register if you can't login 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#4769]
### Description

When a user hits the login page - there should be a link to register instead if they don't yet have an account: 

![Screenshot 2023-03-13 at 15 09 54](https://user-images.githubusercontent.com/14341285/224743798-5ac1da1b-c5e3-4a7e-80b6-d7f5600c009d.png)

**Comment by muhammadjufry** [comment]
Hi @hamzahc1 
Can i solve this issue?, Thanks

**Comment by hamzahc1** [comment]
@PriPatel should we just add a link underneath the modal here saying "Register or Join an existing organization" ?

**Comment by PriPatel** [comment]
Closing in favour of https://github.com/lightdash/lightdash/issues/8090
