### ISSUE TITLE
Don't allow for common email domains to be set in allowed domains

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#4770]
### Description

Users shouldn't set common email domains (e.g. gmail.com) as allowed email domains. 

Changes:
- [ ] add validation to form input
- [ ] add validation in API
- [ ] disable option to update org allowed email domains on creation  [#4718](https://github.com/lightdash/lightdash/issues/4718)

### What problem does this solve?

Less technical users allowing anyone with a popular email provider to join their organization.

**Comment by hamzahc1** [comment]
Most common to include if we want a more manageable list: 

gmail.com 
yahoo.com 
hotmail.com 
aol.com 
hotmail.co.uk 
hotmail.fr 
msn.com 
yahoo.fr 
wanadoo.fr 
orange.fr 
comcast.net 
yahoo.co.uk 
yahoo.com.br 
yahoo.co.in 
live.com 
rediffmail.com 
free.fr 
gmx.de
web.de 
yandex.ru 
outlook.com 
uol.com.br 
bol.com.br 
mail.ru 
cox.net 
hotmail.it 
sbcglobal.net 
sfr.fr 
live.fr
verizon.net 
live.co.uk 
googlemail.com 
yahoo.es 
ig.com.br 
live.nl 
bigpond.com 
terra.com.br 
yahoo.it 
yahoo.de 
rocketmail.com 
yahoo.in 
hotmail.es 
hotmail.de 
shaw.ca 
yahoo.co.jp 
sky.com 
blueyonder.co.uk

**Comment by jnfrati** [comment]
Hello there!
Let me know if I can help out with this one 🙌

**Comment by hamzahc1** [comment]
@jnfrati go for it! do you need more context on what this is doing?

**Comment by jnfrati** [comment]
Awesome!
So I have two questions around this one, the first one would be how do we want to store this list? (maybe as a hardcoded item over common?)
And the other one would be about the last item:
> disable option to update org allowed email domains on creation

The idea would be to remove directly this option when the user has a @gmail.com domain? Or we want to disable it with a tooltip saying something like "@gmail.com domains cannot enable org access"?

**Comment by ZeRego** [comment]
@jnfrati 
> how do we want to store this list? (maybe as a hardcoded item over common?)

yes, we can have a util function ( check `utils/email.ts`) that validates the email domain agains a hardcoded list.

> The idea would be to remove completely this option when the user has a @gmail.com domain? Or we want to disable it with a tooltip saying something like "@gmail.com domains cannot enable org access"?

completely remove it. The BE endpoint should also validate this.
