### ISSUE TITLE
Can't set custom value in filter when there are partial matches

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4798]
### To Reproduce

When there are no matches:
![Captura de ecrã 2023-03-14, às 16 50 37](https://user-images.githubusercontent.com/9117144/225078944-d1921543-0c11-43b5-adc5-cf70f35e4b3c.png)

When there are partial matches:
![Captura de ecrã 2023-03-14, às 16 51 13](https://user-images.githubusercontent.com/9117144/225079043-28baffd5-9413-49a2-831d-43d874fe92dc.png)

Even when there are partial matches we should have the option to add the custom value.

### App Version

0.462.0

**Comment by yasmin-e** [comment]
Resolved ✅ 
The only time you can not add a custom value is when you have an exact match
<img width="353" alt="Screenshot 2023-06-16 at 14 37 10" src="https://github.com/lightdash/lightdash/assets/67699259/e9884463-364b-4f7e-989c-4930fc739471">
<img width="334" alt="Screenshot 2023-06-16 at 14 39 49" src="https://github.com/lightdash/lightdash/assets/67699259/68367798-95e1-4a06-bf23-0c64314046d2">
<img width="333" alt="Screenshot 2023-06-16 at 14 40 33" src="https://github.com/lightdash/lightdash/assets/67699259/6a5fbbd2-c707-458f-98bb-28a1a8b0b8c2">
