### ISSUE TITLE
Long lists in scheduled dashboard csv deliveries look a bit broken

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4799]
<img width="966" alt="Screenshot 2023-03-14 at 17 04 30" src="https://user-images.githubusercontent.com/12776522/225081575-ab0cad3e-2019-491e-a0bc-9f62f66fb8bc.png">

Looks like there are too many items on the list?

**Comment by PriPatel** [comment]
<img width="1321" alt="Screenshot 2023-03-14 at 18 10 03" src="https://user-images.githubusercontent.com/12776522/225097724-93dda0ff-d544-48b3-bb4b-8626fc7fe72a.png">
I tested this using the html generator and it seems to work fine here? It feels like the container has a fixed height or something?

**Comment by rephus** [comment]
Yup, I can replicate

**Comment by rephus** [comment]
It look ok on postmark though, but it doesn't look great on my gmail 
![image](https://user-images.githubusercontent.com/1983672/231379523-0ea5ac79-b216-4999-a3bd-30b1a2e28aab.png)
