### ISSUE TITLE
"viewer" should not be able to see "add" button in space page

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4802]
### Description

"viewer" should not be able to see "add" button in space page

### To Reproduce

- change user role to "viewer"
- go to space

<img width="662" alt="CleanShot 2023-03-14 at 23 05 41@2x" src="https://user-images.githubusercontent.com/962095/225110994-0433c69e-34e6-4519-9974-8783ec85a695.png">

**Comment by jnfrati** [comment]
Hey @IrakliJani! Is it okay if I open a PR for this issue?

**Comment by IrakliJani** [comment]
@jnfrati go for it 🙌
