### ISSUE TITLE
BigNumber chart appears blank

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4805]
### Description

user reporting that bignumber chart appears blank

env: `Chrome 111 on RHEL 9.1`

![image](https://user-images.githubusercontent.com/962095/225246852-f3f2206d-50a8-4a7f-b6d3-8977fa77854e.png)

### To Reproduce

can't reproduce.

**Comment by jakubro** [comment]
@IrakliJani I can replicate it in Chrome 111 on Windows 11 too. Also, we have the same issue with unfurled links pasted in Slack.

One thing I've noticed is that the React tree of the section "Charts" is nearly empty when the value is not showing up:

![image](https://user-images.githubusercontent.com/8297230/225740749-aaab9c52-f30d-42dd-833a-5d914e81e192.png)

But when I expand the section "Results", the big value suddenly appears. The React tree then looks like this:

![image](https://user-images.githubusercontent.com/8297230/225740779-63f54f22-816f-45e3-849c-a43962566768.png)

**Comment by rephus** [comment]
Can't replicate on Linux 
![image](https://user-images.githubusercontent.com/1983672/226557401-c6830ca0-4b6e-431a-b0be-aef4b3f54f51.png)

**Comment by rephus** [comment]
I can replicate on Firefox on linux though 

[Screencast from 21-03-23 09:55:27.webm](https://user-images.githubusercontent.com/1983672/226558101-d53abd78-e541-43f1-8a59-557138a42faa.webm)
