### ISSUE TITLE
replace `verify page` blueprint components with mantine

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4814]
- ignore verify email modal

**Comment by muhammadjufry** [comment]
Hey! @IrakliJani Can i work on this issue
Thank you

**Comment by Dilli-Raj-Timalsina** [comment]
it means this is closed issue ?

**Comment by hrutik7** [comment]
hey @IrakliJani , is this issue still relevant ?

**Comment by IrakliJani** [comment]
@hrutik7 @Dilli-Raj-Timalsina this is no longer relevant
