### ISSUE TITLE
Failed to authorize user error should bring you to the login page

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#482]
<img width="562" alt="Screenshot 2021-09-27 at 10 09 28" src="https://user-images.githubusercontent.com/31848148/134869480-f09f527c-15f8-48eb-9f4f-2c0306de767f.png">

When you get a `failed to authorize user` error, you should be redirected to the login page automatically.

**Comment by ZeRego** [comment]
duplicate of https://github.com/lightdash/lightdash/issues/470

**Comment by jaybe78** [comment]
In `PrivateRoute` I can see that `health.data?.isAuthenticated` used to redirect to login page is still `true` after removing the session
