### ISSUE TITLE
UI infinite loading / flashing during register

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4824]
### Description

> Ross Housewright
I had previously had Lightdash running locally, and trying to get it started again, but running into an issue. I re-ran the install script, everything comes up fine, and I'm prompted with a "create an account" page. No matter what I fill in, the page starts continually flashing a loading modal, and I can't get past this point; in the logs, I see
2023-03-15 18:19:11 [Lightdash] error: Handled error of type ForbiddenError on [PUT] /api/v1/org Cannot register user in a new organization. Ask an existing admin for an invite link.
2023-03-15 18:19:11 [Lightdash] http: PUT /api/v1/org 403 - 9.028 ms
Any ideas of how to get out of this situation? (edited)

[slack thread](https://lightdash-community.slack.com/archives/C03MG2VTR08/p1678904433760759)  

Tech note: UI doesn't handle properly errors when creating an organisation. ( look at the logic in joinOrganisation.tsx page component )

### To Reproduce

1. allow only 1 org `ALLOW_MULTIPLE_ORGS=false` 
2. try to register new users with new orgs
3. see issue

**Comment by TuringLovesDeathMetal** [comment]
We check if there are already users in the database assuming there is also an org. We now create users without orgs so that assumption is wrong. We need to fix the logic to check how many orgs are in the database

**Comment by makesnosense** [comment]
I have somewhat similar issue (maybe I'm doing smth wrong). I'm running two containers with postgres db for lightdash and lightdash.

When I try to register the first user I cannot log in, same flashing during register  and the following error repeating:
```
[Lightdash] error: Handled error of type ForbiddenError on [PUT] /api/v1/org Cannot register user in a new organization. Ask an existing admin for an invite link.
[Lightdash] http: PUT /api/v1/org 403 - 11.288 ms
```

I've read the docs, but found no way to generate the first admin token.

**Comment by rephus** [comment]
That is the same issue @makesnosense this PR should fix it https://github.com/lightdash/lightdash/pull/4834
