### ISSUE TITLE
item description does not appear on pinned items on hover

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4831]
### Description

I should see item description when I hover over pinned items

those components are missing Tooltip on title hover:
`ResourceViewGrid[Space/Chart/Dashboard]`

https://user-images.githubusercontent.com/962095/225640711-cf30d266-e275-4d0e-9a97-5ee8aba67bce.mp4

**Comment by jnfrati** [comment]
Hello here!
@IrakliJani I was checking the code and it seems that the ResourceViewGridSpaceItem already has the tooltip implemented with the Popover component from mantine. This makes sense as it shows some extra data than just a simple text, but for the other two grid items I was thinking of implementing directly the Mantine Tooltip component. 
What do you think?

**Comment by IrakliJani** [comment]
hey @jnfrati, absolutely, I think Tooltip is the best option. I was also thinking since we already have a tooltip for view counts for chart and dashboard components we should show description tooltip not on the whole grid item component (like it does on spaces now) but on the actual title hover. lmk if you have questions 👍
