### ISSUE TITLE
resource view header actions should always align to the right

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4832]
### Description

resource view header actions should always align to the right

### To Reproduce

- go to all spaces page
- go to any space page

screenshots:

<img width="1048" alt="CleanShot 2023-03-16 at 18 01 02@2x" src="https://user-images.githubusercontent.com/962095/225641341-f0fdcb42-a842-431b-80cc-f7762b989cb9.png">
<img width="1081" alt="CleanShot 2023-03-16 at 18 01 20@2x" src="https://user-images.githubusercontent.com/962095/225641355-823ed2ea-6270-4261-bc0a-30e6d47bcfab.png">

**Comment by jnfrati** [comment]
Hello @IrakliJani!
I think I have a solution ready for this one, can I send a PR?
