### ISSUE TITLE
Better `file not found` server error 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4840]
Some people on self-hosting are complaining because they can't serve CSV/image files when running multiple pods , 

 This is a know limitation for people who are self-hosting on multiple containers (or simply trying to get a file after a server reboot), the solution is to enable cloud storage using S3 credentials.

Full  thread here: 

https://lightdash.slack.com/archives/C03MCQ08UKS/p1678975954019009

## Acceptance criteria

Maybe instead of

`no such file or directory, stat '/tmp/csv-sBTWUAj-FzXwBSbRporCo.csv'`

We show an error saying:

> This file csv-sBTWUAj-FzXwBSbRporCo.csv doesn't exist on this server, this might be happening because you are running mulitple containers or becuase files are not persisted. We suggest you check our docs to learn how to enable cloud storage: `docs.lightdash.com...`

**Comment by rephus** [comment]
@hamzahc1 this is the issue we discussed yesterday, feel free to update the message I have added. Let me know if you need extra context or more technical details.

**Comment by hamzahc1** [comment]
@rephus if this error can only appear when a user is self-hosting then I think this it's great - minor grammar and spelling tweaks:
> This file csv-sBTWUAj-FzXwBSbRporCo.csv doesn't exist on this server, this may be happening if you are running multiple containers or because files are not persisted. You can check out our docs to learn more on how to enable cloud storage: docs.lightdash.com...
