### ISSUE TITLE
Generate CSV on the background using scheduler worker

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4846]
### Description

We should be generating CSVs on the background using scheduler worker, the main advantages: 

- We can limit how many CSVs we generate at the same time, by limitting the number of workers
- we can generate this on a separate process/pod, single threaded, without affecting API 
- I can take as long as it needs, without causing timeouts in the request. 

## Acceptance criteria

- [ ] Trigger a scheduler job (now) to generate a CSV on a worker, it could be a new task, or reuse the current task to generate CSVs
- [ ] The API call just returns the Job ID 
- [ ] The CSV url will be stored in the job log table 
- [ ] Use polling on the Job ID and wait until there is a CSV link 
- [ ] Download the CSV using the link, or return an error
- [ ] Permissions: Limit the Job log endpoint  / CSV url to only these roles: TODO

**Comment by owlas** [comment]
@rephus this would be the first time we use polling with the new scheduler tables. I guess we would poll the graphile tables rather than our own solution that we're using for compiling projects?
