### ISSUE TITLE
When I'm adding a table calculation, the 'save' button in the modal should 'Run query'

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4853]
<img width="801" alt="Screenshot 2023-03-20 at 13 42 02" src="https://user-images.githubusercontent.com/12776522/226356738-8038ad30-d549-4863-8c6b-e2b5bad3050e.png">

When I currently add a table calculation, I have to hit `Save`, then `Run Query` again to apply it. It would make sense if the Save button also runs the query after? 

Related to https://github.com/lightdash/lightdash/issues/4284

**Comment by muhammadjufry** [comment]
Hi @PriPatel Can i work on this issue?
And bayon which page there are located?
Thank you

**Comment by muhammadjufry** [comment]
Done! I have create new [pr](https://github.com/lightdash/lightdash/pull/4911)

**Comment by rephus** [comment]
Fixed by https://github.com/lightdash/lightdash/pull/4922
