### ISSUE TITLE
BigNumber chart appears blank in scheduled deliveries

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4858]
### Description

BigNumber chart appears blank in scheduled deliveries

<img width="1394" alt="CleanShot 2023-03-20 at 18 27 44@2x" src="https://user-images.githubusercontent.com/962095/226370905-4a2041f7-0a82-4091-9d66-006911e2e73d.png">

**Comment by rephus** [comment]
It seems this is causing the issue https://github.com/lightdash/lightdash/issues/4805
I've tried upgrading  headless browser image, but that didn't fix it
