### ISSUE TITLE
Custom `target-dir` in `dbt_project.yml` causes error

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4873]
### Description

If I set this in my `dbt_project.yml`

```yaml
# dbt_project.yml
...
target-dir: targets # plural not singular
```

Then I get the error 

```
Cannot read response from dbt, could not read dbt artifact
```

<img width="531" alt="Screenshot 2023-03-15 at 11 05 40 AM" src="https://user-images.githubusercontent.com/11660098/226565732-e4540f78-489d-4279-8a22-e6d6cf87a2c9.png">

**Comment by TuringLovesDeathMetal** [comment]
`Closing this as not planned - hasn't been raised again in more than a year
