### ISSUE TITLE
I should be able to 'switch' which colour is used to represent an increase in Big Number comparisons

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4884]
For cases where an increase in a KPI metric is not a good thing, the user should be able to switch what 'green' represents. By default, red = bad and green = good. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12776522/226694205-b089fdb7-3f65-4d07-b455-4d4ea9e7f88f.gif)

- [ ] Add colour to the comparison number and arrow.  By default, `arrow-down = red6`  and `arrow-up = green6`
- [ ] Add a toggle in the config panel: ~~`Negative colour on increase`~~ `Flip colors`
- [ ] If the user turns the toggle on, `arrow-down = green6`  and `arrow-up = red6`
- [ ] If there is no change, the label colour remains unaffected.

**Comment by hamzahc1** [comment]
Would there also be a neutral colour for no change?

**Comment by PriPatel** [comment]
Yes, it will remain the same (neutral colour). I'll add a point to this ticket for clarity !
