### ISSUE TITLE
If you have a `group by` dimension in your plot, the groupby label is missing and the metric label is (sometimes) cropped

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#489]
![image](https://user-images.githubusercontent.com/31848148/134907413-e2ee9af9-7d87-484f-a352-771634fbf897.png)

This is a chart example where the metric name has gotten cut out of the plot. The `group by` dimension is also not even included in the plot legend 🤔 I don't know where it's gone...

This seems to be happening in charts where I have a `groupby` dimension (the metric name is adjusted to fit in charts with just one dimension)

[Here's a link to the chart](https://lightdash-analytics.lightdash.com/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/tables/organizations_daily?dimensions=organizations_daily_days_since_organization_created%2Corganizations_daily_is_latest_organization&metrics=organizations_daily_count_unique_7d_active_organization_ids%2Corganizations_daily_count_unique_organization_ids&sort=%5B%7B%22fieldId%22%3A%22organizations_daily_is_latest_organization%22%2C%22descending%22%3Atrue%7D%2C%7B%22fieldId%22%3A%22organizations_daily_days_since_organization_created%22%2C%22descending%22%3Afalse%7D%5D&filters=%5B%7B%22type%22%3A%22number%22%2C%22tableName%22%3A%22organizations_daily%22%2C%22fieldName%22%3A%22days_since_organization_created%22%2C%22operator%22%3A%22and%22%2C%22filters%22%3A%5B%7B%22operator%22%3A%22greaterThan%22%2C%22value%22%3A0%2C%22id%22%3A%22c49a2c06-b76f-46a7-b4fe-9f064bd7c5d2%22%7D%5D%7D%5D&limit=500&column_order=organizations_daily_is_latest_organization%2Corganizations_daily_days_since_organization_created%2Corganizations_daily_count_unique_7d_active_organization_ids%2Corganizations_daily_count_unique_organization_ids%2Cweekly_active_organizations&selected_table_calculations=weekly_active_organizations&table_calculations=%5B%7B%22name%22%3A%22weekly_active_organizations%22%2C%22displayName%22%3A%22%25+weekly+active+organizations%22%2C%22sql%22%3A%22%28%24%7Borganizations_daily.count_unique_7d_active_organization_ids%7D%2F%24%7Borganizations_daily.count_unique_organization_ids%7D%29+*+100%22%7D%5D) (sorry, it's in Lightdash's analytics instance)

**Comment by TuringLovesDeathMetal** [comment]
Okay, [here's an example in Jaffle shop](https://demo.lightdash.com/projects/62ead644-a616-4201-95e1-0ec424e09da1/tables/orders?dimensions=orders_status%2Corders_order_date&metrics=orders_unique_order_count%2Ccustomers_unique_customer_count&limit=500&column_order=orders_order_date%2Corders_status%2Corders_unique_order_count%2Ccustomers_unique_customer_count%2Ctest_calc_customer_count_order_count&selected_table_calculations=test_calc_customer_count_order_count&table_calculations=%5B%7B%22name%22%3A%22test_calc_customer_count_order_count%22%2C%22displayName%22%3A%22%25+test+calc+-+customer+count+%2F+order+count%22%2C%22sql%22%3A%22%24%7Bcustomers.unique_customer_count%7D%2F%24%7Borders.unique_order_count%7D%22%7D%5D). The metric isn't cropped because the name isn't long enough, but the `groupby` label is missing. 

Here's another example of the metric being cropped in a chart with a `groupby` dimension: 
![image](https://user-images.githubusercontent.com/31848148/134908144-f5736938-4cdf-46d1-94e8-a28f0bc1f73c.png)

**Comment by TuringLovesDeathMetal** [comment]
This is likely related to #541

**Comment by owlas** [comment]
Hey @TuringLovesDeathMetal what do you mean by this:

> The group by dimension is also not even included in the plot legend 🤔 I don't know where it's gone..

**Comment by TuringLovesDeathMetal** [comment]
@owlas in the first image, I'd want to know what the Yes/No is indicating. 

I think what I _**actually**_ want is to be able to rename these groups (I don't actually want the groupby column name included in the legend). 

So in the top example, I'd rename it to "Is Lightdash staff" / "Is not Lightdash staff" (for example)

**Comment by owlas** [comment]
@TuringLovesDeathMetal Shall we split this out into a separate feature request and bug:

* Bug: axis labels are cropped
* Feature request: rename series

**Comment by TuringLovesDeathMetal** [comment]
Closed because it's split out into #797 and #83
