### ISSUE TITLE
migrate `Space page - action menu` component from Blueprint to Mantine

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4898]
<img width="357" alt="CleanShot 2023-03-22 at 15 21 56@2x" src="https://user-images.githubusercontent.com/962095/226889528-31d81bb7-bd4b-416b-82e2-19cb01ca25f0.png">

ignore:
- action modals

**Comment by IrakliJani** [comment]
still relevant

**Comment by jayanand05** [comment]
hi @IrakliJani , can you explain is it just the icon that is needed to be change here or something else?

**Comment by IrakliJani** [comment]
hey @jayanand05, we are migrating UI framework from Blueprint to Mantine. both icons and menus should change. Tabler icons should be used instead of blueprint icons. and Mantine menu component should be used instead of Blueprint one. you can use this file as a reference `packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx`
