### ISSUE TITLE
Support SSO/SAML authentication and fine-grain ACL

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#49]
## Motivation
We use Google Cloud, BigQuery and dbt. We are looking for a better dbt-friendly BI tool. I love the idea of lightdash. So, if we want to practically use lightdash as a production-grade system, authentication and permission control is necessary. It would be great to support SSO/SAML authentication and fine-grain ACL.

**Comment by owlas** [comment]
Hey @yu-iskw - this is a really important feature, thanks for raising it. Straight on to the roadmap!

Currently Lightdash doesn't have the concept of a user, so the instance looks the same for anybody accessing it. When we launch users, we'll certainly include SSO/SAML

What sort of permissions were you thinking? Some resources we could restrict:
* Permissions on tables you can query
* Permissions on dimensions and metrics within tables
* Permissions on dashboards and charts created from queries

Is there something else in particular you'd need control over?

**Comment by owlas** [comment]
Hey @yu-iskw - this is definitely on the roadmap, I'll reach out so we can plan a little around your requirements. Then I can share them here.

**Comment by yu-iskw** [comment]
I think we can close the issue, as Google SSO and some are already supported.
