### ISSUE TITLE
Include row numbers in results table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#491]
When you want to quickly count something, it's really helpful having row numbers in a table. Would be great if we had row numbers in teh results table :) 

![image](https://user-images.githubusercontent.com/31848148/134914876-c9caae50-0f7d-441a-8897-5988fd988da4.png)

**Comment by PriPatel** [comment]
https://github.com/lightdash/lightdash/issues/1396#issuecomment-1043233795
