### ISSUE TITLE
Add interactive views to usage dashboard

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#4913]
Improve the analytics dashboard to include interactive viewers. Currently we count interactive and non-interactive viewers together as "viewers" on the usage dashboard

_Originally posted by @owlas in https://github.com/lightdash/lightdash/pull/4901#discussion_r1147317885_

**Comment by rephus** [comment]
Fixed here https://github.com/lightdash/lightdash/commit/a7f1c9ad6623c78a63e3020346122977d0b5bb88
