### ISSUE TITLE
Table calculation pop should more user friendly for long queries

### ISSUE THREAD

**Issue by jaybe78** [lightdash/lightdash#492]
## Context
The popup allowing to add table calculation lacks functionalities preventing a good user experience, and especially for complex functions involving many columns.
I created the below function 
```
SUM(${orders.coupon_amount} + ${orders.bank_transfer_amount} + ${orders.credit_card_amount} + ${orders.gift_card_amount}) OVER (PARTITION BY ${orders.customer_id})
```

It was annoying to not be able to make the popup bigger to see the full content.

## Goal
Make the popup resizable

**Comment by TuringLovesDeathMetal** [comment]
Making the popup resizeable might not solve this problem "fully". 

If I have a small screen and a long query, I still want to see all of my code in one screen. 

Maybe we could:
1. make the popup bigger. It would be awesome if it was like totally resizeable (like dragging the bottom corner of it and it always gets re-centered in your screen), but if it's easier you could just add a "make fullscreen" option? (maybe a `fullscreen` icon in the bottom right corner of the SQL box?)
![image](https://user-images.githubusercontent.com/31848148/136350216-70db0129-a76b-4c75-9234-6db0b05c7cd9.png)

2. make the code be "soft-wrapped" (similar to how BigQuery does this in their UI or how most people would look at code in their text editors)
![image](https://user-images.githubusercontent.com/31848148/136349886-9be74ca9-0e7d-4587-9c88-26a627abec0a.png)

**Comment by TuringLovesDeathMetal** [comment]
@owlas @ZeRego can we please add this to the UX/UI crushing 🙏
