### ISSUE TITLE
migrate `forgot password` page from Blueprint to Mantine

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4923]
### Description

migrate

<img width="658" alt="CleanShot 2023-03-27 at 15 29 33@2x" src="https://user-images.githubusercontent.com/962095/227929267-6339a920-cbf0-4d07-8cbf-0a1c321ebe9e.png">

**Comment by PriPatel** [comment]
@joaoviana In this process if its a quick one, please can you remove the monkey emoji?😅
It's soo not appropriate any more :D

**Comment by joaoviana** [comment]
> @joaoviana In this process if its a quick one, please can you remove the monkey emoji?😅 It's soo not appropriate any more :D

sure thing @PriPatel , will remove on the PR 👍
