### ISSUE TITLE
Description field for Spaces

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#4928]
### Description

Description field for Spaces

### What problem does this solve?

We are a lot of people from different departments who work on Lightdash. This means that many Spaces will be created.

It would be great to have the ability to add a few words to a Space.

**Comment by Martin-Carlsson** [comment]
Still relevant

**Comment by Martin-Carlsson** [comment]
I still think this one is important

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of #3892
