### ISSUE TITLE
you should be able to build dashboards in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#493]
### Context
What's Light _dash_ without dashboards?

Here's the proposal: https://lightdash.notion.site/Dashboards-3fca973a44344a28b677ad69505ad78c

### Outcome
We have a proposal for how we're going to build V1 of dashboards

**Comment by owlas** [comment]
## Dashboard spec v1

Depends on #547

### Backend
- [ ] Dashboard object has an id, name, dashboard spec (saved charts + layout will depend on FE library chosen)
- [ ] GET /dashboards
- [ ] GET /dashboard/{id}
- [ ] POST /dashboards
- [ ] DELETE /dashboards
- [ ] PATCH /dashboard/{id} or PUT /dashboard{id} depending if we support partial updates (easier not to?)   

### Frontend
- [ ] List all dashboards at `/dashboards`
- [ ] View dashboard at `/dashboards/{id}`
- [ ] New blank dashboards can be created
- [ ] Saved charts can be added to dashboards
- [ ] Charts are arrangeable in an editable grid: a la https://github.com/react-grid-layout/react-grid-layout
- [ ] All changes (layout and charts and dashboard title) auto save (no save button)
- [ ] Copy url of dashboard to clipboard to share

### Future
- [ ] If you edit a chart that is used by dashboards - receive a warning that updating the chart will update all dashboards
- [ ] If you click "edit chart" on a dashboard you will be redirected back to the dashboard after editing the chart (see [1])
- [ ] FE subscribes to changes on the backend via web sockets - so all clients stay in sync from auto-save (google docs style)


[1]
<img width="1059" alt="Screenshot 2021-10-05 at 14 09 58" src="https://user-images.githubusercontent.com/11660098/136029274-78be0cfa-82cd-44cb-877a-d6b6250f286b.png">

**Comment by ZeRego** [comment]
Questions I have:
- Looker caches the query results for the dashboard and refreshes each 4 hours. Or people can manually clear cache. Will we want to do that ?
- Can we use the same saved chart with slightly different chart configs ? or would the user have to duplicate the chart ?
- When viewing a dashboard will the user be able to play around with the chart configs ? or will it be a static ?
- How will they share/integrate dashboards outside of Lightdash app ? in notion, jira, a monitor in the office, etc.

**Comment by ZeRego** [comment]
@owlas 
> No - no caching, queries are executed on page load, we can do those async to make it approx the same speed as loading a single saved chart

I don't think this will scale later on. Once we have 10 people accessing the same dashboard with 10 charts, that will be 100 requests to the warehouse. 

> Dashboard will initially be static BUT the next version would allow you to edit a saved chart (taking you to the familiar view to save a chart, but then redirect you back to the dashboard on save).
 
I'm talking more about changing the chart configs rather than editing it permanently. E.g as a user viewing a dashboard I may want to disable a label or remove the group dimension. But I don't want to save those. 

> No integrations initially just through the app

I'm trying to have an ideal of our final/ideal dashboard and not on what we are going to deliver first. 
(basically what Katie said in the above comment)

More questions:

- what other types of tiles/panels do we want to support in the dashboard ? e.g. text, iframes, call to action 
- the panel has his own title or do we reuse the saved chart name ?
- what styling options will we have for the panels ? e.g I know in jira we can assign a top border colour
- different dashboard presentation modes ? e.g in jira there is awallboard mode that displays a single tile/panel for X seconds

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego @owlas @jaybe78 I've added some thoughts on the "product vision" for dashboards here. 
Sorry, it's a bit long 😅 but I tried to add as much detail as I could around "features I think will be important in the future". 

The Notion doc is public (I created a public proposals page in Notion), so anyone should be able to comment on it and see the comments on it :) 
https://lightdash.notion.site/Dashboards-3fca973a44344a28b677ad69505ad78c

^this is meant to trigger some discussion around what's feasible, what's missing and the types of technical decisions we might need to take to be able to get there.

**Comment by djayatillake** [comment]
Am I correct in thinking that the issue here is with merge conflicts etc and dealing with them? Could we handle this with folder structure in the repo and permissions. If we for example, had a folder for dashboards with a folder for each user with a file per dashboard, wouldn't this then prevent merge conflicts from happening as then, noone else can work on the same file in the repo that your dashboard code is stored in, other than you.

**Comment by TuringLovesDeathMetal** [comment]
I feel like I need to be reminded of the actual problem here 😅 

I think there are two main reasons why I want dashboards saved as version-controlled code:
1. So we can build "end-to-end" analytics packages (e.g. Hubspot --> Fivetran --> dbt --> Lightdash all in a single package)
2. So we can have critical dashboards be "better protected" (from deletion, from accidental change, etc.)

One of the things you said was:
> One of the worst things about Looker is the lack of visibility on which dashboards are using what and the fact that some dashboards are in code and some are not.

I'm just wondering: If we made it an amazing user experience to understand which dashboards are in code vs. not in code, would you be satisfied? 

Or is there some other reason for having _**all**_ dashboards being saved as code that I've missed 🤔

**Comment by djayatillake** [comment]
> > Am I correct in thinking that the issue here is with merge conflicts etc and dealing with them
> 
> Ya, I think having a gitflow approach to **saving** things is a really intense user experience for people who don't know git - this includes branching, pushing/pulling code, merge conflicts. So, you're basically limiting the users that "build" stuff to only be engineers or data people who are familiar with git.
> 
> > had a folder for dashboards with a folder for each user with a file per dashboard,
> 
> hmmm, how would you share dashboards then? 🤔 If I updated a dashboard in my folder, would you see my updates?

I guess it depends on the owner of the dashboard, you can look at other people's dashboards but if you edit and save it then it becomes yours. This way I think you can hide git from the non-technical users as all PRs will be able to be merged without conflict with guarantee. However, the dashboards still exist in code so engineers can see the whole world.

You would be able to favourite other people's dashboards, but they still own them and if they make changes you'll see them. I think you wouldn't be able to edit someone else dashboard and save without it then becoming your copy of it.

If there were some core dashboards that needed to be "blessed" then the AE/Analysts could build these and non technical users could start from them and save their own edited versions.

**Comment by TuringLovesDeathMetal** [comment]
This work got released this week! 

#310
