### ISSUE TITLE
Auto-Resize images to fit inside "Markdown Tiles"

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4947]
### Description

Images within markdown tiles sometimes require scrolling in order to view the entire image. 

Implement an auto-resize feature for images within markdown tiles that ensures images are displayed at an appropriate size to fit within the tile's dimensions without scrolling.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned - hasn't had activity in more than a year. Will reopen if necessary
