### ISSUE TITLE
Expand the number of default chart colours

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4962]
> There is duplicity in the palette where multiple categories share the same color, and having to manually change each of them anytime there are more than 9, it starts to add up fast (especially without the option to save palettes) 

If there are more than 9 series in a chart, users have to manually update the colour for separation. A possible (quick?) solution is to generate an additional 10-20 default colours until we can work on advanced colour presets and give the users more control.

**Comment by karan0handa** [comment]
@PriPatel If we're going with this change, can you send a list of the 19 colors you plan to add? This is a very easy feature to add.

Here are the original 9 - 
```typescript
export const ECHARTS_DEFAULT_COLORS = [
    '#5470c6',
    '#736bbc',
    '#fc8452',
    '#f6696e',
    '#91cc75',
    '#fac858',
    '#ee6666',
    '#73c0de',
    '#3ba272',
    '#9a60b4',
];
```
