### ISSUE TITLE
please update order_fields_by section under tables

### ISSUE THREAD

**Issue by stellar-ahmed** [lightdash/lightdash#4964]
**Link to existing docs:** 

https://docs.lightdash.com/references/tables/#order-fields-by

**Changes?**

you guys are referencing `# order_fields_by: "yml"` as a way to order the fields, however, that "yml" is not an option that is acceptable. it throws an error. please replace all references to the "yml" with "index" for `# order_fields_by: "index"` does not throw out an error and achieves what the yml ordering achieves.

**Comment by rephus** [comment]
You're right, we need to replace `yml` with `label` , these are the 2 options available: 

https://github.com/lightdash/lightdash/blob/main/packages/common/src/types/table.ts#L2

**Comment by rephus** [comment]
@all-contributors add @stellar-ahmed for bug
