### ISSUE TITLE
author gets set to null when author account is removed

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#4971]
### Description

If a team member leaves and has assets in Lightdash, currently when their account is deleted the author of the assets becomes set to null, it would be better if this was set to an admin

### To Reproduce

Create an account
Create a dashboard and save it
Delete said account
Make another account
Look at the existing dashboard's author and see that it is null null

### App Version

Whatever the current version deployed in cloud is

**Comment by owlas** [comment]
The current behaviour is intentional, unless it's breaking something for you in the UI? Otherwise I'll switch this to a feature request

**Comment by djayatillake** [comment]
That's fine, I thought about it more as a bug as I feel it shouldn't behave this way.

It doesn't break anything per say but it's weird for users to see that the author is null, as then trust in the content is reduced.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/9670 (the new issue has more detail)
