### ISSUE TITLE
Remove frontend filter logic on dashboards

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4980]
Is it in scope to clean up the existing FE logic. There is some redundant code now, like in this file: https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx#L353-L353

_Originally posted by @owlas in https://github.com/lightdash/lightdash/pull/4977#pullrequestreview-1366602796_

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned.
