### ISSUE TITLE
Full tile title is not showing on hover

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4982]
**Default state:**
<img width="264" alt="Screenshot 2023-03-31 at 14 19 37" src="https://user-images.githubusercontent.com/12776522/229130792-e2edef37-adc1-4e99-96f0-32a45d5fa512.png">

**On Hover:**
<img width="251" alt="Screenshot 2023-03-31 at 14 19 39" src="https://user-images.githubusercontent.com/12776522/229130789-d08c53d3-730f-4d4a-b17c-b01328454be9.png">
I expect to see the full title on hover.

Update : this appears to work in some places but not in others. Needs investigating!

**Comment by lokeswaran-aj** [comment]
@PriPatel I believe this issue is fixed already. 

The requirement is only to show the full title while hovering over the title, isn't it?

https://user-images.githubusercontent.com/74011196/231529505-aac8fec7-4adc-4373-a1a2-50a78a68d42e.mov

**Comment by PriPatel** [comment]
@lokeswaran-aj - Thanks for spotting it! maybe its working in some cases but not others! I'll try and replicate and share a video of it happening! Myabe its a tile width thing? Not sure.
