### ISSUE TITLE
Visual improvements to dashboard and chart headers

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4997]
<img width="578" alt="Screenshot 2023-04-03 at 16 40 43" src="https://user-images.githubusercontent.com/12776522/229558601-6ef16c5c-135f-463a-8a01-6e71e3262a12.png">

- [ ] Change the dashboard/chart name to `18px` font-size
- [ ] The `edit icon` next to the dashboard/chart name should only appear when the user is in `edit mode`
- [ ] Change the `edit icon` to the equivalent Tabler version

**Comment by lokeswaran-aj** [comment]
Hii @PriPatel I would like to work on this issue. Can you assign it to me?

**Comment by PriPatel** [comment]
@lokeswaran-aj go for it:)
