### ISSUE TITLE
Scheduled delivery with "all results" selected is not actually exporting all of the results. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5003]
### Description

Created a scheduled delivery with "all results" selected (which is  53920 rows when I run the query in BigQuery). The scheduled delivery was sent with only 3414 results. 

Here's the query I'm using: https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/saved/6564e59d-ac8e-46a2-a597-29092db9b4fd/view

<img width="477" alt="image" src="https://user-images.githubusercontent.com/31848148/229562928-15328ed7-42d0-4a56-b9d1-f27faa62433a.png">

**Comment by owlas** [comment]
Closed in #5020
