### ISSUE TITLE
Export metadata to OpenMetadata

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#5010]
### Description
[OpenMetadata](https://docs.open-metadata.org/) is an open-sourced metadata management tool. We can manage metadata ranging from data sources to dashboards. 

https://docs.open-metadata.org/connectors/dashboard

- [Domo Dashboard](https://docs.open-metadata.org/connectors/dashboard/domo-dashboard)
- [Looker](https://docs.open-metadata.org/connectors/dashboard/looker)
- [Metabase](https://docs.open-metadata.org/connectors/dashboard/metabase)
- [Mode](https://docs.open-metadata.org/connectors/dashboard/mode)
- [PowerBI](https://docs.open-metadata.org/connectors/dashboard/powerbi)
- [Quicksight](https://docs.open-metadata.org/connectors/dashboard/quicksight)
- [Redash](https://docs.open-metadata.org/connectors/dashboard/redash)
- [Superset](https://docs.open-metadata.org/connectors/dashboard/superset)
- [Tableau](https://docs.open-metadata.org/connectors/dashboard/tableau)

### What problem does this solve?
We would like to manage end-to-end metadata on OpenMetadata. So, we would like to ingest or export metadata of lightdash to OpenMetadata.

**Comment by yu-iskw** [comment]
I don't exactly know how it works, but OpenMetadata 1.2 partially supports the connector to Lightdash.

https://docs.open-metadata.org/v1.2.x/main-concepts/metadata-standard/schemas/entity/services/connections/dashboard/lightdashconnection

https://github.com/open-metadata/OpenMetadata/pull/12957

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned
