### ISSUE TITLE
Be able to create sub-spaces within spaces

### ISSUE THREAD

**Issue by XiaozhouWang85** [lightdash/lightdash#5036]
### Description

Being able to nest spaces.

### What problem does this solve?

As the amount of content in Lightdash increases, it becomes harder to keep things organised especially since each chart must be saved before adding it to a dashboard.
One solution is to allow spaces to be nested. This allows each team to have a folder and each dashboard to have a folder with all of it's charts saved inside it.

**Comment by TuringLovesDeathMetal** [comment]
@XiaozhouWang85 closing this one in favour of an older issue for this: https://github.com/lightdash/lightdash/issues/3739
