### ISSUE TITLE
Filter-only change causes unintentional chart format changes

### ISSUE THREAD

**Issue by etburklow** [lightdash/lightdash#5039]
### Description

Sometimes when updating a chart's filters, the configuration of the chart changes unintentionally. This behavior happened today in the example below, and has happened intermittently in the last couple of months. I'm not touching the chart configuration at all, but after saving the chart with the updated filters and then looking at the chart on a dashboard, I'm seeing that it changed. Frequently, it's a chart losing the element that it's "grouped" by

What the chart normally looks like:
<img width="297" alt="Screen Shot 2023-04-10 at 4 59 47 PM" src="https://user-images.githubusercontent.com/31858118/230997841-62f02672-7b08-45a6-9d13-9a247574146f.png">

What the chart looks like after saving despite only changing a filter:
<img width="635" alt="Screen Shot 2023-04-10 at 4 59 28 PM" src="https://user-images.githubusercontent.com/31858118/230997780-fc3c3171-99ae-4851-8fa1-81171b5d0b82.png">

### To Reproduce

This behavior happens intermittently and I can't deliberately reproduce the behavior, but it typically happens when Im making changes to many charts in a short period of time.

### App Version

v0.426.1

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - I have a feeling it's related to some sorting behaviour (given how the chart looks). But we haven't heard of this being reproduced by anyone and haven't been able to reproduce it ourselves. 

Will reopen if it's reported again!
