### ISSUE TITLE
Grant "admins" access to all spaces and content

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5042]
### Description

Currently, admins might not have access to certain spaces or content created by other users. This can make it difficult for admins to manage and oversee their organisation effectively.

### Acceptance criteria

- [ ] admins have two types of content available to them:
    - `shared with me`  - this is content/spaces where they have been explicitly invited or they have created it themselves - this is the content they have access to today
   - `private` - this is content where they have not been explicitly invited - they do not have access to this today. 
- [ ] updated documentation
- [ ] admins can't browse content that's `private` - they can only view the content by direct access to the URL (either saved chart, dashboard, or space)
- [ ] update the modal on creating a private space to say `only you and admins can access this`

<img width="516" alt="image" src="https://user-images.githubusercontent.com/31848148/236245055-a4536346-c5e9-49a1-9f58-6f395bcb4a34.png">

- [ ] update the modal on creating a `restricted access` space to say `only invited members and admins can access`
- [ ] Also update the list of users in the modal to default include all admins
<img width="508" alt="image" src="https://user-images.githubusercontent.com/31848148/236245380-4fcff18b-70a5-4b64-beee-e55b3c58ad45.png">

**Comment by PriPatel** [comment]
- This would also require updating copy when users are creating Spaces. They would need to know that Spaces are not really 'private'.
- This means that admin's `All Spaces` pages are going to potentially be crowded. We might need to show spaces in a table format as well as potentially splitting up private and public spaces. 
- This would require updating the 'Permissions modal'. Always show that that the admin has visibility, even when the user has selected 'Restricted Access'
 <img width="518" alt="Screenshot 2023-04-11 at 10 13 57" src="https://user-images.githubusercontent.com/12776522/231112885-20c5a53f-5ba1-4e8d-b396-e2715a901112.png">

**Comment by PriPatel** [comment]
- We should probably start displaying 'Space Creators' or 'Owners' as well.
