### ISSUE TITLE
Update the Blueprint icons for buttons in charts/dashboard headers to Tabler icons

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5053]
**Dashboards:**
<img width="273" alt="Screenshot 2023-04-11 at 17 02 52" src="https://user-images.githubusercontent.com/12776522/231220990-a4448ab0-6be6-4a47-ac2a-f5edc65a2b3c.png">

**Charts:**
<img width="312" alt="Screenshot 2023-04-11 at 17 02 59" src="https://user-images.githubusercontent.com/12776522/231221005-b5a8dbe1-3a23-4a40-a6bb-ee3fda381a76.png">

**Comment by lokeswaran-aj** [comment]
Hii @PriPatel Can you assign this to me?

**Comment by lokeswaran-aj** [comment]
Hii @PriPatel Raised a [PR](https://github.com/lightdash/lightdash/pull/5071) to fix this issue
