### ISSUE TITLE
Investigate slow dashboards

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5074]
### Description

Some issues have reported slow dashboards, it seems the `dashboard endpoint` alone is taking 1+ second to return. 

![image](https://user-images.githubusercontent.com/1983672/231674593-78417c43-807d-4d7f-a77b-6c129ed12698.png)

**Comment by rephus** [comment]
Related ? https://github.com/lightdash/lightdash/issues/4510

**Comment by owlas** [comment]
Calling this closed after shipping the fixes on this milestone: https://github.com/lightdash/lightdash/milestone/91?closed=1
