### ISSUE TITLE
When I apply conditional formatting to a pivoted value, the cell should get highlighted

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5078]
### Description

Right now, if I add a conditional formatting rule that applies to a value in a pivoted column, then none of the cells are highlighted. 
For example, here I've applied the conditional formatting rule to the number `8`, but no values are highlighted.
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/31848148/231693137-4c570d3a-421f-433f-876e-adb3b064b987.png">

I would expect that the cell would be highlighted.

**Comment by owlas** [comment]
This was by design when we implemented the new table. How would you distinguish the column headers from the data if they were all highlighted similarly?

**Comment by TuringLovesDeathMetal** [comment]
Closign this issue as not planned (hasn't been requested since it was created)
