### ISSUE TITLE
I want to have the option to highlight an entire row or column based on my conditional formatting rule

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5079]
### Description

If I have a conditional formatting rule, I want to have the option to highlight the entire row or column if a value in matches the rule. 

For example, in this image: 
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/31848148/231694304-66f225e0-3017-4324-b4f3-5727df2f3e64.png">

I'd want to be able to highlight the _**row**_ where the value `6` appeared.

In pivoted tables, I'd want to be able to highlight the _**column**_ where the `6` value appeared:
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/31848148/231694534-b287f299-a4cc-45d8-af93-e1082476e090.png">

### What problem does this solve?

<img width="369" alt="image" src="https://user-images.githubusercontent.com/31848148/231694641-80a64f55-9927-4e5e-84d3-637f3aaea848.png">

**Comment by Sai-Karthik-Tumu** [comment]
Hey @TuringLovesDeathMetal , can I work this issue. If yes, could you please add any details if I need to take before working on this.

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned. It feels weird and no one has requested it since it was first created
