### ISSUE TITLE
The totals on my chart should adjust when I toggle fields as visible/not visible from view

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5081]
### Description

When I toggle fields on/off, the bar total labels should update. 

![image](https://user-images.githubusercontent.com/31848148/231697852-fc6f188d-d465-4275-8304-b5507fd02cdb.png)
![image](https://user-images.githubusercontent.com/31848148/231697885-fa7df3b9-4605-4b31-8c97-f4ed1d21b994.png)

**Comment by PriPatel** [comment]
Requested by someone in the community
https://lightdash-community.slack.com/archives/C03MG2VTR08/p1683139712560319
