### ISSUE TITLE
Test and make Lightdash CLI compatible with 1.5.0-rc1

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5094]
### Description

This version of DBT  

```
Core:
  - installed: 1.5.0-rc1
  - latest:    1.4.5     - Ahead of latest version!

Plugins:
  - snowflake: 1.5.0b3 - Ahead of latest version!
```

Is causing the following error when doing `lightdash compile`

```
Found 18 errors when validating dbt models:
- companies: Field at "/refs/0" must be array
```

**Comment by amsharm2** [comment]
is there any fix available for this error ? I am also facing similar error while compilation / deployment
ERROR> order_payments_method_amounts : Field at "/refs/0" must be array

**Comment by rephus** [comment]
Done
