### ISSUE TITLE
Improve error messages when dbt is running, but it fails

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#51]
When dbt’s running but it’s failed, it’s not obvious what the problem is. We need to improve these error messages.

The current error message looks something like this:
```
GET /api/v1/tables 500 283.331 ms - 634
(node:29) UnhandledPromiseRejectionWarning: DbtError: Error returned from dbt while executing method 'status'
    at /usr/app/packages/backend/dist/dbt.js:124:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/app/packages/backend/dist/dbt.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Instead of just having this `DbtError: Error returned from dbt while executing method 'status'`, we should have a bit that says `...and this is why it failed` after it.

**Comment by owlas** [comment]
@all-contributors add @TuringLovesDeathMetal for bugs, docs, design
