### ISSUE TITLE
I wish that the titles on my dashboard tiles would appear in full when I hover.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5102]
### Description

Right now, when I hover on a tile with a title that's long and doesn't fit, I can't see the title in full. I wish there was some way to see the title in full on hover (otherwise I need to open the tile in view mode to see the title).

<img width="466" alt="image" src="https://user-images.githubusercontent.com/31848148/232433383-4f0a38ec-0880-4b64-859f-d9def747b214.png">

**Comment by PriPatel** [comment]
This feature already exists but there appears to be a bug! [ this is a bug! ](https://github.com/lightdash/lightdash/issues/4982)
<img width="498" alt="Screenshot 2023-04-20 at 10 19 19" src="https://user-images.githubusercontent.com/12776522/233274528-7fa42701-d849-44ed-91c5-18228480cacb.png">
It works in some places but not in others! (Screenshot shows an example where it works. Needs investigating!)
