### ISSUE TITLE
Support multiple dbt versions

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#5109]
### Description

Support multiple dbt versions in the same Lightdash instance. 
At the moment user projects need to be compatible with the only dbt version supported by Lightdash. 

The user should be able to specify what dbt version should be used for each project. They should also be able to update the dbt version at any time. 

### What problems does this solve?

When Lightdash updates the version, users might get incompatibility errors.
Users using the most recent version aren't blocked by Lightdash using an older version.

### Possible implementation

This work can be split into multiple PRs.

1. Add tools to support multiple dbt versions

- remove dbt install from dockerfile and instead install https://github.com/brooklyn-data/dbtenv
- change `dbtCliClient.ts` to install the necessary dbt version if not yet installed ( note that the version should be hardcoded for now v1.4.0 )
- change `dbtCliClient.ts` commands from `dbt` to `dbtenv` with a specific version

2. Allow users to select dbt version for their project

- migrate DB so the projects table has a `dbt version` string column
- update types, models, services, endpoints
- update `dbtCliClient.ts` to use the project dbt version instead of the hardcoded version
- add a dropdown in the project from where the user can select the dbt major+minor version eg: 1.3, 1.4.

Possible improvements:
- pre-install some versions on server start

#### How to handle the different manifest versions

We rely heavily on dbt manifest file that is generated with `dbt compile`. At the moment we have 1 function that parses this json and collects the necessary information. 
Since we are going to support multiple versions of this manifest we need one function/class per version.

**Comment by TuringLovesDeathMetal** [comment]
For the first version, let's not make it possible for users to select the dbt version they're using. Instead let's just run 1.5 by default, and if it fails, we run 1.4 instead

**Comment by rephus** [comment]
I've been sharing this ticket with some customer https://github.com/lightdash/lightdash/issues/5668, let's merge that one too  once this ticket is done
