### ISSUE TITLE
user gets stuck at `/join-organization` when trying to sign up after admin invites the user

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5114]
### Description

user gets stuck at `/join-organization` when trying to sign up after admin invites the user

* as an admin invite user
* sign out
* as a user go to `/register`
* type in the same email address that admin used to invite the user
* 💥 

<img width="772" alt="CleanShot 2023-04-17 at 19 36 49@2x" src="https://user-images.githubusercontent.com/962095/232537573-cf79ccbd-054f-417d-8ea0-2d5009e6a351.png">

![image](https://user-images.githubusercontent.com/962095/232537427-0e739700-c957-472d-955c-ba947dd56b44.png)

**Comment by ZeRego** [comment]
The FE is trying to create a new organisation but the backend doesn’t allow it because `ALLOW_MULTIPLE_ORGS` is false by default. The FE should handle the org creation error and show the returned message.
