### ISSUE TITLE
Improve Slack messages when scheduled delivery has no results

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5118]
Currently if a csv exports results in no results, then no slack message is sent. It would be better if we sent a message to slack telling the user that the delivery was completed but there were no results

_Originally posted by @owlas in https://github.com/lightdash/lightdash/issues/5115#issuecomment-1511660455_

**Comment by joaoviana** [comment]
@TuringLovesDeathMetal what do you think about this copy (see `No results to download`), does it sound ok for this particular scenario?

![image](https://user-images.githubusercontent.com/7611706/233106213-76bd42a8-1722-48f5-a565-94f45f688fa1.png)

**Comment by TuringLovesDeathMetal** [comment]
How about `this query returned no results`.

"No results to download" sounds like it might be an us problem (i.e. we somehow made it so that the results weren't available), not a query problem? What do you think?

**Comment by TuringLovesDeathMetal** [comment]
Or even "This chart has no results"

**Comment by joaoviana** [comment]
> How about `this query returned no results`.
> 
> "No results to download" sounds like it might be an us problem (i.e. we somehow made it so that the results weren't available), not a query problem? What do you think?

That sounds great, and makes it clear that where the issue lies. I would like to go for `this query returned no results`

**Comment by TuringLovesDeathMetal** [comment]
Perfect! let's do it
