### ISSUE TITLE
csv export is stuck at loading

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5120]
### Description

csv export is stuck at loading

![image](https://user-images.githubusercontent.com/962095/232572086-8b704e09-cdb1-4701-bf7c-31e121a3f184.png)

### To Reproduce

this can be reproduced by going to analytics and trying to export csv from results or table-chart

**Comment by rephus** [comment]
Some Scheduler with images were blocking the workers, which means no other scheduler jobs were executed, like CSV downloads. This was fixed here: https://github.com/lightdash/lightdash/pull/5112
