### ISSUE TITLE
date/timestamp type metrics can't be plotted in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#513]
Right now, if you have a date metric in Lightdash, it won't plot. 

https://demo.lightdash.com/projects/f24cb810-be54-4ae4-a3a1-5efcd5f6ea3f/tables/orders?dimensions=orders_amount&metrics=orders_date_of_first_order&limit=500&column_order=orders_date_of_first_order%2Corders_amount

**Comment by owlas** [comment]
Needs further testing after #755
