### ISSUE TITLE
bar chart stacking setting persists even if user removes groups

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5131]
### Description

if a user removes groups, the bar chart stacking setting will still be in effect

### To Reproduce

![CleanShot 2023-04-18 at 14 44 42](https://user-images.githubusercontent.com/962095/232754120-cbc5845b-13e2-4bcd-8317-d97b83324743.gif)

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani I feel like some users are using this as a feature actually? But I can't remember if it's this issue?

**Comment by IrakliJani** [comment]
still relevant. as mentioned we need to support stacking without groups too

**Comment by ZeRego** [comment]
Closing this since we want to [support stacking without grouping](https://github.com/lightdash/lightdash/issues/8701) and fixing this bug would undo the work for that feature.
