### ISSUE TITLE
upload slack scheduled deliveries images on thread 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5133]
### Description

Right now images expire in 3 days, after that, you can't see what's on the dashboard

We could upload the images on a thread. 

![image](https://user-images.githubusercontent.com/1983672/232785057-b1719a3b-7dba-48d2-91f4-c9782ff89c58.png)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. 

it hasn't been raised again in nearly a year. Will reopen if it gets mentioned again by a user!
