### ISSUE TITLE
New grouped dropdown component - Adding a saved chart to a dashboard (from the chart) 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5155]
This is the modal that is shown when you are in a `saved chart` and you use the three-dot menu to add it to a dashboard.
<img width="548" alt="Screenshot 2023-04-20 at 09 38 12" src="https://user-images.githubusercontent.com/12776522/233268386-baf8ad6b-d105-46da-aebf-ecc9d59ac330.png">

- [x] The `dashboards` in the dropdown should be grouped by `Spaces`
- [x] The first `space` displayed should be the one that the `chart` in question belongs to. 
- [ ] Add a space icon in front of the Space name

**Comment by yasmin-e** [comment]
Decided to migrate to Mantine in order to use their Select component that allows grouping.
The alternative was to build a custom grouping feat for a native HTML Select which would take longer and would be overwritten by a Mantine migration later on, anyway.
