### ISSUE TITLE
New grouped dropdown component -  Adding multiple charts to a dashboard

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5156]
This is the modal you see in a dashboard when you add `saved charts` tiles. You are able to select multiple charts.
<img width="534" alt="Screenshot 2023-04-20 at 09 51 31" src="https://user-images.githubusercontent.com/12776522/233269624-40817903-b9e2-4b1e-ab94-0ac7ea4eab68.png">

- [ ] Instead of repeating the `Space` name each time, show it as a group label using the new grouped component
- [ ] Update the `Space` icon to be a tabler one
- [ ] The first `Space` that is displayed should be the one that the `dashboard` is already in.

This might need extra testing and care as this is multi-select and therefore a bit different to the other modals we have implemented this to.

**Comment by yasmin-e** [comment]
Decided to migrate to Mantine in order to use their Multiselect component that allows grouping.
The alternative was to build a custom grouping feat which would take longer and would be overwritten by a Mantine migration later on, anyway.
