### ISSUE TITLE
You should not see the 'no results' label when the query returns no results

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5160]
It is already implied. It also adds to clutter

- [ ] Remove both 'no results' labels

<img width="750" alt="Screenshot 2023-04-20 at 10 17 53" src="https://user-images.githubusercontent.com/12776522/233274136-cf11c4e6-d96e-4882-a41e-a7c8fe2e1e96.png">

**Comment by hrutik7** [comment]
Is this relevent ? because I was unable to reproduce this

**Comment by PriPatel** [comment]
Hi @hrutik7 , correct this has already been resolved!
