### ISSUE TITLE
I want to be able to send a scheduled delivery to a google sheet [CLOSE at end of milestone]

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5162]
### Description

I want to be able to set the destination of a scheduled delivery as a google sheet. 

The setup would be the same as exporting a .csv (you define the number of rows, the format, etc.) but then, I would have to include the google sheet link as where to send it. 

### Outstanding questions
- How can we give Lightdash permissions to write to the sheet?

**Comment by hamzahc1** [comment]
Update for folks - this feature is waiting to be approved by Google's Trust & Safety team. Once this is complete, it will be released 🚀
