### ISSUE TITLE
[Scheduled deliveries in Settings] Separate `schedulers` from `logs` API call

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#5175]
### Description
Logs take too long to load, making the whole table lag on render. We should have a separate call for `schedulers` and `logs`. This way, we can render the first table `All schedulers` - `Last Delivery` and `Next delivery` columns that can have a loader while we wait for the logs.

https://user-images.githubusercontent.com/67699259/233463217-f9c2b30c-c483-4971-9348-e314f73b4b5a.mov

**Comment by rephus** [comment]
We don't need this anymore. we limit the number of results , and the bottleneck was on the frontend anyway. Closing this
