### ISSUE TITLE
Create a command in the CLI for `lightdash validate`

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5229]
### Description

This validates the changes in yaml in the dev branch against the content in the preview project (which has been copied from prod). 

You can't fetch the latest changes from prod in your dev branch - be sure to make this clear in the docs!

### Acceptance criteria

- [ ] running `lightdash validate` on the CLI triggers the validation endpoint 
    - [ ] I imagine we'll need to build a preview environment to run `lightdash validate` against...so we'll possible need to run `lightdash preview` before we trigger the validator here! 
- [ ] There is a loading state while the CLI is running the validation
  - something like: `[12s] validating your project` where `[12s]` is a timer that shows you how long your project has been validating for
  - Ideally there would be "stages" that are validated and this is shown on the CLI. E.g. 

```
    [12s] validating your project
    
    - validating tables [COMPLETED]
    - validating charts [COMPLETED]
    - validating dashboards [2s]
```

- [ ] there is some "completion" state which shows you the errors. 
    - [ ] It tells you the overall number of items that were validated
    - [ ] It tells you how long the validation took
    - [ ] It breaks down the validation across tables, charts and dashboards
    - [ ] It gives you a table of the errors ordered by type: (tables, then charts, then dashboards). Then alphabetically by the item name within each type (A-Z)
```
Successfully validated 150 project items in 123s, SUCCESS=130 ERRORS=20

- Tables: SUCCESS = 30, ERRORS = 0
- Charts: SUCCESS = 55, ERRORS = 12
- Dashboards: SUCCESS = 20, ERRORS = 8

Item name   |   Link   |  Error  |
-----------------------------
Katie's Chart. | app.lightdash.cloud/chart-id | blah bah something's broken error
KPI dashboard | app.lightdash.cloud/dashboard-id | blah balsdndskladjksla

Done 🕶
```

**Comment by TuringLovesDeathMetal** [comment]
Idea: Imagine if there was a way to "open this validation in Lightdash" 🤯 

So it would open the "validation" overview page, but in your preview project. I just feel like interacting with these errors would be much nicer in the UI compared to on the CLI

**Comment by TuringLovesDeathMetal** [comment]
Two example use cases:

1. I want to add `lightdash validate` to my CI/CD so that PRs are blocked from being merged if they fail validation. 
2. I want to be able to run `lightdash validate` while I'm developing my project so I can check to see if my changes will break anything in prod.

**Comment by rephus** [comment]
@TuringLovesDeathMetal we don't return `success` on validation, only errors, I can still filter by chart/dashboard/Table and show you a summary before the table if you want 

![image](https://github.com/lightdash/lightdash/assets/1983672/a2a1cb6f-928a-46a6-89d0-d212d85b925b)
