### ISSUE TITLE
I want the search bar to be more prominent in the nav bar

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#5245]
### Description
The search bar should be:
- in the middle instead of the corner right of the nav bar
- wider
- better contrast with the background

It's also weird that it's a text box that you can't type in, so it should be a button since it acts as a button.

### What problem does this solve?
Making it more prominent, so the users interact more with it (currently only 22% of users use it) and have a better chance of finding what they're looking for

**Comment by ZeRego** [comment]
@all-contributors add @yasmin-e for bugs, ideas and design.
