### ISSUE TITLE
Capture search results for improving search

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5250]
### Description

We want to improve search over time, we should track statistics on search success. New events

- `lightdash-server.search.opened`
- `lightdash-server.search.searched`
  - search string
- `lightdash-server.search.completed`
  - rank of result
  - search string
  - number of attempts
- `lightdash-server.search.reopened_results`

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned
