### ISSUE TITLE
Track user's recently viewed `chart`  and `dashboard` 

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#5251]
### Description

https://www.notion.so/lightdash/I-want-to-be-able-to-find-answers-to-my-questions-in-Lightdash-9f884b00e8584405aa1ae4f74cb70b73

- We need to track the chart/dashboard view history on a per user basis.
- This should be tracked in a way that allows for easy and quick calling from the frontend.

### What problem does this solve?

- This is to support the "Recently viewed" feature in this milestone, which comes up in the empty search bar state to help nudge users in the right direction

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. Can re-add it as needed to hte search bar improvements if we decide to work on it.
