### ISSUE TITLE
Analytics events for validate content

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5252]
### Description

`validation_page_viewed` - triggered when someone views the page with all teh validation events.

  - `organization_id`
   - `project_id`
   - `user_id`
   - `validation_run_id`
   - `timestamp`

`validation_run` - triggered when someone hits `validate` from the UI

  - `organization_id`
   - `project_id`
   - `user_id` that triggered it - if it's triggered from a deploy, then this is NULL
   - `timestamp`
   - `context` - where this is being triggered (e.g. `lightdash_app`, `github_action`, eventually `cli`etc.)
  
`validation_completed` triggered when the validation is completed successfully

  - `organization_id`
   - `project_id`
   - `user_id`
   - `validation_run_id`
   - `timestamp`
   - `context`
   - `num_errors_detected` - the total number of errors listed (one piece of content could have multiple errors)
   - `num_content_affected` - the total number of items of content that have errors 
 
`validation_error` triggered when there is an error in running in the validator

  - `organization_id`
- `project_id`
- `user_id`
- `validation_run_id`
- `timestamp`

**Comment by rephus** [comment]
@TuringLovesDeathMetal I'm changing the context to these (currnetly the distinct ways a validation can be triggered) 

>     context: 'lightdash_app' | 'dbt_refresh' | 'test_and_compile' | 'cli'
