### ISSUE TITLE
Hide metrics/dimensions from search

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5253]
### Description

Remove metrics/dimensions from search to improve search speed and reduce the variety of results in search

**Comment by ZeRego** [comment]
My main use of the global search is to find metrics. I just want to have the option to select what content I'm searching. eg: content ( spaces, dashboard, charts ) vs tables/dimensions/metrics

**Comment by IrakliJani** [comment]
@ZeRego agreed on this one
> My main use of the global search is to find metrics. I just want to have the option to select what content I'm searching. eg: content ( spaces, dashboard, charts ) vs tables/dimensions/metrics

new search ui is going have a type picker (miro: https://miro.com/app/board/uXjVNv65JFM=/). so if you are searching for a dashboard you can choose to show only dashboards
