### ISSUE TITLE
I'd like to have keyboard interactions in the search bar

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#5256]
### Description
- I'd like the first result of my search to be hovered 
- I'd like to use up and down keys to navigate my search results
- I'd like to press enter to navigate to my search result (already implemented)
- I'd like to be able to type `/` and see my `Go to` options (pages)

### What problem does this solve?
Better UX

**Comment by IrakliJani** [comment]
- I'd like to be able to type `/` and see my `Go to` options (pages)

let's skip this one as its not about keyboard navigation

related ticket: https://github.com/lightdash/lightdash/issues/5268
