### ISSUE TITLE
On the homepage, I'd like to see the search bar in the main body

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#5258]
### Description
- On the homepage only, the search bar should be in the main body of the homepage, at the top.
- It should also be centred.
- When scrolling down beyond view of the search bar, it should move from the body back to the menubar.
- On every other page, the search bar should remain in the menubar.
- When selecting the search bar, the new search modal should appear, with the rest of the page greyed out. The animation should be smooth.

Sketch: 
https://www.notion.so/lightdash/I-want-to-be-able-to-find-answers-to-my-questions-in-Lightdash-9f884b00e8584405aa1ae4f74cb70b73

### What problem does this solve?
The search bar is not prominent enough.

**Comment by TuringLovesDeathMetal** [comment]
Closign this as not planned - can reopen if needed when we work on the search bar
