### ISSUE TITLE
I'd like my search results to have more relevant information

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#5259]
### Description
For every search result, I want to be able to see:
- an icon 
- its tile
- its description
- where it lives (if it's a `chart` or `dashboard`, in which `space` and if it's a `table`, nothing)

Sketch: https://miro.com/app/board/uXjVMO6641U=/

### What problem does this solve?
Better UX

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned (can be reopened if needed when we work on the search bar)
