### ISSUE TITLE
We're able to track changes in content in the backend

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5260]
### Description

When I change content in the preview environment, we're able to identify those changes (compared to production). 

The changes we want to be able to identify are:
- created chart
- updated chart
- deleted chart
- create dashboard
- updated dashboard
- deleted dashboard
- space created
  - you can only create private spaces in a preview environment (otherwise we'd need to import permissions which we don't want to do).
- space updated 
  - you can't update the permissions on a space.
- space deleted

For updated content, we just copy the content.
For new content, we can change just the project ID so that we don't have to create new chart IDs.

**Comment by tnightengale** [comment]
@TuringLovesDeathMetal Hey, we are very interested in implementing this. Would this just require some SQL DML statements in the Postgres backend? We are happy to look at writing those, but could use some guidance on the API/Frontend implementation?

**Comment by tnightengale** [comment]
@ZeRego Hey, I would love to contribute to getting this feature done and would undoubtedly benefit from your guidance on the implementation. I see your milestone above is no longer active? How can we work together to spec this and get it done?

**Comment by tnightengale** [comment]
Broadly related to #369!
