### ISSUE TITLE
In search, I want to see more results of chart/dashboards/...

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5261]
### Description

When I'm searching results I want the option to "see more dashboards" of a specific type, which would update the results to only show that type. For example if I click "see more" on dashboards, the grouped search results will be replaced with just dashboard results. 

You can also go back the view by clicking "see other results"

**Comment by IrakliJani** [comment]
requires a backend change to paginate search results

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned - can reopen if necessary when we look at more search bar improvements
