### ISSUE TITLE
Docker compose ends up with error

### ISSUE THREAD

**Issue by patrikbraborec** [lightdash/lightdash#5291]
### Description

I followed this [tutorial](https://docs.lightdash.com/self-host/self-host-lightdash-docker-compose/) in the docs. Unfortunately, it ends up with error `error: Error starting standalone scheduler worker getaddrinfo ENOTFOUND db-dev`. I think that issue is in `.env` file: https://github.com/lightdash/lightdash/blob/main/.env#L7.

### To Reproduce

Just follow the docs: https://docs.lightdash.com/self-host/self-host-lightdash-docker-compose/.

### App Version

v0.525.0

**Comment by ZeRego** [comment]
@all-contributors add @patrikbraborec for bug

**Comment by ZeRego** [comment]
Change suggestions https://github.com/lightdash/lightdash/pull/5292#issuecomment-1531116172

> At the moment .env shouldn't be used for production, only for development.
> The [self-hosting docs](https://docs.lightdash.com/self-host/self-host-lightdash-docker-compose/) don't mention using the .env file. @patrikbraborec Was it picked by default or you assumed you should use it?
> 
> Either way, the .env file should be set with production like variables.
> 
> Proposed changes:
> 
> rename .env to .env.development
> update package.json and contribution docs to reference new file name and .env.development.local
> create .env with main env vars with empty values ( check .env.fast-install ) and all the rest of possible env vars commented out
> update self-hosting docs to configure and use the .env file
