### ISSUE TITLE
Provide a Data Model view to see relationship between Tables

### ISSUE THREAD

**Issue by djouallah** [lightdash/lightdash#53]
it will be really nice specially in complex models to see relationship between tables 

thanks, this is a very exciting project.

**Comment by owlas** [comment]
Hey @djouallah thanks for raising this one! This is one of the most exciting things we wanted when we came up with the idea for Lightdash. 

@TuringLovesDeathMetal has started a milestone for this, which I've just linked here and you can follow.

**Comment by TuringLovesDeathMetal** [comment]
hey @djouallah - totally agree that this would be cool! I'm actually speccing this feature now, but just wanted to make sure I understand what you mean by "relationship between tables".

I was imagining having something like the dbt dependency graph for a table available to users in lightdash. So, you could see things that are upstream + downstream of the table you're looking at. (Have attached a pic for reference). 

Were you thinking of something similar? Or were you thinking more about showing the join logic for models if you have something joined to your model in lightdash? 

![image](https://user-images.githubusercontent.com/31848148/121027264-1de5d700-c7a7-11eb-84e4-902613f40087.png)

**Comment by djouallah** [comment]
@TuringLovesDeathMetal thanks, I was rather referring to the join in the data model not the downstream dependencies ( which we have anyway alreadyin the dbt model), what missing is a data model view between tables for reporting
something like this
![image](https://user-images.githubusercontent.com/12554469/121095637-0d2f7280-c834-11eb-8599-d07b95cf8c50.png)

**Comment by TuringLovesDeathMetal** [comment]
@djouallah nice! That makes sense. Oliver and I were actually talking about this yesterday. 

Short-term we're thinking that we just surface the raw SQL used in the join. But long term, it could be really cool to have a more in-depth mapping like you've shown here (e.g. the join keys in the tables, the join types used)

Just [specced a first ticket for this](https://github.com/lightdash/lightdash/issues/68) - hopefully this is a step in the right direction! :)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue in favour of: https://github.com/lightdash/lightdash/issues/68
