### ISSUE TITLE
Metrics on the x-axis

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#531]
If I have two metrics, I might want to compare them against each other on a scatter plot, where I have the x-axis, and y-axis as metrics

**Comment by TuringLovesDeathMetal** [comment]
+1 to this. We'd need to change the chart configuration to be able to support this

**Comment by ZeRego** [comment]
Should we just stop differentiating dimensions from metrics in chart configs ?

**Comment by TuringLovesDeathMetal** [comment]
^That's a really interesting idea!

Instead, maybe focusing on `y-axis` and `x-axis` would be more helpful 🤔 I can't think of a reason why you'd want to differentiate between the two in the chart configs...

I'm imagining Excel, and they don't care what you have on x vs. y...but something more automated/advanced like Tableau and Looker definitely care (I'm trying to think of features that would require you to differentiate between the two...)
