### ISSUE TITLE
Expanding the SQL tab in an explore causes weird formatting

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#532]
If you open the SQL tab in an explore, it causes some weird formatting ont he screen (you lose the side tab and it zooms in on stuff). 

Not sure if this is because some of the values in my SQL query were quite long. 🤔 
https://www.loom.com/share/78b7f272dec84c3ba4f09c7aba92561d

**Comment by TuringLovesDeathMetal** [comment]
Update: it also cuts off some of the SQL if it's too long to fit in the screen. 

E.g. if you copy-paste the SQL into BigQuery, they soft-wrap the text onto a new line:
![image](https://user-images.githubusercontent.com/31848148/135832967-a106abcc-c832-449a-a325-d86c5ee1eb95.png)

**Comment by ZeRego** [comment]
The issue where the sidebar disappears was fixed recently but now we have the issue where the sql  text overflows.
![Screenshot 2021-11-16 at 11 45 47](https://user-images.githubusercontent.com/9117144/141979831-72ef6a2b-08fb-4c9f-8c8c-1f31c28f3c23.png)
