### ISSUE TITLE
Field is selected/unselected from Results pane when adding filter

### ISSUE THREAD

**Issue by serene-capybara** [lightdash/lightdash#5333]
### Description

In the Explore page, when adding a filter from the Metrics/Dimensions list, that Metric/Dimension is selected/unselected from the results columns.
Previously, adding a filter from this list would not select/unselect that field.
### To Reproduce

1. Go to the explore page for one of your tables
2. Click on the `...` menu for one of the dimensions/metrics of your table.
3. Click `Add Filter`
4. See that the field has been selected/unselected from the Results Pane
### App Version
v0.529.2

**Comment by owlas** [comment]
Thanks for reporting @serene-capybara!

I managed to replicate this in v0.527.2 - @IrakliJani we must not be blocking a click propagating in the new mantine sidebar, could you take a look?
