### ISSUE TITLE
Being able to go 'back'/undo changes you've made when you're building an explore

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#536]
### Context
Right now, if you change your query, run it, and realize what you did was wrong, there's no way to undo the changes you've made (unless it's a saved query). 

My instinct when this happens is to click the `back` button in the browser tab. 

### Goal
have some way of navigating "back" to the previous query settings you've just run. 

Some suggestions:
1. you're able to click "back" in the browser
2. there's some "undo" command or button in the app

**Comment by hamzahc1** [comment]
Related to #1431
