### ISSUE TITLE
The width of the Project Settings content does not match the rest of the content in the other tabs 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5364]
<img width="1097" alt="Screenshot 2023-05-04 at 11 12 33" src="https://user-images.githubusercontent.com/12776522/236177737-8c5ed651-0cbb-44a3-bfde-2ee9f5f343a1.png">

**Comment by IrakliJani** [comment]
hmm, not present locally. I'll take this

**Comment by PriPatel** [comment]
This was from our own instance. The demo instance looks fine!
