### ISSUE TITLE
There is no overflow or wrapping in the project dropdown

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5366]
<img width="225" alt="Screenshot 2023-05-04 at 14 28 29" src="https://user-images.githubusercontent.com/12776522/236217998-d2947258-8e00-4e47-98ca-9e5ec88830f9.png">

**Comment by IrakliJani** [comment]
wdyt should there be a wrap or truncated text?

**Comment by PriPatel** [comment]
Some of these preview names are really long so lets do truncated for now! Wrapping might look super weird.
 I suppose the dropdown could also be wider? (doesn't have to match the width of the input, right?) 

 I imagine later we want to make preview ones look different somehow etc so this can just be a quick fix! wdyt?

**Comment by IrakliJani** [comment]
@PriPatel right now it has a vertical scrolling which is not ideal, I'll try to increase dropdown width and truncation as well
https://github.com/lightdash/lightdash/assets/962095/cfa16095-65b5-488b-b18a-13d9b7609413
