### ISSUE TITLE
Can't load all slack users and channels

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#5389]
### Description

[Relevant slack thread](https://lightdash-community.slack.com/archives/C03MG2VTR08/p1683302046337909?thread_ts=1683301749.789409&cid=C03MG2VTR08)

> when trying select a user to send a scheduled delivery to the dropdown box either doesn’t not populate with user names or channels or freezes when they’re present. We also noticed that the calls to the slack API have been getting rate limited or timing out. 

![Screen Shot 2023-05-02 at 11 13 30 AM](https://user-images.githubusercontent.com/9117144/236514105-53804199-eba0-4fe3-8919-1668e7ef66ac.png)

Each Fetching slack users with cursor log represents 500 results. 

We are caching slack results but doesn't cover this case where their slack has thousands of users & channels causing us to make a lot of requests all at once.

Does Slack documentation have a recommendation for such feature? 
Can we have an auto complete?

### App Version

0.537.2

**Comment by rephus** [comment]
We already have pagination on users and channels. , but still, they have rate limiting, so you can't make "Many" requests too quickly... I am not sure how to fix this

**Comment by owlas** [comment]
Is there an autocomplete endpoint in the API? In slack modals there is a component that implements channel autocomplete but not sure if it's a public API

**Comment by rephus** [comment]
even if they have autocomplete (it could be the same endpoint, I can investigate) , that api is also going to be rate limited, so after your 3rd request you're going to get blocked for a few minutes...

**Comment by rephus** [comment]
I contacted slack to see what they suggest...

**Comment by owlas** [comment]
The conversations approach makes sense, we might not even need to make any other change (assuming the customer that had this problem is not actually present in the 2,000 channels in their workspace).

Do we need to change our bot permissions to use that API?

**Comment by rephus** [comment]
Yes, we'll have to include these 3 new scopes for getting private channels and users (im) 

```
    'groups:read', 
    'im:read',
    'mpim:read',
```
