### ISSUE TITLE
 Migrate `Settings > Org settings > Integrations` from Blueprint to Mantine

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#5400]
Migrate to mantine UI the following view: 
![image](https://user-images.githubusercontent.com/7611706/237053754-9064e234-d526-47ed-9ab0-af06cc0d5abd.png)

**Comment by Ankush263** [comment]
Hello @joaoviana, I want to contribute to this issue but can't find the `Integrations` tab

![Screenshot (101)](https://github.com/lightdash/lightdash/assets/86042508/47e992a1-6901-406b-824c-67d591b22687)

**Comment by joaoviana** [comment]
migration to React: done ✅
