### ISSUE TITLE
Migrate `project settings` forms to use Mantine

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5402]
### Description

migration should cover all of the 3 cards under project settings

<img width="1243" alt="CleanShot 2023-05-09 at 13 30 18@2x" src="https://user-images.githubusercontent.com/962095/237055397-9c979b7b-9411-4e98-b51e-f62d9b5f7549.png">

use Card component from Mantine as a card wrapper.
use mantine-form for managing form state.
use either Collapse or accordion for "advanced configuration options"

- [x] general settings
- [x] warehouse connection
- [ ] dbt connection

**Comment by jayanand05** [comment]
working..
