### ISSUE TITLE
Migrate `Project settings > Project access > new User` to use Mantine

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5404]
### Description

- [ ] add user inside Project access should be a modal
- [ ] migrate form to use mantine (mantine-form)

![CleanShot 2023-05-09 at 13 34 07@2x](https://user-images.githubusercontent.com/962095/237056580-007d6bd2-7c25-45e7-8851-92b1ffcf0c96.png)

<img width="713" alt="CleanShot 2023-05-09 at 13 35 03@2x" src="https://user-images.githubusercontent.com/962095/237056548-3dbc3323-b188-45be-bf9d-73fb4246729c.png">

**Comment by iampranavdhar** [comment]
@IrakliJani Can you assign me to this ?

**Comment by IrakliJani** [comment]
@iampranavdhar done!

**Comment by iampranavdhar** [comment]
@IrakliJani Made a PR :)

**Comment by Ankush263** [comment]
Hello @IrakliJani, can I work on this issue?

**Comment by IrakliJani** [comment]
@Ankush263 yep, go ahead!

**Comment by Ankush263** [comment]
Hello @IrakliJani, I have changed some UI components from blueprint to mantine. #7298 
It's just the UI elements, I don't change the input form since that requires some complex code changes.
I want to make this PR less complex.
will make those complex changes in my next PR.

**Comment by muhammadjufry** [comment]
Hi @IrakliJani Can I work on this issue?
