### ISSUE TITLE
Migrate `Project settings > Project access list` to use Mantine

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5405]
### Description

<img width="709" alt="CleanShot 2023-05-09 at 13 37 06@2x" src="https://user-images.githubusercontent.com/962095/237057119-f490fc33-c466-40aa-a559-d874d827e56b.png">

- [ ] use the same table layout as we used it in tokens page

**Comment by jayanand05** [comment]
working on it.

**Comment by jayanand05** [comment]
hi @IrakliJani , should i make this similar to User Management page because it looks very similar to that page?

**Comment by ho-dor** [comment]
@IrakliJani I see you have removed this from the milestone, is it available to work on ?

**Comment by hrutik7** [comment]
this issue not exist any more i think

**Comment by IrakliJani** [comment]
@ho-dor @hrutik7 this is still relevant, there has been slight changes with the layout but the project access list still needs to be migrated to mantine. let me know if you want to work on this ticket. thanks 🙌 

![CleanShot 2023-09-28 at 12 30 19@2x](https://github.com/lightdash/lightdash/assets/962095/e53fb49a-2681-4edf-811a-10f8f448e189)

**Comment by hrutik7** [comment]
yes ! I love to work on this

**Comment by IrakliJani** [comment]
great, assigned to you!
