### ISSUE TITLE
Migrate `Project settings > dbt Cloud` to use Mantine

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5406]
### Description

- [ ] migrate forms using mantine-form.
- [ ] use Card component as a wrapper

<img width="697" alt="CleanShot 2023-05-09 at 13 38 24@2x" src="https://user-images.githubusercontent.com/962095/237057414-99507baf-f8c0-4107-8bdf-9723658a3db6.png">

**Comment by jayanand05** [comment]
hey @IrakliJani, I have done some update using mantine in dbt cloud page it looks something like in the given image it's not finish yet still working on it, let me know wdyt?
![5E16912F-0170-4CEB-808D-381712AD7B43_1_201_a](https://github.com/lightdash/lightdash/assets/113882904/2017c97b-0060-43f0-bbb0-4f58362c5792)
