### ISSUE TITLE
Improve `Project settings > Scheduled deliveries` spacing

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5407]
### Description

- [ ] remove padding from the card container
- [ ] add spacing to the empty state
- [ ] table bounds are inconsistent across `all schedulers` and `run history`
- [ ] improve tooltip content spacing and font sizes
- [ ] edit button has too much space

<img width="719" alt="CleanShot 2023-05-09 at 13 40 48@2x" src="https://user-images.githubusercontent.com/962095/237058218-2802045c-91fe-41bc-8138-81a015fd84fc.png">

<img width="338" alt="CleanShot 2023-05-09 at 13 43 15@2x" src="https://user-images.githubusercontent.com/962095/237058726-dba49a0d-614c-4f77-ba02-20b1fb448772.png">

![CleanShot 2023-05-09 at 13 43 46@2x](https://user-images.githubusercontent.com/962095/237058868-6099caba-caab-4fc3-8682-20d193b66903.png)

**Comment by aggmoulik** [comment]
@IrakliJani Can you share the design for the changes, as font size and spacing need to be perfect for good ui

**Comment by IrakliJani** [comment]
closing in favour of https://github.com/lightdash/lightdash/issues/5369
