### ISSUE TITLE
The social login on the 'Sign Up' page asks the user to 'Sign In'

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5414]
<img width="440" alt="Screenshot 2023-05-09 at 14 05 35" src="https://github.com/lightdash/lightdash/assets/12776522/a0c624de-6b80-46c0-a152-f8478241453f">

This is misleading as I might think that this is the CTA for when I already have an account and need to Sign In. The button should read 'Sign Up with Google' instead.

**Comment by joaoviana** [comment]
Done on https://github.com/lightdash/lightdash/pull/5421, see screenshots for reference!
@PriPatel
