### ISSUE TITLE
Move settings from modal to new page

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#542]
The settings modal is getting busy and would work well on a new page, especially since project settings already redirect you to a settings page

You should also be able to link the project pages using the current url (enabling us to deep link to settings from around the app)

**Current**

<img width="776" alt="Screenshot 2021-10-05 at 10 35 58" src="https://user-images.githubusercontent.com/11660098/135998538-7324e1d8-001d-4536-aa44-169daae8dac3.png">

**After** 

1. Page looks similar to project settings (see below)
2. Add button in project settings to "go back" to all settings

<img width="1527" alt="Screenshot 2022-06-13 at 12 46 38" src="https://user-images.githubusercontent.com/11660098/173346851-7ecbe927-2548-497d-ac37-39ed30a03fb9.png">

**Comment by PriPatel** [comment]
This could potentially solve [#945] as we could add an anchor link to the 'Invite user' section.

**Comment by ZeRego** [comment]
Should we split this in 2 pages or sidebar sections ? User settings and Organization settings

**Comment by ZeRego** [comment]
User settings page: Profile, Password, Social Logins, Personal Tokens.
Organization settings page: Organization, user management, project management, appearance.
