### ISSUE TITLE
When I delete a pinned item, I expect it to disappear from the panel

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#5424]
### Description
When I delete an item from the pinned items panel, it hangs in the panel until the page is refreshed.
_Also, do we want to be able to delete items from the pinned items panel?_  Users might think `delete` means unpin.

https://github.com/lightdash/lightdash/assets/67699259/3d71b824-dcaf-4b4a-9ec0-8faeed5c7ed5

**Comment by PriPatel** [comment]
> Also, do we want to be able to delete items from the pinned items panel? Users might think delete means unpin.
Agree! Let's just have the context menu have one option - to unpin the item. This is a common pattern and means users won't accidentally delete things.
