### ISSUE TITLE
You can create attributes and assign users to them.

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5441]
### Description

You can add attributes and assign users to them. Only org admins can do this. These user attributes can be used to add metadata about users and can later be used to apply row/column based security based on their attributes.

Leads to many customisations in the UI/UX based on the current user

### UI

See Miro sketch: https://miro.com/app/board/uXjVM34fyak=/

- [ ] there is a new page in the `organization settings` called `user attributes`. 
- [ ] This page is only accessible to org. admins
- [ ] admins can create a new attribute by cliking on `add new attribute` button.
- [ ] When you create an attribute, you assign it a name (this must only be using [a-z_0-9] characters)
- [ ] Attributes can optionally have a description.
- [ ] If a user tries to name an attribute with anything but [a-z_0-9], they see an error message, and they are not able to save the attribute. (backend restriction with optional frontend validation)
- [ ] you're able to assign users to attributes and give them values for the attribute. 
- [ ] The attributes page lists all of the attributes and tells you:
    - [ ] the attribute description when you hover over the "info" icon
    - [ ] the number of users who have the attribute assigned to them in text below the entry
    - [ ] the option to edit + delete the attribute. 

### API

Each member has many attributes. Each attribute has:

- `name` - must be unique per member (so can't have two attributes with the same name). They can only use [a-z_]
- `value` - the value of the attribute. can be any string

Lets use UUID

```
### Show all attributes in the org (and users inheriting it?)
GET /org/attributes

### Create a specific attribute on the org (name or description)
POST /org/attributes

### Update the whole attribute payload
PUT /org/attributes/{uuid}
```

### Database

Add a new table for `user_attributes`

- primary key is a UUID
- another index on (orgUuid, name)
- has a description

Add a new table for `organization_member_user_attributes`

- foreign key to `organization_memberships`(orgId, userId)
- foreign key to `user_attributes` (orgId, attributeId)
- a value

### Out of scope

- Non-string attributes (number, date etc.) - in future we could support any dimension type
- attributes are user viewable / editable - in future admins could configure if a user can edit a particular attribute on their profile
- no groups, attributes must be directly assigned to a single user

### Analytics events

- [ ] user_attributes_page_viewed - event that's triggered when the user attribute page is viewed
    - organization_id
    - user_id
    - timestamp
- [ ] user_attribute_created - event that's triggered when a user attribute it created
    - user_id - user who created the attribute
    - organization_id
    - attribute_id - unique ID for the user attribute (unique across all orgs)
    - name - name of the attribute
    - description - description of the attribute
    - values -this is a json blob which has {`user_id`: [user_1, user_2, user_3, etc.], `value`: [value_for_user_1, value_for_user_2, etc.]}
- [ ] user_attribute_updated - event that's triggered when a user attribute is updated
    - user_id - user who updated the attribute
    - attribute_id - unique ID for the user attribute (unique across all orgs)
    - organization_id
    - name - name of the attribute
    - description - description of the attribute
    - values -this is a json blob which has {`user_id`: [user_1, user_2, user_3, etc.], `value`: [value_for_user_1, value_for_user_2, etc.]}
- [ ] user_attribute_deleted - event that's triggered when a user attribute is deleted  
    - user_id - user who deleted the attribute
    - attribute_id - unique ID for the user attribute (unique across all orgs)
    - organization_id

**Comment by ZeRego** [comment]
Adding attributes user by user is going to be painful. 
Does this feature overlap with user groups? Admins can create user groups with these attributes.

**Comment by owlas** [comment]
Yep I agree that groups will make this super powerful, and all users in the group would inherit the attributes.

That's a great next step! 

We could also have a list of allowed attributes like you mentioned @TuringLovesDeathMetal - i.e. you can't type any attribute name but only from a list of pre-created attributes.

I can add both to the milestone. I could even add groups 👀
