### ISSUE TITLE
Add ${ user.attributes.name } to liquid context in filters

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5443]
### Description

Allow users to use `${ user.attributes.name }` in filters and sql. Similar to how we do for the urls in dimensions: https://docs.lightdash.com/references/dimensions#liquid-templating

This should compile at run-time. we'll need to provide the user's attributes to the query compiler.

**Comment by TuringLovesDeathMetal** [comment]
@owlas I'm not too sure I understand this one. Could you give an example of where you'd use this + how it would work?

**Comment by TuringLovesDeathMetal** [comment]
ooooooh - I didn't get how it would filter anything, but now I do. It would basically say "only show rows where `username` = the user's name"

**Comment by jw-aleksandr-zolotukhin** [comment]
I'd add same comment as [here](https://github.com/lightdash/lightdash/issues/1243#issuecomment-1508136028). 
1243 issue is probably a duplicate of this one tbh.

tl,dr: custom sql expression based on user/group attributes would be necessary.

**Comment by owlas** [comment]
Added a comment to the other ticket for that @jw-aleksandr-zolotukhin !

**Comment by owlas** [comment]
Closing for #6350
