### ISSUE TITLE
Indicate if multiple selected filter values are joined with `and` or `or`

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#545]
### Context
Right now, if you have a single filter and you try to add more values to it (e.g. in the image below, I want to filter on multiple criteria for the organization name), it's unclear whether or not the filter logic is using `AND` or `OR` to join the filter criteria together.

Is the below `organization name is not equal to Jaffle Shop OR organization name is not equal to Lightdash`
or is it: `organization name is not equal to Jaffle Shop AND organization name is not equal to Lightdash`
![image](https://user-images.githubusercontent.com/31848148/136023153-7474d411-4e08-400c-9345-7310c65749cc.png)

### Goal
Have some way of indicating the filter logic to users in the UI

Suggestion: adding `and` or `or` to the left of the filter boxes
![image](https://user-images.githubusercontent.com/31848148/136023606-9579d521-942e-48fd-a020-2acf7dc21b7a.png)

**Comment by TuringLovesDeathMetal** [comment]
This is somewhat related to #188

**Comment by owlas** [comment]
@TuringLovesDeathMetal wondering if we should have a milestone for the filter logic, there's a few tickets related to it AND we need to overhaul some tech-debt to make many of the changes.

**Comment by TuringLovesDeathMetal** [comment]
@owlas @ZeRego - here's another UX feature that could be super tiny! (just adding `AND` or `OR`)
