### ISSUE TITLE
I want to know which dashboards my charts appear in

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5453]
### On Lists -> **TODO ⚠️**

- [x] The 'icon' should appear when you hover over the chart list component (like in this [prototype](https://www.figma.com/proto/btY2rdBe5I2W4xLR3upmQG/Untitled?type=design&node-id=661-37558&scaling=min-zoom&page-id=453%3A34864&starting-point-node-id=471%3A35284))  
- [x] Hover on the icon to see the popover
- [x] Remove the existing description that shows up when you hover over the chart name.

Copy over the component that has already been created over to chart lists that appear on:
- [x] The homepage
- [x] `All charts` page
- [x] Individual Space pages

-----
### [On the chart itself - Done](https://github.com/lightdash/lightdash/pull/6094) ✔︎
- [x] Update the icon to be Mantine 
- [x] On hover, it should show the same information as the previous tooltip - description and number of dashboards it appears in. 

Tooltip: 
Description: {description || 'N/A'}
Used in dashboards(length of dashboards): list of dashboards OR 'N/A'

**Comment by PriPatel** [comment]
<img width="351" alt="Screenshot 2023-06-07 at 13 51 54" src="https://github.com/lightdash/lightdash/assets/12776522/da06ea3e-7d21-4ee9-a688-8e18e0532cab">
<img width="354" alt="Screenshot 2023-06-07 at 13 51 57" src="https://github.com/lightdash/lightdash/assets/12776522/1b55b632-42fd-4c49-abbc-0946aa8170bc">

**Comment by joaoviana** [comment]
left to do: `On Lists`, on `ResourceViewList` component. See #6094 for hook used and reusable component
