### ISSUE TITLE
Update analytics events for `saved charts`

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5465]
### Description

- [ ] the `saved_chart_created`, `saved_chart_updated` and `saved_chart_deleted` events have `type`: `sql_runner` or `explore_view`

**Comment by rephus** [comment]
@TuringLovesDeathMetal  We use a new event for sql chats `sql_chart.created` and `sql_chart.updated` 

https://github.com/lightdash/lightdash/blob/main/packages/backend/src/services/SavedSqlService/SavedSqlService.ts#L231

Do they work for you ? or still want to use the `saved_chart_created` event

**Comment by joaoviana** [comment]
> Do they work for you ? or still want to use the saved_chart_created event

@TuringLovesDeathMetal confirms that yes, these would work!

**Comment by rephus** [comment]
Already done using sql_chart.created , sql_chart.updated and sql_chart.deleted tags
