### ISSUE TITLE
Hide the pinned panel when there are no items to pin

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5481]
<img width="889" alt="Screenshot 2023-05-12 at 18 03 04" src="https://github.com/lightdash/lightdash/assets/12776522/bab96f5f-35b9-4768-8296-1ca776c5a749">

There is nothing to pin here, so you shouldn't see the empty pinned panel.

**Comment by CVamsi27** [comment]
Hello, I would like to work in this.
