### ISSUE TITLE
Bug when trying to save a chart to a dashboard

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5482]
Submitted by user
> I think sometimes there is a bug when saving a chart to a dashboard, I have to click my desired dashboard twice from the drop down, otherwise it snaps back to the first dashboard in the list. This is sometimes a bit annoying as I have to go into the other dash and delete the tile

**Comment by TuringLovesDeathMetal** [comment]
This happens to me too _**all the time**_. It defaults to selecting teh first dashboard in the list so I always have to click twice. I think it might be loading the other dashboards or something?

**Comment by TuringLovesDeathMetal** [comment]
this has been fixed!
