### ISSUE TITLE
changing a saved chart, then sharing the link gives unexpected behaviour

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#549]
### Context
If I change something in a saved chart, then try to share the link without saving, it gives me the most recent version of the saved chart (instead of what's on my screen). 

I would have expected it to share what's on my screen. 

https://www.loom.com/share/380f9a55b0914a269043f4caf0e154d7

### Goal
When you change a saved chart, the link-sharing should work the way it does with a regular explore. _**or**_ it should be made really clear that it doesn't have the same behaviour.

**Comment by TuringLovesDeathMetal** [comment]
yes, sorry - that's what I meant.

> So the explore behaviour is identical to saved charts behaviour?

^This is what I'd want for the URL

**Comment by TuringLovesDeathMetal** [comment]
bumping this issue: I ran into it again today, this time coming from `edit saved chart` in the dashboard. 

A lot of exploring data comes from starting with a saved chart, then building on top of it. I'd want to be able to share the link that represents the new chart that I've made (built from the saved chart) without having to save it as a new saved chart.

**Comment by TuringLovesDeathMetal** [comment]
Again, running into this problem. Re-iterating what I said above: a lot of exploring data comes from starting with a saved chart. 

I don't want to have to create a new saved chart every time I want to share a quick analysis built from an existing saved chart (which is what you have to do now). 

Here's the current flow:
- There's some saved chart I want to explore from (e.g. I want to filter the number of weekly active users to some segment of users to try to debug something)
- I open the saved chart and add my new filters, etc. 
- I want to share my throwaway plot with someone else in the team. 
- I have to save the chart as a new chart and then share this saved chart with the other person 

So now, I have a saved chart that really isn't worthy of being saved (since it was just a throwaway analysis). 

Here's how it ideally would work:
- There's some saved chart I want to explore from (e.g. I want to filter the number of weekly active users to some segment of users to try to debug something)
- I open the saved chart and add my new filters, etc. 
- **The link updates with these new changes to the chart configuration**
- I want to share my throwaway plot with someone else in the team. 
- **I share the link with someone in my team** - the link _**isn't**_ connected to the saved plot in any way (e.g. the title isn't the saved plot title)
- They open the link and see the plot I was working on (exactly like they would with any other explore)

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal is this still relevant after we added the "Explore from" button ?

**Comment by TuringLovesDeathMetal** [comment]
No! As long as `explore from here` works as expected, then I think this would be solved :)

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego I think this was fixed when we fixed the explore from here, right? 

The only thing left is #https://github.com/lightdash/lightdash/issues/1876
