### ISSUE TITLE
Tables are missing border-top

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5495]
<img width="987" alt="Screenshot 2023-05-15 at 14 45 51" src="https://github.com/lightdash/lightdash/assets/12776522/0fd8da9c-29f6-49f1-8e9d-085ba6d443b6">

**Comment by CVamsi27** [comment]
Hello, I would like to work on this

**Comment by CVamsi27** [comment]
Hello @PriPatel,
I added the border-top to the header, should I also add border-bottom?
![image](https://github.com/lightdash/lightdash/assets/55316723/5db69ce1-202c-46b2-9585-ad77955e4b0e)
While scrolling down, border is missing. Is this expected?

I would like to submit a pull request.
