### ISSUE TITLE
Documentation about how to add google SSO 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5496]
Related ticket: https://github.com/lightdash/lightdash/issues/5210

![image](https://github.com/lightdash/lightdash/assets/1983672/ca0ae872-4b00-4c73-a259-61bdff6d48d3)

![image](https://github.com/lightdash/lightdash/assets/1983672/7e812810-84d6-4c45-818e-ef1d529415c2)

![image](https://github.com/lightdash/lightdash/assets/1983672/ecd907a5-be3a-499e-8120-2d828f99e8f8)

- `LIGHTDASH_URL/api/v1/oauth/redirect/google`
- the JS origin should be simply `LIGHTDASH_URL`

Where `LIGHTDASH_URL` can be `https://app.lightdash.cloud`

**Link to existing docs:** 

**Changes?**

**Comment by TuringLovesDeathMetal** [comment]
Closing as not planned
