### ISSUE TITLE
I'm not able to get a preview of my dashboard when I paste it into Slack

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5522]
<img width="740" alt="Screenshot 2023-05-17 at 16 11 19" src="https://github.com/lightdash/lightdash/assets/12776522/1ad48fa3-78c0-4a45-9cb6-a1ae608fa449">

It seems to work for charts.

**Comment by ZeRego** [comment]
Only failing for this specific dashboard. Error:

Unable to fetch screenshots from headless chrome Node has 0 height.

**Comment by PriPatel** [comment]
Seems to work now
