### ISSUE TITLE
`lightdash deploy` does not support dbt env vars with default values

### ISSUE THREAD

**Issue by adam-bloom** [lightdash/lightdash#5536]
### Description

We have a dbt profiles.yaml using `env_var` jinja functions with defaults (https://docs.getdbt.com/reference/dbt-jinja-functions/env_var). Env vars are able to be properly passed through to `lightdash deploy`, however, the default values for env vars do not come across, and those values are passed as NaN, which is causing issues.

As an example, here is a subset of our profiles.yaml:
```
      host: "{{ env_var('REDSHIFT_HOST', '') }}"
      port: "{{ env_var('REDSHIFT_PORT', 5439) | as_number }}"
```

Lightdash throws an error because it gets this:
```
{
    "host":"<hostname correctly defined and picked up>",
    "port":"NaN" <-- the default should be here
}
```

### App Version

0.551.1

**Comment by TuringLovesDeathMetal** [comment]
Thanks for opening this Adam! We'll take a look and see what we can do 👀

**Comment by ZeRego** [comment]
Fix required in `packages/cli/src/dbt/templating.ts` jinja global functions
