### ISSUE TITLE
Can we enable project interactive viewers to use SQL Runner?

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#5538]
### Description
We sometimes enable project interactive views to use SQL Runner. The idea behind this is we don't want them to create/edit charts, dashboards and related features as project developers. We give permissions to them so that they explore data with SQL statements. 

https://docs.lightdash.com/references/roles/#project-roles

### What problem does this solve?
We don't have to give project developer roles to persons who need to explore data without creating/editing chards and dashboards.

**Comment by TuringLovesDeathMetal** [comment]
Hey @yu-iskw 👋

Ooh interesting! 

How do you imagine these viewers would access the SQL runner? Would it just be from scratch, creating queries? Or would it be editing a chart's query? Also, what types of users are this? (E.g. finance team, engineers, etc.) I'm surprised that folks outside of the data team are so comfortable in SQL (I wish it was like that all the time! 😅)

**Comment by yu-iskw** [comment]
Hi @TuringLovesDeathMetal, 

I totally understand what you mean. So, I mainly want to enable software engineers to wrangle data with SQL on Lightdash. As we're a small startup and have thousands of tables across products, it is difficult for analytics engineers to completely add dimensions and metrics to models which should be modeled. Meanwhile, we don't want the software engineers to change saved charts and dashboards in spaces. 

Another idea to solve this is to create custom roles, as Google Cloud enables us to create custom roles with selected permissions. If it is not so difficult to realize the idea, that would be worthwhile providing the feature.

**Comment by yu-iskw** [comment]
Hi @TuringLovesDeathMetal what do you think of my opinion?

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. 

There's a wider change that needs to happen around being able to manage user access to individual actions in the app (e.g. access to the SQL runner) and this would fit within that ticket. 

I don't think interactive viewers should be able to access the SQL runner across all orgs.
