### ISSUE TITLE
Remove column and row totals for table calculations and metrics of certain types

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5540]
### Description

currently it seems the totals are in all cases SUM of values in the table. However, if the values in a metric are a count distinct, then having the total display a SUM instead of a count distinct can lead to confusion for end users.

E.g. my total users by month could be 10, 10, 10, 10, 10 for the months of Jan to May - in total that could be the same 10 users but currently in Lightdash the total would show 50 which would be misleading. I just got off a call where this was the kind of confusion a user was facing so wanted to report. 

### Acceptance criteria

- [ ] only apply `totals` to metrics that have: sum, count or number types
- [ ] don't show totals for metrics with average, count_distinct, average, median, percentile
- [ ] don't show totals for table calculations https://github.com/lightdash/lightdash/issues/5547

Eng Note: update the logic in `isSummable()`

**Comment by erikgregorywebb** [comment]
This is becoming a big source of confusion for our end-users. Please prioritize!
