### ISSUE TITLE
I want to be able to go to the chart or dashboard that has a validation error 

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#5544]
### Description

![image](https://github.com/lightdash/lightdash/assets/7611706/6eb9e97b-6bb2-4f4f-a300-aba4df3803f3)

Users can't click on a dashboard/chart in the validation error table. They should be able to click it and get redirected to the respective item.

### What problem does this solve?

Easy access to _problematic_ chart/dashboard that is affected by the error.

**Comment by TuringLovesDeathMetal** [comment]
ya, was just about to open this issue when playing around with the validator!
