### ISSUE TITLE
Hide column totals for table calculations

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5547]
### Description

In this issue we present a better way to handle table calculations column totals: https://github.com/lightdash/lightdash/issues/4067

But while we work on this it might be better to remove the column totals completely for table calculations, or give users the option of doing this since it can be confusing for users.

Community slack thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1684239528791709?thread_ts=1684230133.042719&cid=C03MG2VTR08

**Comment by CVamsi27** [comment]
Hello, I would like to work in this.
