### ISSUE TITLE
Cannot select multiple filter values with same text (but different case)

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#5551]
### Description

I expect to be able to select multiple filter values even when they have the same text but different cases.

e.g. if `lightdash` and `Lightdash` are both available filter dropdown options, it's impossible to select both. Upon the second selection, both selections are cleared. This applies for more than 2 results also. Sometimes, both are pre-selected.

### To Reproduce

Use a filter dropdown where the data contains multiple records which (case-insensitively) match.

### App Version

Latest

**Comment by muhsinkamil** [comment]
https://github.com/lightdash/lightdash/pull/5558 should solve this too 🤞
