### ISSUE TITLE
Big Number tiles that have comparisons enabled look different to normal tiles in Slack

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5590]
<img width="606" alt="Screenshot 2023-05-23 at 17 51 39" src="https://github.com/lightdash/lightdash/assets/12776522/5728fbaf-b68c-4436-9fa8-345e4d3128fa">

The font sizes look different in slack depending on whether a comparison has been enabled or not

- [ ] The comparison tile should look the same as a non-comparison tile

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal We're having trouble recreating this bug!
<img width="477" alt="Screenshot 2023-05-25 at 11 07 26" src="https://github.com/lightdash/lightdash/assets/12776522/ae2b5535-c37d-45c2-b2cb-6b95d6f836f3">

**Comment by yasmin-e** [comment]
Tested on **Analytics** and it's looking good!
@TuringLovesDeathMetal 

<img width="666" alt="Screenshot 2023-05-25 at 11 53 29" src="https://github.com/lightdash/lightdash/assets/67699259/a5856c5e-e063-4dcc-912f-7dacf55e0a90">
<img width="631" alt="Screenshot 2023-05-25 at 11 53 36" src="https://github.com/lightdash/lightdash/assets/67699259/ff99fde0-719f-4d1b-882a-d825b02584cf">
<img width="646" alt="Screenshot 2023-05-25 at 11 57 58" src="https://github.com/lightdash/lightdash/assets/67699259/6e403bd6-6b9b-4bc0-b79a-b3765bec1bbc">
<img width="635" alt="Screenshot 2023-05-25 at 11 58 04" src="https://github.com/lightdash/lightdash/assets/67699259/35ce8523-aac6-4ec0-8afc-c2e2780d9c6e">

**Comment by TuringLovesDeathMetal** [comment]
oh sweet! let's close it then :)
