### ISSUE TITLE
All spaces should be shown in a list view instead of a grid view

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5600]
### Description

Spaces have a lot of important information about them that we're not able to show right now in a grid view. Also, based on Cohere sessions there are some organizations with so many spaces that a grid view actually doesn't make sense. 

We should instead make the `all spaces` a list view (instead of a grid view)

### Acceptance criteria

- [ ] on the `all spaces` page, the spaces are shown as a list (instead of a grid)
- [ ] the list contains information about:
    - [ ] who created the space
    - [ ] when it was created
    - [ ] the number of charts + dashboards in the space
    - [ ] the permissions of the space 

### Questions

- can we improve the filtering/ordering of list items in this issue as well? Basically the header on a list of a bunch of items to make it more useful

**Comment by PriPatel** [comment]
Closing in favour of :
https://github.com/lightdash/lightdash/issues/6186

> can we improve the filtering/ordering of list items in this issue as well? Basically the header on a list of a bunch of items to make it more useful
- The content list milestone addresses this!
