### ISSUE TITLE
Dashboards should be listed in a space first, by default

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5601]
### Description

Right now, we show `all items` as the default tab in a space. Instead, we should have `dashboards` as default shown when you open a space. 

This is based on feedback from users that spaces are cluttered and normally the charts are just components of a dashboard and very rarely (if ever) navigated separately. 

<img width="497" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/4c13f3bb-ae8f-409c-aaf2-8186672776f4">

### Acceptance criteria

- [ ] There are three tabs when you open a space: `all dashboards`, `all saved charts`, `all items`
- [ ] The order is switched from today (dashboards first, then saved charts, then all items)
- [ ] By default, when you open a space, the `all dashboards` tab is shown first.

**Comment by PriPatel** [comment]
This is not ready to build as we need to think about empty states? what if a user has no dashboards and only charts? You might think something is broken during onboarding
