### ISSUE TITLE
Spaces have actions within their three-dot menu when they appear in a list [nested spaces]

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5608]
### Description

<img width="296" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/ce739f77-a179-477a-bb0c-90b15618214a">

- [ ] I can rename a space from the three-dot menu
- [ ] I can delete a space from the three-dot menu
- [ ] I can pin a space to the home page from the three-dot menu

- I cannot duplicate a space
- I cannot move a space

**Comment by lokesh3097** [comment]
Hey @TuringLovesDeathMetal

Is this issue still relevant now? If yes, can you give the steps to reproduce this as I am unable to reproduce the issue?
