### ISSUE TITLE
Use full text search to improve search bar

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5631]
## Problem

Our current search is based on using 

```sql
LOWER(name) LIKE LOWER('%query%')
OR
LOWER(description) LIKE LOWER('%query%')
```

This has the following problems:
- Punctuation has to be matched exactly
- Word order has to be matched exactly
- names and descriptions are equally important
- It's SLOW, because we don't index `lower()` we have to do a full table scan and `lower()` everything
- no ranking of results

## Solution

We can use Postgres' included full text search, this converts the the string into a vector of tokens that:
- removes punctuation
- removes "stop words" like "a" "an" "the" ...
- stems English words (I think we can only use one language at a time?) => ordering, orders, order *all match* "order"
- can be queried without order being important => active users *can match* "users are active"
- can weight the name more than the description!
- can rank results by how accurately they match

### migrations

Each resource (chart, dashboard, ...) that needs to be searched will need a new field added, the search field. This will include the tokenised version of chart that will be indexed. The index is _always_ up to date so we don't need to maintain the search index.

The following example for saved charts combines both the name and description field, but weights names as more relevant than descriptions:

```typescript
export async function up(knex: Knex): Promise<void> {
    if (await knex.schema.hasTable('saved_queries')) {
        await knex.schema.alterTable('saved_queries', (table) => {
            table.specificType(
                'search',
                `tsvector GENERATED ALWAYS AS (setweight(to_tsvector('english', name), 'A') || ' ' || setweight(to_tsvector('english', description), 'B') :: tsvector) STORED`,
            );
            table.index(['search'], 'saved_queries_search_index', 'GIN');
        });
    }
}

export async function down(knex: Knex): Promise<void> {
    if (await knex.schema.hasTable('saved_queries')) {
        await knex.schema.alterTable('saved_queries', (table) => {
            table.dropColumn('search');
            table.dropIndex('saved_queries_search_index');
        });
    }
}
```

### Querying

When querying we can use `websearch_to_tsquery` which makes the order of query terms not important but the user can use some symbols to control search.

On saved charts, this would and a where clause to filter the results and then rank them from most relevant to least relevant:

```typescript
            .andWhereRaw(`search @@ websearch_to_tsquery('english', ?)`, [
                query,
            ])
            .orderByRaw(
                `ts_rank(search, websearch_to_tsquery('english', ?)) DESC`,
                [query],
            );
```

to query this the user can type:

- `active users` - searches `active` and `users` in any order (matching name is better than description)
- `"active users"` - searches for `active` followed by `users` in that specific order
- `active or users` - searches for `active` or `users` only one needs to match, matching both is better
- `active -users` - searches for `active` and cannot have users at all

^ I don't think the operators are that important for our first use case but it comes for free and the `or` behaviour is useful.

### limiting results

We need a better way to limit results, full text search is likely to return more results than the current approach. Since we show results for different entities together (charts, dashboards, metrics), we'd probably need to decide on a max number to show in each category. So we'd only show up to 5 dashboards, then 5 charts, etc. Something to tune

### out of scope

we can't really index dimensions/metrics with this approach because they aren't stored in the database.

**Comment by almeidabbm** [comment]
I have removed the embedding commits from `search-v2` branch by rebasing interactively and created another branch to preserve the state of embedding for future use `search-v2-embedding`
