### ISSUE TITLE
UI improvements - Validator table

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5653]
**Problems**:
<img width="678" alt="Screenshot 2023-05-26 at 19 42 04" src="https://github.com/lightdash/lightdash/assets/12776522/eadb3cff-36fa-4e8e-b792-ba7e2c451371">
- The 'last updated by' column gets pretty squished
- The error itself is quite hard to digest
- The table in general is too small to fit everything we would like- https://github.com/lightdash/lightdash/issues/5652

**Proposal**
- [ ] Move 'last updated by' under item to give more space to display full names
- [ ] Add number of views 
- [ ] Split up the Error by category 'eg. `Metric error`' `Dimension error` `Missing chart`

<img width="868" alt="Screenshot 2023-05-26 at 19 54 44" src="https://github.com/lightdash/lightdash/assets/12776522/2cfad6eb-ae3a-4b1a-a22f-3c773cf837af">

**Comment by PriPatel** [comment]
Dimension error | field no longer exists
-- | --
Metric error | `field` no longer exists
Filter error | `field` no longer exists
Sorting error | `field` no longer exists
Broken chart | `chart name` is broken on this dashboard

**Comment by joaoviana** [comment]
Same (proposal 1 🎉 )! I can start working on this, but need to sync with @rephus on what best way to get the Error UI look like that

**Comment by joaoviana** [comment]
Implement better messaging for Table/Model errors as well

Users should be able to see what is the name of the Table that is throwing the error. 
Table errors that throw: 
* 'Model has no table relation' error
* Field at xxx errors (AjvError)
