### ISSUE TITLE
The update link for versions in Lightdash goes to a broken link

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#5661]
### Description

![image (4)](https://github.com/lightdash/lightdash/assets/14341285/363c53d6-dbf1-4d78-a03e-a69cba018691)

**Comment by hamzahc1** [comment]
🤔 https://lightdash-community.slack.com/archives/C03MG2VTR08/p1685372496202369

**Comment by rephus** [comment]
mmm, ok, yes the version was 0.457 while the new version in prod was 0.579, so this deployment was 122 versions behind. And I know we have recently organized some docs, so this old version was probably pointing to an old doc it doesn't exist anymore. I don't think there is anything we can do anymore, and there is not easy way to prevent this from happening (it will not happen very often though)
