### ISSUE TITLE
Upgrade dbt on Lightdash server to 1.5

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5668]
### Description

Upgrade dbt on the lightdash server to 1.5

This will break any existing lightdash projects that have a `packages.yml` listing a dependency that doesn't support dbt 1.5. This happens commonly because users pin their packages in `packages.yml`.

### (optional) - make project version configurable

We could install multiple versions of dbt on the server and allow the user to specify a version.

This could be achieved by:
- installing multiple dbt versions with python virtual environments
- adding an option to the UI to select the project version (although this only matters when hitting "refresh dbt" not when doing lightdash deploy).
- when executing dbt commands, target the correct dbt version

**Comment by ZeRego** [comment]
Details on how we can support multiple dbt versions in https://github.com/lightdash/lightdash/issues/5109
