### ISSUE TITLE
Open in Lightdash CTA on scheduled deliveries doesn't redirect to the chart/dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5672]
### Description

When I click on the Open in Lightdash CTA on  a scheduled delivery in slack and I have to log in, I'm not taken straight to the chart/dashboard as expected. It just takes me to the homepage.

**Comment by PriPatel** [comment]
Symptom of https://github.com/lightdash/lightdash/issues/4655
