### ISSUE TITLE
`Allowed email domains` UI bug

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#5692]
### Description

<img width="872" alt="Screenshot 2023-05-31 at 12 17 59" src="https://github.com/lightdash/lightdash/assets/67699259/e9437762-a78b-42ac-8e7f-60d8459bbc66">

### App Version
Version: v0.583.0

**Comment by siddarthkay** [comment]
Hi @yasmin-e : If you can elaborate a bit more I would love to take a stab at fixing this issue 👍🏻

**Comment by yasmin-e** [comment]
Hi @siddarthkay, basically when you go to `Settings > Allowed email domains`, enter a domain and then try to select a role from the dropdown, part of the dropdown is hidden. Here's a video:

https://github.com/lightdash/lightdash/assets/67699259/54cfb65f-d448-45b7-83f3-fd602a793058

**Comment by siddarthkay** [comment]
Hi @yasmin-e : great! Thanks for explaining, could you please assign the issue to me?

**Comment by yasmin-e** [comment]
Hi @siddarthkay, actually I have a PR that fixes this bug! Thanks anyway 💟
