### ISSUE TITLE
Provide default options for GitHub

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#570]
We could provide defaults for GitHub such as:

* dbt project root: `/`
* branch: `main`

<img width="892" alt="Screenshot 2021-10-10 at 11 50 00" src="https://user-images.githubusercontent.com/11660098/136692490-bcf7e317-9f66-46a2-a4a3-0bb3b3e71c2e.png">

**Comment by TuringLovesDeathMetal** [comment]
Closed because this has already been implemented
