### ISSUE TITLE
Change position of the close button.

### ISSUE THREAD

**Issue by Krishna2323** [lightdash/lightdash#5705]
Issue: The close button is kind of mixed with the terminal and its harder for a new user to find at first.

Fix: Move the button to the top bar.

<img width="1710" alt="issue-1-lightdash" src="https://github.com/lightdash/lightdash/assets/85894871/5a08f1f0-e6dd-4b17-a91c-9be327d2dbe5">

**Comment by ZeRego** [comment]
Hi @Krishna2323 👋 
This component is from an external library `react-query/devtools` and is rendered in App.tsx `<ReactQueryDevtools initialIsOpen={false} />` 
We are open to contributions if you find a fix for it.

**Comment by Krishna2323** [comment]
thanks for the help @ZeRego, I couldn't find any fix for this issue, the only thing we can do is add little box shadow and could change the background color of the button.

**Comment by Krishna2323** [comment]
can I work on this?
https://github.com/lightdash/lightdash/issues/5719
