### ISSUE TITLE
X-axis labels are missing when there are long label names

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#571]
### Context:
Sometimes, if the x-axis includes multiple string labels that are quite long, our charts remove the labels from the x-axis . 

You can still see teh labels on hover. But, if you were to try to include this graph in any analyses or screenshots anywhere, you'd be missing information on the values of the graph.
![image](https://user-images.githubusercontent.com/31848148/136760267-ddd22dad-e7ce-4642-aea1-e853377bf256.png)

([here's the link to teh graph](https://lightdash-analytics.lightdash.com/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/tables/base_api_error?dimensions=base_api_error_name%2Cbase_api_error_status_code&metrics=base_api_error_count_distinct_api_errors&sort=%5B%7B%22fieldId%22%3A%22base_api_error_count_distinct_api_errors%22%2C%22descending%22%3Atrue%7D%5D&limit=500&column_order=base_api_error_name%2Cbase_api_error_status_code%2Cbase_api_error_count_distinct_api_errors))

### Goal:

You should be able to include all of the x-axis labels on a graph.

**Comment by owlas** [comment]
We should be able to customise this.

@TuringLovesDeathMetal what would be your preference if there isn't enough room for the labels? We could
* rotate them (but that would happen for all charts)
* accept that they may overlap
* current behaviour: drop some
*

**Comment by TuringLovesDeathMetal** [comment]
@owlas I would vote for rotating them. 

If we did this, and I made my chart super big, to the point where the labels no longer overlapped if they were horizontal, would the chart automatically reset the labels so that they're horizontal? (basically, it would dynamically rotate based off of the space)

**Comment by TuringLovesDeathMetal** [comment]
@owlas did this get fixed? 

it's still happening in this plot: 
![image](https://user-images.githubusercontent.com/31848148/145614621-3e780b9f-cd18-4925-b452-11395a8f62b4.png)

https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/tables/funnel_starting_from_cloud_signup?dimensions=funnel_starting_from_cloud_signup_step_name%2Cfunnel_starting_from_cloud_signup_readable_name&metrics=funnel_starting_from_cloud_signup_organization_count&sort=%5B%7B%22fieldId%22%3A%22funnel_starting_from_cloud_signup_step_name%22%2C%22descending%22%3Afalse%7D%5D&limit=500&column_order=funnel_starting_from_cloud_signup_step_name%2Cfunnel_starting_from_cloud_signup_readable_name%2Cfunnel_starting_from_cloud_signup_organization_count

**Comment by rephus** [comment]
@owlas :point_up: ? I'm happy to take a look if you don't know what's wrong with the fix you made

**Comment by owlas** [comment]
@rephus @TuringLovesDeathMetal the current solution we have for this is to show the name on hover. I'm not sure what the perfect solution is. Some options:
- Rotate labels
- Make chart scrollable? 
- Truncate labels

If labels are too long to fit the width of the plot there is little we can do. I'm not sure if this is actually still a bug?

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this and open it for a feature request instead for rotating the axis labels!

**Comment by TuringLovesDeathMetal** [comment]
New issue here: https://github.com/lightdash/lightdash/issues/2028
