### ISSUE TITLE
Filters general: Add `is complete` to date filters

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#572]
### Context
When you're plotting/grouping data by dates, weeks, months, etc. sometimes your plots look weird because the last data point is not a "full set" of dates. 

E.g. if I plot `total new signups` by `week`, and I look at the chart on a Tuesday, the last `week` data point will be skewed (because it will only include the first two days of the week, not an entire week of data). 

### Goal
You should be able to filter dates to only include data points where the date range is "complete".

**Comment by owlas** [comment]
Still relevant.

Other open filters issues:

#920 #333 #205 #207 #186 #188

**Comment by owlas** [comment]
@TuringLovesDeathMetal do you have an example of somewhere you've seen this implemented that you liked? I haven't had experience with a BI tool that exposes something like this!

**Comment by owlas** [comment]
@TuringLovesDeathMetal is this a combination of #188 and #205 ?

Let's say you want to group by year but not include the currently unfinished 2022,  you would add filters:

* Dimension: year
* Metric: any metric
* Filter: in the past 10 years
* Filter: before this year

Or:
* Filter: before this year
* Sort: by year
* Limit: 10 rows only

Or is there something else needed?

**Comment by TuringLovesDeathMetal** [comment]
@owlas I think it's kind of a combination? Here's two examples of where I'd use this:

**Example 1**:
Let's say I wanted to compare the % change in number of weekly active organizations month-on-month **any time on or after September, 2021.** 
I'd get an explore and my results table would look something like: 
![image](https://user-images.githubusercontent.com/31848148/150828371-9e3026d2-6e35-4f39-8dbe-18072bfc235d.png)

Now, the last row is looking at an incomplete month. So, I would want to remove this data from my plot because the results are skewed/not comparable to the other three entries.

There are two ways to do this:
1. limit my visualization to the first 3 rows only (and update this every month to increase the row count by 1 in the visualization...not so great)
2. filter my data to only include "completed months" (very nice)

So, if I went with option 2, my filters would now be:
- date Month `is on or after` September 2021
AND
- date Month `is complete`

And now my results table would look like this:
![image](https://user-images.githubusercontent.com/31848148/150829217-b76c697c-edd2-4406-a3e3-6b2afbbec11d.png)


**Example 2**
Let's use the exact same example as above, except now I'm just looking at data where `date Month is in the past 3 months`.

If I had no `is complete` filter, we'd get a table like this:
![image](https://user-images.githubusercontent.com/31848148/150828943-897aa38d-9a91-4985-9202-8529dce88938.png)

Again, the last row is whack because it's comparing an incomplete month to a full month. Again, I'd want to remove this data from my plot. 

The filter options here would be a bit different. You'd be able to do this one in a single filter option: 
- date Month `is in the past` 3 `complete months`

^so for the `in the past` filter, you'd have timeframe options of `days`, `weeks`, `complete weeks`, `months`, `complete months`, etc.

-----

And that's it! Does that make sense? (I'll also add this to the `in the past` filter ticket...)

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal Great examples! This really helped me understand the problem.
I think the second option is the most intuitive and simplifies implementation.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego glad to hear it 😊 

Just to be double sure, when you say "the second option", do you mean:

- adding `is complete` as a filter
- also adding `complete months`, `complete weeks`, etc. to the `is in the past` date filters

**Comment by ZeRego** [comment]
No, I don't like the `is complete` as an independent filter since there will be multiple edge cases. E.g raw dates and non standard time intervals. 
I was talking about as having this as part of the 'in the past' filter

**Comment by TuringLovesDeathMetal** [comment]
sure, sounds good. The `in the past` one is the most important. 

If the other one gets requested, we can implement it later :)

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego it's beautiful! 😍 

This is exactly what I was imagining :) (I can't imagine how much of a SQL pro you must be now...figuring out all of these weird and wonderful SQL compilations 😅 )
