### ISSUE TITLE
I wish I could see the chart type in the `add charts` modal in a dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5767]
### Description

When I'm adding tiles to a dashboard, if things are named similarly it can be hard to figure out which chart is which. One thing that would help with this is actually having the chart type icon in the modal (the same way we do in search).

<img width="516" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/e1bfb4e3-b502-4fb6-b812-8eb67b482ed7"> 

### Acceptance criteria

- [ ] When I add charts to my dashboard, I can see the chart type in the list of results.

**Comment by yasmin-e** [comment]
⚠️⚠️  We need to add `ChartConfig` property to `useChartSummaries`, this way we can apply `getChartType()` method on the charts and show the corresponding icon.

**Comment by joaoviana** [comment]
This is done now with after: https://github.com/lightdash/lightdash/pull/10758
With the `v2` endpoint for `/content` we can get the `chartKind`!
