### ISSUE TITLE
The actions/filters button overlays need to be decoupled from the dashboard title

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5773]
**Investigated**
- Both title and action menu live inside `HeaderContainer` in `TileBase`
- In the case where a user created a `Markdown tile` with **no title**,  we would like to be able to  remove the height from `HeaderContainer` to avoid the empty space, but by doing so we make the `action menu` unclickable

<img width="610" alt="Screenshot 2023-06-06 at 11 00 37" src="https://github.com/lightdash/lightdash/assets/12776522/ff1e09e9-b22c-4d99-9d40-cabc11ca899e">

This is causing issue : https://github.com/lightdash/lightdash/issues/3174

**Comment by joaoviana** [comment]
done here: https://github.com/lightdash/lightdash/pull/6535
