### ISSUE TITLE
Migration issue on codespaces 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5786]
### Description

when running yarn install
![image](https://github.com/lightdash/lightdash/assets/1983672/2cbb7f21-c716-4702-b713-734c73813de4)

when running migrate 
![image](https://github.com/lightdash/lightdash/assets/1983672/d083dd79-d755-4d18-83c1-c9f775466d2b)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - it hasn't been reported again in the last 6 months. Will reopen if it becomes an issue again!
