### ISSUE TITLE
Column totals should work for all of our default metric types

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5790]
### Description

We have removed the totals for metric types of average and count_distinct since they don't actually make sense as just a sum of hte values 

Instead, the column totals should match the metric calculation. 

### Things to consider

Right now, we calculate totals in the frontend. 
This works for sums. But for averages and count_distinct, we need to know the underlying values to be able to calculate the totals. We might need to move totals to be calculated in the actual query. I'm not sure how we would do this (because I don't know how we'd join it back to the results table after). Maybe we run a query in the backend, and then use it to build hte results table? 

For example, the total [for this `count distinct` metric](https://analytics.lightdash.cloud/projects/d4a98e19-d9a3-4bed-8e7b-c07af3e42686/tables/orders?create_saved_chart_version=%7B%22tableName%22%3A%22orders%22%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22orders_order_date_week%22%5D%2C%22metrics%22%3A%5B%22orders_unique_order_count%22%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22orders_order_date_week%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%5D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22orders_order_date_week%22%2C%22orders_unique_order_count%22%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22orders_order_date_week%22%2C%22yField%22%3A%5B%22orders_unique_order_count%22%5D%7D%2C%22eChartsConfig%22%3A%7B%22series%22%3A%5B%7B%22type%22%3A%22bar%22%2C%22yAxisIndex%22%3A0%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22orders_unique_order_count%22%7D%7D%7D%5D%7D%7D%7D%7D) should be calculated, like this:

```
SELECT
COUNT(DISTINCT("orders".order_id)
FROM TESTING.jaffle_ship.orders AS "orders"
-- note: if there were any filters, they would still be included here - EXCEPT metric filters. These wouldn't be applied.
```

- if there's a limit, it is not applied to the metric total. 

### Acceptance criteria:

- [ ] This should happen for average, count distinct, and median.
- [ ] For max and min, we should be able to calculate this in the frontend (it should just be `MAX(max groups)`)
- [ ] Totals should still not appear for `string`, `number`, `percentile`,  `boolean` or `date` metric types
- [ ] We need to make sure that we have metrics for how slow this makes loading explores with these new totals!!!! ⭐

**Comment by TuringLovesDeathMetal** [comment]
related to #4067

**Comment by pinkbaka** [comment]
❤️

**Comment by ZeRego** [comment]
Note that this feature is behind a feature flag while we test more and fix any edge cases.
