### ISSUE TITLE
Include filters in the dashboard URLS 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5817]
In Lightdash, if I'm on a dashboard and change the filters, neither the URL nor the link button update when filters have been changed. This means there is no way to filter a dashboard and then share that filtered view with someone. 

- This would enable sharing and bookmarking
- It means I could create one dashboard, and create 5 'versions' of it by using different filters and saving the links. (eg. One URL has a `UK` filter applied, another URL has a `US` filter applied. These links would be generated off a single dashboard) 

Note : This could be a crossover of: 
https://github.com/lightdash/lightdash/issues/4994

**Comment by TuringLovesDeathMetal** [comment]
Note: I think this only happens when youre updating an existing filter, not creating a new one

**Comment by yasmin-e** [comment]
> Note: I think this only happens when youre updating an existing filter, not creating a new one

^ That's right! When adding temporary filters (not in edit mode) to a dashboard, the URL updates with the applied filters in real time.
https://www.loom.com/share/99ac2cd4fa3845ad9dbc0c6b68ea640a?sid=d9e7e913-2f8e-4072-8877-cebd5d5a315f

However, when editing an existing filter on a dashboard, the URL does not update.
@PriPatel @TuringLovesDeathMetal we want it to update in this case too, right?

**Comment by PriPatel** [comment]
@yasmin-e  Lets leave it as all filters in view mode for now! 

That would help the users experiecing the problem for now. We might need to think a bit more about what it means to update the URL in edit mode - we already don't show the Link button in edit mode. Could this get confusing etc? 
Thankssss

**Comment by TuringLovesDeathMetal** [comment]
Here's an example of the bug: https://www.loom.com/share/311dfde5be65447780aad5921e4cea57

**Comment by yasmin-e** [comment]
Hi @stellar-geoff, thank you for the feedback ! 🙌🏼 
I do have a follow up question:

Can you confirm that despite the URL not being verbose about the changes, the filters are being updated adequately?

I investigated and this is what I get:
- I have a saved filter on the dashboard, the URL has filters params 
- If I copy my URL and open it in a new or incognito tab, my filters appear
- If I change the value of my filters, the URL seems to stay the same
- If I copy this URL after updating my filters and open it in a new tab, my filters are updated

So, essentially, the behaviour is the expected one, I just don't see the values written out explicitly in the URL.

**Comment by yasmin-e** [comment]
Hey @stellar-geoff, worked on a fix this afternoon 👍🏼 
Will be merged soon and released to Cloud tomorrow.
Thank you for your valuable feedback 🙌🏼 ⚡

**Comment by stellar-geoff** [comment]
@yasmin-e awesome! thanks so much for the quick work
