### ISSUE TITLE
Dashboard UI: Create new dashboard

### ISSUE THREAD

**Issue by jaybe78** [lightdash/lightdash#582]
<img width="191" alt="Screenshot 2021-10-11 at 16 55 10" src="https://user-images.githubusercontent.com/3605098/136820283-cb0d304d-1997-4bed-a493-2d6757ef6437.png">

- Add a button "Create new dashboard"
- Create popup allowing to submit dashboard name

**Comment by owlas** [comment]
@ZeRego I believe this is done, the project doesn't auto close issues when we move them to done :(
