### ISSUE TITLE
The validator should say when it was last run, even if there are no errors.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5827]
### Description

The validator doesn't say when the last validation was run when there are no errors. 

The timestamp should still be there, even if there are no errors. 

<img width="988" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/8eb23fd3-078d-4832-94f6-9ef0fbd29fc6">

**Comment by rephus** [comment]
We don't currently store "Validation runs", so we can't display this info.  perhaps we should build a table with validation summaries..
