### ISSUE TITLE
Ability to zoom in on charts

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#5830]
### Description

I would like to be able to zoom in on charts.

From a user:
> Often looking at some graph you find that some particular point is interesting, like the first days/hours of some graph that has months of data already. Or some graphs that decay near zero and you want to zoom on that late development. We use Dash for our more handcrafted visualizations, it uses Plotly as the charting lib. And I really like the zoom in that (see example [here](https://dash.gallery/dash-peaky-finders/isone?_gl=1*1nzlrh3*_ga*MTQ5Mzg5ODExNS4xNjgwMjQ3NTY1*_ga_6G7EE0JNSC*MTY4NjI5MjAzOS40LjEuMTY4NjI5MjA1NS4wLjAuMA)

Another example (via @owlas)

> There are some examples here under “DataZoom” that show what we could build. it’s quite different from the plotly chart UX
https://echarts.apache.org/examples/en/index.html#chart-type-dataset

### What problem does this solve?

This improve the convenience of analysing data and allows for more detailed insights.

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned. 

To accomplish this today, you can use filtering. We've also implemented `date zoom` which lets you zoom in/out on granularity. Will reopen if this is requested again!
