### ISSUE TITLE
Increase the column width of 'Last delivery start' 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5842]
<img width="326" alt="Screenshot 2023-06-09 at 13 09 43" src="https://github.com/lightdash/lightdash/assets/12776522/797ae165-173c-4f69-a313-3c4261daa67b">

The column should be able to accommodate the following onto one line if possible. We can decrease the space between other columns to allow for this!
<img width="159" alt="Screenshot 2023-06-09 at 14 55 23" src="https://github.com/lightdash/lightdash/assets/12776522/e5609b4e-f388-4d0c-8b9c-84ec8549bc41">

**Comment by yasmin-e** [comment]
fixed by #5841
