### ISSUE TITLE
I want to add multi-level groups to my table group labels

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5868]
### Description

I want to be able to add sub-groups to my table group labels. For example, I could have the group `sales` then a subgroup `emea sales`

It would look something like:

```
models:
  name: sales_emea_model
    meta:
      group_label: sales/emea
```

This would put my sales_emea_model in the sidebar like this:

```
> Sales
  > EMEA
    - sales_emea_model
```

### Acceptance criteria
- [ ] I'm able to have up to 4 sub-groups in my table group labels
- [ ] to create a sub-group in my table groups, I would just need to specify this in my `group_label` (suggested syntax: `group_1/sub_group`)
- [ ] The sub-groups appear in the sidebar nested in the groups
- [ ] The sub groups are ordered alphabetically within a group. 
- [ ] Any tables in the parent group that aren'y in a sub-group are placed below the grouped tables list. 

For example:

```
V Sales
  >EMEA
  > NA
  - my_ungrouped_table
  - z_my_ungrouped_table
```

### Documentation
- [ ] update the docs on groups to include information on how to build subgroups

**Comment by yu-iskw** [comment]
+1

**Comment by okiyuki99** [comment]
+1

**Comment by thiagocroce** [comment]
+1 on this feature, combined with [this related issue](https://github.com/lightdash/lightdash/issues/3593)

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/2686
