### ISSUE TITLE
Special chars not showing correctly in Excel

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#5885]
### Description

> Some of the field values are null in the explore - so in the CSV I’d expect these to just be null/blank cells, but instead it’s formatting `‚àÖ` inside these cells.

Excel doesn't display correctly special chars from exported CSV.
The cell displays correctly when opened in the mac application `Numbers` and in a text editor.

### To Reproduce

Steps:
1. Run query where results have special chars
2. Click on'export CSV'
3. open in Excel

![Screenshot 2023-06-13 at 15 21 21](https://github.com/lightdash/lightdash/assets/9117144/19616fe0-932c-412b-bdb3-5e88db979d32)

Expected the last cell to display `Авиабилет Tλληνικ ∅`

### App Version

0.602.0

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned - it hasn't been flagged by any other users, and we can always reopen it if it becomes an issue again!
