### ISSUE TITLE
Hide unavailable models for explore by default

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#5886]
### Description
Lightdash shows unavailable models on the UI for explore. We can also select models to deploy to Lightdash using the model selection of dbt. But, it would be good to hide unavailable ones by default. Alternatively, we can also add a button or something like that to reveal unavailable models.

![image](https://github.com/lightdash/lightdash/assets/1523515/41c2c967-6084-4757-983f-c1330363b452)

### What problem does this solve?
Even if we roughly select models which contains unavailable ones to lightdash, we can keep the list of models for explore clean.

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned! There is a bunch of work going into reorganizing the Explore tables sidebar, so this has been considered in that redesign :)
