### ISSUE TITLE
Audit log of changes to a chart or dashboard

### ISSUE THREAD

**Issue by raags** [lightdash/lightdash#5888]
### Description

As anyone can make changes to a dashboard or chart, it'll be helpful to get log of these changes made, along with who made those changes. A additional functionality could be to revert changes back to a previous state.

### What problem does this solve?

Dashboard and charts can be edited and changed by multiple team members. Having an ability to have a log of this changes is helpful to identify broken or incorrect charts / dashboard. It also helps to know if any recent changes have been made, by whome, and the purpose of the change.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of chart and dashboard version history!

Chart history exists (more details here: https://docs.lightdash.com/guides/version-history)
dashboard version history is still an open ticket: https://github.com/lightdash/lightdash/issues/5236
