### ISSUE TITLE
Data dictionary of sorts to search and explore available tables, dimentions and measures

### ISSUE THREAD

**Issue by raags** [lightdash/lightdash#5889]
### Description

The "Query from Tables" screen is a great way to start exploring or building new charts. However, if there are large number of such tables it might be hard to understand which one to chose based on the problem being solved - more so when its ambiguous.

An exploration of all the available metrics + their defiintions would be helpful to understand where to start, plus could serve as a reference when checking for the meaning of a particular metric (without knowing which tables its part of).

### What problem does this solve?

It allows to build an undertanding and familiarty of the data and business model, without going outside lightdash (e.g. dbt docs, but its too technical, or other data discovery tools, which are too verbose imo)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as a duplicate of the data catalog work (this is planned to be released very soon!) 

https://github.com/lightdash/lightdash/milestone/148
