### ISSUE TITLE
relation does not exist intermitent error

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5897]
### Description

![image](https://github.com/lightdash/lightdash/assets/1983672/2f7d3e82-fa6d-4f4d-8a8c-520a18cdeeb4)

Someone got this intermitent error when browsing a chart in particular. We think this is happening on cloud only, each pod had a different project adaptor in memory, when a user changes their project connection, we don’t clear the memory in all instances.

More in this thread https://lightdash.slack.com/archives/C05CDRZ3Y73/p1686752149625869

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - it hasn't been raised again since it was first opened in 2023. I believe it's been resolved and can be reopened if needed!
