### ISSUE TITLE
A metric can be defined using free-text SQL

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#59]
Currently, metrics are limited to using one of the (predefined types we have available)[https://docsite.onrender.com/references/metrics#metric-types].

For us to be able to do more complex aggregations (and not have a bajillion pre-defined metric types), users should be able to write custom SQL aggregations to define metrics.

E.g. you'd be able to build the metric for 7d rolling average number of weekly active users

**Comment by owlas** [comment]
I was thinking about this over the weekend! 

One thing I'm wondering, do we get any benefit on the UI by knowing the type of aggregation used to build a metric? If not, we could throw away the idea of pre-defined metrics already. This would stick with the approach of being "as close to sql as possible" for defining metrics.

Currently, there aren't any UI components that check the type of aggregation, only the data type of the metric (e.g. numeric vs. date).

**Comment by TuringLovesDeathMetal** [comment]
interesting thought....
> do we get any benefit on the UI by knowing the type of aggregation used to build a metric?

I think for things like means, we could give users the error bars for each point.

I also think that having these "out of the box metrics" makes it quicker to write the metrics in the .yml file. I'd imagine eventually we'd have things like "variance" or "std. error" included in the out-of-the-box metrics so that you actually wouldn't have to try to remember teh SQL to do this stuff...

What do you think??

**Comment by TuringLovesDeathMetal** [comment]
I'm actually thinking about this some more...and the only metrics you can't build after you've implemented this: https://github.com/lightdash/lightdash/issues/58

Are ones with window functions...(I think)

I feel like this is a feature that people will request though, since it can sometimes be way more complicated to wrestle with pre-defined metrics than trying to just write the SQL yourself...especially at the beginning when we have quite a limited set of "types"

Ugh, I don't know about this one

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal  For #58 I introduced non-aggregate metric types (string, number, date, boolean) where the user can define whatever sql they want to run + we can reference other metrics.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego, let's consider this one as completed for now. 

I still think we need to build something to replace `table calculations` in Looker, but I need to think about this some more and figure out how this could work in lightdash/if we want to force users to work further up the pipeline to build metrics. :) 

Have you added the non-aggregate metric types to the docs?? 

If not, I'll create a new ticket for that!

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal  Yes we updated docs but we haven't made a release yet with these changes.

Preview:
![Screenshot 2021-07-05 at 09 41 13](https://user-images.githubusercontent.com/9117144/124443036-3c72ca00-dd75-11eb-825a-84ec97b139ee.png)

**Comment by TuringLovesDeathMetal** [comment]
amaaaaaaazing <3 looks fab!

**Comment by owlas** [comment]
Closed by #159
