### ISSUE TITLE
Chart x-axis isn't sorted

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#590]
If I sort a date from most recent to least recent date, the chart is also ordered with the most recent date on the left.

This was unexpected because usually time-series charts go from left (the least recent date) to right (the most recent date)

<img width="1496" alt="Screenshot 2021-10-12 at 11 59 36" src="https://user-images.githubusercontent.com/11660098/136943787-9fcb6a05-862e-488f-a576-da38e1c0d831.png">

**Comment by ZeRego** [comment]
Closed by https://github.com/lightdash/lightdash/pull/720
