### ISSUE TITLE
I want to be able to paginate dashboards

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#5934]
For particularly large dashboards, as an alternative to scrolling, I would like to be able to split charts into pages within the same dashboard, and for the queries to only run when a given page is opened.

The reason for this is that, if everything is on one page, every query on that dashboard runs every time that dashboard is opened. This can get expensive.

An example use case for this would be a company core KPI dashboard, which contains key metrics (maybe 10-20 in total) from various parts of the business. These probably won't all fit on a single page without scrolling, and most likely it will require a lot of queries to populate the dashboard (e.g. each metric might actually have 3 queries if you're also showing things like MoM/YoY growth or % vs target alongside a line graph). Rather than having people scroll down to see everything, I would prefer to organise different sections into pages.

There is an existing workaround for this, which is to create the pages as individual dashboards, then include markdown tiles at the bottom of each, with links to the other "pages", but that's a slightly clunky way of doing things.

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this in favour of #3208 

I think they're the same idea. 

I'll add info about the queries only being run when the tab is opened though!

**Comment by mhawkins-runa** [comment]
Ah, yes - same thing, thanks. Sorry, had a look around but didn't find that
one initially.
