### ISSUE TITLE
Resolve github actions seed conflict

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#5943]
### Description

At the moment the actions `CLI tests for DBT 1.3` and `CLI tests for DBT 1.5` run in parallel and both seed the database. 
Is common for one of them to fail because of it. 

There are a few options on how to fix this:
- wait for one action to finish before starting the other one
- merge both tests under the same action

**Comment by patricktrainer** [comment]
Hey @ZeRego - happy to take a stab at this.

The way I see solving for your first point would to be to add a `needs` key to the last job. This would add time to testing, but if thats alright, then I think this is the most straightforward approach. 

On the other hand, to address the main issue

> run in parallel and both seed the database.

im wondering if the test are clobbering each other; considering theyre both pointed at [db and user](https://github.com/lightdash/lightdash/blob/3a96950c294e879ce750fd86d57f96d898e05e57/.github/workflows/cli-test-1.5.yml#L48-L49). I imagine using a seperate db and user for each test would allow you to run in parallel. Though youd need to maintain two dbt profiles as well. So may be more confusing than necessary. 

Thoughts?

**Comment by ZeRego** [comment]
@patricktrainer I agree that using different db would be overkill but we could easily point them to different schemas!💡 

We would need to:

1. change `https://github.com/lightdash/lightdash/blob/main/examples/full-jaffle-shop-demo/profiles/profiles.yml` to
 ```
 schema: "{{ env_var('SEED_SCHEMA', 'jaffle') }}"
 ```
 
2. in the github actions, set `SEED_SCHEMA` to something unique (eg: jaffle_1_3 and jaffle_1_5 ) 

3. pass the new env var to all the commands in `packages/e2e/cypress/cli/cli.cy.ts` 


Let me know if you want to work on this, otherwise I can work on it this week.

**Comment by patricktrainer** [comment]
Hey @ZeRego - good idea on using separate schemas 👍 

Everything seems pretty straightforward, though could you expand some on step 3?

> pass the new env var to all the commands in `packages/e2e/cypress/cli/cli.cy.ts`?

I'll be in the airport and have a long flight today, so I might be able to knock it out then ✈️

**Comment by ZeRego** [comment]
@patricktrainer When we execute commands we pass the env vars.
Example:
```
cy.exec(
            ` dbt run --project-dir ${projectDir} --profiles-dir ${profilesDir}`,
            {
                failOnNonZeroExit: false,
                env: {
                    PGHOST: Cypress.env('PGHOST') || 'localhost',
                    PGPORT: 5432,
                    PGUSER: 'postgres',
                    PGPASSWORD: Cypress.env('PGPASSWORD') || 'password',
                    PGDATABASE: 'postgres',
                    SEED_SCHEMA: Cypress.env('SEED_SCHEMA') || 'jaffle', // <-- pass env var to command
                },
            },
        )
```
