### ISSUE TITLE
Timezone options for date/datetime dimensions

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#5949]
### Description
I would like to provide the ability for users to change reporting timezones if needed.

### What problem does this solve?
At the moment, all timezones are stored as UTC. However, it may be the case that different stakeholders or use cases might require a different reporting timezone. This cannot be easily faciliated in Lightdash at the moment.

I can think of 3 general approaches:
1. We can include a new "timezone" option for date/datetime dimensions that specified the timezones that users can select in the UI
2. [Provide an ability](https://github.com/lightdash/lightdash/issues/3232) to create multiple dimensions based on a single column in YML (this is my preference)
3. Allow [custom dimensions](https://github.com/lightdash/lightdash/issues/3233) to be created in the UI

**Comment by TuringLovesDeathMetal** [comment]
Hey @gordonkjlee !

I just recently specced a milestone for this here: https://github.com/lightdash/lightdash/milestone/97

Would that solve your use case? 

(If yes, I'll close this as a duplicate!)

**Comment by TuringLovesDeathMetal** [comment]
Yep! This issue is related to the user-specific timezones: https://github.com/lightdash/lightdash/issues/5923

Also, you can now create multiple dimensions based off a single column in Lightdash 👀 

Closing this in favour of the milestone linked!
