### ISSUE TITLE
Allow users to use the decimal comma

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#5950]
### Description
Most European countries use the decimal comma. I imagine that the best location for this would be under user settings - allowing users to decide if they want to switch the decimal separator from `.` to `,` and the thousands separator from `,` to `.`

### What problem does this solve?
Let users see numbers in a format most familiar to them.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. 

For now, users can update the necessary dimensions using hte `format` option in their .yml.
