### ISSUE TITLE
Dbt models with no column properties should not show

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#596]
If I define a dbt model in a .sql file but don't document it in a schema.yml file, it shows in lightdash but clicking it just opens an empty explore

**Comment by TuringLovesDeathMetal** [comment]
I feel like I'd rather that they show, and then there's a message saying "hey, you need to add a schema.yml file to see the columns in this explore!" in the empty state. 

^This way you're able to mitigate the error by telling them what's wrong. If the model didn't show there at all, there would be no way to be like "hey, were you expecting this model to pop up, but it hasn't?"

**Comment by TuringLovesDeathMetal** [comment]
@owlas I feel like this is still a thing? 🤔 As in, if I have a model with no columns defined in it, then I'll get a table with no dimensions in Lightdash.

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue - I don't think this is a problem anymore
