### ISSUE TITLE
improve error messages inside a new limit popover for results table

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5961]
How about some shorter error messages?

Over 500: `Maximum value : 500`
A Negative number: `Minimum value: 1`
String : `Invalid value`

Originally posted by @PriPatel in https://github.com/lightdash/lightdash/issues/5915#issuecomment-1596814585_

**Comment by jayanand05** [comment]
Hi @IrakliJani , it's working fine now request you to look into it?

https://github.com/lightdash/lightdash/assets/113882904/9550ba12-ec21-4b47-adca-560d90725a84
