### ISSUE TITLE
When I hover over the table name in a grouped dropdown, I should see its description

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5977]
https://github.com/lightdash/lightdash/issues/5154

<img width="419" alt="Screenshot 2023-06-30 at 10 39 36" src="https://github.com/lightdash/lightdash/assets/7611706/9994a6a9-1983-44bf-b79d-25ed446ff82e">

Once we have implemented the grouped dropdowns, the user should be able to see the table description when they hover over the table name ( just incase you are seeing the table concept for the first time as a business user). 

- [ ] In this case, I should hover over the word 'Orders' and be able to see the table description
- [ ] This should affect dropdowns when Im adding filters in the explore and the dashboard

**Comment by joaoviana** [comment]
`item.description` is too verbose.

Revert: https://github.com/lightdash/lightdash/commit/61dfbee24ba8cffa97055702184e5d8fc04992e1

Add `table.description` `Tooltip` on hover of the **table** name - as described on ticket ^
