### ISSUE TITLE
Move spaces queries into a model 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#598]
The space entities file 'packages/backend/src/database/entities/spaces.ts' has all the queries. These should be moved into 'packages/backend/src/models/SpaceModel.ts'. 

Todo:
- [ ] Create SpaceModel
- [ ] Refactor existing code to use SpaceModel
- [ ] Add unit tests

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego is this still relevant?

**Comment by owlas** [comment]
This was fixed, logic moved to `SpaceModel.ts` - not sure which PR that happened!
