### ISSUE TITLE
Add headless browser protocol in env vars

### ISSUE THREAD

**Issue by ygotthilf** [lightdash/lightdash#5983]
### Description

I would like to call my headless browser server that is secured with TLS ('wss' protocol).

However, protocol is hard coded  [here](https://github.com/lightdash/lightdash/blob/main/packages/backend/src/services/UnfurlService/UnfurlService.ts#L270).

Is it possible to create a HEADLESS_BROWSER_PROTOCOL environment variable ? The value could be "ws" (default) and "wss".

I can submit a PR if it helps !

**Comment by ygotthilf** [comment]
It is !

**Comment by manhnguyen1998** [comment]
Hi @ZeRego 
It's me. Thanks for your support
