### ISSUE TITLE
Conditional formatting rules are applied in reverse order

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#5989]
### Description

Conditional formatting rules are applied in reverse order. I would normally expect the first rule I define to be applied first, then if that condition isn't met, it should check whether the next condition is met, etc.

### To Reproduce

1. On a % change table calculation, set it to show green if the value is greater than 0
2. Add a second rule to show yellow if the value is greater than -0.1
3. Add a third rule to show red if not null (all non-null values not captured by the above rules must be lower than -0.1)
4. All values will now turn red, because the third rule (not null --> red) is applied first. I would normally expect this to be applied last.

### App Version

v0.621.0

**Comment by TuringLovesDeathMetal** [comment]
The order is explained in the docs here: https://docs.lightdash.com/guides/visualizing-your-results#table:~:text=You%20can%20set%20as%20many%20rules%20on%20a%20table%20as%20you%20want.%20If%20two%20or%20more%20rules%20disagree%20with%20each%20other%2C%20the%20rule%20that%E2%80%99s%20on%20the%20bottom%20of%20your%20list%20of%20rules%20will%20win.

We're not going to change this ordering as it would be a breaking change.
