### ISSUE TITLE
Refactor user model & entities

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#599]
The user model `packages/backend/src/models/User.ts` and entities should be refactored.

Todo:

- [ ] all tracking should be in Service
- [ ] move all code from `packages/backend/src/models/User.ts` into `packages/backend/src/models/UserMode.ts`
- [] refactor other services/etc to use the new model methods
- [] add unit tests

**Comment by owlas** [comment]
Still relevant. We should revisit this during #983
