### ISSUE TITLE
Better unfurls when sharing a query

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#60]
e.g in slack they currently look like this
<img width="499" alt="Screenshot 2021-06-07 at 11 49 15" src="https://user-images.githubusercontent.com/11660098/121004273-650fa000-c786-11eb-97a1-c0479906823e.png">

A quick win would be to use meta tags. For slack we could have something more custom to improve unfurling.

One potential challenge with this (and with share urls in general) is if the dimensions/metrics/filters contain sensitive information.

**Comment by TuringLovesDeathMetal** [comment]
THis is still a feature we want to build, it just isn't a priority now!

**Comment by TuringLovesDeathMetal** [comment]
Kind of a duplicate of this: https://github.com/lightdash/lightdash/issues/2776
