### ISSUE TITLE
Add configuration option for pie charts to become a donut chart

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6004]
- [ ] add checkbox in a pie chart config to turn pie chart into a donut chart

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani I feel like this is a bit of bloat - I'm going to close it until someone asks for it 👀

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal there already is a PR for it
