### ISSUE TITLE
I want to know if a CSV export is truncated because of the Cell limit

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#6016]
### Description

We currently limit CSV exports, we truncate the data if the number of cells is bigger than 5 million (by default). 

Ideally, 

* I'd like to know if the CSV is going to be truncated, even before I export the CSV

But for that I'll have to run a query (maybe we can do a COUNT(*) first?) 

If that is not possible, 

* I'd like to know if the file exported was truncated
    * showing a warning at the end of the CSV file
    * Showing a warning on the UI (we can use job details for that) 

### What problem does this solve?

Some people might not know if the data is incomplete.

**Comment by TuringLovesDeathMetal** [comment]
Closing this in favour of: https://github.com/lightdash/lightdash/issues/6688

We're going to notify users _**after**_ export (not before) because it's much less complicated
