### ISSUE TITLE
Ui bug - Tables in the 'User Management' page

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6020]
<img width="439" alt="Screenshot 2023-06-22 at 12 28 54" src="https://github.com/lightdash/lightdash/assets/12776522/34c3fcf5-c4cf-4383-abf9-e540fcdac9a2">

The corner is cut off

**Comment by sivasathyaseeelan** [comment]
can you tell that in which route or on which page you are experiencing this issue?

**Comment by PriPatel** [comment]
Hi @sivasathyaseeelan - I can still see it on this page in our demo:
https://demo.lightdash.com/generalSettings/userManagement

**Comment by sivasathyaseeelan** [comment]
![Screenshot (96)](https://github.com/lightdash/lightdash/assets/95441117/bc3900d8-14f2-495d-903a-a7d31d1daf81)
see this and kindly clarify which part is cutting off

**Comment by PriPatel** [comment]
![249094508-bc3900d8-14f2-495d-903a-a7d31d1daf81](https://github.com/lightdash/lightdash/assets/12776522/1c15a3bc-3732-4683-bc39-539f26497035)
If you zoom into the circle, you can see it
