### ISSUE TITLE
User Management page : UI bug when a dropdown is open and you scroll down the page

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6021]
<img width="707" alt="Screenshot 2023-06-22 at 12 11 52" src="https://github.com/lightdash/lightdash/assets/12776522/31c72a8d-0f9d-4cdc-ac0e-385263c22073">

z-index issue. When the dropdown is open and I scroll down the page, it remains in front of the navbar. It makes things look broken.

**Comment by anjali29singh** [comment]
can you assign this issue to me ?

**Comment by jayanand05** [comment]
Got the issue!

**Comment by jayanand05** [comment]
it's working fine now

https://github.com/lightdash/lightdash/assets/113882904/88415b6e-58a4-4ca8-8045-b85b04a276d3
