### ISSUE TITLE
Migrate hotkeys from blueprint to mantine

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6024]
### Description

Migrate all uses of blueprint hotkeys provider and hooks ( [docs](https://blueprintjs.com/docs/#core/hooks/use-hotkeys) )  with mantine hotkeys hook ( [docs](https://mantine.dev/hooks/use-hotkeys/) )

**Comment by ankur0904** [comment]
@IrakliJani Can I work on this issue?

**Comment by IrakliJani** [comment]
@ankur0904 go for it!
