### ISSUE TITLE
Admins can't see private spaces in the "All spaces" page

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6038]
### Description

Admins have access to private spaces. At the moment they can only see the space by accessing via the url.

Admins should be able to see all the private spaces in the spaces page.

### App Version

0.640.0

**Comment by PriPatel** [comment]
<img width="810" alt="Screenshot 2023-06-26 at 12 07 43" src="https://github.com/lightdash/lightdash/assets/12776522/d74d9143-04d7-46a3-93d3-a3ab3a45e52a">

With the addition of all these new spaces, the Admin's `All Spaces` pages will be crowded and hard to manage. My suggestion to get the page into a 'list' view and have some new management options. (manage between 'all spaces' that I can see in admin view vs spaces that have been specifically shared with me)
