### ISSUE TITLE
Lightdash cloud is hiding metrics. (sneaky)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#604]
### Context
https://www.loom.com/share/cfcbd043d1ba4ce1b6c2d6bc3a55c4a5

I am:
- running Lightdash locally
- connected to a dbt cloud project

**Comment by owlas** [comment]
What version of dbt are you using in dbt cloud? 

I found my version at this link: https://cloud.getdbt.com/#/accounts/20983/projects/34669/environments/32747/

<img width="1907" alt="Screenshot 2021-10-19 at 11 49 30" src="https://user-images.githubusercontent.com/11660098/137895084-d5497cbd-c1bc-4329-bd56-9e6f86f4f307.png">

**Comment by TuringLovesDeathMetal** [comment]
![image](https://user-images.githubusercontent.com/31848148/138056943-509ae722-0e79-4ebb-b16b-9d7d125dbdf4.png)

**Comment by owlas** [comment]
We have deprecated support for dbt cloud #769
