### ISSUE TITLE
I want to be able to customise chart tiles in dashboards

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6051]
### Description

Users can select/deselect legends when viewing charts. 
However, they can't save these _selections_. 

It would be useful to be able to customise these when adding chart tiles to a dashboard, so they can avoid having to create multiple charts of the same query but with different selections. 

Example of a legend selection: 

https://github.com/lightdash/lightdash/assets/7611706/854d64da-306a-431a-830a-1f6d36c09bf8

### What problem does this solve?

Reduces the number of individual tiles that users have to create when adding similar queries to a dashboard.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/3321
