### ISSUE TITLE
Creating "drill down" options for data in a chart or dashboard. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#607]
### Context
A lot of the time, we aggregate data in a chart (e.g. `count unique user Ids`). But, then you might have a question like "which users are the 5 people who have subscribed to Lightdash Cloud?". Wouldn't it be nice if you could just click on this number and see the items that make this up?

Metabase does this really well; https://www.metabase.com/learn/questions/drill-through#view-these-records
^there are looooooads of features that they offer for drill-through behaviours ([see them here](https://www.metabase.com/learn/questions/drill-through.html))

I've found Looker doesn't do this well: it's not default (you have to add the drill-down in lookml) and the way you interacted with the drill-downs felt really janky (it basically gave you a list of data which was a dead-end...metabase makes this way more interactive so you can keep exploring from the drill-down). 
https://docs.looker.com/reference/field-params/drill_fields

Once you have drill fields though, their UX is pretty great (love the "explore from here" option): https://www.youtube.com/watch?v=31giRwg6OIs

### Goal
Be able to see the items that make up an aggregate value in Lightdash.

**Comment by avaitla** [comment]
Yes we need this as well

**Comment by colin-nayuta** [comment]
still relevant
+1

**Comment by TuringLovesDeathMetal** [comment]
yes! #2460

**Comment by TuringLovesDeathMetal** [comment]
Closed in favour of #2460
