### ISSUE TITLE
Updates to the Tiles tab in the Dashboard filters modal

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6072]
Includes blueprint->mantine

<img width="464" alt="Screenshot 2023-07-18 at 13 41 47" src="https://github.com/lightdash/lightdash/assets/12776522/deeb9c87-b3d4-4a52-8a8d-4044aeded3bb">

- [x] When a chart has not been selected, hide the field picker. 
- [ ] Show the chart icon type next to the chart name (https://github.com/lightdash/lightdash/issues/5768)

Add a checkbox above all charts . Users can interact with this to select/deselect all the charts. 
- [x] Checkbox is checked : All charts are selected 
- [x] Checkbox is unchecked : No charts are selected
- [x] Checkbox is indeterminate : Some tiles are selected  (show number of charts eg. 2 charts selected)

**Comment by mustajab-ikram** [comment]
Can I work on this @PriPatel ?

**Comment by joaoviana** [comment]
> Can I work on this @PriPatel ?

@mustajab-ikram 👋  hi! 
Unfortunately I have to work on this since it's already part of a milestone that we're currently working on. Please feel free to pick other tickets 👍
