### ISSUE TITLE
Metrics "formula" preview

### ISSUE THREAD

**Issue by tlfbrito** [lightdash/lightdash#6085]
### Description
Being able to display the SQL code behind a metric.

### What problem does this solve?

Sometimes I would find it useful to know the metric formula just to validate without the need of looking at the DBT code base. Could be also interesting for Editors or Developers to know what is "under the wood".

**Comment by ZeRego** [comment]
@tlfbrito Where would you like to see this information ?

At the moment, in the explore page, users can see the SQL generated for all the selected dimensions, metrics, table calculations. 

![Captura de ecrã 2023-06-30, às 11 35 51](https://github.com/lightdash/lightdash/assets/9117144/44c2a44c-88dd-468c-bcd4-33c0c57f6fc6)

**Comment by tlfbrito** [comment]
This already helps @ZeRego 👍 

I was thinking something more explicit, like Preset approach:
![image](https://github.com/lightdash/lightdash/assets/1071148/b0c9116d-9cbd-4e54-b8c2-fcac4c713ff8)
They also have a special icon where you can hover on the metric and see the metric calculation details.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - we used to have this feature and it had no usage. I also think that being able to see the SQL in the SQL tab is sufficient for this.
