### ISSUE TITLE
Metrics "compact" to be in UI

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#6088]
### Description
At the moment, we can compact metrics to thousands (K) or millions (M) etc. by using the `compact` property.

Rather than (or perhaps in addition to) being specified in the metrics definition, it seems like this should be configured in the UI (metrics and axes) by the reporting user based on the level of aggregation and size of values that are being worked with.

### What problem does this solve?
Sometimes it's not possible to known in advance the order of magnitude of data being worked with. E.g the user might want to look at an individual order, or group by weeks or years. At the moment, I specify multiple metrics - one for £, one for £k, and one for £M. It just seems like this is something that is better configured by the user rather than the analytics engineer.

**Comment by tlfbrito** [comment]
Another suggestion could be set by default the compact defined on "meta:" and then fall back to the following "compact" if the value < 0.

For example:
0.1M would fallback to 100K

**Comment by TuringLovesDeathMetal** [comment]
Ideally, I think it would be great if we could apply `compact` to a single place, and it would get pushed across anywhere that metric/dimension/table calculation was used. 

E.g. applying `compact` format in the results table would mean that the values would be compact when plotted, on the axes, etc. 

Eventually, then, you'd be able to override this default application in more granular settings (e.g. eventually we'll let you add/remove `compact` format from the axes, or from the value labels). But, at the start, it would be great if you could just add it to one place, andit would be effectively implemented everywhere that number was used after.

**Comment by TuringLovesDeathMetal** [comment]
This is now possible!
