### ISSUE TITLE
Migrate blueprint <KeyCombo> to mantine

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6093]
> found this mantine component https://mantine.dev/core/kbd/ that we can use. 
> 
> @muhsinkamil we could create a `HotKey` component that parses the string with `parseHotkey` and then render different symbols/keys depending on the user OS. 
> 
> ```import { parseHotkey } from '@mantine/hooks/lib/use-hotkeys/parse-hotkey';```
> 
> We use similar logic as the blueprint component, how it maps the keys to icons/strings https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/hotkeys/keyComboTag.tsx

_Originally posted by @ZeRego in https://github.com/lightdash/lightdash/pull/6063#discussion_r1245035073_

**Comment by muhsinkamil** [comment]
Just an update, I checked briefly and it seems like `_parseHotkey_` is not exposed from mantine hooks.
So, this may need own logic to map and render to different symbols / keys based on os
```
import { parseHotkey } from '@mantine/hooks/lib/use-hotkeys/parse-hotkey';
```

**Comment by Ankush263** [comment]
Hello @ZeRego, I can work on this issue...🙋‍♂️
