### ISSUE TITLE
API to update a dashboard doesn't accept all partial updates

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#610]
`PATCH /dashboard/dashboardUuid` doesn't accept:

* empty payloads
* payloads with just a description change

It would simplify the frontend implementation if these were available.

**Comment by ZeRego** [comment]
What is the purpose of accepting an empty payload ? 
I think we should close this issue since the FE doesn't need these changes. 
We should only change the payload once there is a ticket to introduce that use case.
