### ISSUE TITLE
Enhance project recognizability 

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6102]
### Description

This issue aims to improve the ease of use and user experience in Lightdash, particularly enhancing project recognizability. 

Thoughts on implementation: 
* Introducing different themes or color schemes for each project. Users would be able to immediately identify the project they are working on by its unique visual design.
* Making the project name explicit in the "Browse" dropdown menu. This ensures users are always aware of the context in which they're operating.

### What problem does this solve?

This lack of immediate recognizability can lead to confusion and inadvertent errors, such as working on the wrong project.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - this is a great idea, but we can reopen it when it gets requested again!
