### ISSUE TITLE
Investigate sorting of emails alphabetically

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6112]
### Description

Users have reported that email-type dimensions get sorted by case, then alphabetically. They should be ordered alphabetically regardless of the casing. 

Slack thread for context: https://lightdash.slack.com/archives/C05DWCRMLUF/p1688143782452199

**Comment by rephus** [comment]
I have the feeling this sorting might be happening in the warehouse, normally SQL databases are case insensitive... I asked the user what warehouse he is using

**Comment by rephus** [comment]
This is happening on snowflake: 

https://community.snowflake.com/s/question/0D50Z00007RaLIiSAN/snowflake-is-case-sensitive-see-example-in-details-is-there-a-way-to-make-it-case-inssentive-

> However, there is a parameter called QUOTED_IDENTIFIERS_IGNORE_CASE, which you can change to true during your session to ignore cases for all object identifiers in double quotes.

**Comment by rephus** [comment]
There is a workaround for this issue by using `QUOTED_IDENTIFIERS_IGNORE_CASE` on snowflake. Alternatively, we could do this ourselves. However, I think some people might not want this to happen...

**Comment by TuringLovesDeathMetal** [comment]
Clsoing this issue as not planned - like Javi said, there's a workaround available here and it's warehouse-dependent (and some people might not want it to be the default behaviour).
