### ISSUE TITLE
[CLOSE AT END OF MILESTONE] I want to be able to select a different date granurality for charts on dashboards 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#6119]
### Description

This "date drill" or date aggregation is a feature that already exists in Hollistic, and customers find this really useful.

https://docs.holistics.io/docs/date-drill#:~:text=Simply%20right-click%20on%20the%20report%20%3E%20select%20Date,granularity%20of%20one%20single%20report%20at%20a%20time.

![image](https://github.com/lightdash/lightdash/assets/1983672/d4d22f09-51ba-4ad3-a185-9ae7715fec57)

Slack thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1688376537051429

### What problem does this solve?

Date Drill allows viewers to quickly change the time granularity (year, quarter, month, week, day, hour, minute) of reports.

This feature is helpful in helping you zoom out of the details to identify a trend, or look closely at day-to-day operations.

**Comment by TuringLovesDeathMetal** [comment]
In Tableau, you have a similar feature: 

![image](https://github.com/lightdash/lightdash/assets/31848148/7dd8759f-837b-49e5-a5a8-26bb83b8939c)

It allows you to drill up and down on the axis itself. And not just for time, you can also drill up/down into categories if a hierarchy is provided.

Some other details: 
if my raw data was at a month-level granularity, then I’m assuming you could only “drill up” from there to quarter or year?
Not necessarily, The behaviour in many BI tools is that if someone drills down '2023-06' monthly data to daily resolution, the bars/lines will not change, but the axis will now show the month as a day '2023-06-01'.
https://help.tableau.com/current/pro/desktop/en-us/Img/hierarchy2.gif

**Comment by rephus** [comment]
Someone else asked for this https://lightdash.slack.com/archives/C05VBJJ5UCC/p1698910644622879?thread_ts=1698893282.144539&cid=C05VBJJ5UCC
