### ISSUE TITLE
 If you toggle the legend checkbox, then it breaks , although the total is calculated correcly. 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#6125]
[Screencast from 03-07-23 16:02:27.webm](https://github.com/lightdash/lightdash/assets/1983672/c509d14b-3746-460f-ab96-8a0fe37391ea)

_Originally posted by @rephus in https://github.com/lightdash/lightdash/issues/6115#issuecomment-1618367308_

**Comment by CVamsi27** [comment]
@rephus,
What should be the behavior of chart on legend checkbox unchecked?
- Un-select all legends
- Retain the previous selection
