### ISSUE TITLE
Update delete dashboard modal to account for charts that belong to dashboards

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6134]
### Description

Charts can now "belong" to dashboards. This means that if you create `chart A` in `dashboard 1,  we'll need to warn you that there are some charts that you'll be deleting (along with the dashboard).

### Acceptance criteria

- [ ]  When a user tries to delete a dashboard that contains a chart that was created in the dashboard, then user gets some warning message explaining what will happen. 
- [ ] The warning message contains information about:
    - [ ] What will happen if you delete this dashboard (the charts created within the dashboard will also be deleted) 
    - [ ] which charts are going to be deleted
- [ ] In the Spaces delete modal, we include charts created in dashboards in the count of charts in this modal. 
<img width="704" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/258bb8af-0e48-4f8b-95d8-59066a2ffd41">

### Analytics events

- `saved_chart_deleted` is triggered if a chart is deleted from a dashboard.

**Comment by PriPatel** [comment]
### When the dashboard contains charts that have been created from within it:
<img width="369" alt="Screenshot 2023-07-06 at 15 29 37" src="https://github.com/lightdash/lightdash/assets/12776522/cafda4c9-aacc-4124-a627-eeaf41e278ad">

- [ ] Show the following message:

> Are you sure you want to delete the dashboard `Dashboard name?`
> This action will also delete all of the charts created from within it. You can preserve these charts by moving them to the Space `Space the dashboard is in`:

- [ ] Then list of all the charts that will be affected, with a 'Move' CTA




### When the dashboard contains charts that have been created from within it and they also appear in other dashboards
<img width="367" alt="Screenshot 2023-07-06 at 15 29 41" src="https://github.com/lightdash/lightdash/assets/12776522/9a5c926d-9018-4dbf-a224-d0ee3ccdd178">

- [ ] Show the following message:
> Are you sure you want to delete the dashboard `Dashboard name`?
> This action will also result in the permanent deletion of all of the charts created from within it as well any instances of them that are being used in other dashboards. You can preserve these charts by moving them to the Space `Space the dashboard is in`:


- [ ] Then list of all the charts that will be affected, with a 'Move' CTA.
- [ ] If the chart is being used in another dashboard, show the name of the dashboard with a link to it.

**Comment by PriPatel** [comment]
Closing in favour of #6239 https://github.com/lightdash/lightdash/issues/6239 for now (because I want to keep this spec for later!)
