### ISSUE TITLE
When I create a saved chart from a query, I'm able to add it to a dashboard or to add it to a space.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6138]
### Description

When I create a saved chart from a query, I'm able to either add it directly to a dashboard (so it "belongs" to that dashboard) or add it to a space. 

### Acceptance criteria

(Items with 👩‍🎨 need design help!)

- [x] 👩‍🎨 When I create a saved chart from a query from the `new query` button in the navbar or from `explore from here`, I'm given the option to `save chart to dashboard` or `save chart to space`. 
- [ ] Saving the chart to a dashboard means that chart now "belongs" to the dashboard (so the same things apply as in this issue: #6133 in terms of where the chart is visible in the app)
- [ ] Saving the chart to a dashboard causes a success toast to appear which includes the option to `open dashboard` (with a link to the dashboard)
    - [ ] Opening this link opens the dashboard, in view mode.
- [ ] Saving a chart to a space works exactly like it does now. 

### Analytics events

- If the user saves chart to a dashboard, then this should cause the same `true`/`false`  to be updated in `saved_chart_created` and `saved_chart_updated` as here: https://github.com/lightdash/lightdash/issues/6133#:~:text=to%2Dyour%2Ddashboard-,Analytics%20events,-Can%20someone%20think

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal And I discussed that we will de-prioritise this flow for now

**Comment by TuringLovesDeathMetal** [comment]
Closed because this is no longer relevant for this milestone (will re-open later if needed)
