### ISSUE TITLE
Ability to show/hide values in the series pie charts config

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6153]
### Description

- [ ] Show/hide values also hasn't been added into the series configuration in the pie charts.

![CleanShot 2023-07-05 at 12 27 40](https://github.com/lightdash/lightdash/assets/962095/4900944b-01d6-4699-8cd0-83dfd56bfd23)

ℹ️ we don't know if users would expect the pie to still be 100% with the values recalculated based on removing a part, or if they'd expect the slice of the pie to just be white

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani I'm going to close this issue for now 👀 

Let's open it when someone asks for it (so I can ask what they actually want to happen when the values are shown/hidden)
