### ISSUE TITLE
support snowflake warehouse selection for running queries

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#616]
Be able to set specific warehouses to be used to run queries against depending on:
 user, 
 user group
 or table/explore
 or permutation of the above

Reasoning:
Splitting cost by use case or team. Choosing the right size warehouse depending on the use case.

**Comment by owlas** [comment]
Just to check: today users add a single profile for each project in Lightdash, which means that **all** queries in a project (no matter which user or table it is) uses the same profile. For snowflake connectors that includes the warehouse.

So the request here is that different users should be able to use the same snowflake credentials but use a different warehouse? And similarly, that certain queries in a project (e.g. based on the table name) should use the same snowflake credentials but a different warehouse?

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as no one has requested it in > 2 years! Will reopen if it becomes an issue :)
