### ISSUE TITLE
Enable to name a table other than the `name` property

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#6164]
### Description
Lightdash automatically names a table with the `models[].name` property in the schema YAML. 

In our case, we name dbt models with the pattern of `{GCP_PROJECT_ID}__{BQ_DATASET_ID}__{BQ_TABLE_ID}` so that we surely make dbt model ID unique. Historically, a dbt model ID is determined by the SQL file name. So, if we have multiple tables whose dataset ID and table ID are the same across Google Cloud projects, those are conflicted. 

For instance, if the name of a dbt model is `project_a__dataset_b__table_c` corresponding to `project-a.dataset_b.table_c` in BigQuery, Lightdash interprets the table name as `Project a dataset b table c` as far as I know. That would be human-readable. But, I would like to define a custom name.

```yaml
# schema.yml
version: 2
models:
  - name: "project_a__dataset_b__table_c"
```

### What problem does this solve?
We can make table names more human-readable.

**Comment by TuringLovesDeathMetal** [comment]
This is already possible with `label`. The docs are here: https://docs.lightdash.com/references/tables#:~:text=Note-,label,-string
