### ISSUE TITLE
Quarter should be included in the default time interval 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#6192]
### Description

![image](https://github.com/lightdash/lightdash/assets/1983672/033ea66a-a104-481e-82be-8251f4fcb180)

https://docs.lightdash.com/references/dimensions#time-intervals

See slack thread: https://lightdash-community.slack.com/archives/C039GAKTPMK/p1688684392757929

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned. 

There haven't been any other requests for this issue since it was opened. If it gets requested again, I will reopen it!
