### ISSUE TITLE
Existing dashboard filters should apply to tiles added to a dashboard 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6198]
### Description

If you apply a dashboard filter, then add a chart to that dashboard - the existing filters are not applied. This should happen automatically. 

For example, if I have a filter `users - date created = '2023-01-01'`, then I add a new chart which is built from an Explore which has the field `users - date created`, then by default, this new chart should have the `users - date created = ' 2023-01-01'` filter applied to it. 

### Acceptance criteria

- [x] Charts added to dashboards should have existing filters applied (where possible)
- [x] Filters are only applied if the chart is built from an explore which has the field used to define the dashboard filter 
- [x] The charts appear in the `tiles` tab of the dashboard filter with the filter applied as soon as the chart appears on the dashboard.

**Comment by IrakliJani** [comment]
user comment on this:

> When creating a new dashboard, I added a table and set up several filters. All good. Later, I decided to add another table using the same model. It took me some time to realize that the filters I created earlier weren't automatically applied to this new table. I had to manually add the new table into the filter scope. I can see why it behaves this way, but it might be beneficial to either apply these filters to the new table by default or provide a warning/notification about it.
