### ISSUE TITLE
Ability to filter on array values and to build charts based on array elements

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#6217]
### Description

This will be a potentially large feature - but Lightdash doesn't currently work well with Arrays.

### What problem does this solve?
1. When trying to filter on arrays, I get an error.
<img width="344" alt="image" src="https://github.com/lightdash/lightdash/assets/7281432/56afe433-6999-4b9e-85ab-5f705b3ea64e">

2. It will also be great to be able to product charts based on Array elements. For example, let's say I have a survey with multiple choices A, B, C. Some respondents may select ['A'], others ['A', 'B'], or ['A', 'C'] etc. Right now, if I plot a chart, frequencies are calculated based on combinations (strict order) or choices. However, what might be more useful is to calculate the percentage of respondents who select A, B, and C - i.e. a frequency chart with just 3 bars.

**Comment by yu-iskw** [comment]
+1

**Comment by okiyuki99** [comment]
+1

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue in favour of this more recent issue around supporting Array data types more generally: https://github.com/lightdash/lightdash/issues/10742
