### ISSUE TITLE
Smaller minimum height for tiles

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#6218]
### Description

I sometimes want to have tiles just to help organise the dashboard by insert section headers (i.e. tile title only with no content).

However, the minimum height on the tile makes this ugly and takes up real estate.

<img width="934" alt="image" src="https://github.com/lightdash/lightdash/assets/7281432/dde18d33-21d0-4fbf-ad89-60d216c40dc6">

### What problem does this solve?
Allow more flexible and useful employment of tiles for organising dashboards.

**Comment by PriPatel** [comment]
+1 from another user

> Is it also possible to add more ways to visualize chart layouts in dashboard? Reason being I have different groups of information in the same dashboard. I've separated them with Markdown tiles to make it more readable as I wasn't sure how else to add headers. But since I'm using tiles as headers, I'd have a giant blank space with no context. I've attached an image for reference.

**Comment by KristyMayer** [comment]
Another related ask -- if you make a "header" tile, can you allow formatting like larger font and centering? the default font is quite small. (I believe we can use markdown to modify but it's a bit janky & doesn't fully achieve the desired result -- I can follow up with a screenshot later if needed.)
