### ISSUE TITLE
Images of scheduled delivery lack some tiles on slack

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#6235]
### Description
Delivered images on slack lack some tiles in a dashboard.

#### The dashboard with a scheduled delivery
The dashboard has three tiles.

![image](https://github.com/lightdash/lightdash/assets/1523515/0d74fb40-c9aa-4222-8e0c-f0f22ac50e0f)

#### The delivered image on slack
However, the delivered image on slack contains just one tile. The two tiles weren't shown in the image. The expected behavior is to show all tiles in the dashboard.
![image](https://github.com/lightdash/lightdash/assets/1523515/822e1aec-53ad-48b8-9ec4-5ec6acdd7136)

### To Reproduce

1. Create a dashboard in a public space.
2. Put some tiles to the dashboard
3. Set a scheduled delivery to a public slack channel.

### App Version

- v0.657.0 on Lightdash Cloud

**Comment by TuringLovesDeathMetal** [comment]
This is related to #6932
