### ISSUE TITLE
Easter egg: Adding the snake game to scatter plots 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#624]
During a donut session with @ZeRego - we were talking about fun easter eggs that we could add to Lightdash. Our favourite one is that when a user is looking at a scatter plot, they can execute a special keyboard command that changes the chart into the classic Nokia Snake game 🐍 : 

![image](https://user-images.githubusercontent.com/14341285/137767862-cf20217a-32a2-4bfb-90e4-3acb16f5e1e4.png)

**Comment by owlas** [comment]
What do you think @hamzahc1 still relevant?
