### ISSUE TITLE
I want to be able to specify which snowflake warehouse my Lightdash models are being executed in

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6240]
### Scope
Snowflake DWH connection only

### Description
It would be really great if we could (optionally) specify what snowflake warehouse Lightdash should use when fetching the data from the model.

**Why**?
In our default project we have several datasets for various things. Raw tracking data, clean product session/page views, AB testing focus, and etc.
Volumes of those are VERY different. From tens of billions rows to several millions. Query usage level is not the same as well, we can't control really how often what source is being used. It's pretty unpredictable.
Right now all those models will be queried by using the warehouse configured in connection.
It's not ideal as if we use big sized warehouse (let's say XL) to ensure querying big datasets is fast enough then we're burning the money on querying smaller datasets. As smaller ones would be probably totally cool to query with M sized warehouse.
If we set it smaller, then users of bigger datasets are waiting and cluttering the warehouse (there's a limit how many queries you can run on one warehouse... and we're not on enterprise snowflake edition so auto horizontal scaling is not working for us ).

### Potential solution
There's already configuration for this in dbt, we're just not reading it in Lightdash. We should be reading this config in Lightdash: https://docs.getdbt.com/reference/resource-configs/snowflake-configs#configuring-virtual-warehouses

<img width="598" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/5ed5b696-bb40-4b75-88ef-63b71cd3253a">

**Comment by jw-aleksandr-zolotukhin** [comment]
what a great idea :-)

**Comment by owlas** [comment]
it looks like we don't need to add this to the `meta` since it's already a valid dbt configuration option

**Comment by TuringLovesDeathMetal** [comment]
@jw-aleksandr-zolotukhin just following up from Oliver's comment. 

There's this configuration in dbt here: https://docs.getdbt.com/reference/resource-configs/snowflake-configs#configuring-virtual-warehouses

Are you using this already? Is it just that Lightdash isn't "reading" this?

**Comment by jw-aleksandr-zolotukhin** [comment]
@TuringLovesDeathMetal 
yes. reading that native dbt setting would be ideal.
