### ISSUE TITLE
The prompt in autocomplete drop-downs telling users to 'Start typing' is cut off

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6249]
<img width="343" alt="Screenshot 2023-07-11 at 13 26 34" src="https://github.com/lightdash/lightdash/assets/12776522/e91e2a2b-41a0-418b-ad12-1fcfb905fed7">

- [ ] You should be able to see the full prompt. The prompt could be shifted to the left.

**Comment by hrutik7** [comment]
hey @PriPatel ,
I would like to work on this. I just wanted to know if this is still relevant?
