### ISSUE TITLE
Add support for Databricks spark

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#625]
dbt has now made Databricks Spark an officially supported adapter.

Lightdash should also support Databricks Spark projects!

**Comment by drernie** [comment]
Any updated ETA for official Spark support? Not urgent, but still important!

**Comment by owlas** [comment]
Hey @drernie this is almost complete now, just in final stages of testing!

**Comment by drernie** [comment]
I noticed that the documentation has not been updated to mention DataBricks support:

https://docs.lightdash.com/get-started/setup-lightdash/connect-project#database-1

Should I create a new ticket for that, or just wait until it is refreshed?

**Comment by owlas** [comment]
Sorry looks like the docs deployment hasn't updated! I'll debug now.

Until then you can access the latest Databricks docs in the repository: https://github.com/lightdash/lightdash/blob/main/docs/docs/get-started/setup-lightdash/connect-project.mdx#databricks
