### ISSUE TITLE
SQL runner showing no columns

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6261]
### Description

There is an edge case where the results have no `fields` metadata which is used by the Lightdash UI to generate the columns.
[slack thread](https://lightdash.slack.com/archives/C04KD95TF0U/p1689019772967779)

### To Reproduce

We still aren't sure about the replication steps.

> Ok, just found something - this query is from my dev schema. Any queries on this particular view in my dev schema don't work in SQL Runner (but do work in BigQuery console). 

![Screenshot 2023-07-10 at 4 08 10 PM](https://github.com/lightdash/lightdash/assets/9117144/02d68983-6e70-4cc6-8632-3cf98da0bc84)

### App Version

0.660.0

**Comment by TuringLovesDeathMetal** [comment]
Clsogin this issue as not planned - we haven't been able to replicate and ithasn't been reported since.
