### ISSUE TITLE
Navbar is overlapping right sidebar 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#6275]
### Description

![image](https://github.com/lightdash/lightdash/assets/1983672/e698e72c-2a85-407b-89c1-cfffd108f30b)

I've noticed the navbar is now overlapping the right sidebar, this might be affecting other components too.

**Comment by Krishna2323** [comment]
Hey @rephus, can you pls assign me this?
I had fixed this minor bug.

<img width="1710" alt="Screenshot 2023-07-13 at 9 36 48 AM" src="https://github.com/lightdash/lightdash/assets/85894871/4dbff235-c5ea-492b-a566-9b7311248859">

**Comment by TuringLovesDeathMetal** [comment]
This is no longer an issue.
