### ISSUE TITLE
You should only be able to see the drag handle on a pinned item on part of it, rather than the whole item

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6278]
> In pinned items area when I'm hovering mouse becoming a hand icon which indicates that i can move thing around. Yeap, I can reorder those pins indeed.
> But it got me confused for a moment few times already, as I just wanted to open it. As it's not really the :point_up: cursor that user would expect to see for something clickable.
> Yes, you can still do a single click and open it, but it's :exploding_head:
> I believe opening the pinned item is way more often action comparing to reordering.
> How about making a :point_up: on main area and dedicate some visible part of the pinned panel to be draggable?

- [ ] The main interaction on hover should be the point cursor
- [ ] Is it possible to make the area to the left of the icon show up as draggable only?

**Comment by joaoviana** [comment]
After chatting with @PriPatel, will implement the following: 
- change the cursor type on hover of pinned items
- on hover of pinned item, display 6-dot icon on the left-hand side of the item, and element is only draggable when interacting with that icon

**Comment by joaoviana** [comment]
As discussed offline with @PriPatel, revisit `Tooltip` display only on the name of the items, not on the whole `Anchor` component
