### ISSUE TITLE
When you hover over a point in a chart, the exact value in the tooltip should stand out more 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6283]
Right now, when you hover over a point in a chart, we show every single value in the tooltip.

### Problems
- Sometimes the tooltip gets so big that it covers the chart
- Sometimes there are so many series in the tooltip that it's cropped and doesn't show the value I'm hovering over.
- If I use the same colour twice in a bar chart, I have no clear way of knowing which value in the tooltip is being referred to when I hover the bar
- We already tried updating the tooltip to show **only** the value of the point the user is hovering over. However, it seems that seeing all values is useful in order to make comparisons. 

### Possible solutions

Let's build two options, then share them with users and see which they prefer. 

### Option 1

- just show the value of the point on hover over a point
- on hover anywhere else in the chart show all of the values

e.g. here, I'd expect to see one value (the value of the orange point I'm hovering on)
<img width="899" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/57fbf73b-83e0-4912-9cb1-26d778442962">

Here, I'd expect to see what I see now (I'm hovering somewhere within the chart, but not on a specific point - so I want to see all values)
<img width="850" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/0e520285-59db-4b01-a397-dcc5783b0ab3">

### Option 2

- Show all values on hover over a point, but highlight the value of the point, and stick it at the top
- on hover anywhere else, show all the values

e.g. here, I'd expect to see the value for the orange point in bold, at the top (or highlighted, or something - you can experiment and see what looks the best!), but I'd still see all of the other values for the series below it.
<img width="899" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/57fbf73b-83e0-4912-9cb1-26d778442962">

Here, I'd expect to see what I see now (I'm hovering somewhere within the chart, but not on a specific point - so I want to see all values)
<img width="850" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/0e520285-59db-4b01-a397-dcc5783b0ab3">

**Comment by joaoviana** [comment]
done here as well: https://github.com/lightdash/lightdash/pull/7247

**Comment by TuringLovesDeathMetal** [comment]
This issue has been resolved!
