### ISSUE TITLE
Wrong button copy when editing a dashboard tile

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6287]
### To Reproduce

Steps:
- go to dashboard with loom/markdown tiles
- click edit
- click options menu for loom/markdown tile
- see `replace chart` button

Expected `Edit tile content` instead

<img width="788" alt="Screenshot 2023-07-12 at 14 37 18" src="https://github.com/lightdash/lightdash/assets/9117144/675cd5aa-0eb0-4378-9c40-43c2626bf92e">

### App Version

0.664.1

**Comment by PriPatel** [comment]
@ZeRego 
`Edit tile content`
