### ISSUE TITLE
Warn user when chart data might not be accurate

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6289]
### Description

Add a warning message when the chart configuration has grouping/pivot and doesn’t use all dimensions that are in the query.

In those cases, the unused dimensions should be removed from the query or added to the pivoting/grouping.
Otherwise, some data will be “lost” since there are multiple rows for the same pivot/group value.

### What problem does this solve?

Some users get confused when they are grouping/pivoting and data is “missing” from the chart.

eg: [https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/tables/dbt_or[…]%2C%22label%22%3A%7B%22show%22%3Afalse%7D%7D%5D%7D%7D%7D%7D](https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/tables/dbt_orders?create_saved_chart_version=%7B%22tableName%22%3A%22dbt_orders%22%2C%22metricQuery%22%3A%7B%22dimensions%22%3A%5B%22dbt_orders_currency%22%2C%22dbt_orders_partner_name%22%2C%22dbt_orders_order_date_month%22%5D%2C%22metrics%22%3A%5B%22dbt_orders_average_of_basket_total%22%2C%22dbt_orders_count_distinct_order_id%22%2C%22dbt_orders_sum_of_basket_total%22%5D%2C%22filters%22%3A%7B%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22dbt_orders_order_date_month%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%5D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22dbt_orders_currency%22%2C%22dbt_orders_partner_name%22%2C%22dbt_orders_order_date_month%22%2C%22dbt_orders_average_of_basket_total%22%2C%22dbt_orders_count_distinct_order_id%22%2C%22dbt_orders_sum_of_basket_total%22%5D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22dbt_orders_order_date_month%22%2C%22yField%22%3A%5B%22dbt_orders_average_of_basket_total%22%2C%22dbt_orders_sum_of_basket_total%22%2C%22dbt_orders_count_distinct_order_id%22%5D%7D%2C%22eChartsConfig%22%3A%7B%22series%22%3A%5B%7B%22type%22%3A%22bar%22%2C%22yAxisIndex%22%3A0%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_month%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_average_of_basket_total%22%7D%7D%2C%22label%22%3A%7B%22show%22%3Afalse%7D%7D%2C%7B%22type%22%3A%22bar%22%2C%22yAxisIndex%22%3A0%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_month%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_sum_of_basket_total%22%7D%7D%2C%22label%22%3A%7B%22show%22%3Atrue%2C%22position%22%3A%22top%22%7D%7D%2C%7B%22type%22%3A%22bar%22%2C%22yAxisIndex%22%3A0%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_month%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_orders_count_distinct_order_id%22%7D%7D%2C%22label%22%3A%7B%22show%22%3Afalse%7D%7D%5D%7D%7D%7D%7D)

<img width="1867" alt="Screenshot 2023-10-11 at 18 23 28" src="https://github.com/lightdash/lightdash/assets/9117144/7a2fe791-c2ba-43a2-85f0-4c3b6c1303e9">

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue for now - I don't think warning is the best option here. I think there's some behaviour around "ungrouping" this or maybe showing that we only select the first value. But I'm going to close this as not planned (we can reopen and look into this later if needed)
