### ISSUE TITLE
Set a reference line to a field / metric (i.e. dynamic / programatic)

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6298]
### Description

Instead of providing a fixed value for a reference line, I'd like to use a field (probably another metric) to set the line dynamically 

An example of this would be if I had a "actual" vs. "budget" metric over time.

**Comment by TuringLovesDeathMetal** [comment]
closed as a duplicate of https://github.com/lightdash/lightdash/issues/8232
