### ISSUE TITLE
Show descriptions of fields when adding filters 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6299]
### Description

Acceptance Criteria: 

- [ ] When you hover on fields when adding filters, you should see the description in a tooltip the same way we show this for tables 
<img width="406" alt="CleanShot 2023-07-12 at 22 44 12@2x" src="https://github.com/lightdash/lightdash/assets/14341285/bb8af9bf-4934-43af-a891-671566b7049b">

- [ ] There should be a delay of 0.5 second for the hover action before the tooltip appears, this is to stop tooltips constantly appearing if you're scrolling for example.

**Comment by Krishna2323** [comment]
hello @hamzahc1, can I work on this?

**Comment by hamzahc1** [comment]
@Krishna2323 - I'd recommend picking from our [good first issues list](https://github.com/lightdash/lightdash/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%99%8B+good+first+issue%22) instead as while some of these smaller issues may appear simple, they often require more context on the code base 😊. Excited for your contribution 🚀

**Comment by Krishna2323** [comment]
Thanks @hamzahc1, I'm comfortable with the code base, will find another issue if you are saying. Is there anyone who can assign me issues quickly?
I'm will make meaningful impact through my contributions.
