### ISSUE TITLE
Dashboard and Chart Level Usage Analytics

### ISSUE THREAD

**Issue by pinkbaka** [lightdash/lightdash#6300]
### Description

For a chart or dashboard, I want to see who and how often they are using it. 

### What problem does this solve?

I want to measure adoption / general use when implementing dashboards for specific initiatives.

**Comment by PriPatel** [comment]
Closing in favour of  'https://github.com/lightdash/lightdash/issues/4415 ! 
**I want to know the 'view history' of my dashboards and charts**
