### ISSUE TITLE
Make it clear that scheduled deliveries content expires after 3 days

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6306]
### Miro sketch:

https://miro.com/app/board/uXjVP1D_L4w=/?moveToWidget=3458764564350757379&cot=14

### Areas of impact:

- [ ] **When you are setting up the scheduled delivery**, there should be some 'fine print' telling you what to expect and that the content will expire after 3 days

- [ ] **In emails**, the footer should show that the content expires after 3 days. There should be helpful next steps - eg. reach out to an admin, log in to the app etc.  

- [ ] **Slack** : There are quite a [few things we could do here](https://lightdash.slack.com/archives/C048FE7206Q/p1689599698513139)!

We can use some copy from the existing docs
> For security reasons, the delivered files expire after 3 days. This means old emails or Slack shares will have broken images and there is not an option to retrieve them. If you want to keep the sent files, it's best to download them from the scheduled delivery.

**Comment by hamzahc1** [comment]
Could we also change the image after 3 days to something else? I know Mode does this :

> >Q: How long is the generated image in Slack available for?
> 
> The report image preview is live for 4 days after posting in the Slack channel. After this time, the image will be replaced with a stock image stating that the report preview has expired. Users with Mode access can still access the report to view data from the latest run via clicking the URL shared in the Slack message.

**Comment by rephus** [comment]
Quick note: expiry date can be different than 3 days, so we need to treat this number as a variable.
