### ISSUE TITLE
Error after renaming custom metric

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6307]
### To Reproduce

Steps
1. create custom metric 
2. sort by custom metric
3. save chart
4. rename custom metric 

https://github.com/lightdash/lightdash/assets/9117144/1e7918ea-a448-4f08-9201-a161edd4c3d9

### App Version

0.667.0

**Comment by TuringLovesDeathMetal** [comment]
This has not been reported since. Closing this issue as not planned. WIll reopen if it's reported again!
