### ISSUE TITLE
You should be able to apply temporary sorting to table charts in dashboards

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6315]
Miro sketch: https://miro.com/app/board/uXjVNeDsQHw=/?share_link_id=24821374308

### Acceptance critieria: 

- [ ] You should be able to apply temporary sorting to columns in table charts in dashboards. This is for exploration whilst in view-mode.
- [ ] This only applies to table chart types
- [ ] The sorting isn't saved once the user refreshes the page, or exits the dashboard (just like dashboard filters in view mode)
- [ ] By default the table is sorted according to the sort of the underlying table. 
- [ ] Clicking any of the headers then completely overrides the sort configuration on the underlying table and the UI should indicate the sort order. 
- [ ] Clicking on the same column header:
  - [ ] once = sorting descending
  - [ ] twice = sorting ascending
  - [ ] three times = sorting turned off 
- [ ] If I've added a sort on one column, then I click on another column, the sort from the first column is removed and only the second column sort is applied. 
- [ ] This sorting behaviour works in `view mode` of a chart, in `view mode` on a dashboard, and in the table in `view underlying data`
- [ ] Users can only apply a single sort 
- [ ] It should apply sorting in the underlying sql query

This allows the user to override the `sort` configuration on a `MetricQuery` like we have for dashboard filters. It should apply sorting in the underlying sql query

**Comment by owlas** [comment]
what about multisort?

**Comment by owlas** [comment]
For now let's only support a single sort type. 

By default the table is sorted according to the sort of the underlying table. Clicking any of the headers then completely overrides the sort configuration on the underlying table and the UI should indicate the sort order. The user can sort a single column at a time, no multi-sort.

**Comment by hamzahc1** [comment]
This was requested by a potential customer today.

**Comment by hamzahc1** [comment]
This should also apply to View underlying values

**Comment by mhawkins-runa** [comment]
Is this essentially the same issue as [this](https://github.com/lightdash/lightdash/issues/3591)? I was searching for this issue as I'm interested in the same feature, and came across both tickets.

**Comment by hamzahc1** [comment]
> Is this essentially the same issue as [this](https://github.com/lightdash/lightdash/issues/3591)? I was searching for this issue as I'm interested in the same feature, and came across both tickets.

Good catch! I've closed the other issue in favour of this one

**Comment by rephus** [comment]
Let's also show the default sorting applied at the chart level (even without adding temporary sorting)

Related thread: https://lightdash.slack.com/archives/C053ESBT36V/p1697029941481439
