### ISSUE TITLE
Replace Tooltip2 with Mantine (not in tables)

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6337]
### Description

Replace Tooltip2 with Mantine components not in tables. At the time of filing this ticket there are 25 files with Tooltip2. Some are more complex than others. There is a separate ticket for tooltips in tables as they have specific perf concerns. 

- [ ] Replace simple tooltips (just text, no styles)
- [ ] Replace styled tooltips and those with logic. Test this a little extra :).
- [ ] Check that tooltips in menus and modal work properly

Try to create a PR for each 5/6 files changed, to make it easier to review.

**Comment by Ankush263** [comment]
Hello @magnew, I can work on this Issue
