### ISSUE TITLE
Replace Popover2 with Mantine

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6340]
### Description

Replace Popover2 with mantine components. At the time of filing there are about 16 files with Popover2s. Some of these will probably be Mantine Popovers and some Hovercards. 

- [ ] Replace popovers on Dashboard page
- [ ] Replace popovers in Explore
- [ ] Replace popovers in chart config
- [ ] Replace popovers in Settings (Scheduler)
- [ ] Look for z-index issues. Are there tooltips in any popover? Are there popovers in a modal?

**Comment by Ankush263** [comment]
Hello @magnew 🙋‍♂️, I can work on this issue

**Comment by la55u** [comment]
This should be closed as completed
