### ISSUE TITLE
Add `sql_filter` to models

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6349]
### Description

More context: #5442 

Users can declare a filter in their `yaml`, which will always be applied to any query against that model.

```yaml
models:
  - name: users
    meta:
      sql_where: ${my_dimension} = 12 OR ${TABLE}.hello = 'bye'
```

- Can reference dimensions with `${my_dimension}`
- Can reference the base table with `${TABLE}`
- `sql_where` is only applied if the model is being queried directly. It doesn't apply if another table is queried and joins `users`
- Cannot reference metrics with `${metric}` 

The generated SQL for any query should always include this

```
SELECT
  dimensions,
  metrics
GROUP BY dimensions
WHERE true
  AND ${ sql_where }
  AND (.... remaining filter logic ....)
```

The UI doesn't indicate that this is applied but it's visible in the compiled SQL.

Open questions:
- Should you be able to reference joined tables? `${my_joined_table.dimension}` - we'd need to scan for these references when we decide what tables to join.

### Analytics events

- [ ]  we should add two columns to the `project_compile` event:
  - [ ] `models_with_sql_filters_count` - the number of models that have at least one sql filter on them. (Note: models can only have a single sql_filter on them)

**Comment by TuringLovesDeathMetal** [comment]
@owlas what's the reason that we went with `sql_where` over specifying that this is a `user attribute` filter? 

(i.e. the questions in the issue that you linked)

**Comment by owlas** [comment]
@TuringLovesDeathMetal since #5442 included a few (not-mutually exclusive) filter options, I've started to break them out into individual issues.

I'll open a new ticket for the other syntax
