### ISSUE TITLE
Chart type changes when filtering on dashboard

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#6355]
### Description
When the user filters on a dash, all the series disappear then come back as the default `bar` type.
We might be sorting the series types (line/bar/area) on each series.

**Comment by magnew** [comment]
Is there a specific chart type for this? I put a line chart on a dashboard and added a filter and still see the line chart when I save it. Is there something else required?

**Comment by rephus** [comment]
Related: https://github.com/lightdash/lightdash/issues/6257

**Comment by hamzahc1** [comment]
Is this still happening? I couldn't recreate this 🤔

**Comment by rephus** [comment]
Unable to replicate
