### ISSUE TITLE
When I remove the only chart that's using a filter on a dashboard, the filter stays

### ISSUE THREAD

**Issue by yasmin-e** [lightdash/lightdash#6358]
### Description
When I remove the only chart that's using a filter on a dashboard, the filter stays with an error message.

https://github.com/lightdash/lightdash/assets/67699259/5152e406-5456-49a2-9c42-84ef1a634971

### To Reproduce
- Go to a dashboard with at least 2+ charts
- Apply a filter to a single chart
- Remove that chart from the dashboard
- An error message appears in the place of the filter

### App Version
Version: v0.667.0

**Comment by TuringLovesDeathMetal** [comment]
Suggested solution: If there are no charts that the filter applies to, the filter is removed from the filters list automatically.
