### ISSUE TITLE
I should be able to choose whether my dashboard filter has a default value applied to it

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6377]
Implement backend first: #6497

Ignore UI changes - implement functionality only for "default value" switch

<img width="820" alt="Screenshot 2023-07-18 at 15 20 49" src="https://github.com/lightdash/lightdash/assets/12776522/ae652fa0-36d4-4a0b-ab41-d7a1b29a48e0">

- [ ] Change `Value` to `Default Value`
- [ ] Add a toggle next to the label
- [ ] If the toggle is on, the value field will show Placeholder text to prompt the user to enter a value (paste doc with placeholder changes here) (filter disabled = false)
- [ ] If the toggle is off, the value field will be disabled and show `Any value` (filter disabled = true)

### Documentation

Update this doc: https://docs.lightdash.com/guides/limiting-data-using-filters#adding-filters-to-your-dashboard to include information about default value filters

**Comment by hamzahc1** [comment]
Note here, the default behaviour should be no default value (i.e. toggle should be off)
