### ISSUE TITLE
Move dashboard filter configuration out of popovers and into modals

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6384]
https://www.figma.com/file/btY2rdBe5I2W4xLR3upmQG/Untitled?type=design&node-id=1930-194899&mode=design&t=Ks26oJQK60dE21EA-0

### Edit mode
- [ ] In edit mode, when I click on 'add filter' the filter config should appear in a Mantine modal now, rather than a popover (size `md`)
- [ ] The 'Chart tiles' tab should be disabled if no dimension has been selected

### View mode
- [ ] When I click on a saved filter in view mode, I should now see a Mantine popover
- [ ] When I click "add" I see the full modal
- [ ] When I click on a temporary filter in view mode, I see the full modal

**Comment by kharbandaashu** [comment]
Hey @PriPatel, I would like to contribute. Please assign to me.

**Comment by owlas** [comment]
Hey @kharbandaashu if it's your first time contributing to the repository I would encourage you to check out the `good-first-issue` label, which we curate to provide issues that are well suited to the first few contributions.

**Comment by mustajab-ikram** [comment]
hey @kharbandaashu @PriPatel ,
Can I pick this?

**Comment by PriPatel** [comment]
Hi @mustajab-ikram Thanks for your interest in contributing! This milestone is already in progress and has quite a few unknowns - I recommend looking at issues with the [good-first-issue](https://github.com/lightdash/lightdash/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%99%8B+good+first+issue%22) tag!

**Comment by iampranavdhar** [comment]
This will be taken care, of under #6490 right?
