### ISSUE TITLE
Chart in dashboard analytics events

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6388]
Extracted from original issue:

> ## Analytics events
> Can someone think of a better word than belongs_to_dashboard? or do we think that's clear enough?
> 
> For the saved_chart_created event, there is a new field called belongs_to_dashboard. This is either True or False. If the chart was created from within a dashboard and is therefore "linked" to the dashboard, the belongs_to_dashboard is True. If the chart was created outside of a dashboard and is therefore not linked to any dashboard, it has belongs_to_dashboard = False.
> We also need to update saved_chart_updated to include belongs_to_dashboard

Requirements:
- [ ] trigger `saved_chart_created` when creating a chart that belongs to a dashboard
- [ ] add `dashboard_id` to `saved_chart_created` and `saved_chart_updated` when chart belongs to a dashboard ( @TuringLovesDeathMetal do we need it in the `saved_chart_deleted`) ?

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego 
No, I think it's fine - if we need it in there, we can just join to the latest `updated` event and find out :)
