### ISSUE TITLE
There should be a way to 'reset' or 'clear' a dashboard filter

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6398]
Now that we allow 'empty' filters to be added to the dashboards, there should be some way for the end user to 'Reset' the filter back to how the 'builder' would have set it up.

**Option 1** 
Reset the filter to it's original state
<img width="455" alt="Screenshot 2023-07-18 at 18 07 29" src="https://github.com/lightdash/lightdash/assets/12776522/199353ad-afb1-4e10-b59b-62458eab2268">

**Option 2** 
<img width="443" alt="Screenshot 2023-07-18 at 18 08 29" src="https://github.com/lightdash/lightdash/assets/12776522/47579c43-0931-446b-81c7-5a3bb688ae94">
Every value field (string / number / date) should have a 'clear' button so that the user can leave it empty

### Docs

- add this information to the docs page for dashboard filters: https://docs.lightdash.com/guides/limiting-data-using-filters#adding-filters-to-your-dashboard

**Comment by owlas** [comment]
Rolled into #6377
