### ISSUE TITLE
users can control what part of the dependency graph they see

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#64]
Users can choose to see the full tree or just the direct links in the tree of the dependency graph

https://sketch.cloud/s/62ffa882-a034-429e-9bba-312d59130ce7

**Comment by TuringLovesDeathMetal** [comment]
@owlas - I've updated the spec here. 

Not sure which label I prefer for the buttons though:
- option 1 is: "Show all dependencies" + "Show direct dependencies"
- option 2 is: "Show full lineage" + "Show direct lineage"

"dependencies" gives you a better idea of what it's going to show you, but since you've just clicked on "see lineage", the word "lineage" might actually fit better here...

Will leave it up to you to pick which you prefer!

**Comment by owlas** [comment]
Hey @TuringLovesDeathMetal I just realised that: 

* An explore has multiple tables (of course one is the base table)
* Each of those tables has it's own lineage
* the tables are joined together to form an explore

Since we show lineage at the explore-level, shouldn't it include all the relevant tables to that explore?

E.g an explore with 1 base table and  joined tables -> lineage would show all three table's lineage smooshed together. Maybe we'd additionally show a "joined" link between them. Which would touch on #68

**Comment by ZeRego** [comment]
Should the arrows in the lineage show the join sql so users can see how they are connected ?
Would this make my ticket redundant ?

**Comment by owlas** [comment]
I suppose we could do something like that on hover.

**Comment by TuringLovesDeathMetal** [comment]
I would have expected that it would _**just**_ contain lineage information for the "main" table in the Explore (not the joined ones). 

Then you would be able to see join information like this: https://github.com/lightdash/lightdash/issues/68

I don't think that joined tables would be part of the "lineage" in my mind 🤔 as in, if I changed any upstream tables of the main table, none of the joins would be affected...right?

**Comment by owlas** [comment]
Yeah that's true. But I guess if something upstream of a joined table changes then it will affect the explore in question.

**Comment by owlas** [comment]
I mean this could be solved if we showed lineage on a table level rather than an explore level, but I don't think that really has a home in the UI right now, except for the sidebar dimensions/metrics list

**Comment by TuringLovesDeathMetal** [comment]
hmmm....what about something like this?

![image](https://user-images.githubusercontent.com/31848148/123104298-1c6b0e80-d437-11eb-9c35-b12ceec98ba7.png)

**Comment by TuringLovesDeathMetal** [comment]
Okay, updated the Sketch file here:
https://sketch.cloud/s/62ffa882-a034-429e-9bba-312d59130ce7

I'm not in love with the "show all dependences (including joined tables)" option. The reasons being:
1. what happens if a table joined has the same upstream/downstream dependencies? Do we draw an arrow to the same location?  
2. is this an overwhelming amount of information to show someone? --> should we maybe instead give the option of clicking on one of the joined tables and opening a new dependency graph?

The reasons why having it this way _**could**_ be dope:
- imagine if something is broken/a number is off. So, you look at the dependency graph, you click on the "including joined tables" option, and you can see that upstream of the joined table (e.g. Users), one of its dependencies had failed --> causing the count of unique user IDs (a metric you pull from this joined table) to fail. 
- ^I'm imagining that eventually we'll include status of tables in the lineage graph

**Comment by owlas** [comment]
@TuringLovesDeathMetal this is awesome!

Shall we split this out into another separate ticket then? Have the simple lineage and then the "with joins" sometime in future?

**Comment by TuringLovesDeathMetal** [comment]
yep, great idea. 

Here's the newest ticket: https://github.com/lightdash/lightdash/issues/121
