### ISSUE TITLE
Update the `dashboard filters` docs 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6400]
Update this doc: https://docs.lightdash.com/guides/limiting-data-using-filters#adding-filters-to-your-dashboard

**UPDATE 16/08**
All images for the new filter pills were updated in: https://docs.lightdash.com/guides/limiting-data-using-filters/#adding-filters-to-your-dashboard. However, these do not contain the changes to the Tiles tab (new checkboxes, new icons) 

- [ ] #6845

- [ ] #6846

So, UI changes to be made are:
- [ ] Update Tiles tab screenshots
- [ ] Update Dashboard buttons screenshots
- [ ] Update screenshots https://docs.lightdash.com/get-started/exploring-data/dashboards - dashboard action buttons specifically

On content:
- [ ] Add description on how to reset a Filter to its initial value/setting

**Note**: please use Miro to create these images!

- Here is the Miro board with all existing docs images so you can use that as a guide for how to create your own + add any new images into there: https://miro.com/app/board/uXjVPdFXdWo=/?share_link_id=331277786844
- please use company colours for any arrows/highlighting in the images ❤️
- if you need help, ask Katie!

**Comment by joaoviana** [comment]
doing most of it here: https://github.com/lightdash/lightdash/pull/6657

Then, will update some UIs once more tickets are done

**Comment by hamzahc1** [comment]
@joaoviana - as this is now handed over, can you instead update this ticket with where you believe it's still outstanding?

**Comment by joaoviana** [comment]
Closed as it's been split into 2 issues
