### ISSUE TITLE
Headway update for dashboard filters improvements

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6402]
- descriptions of fields when adding filters: https://github.com/lightdash/lightdash/issues/6299
- Changed appearance of dashboard filter pills: https://github.com/lightdash/lightdash/issues/6370
- default values on filters: https://github.com/lightdash/lightdash/issues/6377
- updated `tiles` tab: https://github.com/lightdash/lightdash/issues/6072
- view mode vs. edit mode interaction improvements: https://github.com/lightdash/lightdash/issues/6371
- improved operators: https://github.com/lightdash/lightdash/issues/6372
- improved interactions with the `label` field: https://github.com/lightdash/lightdash/issues/6379

**Comment by magnew** [comment]
This is done
