### ISSUE TITLE
I want min/max values in conditional formatting colour ranges to be set automatically

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6406]
### Description

when creating a colour range rule in conditional formatting you have to specify min/max values by yourself.
I want these value to be adjusted automatically based on the data

acceptance criteria:

- [ ] we should have the max value set by default to the max value in the column they're applying the conditional formatting to
- [ ] on hover, you see the rule, and it says greater than (min value) and less than (max value). I'd expect it to say what colour it is based on the "rules"/intervals we've set in the colour range. E.g. if white = values between [0, 5], I'd expect to see that when hovering over white. Not values between [0, 100]
- [ ] if field is not selected (applying conditional formatting to all applicable columns), then min/max value should be taken from all applicable columns

**Comment by magnew** [comment]
Closing as a duplicate of #4516
