### ISSUE TITLE
Allow the user to customise the sql join type

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6414]
### Description

User wants to use `inner` join instead of the `left` join we use by default: https://lightdash.slack.com/archives/C053ESBT36V/p1689776286272479

```yaml
models:
  - name: users
    meta:
      joins: 
        - join: companies
          type: inner
          sql_on: ${users.user_id} = ${companies.user_id}
```

### Acceptance criteria

- [ ] There is a way to specify the join type in the join meta (probably `type`?)
- [ ] there are these options for join type: 
    - [ ] `inner`: corresponds to `INNER JOIN` SQL logic
    - [ ]  `full`: corresponds to `FULL OUTER JOIN` SQL logic
    - [ ]  `left`: corresponds to `LEFT OUTER JOIN`  
    - [ ] `right`: corresponds to `RIGHT OUTER JOIN`
- [ ] by default, if no `type` is defined, we use `LEFT OUTER JOIN`

### Docs

Update the `tables` reference doc to include:

- [ ] a `joins configuration` section like in metrics here: https://docs.lightdash.com/references/metrics/#metric-configuration
- [ ] This includes an example join with all of the configurations applied
- [ ] It also includes a table with all the configurations described in it
- [ ] These configurations in the table are linked to the sections already in the doc (which explain the configuration options)
- [ ] add a new configuration row + section in the docs for "Specify your join type using `type`"
- [ ] Remove the info at the top of the `joins` doc which says "all joins are LEFT OUTER joins"
- [ ] Add an info block in the `specify your join type` section which says "By default, if no `type` is specified, all joins are `LEFT OUTER` joins"

**Comment by jw-aleksandr-zolotukhin** [comment]
probably makes sense to allow not only `inner`, but also all other types of joins along.
