### ISSUE TITLE
I want to be able to provide a custom list of filters on a scheduled delivery dashboard

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#6447]
### Description

I want to be able to provide a custom list of filters on a scheduled delivery dashboard

Slack thread: https://lightdash.slack.com/archives/C04FQQU4RL7/p1689933736689099

**Comment by TuringLovesDeathMetal** [comment]
This is a duplicate. Closing this in favour of https://github.com/lightdash/lightdash/issues/4425
