### ISSUE TITLE
Amend dashboard components typing

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6450]
### Description

The DashboardContext should support both the tiles and create tile types.

Example of current typing:
```
    dashboardTiles: Dashboard['tiles'] | [];
```

Ideal typing:
```
    dashboardTiles: Array<Dashboard['tiles'][number]| CreateDashboard['tiles'][number]>;
```

Similar typing needs to be amended in most of the dashboard components. eg: AddTileButton

**Comment by yasmin-e** [comment]
This will allow us to solve the typing error in `packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx` > `InvalidDashboardChartTile`, left a TODO in the component
