### ISSUE TITLE
Investigate ERR_INVALID_CALLBACK error 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#6451]
### Description

>{"code":"ERR_INVALID_CALLBACK","level":"error","message":"Uncaught Exception thrown Callback must be a function. Received undefined","stack":"TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined\n    at setInterval (node:timers:211:3)\n    at Object.callback (/usr/app/node_modules/snowflake-sdk/lib/connection/connection.js:184:26)\n    at requestCallback (/usr/app/node_modules/snowflake-sdk/lib/services/sf.js:1192:23)\n    at Object.callback (/usr/app/node_modules/snowflake-sdk/lib/services/sf.js:662:43)\n    at /usr/app/node_modules/snowflake-sdk/lib/http/base.js:111:25\n    at done (/usr/app/node_modules/urllib/lib/urllib.js:589:5)\n    at /usr/app/node_modules/urllib/lib/urllib.js:953:9\n    at decodeContent (/usr/app/node_modules/urllib/lib/urllib.js:740:14)\n    at handleResponseCloseAndEnd (/usr/app/node_modules/urllib/lib/urllib.js:924:7)\n    at IncomingMessage.<anonymous> (/usr/app/node_modules/urllib/lib/urllib.js:962:7)\n    at /usr/app/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:55\n    at AsyncLocalStorage.run (node:async_hooks:319:14)\n    at AsyncLocalStorageContextManager.with (/usr/app/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)\n    at IncomingMessage.contextWrapper (/usr/app/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:32)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:552:15)","timestamp":"2023-07-21 08:45:30"}

is killing the backend. 

Slack thread: https://lightdash.slack.com/archives/C02GQKJK84Q/p1689940347894789

**Comment by jzamanxometry** [comment]
I am also seeing this error when I try to locally deploy . See slack thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1700248883273949

**Comment by TuringLovesDeathMetal** [comment]
closing this issue as not planned. it's been more than a year since any activity. Can reopen if needed!
