### ISSUE TITLE
Allow charts to group by Table Calculation

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#6452]
### Description
I am trying to use Table Calculations to create categories - e.g. Current Month or Previous Month - using a window statement. I would like to group values in the chart based on this, but I am not able to select Table Calculations.

### What problem does this solve?

Allow custom dimensions (created using Table Calculations) to be used to segment charts.

**Comment by owlas** [comment]
Hey @gordonkjlee we have some open tickets for custom dimensions (as distinct from table calculations) such as:

- #5198 
- #5199 
- #5200 

Did you want to add another custom dimension type? something to modify existing date/timestamp dimensions in a model?

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of: https://github.com/lightdash/lightdash/issues/2699
