### ISSUE TITLE
Formatting a table calculation (e.g. as currency) causes it to drop from the chart

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#6453]
### Description
Formatting a table calculation causes it to be dropped from the chart. This makes iterating the design process quite frustrating.

### To Reproduce
1. Create table calculation and graph it
2. Format the table calculation, and it drops from the chart

### App Version
0.686

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of: https://github.com/lightdash/lightdash/issues/4313
