### ISSUE TITLE
Charts: right axis label input should be hidden when there is no right axis

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6471]
### Description

The second (usually right) axis label on cartesian charts appears to do nothing if you have no series with a right axis. 

We should disable or hide the input when there is nothing configured to the right. 

### To Reproduce

On any cartesian chart:
1. Open the config
2. Go to the Axes tab
3. Enter a label in the third axis label inputs (usually "Y-axis label (right)").
4. Check the chart. The label doesn't show 😞 

The input shouldn't show if there is no right-series axis.

### App Version

Version: v0.688.1

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this as not planned. No one's complained about it yet - but agreed, this could be a good improvement (I just don't think it's going to happen)
