### ISSUE TITLE
Reference lines get disabled when hovering over other series

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6480]
### Description

Reference lines on a chart get disabled when the user hovers over another series

### To Reproduce

1. Create a chart with reference lines
2. At first you will see solid reference lines like so
<img width="1067" alt="Screenshot 2023-07-25 at 16 44 32" src="https://github.com/lightdash/lightdash/assets/1864179/a19a4ce6-deef-448a-9d8f-50402df69d0c">

4. Hover over series in the chart. The lines will dim, which is expected.
5. Stop hovering on the chart. 
6. The reference lines stay dim 😞 
<img width="1064" alt="Screenshot 2023-07-25 at 16 44 45" src="https://github.com/lightdash/lightdash/assets/1864179/8ed00ba8-ae4a-4eca-aef6-b1deaea5839a">

### App Version

v0.691.0

**Comment by karan0handa** [comment]
I can't reproduce this issue on the main branch (there's no dimming at all). Has this been fixed / dimming been removed?

**Comment by karan0handa** [comment]
I couldn't reproduce the issue. Even though the dimming of the other series is janky (maybe a dev only issue?), the reference lines don't stay dim. Maybe it got fixed after mantine migration?

https://www.loom.com/share/edc3bf9caf954e02a070ce2230c745b5

**Comment by magnew** [comment]
> I couldn't reproduce the issue. Even though the dimming of the other series is janky (maybe a dev only issue?), the reference lines don't stay dim. Maybe it got fixed after mantine migration?
> 
> https://www.loom.com/share/edc3bf9caf954e02a070ce2230c745b5

Hi @karan0handa, Thanks for looking into this! Confirmed, I don't see it anymore. I'll close the ticket.
