### ISSUE TITLE
Update UI for dashboard filters bar

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6481]
### Description

Uses mantine for "add filter" and redesigned pills:

### before

<img width="302" alt="CleanShot 2023-07-25 at 16 38 15@2x" src="https://github.com/lightdash/lightdash/assets/11660098/dbc2fee3-c474-4c9b-aed0-5bf5bbcd64fd">

### after

There should also be an `x` button to remove the filter

<img width="287" alt="CleanShot 2023-07-25 at 16 36 24@2x" src="https://github.com/lightdash/lightdash/assets/11660098/fd9985aa-f1a3-4cb2-bbf9-0af4040e2f4e">

**Comment by joaoviana** [comment]
The `x` should only appear on hover I assume 👍

**Comment by owlas** [comment]
Dupe of #6370
