### ISSUE TITLE
In view mode, you cannot remove saved dashboard filters

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6487]
### Description

Dashboard filters have 2 types:
- saved dashboard filters added by an editor in "edit" mode
- temporary dashboard filters added by a viewer in view mode

Viewers should be able to add and remove their own filters (like they can do now). But they shouldn't be able to remove saved dashboard filters, they can still change their values, but they can't remove them.

(ignore UI changes in this screenshot, except the remove filter)

<img width="682" alt="CleanShot 2023-07-26 at 09 12 53@2x" src="https://github.com/lightdash/lightdash/assets/11660098/bac223c8-c572-466b-92ae-6bfd6a08bc36">

**Comment by joaoviana** [comment]
done in #6370
