### ISSUE TITLE
users can click to see the "source" of a field/metric

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#65]
users can click to see the "source" of a field/metric. When they click on it in lightdash, it opens the dbt model .yml file in a text editor. 

https://sketch.cloud/s/785822f3-caf0-41bf-901b-388f2ff3d6ea

**Comment by owlas** [comment]
I'm not sure how feasible it is to actually open the app (most browsers disable this kind of stuff for security).

But we can definitely pin-point the source and surface the local path to the user.

**Comment by TuringLovesDeathMetal** [comment]
> But we can definitely pin-point the source and surface the local path to the user.


That could actually be awesome. I've updated the sketch file to include this relative path / local path to the user :) (wasn't sure if we actually have the full local path of the file, so I said "relative path" in the sketch - if we have access to the full local path, then let's use that!)

https://www.sketch.com/s/785822f3-caf0-41bf-901b-388f2ff3d6ea/v/wrq0Aq/a/m1MzEL7/r/ZK3pL3

**Comment by owlas** [comment]
We can use stoplight for validation: https://github.com/stoplightio/spectral#-documentation-and-community

Source map implementation used by stoplight: https://github.com/stoplightio/yaml

**Comment by ZeRego** [comment]
Existing path properties available in `DbtModelNode` objects.

![Screenshot 2021-06-23 at 14 45 46](https://user-images.githubusercontent.com/9117144/123109117-e0ce4580-d432-11eb-82aa-d14e9950b457.png)

**Comment by owlas** [comment]
Oh awesome. Do we have line numbers in there for the columns? I can't see it from the screenshot

**Comment by ZeRego** [comment]
> Do we have line numbers in there for the columns?
It doesn't. If we want to find the line we will need a lib like the one you mentioned.

**Comment by owlas** [comment]
@TuringLovesDeathMetal did you imagine having line numbers?

I assumed so but looking at the design it's actually just the filename right?

**Comment by TuringLovesDeathMetal** [comment]
I thought it wasn't possible to get line numbers... if we can, great!

If we can't though, I think it's still a pretty great feature to give you the filename.

Can you somehow open a file to a specific line on the command line? 🤔 

E.g. if I told you that this field was in `dbt/myproject/mymodel.yml` line 25, would you actually be able to use that information to open the file to a specific line?? (sorry, totally could google this....)

**Comment by owlas** [comment]
@TuringLovesDeathMetal so we can't like open the app for them BUT we can provide links for specific editors (but wouldn't know which the user would want).

e.g. for VS Code you can just provide these sort of links: vscode://file/c:/myProject/package.json:5:10
