### ISSUE TITLE
"Save chart as" flow doesn't work as expected

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6511]
### Description

When creating a new chart from a chart (with the `Save chart as` option), users see "you have unsaved changes" modal when completing the Save Modal Form.

### To Reproduce

1. Open existing chart
2. Edit
3. add / remove field/dimension/metric
4. `Save chart as`
5. Complete form
6. See success toast
7. See `You have unsaved changes` modal

Recording: 

https://github.com/lightdash/lightdash/assets/7611706/0bb09556-353c-47e1-85bb-6788f8b7e8c1

**Comment by mustajab-ikram** [comment]
hey @joaoviana,
Can I pick this up?

**Comment by joaoviana** [comment]
> hey @joaoviana, Can I pick this up?

hi @mustajab-ikram, this has been picked up by one of the Lightdash Engs, I recommend looking into other issues, for example here: https://github.com/lightdash/lightdash/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%99%8B+good+first+issue%22 thanks! 🙌
