### ISSUE TITLE
Banner image in welcome emails is not showing

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6512]
<img width="1060" alt="Screenshot 2023-07-27 at 14 38 23" src="https://github.com/lightdash/lightdash/assets/12776522/4871b51f-cf6e-4155-9df4-c97915f09ca8">

Looks fine for `Forgot password` emails...
<img width="908" alt="Screenshot 2023-07-27 at 14 42 05" src="https://github.com/lightdash/lightdash/assets/12776522/8c061637-bb49-4062-9964-bf5baae0b6b9">

**Comment by joaoviana** [comment]
closing as @PriPatel and I just tested on a deployed instance and the banner is showing

**Comment by joaoviana** [comment]
<img width="1057" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/089ca616-21c3-406e-bd05-8399b7c8e76d">
from today
