### ISSUE TITLE
Make the 'delete' actions on the Settings pages consistent

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6515]
Right now, the 'delete' actions across every panel in the Settings page is different. eg with/without icon, icon choice, button style and copy. 

All delete buttons should be `tabler-icon-trash` with **no copy.** eg:
<img width="260" alt="Screenshot 2023-07-27 at 15 19 25" src="https://github.com/lightdash/lightdash/assets/12776522/a3aa6fea-292e-49f3-b291-0921b5c15962">

Update the following: 

- [x] User management panel for each user row
- [x] All projects panel
- [x] Slack integration panel
- [x] Personal tokens panel
- [ ] Projects access panel

<img width="917" alt="Screenshot 2023-07-27 at 15 04 32" src="https://github.com/lightdash/lightdash/assets/12776522/73338146-f177-4e26-be91-e7be022cf77a">
<img width="929" alt="Screenshot 2023-07-27 at 15 04 26" src="https://github.com/lightdash/lightdash/assets/12776522/064e8327-634e-4fcc-95b0-ee772da8a52f">
<img width="919" alt="Screenshot 2023-07-27 at 15 04 20" src="https://github.com/lightdash/lightdash/assets/12776522/367d8319-c060-4f0c-abf2-81024f42583d">
<img width="515" alt="Screenshot 2023-07-27 at 15 04 15" src="https://github.com/lightdash/lightdash/assets/12776522/c3c93fe5-7532-4b74-9f00-ddbc6345ff8b">
<img width="903" alt="Screenshot 2023-07-27 at 15 04 09" src="https://github.com/lightdash/lightdash/assets/12776522/895e9cf9-1539-48ec-a915-523004c8e129">

**Comment by ujwalkumar1995** [comment]
Hey @PriPatel 
I would like to work on this. Could you please assign?
