### ISSUE TITLE
Charts display time values in the user's timezone rather than in UTC format

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6518]
### Description

Users are reporting that when visualising date-type fields in charts they are represented in their current timezone, rather than in UTC, causing a discrepancy between the values displayed on the results table vs charts

### To Reproduce

Create chart 
Add time-based field
Visualise chart
See tooltip with the different time compared to the results table

Taken from community slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1690220388510949

Excerpt from thread: 
```
The table accurately displays the data in UTC. However, the charts seem to be using an unknown timezone for the time values. Ideally, the charts should use the same timezone as the result table, which is UTC in this case.
```

**Comment by ZeRego** [comment]
At the moment we should only display in UTC. 

We have a feature request to introduce timezone configuration -> https://github.com/lightdash/lightdash/issues/5921

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned - we haven't heard of it happening again with users and we've made some changes to timezones in the last few months to make this more consistent. 

If it comes up again, I'll reopen it.
