### ISSUE TITLE
Export eCharts as JSON

### ISSUE THREAD

**Issue by drernie** [lightdash/lightdash#653]

**Comment by drernie** [comment]
I would love to use Lightdash to create my own ad-hoc dashboards and reports

Specifically, I want to be able to save an eChart as JSON, so I can include it in, eg the Quilt Data hub (who is adding eCharts support after I talked to you :-)

Initially it would be more robust to include all the data directly in the JSON. 

Long-term, I think Lightdash needs to formally support some type of data packages, so that a) charts can reference a stable data URL b) analyses can be explicitly versioned. But that’s a different issue…

**Comment by drernie** [comment]
Was there an update somewhere about this now being available? Or did I just imagine it?

**Comment by ZeRego** [comment]
@drernie Yes! This was released in 0.9.4.  The PR #746 was tagged with the wrong issue, that's why this ticket wasn't closed. Doing that now.

Preview:
![Export chart json](https://user-images.githubusercontent.com/9117144/141277124-482aa683-dc94-402b-a6fb-9b8ea9c13bd3.png)
