### ISSUE TITLE
There should be some indication when I've hit the row limit for a query

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6545]
### Description

Right now, when I run a query in Lightdash, I have to set a row limit. 

If my query exceed this row limit, then I'm not notified in any way. This is confusing because it makes me just think that there's a bug or something in Lightdash and that's why I'm not seeing the correct data (not because it's been limited by the row count). 

THere should be some indication when I've hit the row limit for a query. 

**Note:** This could be qutie difficult because we set row limits using the `LIMIT` clause in the SQL query...so we'd need to somehow run a query before to see how many results there were...

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal - this could be related to #https://github.com/lightdash/lightdash/issues/3067 ?

**Comment by TuringLovesDeathMetal** [comment]
Closing this in favour of #3067
