### ISSUE TITLE
The series I'm hovering on is not shown because the list of series is too long (and is cropped)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6547]
### Description

When I have a lot of different series on my chart, if I try to hover over a point ont he chart, the list of series is cropped. 

![image](https://github.com/lightdash/lightdash/assets/31848148/28fbb645-8ba3-484f-86ba-f4ec2cff6026)

For example, in the image above, the value I'm hovering over isn't actually shown in the list of series because the series list is cropped. 

### Acceptance criteria

There should be a way to scroll through the list of series if the tooltip is larger than the chart tab frame. 

E.g. here, I'd expect on hover that if I scrolled, it would scroll the series in the tooltip

<img width="744" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/8c202327-3a88-4dfe-8813-89d6425b7304">

**Comment by PriPatel** [comment]
Related to https://github.com/lightdash/lightdash/issues/6283

**Comment by 12ian34** [comment]
@joaoviana to see Katie in detention after class.
