### ISSUE TITLE
When onboarding, I only have one 'copy' button for 3 different snippets to run in my dbt project

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6548]
<img width="517" alt="Screenshot 2023-07-31 at 10 05 44" src="https://github.com/lightdash/lightdash/assets/12776522/f5cbcf2c-c996-49fc-a995-7e7050c5413e">

Right now, there are three different snippets that I need to be able to copy and paste to run in my dbt project, but it looks like 1 big one.

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel I don't think we need multiple copy options here. If you run this in your CLI, it will execute each command one-after-the-other

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal thanks! Closing!!
