### ISSUE TITLE
Usage analytics should not show empty value for deleted users

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6568]
### Description

Right now, if I delete a user from the organization, they appear as an empty user name in the table "which users have run the most queries in the last 7 days?"

This is confusing. 

If a user is deleted from an org, they should not appear in any user tables. 

All of the SQL queries should have `WHERE user_name IS NOT NULL` or something

**Comment by joaoviana** [comment]
@TuringLovesDeathMetal to check

**Comment by TuringLovesDeathMetal** [comment]
Closing this because we're not able to reproduce it. Will re-open if needed!
