### ISSUE TITLE
Make dashboards responsive

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#657]
Currently dashboards are fixed-width, the chart layouts would be much improved if the layout would reflow when the charts update.

Fortunately [react grid layout](https://github.com/react-grid-layout/react-grid-layout) allows us to do that, unfortunately it requires extra information to be stored with the layout.

Currently we store a tile as:

```js
tile = { x, y, w, h}
```

But with a responsive layout, we should store separate layouts for each breakpoint e.g.:

```js
tile = { lg: { x, y, w, h}, md: { x, y, w, h}}
```

We'll need to store these in the db, so would need a db schema change.

**Comment by TuringLovesDeathMetal** [comment]
I think this is solved - the charts in a dashboard change size - I'm going to assume this is solved (also since nobody's asked for it in over a year)
