### ISSUE TITLE
Better JSON-Blob/Complex type support in tables

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6578]
### Description

Complex types in Lightdash results tables can be hard to read and don't always display well. 

https://www.loom.com/share/c89dad0f002547a1baeee3a37ddb5986?sid=73262a3f-a430-4880-9327-cf9c47442b1a

**Comment by hamzahc1** [comment]
This looks great! Only UX improvement I'd suggest would put the "copy to clipboard" option at the bottom of the modal rather than on each line

**Comment by magnew** [comment]
Let me look into whether I can move the clipboard copy. It's coming from the library I'm using, but maybe there is an option. I assume that wouldn't be a blocker?

Yea, I can refactor this a bit and it could theoretically go anywhere.
