### ISSUE TITLE
Hiding a series in a stacked group shows the wrong total when there are other series

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6588]
### Description

Hiding a series in a stacked group shows the wrong total when there are other series. The total stays the same for the whole stack, but it should not include the hidden amount. 

### To Reproduce

1. Create a chart with two grouped series. 
2. Stack them
3. Show totals
4. Hide one of the series in a stack
5. Notice the totals dont change. 

Here's a video

https://github.com/lightdash/lightdash/assets/1864179/0572061b-5a4a-4134-bc2f-43d6ebdf1653

### App Version

Version: v0.715.0

**Comment by mustajab-ikram** [comment]
hey @magnew, 
Would like to work on this, can you assign this to me?

**Comment by TuringLovesDeathMetal** [comment]
Users are still reporting this as an issue

**Comment by rephus** [comment]
Mmm, I can't find a way to replicate this issue, am I missing something @magnew  ? 

[Screencast from 05-10-23 10:30:49.webm](https://github.com/lightdash/lightdash/assets/1983672/ccbc8999-89ca-4350-8959-5c1fbe896321)

**Comment by rephus** [comment]
Right, thanks @hamzahc1 I can replicate if the first serie is a line chart. 

![image](https://github.com/lightdash/lightdash/assets/1983672/26da73b0-5b2d-4659-b581-e5e3beefcfa5)
