### ISSUE TITLE
Add password requirements 

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6620]
Add 3 password rules:
- minimum length
- must contain a letter
- must contain a number or a symbol

The UI should show whether these rules have been satisfied `onChange` in the password input field (i.e. revalidate on every keystroke)

**Comment by ZeRego** [comment]
@iampranavdhar If you are comfortable with making changes to the FE and BE.

Pages that need that fix: register, accept an invite, user settings page 
Both the form and the endpoint should have the same validation so perhaps we need code the `common` package which can be used by both.

**Comment by iampranavdhar** [comment]
@ZeRego, @owlas  Can you change the assignee to me?

**Comment by iampranavdhar** [comment]
Made a pull request, consider reviewing the code in your free time :)
