### ISSUE TITLE
Update `./docs` dependencies

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6621]
Based on dependabot report

**Comment by ZeRego** [comment]
> Security auditing is broken in the front end, because much of the time, these CVEs don't actually impact anyone. I recommend you to read this Dan Abramov blog post: https://overreacted.io/npm-audit-broken-by-design/ 

> In short, upgrading involves unnecessary trouble (big architectural changes across major versions) while it doesn't actually fix any security issues. **I'm going to close this as wontfix**. Thanks for taking interest in this.

https://github.com/facebook/docusaurus/issues/6394#issuecomment-1015942459

**Comment by ZeRego** [comment]
Docs folder was moved outside this repo
