### ISSUE TITLE
Investigate silent failure when trying to move a dashboard between spaces

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6626]
### Description

A customer is seeing a silent failure when trying to move dashboards between spaces from the resource list. We can't repro it. We are going to add some temporary logging around this to gather more data and remove it when closing this ticket. 

Many details in this thread:

https://lightdash.slack.com/archives/C02KDBTN9RV/p1690872099600449

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as we weren't able to reproduce
