### ISSUE TITLE
Tables filtered with "table configuration" are available via the API

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6629]
### Description

If a table is filtered using the "table configuration" on a project, the table is still reachable via the API.

**Comment by rephus** [comment]
## Differences between selecting tables in the UI and selecting models on the CLI 

### Selecting tables in the UI 

On settings, you can filter the tables that will be visible in the `Explore` page

![image](https://github.com/lightdash/lightdash/assets/1983672/700ea4cf-61f9-4ad1-9538-21d5fbae8081)

The API call we run on explore is  `/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/explores?filtered=false` which is already filtering all the hidden tables.

However, if you make a request to filtered=false (`/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/explores?filtered=false`) you will get all filtered tables. 

And you could run queries on those tables using the API. 

*Use case* : If you want to "hide" some models from the `explore page` , to simplify the UI, but at the same time, you want to keep all joined tables working. 

*Do not use* if you want to restrict access to those tables, if you do, remove the models directly using the CLI. 

### Selecting tables from the CLI 

On the CLI, via dbt, we can filter out completely some of the models we deploy to Lightdash, only the models you select will be available on lightdash. 

> lightdash deploy --create --project-dir ./examples/full-jaffle-shop-demo/dbt/ --profiles-dir ./examples/full-jaffle-shop-demo/profiles/ -s customers -s orders

![image](https://github.com/lightdash/lightdash/assets/1983672/f0653147-b6bc-4353-b7a0-d8c7b126cb24)

*Use case* If you want to only publish some of the models on lightdash, you will only be able to run queries against these models. 

* Do not use* if you have joined tables that depend on models you don't want to deploy

**Comment by joaoviana** [comment]
This is not intended behaviour
