### ISSUE TITLE
Google Sheets deliveries should be included in my scheduled deliveries overview

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6667]
### Description

Acceptance Criteria: 

- [ ] All scheduled deliveries to a Google Sheet are available in scheduled delivery manager 
- [ ] Links to the connected Google sheet are available

**Comment by rephus** [comment]
> Links to the connected Google sheet are available 

Where are we adding the link for this ? 

What UI changes do we need to make ?

**Comment by hamzahc1** [comment]
![Untitled](https://github.com/lightdash/lightdash/assets/14341285/d0a04538-72a5-4f01-aa19-43c274b9ab7c)

**Comment by hamzahc1** [comment]
These are the changes for the overview board: 
- Icon should be Gsheets
- Destination = google sheets
- On hover - show name of Google Sheet 
- On click - navigate to Google Sheet (opens in new tab)
