### ISSUE TITLE
Google Sheet should show when data was loaded in

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6671]
### Description

- [ ] Google sheet should show when data was last received/updated - maybe by updating a cell above the info?

**Comment by rephus** [comment]
how about renaming the "tab" with the timestamp ? 
![image](https://github.com/lightdash/lightdash/assets/1983672/004844b3-8847-48c3-9a11-c5474a293b7b)

**Comment by hamzahc1** [comment]
Ok - let's leave it as is for now, if we hear different. feedback we can change this. My sense is that people will want to rename the tab name to something that makes sense for them 🤔 but happy to leave it for now!
