### ISSUE TITLE
Users can select where new Google Sheet should be created when exporting from a chart

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6675]
### Description

Acceptance Criteria: 

- [ ] By default, we create the Google Sheet in the root of the GDrive

- [ ] Using Google file picker, used can select a folder where Gsheet should be created

**Comment by rephus** [comment]
What's the UI for this ?

**Comment by hamzahc1** [comment]
I was hoping we could do this via the Picker - but looking online it doesn't seem this is possible 🤔 (https://stackoverflow.com/questions/76216805/create-new-spreadsheet-in-google-drive-picker) 

We have two options
1. We get the user to select a sheet (like scheduled deliveries) 
2. We always create a new Google Sheet (assuming GSheets lets us do this in the root of GDrive).

**Comment by rephus** [comment]
Perhaps this https://stackoverflow.com/a/21186459

To select a file we use the component `react-google-drive-picker` not sure if that has an option to select only a folder
