### ISSUE TITLE
Ability to attach PDF of Dashboard in scheduled deliveries emails

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6678]
### Description

When large dashboards are scheduled for delivery via email, the embedded image's text can be difficult to read without expanding the email. 

### What problem does this solve?

To enhance the readability and accessibility for users, it would be beneficial to provide an option to include the same dashboard image as a PDF attachment within the same email. This would offer users an alternative way to view the dashboard with better clarity.

### Acceptance criteria:

- [ ] If a user selects `image` as the export option, there is a toggle below the format which allows you to `Also include image as PDF attachment in email`
<img width="182" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/233474a1-7dbd-4901-b201-54a749f29871">

- [ ] by default, this toggle is `off` 
- [ ] This is only for email to start with (we can open a separate issue for Slack)

**Comment by rephus** [comment]
Backend merged, frontend will be done on a separate PR
