### ISSUE TITLE
Notify the user if an exported CSV has reached it's limit

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6688]
### Description

If a CSV reaches the limit then it silently truncates the data, which has caused some users to lose trust in the exports.

- [ ] If downloading through the UI and the CSV reaches a limit, show this in the UI when the download is complete
  - [ ] Make this a warning that appears in the UI which says:
    - [ ] **The results in this export have been limited.** 
            Your results were 150,000 cells, but the export limit is 100,000 cells.`
  - [ ] rename the file so it says `incomplete-results-` at the start
- See this Miro sketch for slack + email (single chart + dashboard) warning states: https://miro.com/app/board/uXjVP1D_L4w=/?moveToWidget=3458764563149170505&cot=14

**Comment by gui-brandalley** [comment]
Hi, is there any expected date for this one?
It would be very useful in our case.
