### ISSUE TITLE
It should show an error and fail when you `stop-preview` an incorrect project

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6698]
### Description

It should show an error and fail when you `stop-preview` an incorrect project

- this should not say done: <img width="434" alt="CleanShot 2023-08-10 at 20 24 11@2x" src="https://github.com/lightdash/lightdash/assets/962095/3340812c-f9fe-4039-a140-e0eaaba53c53">

- this is an example how it should display the error: <img width="410" alt="CleanShot 2023-08-10 at 20 24 23@2x" src="https://github.com/lightdash/lightdash/assets/962095/19552bf0-8ca7-445c-a9e0-5c360e672502">

**Comment by jayanand05** [comment]
working...

**Comment by jayanand05** [comment]
Working on it .

**Comment by jayanand05** [comment]
working..
