### ISSUE TITLE
broken scrolling when showing preview + dashboard living in charts banners

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6722]
### Description

broken scrolling when showing preview + dashboard living in charts banners

1. full screen pages like sql runner or explorer should not have a scroll
   <img width="1287" alt="CleanShot 2023-08-11 at 20 09 47@2x" src="https://github.com/lightdash/lightdash/assets/962095/70b9eaa2-d3ff-4a9d-9638-b265cab15a02">

2. two scrollbars appearing on the homepage

https://github.com/lightdash/lightdash/assets/962095/1d375cbf-7a3d-4981-a06b-986cb45c94d8

**Comment by hrutik7** [comment]
hey @IrakliJani i think this is fixed right ?
if not then I would like to work on it :)

**Comment by IrakliJani** [comment]
hi @hrutik7 this is still relevant, I can see the same when creating a chart from the dashboard

https://github.com/lightdash/lightdash/assets/962095/8a708717-4ae1-473d-9d13-3c7678cf13ec

**Comment by IrakliJani** [comment]
done!

**Comment by karan0handa** [comment]
Seems like the same issue: #6430

**Comment by IrakliJani** [comment]
@karan0handa, yeah, closing in favor of #6430
