### ISSUE TITLE
Ability to see sorted values in tooltip for grouped chart totals

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6723]
### Description

User is seeking an option to sort by the totals of stacked bars. This functionality isn't present currently. The suggestion is to introduce this sorting option within the configuration panel but this can also be a default

<img width="375" alt="CleanShot 2023-08-11 at 20 49 09@2x" src="https://github.com/lightdash/lightdash/assets/962095/b09d0d37-cb4a-41b5-8589-fce4384bd9ec">

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of this: https://github.com/lightdash/lightdash/issues/10547
