### ISSUE TITLE
dashboard filters not applied in drill into/underlying data for pivot tables

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6726]
### Description

When using the "drill into" or "underlying data" functionality on pivot table tiles in the dashboard, the top-level dashboard filters are not being carried over to the explore tab.

dashboard
![CleanShot 2023-08-14 at 13 05 48@2x](https://github.com/lightdash/lightdash/assets/962095/84e09443-3a00-429f-9504-94c7afcea4ef)

filters after underlying data, drill-into
<img width="886" alt="CleanShot 2023-08-14 at 13 05 30@2x" src="https://github.com/lightdash/lightdash/assets/962095/e9782a36-2c97-4f52-89cb-7ff344381bbe">

**Comment by joaoviana** [comment]
The work on this was reverted; Find solution that is more performant
