### ISSUE TITLE
Migrate Boolean Filter input to Mantine

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6727]
### Description

In: `/packages/frontend/src/components/common/Filters/FilterInputs/BooleanFilterInputs.tsx`

Migrate Boolean Filter input to Mantine ahead of the work to be done on: https://github.com/lightdash/lightdash/issues/6490

screenshot reference: 

<img width="360" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/c25ebde8-ecd0-4729-b799-419e91562d62">

### What problem does this solve?

Supports the complete migration of the Filter UI

**Comment by ho-dor** [comment]
@joaoviana @owlas can I work on this and some other issues which are part of this [milestone](https://github.com/lightdash/lightdash/milestone/113)  ? Thanks.
