### ISSUE TITLE
Migrate Number Filter input to Mantine

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6728]
### Description

In: `packages/frontend/src/components/common/Filters/FilterInputs/NumericInput.styles.tsx`

Migrate `NumericInput` Filter input to Mantine ahead of the work to be done on: https://github.com/lightdash/lightdash/issues/6490

screenshot reference: 

<img width="360" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/e2446667-85bd-4790-95db-efa818d22ed3">

### What problem does this solve?

Supports the complete migration of the Filter UI

**Comment by IrakliJani** [comment]
this one is tag input described here https://github.com/lightdash/lightdash/issues/7317
