### ISSUE TITLE
Migrate Date Filter inputs to Mantine

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6729]
### Description

`WeekPicker`
* when time frame is `Week` see: `TimeFrames`

<img width="379" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/ebe1b751-dab3-4bb5-8bef-ed30b7a2d53f">

`DateInput2`

* for timestamps
* for operators like: `is` `is not`

<img width="375" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/0dad6af5-b2d1-43b5-aed9-04df0b61b37a">

`UnitOfTimeAutoComplete`
* for operators like: `in the last`, `in the current`

<img width="366" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/331ef8d3-dfe6-4cc7-8e35-2757a463cc7d">

StyledDateRangeInput
* for the operator: `is between`
<img width="427" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/075bd567-193e-443f-9904-dbf824d44476">

Migrate these in individual PRs ahead of the work to be done on: https://github.com/lightdash/lightdash/issues/6490

### What problem does this solve?

Supports the complete migration of the Filter UI

NOTE: 
`MonthAndYearInput` and `YearInput` are already Mantine

**Comment by IrakliJani** [comment]
some of the items are done here, created separate tickets for remaining components. closing in favor of them
