### ISSUE TITLE
Saved filters don't reset after clicking reset or removing the filter value

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#6758]
### Description

I have a dashboard with a saved filter ("is any value" by default). As a user, if I then add a value to the filter and apply it, everything is normal so far. However, if I want to then remove that filter (not replace with a different value, but reset it completely), it seems I cannot. The "reset to original value" button doesn't seem to work. It just removes the value from the filter window, but because the "Apply" button then becomes inactive, the filter remains applied, and the filter value still shows on the filter button at the top of the dashboard when I close the filter window.

### To Reproduce

1. Open a dashboard that has saved filters
2. Click on a filter.
3. Enter a value in the text box
4. Click apply
5. Click on the filter again
6. Click the "reset to original value" button
7. No further action possible. The value in the text box will disappear, but you won't be able to click apply, or switch the filter back to "any value"
![image](https://github.com/lightdash/lightdash/assets/135957659/378766be-69ec-4f98-9753-4f2e752a975f)

### App Version

v0.741.0

**Comment by hamzahc1** [comment]
Hey @mhawkins-runa - thanks for reporting, we already have a bug for this that should close in the next couple of days - I'm going to close this issue in favour of that one https://github.com/lightdash/lightdash/issues/6686
