### ISSUE TITLE
Default value toggle applies to the value and not the operator, but it is placed above the operator

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6761]
### Description

The default value toggle applies to the value and not the operator, but it is placed above the operator. This can be confusing for users. 

Solution:
Instead - we can move the toggle below the value field 
<img width="492" alt="CleanShot 2023-08-15 at 19 36 55@2x" src="https://github.com/lightdash/lightdash/assets/14341285/f61329d4-2850-404b-b4d6-34ff460db464">

Acceptance Criteria: 

- [ ] Default value toggle is below the input field
- [ ] When toggle is `off` - if you hover on the greyed out `any value` field - a popover should appear with copy: "Turn on default values to set a value for filter"

**Comment by PriPatel** [comment]
@magnew I liked your copy suggestion before : "Provide default value"
