### ISSUE TITLE
Update project settings to connect to the dbt semantic layer

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6767]
### Description

- [ ] Add a `url` input since each user can be in a different region. [dbt docs ](https://docs.getdbt.com/docs/cloud/about-cloud/regions-ip-addresses) more info here: https://lightdash.slack.com/archives/C03MNR8L51C/p1700493892544309
- [ ] Update dbt integration page to store an `environmentId` instead of the job id
- [ ] Update backend to use stored credentials instead of environment variables
- [ ] remove `hasDbtSemanticLayer` from health endpoint

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - we'll be builing a new project connection settings page instead
