### ISSUE TITLE
Custom Percentile Metric is missing option to set the percentile.

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#6773]
### Description
it's not possible to specify the percentile value, e.g. 10th percentile, etc. when defining a custom metric with `percentile` type.

We should add `percentile` as a field where they can input an integer value between 0 - 100. THis should sit above the `filters` toggle.

### To Reproduce
1. Click on the 3-dot menu on a numeric dimension
2. Select "Add Custom Metric">"Percentile"
3. There isn't an option to define the percentile

![image](https://github.com/lightdash/lightdash/assets/7281432/e1f20a56-c1ea-466b-a3aa-4cca668270eb)

### App Version
0.744.1

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey @gordonkjlee 

I'm not too sure I understand what the bug is here 🤔 this sounds more like a feature request than a bug. 

Where did you hear that percentile custom metrics were an option? Or were you just expecting that they would be a type that was available?

**Comment by TuringLovesDeathMetal** [comment]
ah, I see - what bit of it isn't configurable? 

We have a "standard" option for all of the custom metrics where you're able to add filters to the custom metrics, but that's the only configuration option available. 

Is there another configuration you'd want to see for percentile metrics?

**Comment by TuringLovesDeathMetal** [comment]
great point 👀 

I haven't used the percentile custom metric yet, (only pre-defined in the .yml). 

Here's teh description for defining it in the .yml: https://docs.lightdash.com/references/metrics#percentile

So yep, we're missing a bit which asks what percentile you want

**Comment by TuringLovesDeathMetal** [comment]
I've updated the description and added it to the backlog! Thanks for flagging this @gordonkjlee 🙏
