### ISSUE TITLE
I want to create an index tile/table of contents at the top of my dashboard 

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6804]
### Description

Users would like to be able to create a _table of contents_ on their dashboard so they can link to tiles in their dashboard. 
In this way, the viewer would click on the link and it would highlight and/or scroll to the chart that corresponds to the link. 

### What problem does this solve?

Smooth UX in dashboards

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned. There's a larger piece of UX work around navigating through dashboards (e.g. dashboard tabs, dashboard table of contents, etc.). 

This feels like a single ticket that will become a larger part of a holistic effort! I don't think it will be tackled as an independent feature.
