### ISSUE TITLE
Unable to join workspace when signing up with gmail account.

### ISSUE THREAD

**Issue by ujwalkumar1995** [lightdash/lightdash#6816]
### Description

I created an account on lightdash with my gmail. It suggested me join Bermeo workspace as it is open to people with @gmail account. When I try to join it, I get 403 forbidden on the network tab saying "User already has an organization". 

### To Reproduce

- Try to sign up with a account on lightdash using your gmail. 
- Try to join the Bermeo workspace. 
- You would get 403 error. Also it would be optimal if it would be somewhere on the screen. As I don't get any feedback on the screen, I checked it from network tab.

I feel there are two problems here, I should not get 403 error as I don't have an organization. Secondly, even if I do, I should get feedback on the screen and should not have to check in network tab for the error.

### App Version

Tried to sign up on the official website.

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned - currently, in Lightdash you cannot use the same email for multiple organizations. This error likely happened because you already had a Lightdash account created.
