### ISSUE TITLE
When I export the data from a table visualization that's pivoted, I want the pivot to be kept in the export.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6838]
### Description

Right now, if I try to export the results from a table visualization that's pivoted, the results are exported un-pivoted. 

e.g. this table:
<img width="1459" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/c4b0d632-76dd-4517-be5c-7cb4ceb6be60">

exports to a .csv that looks like this:
<img width="464" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/ad1996c2-f8d7-43cf-80be-bd9b5060f189">

I want to be able to export my .csv so that the pivot is maintained. 

### Acceptance criteria

- [ ] If I have a pivoted table, then the data is maintained in that format in my .csv or google sheets export. 
- [ ] For tables with pivots and multiple measures, each pivot value is repeated across columns rather than represented as one merged column.

E.g. in this image, the month would be repeated across columns in the exported file:

<img width="1497" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/65da6382-05a9-43d3-a274-ea30027c30bd">

### Tech notes

We already have the logic to pivot data in `/packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts` without dependencies on React. We need to move this file to the common package so it can be used by the FE and BE.

We need have to change the methods `convertSqlQueryResultsToCsv` and `writeRowsToFile` in `packages/backend/src/services/CsvService/CsvService.ts` to handle the new pivoted data.

All the places where the user can export a CSV:
- Explorer
- SQL runner
- Chart
- Dashboard
- Scheduled deliveries

**Comment by etadelta222** [comment]
+1

**Comment by agha4to** [comment]
Hi, I've started looking into implementing this.

**Comment by hamzahc1** [comment]
hey @agha4to are you already working on this? If not we might reassign it to someone internally as we'd like to prioritise the ticket. Let us know if you have a PR/draft PR you'd like us to review. If not, we'll reassign :)

**Comment by agha4to** [comment]
Hi, Hamzah 👍 I started looking at this a couple weeks ago, but I don't have any code. I would probably not be able to start again until sometime next week at the earliest.

**Comment by hamzahc1** [comment]
Thanks for the update! In that case we'll reassign it for now!
