### ISSUE TITLE
I want to be able to see which preview projects are inactive

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6839]
### Description

Sometimes, people forget to delete preview projects once they're finished with them. This can lead to a bunch of preview projects that are inactive, cluttering the `projects` selector. 

But, as an admin, it's hard to know which of these projects are still in use vs. which are inactive and you're able to delete.

There should be a way to distinguish between inactive vs. active preview projects.

### Acceptance criteria

- [ ] When a preview project has not been interacted with for 48 hours, it gets tagged as `inactive`. 
- [ ] `active` means: there has been at least one query run in the project in the last 48 hours OR the project has been compiled in the last 48 hours.
- [ ] In the `all projects` list, there's a flag that says `inactive` (beside `preview`). 
- [ ] On hover, the pill has helper text which says `No one has run a query in this project for the last 48 hours`
<img width="962" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/661d5989-9605-44de-ab82-faac6def671e">

**Comment by PriPatel** [comment]
Rather than add another pill,  could the existing pill just say inactive preview? (and maybe be a different colour?)
(just conscious that theres a lot going on in this table already, and there is lots fighting for my attention. Adding another pill will add to cognitive load)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as a duplicate of https://github.com/lightdash/lightdash/issues/3733

^I feel like this is a sub-issue of a wider issue which is that the preview projects aren'y being deleted automatically. If tehre was an automated deletion process that made sense, tehn this wouldn't be an issue.
