### ISSUE TITLE
The spacing in between the first two filter buttons is smaller than the others

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6851]
<img width="754" alt="Screenshot 2023-08-23 at 10 15 42" src="https://github.com/lightdash/lightdash/assets/12776522/454636aa-829e-409d-81bb-0c49a6d1a02c">
The space in between `Add filter` and the first filter is a lot smaller than the space in between the first two filters.

**Comment by ujwalkumar1995** [comment]
Hey @PriPatel 
I would like to work on this issue. Could you please assign?
