### ISSUE TITLE
Adding a dashboard filter on July 2023 causes the date filter to actually filter on June 30th, 2023 causing no results

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6902]
### Description

https://www.loom.com/share/00a2564c9fbe4747ba321a7de8f92778

### App Version

I think this might have something to do with timezones? (maybe) 

Both me and the user that was also running into this issue are in GMT + 2 (i.e. Paris/Berlin time)

**Comment by IrakliJani** [comment]
same but with year picker when I select 2020 as a year
<img width="505" alt="CleanShot 2023-08-28 at 18 31 44@2x" src="https://github.com/lightdash/lightdash/assets/962095/f6070f71-0580-40a6-af84-691642324ccf">
