### ISSUE TITLE
Custom Percentile metric not saving correctly and defaults back to 50%

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#6904]
### Description
Custom percentile metrics do not appear to be setting/saving correctly. I can create custom percentile metrics and create nice charts, but when these are revisited (e.g. refresh the page, or add it to a dashboard and see it there), all the percentiles show the median (i.e. 50th percentile).

### To Reproduce
1. Open new query
2. Create custom percentile metric at 10%
3. Save the chart (even without any metrics selected or graphed)
4. Refresh the page and inspect the custom metric again (this will now show as 50%)

### App Version
0.757.1

**Comment by TuringLovesDeathMetal** [comment]
@gordonkjlee thanks for flagging this! We're fixing this now - should be out today or tomorrow 👀
