### ISSUE TITLE
Intermittent dashboard crash 

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6905]
### Description

We are seeing an intermittent dashboard crash. It's not 100% consistent, but it seems to happen most when a dashboard is reloading right after being edited. There are some console logs that are not especially helpful but look related.  

<img width="1461" alt="Screenshot 2023-08-28 at 15 00 16" src="https://github.com/lightdash/lightdash/assets/1864179/b61db29e-ef7b-4085-880d-55402b447acb">

### To Reproduce

This isn't always re-producible, but it's fairly consistent with the following steps.

1. Create a dashboard with a couple charts.
2. Edit the dashboard. 
3. Edit a chart. 
4. Change the chart name. 
5. Click 'Return to dashboard' 
6. Before the dashboard is fully reloaded, it often crashes

### App Version

Version: v0.758.0

**Comment by TuringLovesDeathMetal** [comment]
Could this be related to the dashboard refresh work we shipped? (since we're only seeing it today 👀 )

**Comment by magnew** [comment]
> Could this be related to the dashboard refresh work we shipped? (since we're only seeing it today 👀 )

Yes, very much.
