### ISSUE TITLE
Non-default filters are ignored when exporting a dashboard

### ISSUE THREAD

**Issue by christian-endres** [lightdash/lightdash#6906]
### Description

When exporting a dashboard as an image, the dashboard is always rendered with the default filter values.

This seems to be caused by the `UnfurlService` not appending the filter query params to the "minimal" URL in 
https://github.com/lightdash/lightdash/blob/d59cae8c23763ce2535f27b94a060b63f21cf30b/packages/backend/src/services/UnfurlService/UnfurlService.ts#L228

### To Reproduce

1. Go to a dashboard and change a filter value
2. Go to "Export dashboard"
![image](https://github.com/lightdash/lightdash/assets/126677954/5738da17-f392-4ae4-ae3b-57d9a52684ac)
3. The screenshot is rendered with default filter values

Note: The screenshot is only opened correctly if https://github.com/lightdash/lightdash/issues/6546 is fixed/worked around.

### App Version

`v0.705.1`

**Comment by TuringLovesDeathMetal** [comment]
👋 Hi @christian-endres!

Thanks for opening this issue - I've added this to the backlog (as well as the other issue you've linked) and someone will look into it soon 👀

**Comment by tlfbrito** [comment]
👍
