### ISSUE TITLE
I want to create a default value for a user attribute

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6910]
### Description

Right now, to assign everyone in your company to a user attribute, you'd need to manually assign each individual. Instead, I'd love to be able to set a default value for users, then I can adjust the default value after that. 

This means I only need to assign specific values to a handful of users (instead of trying to set values for every user in my instance). 

### Acceptance criteria

- [ ] Above `assign to users` there is a section called `default value` which has a toggle that's default off
<img width="656" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/e2adbf17-643c-4ec7-9b2c-d6e0aee206fd">
- [ ] If you toggle it on, then there's a text box that appears where you can enter a value
- [ ] There is an info icon beside `default value`. On hover, the text says `Use this to assign a default value for this attribute to all users in your organization. Adding specific user values below will override this default (it will not add to the default value).`

**Comment by rephus** [comment]
+1 to this feature. I thought about this when we built this some time ago
