### ISSUE TITLE
Remove feature flag on charts created within dashboards

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6913]

**Comment by magnew** [comment]
> Hey @TuringLovesDeathMetal I would like to contribute on this issue. As per my analysis, I could only find one usage of this flag in AddTilesButton.tsx. Please let me know if that is what we need to fix as part of this issue and I would be happy to submit a PR.

Hi @ujwalkumar1995, this is an internal tracking ticket for removing that flag when the feature is ready. There are a few more things that need to be done first. You are right that it is just that one flag, but we aren't ready to do it yet.
