### ISSUE TITLE
I want an option to `send now` in my scheduled delivery

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6927]
### Description

I want an option to `send now` in a scheduled delivery. This would send the delivery immediately. 

You could also schedule the delivery to send regularly. 

This is helpful in testing a delivery, but also in sharing files via email or slack to large groups of users instead of copy-pasting a link everywhere.

**Comment by PriPatel** [comment]
Related to https://github.com/lightdash/lightdash/issues/4380 !

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/4380
