### ISSUE TITLE
The icons in the two main tabs in the navbar ('New' + 'Browse') should be the same size as other icons in the navbar 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6952]
**Before:**
<img width="1127" alt="Screenshot 2023-08-31 at 15 58 41" src="https://github.com/lightdash/lightdash/assets/12776522/3c431280-9199-4ecc-8fa7-8337e460f3d6">
There is a mix of heights in the icons across the navbar. 

**After:**
<img width="1124" alt="Screenshot 2023-08-31 at 15 58 30" src="https://github.com/lightdash/lightdash/assets/12776522/f51433d6-63ec-443f-9a48-e0a71f905e92">
All icons are 16 x16 and align a lot better. Its ok for the icons to be smaller in the tab as they are more decorative, than crucial

- [ ] Update the icons in the `New` and `Browse` tab to be 16 x 16

**Comment by ujwalkumar1995** [comment]
Hey @PriPatel 
I would like to contribute to this issue. Could you please assign?

**Comment by PriPatel** [comment]
Hi @ujwalkumar1995 , thanks , yes please go for it :)
