### ISSUE TITLE
Reference user email with `${ lightdash.user.email }` in `sql_on` and `sql_filter`

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6955]
### Description

Developers can already reference user attributes with `${ lightdash.attribute.name }` in `sql_on` and `sql_filter` clauses in yaml but since we already have access to the user's email, it isn't necessary for them to add an attribute for email. Instead we can expose this at `${ lightdash.user.email }`

### Docs

Update the user attributes docs to include this: https://docs.lightdash.com/references/user-attributes

**Comment by walkabout21** [comment]
We need this feature in order to implement sso  login based fine grain access controls

**Comment by timhiebenthal** [comment]
Yes, please!
If it's already available anyway it would be a low-hanging fruit to make row-level-security even more powerful :)
