### ISSUE TITLE
Sync modal needs scrolling after adding a sync 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#6968]
### Description

After adding a sync, the button to add new syncs is "hidden" 

### To Reproduce
[Screencast from 01-09-23 09:50:08.webm](https://github.com/lightdash/lightdash/assets/1983672/9517b6d1-c748-445e-8a99-8ac9e526dfe0)

### App Version

v0.762.0

**Comment by rephus** [comment]
@joaoviana FYI

**Comment by joaoviana** [comment]
interesting, the `ScrollArea` component I added from Mantine doesn't work on this `Stack` anymore? 🤔

**Comment by karan0handa** [comment]
Issue is in `SyncModalView.tsx:29`

```typescript
<ScrollArea h={450}>
```
This fix seems to work. It seems that the max-height of the `mantine` `Paper` (inside `Modal`) is `calc(100dvh - (8.75rem * 2))` 
```typescript
 <ScrollArea h={'calc(100dvh - (13rem * 2))'}>
 ```
