### ISSUE TITLE
Unable to connect to dbt project referenced as a package in a separate dbt project

### ISSUE THREAD

**Issue by loicchamberlin** [lightdash/lightdash#6997]
### Description

I wanted to connect my gitlab repository that contains a dbt project to lightdash. We can call it project A. 
In the packages.yml of project A, I reference another dbt project, also contained in a private gitlab repository, Project B. 

The thing is, Lightdash doesn't seem to be able to retrieve the repository project B while testing the connection to project A on lightdash. 
I made sure to use a Personnal Access Token that has the rights to access project B from project A.

### To Reproduce

1. On Gitlab, Create two repositories with dbt projects in it, A & B. Both private.
2. Add project B into the packages.yml of project A.
3. On lightdash, Configure the connections settings witht the right data and path to the repository project A.
4. Add the configured Personnal Access Token with correct rights.
5. Test & Compile project

See the error : 
<img width="549" alt="image" src="https://github.com/lightdash/lightdash/assets/82515518/da1a993f-994b-45f0-a68a-36ebf91825cc">
 
### App Version

v0.726.0

**Comment by TuringLovesDeathMetal** [comment]
(Just so we can understand if this is an issue of it being referenced as a package, or if it's an issue with `project B` itself 👀 )

**Comment by loicchamberlin** [comment]
Hi @TuringLovesDeathMetal !

We are working in a data mesh approach with one dbt project per data product and also one dbt project for all our common macros. This means that all our dbt projects import via the package.yml our common data product (which is a dbt project).
Getting back to our example, there is no problem with project B which in terms of dbt should just be seen as any other packages. The problem here seems to stem from the fact that this project B is a private repository and lightdash does not seem to be able to import it. This is how we define it in the packages.yml.

- git: git@gitlab.com:a8042/data-analytics/dp-common.git
  revision: main
  warn-unpinned: false

The git token we have provided in the setup of data product A has access to this git repo of data product B as well.

**Comment by charles-astrafy** [comment]
Hi,

Very interested in that feature as well as having multiple dbt projects (each in private git repositories) that call one each other is quite common. And it seems lightdash cannot leverage the git credential provided for the original dbt project to fetch other private dbt projects located in the packages.yml.

**Comment by ZeRego** [comment]
Hi 👋 
When using private packages, they need to be defined in a different way. You can see dbt docs on the different ways you can do it.
https://docs.getdbt.com/docs/build/packages#git-token-method

The necessary environment variables can be set in the project settings:
https://docs.lightdash.com/get-started/setup-lightdash/connect-project#environment-variables

<img width="883" alt="Screenshot 2023-09-18 at 16 31 06" src="https://github.com/lightdash/lightdash/assets/9117144/475d3c24-fafa-4ebf-952d-8edd321c0297">

**Comment by loicchamberlin** [comment]
Hi, 
I made the changes to test it out. It is working using this methodology but it is a HTTPS connection, which isn’t what we had in mind to use.

Internally, we’re SSH to import other data-product repository (calling these **project B**) in dbt in our working repo (**project A**). We have noticed that the Personnal Access Token, used in lightdash during the configuration, was only used to retrieve the configured repository (project A).

While this PAT is configured to be able to access project B also. It feels like the lightdash configuration doesn’t accept the SSH connection using the PAT already put in there.

**Comment by ZeRego** [comment]
> It feels like the lightdash configuration doesn’t accept the SSH connection using the PAT already put in there.

SSH requires a SSH key and can't be used with a PAT. 
PAT is commonly used in SASS integrations because it can have fine grained scopes/permissions. 

> We have noticed that the Personnal Access Token, used in lightdash during the configuration, was only used to retrieve the configured repository (project A).

Perhaps we could expose the PAT as a environment variable, but it still requires to change the package url to use https connection and concatenate the environment variable. Developers would also have to define that env var in their machines.
