### ISSUE TITLE
Clicking on the dashboard name in the list popovers does not take me to the dashboard

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#7023]
<img width="511" alt="Screenshot 2023-09-06 at 09 48 50" src="https://github.com/lightdash/lightdash/assets/12776522/59a3c65c-8947-4100-9855-98e34ea1df10">

Current behaviour
  - Hover over a chart in list view
  - Click on one of the dashboard links
  - The chart you were hovering over opens up in the same tab

Expected behaviour
  - Hover over a chart in list view
  - Click on one of the dashboard links
  - The dashboard you have clicked on opens up in a new tab

**Comment by nimit9** [comment]
I'd like to work on this issue

**Comment by PriPatel** [comment]
@nimit9 Thanks - Please go for it :)

**Comment by nimit9** [comment]
Have raised the PR for the fix. Please let me know if there are any changes needed.

> @nimit9 Thanks - Please go for it :)
