### ISSUE TITLE
Refactor UnfurlService->getUserCookie()

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#7027]
### Description

At the moment our server makes a request to our own API to get a user cookie. See UnfurlService->getUserCookie()
eg: https://example.lightdash.com/api/v1/headless-browser/login/{hash}

This seems to cause some issues for users with self-signed certificates.

```
error: Handled error of type UnexpectedServerError on [POST] /api/v1/dashboards/{uuid}/export FetchError: request to https://ld-temp.xxxx.vpn/api/v1/headless-browser/login/{hash} failed, reason: connect ETIMEDOUT 192.168.2.162:443
```

Ideally, PassportJS would have a method to get a user session/cookie but we haven't found one. Alternatively, we could fetch the session from the database ( table sessions )

btw: There is a chance where this doesn't work.

**Comment by rephus** [comment]
Some time ago I explored these options before building the endpoint to get the cookie. 

- PassportJS would have a method to get a user session/cookie

I couldn't find anything for this, most functions to handle cookies are internal and are not exposed on the library. 

- Alternatively, we could fetch the session from the database ( table sessions )

The database only contains part of the cookie, or an enconded version. I looked at the sourcecode to find how to reconstruct the full cookie , but I couldn't find anything simple enough, but I guess it is possible. 

I'm happy to help or pair on this, but it would be nice to have a fresh pair of eyes here.

**Comment by ZeRego** [comment]
@rephus What if the login endpoint redirects to the url that we want ?

Current flow:
1. authenticate user by calling our own API request `/api/v1/headless-browser/login/{uuid}` to get the cookie
2. load chart/dashboard url in puppeteer with cookie from step 1 

Suggested flow:
1. load `/api/v1/headless-browser/login/{uuid}?redirectUrl={chart_url}` url in puppeteer
  1.1 that route will authenticate the user and redirect to the chart/dashboard page with the correct cookie

**Comment by rephus** [comment]
Yeah, good idea, that might work, we'll have to be careful and implement the make sure we wait for the redirection before taking the screenshot in puppeteer. I still think we should timebox investigating `fetch the session from the database`, if we can generate the cookie locally, I think is going to be more stable than the redirect.

**Comment by ZeRego** [comment]
Users should set the env var `INTERNAL_LIGHTDASH_HOST` so these requests go via internal ip/domain rather than public internet.

[docs](https://docs.lightdash.com/self-host/customize-deployment/environment-variables)
> Internal Lightdash host for the Headless browser to send requests when your Lightdash instance is not accessible from the Internet.
