### ISSUE TITLE
Investigate how to improve page load

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#7057]
### Description

Goal:

- [ ] investigate main problems
- [ ] find solutions
- [ ] create actionable tickets

Context:

Using Chrome performance insights, with fast internet (450mbps) it took 9 seconds to load the home page.
![Screenshot 2023-09-08 at 15 05 58](https://github.com/lightdash/lightdash/assets/9117144/aad3010f-e0a7-4fc1-87ac-802a46475df9)

It took 4.39 seconds just to have the DOM content(html, js, css) to be loaded:

![Screenshot 2023-09-08 at 15 11 34](https://github.com/lightdash/lightdash/assets/9117144/db92b640-5265-4fe3-82da-13bb60c59407)

The assets are cached in the browser but we deploy everyday, creating new assets and forcing the browser to loading again the assets.

Ideas:
- if we finish the Mantine migration we won't need the blueprint assets
- can we reduce the size of the index.js by using react suspense?
- configure build to only optimize for the latest browser versions
- minify css files

### What problem does this solve?

Do not have to wait several seconds for the Lightdash pages to load.

**Comment by joaoviana** [comment]
Ensure we're serving gzipped assets: https://github.com/lightdash/lightdash/issues/7097
Minify CSS files: https://github.com/lightdash/lightdash/issues/7095
Spec in-memory cache to help with page load performance: https://github.com/lightdash/lightdash/issues/7099
