### ISSUE TITLE
When applying a string filter, ignore when filter value is empty 

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#7064]
### Current behaviour

Currently, when a user sets a filter of type string with an empty value, then it compiles as `WHERE (false)` which then yields no results. 

Example: 
<img width="1499" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/be5e4c98-00dc-4b4b-a866-d3de7ac1acea">

compiled query: 
```sql
SELECT
  `dbt_orders`.shipping_city AS `dbt_orders_shipping_city`,
  `dbt_orders`.partner_name AS `dbt_orders_partner_name`,
  COUNT(DISTINCT `dbt_orders`.order_id) AS `dbt_orders_count_distinct_order_id`
FROM `lightdash-analytics`.`lightdash_demo_gardening`.`dbt_orders` AS `dbt_orders`

WHERE ((
  false
))
GROUP BY 1,2
ORDER BY `dbt_orders_count_distinct_order_id` DESC
LIMIT 500
```

see `WHERE ((
  false
))`

### Expected behaviour

Nothing should affect the query if the filter is empty.

**Comment by ujwalkumar1995** [comment]
Hey @joaoviana 
I have raised a PR for the above issue. Could you please review?
I encountered couple of similar bugs. Raised #7083 and #7082 which may be related to this as well.
