### ISSUE TITLE
Add sidebar to SQL runner containing warehouse catalog

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#707]
To help the user to write a valid raw sql query, we should show the current state of the data warehouse catalog. We can group this by database/schema/table. 

One question @TuringLovesDeathMetal should we only show the catalog for a single database? Most warehouses cannot query across databases (bigquery being a notable exception) - so I think it makes sense for the UI to only show schemas in a single database. We could have a drop down at the top?

<img width="812" alt="Screenshot 2021-10-29 at 10 43 46" src="https://user-images.githubusercontent.com/11660098/139413699-57ccbe98-2249-4a5a-aabb-f038430cb47a.png">

**Comment by TuringLovesDeathMetal** [comment]
this has been completed
