### ISSUE TITLE
Increase expiration time of scheduled deliveries to 7 days

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7070]
### Description

Right now, scheduled deliveries expire after 3 days, but we want to increase this expiry date to 7 days. 

The reason being: I send reports to external folks using scheduled deliveries (they don't have access to Lightdahs, only to the deliveries I send them). 

if someone from a partner is on holiday / off sick, they can’t access their report.

7 days gives a much better lee-way for this (and if they're away beyond this time, I can resend the report).

**Comment by ujwalkumar1995** [comment]
Hey @TuringLovesDeathMetal 
I have submitted a PR for the above issue. Looking at the code I thought that this expiration time is configurable from env variables, so not sure if this change is even needed. Please feel free to provide any feedback if my understanding was wrong.

**Comment by rephus** [comment]
We've decided internally that we should keep the default as it is, and change the expiry via ENV variable when needed
