### ISSUE TITLE
I want to be able to toggle the links to my Lightdash project on/off in scheduled deliveries

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#7072]
### Description

This is related to [this issue](https://github.com/lightdash/lightdash/issues/6858), but slightly different.

- [ ] There is a toggle in the scheduled delivery configuration modal to `include links to Lightdash`
- [ ] This toggle only appears when the user has selected the `email` scheduled delivery format
- [ ] By default, the toggle is on.
- [ ] There is an `info` icon which, on hover, says:
  - [ ] `Include links to the shared content in your Lightdash project. We recommend turning this off if you're sharing with users who do not have access to your Lightdash project`
- [ ] When the toggle is off, the "View chart in Lightdash" link is omitted
- [ ] When the toggle is off, the "Scheduled delivery" text does not have a hyperlink

![image](https://github.com/lightdash/lightdash/assets/135957659/b2b94154-2bff-440f-a87f-68fb36eafd53)

### What problem does this solve?

This allows us to schedule deliveries to external recipients without giving them a weird UX where they get a link that they can't access.

**Comment by magnew** [comment]
Pulling in due to multiple customer requests
