### ISSUE TITLE
Vertical Legend option for charts

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7091]
### Description

add support for vertical legends in charts.
introduces new toggle in chart config.

![CleanShot 2023-09-18 at 12 13 51](https://github.com/lightdash/lightdash/assets/962095/61f629e3-9fb8-44ba-adbf-19eb3d5eaf9f)

**Comment by ayush117** [comment]
"Hello @IrakliJani, I've addressed the concerns in issue #7191. Could you please take a moment to review my work and provide feedback? Thank you!"
