### ISSUE TITLE
Add Sentry Dashboard for Dashboard page load performance insights

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#7094]
### Description

We currently have enough information on Sentry to analyse which rpc calls affect UX when viewing a dashboard. 
With this data, we can create a dashboard/chart to keep track of transactions of this type and allow alerting to our internal Slack Channels. We can also filter by instance/customer email domain, so that should also benefit observability granularity. 

To do: 
- [x] #7100
- [x] Enable Sentry Dashboards' feature
- [ ] Set up alerts

### What problem does this solve?

Observability and response readiness.

**Comment by joaoviana** [comment]
Blocked on enablement of dashboards in Sentry

**Comment by owlas** [comment]
enabled dashboards, made you admin @joaoviana

**Comment by joaoviana** [comment]
One for Frontend and another one for the Backend: https://lightdash.sentry.io/dashboards/
