### ISSUE TITLE
Investigate improvements to advise on Data warehouse configuration 

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#7098]
### Description

We suspect that a number of users reporting slow dashboards could see improvements in dashboard load times if they tune their data warehouse config to speed up multiple warehouse queries.

Questions: 
- [ ] Can people do this?
- [ ] Will it help?
- [ ] What advice can we give?

To achieve: 
- [ ] Add docs per warehouse type on out-of-the-box cache strategies

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. Can always reopen if we decide to dig more into dashboard performance at a later date!
