### ISSUE TITLE
Pie chart not showing all available series after DBT model update

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7103]
### Description

After updating items in the corresponding DBT model, the pie-chart in Lightdash is not showing all the available series for editing

temporary solution: rebuilding the chart from scratch resolves the problem.

At the time what happened was: we created the chart when the data had only a few series, after a few materializations the data started to have additional series but the chart was locked.

![CleanShot 2023-09-18 at 16 55 23](https://github.com/lightdash/lightdash/assets/962095/11c2ccee-54fe-441e-a7fd-2d762ac537bd)

**Comment by ZeRego** [comment]
See code from cartesian charts where we generate new series. 

https://github.com/lightdash/lightdash/blob/7c32c753398cadcb848c8eafa05bcba3ae2905bb/packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts#L561

**Comment by ZeRego** [comment]
We could not reproduce this issue.
