### ISSUE TITLE
Document dbt Semantic Layer integration

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#7110]
**Link to existing docs:** 

**Changes?**

Note: the following steps are necessary until we provide a way to configure it in the UI.

How to enable MetricFlow beta page on self host:

1. Add environment variables to the Lightdash deployment/server: `DBT_CLOUD_BEARER_TOKEN` and `DBT_CLOUD_ENVIRONMENT_ID`
  - bearer token: https://docs.getdbt.com/docs/dbt-cloud-apis/service-tokens
  - environment id: If your dbt URL ends with .../environments/222222, your environmentId is 222222
2. Restart server/lightdash
3. Visit page `/projects/{project uuid}/metricflow`

**Comment by joaoviana** [comment]
Also add reference to `DBT_CLOUD_DOMAIN`
