### ISSUE TITLE
Replacing data sources

### ISSUE THREAD

**Issue by zoehua123** [lightdash/lightdash#7117]
### Description

It would be great to have a feature that allows us to replace data sources that share the same fields for a table/chart whilst maintaining the layout and composition.

### What problem does this solve?

When renaming a table (sql file), it requires us to recreate entire dashboards since the tiles reference a table name that no longer exists

**Comment by ZeRego** [comment]
Looks duplicate of https://github.com/lightdash/lightdash/issues/5264

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/5264
