### ISSUE TITLE
Add calculated values (e.g. mean) to reference lines

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7120]
### Description

I want to be able to add a reference line that is based on a calculated value which is dynamic (e.g. mean, median, mode, percentile, max, min)

These values would be referenced in when I'm creating reference line using something like `${mean}`. 

### Acceptance criteria

- [ ] I'm able to add calculated values to my reference line
- [ ] these values update when the data in hte chart updates
- [ ] The values generated are always a constant (these are not trend lines)
- [ ] I'm able to use `mean`, `median`, `max`, and `min` to my calculated values
- [ ] I'm able to include `${percentile.value}` to calculate the percentile (e.g. `${percentile.10}`)

**Comment by magnew** [comment]
Closing as a duplicate of #8232
