### ISSUE TITLE
number of results missing from pivot tables

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7149]
### Description

number of results missing from pivot tables.

![CleanShot 2023-09-20 at 20 34 19@2x](https://github.com/lightdash/lightdash/assets/962095/50e8cf6f-588d-4e4a-b017-126d17626ae7)

![CleanShot 2023-09-20 at 20 34 25@2x](https://github.com/lightdash/lightdash/assets/962095/89c271ce-03eb-4c87-9a4b-fe759a04fb1f)

this is how it's displayed in results table
![CleanShot 2023-09-20 at 20 34 36@2x](https://github.com/lightdash/lightdash/assets/962095/2b8d117d-17ca-448d-9e98-3391cd7159e0)

**Comment by ho-dor** [comment]
[related comment](https://github.com/lightdash/lightdash/issues/6727#issuecomment-1736794658)

**Comment by IrakliJani** [comment]
hi @ho-dor, you can check out issues with https://github.com/lightdash/lightdash/labels/%F0%9F%99%8B%20good%20first%20issue label
