### ISSUE TITLE
I want to be able to specify email destinations for my threshold alerts 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#7150]
Blocked by  #3961  and [internal design ticket ](https://github.com/lightdash/lightdash-internal-work/issues/1011)

**The 'threshold alert' form**
- [ ] I should be able to set one or more email addresses as destinations. This should work similarly to 'scheduled deliveries'

**The email**
- [ ] - The email subject should show the alert message
- [ ] - The body message should reference the change and the original threshold
- [ ] - A pic of the latest chart should be attached.
- [ ] - A link to the chart should be shown 

**Open questions:**
- Does 'expiration' still affect these emails?

**Comment by rephus** [comment]
>     Does 'expiration' still affect these emails?

Yes, because we store the image in the same s3 repo
