### ISSUE TITLE
Enable adding a chart directly to a dashboard from the explores page

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#7154]
### Description

When saving a chart from the explore page, there is an option to add the chart to a space, but not a dashboard. It would be great to be able to choose a dashboard to add it to as well. 

This might just be an extra "Add to dashboard" field in the existing form, but it would be good to check with the design team.

**Comment by PriPatel** [comment]
Agreed, it could just an extra field, but we should be mindful of https://github.com/lightdash/lightdash/issues/7169 if we implement that to! We would need to make it clear that adding to a dashboard is very different to saving to a dashboard.

I imagine the form at this point would be quite long, so a little layout refactor might be needed!

**Comment by justabi** [comment]
@PriPatel what is the difference between adding to a dashboard and saving to a dashboard?
Saving to a dashboard (from the explore page) is likely more of a common use case

**Comment by PriPatel** [comment]
Closing in favour of https://github.com/lightdash/lightdash/issues/8711


@justabi So sorry for the very late reply - Adding to a dashboard adds a saved chart to it and the same chart can be added to multiple dashboards. Saving to a dashboard = the chart is only accessible through the dashboard and not through Spaces.
