### ISSUE TITLE
Identify react-query queries that we could optimise

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#7165]
### Description

We should consider caching the following queries: 
- [ ] /projects
- [ ] /org
- [ ] /user
- [ ] /health

<img width="403" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/766aae50-d58f-4237-97cb-29aa3f863d12">

### What problem does this solve?

Unnecessary re-runs of queries that don't change often

**Comment by amanx123** [comment]
I would like to work over this optimisation issue. Can you assign me ?

**Comment by joaoviana** [comment]
This work has been done on:https://github.com/lightdash/lightdash/pull/7865
