### ISSUE TITLE
Maximum update depth exceeded error when `cancelling` changes on a chart

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7179]
### Description

Fix error https://lightdash.slack.com/archives/C0234T34WEQ/p1695356088719519

**Comment by magnew** [comment]
I tried pretty hard to repro this, but couldn't get it with a normal (Jaffle) setup. It's possible something is changing in the data layer while they are editing that causes this loop? 

This definitely isn't very easy to hit. I suggest we close it as it's kind of unactionable.

**Comment by magnew** [comment]
Closing as unrepro-able. If we see if again we can revisit.
