### ISSUE TITLE
Handle timestamps with time offsets

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#718]
When we receive timestamps with time offsets from the database, we should convert them to UTC.

By normalising all timestamps on the backend, we can ensure correct conversion on the frontend.

**Comment by TuringLovesDeathMetal** [comment]
does this mean if I had a timestamp that I'd converted to be in California time in dbt, that we'd convert it _**back**_ to UTC?

**Comment by owlas** [comment]
Yes, specifically if you use the type `TIMESTAMP_TZ` which includes both a timestamp and a time offset with it. I think the general issue is that `TIMESTAMP_TZ` data can actually have a different offset for every row. 

I'm not sure what the best behaviour is to be honest but what we have now does not intentionally handle time offsets.

Today: timestamps are shown in the browsers local timezone. So if something is created at 1am UTC, then the time looks different to users in the UK vs. France. Not sure how that **should** work if the original timestamp is not in UTC.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego Have we done this? I feel like all of your work around timezones and timestamps might've solved this 😅
