### ISSUE TITLE
Scheduled deliveries UI/UX improvements using Mantine Library

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7185]
### Must haves: 
- [x] Migrate to Mantine (100%)
- [x] Add tabs up top
- [x] Take 'custom body message' option out of the first tab and into the second

### Other suggested changes (nice-to-haves):
https://www.figma.com/file/btY2rdBe5I2W4xLR3upmQG/Untitled?type=design&node-id=2981-3667&mode=design&t=CaSoABrNJ9hlLZx7-0
- [x] Change layout of frequencies to look nicer
- [x] `Format` selection should not be a dropdown. Both options should be visible at the same time.
- [x] .csv options could be hidden (either through a popover, or a accordion-type component)
- [x] Change destinations to https://mantine.dev/core/multi-select/ for slack and https://mantine.dev/core/tags-input/ for emails perhaps?

**Comment by magnew** [comment]
This is all done
