### ISSUE TITLE
Support `defer` in dbt for building preview environments

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7194]
### Description

If I use dbt's [defer flag](https://docs.getdbt.com/reference/node-selection/defer) for "Slim CI" so that the CI/CD pipeline only builds changed child models, but defers to unchanged parent models in the production schema/db, I'm not able to pass the same manifest.json with that information to Lightdash.

For example, I have the DAG `A -> B`, and I change the child model B.

My CI/CD builds B as `db.dev__feature_xyz.model_b` and uses `A` as it already exists in production; `db.prod.model_a.`

However, when I create a preview in Lightdash, and try to validate it, it complains that model A does not exist at `db.dev__feature_xyz.model_a.`

It seems like because the Lightdash CLI performs it's own dbt compile, it is not possible to configure the preview such that it expects defered models to exist under the prod schema/db. Eg. at `db.prod.model_a`.

So now, I'm forced to rebuild the entire project in a different schema/db if I wish to use previews and validate them.

**Comment by tnightengale** [comment]
@TuringLovesDeathMetal I have a PR in the wings for this :D 

My solution is to add an a option, `lightdash deploy --manifest=<path>` that enables users to skip the implicit `dbt compile` present in the `lightdash deploy` command, and pass an existing `manifest.json`.

Thus, anyone can run their own `dbt compile --defer` to create a `manifest.json` and deploy it.

Thoughts?

**Comment by tnightengale** [comment]
Upon further reflection, I think the cleanest approach is to just skip `dbt compile` since dbt will always place `manifest.json` in the project dir's `target/` folder.
