### ISSUE TITLE
Sidebar size should be fixed (even if the chart is big)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#721]
### Context
Right now, if you have a chart that's really wide, the sidebar is super tiny, and there's no way to make it bigger. 

This is a screenshot from my Mac (this isn't nearly as big of a problem on my extra monitor that's way bigger) 
![image](https://user-images.githubusercontent.com/31848148/139842973-57f81738-e670-421f-9323-ab187865e451.png)

### Goal
The sidebar shouldn't shrink if the chart is bigger - it should be a fixed width

**Comment by owlas** [comment]
@TuringLovesDeathMetal is the request that it shouldn't get smaller when the chart is fixed? This will be fixed in #784 

Or would you specifically like to be able to manually adjust the sidebar width? Or make it collapsed?

**Comment by TuringLovesDeathMetal** [comment]
yep, my actual complaint was that it shouldn't get smaller when teh chart is fixed! 

I don't have a requirement for adjusting/collapsing the sidebar width...(yet)... I'll update the title + close the ticket!

**Comment by TuringLovesDeathMetal** [comment]
not
