### ISSUE TITLE
Show static IP address on project connection form

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#722]
When connecting a project in Lightdash Cloud users need to whitelist the IP address in their warehouse.
It would be nice if we could show the IP in the UI. 
We could pass this as a env var and only show the UI if that env var is defined.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego when in the signup flow should this happen? Like, where in the signup flow will they get an error if they haven't whitelisted the IP address yet?

**Comment by ZeRego** [comment]
> when in the signup flow should this happen? 
Not only during signup but also when editing the project connection.
I think we should display this in the warehouse connection form. It could be above the form fields or on the left side.
> Like, where in the signup flow will they get an error if they haven't whitelisted the IP address yet?
I suspect they get an error when testing the connection but never tested this problem before.

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego is this still a thing?

**Comment by ZeRego** [comment]
Yes but low priority while we are in beta.

**Comment by ZeRego** [comment]
We should also have a docs page about this, similar to this https://www.metabase.com/cloud/docs/ip-addresses-to-whitelist.html
