### ISSUE TITLE
Stacking/grouping only available if at least one column is a string

### ISSUE THREAD

**Issue by Daniel-SalazarSoplapuco** [lightdash/lightdash#7225]
### Description
There is no possibility of stacking when the x-axis is non-string, or group when grouping series is nonstring.
For example, you create a graph that shows stacked on the x-axis the number of months between customer creation and first order. The Y-axis is the closed sales, you then want to group by the number of months between the first and closed sales month. 

You won't be able to either stack or group by.

Furthermore, when you use cast( as string), you lose the intended sorting.

### To Reproduce
Below an example of converting numerical x-axis and grouping series to string:
![image](https://github.com/lightdash/lightdash/assets/85174516/6af0c24d-8baf-41a1-b1b0-882d9d27c413)

### App Version

v0.786.1

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey @Daniel-SalazarSoplapuco 

Is this grouping issue happening in the SQL runner? Or in the Explore view?

**Comment by Daniel-SalazarSoplapuco** [comment]
Hi! This is indeed in the SQL runner.
Let me know in any way I can help this is a bit of a blocker for us.

**Comment by Daniel-SalazarSoplapuco** [comment]
This has been resolved Katie answered, that I need to sort them without the cast.
```
Select
cast(numerical column 1 as string) as x_axis,
numerical column 1 as y_axis
from table
order by numerical column desc
```

**Comment by Daniel-SalazarSoplapuco** [comment]
resolved through work arround
