### ISSUE TITLE
Change dbt cloud connection option 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#723]
### Context
A bunch of users have been connecting their Lightdash instance to their dbt project using the dbt cloud connection option. 

This experience is super janky and I think we should change it.

Here are my reasons:
- To get the dbt manifest files from dbt cloud, we need users to have the dbt cloud IDE open in their browser while their using Lightdash. This has cause a bunch of errors for users in onboarding (I've seen it happen at least 4x now)
- You have to connect your Lightdash instance to a development environment in dbt cloud. This makes it really hard to: invite other users to your Lightdash instance (can you even have multiple people in dbt cloud with teh same IDE open 🤔) 
- ^ this feature also makes it feel like it isn't a "production BI tool" (since it's not actually connected to your prod environment)

The reasons why we would keep the dbt cloud connection could be:
1. It makes the setup easier (this is _**sort of**_ true right now, but we've ended up just telling people to use GitHub/GitLab instead because it's more robust)
2. it makes it easier to use Lightdash (this, again, is sort of true: you see immediate changes in Lightdash synced to your dbt project...but it's connected to a dev environment, so not that useful...)

### Goal
Change the dbt cloud connection option (...or maybe remove it for now)

There are three options here:
1. **We keep the dbt cloud connection option as is, but update the connection instructions**. In the signup flow, we have a big warning box if they select the dbt cloud option and describe the limitations of it (it's only really for a single user in dev, you have to have the ide open, etc.)
2. **We improve the dbt cloud connection option**. We need to get the dbt manifest file from dbt cloud somehow...if this is possible, we could ditch the dependency on the dbt cloud IDE. But, this still keeps the limitation that you can only really have one user using it in the dev project.
3. **We remove the dbt cloud connection option.** This would mean that people have to connect their dbt project via GitHub or GitLab. We could eventually add it back (but I think we would need separate dev + production environments in Lightdash before it would be worth having the dbt cloud connection)

I vote # 3, but am interested to hear what y'all think!

**Comment by TuringLovesDeathMetal** [comment]
@hamzahc1 @ZeRego @owlas 👀

**Comment by owlas** [comment]
3 sounds good. I also just bumped into an unexpected problem because I connected using dbt cloud and didn't have a table materialised in my dev environment but I did in prod.

**Comment by hamzahc1** [comment]
Option 3 sounds good to me for the reasons mentioned. Is Option 2 something we want to revisit in the future? if so close this issue and we can open one, otherwise agree with points above!

**Comment by ZeRego** [comment]
I would prefer option 1 but if we are going with option 3, can we just disable/hide that option in the UI instead of deleting all of our code ?
