### ISSUE TITLE
Temp filters got lost when creating and in-dashboard chart

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#7264]
### Description

Temp filters got lost when creating and in-dashboard chart

### To Reproduce

1. Create a dashboard
2. Add a temporary filter
3. Add a new chart (not saved)
4. When you are re-directed to the dashboard the temporary filter is lost

Suggested fix: we are just not saving the tempt filters. We could.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned!
