### ISSUE TITLE
dashboard-level filters should override chart-level filters in the case that the chart is already filtering on the same field.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7268]
### Description

Right now, dashboard filters are "additive" to the chart filters in their tiles. For example, if I have a chart that's filtered on `date = 2023-01-01`, then a dashboard filter for `date = 2023-01-04`, the chart on that dashboard will be filtered on `date = 2023-01-01 AND date = 2023-01-04`. 

Instead, what I'm proposing is that if I have a chart that's filtered on a field, and it's in a dashboard where there's a filter applied to that _**same**_ field in the chart, then the dashboard filter should override the chart filter. 

Here's a really clear explanation of what the behaviour should be like: https://www.googlecloudcommunity.com/gc/Exploring-Curating-Data/Overriding-Look-Filters-in-the-Explore-Section-With-Dashboard/td-p/582846

### Acceptance criteria

- [ ] If I have a chart that is filtered on a field, then I apply a dashboard filter on teh same field, the chart filter should be overridden by the dashboard filter. 
- [ ] The operators _**do not**_ need to match, but the fields need to match.

### Why do we think this is a good idea? 

Right now, I have to create saved charts with no date filters (e.g. num users weekly) because otherwise, the chart could have data that's fltered in a different timeframe to everything else on the dashboard. If we added the `override`, then I could add a 14 week filter to my "num users weekly" chart so that when people open the saved chart, they're not running some massive query. But when it's added to a dashboard also being filtered on date, then the date filter could be overriden to 16 weeks (for example).

**Comment by ZeRego** [comment]
Replacing filter values without context is dangerous.

Example 1
Big number chart "Total revenue" has the filter `order_status=completed`.
If the Dashboard has a filter `order_status=pending` it will override the chart and the data won't match the title.

Example 2
Bar chart "Last week total revenue" has the filter `date in last 1 week`
If the dashboard has a filter `date=2023-01-04` it will override the chart and the data won't match the title.


What if the user can mark what chart filters can be overridden? 
In Example 1, the editor would not allow the `order_status=completed` filter to be overridden as the chart highly depends on it.

In Example 2, the editor would rename the chart to "Total revenue" and allow the date filter to be overridden. This way the chart filter would act as a default filter in case the dashboard doesn't have a different value.

In cases where the dashboard has `date=any` should the chart still apply its filter or remove the filter?

**Comment by TuringLovesDeathMetal** [comment]
Here's a proposal for how this could work:

1. We have the option when you're creating a saved chart to make a filter `required`. A `required` filter is _**additive**_ to the dashboard filters (not overriden). 
2. If you have a filter that is _**not**_ required on your saved chart, then the filter is _**overriden**_ by the dashboard filter. 
3. These `required` filters would be listed on the chart in the dashboard (so that it's clear to the end user why something isn't being changed by a dashboard filter): https://github.com/lightdash/lightdash/issues/8602

The way we would roll this out is:
- All of the filters on the saved charts would be set to `required`
- Moving forward, filters added to saved charts would _**not**_ be set to `required` (so, the default behaviour would be that chart filters are _**overridden**_ by dashboard filters). 
- This way no existing content would be broken, but new content would be different.

**Comment by coldborecapital** [comment]
@TuringLovesDeathMetal , I'm not sure you would need to specify if a filter was or wasn't required at the chart level. If you don't want a dashboard filter to affect a chart, you could just set the filter to not apply to that chart. Otherwise, the dashboard-level filter takes precedence. This is how they have filters configured in Looker, and it works quite well.

**Comment by TuringLovesDeathMetal** [comment]
Update on this:  the behaviour of dashboard filters is going to change. (we'll release this to everyone a week after this issue is closed)

# What's changing?

>## Dashboard filters will now override chart filters when filtering on the same field.

Here's a scenario:
  - I save a chart with a filter `date` = `in the last 1 month`
  - I add the chart to a dashboard
  - On the dashboard, I add a filter for `date` = `in the last 1 year` and apply it to the same chart. 

**Before:** The dashboard filter would be added to the chart filter. So, the chart would be filtered on `date` = `in the last 1 month` AND `date` = `in the last 1 year`. The result is that the chart will still only show data from `in the last 1 month`.

**Now:** The dashboard filter will **override** the chart filter. So, the chart will now be filtered on `date` = `in the last year` in that dashboard

Here's a video showing an example of the behaviour before vs. now.

https://www.loom.com/share/debd5c62d7874478b640a81a3eefa114

Note: This only affects filters applied to the **same field** in the dashboard + chart. All other dashboard filters will still be additive (so they will **add** to the chart filters with `AND`). 

---  

# How does it affect me? 

For most users, this shouldn't break anything. But, here are some things that will change:

## 1. Chart filters can no longer be used as a way to securely manage access to data.

Users can now override chart filters in a dashboard. That means if you're using chart filters as a way to manage access to data in a dashboard, then you'll need to consider using row-level security to do this instead. 

For example, I build a chart for total orders from a specific customer using a chart filter on `partner name` = `Redwood Ranch`. 

![image.png](https://cloud.headwayapp.co/changelogs_images/images/big/000/125/025-0c44363bd5c144bfc539039dc59c481ac4f0f619.png =100%)

If I add this to a dashboard which **_only_** includes charts with information about our Redwood Ranch partner, users (including Viewers) can override the `partner name` filter on the dashboard (e.g. change it to `partner name` = `Gardens of Sweden`). 

![image.png](https://cloud.headwayapp.co/changelogs_images/images/big/000/125/026-714b6180d88a3a3a65a42645c97af6a46febdc1e.png =100%)

This will result in a chart with `partner name` = `Gardens of Sweden`:

![image.png](https://cloud.headwayapp.co/changelogs_images/images/big/000/125/028-0e78a9b3e1c6c24a0743444e9b47fe051545b5f3.png =100%)

With these changes, you can no longer use chart filters as a way of reliably limiting access to data in a dashboard (since the chart filters can be overridden by dashboard filters). Instead, if you need to limit access to data for certain users, you'll need to use user attributes and row-level security. You can read more about [how to do this in the docs here](https://docs.lightdash.com/references/user-attributes#row-filtering-with-sql_filter). 

## 2. If you want to have two filters on the same field joined by `AND`, you'll need to add two filters to your dashboard. 

Before, if you had a filter on a chart and filtered the same field on a dashboard, they would be joined by `AND`. Now, if you want to have two filters on the same field joined by `AND`, you'll need to add two filters to your dashboard.

For example, before, if I had a chart with `partner name INCLUDES 'e'` and I added a dashboard filter for `partner name INCLUDES 'a'`, now to get the same behaviour, I'd need to add two filters to my dashboard: `partner name INCLUDES 'e'` and `partner name INCLUDES 'a'`.

![image.png](https://cloud.headwayapp.co/changelogs_images/images/big/000/125/038-d6bebca64660b5fa16935a8140eaa525a7509119.png =100%)

---

# Why are we making this change? 

We got a lot of user feedback that end users were expecting the dashboard filters to override the chart filters (since this is how it works in a lot of other BI tools). This caused confusion for users and we wanted to fix that.

The other feedback we got from users was that to reuse the same chart in multiple dashboards (especially time series charts), they couldn't add filters to the dates. This caused charts to be created from massive queries and relied on end-users knowing to filter the dates on the chart whenever they used it. 

Overall, we think that this is the behaviour that people are expecting and it's change for the better!

**Comment by ZeRego** [comment]
This feature was enabled for all cloud users today. Next week, we will remove the feature flag and the code related to the old behaviour.
