### ISSUE TITLE
Migrate NumericInput to Mantine

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7318]
### Description

![CleanShot 2023-10-04 at 13 35 51@2x](https://github.com/lightdash/lightdash/assets/962095/71d324a9-69bd-4206-84ee-6c5015044a22)

**Comment by ujwalkumar1995** [comment]
Hey @IrakliJani 
I was looking at this issue and trying to fix it.
I was facing challenges with couple of things and wanted to seek your inputs on the same.
So the current version of mantine that is being used in the project has few limitations when it comes to NumberInput. It seems we cannot directly restrict the usage of decimals or negative numbers in the input. I checked in the latest version of mantine, these features are available. Is there any plan to update mantine to the latest version or do we have to look for some workarounds to handle these scenarios as I can see we may need these scenarios at some of the places.

**Comment by Ankush263** [comment]
Hello @IrakliJani, I can work on this issue.🙋‍♂️

**Comment by IrakliJani** [comment]
hi @ujwalkumar1995, @Ankush263, appreciate your interest to contribute to this issue, but this issue is part of a milestone typically reserved for in-house development. I suggest looking into issues labeled as 'good first issue.' Thank you for your understanding!
