### ISSUE TITLE
You should be able to rename a dashboard before you have to save it.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#732]
### Context
I tried to create a new dashboard. I was searching for ways to change the `Untitled Dashboard` name to something else. I couldn't figure it out, until I saved it, then realized the rename option was after I'd created the dashboard. 

### Goal
You should be able to rename a dashboard _**before**_ you have to save it.

I'd suggest:
having a title with a pencil beside it. If you click the pencil, then you can edit the title. Then when you press `save` on the dashboard, it saves.

**Comment by owlas** [comment]
Nice! We can also prompt for a name if the user attempts to save and the name is still "Untitled dashboard"

**Comment by TuringLovesDeathMetal** [comment]
Closed in favour of #744
