### ISSUE TITLE
Make it obvious when the query needs to be refreshed/re-run

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#733]
When the results are stale (e.g. filters added, sorts changed, table calculations changed), the query needs to be re-run to get updated results. 

It should be obvious to the user when the query needs to be rerun.

- when the query is 'up-to-date', the button is disabled. So that when an update has been made it turns 'active'.
![Screenshot 2021-12-13 at 10 56 44](https://user-images.githubusercontent.com/12776522/145800343-205be52c-bc06-4b18-a66f-c5453a800d97.png)

**Comment by PriPatel** [comment]
Thinking about a few ways we could do this!
At the very least, perhaps when the query is 'up-to-date', the button is disabled? So that when an update has been made it turns 'active'? Perhaps the visual state change might make a difference.

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel any chance this has been fixed in the new `view mode` work?

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal  - nope, not in scope !

**Comment by owlas** [comment]
Another example of this came up today. When I remove dimensions from the table, then I really need to rerun the query to update the metrics calculations

**Comment by TuringLovesDeathMetal** [comment]
I also think that for this to be "really" useful, we would want to have the `run query` button pinned to the top of the screen (so as you scroll/look at the results table, you can still see it)

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel how would you feel about having a pinned `run query` button? is that 🤮 or 🤩 ?

**Comment by PriPatel** [comment]
The run query button currently floats by itself, so there isn't anything to pin it to!!

Options
-Try pinning it to the bottom of the sidebar - This makes a lot of sense if you think about a user's actions... you pick your metrics/dims then Run query. This is a big change though so I don't know if we want to experiment with this! I will propose this properly later when the Explore page becomes the design focus. 

- A common pattern is to have a toast at the top of the page, reminding the user that they have to hit the Run Query button. Its like when I use something like Google maps, and I move to a different area on the map. It means the results in the sidebar are no longer relevant, so it gives me a cta at the top to 'Search this area'.  
<img width="1440" alt="Screenshot 2022-08-30 at 16 59 09" src="https://user-images.githubusercontent.com/12776522/187484584-95e0c7cb-61cc-4c67-ad50-d0bf3cc8f64a.png">

**Comment by TuringLovesDeathMetal** [comment]
Cool, let's leave the pinning to another ticket. 

Instead, let's just make the active/inactive button change here :)
