### ISSUE TITLE
Add option to `duplicate` charts from within dashboards.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7335]
### Description

Right now, there is no option to `duplicate` charts when you're in a dashboard. This is especially noticeable with charts created from within dashboards because there's no way to duplicate charts except from the charts list in a space, and these charts aren't included in any lists.

### Acceptance criteria

- [ ] There is an option in a chart's three-dot-menu on a dashboard to be able to `duplicate`
- [ ] This option is only shown when you're in `edit` mode on a dashboard
- [ ] Hitting `duplicate` creates the duplicate chart in the _**same place**_ as the existing chart (either in the same space, or in a dashboard if the chart was created from within the dashboard). 
- [ ] It then adds the chart to the dashboard as well, at the bottom. 
- [ ] When the chart is added, the browser automatically scrolls to the bottom of the dashboard so that the users can see the new chart that's been added
- [ ] There's a success toast that says "chart duplicated and added to this dashboard"

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1711101285332779

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1711101285332779?thread_ts=1711101285.332779&cid=C053ESBT36V
