### ISSUE TITLE
Add `format` option for existing metrics in the results table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7339]
### Description

I want to be able to override the formatting for metrics in my results table. 

### Acceptance criteria

Miro sketch: https://miro.com/app/board/uXjVNdj6O-Q=/?moveToWidget=3458764565900155213&cot=14

- [x] If you have a numeric type metric in your results table, there is a `format` option that appears in the drop-down toggle. 
- [x] Clicking on `format` opens a modal where you can adjust the format of your numeric field
- [ ] this _**only**_ applies to numeric type metrics. 
- [x] If you adjust the format from the results table, it overrides teh format applied in the .yml file. 
- [x] This option to adjust formatting is only available from the results table in the Explore view (not in the SQL runner or in view mode).
- [x] the formatting should also show up in the charts
- [x] the formatting should also show up in exports/images (.csv exports, google sheets syncs, and images)
- [x] this ticket is only related to formatting in metrics coming from the .yml 

### Analytics events

add analytics event to `query_executed`. parameter should be `metrics_formatted` = TRUE or FALSE

### Documentation

- add to docs here: https://docs.lightdash.com/guides/formatting-your-fields#formatting-your-fields-in-the-lightdash-ui

**Comment by hamzahc1** [comment]
Reminder for @TuringLovesDeathMetal that this definitely needs a headway update + @jpetey75 to go into the next feature friday!
