### ISSUE TITLE
Exporting a JPG from a chart throws an error: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7352]
### Description

Not sure how to replicate exactly, perhaps when the are no results and chart type is pie chart ? 

Sentry error https://lightdash.sentry.io/issues/4471311124/?referrer=issue_alert-slack&notification_uuid=7a26a849-258a-4d73-96a9-de3a5226c62a&alert_rule_id=9333608&alert_type=issue

Replays: https://lightdash.sentry.io/issues/4471311124/replays/?referrer=slack

**Comment by ydv-ankit** [comment]
i want to work on this issue

**Comment by ydv-ankit** [comment]
Okay no problem
