### ISSUE TITLE
Analytics events for custom binned dimensions

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7356]
- add `num_fixed_width_bin_custom_dimensions`, `num_fixed_bins_bin_custom_dimensions`, `num_custom_range_bin_custom_dimensions` to the following events:
- `query executed`
- `saved_chart_created`
- `saved_chart_updated`

**Comment by rephus** [comment]
saved_chart_updated is not triggered when a `new chart version` (so no metricquery will be in there) is created, that is happening in `saved_chart_version.created`
