### ISSUE TITLE
Make charts downloadable

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#74]
It would be great if I could export a chart as a .png etc for external presentation. 

This is built into ECharts

**Comment by hamzahc1** [comment]
I would consider file types like SVG/PDF too for embedding or if you want to customise the chart out of Lightdash

**Comment by ZeRego** [comment]
@hamzahc1 @TuringLovesDeathMetal @owlas 
Thoughts on design/text ? 
![Screenshot 2021-07-06 at 14 31 14](https://user-images.githubusercontent.com/9117144/124608758-e7af7c00-de66-11eb-9389-9fe9a11e2df1.png)

**Comment by TuringLovesDeathMetal** [comment]
looks good to me!

**Comment by hamzahc1** [comment]
@ZeRego - 
Can we replace the floppy disk icon with something less.. old school 😅 . Some potential candidates: https://www.flaticon.com/search?word=download&type=icon

**Comment by owlas** [comment]
@hamzahc1 available icons for our ui framework here: https://blueprintjs.com/docs/#icons

**Comment by ZeRego** [comment]
I have only been using icons from our component library. https://blueprintjs.com/docs/#icons
Here are some icons that are similar to the ones there. 
![Screenshot 2021-07-06 at 14 42 52](https://user-images.githubusercontent.com/9117144/124610538-82f52100-de68-11eb-9395-b4908ef3fc90.png)

**Comment by hamzahc1** [comment]
They look good! Maybe the Cloud: download?
