### ISSUE TITLE
As an admin, I'd like to impersonate one of my users to test permissions and user attributes

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7420]
### Description

As an admin, I'd like to impersonate one of my users to test permissions and user attributes

Thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1696973321983039

**Comment by TuringLovesDeathMetal** [comment]
closing this as a duplicate of https://github.com/lightdash/lightdash/issues/6083
