### ISSUE TITLE
Add more details and new charts to Usage analytics dashboard

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7423]
### Description

List of improvements: 

- [ ] Remove top 10 limit on `Which users have run the most queries in the last 7 days? (top 10)`
- [ ] Add a new chart to show `dashboards + views` (at least top 20) 
- [ ] Add a new chart to show `charts + views`

Thread: https://lightdash.slack.com/archives/C053ESBT36V/p1696952800523729?thread_ts=1696937066.677159&cid=C053ESBT36V

**Comment by 12ian34** [comment]
This is for JustWatch
