### ISSUE TITLE
I shouldn't be able to interact with chart titles when I've created a chart from within a dashboard (and I'm in dashboard edit mode)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7435]
### Description

We've disabled interacting with charts when you're in edit mode of a dashboard because of dashboard state issues, but we didn't disable interacting with the chart title. So, I can override all of my dashboard changes using this loophole

https://www.loom.com/share/636b999424434d01920f7a317e664276

**Comment by ujwalkumar1995** [comment]
Hey @TuringLovesDeathMetal 
If my understanding is correct, this can also occur even if we are not in the edit mode of the dashboard. Even in view mode, we can click on chart title and still reproduce this bug. So should the title link be completely disabled for charts created within the dashboards?

**Comment by magnew** [comment]
> Hey @TuringLovesDeathMetal From my analysis, this can also occur even if we are not in the edit mode of the dashboard. Even in view mode, we can click on chart title and still reproduce this bug. So should the title link be completely disabled for charts created within the dashboards?

@ujwalkumar1995, you are correct. I saw this elsewhere and I put a fix up, so I'm linking it. Title links will be disabled. Eventually we can do more to make this experience better.
