### ISSUE TITLE
New spaces don't appear on "space" page unless I refresh the page

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7440]
### Description

WHen I'm moving a chart to a new space, I'm creating a new space. I also want to move other charts to the same space. However, the new space I created doesn't appear unless I refresh the page 

[Screencast from 12-10-23 08:38:23.webm](https://github.com/lightdash/lightdash/assets/1983672/92fefa0f-5d54-4cc3-94e2-bffdb1dfe1c7)

**Comment by Ankush263** [comment]
Hey @rephus 🙋‍♂️ I can contribute to this issue

**Comment by ZeRego** [comment]
@Ankush263 go for it 👍

**Comment by Ankush263** [comment]
> @Ankush263 go for it 👍

already done
