### ISSUE TITLE
snowflake defaults to uppercase columns, this is a problem when we run queries, we should disable that setting

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7459]
### Description

We can disable this setting `QUOTED_IDENTIFIERS_IGNORE_CASE` by session, right before running queries on snowflake . Otherwise , customers are force to do this themselves on their database "globally"

Slack thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1697140686106889
https://lightdash.slack.com/archives/C03MCQ08UKS/p1671801454907029?thread_ts=1671788015.431399&cid=C03MCQ08UKS
https://lightdash.slack.com/archives/C05DWCRMLUF/p1688649723896499?thread_ts=1688143782.452199&cid=C05DWCRMLUF

There are other threads on slack if you search by `QUOTED_IDENTIFIERS_IGNORE_CASE`

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1710719110166299?thread_ts=1710719110.166299&cid=C03MG2VTR08
