### ISSUE TITLE
Private spaces dissapear from `all spaces` list 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7464]
### Description

If I click `home` on the space list, and then go back, all private spaces dissapear (including my own) . I need to force refresh the page to see them again. 

[Screencast from 13-10-23 11:52:32.webm](https://github.com/lightdash/lightdash/assets/1983672/fc8091d7-f0f0-4f53-8e01-652c0862e7d4)

This must be a query cache hook thing

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. It hasn't been flagged again by any users since it was created more than a year ago. Can always reopen if needed.
