### ISSUE TITLE
Reappearing the three options of created space in the corner of the Home/All Space section

### ISSUE THREAD

**Issue by jayanand05** [lightdash/lightdash#7510]
### Description

In Home/All Spaces section when i click the 3dot of any created space with options Rename, Pin to homepage, Delete space and  when i click on any of these option the all 3 options appears for a second in the corner of the page 

https://github.com/lightdash/lightdash/assets/113882904/792b87b2-380e-4a5d-aa90-2f5c3a099155

**Comment by lokesh3097** [comment]
Can I get this issue assigned? I think I've found the problem and the solution.

**Comment by IrakliJani** [comment]
@lokesh3097 done!

**Comment by lokesh3097** [comment]
Thank You @IrakliJani!

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. It hasn't been requested/flagged by any users since created more than a year ago. Can reopen if needed
