### ISSUE TITLE
page layout issues on different pages

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7531]
### Description

![CleanShot 2023-10-17 at 18 26 20@2x](https://github.com/lightdash/lightdash/assets/962095/bd18c64a-bee0-4ccd-be63-785ddc406fd6)

there seems to be a conflicting configuration option to `Page` component especially on pages with banners

**Comment by joaoviana** [comment]
Is it specifically on this page or on others? 
I've merged: https://github.com/lightdash/lightdash/pull/7455
And I tested: chart within dashboard, but no `New chart within dashboard` 😢

**Comment by IrakliJani** [comment]
@joaoviana when creating chart within dashboard but the logic is off and Page component needs more thinking and changes. I have a work in progress branch. that PR also caused some other issues see thread here: https://lightdash.slack.com/archives/C02GQKJK84Q/p1697925877802889

**Comment by PriPatel** [comment]
Will this close issue https://github.com/lightdash/lightdash/issues/8364 ?

**Comment by joaoviana** [comment]
> Will this close issue https://github.com/lightdash/lightdash/issues/8364 ?

Yup @PriPatel
