### ISSUE TITLE
It's not clear that you need to click refresh dbt after editing project settings

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#754]
### Context
If you update your project settings, we don't give you any indication that you need to refresh dbt after. 

### Goal
When someone updates their project settings, it should be clear that they need to click `refresh dbt`

Potential solution: when a user saves changes to their project, we tell them (in text) that they need to refresh dbt.

**Comment by ZeRego** [comment]
Fixed so it automatically refetch tables/results/etc after project update.
