### ISSUE TITLE
custom dashboard filter is not included in the shared url

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7547]
### Description

custom dashboard filter is not included in the shared url

### To Reproduce
- navigate to any dashboard that has filters
- in view mode update custom filter
- click share button

https://github.com/lightdash/lightdash/assets/962095/47a5564a-1bcc-4abc-b5fb-ced21190b5e0

**Comment by magnew** [comment]
When we fix this, we should make sure we are NOT storing the entire state of the permanent filters in the URL. Only ones that are modified. There is a related ticket about making it possible to control permanent filters from the URL and this should probably be done with the same design. 

Related ticket here: https://github.com/lightdash/lightdash/issues/7494

**Comment by joaoviana** [comment]
> NOT storing the entire state of the permanent filters in the URL

Makes sense @magnew, what would you expect to be stored? The filter id (or similar) + the value?

**Comment by magnew** [comment]
> > NOT storing the entire state of the permanent filters in the URL
> 
> Makes sense @magnew, what would you expect to be stored? The filter id (or similar) + the value?

Yup. We need to decide what that I'd is, but that's the idea. We could use the UUID but that would make this less usable for other scenarios.
