### ISSUE TITLE
custom metrics (count) generates wrong sql with `includes` operator

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7565]
### Description

The generated SQL query for custom metrics (count) is not grouping OR clauses correctly when more than one filter is applied and one of the filters uses the includes operator with multiple values. This results in a global OR statement, affecting the query's logic.

### Acceptance criteria

- [ ] `OR` clauses within the same filter should be grouped together with parentheses to avoid global OR statements.

![CleanShot 2023-10-20 at 16 04 39@2x](https://github.com/lightdash/lightdash/assets/962095/5fac17fc-e215-46e3-82d7-61392490aa95)

generated sql:

![CleanShot 2023-10-20 at 16 04 57@2x](https://github.com/lightdash/lightdash/assets/962095/576688a5-4fed-4619-88df-c811d64e4a07)

```sql
SELECT
  "customers".customer_id AS "customers_customer_id",
  AVG("orders".amount) AS "orders_average_order_size",
  COUNT(CASE WHEN (LOWER("orders".status) LIKE LOWER('%completed%')
  OR
  LOWER("orders".status) LIKE LOWER('%placed%')
  OR
  LOWER("orders".status) LIKE LOWER('%return_pending%') AND ("orders".order_id) IN (3)) THEN ("orders".status) ELSE NULL END) AS "orders_status_count_of_status"
FROM "lightdash_dev"."jaffle"."orders" AS "orders"
LEFT OUTER JOIN "lightdash_dev"."jaffle"."customers" AS "customers"
  ON ("customers".customer_id) = ("orders".customer_id)

GROUP BY 1
ORDER BY "orders_average_order_size" DESC
LIMIT 500```

**Comment by Karthik3061** [comment]
Hey @IrakliJani , can you have a look on the PR. Parenthesis have been added for each filter individually
