### ISSUE TITLE
Empty state for chart with no data

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#76]
When a chart can't be plotted or has no data, the empty state doesn't render anything and the configure panel is quite confusing:

<img width="1378" alt="Screenshot 2021-06-20 at 13 18 49" src="https://user-images.githubusercontent.com/11660098/122673825-24724680-d1ca-11eb-8991-c40688471266.png">

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal @owlas any thoughts on this layout and text ? Tried to mimic what we have in the results section.
![Screenshot 2021-06-22 at 16 29 42](https://user-images.githubusercontent.com/9117144/122954222-29282d80-d377-11eb-9dc8-811f3b51ac61.png)

**Comment by owlas** [comment]
@ZeRego that looks awesome!

I didn't mention before but the logic to determine whether the chart is valid is derived here: 
https://github.com/lightdash/lightdash/blob/3e2c7aae8f1c1e90d20a360cab7d155955e0a3ef/packages/frontend/src/hooks/useChartConfig.tsx#L23-L36

Where the `ChartConfig.plotData` can be `undefined`

Then there are two components that render depending on this hook:

### SimpleChart.js

https://github.com/lightdash/lightdash/blob/3e2c7aae8f1c1e90d20a360cab7d155955e0a3ef/packages/frontend/src/components/SimpleChart.tsx#L41-L43

### ChartConfigPanel.js

https://github.com/lightdash/lightdash/blob/3e2c7aae8f1c1e90d20a360cab7d155955e0a3ef/packages/frontend/src/components/ChartConfigPanel.tsx#L18-L56
