### ISSUE TITLE
Warehouse connection form: values persist between different forms

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#761]
If I’m filling out the warehouse connection for postgres and then switch to databricks, some of my form answers are copied into the databricks form.

For example, the port is set to 5432 because I set that on the postgres form.

It would be better if they weren’t coupled

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

**Comment by ZeRego** [comment]
@owlas @rephus we already fixed this, right ?

**Comment by rephus** [comment]
Let me try to replicate

**Comment by rephus** [comment]
Yes, this doesn't even make sense anymore, we have changed the warehouse form completely. Closing
