### ISSUE TITLE
custom dimension is wrongly selecting dimensions

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7613]
### Description

If a custom dimension matches the name of the dimension, the explorer sidebar thinks the dimension is selected

![image](https://github.com/lightdash/lightdash/assets/1983672/25d303ba-cfd0-46bc-ab12-c6342bc78482)

**Comment by adarshlilha** [comment]
Hi @rephus 
I came across Lightdash and trying to dig into this issue, can I take this up if available?

A help on how to create a custom dimension would be super useful, TIA

**Comment by joaoviana** [comment]
Hi @adarshlilha I'm actually looking into this! Thanks for the initiative, but this is a milestone that @rephus and I are collaborating on 👍
