### ISSUE TITLE
Pin to homepage doesn't get updated to Unpin & vice-versa in All Spaces

### ISSUE THREAD

**Issue by lokesh3097** [lightdash/lightdash#7636]
### Description

The 'Pin to homepage' option doesn't get updated to 'Unpin from Homepage' and vice-versa when pinning/unpinning from the 'All Spaces' page.

### To Reproduce

1. Go to the Browse -> All Spaces
2. Select 3 Dot menu
3. Pin/Unpin a Space
4. You can see that the next time you click on the 3 dot menu, it doesn't show the reverse option, still shows the same option

### Screen Recording

https://github.com/lightdash/lightdash/assets/28948185/0b19adf6-a970-49de-9ac5-f609175e0a60

### App Version

v0.815.0

PS: I would like to work on this issue.

**Comment by Ankush263** [comment]
Hello, I can work on this issue...

**Comment by joaoviana** [comment]
fixed by the PR above ^
