### ISSUE TITLE
Big value charts should format differences in the same way as the underlying number

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#7664]
### Description
When comparing the raw value difference of a table calculation number (formatted as a percentage), the difference is showing as a number rather than a percentage (which would have been more intuitive).

<img width="428" alt="image" src="https://github.com/lightdash/lightdash/assets/7281432/85b73292-5a0a-472d-b813-278293bf4483">

### What problem does this solve?
If a number if formatted as a percentage, the value difference should be formatted as a percentage too.

**Comment by TuringLovesDeathMetal** [comment]
hmmm, I'm not sure I agree with this @gordonkjlee 

This is showing the percentage point difference (which is typically the best way to talk about differences between percentages). If we showed this as a percent, then you'd be saying "percent difference of a percent vs. another percent" (which is really unintuitive/misleading to people).
