### ISSUE TITLE
If I change the value of a saved filter in view mode, then try to export that dashboard, the filter does not apply. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7696]
### Description

- Try adjusting a saved filter on a dashboard in view mode
- Export the dashboard
- see that the data is not filtered to the temporary filter value

I'd expect that the exported data would be filtered to whatever temporary filter value I've applied to my saved filter int he dashboard. 

https://www.loom.com/share/739217e0742d48349e0b2694174ee537

**Comment by hamzahc1** [comment]
I've updated this to high priority as it's urgent for a customer!
