### ISSUE TITLE
Filters disappear on duplicated dashboard

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#7709]
### Description
When a dashboard is duplicated, the duplicated dashboard does not have filters.

### To Reproduce
1. Create a dashboard and create filters
2. Duplicate the dashboard

### App Version
v0.827.0

**Comment by Ankush263** [comment]
Hey @gordonkjlee, I have tested it in my local environment and it works perfectly, I can see the filters in the duplicate dashboard.
Make sure you save those changes when applying filter.

**Comment by Ankush263** [comment]
hey @gordonkjlee, you are right, you can't even save the filter on the dashboard once you set it, I think this is the reason why you can't see the filters in the duplicate dashboard.

**Comment by TuringLovesDeathMetal** [comment]
@gordonkjlee what version of Lightdash are you on? Latest version is 0.832.0

I feel like we fixed this a few weeks ago, but I can't find the issue for it 🤔
