### ISSUE TITLE
:bug: Website homepage cards overlap with previous section

### ISSUE THREAD

**Issue by khareyash05** [lightdash/lightdash#7713]
### Description
Cards have moved up in the section.I would like to work on that
![image](https://github.com/lightdash/lightdash/assets/60147732/14331773-ded7-4e7b-8c9b-cdd13c319c11)

**Comment by PriPatel** [comment]
Hi @khareyash05 Thanks for flagging! Our marketing website is maintained internally on Webflow so it's not open to contributors. Thanks again, though!
