### ISSUE TITLE
Combine Sentry and OTEL wrappers/events

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#7719]
### Description

In the BE we should combine the sentry and OTEL wrap functions/events.

**Comment by ZeRego** [comment]
docs on how to use sentry+otel https://docs.sentry.io/platforms/node/performance/instrumentation/opentelemetry/

**Comment by joaoviana** [comment]
We enabled this here: https://github.com/lightdash/lightdash/pull/10403 by migrating to sentry v8, which uses `opentelemetry` under the hood
