### ISSUE TITLE
Update button copy on nested filters

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#7725]
<img width="997" alt="Screenshot 2023-10-30 at 13 43 50" src="https://github.com/lightdash/lightdash/assets/12776522/e002a80c-9ae3-4b85-81b1-d36a29f42345">

Right now, we have two buttons that say 'add filter', but they both do different things. 

- [ ] Change `Add filter` on the button **in the nested group** to `Add group rule`

**Comment by Asymtode712** [comment]
I would like to work on it. Please assign me

**Comment by PriPatel** [comment]
thanks a lot @Sai-Karthik-Tumu !
