### ISSUE TITLE
Fix custom dimension rounding on snowflake

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7727]
### Description
We fixed rounding on most warehouses by rounding (ratio) , however, this is not enough on snowflake

![image](https://github.com/lightdash/lightdash/assets/1983672/b2c94a98-6537-40cb-b391-9c62a66356be)

Add rounding on the `label` (when doing cast) 

And then enable e2e tests on creatproject

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. we haven't had anyone complain about this in more than a year. Can always reopen if needed!
