### ISSUE TITLE
Updates to dashboard filter popovers

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7746]
### 1. Include the field name as well as the table name in edit mode.

Right now, when I click on a filter in a dashboard, this is what I see:

![image](https://github.com/lightdash/lightdash/assets/31848148/f7a7e612-567d-41be-b9d9-0c6c6bc52d78)

It only has the table name, but it's using an icon (which is used with fields, not tables). I think we're actually missing the filed name. Instead, it should be like: 

[Icon] Organizations daily **Date (week)**

^or whatever the field name is. 

![image](https://github.com/lightdash/lightdash/assets/31848148/5b4f7a38-5c55-4876-abc7-ba9490a436f1)

### 2. In `view` mode, I should only see the filter label, not the table name/field name

Right now, in view mode, when I click on a filter I see the table name in the filter popover. 

![image](https://github.com/lightdash/lightdash/assets/31848148/2cbea489-3d7f-43ab-8411-c62aa6fba623)

What I should actually see is the filter label (as defined in edit mode here:)

![image](https://github.com/lightdash/lightdash/assets/31848148/fc53ee09-a6be-4114-979b-9208a2c37bae)

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal first one is a bug actually. just opened a PR for it https://github.com/lightdash/lightdash/pull/7775
