### ISSUE TITLE
Inconsistencies with Dashboard filter tile targets

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#7750]
### Description

Some users have reported that when editing a **saved** filter's tile targets, the following happens inconsistently: 
* Select a field that is not default for tile X;
* Select same field on tile Y;
* After selecting field on tile Y, tile X's field resets to default

Current workaround is to tell users to remove and re-add tile to the dashboard; 

However, this proves to be not a permanent solution, as it at some point creeps up again, leading to unexpected (and easy to identify) issues on the dashboard the users curate

### To Reproduce

I wasn't able to replicate this on my end but a specific scenario for a user that was experiencing this: 
* saved filter was Date + `current month`
* tile targets were all default field (so the one that matched the field `current month`; 
* user wanted to select from another table (that was joined) (so for example, from `Orders` to `Customers`) 
* first tile changed correctly
* when changing second tile to the same, it reset the first tile to the default. 
* this happened over and over again

Internal Slack ref: https://lightdash.slack.com/archives/C04FQQU4RL7/p1698747786152749

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as it hasn't been reported by another user since it was opened. 

Will reopen the issue if it is reported again!
