### ISSUE TITLE
The ordering of my columns in my csv + Google Sheets export should match the ordering of the columns in my results table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7753]
### Description

The ordering of the columns in my results table gets swapped around in my google sheets or CSV export (It applies the ordering of the very initial results table, before I move any columns around). If I move any columns around, they are not exported in the same order in the Google Sheet/csv

Some users are reporting that this is only affectig table calculations, and this is a recent regression (table calculations are on the far right in the table, but when exported appear on the far left in the .csv)

https://www.loom.com/share/dc94e8cb1a054a6eb52abf9032d3f864

**Comment by Shivanshu-09** [comment]
Is this still an issue? I reproduced it but it seems to be working. @TuringLovesDeathMetal
