### ISSUE TITLE
Default filter

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#7762]
### Description

I have a usability problem that I don't really know how to solve.

We have special type of account that should be filtered out of most reporting.

Most of our Lightdash users are not aware of that special type of account.

The problem is, if that account isn't filtered out, the Lightdash users will get wrong data.

However, I cannot filter the accounts out before Lightdash, since, in come cases it needs to be included.

#### Two options:

 - The possibility to have default filter. So every time the explorer is opened, the filter is added.
 - #4888

#### This issue are related to:

 - #7521
 - #6974

**Comment by TuringLovesDeathMetal** [comment]
👋 hey @Martin-Carlsson 

this sounds a lot like this issue would solve it : https://github.com/lightdash/lightdash/issues/1735

i'm going to close this as a duplicate in favour of the existing issue! (but let me know if you think your request is different)

**Comment by Martin-Carlsson** [comment]
@TuringLovesDeathMetal 

## Yes 💯％
