### ISSUE TITLE
Change the 'Edit chart' button to be a Mantine one

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#7795]
<img width="201" alt="Screenshot 2023-11-02 at 19 58 29" src="https://github.com/lightdash/lightdash/assets/12776522/8055bed4-6f9b-4b6d-8438-f1f20c8f7ea4">

The three dot menu has been updated to Mantine, so now the buttons are different heights.

- [ ] Update button
- [ ] Update pen icon to be a Tabler one

**Comment by Ankush263** [comment]
hey @PriPatel 👋, can I take this task...???

**Comment by PriPatel** [comment]
@Ankush263 yes, go for it!
