### ISSUE TITLE
Support dbt 1.7

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#7797]
### Description

dbt 1.7 was released https://github.com/dbt-labs/dbt-core/releases

Take inspiration from this PR when we added support for dbt 1.6: https://github.com/lightdash/lightdash/pull/6950/files

**Comment by yu-iskw** [comment]
@ZeRego I have two questions.

1. Do we have any specific timeline to support dbt 1.7?
2. What will happen, if we today deploy models by dbt 1.7 to Lightdash?

**Comment by ZeRego** [comment]
> Do we have any specific timeline to support dbt 1.7?

In the following weeks

> What will happen, if we today deploy models by dbt 1.7 to Lightdash?

There is a change the deployment fails as we don't recognise the manifest format that dbt 1.7 generates.

**Comment by owlas** [comment]
@ZeRego there is a new manifest.json version `v11` for dbt 1.7 - https://docs.getdbt.com/reference/artifacts/manifest-json
