### ISSUE TITLE
When I delete the table that my custom metric is built from, my chart breaks and there's no way to fix it. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7809]
### Description

Steps:

- create a chart that uses a custom metric built from a joined table
- delete the joined table
- go back to the chart
- the chart is broken and there's no way to fix it (the configure panel has blank fields that you can't change).

https://www.loom.com/share/525be10fdca443fc9a2dcc3b342a0648

**Comment by rephus** [comment]
@TuringLovesDeathMetal I'm not sure what should be the fix for this, is it happening only with custom metrics ? I  think this might also happen with dimensions if you remove it from dbt

**Comment by nmwur** [comment]
@rephus this is indeed happening with custom dimensions too. On it

**Comment by TuringLovesDeathMetal** [comment]
@rephus sorry, just seeing this now. 

I think there are two options here (not sure which is easier to do):

1. If I delete a custom dimension or metric being used in the chart, then when I open the chart config, I see the field, but it's greyed out/has a warning symbol/appears like an "error" and on hover over the warning, it says "this field no longer exists". The chart would show as an error (i.e. there would be no chart shown) and I would be able to remove the custom metric/dimension from the config.

<img width="1028" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/bddf8e28-be13-4b3e-90dd-5e2af1c9c6b7">

2. The chart would show as an error/broken. The field (custom metric or dimension) that is broken would be removed from the chart config. 
<img width="1044" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/258755ce-5a36-4c7e-9aa5-9bd2e80bd2ee">

**Comment by TuringLovesDeathMetal** [comment]
^The error messages are just suggestions, I think we already have copy that we use for chart errors? And I think that the error on the field should be the same as the error you see today in the results table when you hover on the field (I can't remember the copy exactly...)

**Comment by TuringLovesDeathMetal** [comment]
ah, the copy is:

for hover on the metric/dimension:
`custom metric 'my_custom_metric' references a table that doesn't exist 'dbt_orders`

Then the chart copy:
<img width="192" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/fa176421-d3ac-4716-9887-d4c8d419c449">
