### ISSUE TITLE
When selecting a value on `Multiselect`, I have to click on the input for the the tag to persist 

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#7812]
### To Reproduce

Create a filter on a chart
Filter can be `string`
Use `is/equals` operator
Select an option on the `Multiselect`
Click away
Tag doesn't persist

Screen recording

https://github.com/lightdash/lightdash/assets/7611706/00ef9a41-7553-4a0b-b8e0-d3dbeee081ef

**Comment by iMac7** [comment]
@IrakliJani please assign me this issue if work hasn't started on it, I will be submitting a PR for it shortly
