### ISSUE TITLE
The filter lists shouldn't reset to the top when I select a value from the list

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7835]
### Description

Right now, the filter list resets to the top each time I select a value. Ideally, it should stay in the same "place" as I'm currently in when:

1. I've scrolled to somewhere in the list
2. I've typed some letters to filter the list

Here's an example of both of those options and how they're currently resetting the filter list position

https://www.loom.com/share/c07ee1203855400895850d6379030bb9

**Comment by iMac7** [comment]
Please assign me this. I have linked a PR for it above with comments

**Comment by ZeRego** [comment]
Something to consider before applying a fix. 
Comment from #7917 
> If we test this problem with the vanilla Mantine component we can see that it doesn't scroll when picking a value.
This makes me wonder if our code is not efficient and is rerendering when it shouldn't causing the scroll to reset.
Would be good to investigate and confirm what is causing this behaviour before pushing a fix where we control the scroll.
