### ISSUE TITLE
When I export a table chart type as a .csv from `view mode`, the ordering of the export is changed

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7837]
### Description

- create a table chart type
- save the chart
- open it in `view` mode
- hit `export .csv`
- see that the ordering is different in the export vs. in the chart

Here's an example chart: https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/saved/6cb9caa8-da87-43df-b74b-c5ec0e8d6bda/view

![image](https://github.com/lightdash/lightdash/assets/31848148/ee4cc69c-2d16-438d-9626-769049c2cc0d)

Here's the output .csv:
![image](https://github.com/lightdash/lightdash/assets/31848148/07aa95de-e37b-46d5-b29b-aba6572731e3)

**Comment by magnew** [comment]
Looks fixed, closing!
