### ISSUE TITLE
I should be able to see where a model is used in Lightdash before I make changes 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#7854]
### Description

There should be a way to quickly see where a model is being used (e.g. what charts and dashboards it's in) so that I can easily plan what I need to do if I want to make changes or delete/replace it.

**Comment by TuringLovesDeathMetal** [comment]
This is resolved now using the exposures work that Jose did. 

More details here: https://lightdash-community.slack.com/archives/C039GAKTPMK/p1705316689969779
