### ISSUE TITLE
Dashboard filters get applied/selected unexpectedly from dropdown menus

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#7856]
### To Reproduce

To reproduce:

1. Start with no filter values (e.g. empty filter) in view mode.
2. Start typing to get auto-complete results in a filter
3. Use your keyboard to pick a value, then hit “Enter” (Value should be added to filter values list)
4. Then press tab (to close the drop-down and move to “Apply” button
5. The value is removed from filter values list

Second behaviour:

1. Start with one filter value in view mode
2. Start typing to get auto-complete results in filter
3. Use your keyboard to scroll values, but don’t hit Enter
4. Instead, hit tab to close the drop-down (or ANY other de-focusing method, including clicking out)
5. The last value you had highlighted in the drop down is now added to the filter values list

**Comment by IrakliJani** [comment]
fixed in https://github.com/lightdash/lightdash/pull/7816
