### ISSUE TITLE
In redshift, `count distinct` custom metrics are being cast as integers, not decimals.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7877]
### Description

When I'm creating `count distinct` custom metrics in Lightdash using Redshift, they are generated as integers, not decimals. What this means is that when I try to divide the custom metrics in a table calculation, the results return `0` instead of a decimal (if the output value is < 1)

### To Reproduce

1. Create two custom metrics in redshift for `count_distinct`
2. try to divide these values using a table calculation
3. The resulting values return 0 (if they're < 1), instead of a decimal value.

See slack conversation here for more information: https://lightdash.slack.com/archives/C049LQZGVD3/p1699453833674909

**Comment by rephus** [comment]
We should get access to a redshift instance for testing this.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - I've updated the docs here: https://intercom.help/lightdash-faqs/en/articles/9233890-why-are-fields-using-division-average-percent-etc-ignoring-decimals-or-showing-up-as-0

And I've opened a new issue here specific to average metrics: https://github.com/lightdash/lightdash/issues/9877
