### ISSUE TITLE
Support AWS Athena

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#789]
_Originally posted by @owlas in https://github.com/lightdash/lightdash/issues/371#issuecomment-964516130_

**Comment by mrshu** [comment]
@owlas would you mind briefly commenting on what this would entail? It would be very interesting for our usecase.

Thanks!

**Comment by jankatins** [comment]
I had a *quick* look at this: seems this file has to be created for athena: https://github.com/lightdash/lightdash/blob/main/packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts (+ tests, etc)

**Comment by mrshu** [comment]
Thanks @jankatins, I guess it shouldn't be that difficult then.

**Comment by jankatins** [comment]
Yes, it's still relevant.

**Comment by jankatins** [comment]
https://github.com/lightdash/lightdash/issues/4940 and https://github.com/lightdash/lightdash/issues/3554 seem to duplicate this issue and have more information -> this can probably be closed.

**Comment by mrshu** [comment]
@jankatins this can indeed be closed I believe.

**Comment by TuringLovesDeathMetal** [comment]
Closing this - we only support dbt verified adapters. Once Athena is verified, we will support it!

**Comment by ppriyranjan** [comment]
I see that Athena is verified adaptor now on dbt, https://docs.getdbt.com/docs/trusted-adapters
Can we open this issue?
