### ISSUE TITLE
Total labels are missing after changing a filter in dashboards 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7914]
### Description

Thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1699313742642359

### To Reproduce

1. Create a bar chart with totals 
2. Add it to a dashboard
3. Go the dashboard
4. Change a filter affecting the results on the chart
5. Total labels are missing!

**Comment by TuringLovesDeathMetal** [comment]
unable to reproduce
