### ISSUE TITLE
There should be a delay on the tooltips that appear on fields when I'm trying to apply dashboard filters 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#7927]
There used to be a longer delay on the tooltips here. Right now, it is quite annoying having many tooltips pop up as I scroll down the list quickly:
![image](https://github.com/lightdash/lightdash/assets/12776522/3c764edf-f73c-4de0-8c93-0b0f5eb019b3)

Tagging as a bug, as I think this used to work as expected and something might have changed.

**Comment by iMac7** [comment]
@PriPatel kindly assign me this
