### ISSUE TITLE
Changing a chart's type requires a dashboard refresh to show up

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#7937]
### Description

If I edit a saved chart from a dashboard, then go back to the dashboard, the new chart type doesn't show up without a refresh

### To Reproduce

1. Make a dashboard
2. Add a saved chart to it. 
3. Save
4. Edit the chart from the tile
5. Change the chart type
6. Save
7. Click back to the dashboard
8. You'll see the old chart
9. Refresh

**Comment by iMac7** [comment]
@magnew I can do this, please assign me
