### ISSUE TITLE
Filtering by week start date only allows Sunday as start of week

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#7951]
### Description

In my project settings, I have week start date set as Monday, but when I try to apply a date filter at week granularity, I can only select a Sunday as the week commencing date.

### To Reproduce

Steps & screenshot/gif/loom to reproduce the behavior
1. Under 'Connection settings', click 'Advanced' in the 'Warehouse connection' section
2. Set start of week to Monday
3. In the table explorer, create a date filter with week is on or after [date]
4. You will only be able to select a Sunday.

### App Version

v0.863.9

**Comment by TuringLovesDeathMetal** [comment]
@mhawkins-runa - I'm not able to reproduce this behaviour
<img width="686" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/ac2aeb96-3974-4c95-85ab-264a83ea816e">

Are you using the `week` time interval that's added by default in Lightdash? Or are you using a `week` time interval that you've defined in your underlying SQL?

**Comment by mhawkins-runa** [comment]
I can no longer reproduce this either. Must have been resolved since I raised the issue. (I was using the `week` time interval added in Lightdash)
