### ISSUE TITLE
Regression in filters: I should be able to click `enter` when I'm typing in the filter box on an incomplete filter value.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7958]
### Description

I used to be able to start typing a filter value that didn't match anything, and just hit `enter` and it would add the filter value automatically. Now, I can't do that. Instead, I need to scroll all the way to the bottom and select `add value`. 

E.g. here I write `test` and it doesn't match anything. I should be able to just hit `enter` and it should add the filter value. 

<img width="602" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/32de8cdd-b602-4d29-a1fb-756b704e9ce4">

**Comment by iMac7** [comment]
@TuringLovesDeathMetal please assign me this

**Comment by magnew** [comment]
@iMac7, assigned to me, but I will take a look at the PR. Thanks!
