### ISSUE TITLE
schedule delivery link is broken for saved schedule delivery

### ISSUE THREAD

**Issue by Shifan-Gu** [lightdash/lightdash#7960]
### Description

When click "Scheduled delivery" link in side the email sent by the "saved schedule delivery", it generates the url like this. 

<img width="752" alt="Screenshot 2023-11-14 at 16 49 05" src="https://github.com/lightdash/lightdash/assets/101873365/11d74c73-38b2-4d5c-a3c4-d8c3cf5e9cc5">

```
https://<hostname>/projects/aee9c55a-be0b-49ee-9ee8-d4b94d9f35a4/dashboards/a58a2405-028d-4354-b581-48d162808024/view?scheduler_uuid=undefined
```
which leads to this error page 
![image](https://github.com/lightdash/lightdash/assets/101873365/f229a812-cbc4-4162-af65-ee8d3dca3c69)

### To Reproduce

1. go to Scheduled deliveries
![Screenshot 2023-11-14 at 16 54 09](https://github.com/lightdash/lightdash/assets/101873365/f554aa9c-068d-489a-aa3a-c55e3b71a318)

2. create a save a scheduled delivery
 
![Screenshot 2023-11-14 at 16 54 38](https://github.com/lightdash/lightdash/assets/101873365/26cad841-54f1-4df7-9062-c36a283a1201)

3. click the link inside the email 
<img width="709" alt="Screenshot 2023-11-14 at 16 57 14" src="https://github.com/lightdash/lightdash/assets/101873365/89a7d573-8d5f-417f-86ee-0238ded50bb1">

### App Version

 0.853.0

**Comment by magnew** [comment]
@Shifan-Gu, good report, thank you!
