### ISSUE TITLE
Investigate filter tile picker not being able to select all tiles

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#7964]
### Description

User are seeing an issue where checking a chart tile to be filtered causes other tiles to get unselected. It's difficult to repro though.  In the report there are two filters with the same name (I tried that) and about 20 tiles on the page.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. Hasn't been flagged again in nearly a year. Can reopen if needed
