### ISSUE TITLE
Filter autocomplete doesn't show all available options

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#7965]
### Description

A Cloud user reported that filters on dashboards weren't working as expected for the last week, and on certain dashboards, the search wasn't returning results that they knew existed. They were able to manually type out the whole filter value and get the filter to work as expected. 

See link for more details:

**Comment by TuringLovesDeathMetal** [comment]
This query should have `FROM organizations` not `FROM stripe`

<img width="496" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/acdcb9a6-f7a6-4855-ad7f-dec1c7fa1c66">

**Comment by 12ian34** [comment]
❤️
