### ISSUE TITLE
Update docs for column totals. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7990]
Maybe we add a page in `troublsehooting` called `Why don't my totals match the values in my table?` (see Looker doc for inspo: https://cloud.google.com/looker/docs/best-practices/how-to-troubleshoot-looker-totals)

- [ ] explain how you can get different totals than if you're just adding things up in the table:
     - [ ] explain how metric filters aren't included 
     - [ ] explain how the limit in the table isn't included

**Comment by joaoviana** [comment]
Add note in docs that we don't have this on pivot tables
