### ISSUE TITLE
Custom metric sorting cannot be removed if custom metric name is changed, leads to unfixable error

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#7991]
### Description

When sorting by a custom metric, if you then change the name of the custom metric, the old metric name persists in the compiled SQL, and cannot be removed. In the screenshot below, it says I am sorting by 3 fields, but I only have 2 selected. This happened after I changed the name of a custom metric that was previously included in the sorting. Now, I cannot run my query without getting an error.

![image](https://github.com/lightdash/lightdash/assets/135957659/79746be5-2444-449f-8c9a-bd0755406acd)

### To Reproduce

Steps & screenshot/gif/loom to reproduce the behavior
1. Create a custom metric in the explorer
2. Sort by the custom metric
3. Change the name of the custom metric
4. Run query and see error

### App Version

v0.863.12

**Comment by iMac7** [comment]
@mhawkins-runa please assign me this
