### ISSUE TITLE
Collapsible sub-headings for Pivot Tables

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#7993]
### Description

I would like to be able to collapse sub-headings in Pivot Tables, [like how Excel does it](https://support.microsoft.com/en-au/office/expand-collapse-or-show-details-in-a-pivottable-or-pivotchart-d70d7e70-d230-4d45-81db-1f5e39bcb394).

Ideally, the Collapsed subheadings would should Sub Totals for the collapsed section, as per #7992 .

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as a duplicate (which has been completed): https://github.com/lightdash/lightdash/issues/7992
