### ISSUE TITLE
Adjusting the format of my table calculation shouldn't reset my entire chart config

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7996]
### Description

Rght now, if I'm using a table calculation as one of the fields in my chart, then I change the table calculation, all of the chart config I had set gets reset. This is really frustrating because I could have made a load of adjustments to the chart config before trying to adjust my table calculation. 

Ideally, when I adjust my table calculation, it would keep the chart config the same adn just update the values in my chart. 

https://www.loom.com/share/848d1bc09a534376b67a80500192fecf?from_recorder=1&focus_title=1

**Comment by iMac7** [comment]
hey @TuringLovesDeathMetal please assign me this

**Comment by gavin-ob** [comment]
This is closed but doesn't seem to fixed in v0.937.2 (latest version at time of writing), was this intentional? agree with OP that this is frustrating.
