### ISSUE TITLE
Improve dashboard sorting UI 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#8012]
### Description

-  [ ] The “remove sort” button is always clickable, even when no sorting is applied, so I clicked it and nothing happens - this should not appear as an option if no sorting is applied. 
- [ ] change the icon for sorting. 
  - [ ] for strings and booleans, use the A-Z, an Z-A icons
  - [ ] for numbers, dates, and times, use the 0-9 and 9-0 icons

![Image](https://github.com/lightdash/lightdash/assets/31848148/9b89f438-dba3-4eb4-9132-8939efce41f5)

![Image](https://github.com/lightdash/lightdash/assets/31848148/335c4346-b487-4f15-b15a-6ddf227bd9b8)

**Comment by adarshlilha** [comment]
@rephus I would like to take this up, if available, TIA

will be adding:
* disable remove sort btn if no sort applied 
* add tooltip - sort asc/desc

**Comment by owlas** [comment]
Hey @rephus we're still updating the spec for this issue
