### ISSUE TITLE
Scheduler sometimes reports delivery success when there was a failure in rendering

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#8023]
### Description

When a dashboard or chart fails to render, the scheduler delivers an image of the failure, then reports that the delivery was a success. We should show the error in the scheduler status in this case. 

Here's an example of a delivery that fails and reports success:
![image](https://github.com/lightdash/lightdash/assets/1864179/02ff2e04-2c1a-4e22-9d8d-6d4fcae19431)

**Comment by TuringLovesDeathMetal** [comment]
closing this as not planned. It hasn't been requested by a user since it was created almost a year ago.
