### ISSUE TITLE
Why does the DataBricks profile require a 'database'?

### ISSUE THREAD

**Issue by drernie** [lightdash/lightdash#803]
I am excited by the included support for DataBricks in v0.9.4

https://github.com/lightdash/lightdash/issues/625

However, I don't understand why the 'database' field is required.  In my S3 installation, we just use the 'schema' field, and it works fine:
```
      type: spark
      method: http
      schema: dev_ernest
      host: nauto-biz-prod-us.cloud.databricks.com
      token: _token_
      cluster: 1004-233546-lager607
      port: 443
      connect_timeout: 30
      connect_retries: 15
      threads: 5
```
Is there some subtlety I am missing?  Right now it seems to fail silently, whether or not I put anything in the `database` field.

Alas, I can't find any documentation for DataBricks yet:

https://docs.lightdash.com/get-started/setup-lightdash/connect-project#database-1

As a side not, I would love it if LightDash would follow the lead ofthe DBT GitHub Action and pull Warehouse connection data (apart from the token) from the profiles.yml file *inside* the dbt project:

https://github.com/mwhitaker/dbt-action

**Comment by owlas** [comment]
> However, I don't understand why the 'database' field is required

Hey @drernie sorry this is confusing. Database here means schema! They are interchangeable in the dbt profiles.yml too

We followed the conventions from the [Databricks connection pages](https://docs.databricks.com/integrations/partners.html). 

I'll update this to say `Database/schema` would that be clearer?

> can't find any documentation for DataBricks yet:

Looks like a bug in our deployment for the docs page, but you can find information to connect to [Databricks in the markdown source file](https://github.com/lightdash/lightdash/blob/main/docs/docs/get-started/setup-lightdash/connect-project.mdx#databricks)

> pull Warehouse connection data (apart from the token) from the profiles.yml file inside the dbt project

We used to have this feature but recently removed it for two reasons:
1. Many times users wanted different credentials for Lightdash (read only) vs. their dbt project (write access)
2. Most users _didn't_ have a template `profiles.yml` in their repository and found it hard to set environment variables correctly

Although, where possible I'd like to pull in the `profiles.yml` data where we can. How are you connecting Lightdash to your dbt project via GitHub or locally? And where is your `profiles.yml` stored?

**Comment by drernie** [comment]
FYI, here is the DataBricks documentation (for DBT Core), which also uses 'schema' instead of 'database':
https://docs.databricks.com/dev-tools/dbt.html
```
databricks_cluster:
  outputs:
    dev:
      type: spark
      method: odbc
      driver: <path-to-odbc-driver>
      schema: default
      host: <cluster-server-hostname>
      token: <personal-access-token>
      cluster: <cluster-id>
      port: <cluster-port-number>
      connect_retries: 5
      connect_timeout: 60
  target: dev
```
Though I notice their DBT Cloud documentation says:
https://docs.databricks.com/dev-tools/dbt-cloud.html#language-Cluster
> For Schema, enter the name of the database where you want dbt Cloud to create the tables and views (for example, default).

NOTE: I tried 'default'  as the value for database but it doesn't seem to help. I also

**Comment by owlas** [comment]
> tried 'default' as the value for database but it doesn't seem to help

So even when you pass the correct `schema` in the `database` field, it isn't working? That seems like a bug. Do you see an error message that you can share?

**Comment by drernie** [comment]
Yeah, I don't seem to get any reaction or error.  Where should I even look for error logs generated by the Docker container?

Here's a Loom video of what I tried:
https://www.loom.com/share/589b216c1b064e1898dc8a5f7194600e

**Comment by owlas** [comment]
Thanks @drernie 

When you hit "Test and save connection" does it begin spinning? If it spins and then stops, it may have actually worked successfully, so if you then navigate to Explore > Tables and see if everything is there.

If there were errors you'll see something in the logs which you can access in docker by clicking on the lightdash container (it's really not obvious but you kinda just click in the blank space on that row)

<img width="1258" alt="Screenshot 2021-11-11 at 20 32 36" src="https://user-images.githubusercontent.com/11660098/141365201-9af0c172-34ea-46ea-8dc1-e8c84492a33b.png">

**Comment by drernie** [comment]
Huh, no spinning. The only thing I see in the logs is:
```
getaddrinfo ENOTFOUND db

Error: getaddrinfo ENOTFOUND db

    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)

error Command failed with exit code 1.

error Command failed.

Exit code: 1

Command: /usr/bin/node

Arguments: /usr/share/yarn/lib/cli.js migrate-production

Directory: /usr/app/packages/backend

Output:


```
That is why Safari. Let me try Chrome...

**Comment by drernie** [comment]
Same behavior on Chrome.  No spinning or anything. The only clue is this message in the Console:
```
Unchecked runtime.lastError: The message port closed before a response was received.
```
createProject:1

**Comment by drernie** [comment]
FYI, I was not able to reproduce that 'createProject:1' message after reloading the page in Chrome.

I also did not see the getaddrinfo message after that first time with Safari

**Comment by drernie** [comment]
So, I went ahead and built lightdash from scratch:

https://ihack.us/2021/11/11/how-to-build-lightdash-from-source/

So now when I run it, I get a real error message:
```
There was an error getting connected
Dbt server exited with an error:

Runtime Error

Could not run dbt

Encountered an error:

ERROR Runtime Error

Credentials in profile "lightdash_profile", target "lightdash_target" invalid: Runtime Error

Could not find adapter type spark!
Encountered an error while reading profiles:
```
But, that may just be a problem with my configuration...

**Comment by drernie** [comment]
If the adapter issue is real, it might be because SIMBA is hard-code:
```
export const DRIVER_PATH = '/opt/simba/spark/lib/64/libsparkodbc_sb64.so';
```
When I use the [driver from Databricks](https://databricks.com/spark/odbc-drivers-download), I only seem to get:
```
./Library/simba/spark/lib/SparkODBC.did
./Library/simba/spark/lib/libsparkodbc_sbu.dylib
```

**Comment by drernie** [comment]
Amusingly, it seems like the ODBC driver hard-codes the 'default' schema.  Let me  see if switching to that makes a difference...

**Comment by drernie** [comment]
FYI, I finally managed to get my local ODBC running, but  I seem to have had to:
- enable an SQL Endpoint
- create an access token specifically for that
- pass in the endpoint value

```
    odbc:
      type: spark
      method: odbc
      driver: /Library/simba/spark/lib/libsparkodbc_sbu.dylib
      schema: default
      host: nauto-biz-prod-us.cloud.databricks.com
      organization: Nauto
      token: _TOKEN_
      endpoint: 8ae442b239645c89
      port: 443
      user: ernest.prabhakar
```
Trying to see if I can get the generated DBT command to execute on the command-line:
```
dbt rpc --host localhost --port 49932 --profiles-dir /private/var/folders/0d/k_f1f8wn0wv_rh3hvhwymrs00000gp/T/41ca79cf1f5e343a979ba3a1d71d5d1c --project-dir /Users/nauto/Developer/dbt --target lightdash_target --profile lightdash_profile
```

**Comment by drernie** [comment]
Good news! I have successfully manually built LightDash and connected to DataBricks via ODBC!

> Successfully connected! Updated project settings.

It took me some mangling in order to get DBT running properly in the same macOS directory as LightDash, which presumably is NOT the issue I ran into with the Docker container.

However, I noticed that the ODBC configuration string seems to hardcode 'default', rather than 
```
        this.connectionString = `Driver=${DRIVER_PATH};Server=${serverHostName};HOST=${serverHostName};PORT=${port};SparkServerType=3;Schema=default;ThriftTransport=2;SSL=1;AuthMech=3;UID=token;PWD=${personalAccessToken};HTTPPath=${httpPath};UseNativeQuery=1`;
```

Which, fortuitously enough, actually matches the title of this Issue!  If we are going to request/require that field, we should presumably use it in this ODBC string, right?

**Comment by drernie** [comment]
FYI, I'm starting over again with a fresh install of 0.10.

Now I get a clean error message when trying to use a local DBT file:
```
There was an error getting connected
Failed to run "dbt deps"

Running with dbt=0.21.0

Encountered an error:

Runtime Error

fatal: Invalid --project-dir flag. Not a dbt project. Missing dbt_project.yml file
```
Presumably this is because it is looking inside the container? I'll try pushing the config to GitHub and trying that option.

**Comment by drernie** [comment]
Ah, the documentation explicitly addresses this: https://docs.lightdash.com/get-started/setup-lightdash/connect-project/#local-dbt-project

I used: /usr/app/dbt

Almost worked:
```
There was an error getting connected
Failed to run "dbt compile"

Running with dbt=0.21.0

Found 20 models, 40 tests, 0 snapshots, 0 analyses, 674 macros, 0 operations, 0 seed files, 7 sources, 0 exposures

19:58:15 | Concurrency: 1 threads (target='prod')

19:58:15 |

Encountered an error:

Runtime Error

Runtime Error in model stg_salesforceaccount (models/stg_salesforceaccount.sql)

Runtime Error

  Database Error

    failed to connect


```
Docker shows:
```
GET /favicon-16x16.png 304 19.200 ms - -

POST /api/v1/org/projects 500 4202.604 ms - 417

POST /api/v1/org/projects 500 3124.058 ms - 417

POST /api/v1/org/projects 500 3028.276 ms - 417

GET /api/v1/projects/7f56ead6-cbfa-4502-850c-f63c3510d922/status 401 9.075 ms - 120

GET /api/v1/projects/7f56ead6-cbfa-4502-850c-f63c3510d922/status 401 4.278 ms - 120

GET /api/v1/org/projects 401 5.451 ms - 120

GET /api/v1/org/projects 401 3.334 ms - 120

POST /api/v1/org/projects 500 256150.882 ms - 922
```

**Comment by drernie** [comment]
Hmm, I have same error now from lightdash local directly. Need to figure out what changed:
```
There was an error getting connected
Failed to run "dbt compile"

Running with dbt=0.21.0

Found 20 models, 40 tests, 0 snapshots, 0 analyses, 674 macros, 0 operations, 0 seed files, 7 sources, 0 exposures

19:58:15 | Concurrency: 1 threads (target='prod')

19:58:15 |

Encountered an error:

Runtime Error

Runtime Error in model stg_salesforceaccount (models/stg_salesforceaccount.sql)

Runtime Error

  Database Error

    failed to connect

```

**Comment by owlas** [comment]
@all-contributors add @drernie for ideas

**Comment by owlas** [comment]
In the new project settings form, we need to set "database" to "schema" in the UI and move it to the "dbt configuration" just like in https://github.com/lightdash/lightdash/pull/2086

<img width="1092" alt="Screenshot 2022-05-17 at 15 56 15" src="https://user-images.githubusercontent.com/11660098/168842394-de847964-1518-4cbe-90a8-8f48cfe5315c.png">
