### ISSUE TITLE
Add date zoom to `explore from here` in a dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8054]
### Description

- [ ] If I'm zoomed in to some date granularity (e.g. month) and I click on `explore from here` in a dashboard, the chart _**should**_ have the date zoom changes applied.

**Comment by rephus** [comment]
charts on explore will copy the date zoom attribute from dashboard, however, there is no indication of "zoom" in explore, and it can't be changed, which might be confusing if you're trying to build a new chart with these settings. 

We could try this out and consider adding the time zoom also in the explore.
