### ISSUE TITLE
Renaming a custom metric breaks a filter

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#8061]
If you rename a custom metric that is present on a filter, then the filter breaks and you can't run queries anymore.

![image](https://github.com/lightdash/lightdash/assets/1983672/4feb5dc2-6dac-4078-821f-e919af80b245)

_Originally posted by @rephus in https://github.com/lightdash/lightdash/issues/8002#issuecomment-1822551399_

**Comment by Sai-Karthik-Tumu** [comment]
Hey @rephus , 
Can I work on this issue?
