### ISSUE TITLE
Catch all server errors and show a more friendly user message with a way to report bugs

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#8068]
### Description

Unexpected errors in the backend shouldn't show things like database implementation to the end user. We should update our server errors to show a more friendly error message and log out the full error to server logs only.

See packages/backend/src/errors.ts where express handles error responses

Bonus: if sentry/otel is enabled, we show the user a transaction id, so they can use this when asking for support from the team.

**Comment by TuringLovesDeathMetal** [comment]
This issue has been completed. We now show issue IDs that users can report to us
