### ISSUE TITLE
Ability to switch an explore's model

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#8076]
### Description
Ability to switch an explore's model to another dbt model

### What problem does this solve?
Sometimes models get renamed or a new model version is created. At the moment, there is no easy way to update Lightdash explores to use the new/renamed model.

**Comment by owlas** [comment]
Hey @gordonkjlee this is a great request! How would you ideally express this inside your dbt yaml?

**Comment by ZeRego** [comment]
Related to #5264

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/5264
