### ISSUE TITLE
Improved default axis labels for date fields

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#8094]
### Description

When we generate a label for a date dimension it'll say something like "Order date day" or "Order date week" - it should just be "Order date". This is cleaner and makes date-zooming clearer

This should only be applied to chart axis labels (not to the results table).

**Comment by rephus** [comment]
Perhaps this is cleaner in the chart, but what about results table / table viz ? YOu might want to add different columns with different time frames, and you don't want to show `Order date` on all of them @owlas

**Comment by rephus** [comment]
If we do this, do we even need to do https://github.com/lightdash/lightdash/issues/8105 ?
