### ISSUE TITLE
Add second y-axis for multi metrics

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#81]
When plotting multiple series, you should be able to assign them to separate axes.

**Blocked by** #1565 

### What does this look like?

Update the series tab in the chart configuration to give the option to map the series to the left or right axis (for horizontal charts this should be the top or bottom axis)

The axis label tab will need an additional entry too.

![IMG_7613](https://user-images.githubusercontent.com/11660098/159504769-204f5282-925e-4c3e-87f8-07153f7ecf7c.jpg)

<img width="350" alt="Screenshot 2022-03-22 at 14 27 08" src="https://user-images.githubusercontent.com/11660098/159504834-8220e0b6-4cf3-4b32-930f-44c653fa959e.png">

<img width="347" alt="Screenshot 2022-03-22 at 14 27 52" src="https://user-images.githubusercontent.com/11660098/159505002-a61b29ee-84ab-41b9-8b2c-fc9fe2793779.png">

**Comment by TuringLovesDeathMetal** [comment]
still relevant!

**Comment by djayatillake** [comment]
any timelines on this one? it's a bit frontend for my liking to have a go

**Comment by TuringLovesDeathMetal** [comment]
not yet...

There's a big chunk of work around improving the chart configurations space. This would definitely fit in there. 
We'll have a better estimate at the end of next week once we've done our planning session for the start of 2022!

**Comment by TuringLovesDeathMetal** [comment]
@djayatillake update on this: we're focusing on dashboard + chart interactivity (things like dashboard filters, cross filtering, drill-down), the dbt <> Lightdash connection and features that make the setup of Lightdash easier (going from 0). 

So I don't think we'll get a chance to work on it before March! But there's a bunch of tickets now building up around chart configs and it feels like once the setup is slick, this will be the bigger priority 👌

**Comment by hamzahc1** [comment]
+1 for this - it's been requested by a couple of Cloud users too (See Slack for details!)

**Comment by colin1d** [comment]
+1 on this ticket and think this is one
 of the most important basic feature for data visualisation
 
 example from below  print screen
from left to right
1st graph doesnt not make sense
<img width="1821" alt="Screenshot 2022-03-03 at 00 44 32" src="https://user-images.githubusercontent.com/99738347/156474257-575df11d-f6c1-4745-ad6a-a4a987602015.png">

thanks.

**Comment by colin-nayuta** [comment]
+1 on this ticket and think this is one of the most important basic feature for data visualisation

example from below print screen
from left to right
1st graph doesnt not make sense

<img width="1828" alt="Screenshot 2022-03-03 at 00 48 31" src="https://user-images.githubusercontent.com/98808543/156474617-dbda5e98-494f-4683-b410-6f31ed0bbdf6.png">

thanks.

**Comment by PriPatel** [comment]
We've decided to support 2 axes max. The toggle should only show when there is more than 1 metric selected.
<img width="361" alt="Screenshot 2022-03-24 at 10 57 02" src="https://user-images.githubusercontent.com/12776522/159901977-6c590dbc-54ff-4487-80d7-d565b3879c9d.png">

Related design files [here](https://github.com/lightdash/lightdash-internal-work/issues/236)

**Comment by djayatillake** [comment]
this looks great!!!
