### ISSUE TITLE
There should be a way to Explore "unlisted tables"

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#817]
### Context
Since we added the "table filtering" feature (it's awesome, btw!) I can no longer explore tables that are unlisted. E.g. if I wanted to explore a `base_` table in our project right now, I would have to change the settings for _**everyone**_ in the project to be able to see these tables. THen change it back. 

![image](https://user-images.githubusercontent.com/31848148/141777407-f36143b9-fe15-4f8e-93be-27da67e6990f.png)

### Goal
There should be a way to explore "unlisted tables" without having to change the project settings. 

**suggestion:** At the bottom of the tables list, we add a `see unlisted tables` button which makes _**all**_ of the models in your dbt project pop up in the sidebar. 

When this happens, you'd have a button at the top that would say `hide unlisted tables` which would bring you back to the filtered tables list.

**Comment by ZeRego** [comment]
Suggested changes:

```
// packages/frontend/src/hooks/useExplores.tsx
     queryKey: ['tables', filtered],
```

```
// packages/frontend/src/components/ExploreSideBar.tsx
    const [filterExplores, toggleFilterExplores] = useToggle(true);
    const exploresResult = useExplores(filterExplores);
    ...
                        <Button onClick={toggleFilterExplores}>
                            {filterExplores
                                ? 'See unlisted tables'
                                : 'Hide unlisted tables'}
                        </Button>
```
