### ISSUE TITLE
You should be able to have many line types on the same graph

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#819]
### Context
Right now, you can only have one line style/value style on the same graph (e.g. only bar chart). This is annoying, because sometimes I want a bar chart, but then a line as well (for one of the metrics)

### Goal
You should be able to have many line types on the same graph.

NOTE: the only line types I would imagine mixing are: all the flavours of bar charts + all the flavours of scatter plots/line charts

**design**

This option can live under the series tab. Where each series can be assigned to a line/area/scatter/bar

<img width="429" alt="Screenshot 2022-03-22 at 15 07 31" src="https://user-images.githubusercontent.com/11660098/159513852-2ddc4856-f6e5-4b39-81ac-b4cf9ced6d55.png">

**Comment by PriPatel** [comment]
Note :
If the user has multiple line types on one chart, then when they close the chart config panel, a new 'combo / custom ' option will appear here and be highlighted. If the user then changes the type to 'scatter', all lines will become scatter. 
<img width="211" alt="Screenshot 2022-03-23 at 10 23 42" src="https://user-images.githubusercontent.com/12776522/159686171-153916ad-6cfd-417b-92d7-10e47acd163e.png">
/

**Comment by PriPatel** [comment]
-  Check out the [Series Tabs here](https://www.figma.com/file/ayHkLusYRiPx3F33SjrqGP/Chart-config-Wireframes-WIP?node-id=0%3A1) to see how this might work across different scenarios.

- The dropdown in the chart panel will be affected by this change. [Here is a proposed flow. ](https://www.figma.com/proto/ayHkLusYRiPx3F33SjrqGP/Chart-config-Wireframes-WIP?node-id=227%3A3149&scaling=min-zoom&page-id=128%3A50&starting-point-node-id=227%3A3149&show-proto-sidebar=1)
