### ISSUE TITLE
Smaller "results may be incomplete" button

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#8192]
![image (1)](https://github.com/lightdash/lightdash/assets/11660098/642fcdc4-8d30-4b2c-b0e3-7d6bf2f2f84e)

The current warning alert box looks like something is very wrong with the query. Let's make it less prominent.

Include just a single line of text, near the run query button, not in an alert box. It should say "Results may be incomplete". On hover a tooltip can say "Query limit of `X` reached. There may be additional results that have not been displayed. To see more increase the query limit or try narrowing filters." - The "increase query limit" would ideally be conditional if they have reached the maximum allowable query limit.

Perhaps we could also indicate something on the run query button where we show the limit? Like `500!` if the 500 limit has been reached. Just a small hint.

**Comment by ZeRego** [comment]
closing this ticket in favour of https://github.com/lightdash/lightdash/pull/8222
