### ISSUE TITLE
Inputs appear misaligned when there is an error on any field in the 'Project Invite' modal

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#8195]
To reproduce:
Enter an invalid email address in either the organization access or project access modals.

<img width="632" alt="Screenshot 2023-12-04 at 14 46 06" src="https://github.com/lightdash/lightdash/assets/12776522/5b378a64-4972-44b8-88b4-8e89083acbef">

- [ ] The fields should be aligned when there is a default state or an error state

**Comment by alfredlouisw8** [comment]
hi can i work on this issue?

**Comment by raheelam** [comment]
@PriPatel hello can i work on this issue?

**Comment by PriPatel** [comment]
@alfredlouisw8 , go for it !
