### ISSUE TITLE
validate email inputs and not allow white spaces

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8198]
### Description

Sometimes, people accidentally type an invalid email address because they've added a whitespace. It's really unclear that this is the problem and it's hard to debug as a user (becuase whitespace isn't obvious). 

We should show an error in email inputs if it contains white spaces. 

We should do this in:

- email input for reset password
- email input for creating a new organization
- email input for adding a new user to a project
- email input for adding a new user to an organization

Tech note: 
check existing functions `getEmailSchema` and `validateEmail`

**Comment by iMac7** [comment]
hi @TuringLovesDeathMetal assign me this

**Comment by IrakliJani** [comment]
@iMac7 done!

**Comment by jogeshwar01** [comment]
@ZeRego Can I work on this?

**Comment by ZeRego** [comment]
@jogeshwar01 go for it :)
