### ISSUE TITLE
sql query generator error with field names starting with a number

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8212]
### Description

The SQL query generator fails when a field/column name begins with a number, leading to syntax errors.

![CleanShot 2023-12-05 at 19 49 07@2x](https://github.com/lightdash/lightdash/assets/962095/5974eb26-07ff-4d45-a2eb-d2cbe74f3bb0)

![CleanShot 2023-12-05 at 19 49 32](https://github.com/lightdash/lightdash/assets/962095/d18e5cdb-dbee-490d-a593-65dbd2e43682)

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani are people writing column names with numbers in front of them? This will fail generally if they try to use them in any SQL, so I'm not surprised we're triggering an error here...

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal we can close the ticket as the customer renamed column name. it will work though if we put quotes around fields right?

**Comment by TuringLovesDeathMetal** [comment]
ya, it should work if we add quotes. I'm going to close this as not planned for now though 👀 we can reopen if someone adds numbers at the front of their columns and complains, but this is super uncommon to do (and not traditionally good practice in data).
