### ISSUE TITLE
Deleting a chart still shows the chart on a cached dashboard  

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#8223]
### Description
We should invalidate caches for that dashboard / chats 

[Screencast from 30-11-23 11:46:32.webm](https://github.com/lightdash/lightdash/assets/1983672/c3da6607-4ed2-4576-81b3-fb88c4f40ef1)

**Comment by iMac7** [comment]
@rephus is it just the cache? I added a chart to my dashboard then deleted it, and it leaves an empty tile with no data. maybe the dashboard tile is not being deleted when the chart is deleted?

![image](https://github.com/lightdash/lightdash/assets/76876702/c71ba843-9b91-43b0-8782-0c92cf5a3e8a)
