### ISSUE TITLE
users with `viewer` access should be able to export results from tables, but not adjust the export limit

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8253]
### Description

Right now, users with `viewer` access can't export results. This is a bit weird becuase I could just open the results table in view mode, then copy-paste the values into a .csv. 

So, I'm suggesting that we add the option for viewers to export results to a .csv or google sheets, but not adjust the result limits. 

### Acceptance criteria

- [ ] viewers can export results to a .csv or google sheets
- [ ] When they see the export option, they see `formatted` or `unformatted`, but they don't have the option to adjust the number of results exported (they just get whatever is in the table). 
- [ ] Update docs here: https://docs.lightdash.com/references/roles
  - [ ] For the `export google sheets` and `export to csv`, include a ✅ for viewers, but add: `*cannot adjust the number of results exported`

**Comment by rephus** [comment]
I thought this was already done @TuringLovesDeathMetal

**Comment by rephus** [comment]
Fixed here https://github.com/lightdash/lightdash/pull/8392
