### ISSUE TITLE
Date zoom should work with Timestamp dimensions too

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#8269]
### Description
The [date zoom feature](https://docs.lightdash.com/guides/interactive-dashboards/#date-zoom) doesn't seem to currently work with timestamp fields.

It will be great if this also works with timestamp dimensions - zoomable to hours, minutes, seconds.

### What problem does this solve?
1. Allow timestamp fields to benefit from date zoom
2. Allow more granular zooming in

**Comment by gavin-ob** [comment]
second that!

**Comment by ZeRego** [comment]
This ticket should be split in 2: 
- bug: date zoom should work with timestamps
- feature: have more time granularity
