### ISSUE TITLE
Enable Creation of Custom Dimensions with Flexible SQL Expressions in UI

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#8275]
### Description

Introduce the capability to create custom dimensions in Lightdash using flexible SQL expressions directly through the Lightdash UI. This feature would allow users to define complex and specific dimensions tailored to their data analysis requirements.

### What problem does this solve?

Currently, users may be limited in their ability to create custom dimensions that meet their specific analytical needs. By enabling the creation of custom dimensions with SQL expressions in the UI, users can have greater flexibility and control over their data analysis. This feature would empower users to define more nuanced and precise dimensions, enhancing the depth and quality of insights derived from their data.

**Comment by jpetey75** [comment]
this was completed in https://github.com/lightdash/lightdash/issues/9930
