### ISSUE TITLE
Scheduled delivery dashboard is being formatted incorrectly between two scheduled deliveries

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8276]
### Description

Getting some inconsistent layouts in scheduled emails. With no changes, different emails show different layouts. Do you know what might be causing this?

Here's a link to the slack thread with some screenshots: https://lightdash.slack.com/archives/C04DLEN7BJS/p1702310726983879

**Comment by joaoviana** [comment]
Relevant issue: https://github.com/react-grid-layout/react-grid-layout/issues/1787

**Comment by joaoviana** [comment]
https://github.com/lightdash/lightdash/pull/8478
https://github.com/lightdash/lightdash/pull/8477
https://github.com/lightdash/lightdash/pull/8428
https://github.com/lightdash/lightdash/pull/8389

All the above were to introduce `previews` and custom width for Dashboard exports and scheduled deliveries _only_ for dashboards
