### ISSUE TITLE
Add "helmet" express plugin

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#8331]
### Description

Add [helmet](https://github.com/helmetjs/helmet) to our express server.

Headers:
- Strict transport policy (HSTS) includeSubdomains: preload, maxAge: 31536000
- Content security policy (CSP) ~needs #10325 first~
- X-Content-Type-Options nosniff
- Referrer-policy strict-origin-when-cross-origin
- Permissions-Policy `camera=() microphone=()`

**Comment by ZeRego** [comment]
Blockers:
- [ ] replace `monaco editor` since they inject inline scripts and css.
Issue open since 2016 :sob:
https://github.com/microsoft/monaco-editor/issues/271
- [ ] precompile AJV schemas. closed issue with more info: https://github.com/ajv-validator/ajv/issues/406

**Comment by TuringLovesDeathMetal** [comment]
- add this without the content checks

**Comment by ZeRego** [comment]
Note that we are going to add `Content-Security-Policy-Report-Only:` for a short period. This allows us to collect violation reports and adjust configuration without causing downtime.
