### ISSUE TITLE
Investigate scheduled deliveries not being sent

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#8359]
### Description

A customer has reported that scheduled deliveries aren't arriving up to 50% of the time. They are reasonably sure this is recent, with the addition of scheduled delivery filters. 

[Thread for context](https://lightdash.slack.com/archives/C03MCQ08UKS/p1703006937088819) (requires access)

**Comment by joaoviana** [comment]
`Send now` scheduled deliveries display an error message if there's an error

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned - I can't see this linked to any Slack messages and we haven't heard any more reports of this recently. Will reopen if it's needed!
