### ISSUE TITLE
I can't apply group_label to my models 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#8361]
### Description

Docs: https://docs.lightdash.com/references/tables#table-configuration

### To Reproduce

1. Add group_label to 1 or more models in jaffle_shop schema.yml

![image](https://github.com/lightdash/lightdash/assets/1983672/d898804a-392e-4624-bb85-e1b145ef84c4)

2. Update dbt schema (I tested this via UI and CLI, same result) 
3. The group_label is not present in the explore :fire: 

I've noticed at this point, meta.group_label is undefined https://github.com/lightdash/lightdash/blob/main/packages/common/src/compiler/translator.ts#L435

Perhaps is something about the Lightdash manifest ? 

### App Version

v0.908.0

**Comment by jogeshwar01** [comment]
@rephus 
Just tried to reproduce this issue. It seems to be working fine at my end.
Basically added the group labels to these tables - customers,orders and payments like this -

![image](https://github.com/lightdash/lightdash/assets/85165953/b808c83a-4be8-425f-adcc-190d15c0432b)

Updated dbt schema - once using the UI (refresh dbt button) and once with the cli (running the seed scripts).
Had migrated back to v0.908 to check if it might have been an issue with it but still same output.
I do get these tables grouped in the Explorer in both cases. Here is the screenshot.

![image](https://github.com/lightdash/lightdash/assets/85165953/ce0bd9bc-edbf-45a2-a04f-37f1575c00b0)

Is there something that I might be missing here.

**Comment by TuringLovesDeathMetal** [comment]
not able to reproduce
