### ISSUE TITLE
I can edit a "chart from a dashboard" tile title

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8363]
### Description

https://www.loom.com/share/f1f81d53f272445397f304011c669842

I think we should:

- add the option to `edit tile content` in charts created from within a dashboard under the `edit tile content` option, as it exists in charts not created from within a dashboard

Currently, we can't edit the tile content of a "chart from a dashboard":
![image](https://github.com/lightdash/lightdash/assets/7611706/037fd0ef-ce05-44c6-83d1-1461373bbd1e)

**Comment by joaoviana** [comment]
I wouldn't call this a bug but more a feature request for 

When editing a dashboard:

Saved charts:
<img width="467" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/a00c0c01-a5bc-4dc3-9f5f-4800d3b18df5">

Charts from a dashboard:
<img width="501" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/168e82b2-d7d4-4cae-80ef-1fe0e3fbadc2">
<img width="415" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/cf5025ea-3cf2-4f44-bfdc-401780f3ca7e">

When viewing a dashboard

Saved charts:
<img width="501" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/1495025d-cbd7-4c24-b06d-d5190fcddd14">

Charts from a dashboard:
<img width="350" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/0f864cc3-76c7-4524-83fa-6b9fe1bdccb7">

With this PR: https://github.com/lightdash/lightdash/pull/8495, when editing a dashboard and we hit the `3-dot-menu` of chart from a dashboard, we see the `edit tile content` disabled + a tooltip explaining why. 

So for the AC:
> remove the functionality from edit tile content to change the chart shown within a tile (i.e. to swap a chart out for another chart)

I think the PR above completed that ^

Andfor this AC:
> add the option to edit title in charts created from within dashboard

I would have a separate issue for all charts (any type) created from a dashboard, what do you think?

> rename edit tile content to edit title

Would this be the title of the chart or the title saved in the dashboard tile? For example, you would view the chart from a dashboard with title X but it could have title X, Y or `hidden` in the dashboard? 

LMK what you think @TuringLovesDeathMetal !

**Comment by TuringLovesDeathMetal** [comment]
ah ya, this is probably not a great spec 😅 

I think what the external PR did is what I wanted, but probably should have split it into two things. 

The first thing is: users should be able to edit the title of a chart from the three-dot menu. Not the _**underlying**_ title, but the title shown on the dashboard (the same way as you can do this for charts _**not**_ created within a dashboard). 

The second thing was a bit rogue. SO actually, I think what should happen is this should exist in the `edit tile content` option just like it does today in the other charts that are created not from within a dashboard.

**Comment by joaoviana** [comment]
thanks @TuringLovesDeathMetal, I've updated the title and description with the updates from our discussion 👍

**Comment by joaoviana** [comment]
this has been done in https://github.com/lightdash/lightdash/issues/9240
