### ISSUE TITLE
The sidebar in the explore view is not full height when I try to create a chart from within a dashboard

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#8364]
<img width="206" alt="Screenshot 2023-12-20 at 11 01 29" src="https://github.com/lightdash/lightdash/assets/12776522/8957b6d2-d6eb-4497-97b3-6ec24aef2b1e">

There's a gap at the bottom

**Comment by amanx123** [comment]
Can i solve this issue ?
