### ISSUE TITLE
Poor UX when creating a dashboard with no save charts

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#840]
<a href="https://www.loom.com/share/1a2bb82c29b84b3493480d5953551083">
    <p>No saved charts ux bug - Watch Video</p>
    <img style="max-width:300px;" src="null">
  </a>
  
We could have a message or a link to the docs to explain how to create saved charts first.

**Comment by TuringLovesDeathMetal** [comment]
This has been fixed!
