### ISSUE TITLE
After scrolling past ~50 rows, rows start alternating background colour 

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#8402]
### To Reproduce

1. Query from table
2. Scroll the results table with a dim that has more than > 50 values on `SCROLL` mode

https://github.com/lightdash/lightdash/assets/7611706/7d952b08-5903-4678-a78e-d1e447c0beac

**Comment by joaoviana** [comment]
Hi @hammadahamed, this is probably a side-effect of our migration-to-mantine completion. I've spoke internally with the team and we'll discuss. So I would say that this one _should_ be fixed by the Lightdash team. 

This one: https://github.com/lightdash/lightdash/issues/8195 for example would be cool to picked up 🙌

**Comment by hammadahamed** [comment]
Sure @joaoviana , Thanks for suggesting another issue. Will look into it.
