### ISSUE TITLE
Support fixed width and custom binning for Lightdash Validate

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#8419]
### Description

From a user:

>We are having an issue with lightdash validate.
>So in our CI/CD process we do a "lightdash preview" and after that we do a "lightdash validate".
>We get sorting error on fields that does not show up in the preview environment, and we have a quite strong feeling it is related to binning since this column is a binned value and in the SQL charts the select binning columns are missing in the SQL statements. 

The user requires support for custom and fixed width binning.
Validate does not support binning so errors will arise. We should support it to cater to this use case.

**Comment by rephus** [comment]
I can reproduce 
![image](https://github.com/lightdash/lightdash/assets/1983672/538b7b77-83f6-4bf0-aff2-937e587329f9)

**Comment by gictor** [comment]
wonderful @rephus, we just confirmed that this works
