### ISSUE TITLE
incorrect `MONTH_NAME` ordering in line charts

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8434]
### Description

Line charts are displaying months out of order when using `MONTH_NAME` dimensions - months don't follow the correct order.

![image](https://github.com/lightdash/lightdash/assets/962095/8629ab1f-7bf0-499a-9c6e-5e99930b8b21)

**Comment by IrakliJani** [comment]
related ticket that does not mention chart-config. keeping both open for now https://github.com/lightdash/lightdash/issues/4095

**Comment by TuringLovesDeathMetal** [comment]
^I think this is a duplicate of #4095? I'm going to close this issue in favour of #4095, but we can always reopen/move context if needed!
