### ISSUE TITLE
On the first onboarding screen, the 'Organization Name' input disappears when I try to fill it out

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#8450]
When I try to fill out my Org Name on the first onboarding screen, the input disappears. This means we could potentially not be capturing Org Names from new users. 

https://www.loom.com/share/e8ed8803a8754aeeacd5bd03b50a3050

**Comment by lancerael** [comment]
I think I have a fix for this: https://github.com/lightdash/lightdash/pull/8458

**Comment by PriPatel** [comment]
Thanks @lancerael !
