### ISSUE TITLE
You should be able to create a new saved chart from within a dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#848]
### Context
Right now, if I want to create a dashboard, I can only add charts that are saved charts. It's quite a bad experience having to exit my dashboard, go to the `Explores` tab, create a chart, go back to my dashboard, then add a chart. 

Instead, a user should be able to create a new saved chart from within a dashboard

### Goal
A user can create a saved chart from within a dashboard

**Suggestion**: 
- [ ] In the modal where you select a `saved chart` there's  a button at the bottom which says `create new saved chart`. 
- [ ] This would bring you to the Tables page 
- [ ] Then, once you created + saved the chart, it would bring you back to the dashboard, with the chart added to the dashboard

Similar components as with the spaces:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/31848148/192533079-40e3b48b-4f8a-4dd8-9862-c5831532feac.png">

**Comment by TuringLovesDeathMetal** [comment]
This has been completed

**Comment by joaoviana** [comment]
done in milestone: https://github.com/lightdash/lightdash/milestone/101
