### ISSUE TITLE
Date on tooltip showing wrong date

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8505]
### Description

This was "fixed" here: https://github.com/lightdash/lightdash/issues/2657

But it's popped up again for some users. 

See slack thread here: https://lightdash.slack.com/archives/C03EC7PCW8H/p1704724704742839

**Comment by rephus** [comment]
I know why this is happening, and I can replicate, but I'm not sure how to fix it without doing a major refactoring 

![Screenshot from 2024-01-23 06-23-57](https://github.com/lightdash/lightdash/assets/1983672/6e4a0128-f512-472d-827e-d1e4ca1f1bb3)

My backend is on UTC+2 and my frontend is on UTC-9 

![Screenshot from 2024-01-23 06-24-05](https://github.com/lightdash/lightdash/assets/1983672/57014875-6c24-46db-b898-98a4f8e81e11)

My backend is returning the `2020-06-30 22:00` as `2020-07` in raw. 

![Screenshot from 2024-01-23 06-23-50](https://github.com/lightdash/lightdash/assets/1983672/4c16dd48-034c-4352-b5c7-0a8bb8b28f15)

We use the timestamp to construct the chart, echarts converts this date into a timestamp `1593554400000` , even if we try to convert that back to UTC, we can get `2020-06-30 22:00`

![Screenshot from 2024-01-23 06-24-36](https://github.com/lightdash/lightdash/assets/1983672/ed070638-1692-42a6-bf8a-f8cc96bc86cf)

Possible solutions. 

- Major refactoring to return results data or without timezone 
- could we add the formatted month as metadata in the chart ?

**Comment by rephus** [comment]
I think the fix should happen on the backend, where we strip the timezone information from the dates. 

The fix should happen here https://github.com/lightdash/lightdash/blob/main/packages/common/src/index.ts#L852

Example: 

My backend gets the data from the database `Moment<2020-07-01T00:00:00+02:00>` (it has timezone info) , and this is converted to a `month` 

![image](https://github.com/lightdash/lightdash/assets/1983672/0835288a-a060-4e5b-a4ad-da629e9e2d17)

However, the data we return to the frontend is

![image](https://github.com/lightdash/lightdash/assets/1983672/a7c5573f-7a5f-4df7-b80b-62e473c42e83)
WHich is wrong. 

We use the `formatted` for most of the charts / results , however the `raw` is a wrong data. 
This datetime is then sent to echarts, which converts them to numbers `1593554400000` 

At this point we're unable to get `2020-07` anymore.
