### ISSUE TITLE
Can't filter between two times in the same day

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#8511]
### To Reproduce

1. Add filter for date with interval that is less than a data. eg: hour, minute, raw
2. select first date
3. select second date in the same day but different hour

Notice it is not possible to select the same day as the first value.

<img width="815" alt="Screenshot 2024-01-09 at 09 50 05" src="https://github.com/lightdash/lightdash/assets/9117144/8ff2b858-e855-49fe-a6d3-3a2741271778">

### App Version

0.925.1

**Comment by lancerael** [comment]
I have a fix for this - would you like to assign me please @ZeRego ?
Or just approve my PR 😸 https://github.com/lightdash/lightdash/pull/8581
