### ISSUE TITLE
Move users and groups to tabs in the project access page

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8513]
### Description

Once users and groups have similar UX for adjusting roles (which is done in this issue: https://github.com/lightdash/lightdash/issues/8512) then it makes more sense for them to be in tabs instead of one being in a modal and the other in tabs. 

### Acceptance criteria:

Miro sketch: https://miro.com/app/board/uXjVN7jWjwA=/?moveToWidget=3458764575030213197&cot=14

- [ ] There are two tabs in the project access page: `users` and `groups`
- [ ] The `users` tab contains a list of all the users that have access to the project
- [ ] the `groups` tab contains a listof all the groups that have access to the project
- [ ] The button on the top-right needs to change (there are a list of suggestions in the Miro sketch).

**Comment by IrakliJani** [comment]
https://github.com/lightdash/lightdash/pull/8527 work was done in this PR
