### ISSUE TITLE
Analytics events for user groups

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8531]
- event for `group_created`
  - user_id that created the group
  - organization_id
  - timestamp
  - group_id
  - group_name
  - num_users_in_group
- event for `group_updated`
  - same fields as `group_created`
- event for `group_deleted`
  - user_id that deleted the group
  - organization_id
  - timestamp
  - group_id

- update `user_attribute_created` with `values_group_values` and `values_group_ids` (right now there is `values_values` and `values_user_ids` - I want the same, but for groups)
- update `user_attribute_updated` with the same as above

**Comment by ZeRego** [comment]
> user_group_members list of user IDs that are group members (calling this user group members because I imagine eventually you'll be able to assign groups to groups)

Having them on the same list is not a good idea if we want to use them to join the user/group table. If they are on the same list we won't know what table to join for each uuid.
