### ISSUE TITLE
Make tables and metrics more discoverable in onboarding/when you first land in the app

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#858]
When you open Lightdash you're shown a list of (possibly filtered) dbt model names.

Without more context, it's hard for less technical users to find the right starting place. #857 would help by allowing analysts to provide more user-friendly names for tables.

They should also be searchable, along with all the metrics and their descriptions. That means if I know I want to see "revenue" I can very quickly get to where I'm going.

Any ideas here?

Some thoughts:
* Suggest some getting-started metric + dimension combinations
* Provide search across tables and descriptions
* Provide search across all metrics and descriptions
* Show table descriptions in the UI
* Allow analysts to curate and layout a "homepage" containing the key explores and dashboards.

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue - it's had no action in 2 years and doesn't have a complete acceptance criteria/spec
