### ISSUE TITLE
I'm able to enable/disable Lightdash groups automatically being assigned to groups based on their OKTA groups. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8591]
### Description

This is an organization setting. I'd either expect it on this page:

![Image](https://github.com/lightdash/lightdash/assets/31848148/0d89c37e-c9aa-49f0-a892-8efa4ad7680d)

or somewhere on this page? 

![Image](https://github.com/lightdash/lightdash/assets/31848148/565aa0a8-64a2-4bb6-bc9e-ae031f030ce8)

It should be a section called `Enable SSO user groups mapping`

The subheading/text should say: 

> If you have Single Sign On (SSO) set up on Lightdash, then enabling SSO user groups mapping automatically maps groups in your
> internal user directory to user groups in Lightdash. To learn more, 
> [check out our docs](https://docs.lightdash.com/references/groups#using-okta-to-manage-groups-in-lightdash).

There should be a toggle to `enable` and `disable` the setting.

**Comment by 12ian34** [comment]
We can achieve this with env vars

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue for now as it's controlled through env vars
