### ISSUE TITLE
I want to be able to see all the labels on the X axis

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#8593]
### Description

Currently, echarts configuration hides most labels when choosing a date on the x axis.
The user can still see the label if they hover on the axis line. However, it would be better (for visibility) if we allowed/turned on the labels' visibility at all times. 

Example: 
<img width="1496" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/45a063af-bb77-4862-8416-728641a6fd4c">

Here ^, for this short range, we could display all labels - 1, 2, 3, 4, 5 (with a rotation applied) so that users can see these without the need to hover on the line.

**Comment by TuringLovesDeathMetal** [comment]
duplicate - closing this in favour of this ticket: https://github.com/lightdash/lightdash/issues/6327

**Comment by joaoviana** [comment]
thank you @TuringLovesDeathMetal !
