### ISSUE TITLE
Add a join parameter to define the join relationship, and dynamically deal with fanouts in the queries

### ISSUE THREAD

**Issue by NaomiJohnson** [lightdash/lightdash#861]
With any one-to-many, many-to-one and many-to-many joins, fanouts occur. 

Looker has a powerful feature, that deals with these fanouts dynamically, based on the relationship that has been defined.
See docs [here](https://docs.looker.com/reference/explore-params/relationship) and [here](https://help.looker.com/hc/en-us/articles/360023722974-A-Simple-Explanation-of-Symmetric-Aggregates-or-Why-On-Earth-Does-My-SQL-Look-Like-That-)

Without this, any metrics defined in lightdash/dbt that are not count or sum distincts are prone to fanouts and incorrect numbers.

_See example below:_
- The orders model in lightdash demo shows avg order amount as 16.89 (see [here](https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/tables/orders?metrics=orders_avg_amount%2Corders_unique_order_count&sort=%5B%7B%22fieldId%22%3A%22orders_avg_amount%22%2C%22descending%22%3Atrue%7D%5D&limit=500&column_order=orders_avg_amount%2Corders_unique_order_count))
- The join from payments to orders is a many to one join, so the avg order amount from the payments explore is incorrect, at 18.43
(see [here](https://demo.lightdash.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/tables/payments?metrics=payments_total_revenue%2Cpayments_unique_payment_count%2Corders_avg_amount%2Corders_unique_order_count&sort=%5B%7B%22fieldId%22%3A%22payments_total_revenue%22%2C%22descending%22%3Atrue%7D%5D&limit=500&column_order=payments_total_revenue%2Cpayments_unique_payment_count%2Corders_avg_amount%2Corders_unique_order_count))

**I highly recommend that a similar feature is built, so that:**
1. The join relationship is defined
2. Primary keys for models/tables are defined, to uniquely identify a row
3. Lightdash dynamically updates the metric logic, so that unique rows are only included once when a fanout occurs

**Without this, explores will be limited to only certain metrics or one-to-one joins between tables**

**Comment by TuringLovesDeathMetal** [comment]
Totally agree with this!

We actually had a similar discussion about this a week or two ago here: https://github.com/lightdash/lightdash/issues/753

I've added this to the backlog for this week! So hopefully we'll have something sorted by the end of next week 🤞 will keep you updated :)

**Comment by TuringLovesDeathMetal** [comment]
(another good doc on Symmetric Aggregates in Looker [here](https://help.looker.com/hc/en-us/articles/360023722974-A-Simple-Explanation-of-Symmetric-Aggregates-or-Why-On-Earth-Does-My-SQL-Look-Like-That-))

**Comment by owlas** [comment]
Another good doc on issues with multiple fact tables: https://community.thoughtspot.com/customers/s/article/What-is-Attribution-and-Chasm-Traps

**Comment by owlas** [comment]
@all-contributors add @NaomiJohnson for design, bugs

**Comment by TuringLovesDeathMetal** [comment]
#961 <-- here's a feature request proposal for this!
