### ISSUE TITLE
Allow users to store their own redshift / postgres credentials on their profile

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#8611]
### Description

Feature flag

- [ ] Users can add a set of postgres/redshift credentials via the UI under their profile
- [ ] Implement functionality for users to create, update, and delete credentials  a set of postgres/redshift credentials via the UI under their profile
- [ ] The credentials are just a username + password
- [ ] Credentials should be encrypted in db
- [ ] On read, only the username should be returned to the client, not the password
- [ ] Credentials have a unique id but also a friendly name

**Comment by joaoviana** [comment]
> Users can add a set of postgres/redshift credentials via the UI under their profile

working on this one
