### ISSUE TITLE
Build timeframes for date and timestamp columns/dimensions

### ISSUE THREAD

**Issue by NaomiJohnson** [lightdash/lightdash#862]
It is often the case where a date or timestamp column is analysed at a less granular level, e.g. week, month etc

**I suggest to build a feature to specify the timeframes to add to the explore for a date/timeframe dimension (similar to [this](https://docs.looker.com/reference/field-params/dimension_group)), rather than needing to build every timeframe as a column in a dbt model.**
Currently, it seems that every timeframe would need to be created as a column in the dbt model, and therefore the table. The UX for this table will be negatively impacted by this, when the table is queried (either in the data warehouse, or SQL runner in lightdash)

By building this timeframe feature, the timeframes can be grouped under the one date/timeframe dimension and allow for the end user to select the timeframe they would like. The query would dynamically change based on (a) the timeframe used, and (b) the data warehouse queried.
E.g. for Snowflake, order week would be `date_trunc('week', order_date)`

I cannot see this feature in docs or when using the demo - if it exists, please delete the issue

**Comment by ZeRego** [comment]
Thanks for bringing this up @NaomiJohnson :) 
This relates to the https://github.com/lightdash/lightdash/issues/193 feature request. cc: @TuringLovesDeathMetal

**Comment by TuringLovesDeathMetal** [comment]
^Yep! This one's also in the backlog for this week 💪 @NaomiJohnson looks like your issues have aligned perfectly with weekly planning - fancy a PM job? 😅

**Comment by NaomiJohnson** [comment]
Amazing, great to hear! I'll continue to send over any more ideas I have

**Comment by TuringLovesDeathMetal** [comment]
Closed in favour of #193
