### ISSUE TITLE
Time intervals should be ordered chronologically in the sidebar

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8624]
### Description

![image](https://github.com/lightdash/lightdash/assets/31848148/1b1f458e-122e-4deb-9eac-291d12a58575)

It should be day --> week --> month --> quarter --> year

**Comment by jogeshwar01** [comment]
@TuringLovesDeathMetal 
Unable to reproduce this issue. I tried to manually set intervals on the schema and then checked the sorting.
It is working fine. The chronological sorting seems to be implemented already.

https://github.com/lightdash/lightdash/blob/9ae1ee874c1724a96d7ad30784a1898aa6e9da79/packages/common/src/utils/timeFrames.ts#L505-L506

![image](https://github.com/lightdash/lightdash/assets/85165953/06a58af0-01e3-483c-b123-a3ea30c8aaae)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned - it's not able to be reproduced and hasn't been reported again. 

Will reopen if it becomes an issue!
