### ISSUE TITLE
When I load a chart in the explore view, it says "no data available", then the data just shows up 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8627]
### Description

when you load a chart, it says “no data available” but actually, it’s just waiting for the results to load?
Here’s a video of what I mean (I refresh the page, and you see no data available but then it just shows the data): https://www.loom.com/share/fa1e36856f574623bd0d6d8e296261ce

Instead, it should say `data loading` or something?

**Comment by Ankush263** [comment]
Hello, I can help. We can use a loader(Mantine Loader) with some texts. @rephus please assign me to this issue.
