### ISSUE TITLE
When a table calculation involves a custom metric, renaming the metric causes it to break.

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#8628]
I've noticed a couple more issues during testing:

When a table calculation involves a custom metric, renaming the metric causes it to break.
 

_Originally posted by @jogeshwar01 in https://github.com/lightdash/lightdash/issues/8521#issuecomment-1894363261_

**Comment by jogeshwar01** [comment]
This also breaks in case of removing a custom metric. So we would have to handle that as well.
