### ISSUE TITLE
Blank screen when I add a dimension, don't run the query, add ordering, then try to group by the dimension

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#864]
https://www.loom.com/share/92a50556d54f4a42967fe8753a60640d

^I addede a dimension, didn't run the query. Then added sorting: it runs the query automatically. Then, I try to `group by` the dimension and it leads to this blank screen

**Comment by owlas** [comment]
Hey @TuringLovesDeathMetal - if you open the console in the development tools ([instructions to open dev tools](https://balsamiq.com/support/faqs/browserconsole/)) do you see any errors? If so, can you share?

**Comment by TuringLovesDeathMetal** [comment]
![image](https://user-images.githubusercontent.com/31848148/142894063-48e77caa-6ce4-4d21-b52f-417eab1bba48.png)

yep! pinged some errors at me

**Comment by owlas** [comment]
Thanks!

**Comment by ZeRego** [comment]
Related with #874

**Comment by ZeRego** [comment]
Problem found: 
This happens when the user is grouping by a boolean dimension and with only one metric/table calc.
