### ISSUE TITLE
 Show all users that have access to a space and their role

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8655]
### Description

If I open the `share` modal for a full access space, I should see a list of all users who have access to the space alongside their space roles. 

This is what it looks like today: 
<img width="630" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/02f2c17f-41f5-473e-945a-2502fd50b160">

This should look similar to the `project access` list in the `project access` settings page. Maybe some copy like "This user can view this space because they are a project Viewer."

<img width="864" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/6ba487fb-ab69-4840-918e-a83e0dbdcbef">

### Acceptance criteria

- [ ] Users with viewer role:`Can view` appear beside their name in the list. 
- [ ] Users who editor role: `Can edit` appear beside their name in the list.
- [ ] Show all the users with direct or inherited access independently if the space is private
- [ ] Note: you can't yet change the access to a space in this ticket!

---

Tech notes:

Goal: Show all users that have access to a space and their role

Currently, the frontend calls a few endpoints and stitches the information together to know what users have access to a project and which what role. There is a bug currently where it doesn't show the users that have access to the space via a group. We are going to move all this logic to the backend and fix it.

Note that this list of changes might not include everything. Use your judgment and look at similar code if possible.

```jsx
type Space = {
  ...
  access: SpaceShare[];
}

export type SpaceShare = {
  userUuid: string;
  firstName: string;
  lastName: string;
  role: SpaceMemberRole; 
  hasDirectAccess: boolean;
  inheritedRole: SpaceMemberRole | undefined;
  inheritedFrom: 'organization' | 'project' | 'group' | undefined
};

enum SpaceMemberRole {
  VIEWER = 'viewer',
  EDITOR = 'editor',
}
```

- [ ]  update `Space` type
    - [ ]  `access` should be required
- [ ]  update `SpaceShare` type
    - [ ]  replace `ProjectMemberRole` with `SpaceMemberRole`
    - [ ]  add `hasDirectAccess: boolean` which should be false if inherits role from organization or project but not group
    - [ ]  add `inheritedRole: SpaceMemberRole | undefined` which contains the org/project/group role
    - [ ]  add `inheritedFrom: 'organization' | 'project' | 'group' | undefined` which contains the org/project/group name when the role is inherited
- [ ]  update `getSpaceAccess` in `SpaceModel`
    - [ ]  it should return all the users that have access to the space
    - [ ]  we need to convert the project/org role to a space role for now
- [ ]  update `ShareSpaceModal` component
    - [ ]  remove calls to org members and project access
    - [ ]  display all users with access
        - [ ]  show tooltip about inherited roles

**Comment by owlas** [comment]
Something like "This user can view this space because they are an Organization Viewer"
