### ISSUE TITLE
Allow to edit space roles

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8656]
### Description

Allow to edit space roles. Users who are space editors can manage the space resources. Users who are space admins can manage space access.

### Acceptance criteria

- [ ] Only admins can update it's members roles.
- [ ] An admin can change the space role of a user to Viewer/Editor/Admin.
   - Exception 1: admins cannot have their space role changed
   - Exception 2: org/project viewers cannot be space editor/admins. Interactive viewers can.
- [ ] A org/project editor can be a space viewer. If so, they cannot edit that space resources.
- [ ] A org/project interactive viewer can be a space editor. If so, they can edit that space resources.

# Tech notes

Goal: allow to edit individual user space roles

Note that this list of changes might not include everything. Use your judgment and look at similar code if possible.

- [ ]  create table `space_user_access`
    - [ ]  user_uuid
    - [ ]  space_uuid
    - [ ]  space_role
    - [ ]  created_at
    - [ ]  updated_at
- [ ]  migrate data from `space_share` & delete table
    - [ ]  fetch user admin role, project user role, project groups role. If they are editor or above, set them as space admins.
    - [ ]  ignore/skip cases where user_id no longer has access to the project
- [ ]  update `/projects/${projectUuid}/spaces/${spaceUuid}/share` endpoint
    - [ ]  receive a space role
    - [ ]  upsert row in `space_user_access`
- [ ] update SpaceModel.getSpaceAccess() to only inherit role if they are org/project admin
- [ ] update `ShareSpaceModal` component
    - [ ]  allow to change roles
- [ ]  update all calls to `getUserAbilityBuilder` in UserModel to use space role from DB

**Comment by owlas** [comment]
> A user's space permissions are additive (not overriding). E.g. if I have project editor access, I cannot be "downgraded" to a space viewer. If you try to change my permissions to Can view, you will see an error like this (the copy should say this user has the project role: editor.)

This is great. Just one clarifying question, should this be a warning not an error? I may want to set somebody as a viewer before revoking their project/org access (say I was downgrading their permissions). Showing the warning is a great UX boost, but I don't think we should prevent them taking the action

**Comment by owlas** [comment]
@ZeRego we need to be careful about how we design this permission in the database. Because presumably:

- If I lose access to the project I should lose access to the space (@TuringLovesDeathMetal ?)
- I could lose access via my organization role, project role, or a project assignment through a group

So it may be important to check

```
user has access to project ? AND user has edit access
```
