### ISSUE TITLE
Allow group access to spaces

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#8718]
Goal: allow group space roles

### UI

- In the modal showing access, order by role, but within roles, order groups first, then users
- If I search for a group to invite, they should appear. Search should show groups with a different avatar (see below).
- The groups should appear the same as users, but instead of an avatar with their initials, it should be an avatar with a picture that looks like three people's silhouettes 👥
- Maybe we make it a different colour? let's try and see...

### Tech notes

Note that this list of changes might not include everything. Use your judgment and look at similar code if possible.

- [ ]  create table `space_group_access`
    - [ ]  group_uuid
    - [ ]  space_uuid
    - [ ]  space_role
    - [ ]  created_at
    - [ ]  updated_at
- [ ]  update space endpoints to get/create/update/delete group access
- [ ]  update `ShareSpaceModal` component
    - [ ]  allow to add/edit groups
- [ ]  update all calls to `getUserAbilityBuilder` in UserModel to include space group access
- [ ]  update `getSpaceAccess` in `SpaceModel` to include space group access

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C06GC0U6D2T/p1711469639616359?thread_ts=1711469639.616359&cid=C06GC0U6D2T

**Comment by TuringLovesDeathMetal** [comment]
THis issue has been completed and released!
