### ISSUE TITLE
Fix validation error for non-existent filter columns

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8730]
### Description

Users encounter a validation error for filters linked to deleted columns. The error persists even after removing the filter and dismissing the error message

![CleanShot 2024-01-25 at 22 02 18](https://github.com/lightdash/lightdash/assets/962095/f7edcb72-1b6d-47a3-afae-76f1b77b5e8d)

**Comment by uttam17** [comment]
Let me know if I can provide any additional information! https://lightdash-community.slack.com/archives/C03MG2VTR08/p1706202784526829?thread_ts=1701274352.331179&cid=C03MG2VTR08

**Comment by rephus** [comment]
Unable to replicate
