### ISSUE TITLE
Inconsistent spacing between label and field 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#8736]
<img width="227" alt="Screenshot 2024-01-26 at 10 00 56" src="https://github.com/lightdash/lightdash/assets/12776522/58c36c79-e179-4f32-b724-c9ee35d0eec9">

The spacing between the Delivery name and the field below it is no consistent with the other fields in the same form

- [ ] Delivery name spacing should match the other fields in the form

**Comment by jogeshwar01** [comment]
@PriPatel Can I take this up?

**Comment by PriPatel** [comment]
@jogeshwar01 yep go for it!
