### ISSUE TITLE
The 'Save' button on Settings forms should be inactive until a change has actually been made

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#8738]
<img width="908" alt="Screenshot 2024-01-26 at 10 07 51" src="https://github.com/lightdash/lightdash/assets/12776522/a63cce60-ad7e-43f8-a58f-ca42331b9549">

The `Save` button here is active even though I've made no changes.

**Problems**
- When I do a make a change, the state of the button doesn't change, so I'm not sure if my changes have saved(!)
- When I want to undo my changes, I feel like I need to refresh to cancel them
- On a page with many forms, there are many active primary CTAs - it's information overload. 

**Proposal**
- [ ] The `Save` Button should be disabled until a change has been made
- [ ] Once a change has been made, there should be an option to cancel that change. When I click on this, the changes revert and the `Save` button goes back to being disabled

The **Appearance** tab in the Settings Page already does this correctly. Follow this pattern!

**Areas of impact in the form settings**

- [ ] User settings - **Profile form**
- [ ] User settings -  **Password form** 
- [ ] Project - **Tables Configuration form** 
- [ ] Organizations - **General form**
- [ ] Organizations - **Embedding configuration form**

**Comment by jogeshwar01** [comment]
@PriPatel Can I work on this?

Also, I just wanted to check on the ` Organizations - Embedding configuration form`. It doesn't seem to be present in the code.
I do see it in the docs - https://docs.lightdash.com/references/embedding/. Is the code for this closed-source for now?
