### ISSUE TITLE
In memory table calculations

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#8766]
### Description

Run table calculations in memory in the backend on a results set, rather than in the warehouse.

- [ ] Looking at existing table calculations to get a better sense of the amount of existing records + extract any other useful metrics, or just a sample for later testing
- [ ] run the new DuckDB implementation in parallel in the background for a sample of these table calculations to extract additional performance metrics
- [ ] Add feature flag for implementation
- [ ] Only apply in-memory to new charts not existing ones
- [ ] Add performance monitoring around existing queries to measure impact of in memory table calcs

**Comment by filp** [comment]
Reopening, was accidentally closed via linked PR https://github.com/lightdash/lightdash/pull/8780
