### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#878]
Relates to #877

We should enable the bot so we keep dependencies updated.

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

**Comment by elton-okawa** [comment]
I noticed it's already activated, see newest PR #5844 and [others merged](https://github.com/lightdash/lightdash/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies+)

I think we can close this issue 😄
