### ISSUE TITLE
Error when migrating down

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#879]
```
migration file "20211118105119_add_markdown_and_loom_dashboard_tiles.ts" failed
migration failed with error: delete from "dashboard_tile_types" where "dashboard_tile_type" in ($1, $2) - update or delete on table "dashboard_tile_types" violates foreign key constraint "dashboard_tiles_type_foreign" on table "dashboard_tiles"
delete from "dashboard_tile_types" where "dashboard_tile_type" in ($1, $2) - update or delete on table "dashboard_tile_types" violates foreign key constraint "dashboard_tiles_type_foreign" on table "dashboard_tiles"
Key (dashboard_tile_type)=(markdown) is still referenced from table "dashboard_tiles".
error: delete from "dashboard_tile_types" where "dashboard_tile_type" in ($1, $2) - update or delete on table "dashboard_tile_types" violates foreign key constraint "dashboard_tiles_type_foreign" on table "dashboard_tiles"
```
This happens becasue there is a dashboard with a tile of type markdown/loom

**Comment by owlas** [comment]
@ZeRego in the migration down the deletes are in the wrong order:

https://github.com/lightdash/lightdash/blob/13f881f6adec551005d4594b0fe580b3ecb24219/packages/backend/src/database/migrations/20211118105119_add_markdown_and_loom_dashboard_tiles.ts#L65-L69

Any references to the `TileType` enum has `.ondelete('RESTRICT')` clause, so you cannot delete `TileType` enums if they are used anywhere in the DB.

The references should be deleted first (i.e. all the tiles should be deleted first) - then when there are no more loom/markdown tiles in the DB, you can drop the type.
