### ISSUE TITLE
ability to set results in explore to be default "scroll" rather than "page"

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8800]
### Description

Currently, it is hardcoded to default to "page". There should be one of these options:
- An environment variable to control which behavior is the default.
- An entry in the settings page? (Should it be at the user level or organization level? 🤔 )
- Saving the previous state: if a user switches to "scroll", the "scroll" setting should be saved in the browser.

![CleanShot 2024-01-31 at 17 13 31@2x](https://github.com/lightdash/lightdash/assets/962095/f0d8127f-c073-4467-b3ea-d92cd3bb0dd4)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. It hasn't been requested by any other users and I don't believe it's something that should be customizable (the burden of clicking between page <> scroll doesn't feel big enough for this to be a massive UX issue).
