### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by jenna-parker** [lightdash/lightdash#8825]
### Description

Receiving 414 Request-URI Too Large when clicking 'Explore from here' on a chart

### App Version

Version: v0.963.1

**Comment by ZeRego** [comment]
Related to https://github.com/lightdash/lightdash/issues/4137#issuecomment-1838446154

**Comment by rephus** [comment]
Steps to replicate on a `chart` : 
- create a chart with a long filter (eg: loren ipsum) 
- Save
- Click explore from here
- :fire: 

![image](https://github.com/lightdash/lightdash/assets/1983672/7c6e71f1-e0d0-4485-bf75-d9a1caa5dd1b)

This got fixed recently in `explore from here` on dashboards by using `share` urls and opening in a new tab. We can apply the same fix here

**Comment by joaoviana** [comment]
Another error code is `431`
