### ISSUE TITLE
Can't add custom value to a filter when there are 100 results

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#8840]
### To Reproduce

- go to a dashboard
- add a string filter
- type a custom value
- if there are 100 suggestions, I can't add the custom text as the filter value

### App Version

0.970.0

**Comment by filp** [comment]
Haven't been able to replicate this yet, tried having 100, >100 suggestions, and also messing around with the suggestion list limit;

**Comment by hamzahc1** [comment]
Here's the link to the original issue if that's helpful @filp https://lightdash.slack.com/archives/C04FQQU4RL7/p1706885888412239

**Comment by filp** [comment]
Thanks @hamzahc1! Will see if there's any additional context there that might help 💪
