### ISSUE TITLE
allowed email domains for organizations should have unique constraint

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8841]
### Description

at the moment you can assign same email domain in different organizations

![CleanShot 2024-02-02 at 20 04 55@2x](https://github.com/lightdash/lightdash/assets/962095/3dc3dff2-b394-4e09-9e70-b21cb565bc36)

![CleanShot 2024-02-02 at 20 06 29@2x](https://github.com/lightdash/lightdash/assets/962095/c92342bc-0e66-4b62-8d89-972330a5e9c6)

**Comment by rephus** [comment]
We'll need to make sure we can add this `unique` filter on prod before merging, otherwise migration will fail. Specially on app and eu1

**Comment by owlas** [comment]
Is this a problem? The UX is built around allowing this. i.e. after you login you can choose from one of many orgs to join.

**Comment by owlas** [comment]
Closing for upcoming milestone to improve org sso
