### ISSUE TITLE
Value labels aren't shown on a line chart unless `show symbols` is selected

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8857]
### Description

https://www.loom.com/share/af8fcc3d507a4fbc82a674a56733b05a?from_recorder=1&focus_title=1

**Comment by jogeshwar01** [comment]
@TuringLovesDeathMetal 
It looks like a similar issue had popped up earlier as well. #5516 
Echarts didn't seem to have an option for this then. Labels were only displayed in line series when symbols were visible.
