### ISSUE TITLE
conditional formatting isn't showing up for some whole numbers

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8873]
### Description

- using `less than 0` for negative numbers in conditional formatting doesn't work

https://www.loom.com/share/a7090b99e3574db5807ac2087b21fbf4?from_recorder=1&focus_title=1

- there's also an issue with percentages between 100% and 200%.

I think this might be related to this issue: https://github.com/lightdash/lightdash/issues/8710

Here's another user example of similar behaviour: https://lightdash.slack.com/archives/C05F0N3UPSP/p1707412704776399?thread_ts=1707412150.154529&cid=C05F0N3UPSP

**Comment by TuringLovesDeathMetal** [comment]
This is also an issue with percentages between 100% and 200%. 

I think this might be related to this issue: https://github.com/lightdash/lightdash/issues/8710

Here's another user example of similar behaviour: https://lightdash.slack.com/archives/C05F0N3UPSP/p1707412704776399?thread_ts=1707412150.154529&cid=C05F0N3UPSP

**Comment by joaoviana** [comment]
just a fyi: 
- setting a `0` wasn't doing anything before and after the PR linked to #8710

**Comment by joaoviana** [comment]
I'm unable to replicate the 100-200 color range not working. Were you able to @TuringLovesDeathMetal ?
