### ISSUE TITLE
use new github integration to improve github project connection 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#8878]
### Description

We can be using new integration to select a repo / branch from the list of available repos when connecting a project
<img width="870" alt="image" src="https://github.com/lightdash/lightdash/assets/1983672/148b94d4-2a78-4e65-adc2-c0d73c3cf78a">

We need to think what's going to be the flow , specially for a fresh new onboarding. Do we show the `install` github button in this modal if the account is not linked yet ?

**Comment by TuringLovesDeathMetal** [comment]
closing this issue as not planned - I think that we will eventually do this, but I feel like this ticket doesn't have the detail we need for the work (so we can always reopen a ticket when we decide on the flow!)
