### ISSUE TITLE
Expand Date Zoom to Affect Table Calculations

### ISSUE THREAD

**Issue by gracemalirBP** [lightdash/lightdash#8885]
### Description

When Date Zoom is applied all tiles will be updated to the new date granularity meaning more custom metrics and calculations will be impacted by Date Zoom.

### What problem does this solve?

Currently Date Zoom seems to only affect dimensions. This means when date granularity is changed in a dashboard where a tile shows a table calculation that includes the date dimension, the tile breaks. eg period vs period % change.

(
DIV0(${SUM_TOTAL_PAID_EX_TAX_GBP},LAG(${SUM_TOTAL_PAID_EX_TAX_GBP},1) OVER(
    ORDER BY 
      ${DATE_PLACED_AT_week})
  )
) - 1

**Comment by joaoviana** [comment]
Hey @gracemalirBP!

Here is a screen recording of one example I've got that includes: 
* date dimension
* table calculation that references that same date dimension

I've updated the date zoom to the granularities available and can't see issues with the tile 🤔 

https://github.com/lightdash/lightdash/assets/7611706/6740dfb6-ec67-4db5-bdd7-a93a65e9ee26

**Comment by gracemalirBP** [comment]
Thanks @joaoviana ! Will close this feature request and I will submit more qs via slack if I can't find a solution in our dashboards.
