### ISSUE TITLE
Navbar should indicate where you are at any given time. 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#889]
### **Context**
As a first time user, after logging in for the first time , I was unsure about whether I was on the homepage or not. It was only after clicking on `Explore`, I could see that I was on the `Tables` page. 

![Screenshot 2021-11-24 at 18 03 24](https://user-images.githubusercontent.com/12776522/143292202-7c53ce7a-7da8-4bb7-99a9-8b94c9b478d3.png)

### **Goal**
 I should be able to tell where I am in the app without having to click on anything. The `Explore` tab should be highlighted in some way. This gives me a sense of what I can do on this page as well!

**Comment by hamzahc1** [comment]
@all-contributors add @PriPatel for design
