### ISSUE TITLE
It is not obvious that dashboard tiles are draggable

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#890]
### **Context**
It is not immediately obvious that the tiles in a dashboard are draggable. I only discovered this whilst watching someone else use it.  It is a nice feature that allows customisation so it is a shame that it is not that obvious!

### **Goal**

Similiar to the resize icon that appears at the bottom right of a tile, we could show a drag handle on the top left somewhere. This would also indicate the click target area (as you can't just drag from every point on the tile).  Alternatively, we could just show some instructions!  

![Screenshot 2021-11-24 at 18 28 12](https://user-images.githubusercontent.com/12776522/143294745-057b5189-e809-4962-b4bf-4cc7eb03a531.png)

**Comment by owlas** [comment]
@all-contributors add @PriPatel for bugs

**Comment by TuringLovesDeathMetal** [comment]
+1 for this! 

I recently spent 5 minutes trying to figure out why a tile wasn't dragging. 

Specifically: it's unclear that only the top right corner can be used to drag a tile (otherwise, it doesn't work)

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue: you can now drag a chart from anywhere on the chart
