### ISSUE TITLE
Use embedding model to improve search results

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#8918]
## Problem

Current search only searches by strictly equal words, we want to improve search so it performs a similarity search and returns relevant items.

The idea is to use an embedding model running locally, create a vector representation of the items to be searched and perform a semantic search by similarity.

This will work in conjunction with #5631 to comply not only with semantic similarity but also wrongly typed queries.

Note: add environment variable to toggle this feature on/off.

Add it to:

- [ ] Charts
- [x] Dashboards
- [ ] Spaces
- [ ] Tables
- [ ] Metrics
- [ ] Dimensions

### What problem does this solve?

Incomplete search results.

**Comment by almeidabbm** [comment]
@IrakliJani after standup today it was decided to change the scope of the search v2 to only include full text search, and leave this ticket for later.

I will get started on preserving the work we did here onto a separate branch, link it here and revert the commits for embedding from the `search-v2` branch

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. Can reopen if we decide this is a priority
