### ISSUE TITLE
`dbt ls` < 1.6.6 doesn't support `--quiet` flag

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#8928]
### Description

Update the following: https://github.com/lightdash/lightdash/blob/f720643ef3606d52c75275d323eb62efead63455/packages/cli/src/handlers/dbt/compile.ts#L83-L87 to not push `--quiet` flag when dbt version is < 1.6.6

error output example for < 1.6.6
``` 
Command failed with exit code 2: dbt ls --project-dir ./ --profiles-dir . --target TARGET --select tag:lightdash --output json --output-keys unique_id --quiet
Usage: dbt ls [OPTIONS]
Try 'dbt ls -h' for help.
Error: No such option: --quiet
```

**Comment by ZeRego** [comment]
Dbt 1.5 supports `--quiet` as our CLI tests are passing.

Also checked manually: 

<img width="1083" alt="Screenshot 2024-02-15 at 08 30 00" src="https://github.com/lightdash/lightdash/assets/9117144/52409b35-8cef-4380-86fc-012ab0f49c9e">
