### ISSUE TITLE
Update layout of Chart Context menus

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#8964]
<img width="378" alt="Screenshot 2024-02-16 at 15 53 49" src="https://github.com/lightdash/lightdash/assets/12776522/d8c659cd-d8a3-43f6-8f83-9c00d47e3402">

Make the menu similar to the one we use for 'Move to Space'

- [ ] Use dropdown headings to separate the options into two groups `Manage` and `Integrations`. Keep `Delete` as it is at the bottom. 
Manage: `Save chart as`, `Add to Dashboard`, `Move to Space`, `View Version History`
Integrations: `Scheduled Deliveries`, `Google Sync`, `Alerts`

**Comment by joemiltonm** [comment]
Hi @PriPatel 

Is the following layout the expected one

![Screenshot from 2024-02-17 11-47-49](https://github.com/lightdash/lightdash/assets/64725924/825e2ba8-b4ba-47c2-9f2c-b8d4ab7d898c)

**Comment by PriPatel** [comment]
Hi @joemiltonm, that looks correct :)

**Comment by joemiltonm** [comment]
> Hi @joemiltonm, that looks correct :)

Thank you @PriPatel, will create the PR.
