### ISSUE TITLE
Threshold alerts - It should be clear that the value 'increased by' is either a 'raw' or 'percentage' increase.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#8983]
<img width="204" alt="Screenshot 2024-02-19 at 11 06 52" src="https://github.com/lightdash/lightdash/assets/12776522/7db01666-1b8f-40bd-9eae-9a530e2e99df">

Using a component similar to above could work. It should be clear that the user is either inputting a `%` increase or a `raw#` increase

**Comment by rephus** [comment]
Closing this in favor of https://github.com/lightdash/lightdash/issues/10980
