### ISSUE TITLE
Add analytics events (comments)

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#9004]
### Description

Track analytics events to measure the success of this feature. 

`comment_created`  
- is_reply
- has_mention
- dashboard_uuid
- dashboard_tile_uuid

`comment_deleted`
- is_reply
- has_mention
- dashboard_uuid
- dashboard_tile_uuid

`comment_resolved`
- has_mention
- is_owner
- dashboard_uuid
- dashboard_tile_uuid

`comment_clicked` (UI, when user clicks on Comment icon on a dashboard tile)
- dashboard_uuid
- dashboard_tile_uuid

**Comment by rephus** [comment]
@joaoviana I have a few questions about this spec:

See implementation here https://github.com/lightdash/lightdash/pull/9095

`comment_deleted / comment_resolved` properties
https://github.com/lightdash/lightdash/pull/9095/files#diff-2aea2dada45dc8837cc5dde0adf81957509661dd5c12d6059fb0fdd23c05b1ecR162

`notification_clicked` I'm not sure when this is triggered... I created a `comments_click` that is triggered in the frontend when the notification modal opens. Not sure if this is what you had in mind
https://github.com/lightdash/lightdash/pull/9095/files#diff-ccca38967d502ec896a6ece5ac015996b4a15c195b62a33d0ce91211400ca6f0R107

I don't know what this is : 

This should include:

    how many comments
    how many replies
    how many comments with mentions
    how many notification clicks
    how many comments were resolved

we should be able to calculate by aggregating the data in analytics, right ? or am I missing anything...

**Comment by joaoviana** [comment]
>`notification_clicked` I'm not sure when this is triggered... I created a `comments_click` that is triggered in the frontend when the notification modal opens. Not sure if this is what you had in mind https://github.com/lightdash/lightdash/pull/9095/files#diff-ccca38967d502ec896a6ece5ac015996b4a15c195b62a33d0ce91211400ca6f0R107

Nice! This is one I didnt' think about before but worth adding on the FE. 
The `notification_clicked` would be triggered when the user sees a new comment notification on the `bell` icon on the nav bar (yet to be implemented, but should be done here: 

https://github.com/lightdash/lightdash/issues/9048


> This should include:
> 
> ```
> how many comments
> how many replies
> how many comments with mentions
> how many notification clicks
> how many comments were resolved
> ```
> 
> we should be able to calculate by aggregating the data in analytics, right ? or am I missing anything...

yes, you're right. This should have been removed from the description because the events above that text are the ones that will be used for these calculations.
