### ISSUE TITLE
Publish dashboards to be shared publicly 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#906]
It would be cool if dashboards (and charts?) could be published to be shared to the web, similar to how Notion has this for pages with the little toggle. I imagine this would only work for Lightdash Cloud initially...

<img width="213" alt="Screenshot 2021-11-26 at 19 19 43" src="https://user-images.githubusercontent.com/14341285/143623139-ee12f19e-765c-4a96-ae78-a464c06eae1a.png">

**Comment by 12ian34** [comment]
not stale - just requested by a user, and i know many others could use this

**Comment by PriPatel** [comment]
Kinda related
https://github.com/lightdash/lightdash/issues/3273

**Comment by rephus** [comment]
We'll have to generate a nanoid or similar token to protect the charts and dashboards. A few 

- First we need to decide if we need to add extra tokens to pages, or existing URLs are cryptic enough to share without risk of someone guessing it (from outside the org) 
- If we add tokens, It will be something like `projects/3675b69e-8324-4110-bdca-059031aa8da3/dashboards/1213e56d-8b7b-4388-8a8d-d00de283303a/view?token=123abc`
- Page access/tokens will be stored in DB, it will grant access to 1 page in particular. (we can reuse shared with a flag) 
- Those URLs can be `shorten` using our `share url ` functionality
- If page is accessable / token is present, we don't need to login (skip login redirect), we show directly the chart/dashboard
- we can't allow to do anything: disable/hide edit, create buttons
- Those tokens can be revoked at any time.
- Maybe the current `share`button an open a popup with a toggle "make this public" ? 

- We want to use this too when sharing in slack  (so headless chrome can see the dashboard without authentication)

**Comment by owlas** [comment]
Yeah good idea! If we have a long enough id I think it would be secure enough, the problem with the existing dashboards is that you have to be authenticated for many API calls to render the dashboard correctly. And many of those api calls are too flexible.

I'm going to open my PR to fix this and have dashboards rendered from much simpler API calls that are less restrictive

**Comment by TuringLovesDeathMetal** [comment]
Closing this as completed! We now have embedding which allows users to do this :) 

https://docs.lightdash.com/guides/how-to-embed-content
