### ISSUE TITLE
Dashboard filter label is not applied inside the modal

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#9062]
### To Reproduce

Apply filter label

<img width="445" alt="Screenshot 2024-02-22 at 11 07 44" src="https://github.com/lightdash/lightdash/assets/9117144/97939e65-7283-46e8-9c62-f8c2ef1f8915">

In view mode we show the custom label in the "pill" but not inside the modal.

<img width="454" alt="Screenshot 2024-02-22 at 11 07 35" src="https://github.com/lightdash/lightdash/assets/9117144/11a0bfb0-0644-4652-acbb-a478dc143820">

### App Version

0.1001.6

**Comment by jogeshwar01** [comment]
@ZeRego Can I take this up?
Just to confirm, the expected title n the modal was `Customers Month` instead of `Customers Created month`, right?

**Comment by ZeRego** [comment]
@jogeshwar01 Yes you can work on it. Expected is the custom label, is this case `Month` as it shows in the filter "pill".
