### ISSUE TITLE
Chart image doesn't shrink with a shrinking window

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#907]
### Context
When you shrink a window, the chart image doesn't shrink with it (it fills out of the border, and you can't scroll to look at it). 
BUT if you re-run the query with teh small window, it fits to the window. 
Then, if you stretch the window, it stretches to fill the window. 
But, if you try to shrink it again, it doesn't shrink. 

https://www.loom.com/share/e6ba568a54a145d19f29937ccc772d8c

### Goal
Charts should dynamically shrink to fit a window

**Comment by ZeRego** [comment]
@nathaliabj Can you confirm this was fixed by your PR ? https://github.com/lightdash/lightdash/pull/1142

**Comment by nathaliabj** [comment]
@ZeRego yes, this should be fixed on #1142
