### ISSUE TITLE
Open alert modal config when you click on the ?scheduler_uuid link from slack 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#9075]
### Description

![image](https://github.com/lightdash/lightdash/assets/1983672/77254c2b-7b4d-4eb9-8d9c-67383d6dab8c)

WHat's happening: threshold alerts are in the backend a special type of `scheduled delivery` but in the UI we use a different modal to configure them. 

The backend creates the link for the frontend with threshold_uuid to open automatically the modal with the `threshold_uuid` , but this was never implemented in the frontend. 

What to do: See how it is done for `scheduler_uuid` and replicate this behaviour in the frontend for `threshold_uuid

Thread: https://lightdash.slack.com/archives/C016QJZA6JY/p1708622355093849?thread_ts=1708622053.352029&cid=C016QJZA6JY

### To Reproduce

Requirements: Having slack/email enabled
 
1. Create a threshold alert
2. Trigger the threshold alert
3. The `data alert` link will contain something like `https://x.lightdash.cloud/projects/<projectuuid>/saved/<chartuuid>?threshold_uuid=bcfaba98-54b7-429e-8aa1-33108fbc381f`
4. Clicking on the link doesn't open the modal 

### Acceptance criteria

- [ ] After clicking on the `data alert` in the slack (and email?) message, it should take you to the right chart, with this modal open 

![image](https://github.com/user-attachments/assets/49bfe1e7-221c-436c-bb7c-2a33cbef8a18)

**Comment by aayushi1995** [comment]
Hello @rephus, 
I want to contribute to this issue, But I don't have much information since the Slack URL doesn't work for me.
It would help if you could elaborate more on what the bug is and give me steps to reproduce it.
Thanks :)

**Comment by VenkataRohan** [comment]
Hi @rephus , I am interested in contributing to this issue

can I work on it?

**Comment by aayushi1995** [comment]
Hi @VenkataRohan, 
Please go ahead and work on this one.
I did not get enough time to work on it. 
I might start contributing after a few weeks.
Sorry @rephus

**Comment by VenkataRohan** [comment]
Hi @rephus , I have raised a PR #12119  for this issue 
can you please check
