### ISSUE TITLE
Copy change in 'Charts Context Menu'

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#9080]
<img width="233" alt="Screenshot 2024-02-23 at 10 44 05" src="https://github.com/lightdash/lightdash/assets/12776522/c1f7dca3-8b3a-4a2c-97ed-f253ceaa5203">

The chart context menu is now looking cleaner. The `integrations` bit feels inconsistent as the last item is a verb, whereas the first two options are nouns. It also spans two lines.

- [ ] Update `Sync with Google Sheets` --> `Google Sheets sync`

**Comment by jogeshwar01** [comment]
@PriPatel Can I fix this?
Also to verify, should we also change the modal title that opens up on clicking `Sync with Google Sheets` to `Google Sheets Sync` for consistency.

This one - 

![image](https://github.com/lightdash/lightdash/assets/85165953/2699b32e-c0f0-401f-adc0-22980e1a86ec)

**Comment by PriPatel** [comment]
@jogeshwar01 sounds great - go for it :)

**Comment by PriPatel** [comment]
@jogeshwar01 - for now lets just stick with the context menu! Thanks so much :)
