### ISSUE TITLE
Display the descriptions of the search results in gray

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9110]
### Description

Descriptions are the same color as the title of the search results, they should be a lighter gray so it's easier to read.

Use:
- title: default text color - same as home page entity title
- description: `gray.6` - same as home page type title and view count

**Comment by PriPatel** [comment]
<img width="274" alt="Screenshot 2024-02-26 at 16 56 10" src="https://github.com/lightdash/lightdash/assets/12776522/63d78ae2-a41e-4f6e-adc8-b2c49135692e">

you can reference similar title/description colours on the homepage btw!

**Comment by IrakliJani** [comment]
this is done ✅
