### ISSUE TITLE
Markdown tiles should be freetext (i.e. not include a required title)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#912]
### Context
Right now, you're required to have a title + body in a markdown tile. 

Sometimes, if you're just trying to group sets of tiles together, you'll just want to have a `title` without a body. (e.g. I have 3 tiles that are to do with `adoption`, I just want to write `adoption` and no body) or a body without a title.

**Comment by hamzahc1** [comment]
Adding to this, the expected behaviour for me would be: 

- Title shows up as a H1 heading (or you can choose h1, h2, h3) 
- Accept only markdown defined in the body and you don't need a title.

**Comment by owlas** [comment]
@TuringLovesDeathMetal the title is confusing, are you proposing that valid configs are:

* title only ✅ 
* body only ✅ 
* title and body ✅ 
* neither ❌ 
?

**Comment by TuringLovesDeathMetal** [comment]
yes, exactly. 

neither is not an option. but all other configs are. 

also, +1 with what Hamzah said about title showing up as an H1 heading. I don't think you should be able to choose h1, h2 or h3 for the title since if you're able to have body-only, then you could just make the first line into an H2 heading if you really wanted to.

**Comment by hamzahc1** [comment]
I think we should simplify this and just make it a free text markdown tile - i.e. users can choose to add a title with H1 if they want - rather than us enforcing it.
