### ISSUE TITLE
Create dashboard to measure engagements with comments

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#9120]
Examples: https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/dashboards/d195e232-e9ea-4518-88a6-211f702fda5f

**Comment by joaoviana** [comment]
Sounds good 👍

**Comment by joaoviana** [comment]
Done, it's called: Dashboard Comments - Feature usage
