### ISSUE TITLE
dbt connection setup fails for Azure DevOps

### ISSUE THREAD

**Issue by pascal-holy** [lightdash/lightdash#9133]
### Description

I want to setup a dbt connection to Azure DevOps. The "branch" value is taken from the "path" key once I click on Test and Compile project. Then I get the error `The "path" argument must be of type string. Received undefined`

### To Reproduce

<img width="1485" alt="Screenshot 2024-02-27 at 16 37 33" src="https://github.com/lightdash/lightdash/assets/54705263/aaa8dedd-59df-429c-b722-a6dc5b26432a">

### App Version
0.1018.1

**Comment by owlas** [comment]
Hey pascal, thanks for opening this! Is this the first time you tried to connect via Azure DevOps? Or were you updating an existing connection? Have you had this working previously?

**Comment by pascal-holy** [comment]
Hey owlas,
thanks for taking a look at my problem. We had an old version running on Heroku. There everything worked. But now we want to deploy via Hossted and are getting this behaviour on all browsers.
