### ISSUE TITLE
Rename type "Dependencies"

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#9172]
Nitpick: I'd avoid language specific to dependency injection at this level, to avoid binding individual classes overly to how dependency management actually works, and make it clear these are just constructor arguments like any others.

_Originally posted by @filp in https://github.com/lightdash/lightdash/pull/9156#discussion_r1507391791_
            

The same applies to types `{class name}Dependencies`. eg: GroupServiceDependencies

Rename all these types to "{class name}Arguments. 
         

<img width="1013" alt="Screenshot 2024-02-29 at 13 20 58" src="https://github.com/lightdash/lightdash/assets/9117144/fac65327-86b8-404b-948b-628c2daffe0b">

**Comment by jogeshwar01** [comment]
@ZeRego Can I take this up?

**Comment by ZeRego** [comment]
@jogeshwar01 yes
