### ISSUE TITLE
Add a flag to lightdash generate to remove unused columns

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#9194]
### Description

Add a flag to `lightdash generate` to remove unused columns. At the moment the CLI doesnt remove columns on `lightdash generate`. We should keep that default behavior, but also add a flag so people can specify that they want columns removed.

**Comment by TuringLovesDeathMetal** [comment]
This does happen already 🤔 



![Image](https://github.com/lightdash/lightdash/assets/31848148/8f6eaf37-967d-4b27-b518-8e4de25f9359)


I'm going to close this as not planned - we can always reopen as needed!

**Comment by Ester-Ramos** [comment]
hi! this doesn't happen in the Github CI. According to one of your team:
![Screenshot 2024-03-05 at 09 03 21](https://github.com/lightdash/lightdash/assets/11940897/3e08f3b8-f095-4fa9-a4d8-77c0f94e2f92)
