### ISSUE TITLE
You should be able to filter at a dashboard level

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#921]
**Tasks**
- [x] #1273
- [x] #1274
- [x] #1275
- [x] #1330

### Context
If you have multiple charts on a dashboard, you should be able to filter all of the charts on that dashboard using common fields/metrics. 

These filters should be applied to the charts of your choice within the dashboard

**Comment by djayatillake** [comment]
Will we be making a new object like filters called dashboard filters or will dashboards have a property also called filters?

**Comment by TuringLovesDeathMetal** [comment]
I'd imagine that it would be a new object, since filters at a dashboard-level would require parameters that current filters don't have (e.g. which charts to apply the filter to, which fields from those charts the filter should be applied to) 🤔

**Comment by PriPatel** [comment]
Here's a summary of what we've discussed so far and an initial plan for how we want to build these features out. @TuringLovesDeathMetal @owlas Please edit whatever you need to!!


> "As a user, I have a dashboard made up of charts that were created using table 1 and table 2"




**V1. Add filters to dashboard (but they are not saved)**

> -  User is able to select a filter field to apply to chart(s) on their dashboard from a dropdown. (the field options displayed are from table 1 and table 2 but **not** table 3)
> -  If the filter field is from table 1 - all charts from table 1 will be affected.
> - User is able to clear the filter. 
> -  It is clear to the user which table has been affected, and which has not. (nice-to-have)
> -  TBD  - How does overriding work?


**V2. Add filters to dashboard (but they are saved)**

> - User is able to ‘save’ their applied filter to the dashboard. 
> - User is able to edit the saved filters to a dashboard.
> - The filter is applied instantly without the need to hit an ‘apply’ button. (nice-to-have)
> - Filter field is an autocomplete dropdown (nice-to-have)


**V3. Autocomplete for better UX across the whole flow of adding filters**

> - User is able to add a filter field to apply to a single chart. eg. a filter field from table 1 only on Chart A, even though Chart B also includes this field.
> - If the chosen filter field applies to another chart, user has the option to “apply to all other valid charts.”
> - An improved UX flow, similar to how Metabase handles this. (Will add more to this later!)


**V4. Adding views to dashboards - so you can save multiple configurations of filters**
eg. User wants to create one dashboard (with filters) for Australia and they want multiple ‘copies’ of this dashboard but for the UK, the US and for the Middle East.

> - User is able to save a ‘view’ 
> - User is able to add multiple ‘views’
> - User is able to name their ‘views’
> - User is able to add filters on top of views.
> - User is easily able to switch between views.

**Comment by owlas** [comment]
This is great!

We can split these into multiple issues and link them under this ticket

**Comment by TuringLovesDeathMetal** [comment]
sounds good!!

Also, thought about the "override" vs. "add on" for the filter behaviour. 

I think I'm going with override. Based on this example with dates (which I think will be the most common type of dashboard filter): 

I have a chart A that has a filter "is in the past 3 weeks". 
I add a dashboard filter for date "is in the past 6 weeks". 

I would expect chart A to now show dates in the past 6 weeks.

**Comment by owlas** [comment]
@TuringLovesDeathMetal I'm unsure about the override part for two reasons (one UX one technical)

1. UX reason - if my chart is titled "Most viewed pages last month" I don't think I would expect it to change to the last 3 months because I changed the dashboard filter.
2. Technical reason - a chart could have many filters on it including the same column many times (`column is not NULL AND column is since x date OR column is before y date AND column is in the last 4 weeks`) - would we override all instances or just one?

It would be simpler (maybe I'm overweighting complexity of implementation) to just say:

`Chart filters = (chart-specific filters) AND (dashboard filters)`

**Comment by TuringLovesDeathMetal** [comment]
@owlas 
1. Really? I think I would expect this to change 🤔 ...what if I wanted to look at the most viewed pages from the last three months? 

2. I would expect it to override all of the filters 


I don't actually know the best answer to this....but...

- Metabase uses the "additive" approach ([here's a bunch of feedback from users who don't like it](https://github.com/metabase/metabase/issues/2763)...there might be loooooads who love it! But I found this useful to read through)
- [Looker uses the "override" approach](https://docs.looker.com/dashboards/dashboard-beta-filters#:~:text=Dashboard%20filters%20override%20filters%20applied%20to%20a%20tile%E2%80%99s%20underlying%20Look%20or%20Explore%20when%20both%20types%20of%20filters%20are%20filtering%20on%20the%20same%20field.%20See%20the%20Overriding%20Look%20filters%20in%20the%20Explore%20section%20with%20dashboard%20global%20filters%20Looker%20Community%20post%20for%20more%20details.)
- I have no idea what Tableau is doing 😅 but it looks _**sort of**_ additive - I think their "saved charts" are almost treated like separate datasets (sheets). So there's no concept of a saved chart having "it's own filters" ([here's a video explaining it starting at 2:14](https://help.tableau.com/current/pro/desktop/en-us/actions_filter.htm))

**Comment by TuringLovesDeathMetal** [comment]
I never wondered what Looker was doing in the background for dashboard level filters...which makes me feel like this is intuitive. 

_**but**_ if it's way harder to build technically and no one else agrees with me, then we should definitely build additive filters! and get feedback :)

**Comment by PriPatel** [comment]
[**Walkthrough for V1 here:** ](https://www.figma.com/proto/I2JQLUxDb533DXcYoHvrXC/Lightdash-product-(Copy)?node-id=1150%3A38891&scaling=min-zoom&page-id=1150%3A38890&starting-point-node-id=1150%3A38891
)
Super simplified!  Really reduces cognitive load and keeps the 'view' mode nice and clean.

[**V2**](https://www.figma.com/proto/I2JQLUxDb533DXcYoHvrXC/Lightdash-product-(Copy)?node-id=1152%3A43053&scaling=min-zoom&page-id=1150%3A38890&starting-point-node-id=1152%3A43053)
V2 works in the same way as V1. You can add filters on the fly that don't get saved. You can add filters in 'edit' mode that do get saved, but that can't be edited when you are in 'view' mode:

---
[Figma file with edge cases 
](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1097%3A37682
)

**Comment by ZeRego** [comment]
@PriPatel 
This looks really clean 🎉 
I think we need to show the operator in the tag/pill. E.g  'Order status equals pending, completed'
Also, don't we want to keep the field input so the user can edit it ?

@TuringLovesDeathMetal @owlas 
About the filter strategy, could we let the user choose the merging strategy ? 
- override: We will override all filter rules that use the same column
- additive: We will add the filter with an ADD operator to the filters root 

Notice I said 'filters root', to take in consideration complex filter logic with nested logic operations ( which we might support in the future ).

**Comment by TuringLovesDeathMetal** [comment]
Looks great @PriPatel !!!

**Comment by PriPatel** [comment]
thanks @owlas !

> V2. Add filters to dashboard (but they are saved)


Put simply, the idea here is when you refresh the dashboard, the filter you have added in 'edit' mode is saved.  (so you don't need to add a filter for date range every single time you open up the dashboard!). 

When you refresh the dashboard the filter you added when in view mode is not saved. ( so that data consumers don't mess things up!)

This paves the way for presets as you need to introduce the concept of saving first. So in V2, there is only one preset, the 'default' view. [Check out this walkthrough](https://www.figma.com/proto/I2JQLUxDb533DXcYoHvrXC/Lightdash-product-(Copy)?node-id=1156%3A47530&scaling=min-zoom&page-id=1156%3A47529&starting-point-node-id=1156%3A47530)
 Let me know if I've just misunderstood your point haha!!

**Comment by TuringLovesDeathMetal** [comment]
>  additive filters (I think) cover most use cases and are substantially simpler to implement than the override.

@owlas if they're much simpler, then let's do additive. I'm still in favour of override, but let's ship the additive and then we can collect feedback :)

**Comment by owlas** [comment]
> weirdly in favour
love this. yep let's experiment!

**Comment by owlas** [comment]
I think for now @ZeRego @nathaliabj we keep the logic for combining filters in the frontend? And push this behind the API once we've let users take it for a spin.

So it would go:

1. Open dashboard, get a bunch of saved-chart ids
2. Each dashboard tiles uses those ids to get the underlying query (metric, dimension, **filters**, sorts...)
3. The dashboard tile runs the query and renders the plot
----
4. The user adds a filter to the dashboard
5. Each tile figures out if the filter is relevant and if so adds it to filter list and resubmits it's query.

What do you think?

**Comment by ZeRego** [comment]
Sounds good 👍

**Comment by TuringLovesDeathMetal** [comment]
> I don't completely understand the V2 UX, I think the dashboard level filters should always be editable in view mode, since it's just a type of chart interaction. I thought the preset named "views" like "Americas" would behave like a separate option to the on-the-fly filters, which would always be available and editable.

Agreed with this, sort of. 

I think that you should be able to save a set of dashboard filters as the "default" when someone opens the dashboard. 

The way you'd add these `default` filters is how you've described @PriPatel - you have to go to `edit` mode, then select the filters, then save. 

If I'm viewing a dashboard that has a set of default filters, I can adjust them "on the fly" (e.g. if the default filter was `date is in the past 3 weeks`, I could change this to be `is in the past 5 weeks`). I can also add new filters, or remove the ones that are there. 

_**but**_ these filters aren't persisted. So if I changed a bunch of filters in my view, but then Priyanka goes and looks at the same dashboard, she would see the `default` filters. 

Does that make sense? 

Then for `views`. This would just be multiple sets of saved filters. For example, I could have the KPI dashboard and the default filter would be `date is in the past 3 weeks`.  Then, I'd have another view which was just for Lightdash Cloud users (so it would have the filters `is lightdash cloud` and `date is in the past 3 weeks`). 
^I'd have to select one of these as being the `default` (or have `no filters` as the default). Then when someone opened the KPI dashboard, they would see the dashboard filtered using the `default` filters. 

They could click and adjust things the same way as I described above - but again, unless they go into `edit` mode and save these changes, the wouldn't persist.

**Comment by TuringLovesDeathMetal** [comment]
^Note: if we have this behaviour where you can change saved filters on the fly, then fixing this bug will become really important (because it will break the user experience for sharing things: #549 )

**Comment by ZeRego** [comment]
Technical implementation proposal:
**The filters are only saved under a 'view', not in the dashboard itself** This means that in the first stage we would be saving the filters under a default view. ( Migration should create 'view' table and create a default view per each dashboard. On dashboard creation, create a matching row in 'view' table. )
In the second stage we allow for multiple views.
