### ISSUE TITLE
I want to be able to run a dashboard only when a filter is selected

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9264]
### Description

Right now, when you open a dashboard, everything automatically loads. 

This is fine, if your data isn't too big. But sometimes, I build a dashboard which is _**meant**_ to be filtered (e.g. in Lightdash, our Cloud Activity Tracker). 

If I have a really big dataset, then I actually don't want my dashboard to load until I've filtered my dashboard. 

There should be a way to set the dashboard to only run once a filter value has been selected. 

E.g. here, I would want to be able to set the dashboard to `load on filter` or something. Then pick the `date week` filter as "needing to have a value"

<img width="390" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/c33ffe39-540d-430f-a562-8d3c42973549">

**Comment by owlas** [comment]
@TuringLovesDeathMetal and @joaoviana is this something we should set on a filter-level in the filter config panel.

i.e. "this filter must have a value"

**Comment by joaoviana** [comment]
> @TuringLovesDeathMetal and @joaoviana is this something we should set on a filter-level in the filter config panel.
> 
> i.e. "this filter must have a value"

I was thinking this could be on a _global_ level, like on this example:
<img width="1003" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/46a757f3-c936-4363-abee-38b16086a4db">

Where you can select which filters would _block_ the dashboard if no filter is applied. 

I can, instead, follow your approach!

**Comment by hamzahc1** [comment]
When this merges - it should have a headway update @joaoviana  😄

**Comment by joaoviana** [comment]
> When this merges - it should have a headway update @joaoviana  😄 

And will also update docs @hamzahc1 !
