### ISSUE TITLE
Filter value stays there, even though an option has been selected

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9278]
if you choose an option in a filter after you’ve started writing on it the option will be chosen but the word will stay there and you have to manually delete it

![image](https://github.com/lightdash/lightdash/assets/31848148/570bec87-5e69-4215-821b-34e012b8d1c3)

**Comment by IrakliJani** [comment]
Note: This is a controversial UX decision. Clearing the string means it also "resets" results. The best UX practice could be to clear the string but keep the previous results. This might be significant work if Mantine makes it hard to implement.
