### ISSUE TITLE
Chart colors may not be consistently assigned from chart editor to dashboard

### ISSUE THREAD

**Issue by filp** [lightdash/lightdash#9297]
### Description

User reports indicate chart colors may not be predictable going from the chart editor to the dashboard in some situations.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C05F0N3UPSP/p1710235792414099?thread_ts=1710235792.414099&cid=C05F0N3UPSP

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1709820382461129?thread_ts=1709820382.461129&cid=C03MG2VTR08
