### ISSUE TITLE
People should be able to download embedded dashboards

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9300]
### Description

I want users to be able to download the dashboard as a PDF. 

This should be an option that I can toggle on/off when I'm setting up the embedded dashboard. 

### Documentation

- add this to the embedding reference docs

### Analytics events

- add an analytics event tracking exports from embeds

**Comment by Ifunanyacollins** [comment]
@TuringLovesDeathMetal  I'm interested in working on this can I pick this up?

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C069QQMERD2/p1709832763118609?thread_ts=1709832763.118609&cid=C069QQMERD2

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C069QQMERD2/p1710876058820849?thread_ts=1710876058.820849&cid=C069QQMERD2
