### ISSUE TITLE
In my embedded dashboard, I want some filters to be adjustable, but not others. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9302]
### Description

Right now, it's just `on` or `off` for filter interactivity. 
<img width="489" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/1de46d1b-1b4d-4fc0-b012-f1b59f132d0b">

Instead, we should replaced this and it should be: `Users can change` then there should be three options `no filters`, `some filters` or `all filters`

If you select `all filters`, then it has the same behaviour as today if you toggle this `on`. 

If you select `no filters`, then it has the same behaviour as today if you toggle this `off`. 

If you select `some filters`, then it would show you a list of the filters on the dashboard and you would be able to `check` which filters you want users to be able to change. 

<img width="903" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/f6b389d0-8896-404b-98f8-714c722e0448">

### Docs

- add docs to the embedding reference doc. Make sure to add screenshots showing what the different states actually look like in an embedded dashboard. 

### Analytics events

- add analytics event to embed created (?) I don't know if that's an event...but basically, add a new column which tells us if they have `all filters`, `no filters` or `some filters` selected in a place that makes sense :)

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C069QQMERD2/p1709832763118609?thread_ts=1709832763.118609&cid=C069QQMERD2
