### ISSUE TITLE
SQL Runner editor cursor misaligned from the current character

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9321]
### Description

Cursor is off the current character in the SQL Runner editor while using the `Safari` browser.

### To Reproduce

1. Open Lightdash on safari
2. Go to the SQL Runner
3. Select on of the tables on the side bar
4. Try to place the cursor in the last character of any line

https://github.com/lightdash/lightdash/assets/22939015/2c6c131f-423f-4377-9cf3-0772bfa731d6

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/D03T6HHCK7A/p1710178666798939

**Comment by IrakliJani** [comment]
sorry @almeidabbm im testing something. I'll remove these comments in a bit!

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C06P1777QR2/p1710179292087189?thread_ts=1710179292.087189&cid=C06P1777QR2

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C06P1777QR2/p1710179292087189?thread_ts=1710179292.087189&cid=C06P1777QR2

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C06P1777QR2/p1710179292087189?thread_ts=1710179292.087189&cid=C06P1777QR2

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/D03T6HHCK7A/p1710180654916879?thread_ts=1710180654.916879&cid=D03T6HHCK7A

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY

**Comment by IrakliJani** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C016QJZA6JY/p1710180267630849?thread_ts=1710180267.630849&cid=C016QJZA6JY
