### ISSUE TITLE
Error getting project validation 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#9327]
### Description

Some users don't have access to the project validation details. The frontend is requesting these details independently if the user has access to such feature.

We should check the user permission before making the request.

### To Reproduce

1. Login with a viewer. 
2. see network error

<img width="1055" alt="Screenshot 2024-03-11 at 18 10 46" src="https://github.com/lightdash/lightdash/assets/9117144/9c60d389-47a3-4f63-b47c-11df4ea614ed">

**Comment by wasifkareem** [comment]
Hi @ZeRego , is this issue already resolved?? I'm not able to reproduce it.
