### ISSUE TITLE
Percent table calculation is 0%

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9360]
### Description

When I create a table calculation for a percent value, it's result is 0%.

Slack thread: https://lightdash.slack.com/archives/C06HXEEJAA2/p1710342827292709

### To Reproduce

Haven't been able to reproduce the issue.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C06HXEEJAA2/p1710342827292709?thread_ts=1710342827.292709&cid=C06HXEEJAA2
