### ISSUE TITLE
Reference line of 1 sets the chart y axis minimum to 1. 

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#9368]
There's a strange bug when adding reference lines to charts. I've set a reference line value of 1 on the Y axis and then the minimum Y value then defaults to 1. However, when setting to anything above one it works as expected.

[See this](https://lightdash-community.slack.com/archives/C03MG2VTR08/p1710410143121219) for screenshots.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1710410143121219?thread_ts=1710410143.121219&cid=C03MG2VTR08
