### ISSUE TITLE
Improve documentation on who can create project previews

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9378]
**Link to existing docs:** [Roles & Permissions docs](https://docs.lightdash.com/references/roles)

- Add information about creating previews
- Display in the create project preview logs when a project's content wasn't copied over to the preview

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C06B2PP2478/p1710277691872089?thread_ts=1710277691.872089&cid=C06B2PP2478
