### ISSUE TITLE
Auto y-axis range of line charts does not adjust properly

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9379]
### Description

Auto y-axis range is clipping line chart lines

### To Reproduce

Haven't been able to reproduce

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C05F0N3UPSP/p1710345039666669?thread_ts=1710345039.666669&cid=C05F0N3UPSP
