### ISSUE TITLE
Preview projects should copy content the user has access to

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9386]
### Description

Currently `admin`, `developer`, `editor` and `interactive viewer` role users can create preview projects.
For security restrictions only `admin` user created preview projects get the content copied from the base project.
The other user role's preview projects do not get any of the content copied over.

As a `developer`, `editor` and `interactive viewer` I would like my preview projects to have the same content I have access to in the source project.

### What problem does this solve?

Roles other than `admin` do not have access to any content in preview projects.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C06B2PP2478/p1710277691872089?thread_ts=1710277691.872089&cid=C06B2PP2478
