### ISSUE TITLE
Cannot change chart type

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9393]
### Description

https://github.com/lightdash/lightdash/pull/9346 introduced a bug when trying to change chart type

### To Reproduce

How to reproduce:
1. Create chart
2. Try to change chart type from Bar to Horizontal bar / line

### App Version

0.1031.1

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1710519293929319?thread_ts=1710519293.929319&cid=C03MG2VTR08
