### ISSUE TITLE
CLI preview descriptions are incorrect

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9402]
### Description

- In the CLI help command, the `preview` command has the same description as the `compile` command
- Add consistency in descriptions: always start end with `s` or not. e.g. `compile` vs `compiles`

### To Reproduce

1. Run `lightdash help`

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1710681305794359?thread_ts=1710681305.794359&cid=C053ESBT36V
