### ISSUE TITLE
Implement the grouped dropdown in the 'Chart config' inputs and hide Table names from the fields.

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#9409]
- [ ] Don't show the table name in the inputs in chart config. This should affect all chart types
- [ ] Use table names as headings in the dropdowns instead. We use this pattern pretty much everywhere else!
![Image](https://github.com/lightdash/lightdash/assets/12776522/1ef01aa5-aef3-47d8-aa5e-d9a553593839)

---

**Problem**

From a user:
> We use descriptive table names. This causes the actual name of the field in the Y Axis view to not be visible, or be partially visible. You can still see it with the tool tip, but it's not easy. I might be missing a setting to turn off the table name when the chart contains a single table. I didn't see any open issues for this, but it's possible the wording I'm using to describe it is off.

> In our case, we don't join any models together at the lightdash level, so we don't have a case where we would have two models in a chart. As the metric name is the most important portion of the display, my suggestion would be to display as <metric name> - <model name>. Another option would be to just drop the model name all together unless more than one model is joined in.

There are many legitimate cases where users will have long table names and when configuring a chart, it makes sense to prioritise the name of the metric/dimension name since only the tooltip will end up showing that. We should switch the order of display as suggested above.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1710375221839609?thread_ts=1710375221.839609&cid=C03MG2VTR08
