### ISSUE TITLE
Support Grid and Waterfall chart types in Vega

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#9410]
As requested by a user.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C05B9N87JPR/p1710251122591829?thread_ts=1710251122.591829&cid=C05B9N87JPR

**Comment by thiagocroce** [comment]
+1

**Comment by TuringLovesDeathMetal** [comment]
closing this as a duplicate of https://github.com/lightdash/lightdash/issues/8876
