### ISSUE TITLE
Add chartKind field to `api/v1/projects/{projectUuid}/charts` endpoint

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9413]
### Description

- `/charts` and `/chart-summaries` should share the same information on chart kind/type

### App Version

v0.1035.0

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1710754301557109?thread_ts=1710754301.557109&cid=C053ESBT36V
