### ISSUE TITLE
Add value label to Reference Lines based on 'average'

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#9419]
From a user

> When you add a reference line, and use value = ‘average’ it creates an average line and labels it in the chart ‘average’ - as per my image above. It would be great if that label was the actual value -“average=7.8%”

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C049LQZGVD3/p1710756234195909?thread_ts=1710756234.195909&cid=C049LQZGVD3

**Comment by hamzahc1** [comment]
@magnew - another one that could do with a headway update when it merges 😄
