### ISSUE TITLE
string type fields from clickhouse (through trino connector) return a base64 encoded string

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#9424]
### Description

there seems to be an issue with trino connector + clickhouse warehouse
instead of actual string values it returns base64 encoded values
numbers and timestamps seem to be ok.

![image](https://github.com/lightdash/lightdash/assets/962095/62e5cedc-6057-47cb-ae6a-4cb81abf209f)

### To Reproduce

...

### App Version

`v0.1035.0`

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1710763827302669?thread_ts=1710763827.302669&cid=C03MG2VTR08

**Comment by Grisgruis** [comment]
> Related stackoverflow: https://stackoverflow.com/questions/73699398/superset-trino-clickhouse-showing-data-wrongly-encoded

adding `clickhouse.map-string-as-varchar=true` to the clickhouse catalog in trino fixed the issue, was not looking trino docs due to datagrip showing correct values -_-.

Fixed, can be closed

**Comment by IrakliJani** [comment]
thanks everyone! closing ✅
