### ISSUE TITLE
CLI profiles.yml should also accept `schema` instead of `dataset` for bigquery

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9427]
### Description

From the DBT [docs](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#oauth-via-gcloud), a `bigquery` profile should be allowed to have `schema` defined instead of `dataset`.

Currently we are enforcing the `dataset` field.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C047XUL7QAZ/p1710763679226799?thread_ts=1710763679.226799&cid=C047XUL7QAZ
