### ISSUE TITLE
431 when explore URL is too big

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9431]
### Description

Related issue: #4137 

Whenever I copy an explore URL to store it for later usage, if the URL is too big it will result in a 431 HTTP error

![image](https://github.com/lightdash/lightdash/assets/22939015/e0d71401-df8b-4a64-b2cf-cf51a2af49ee)

### To Reproduce

1. Click `Run query from tables`
2. Click Payments table - from seed data
3. Add the following fields and filters:
![image](https://github.com/lightdash/lightdash/assets/22939015/a616e2cd-349a-4c22-b89a-053e8c5572ea)
4. Click `Run query`
5. Copy the URL and paste on a separate tab

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C05Q96U8FHN/p1710494236558959?thread_ts=1710494236.558959&cid=C05Q96U8FHN

**Comment by ZeRego** [comment]
Closing this to have all the long URL issues under the same ticket https://github.com/lightdash/lightdash/issues/4137

**Comment by ZeRego** [comment]
Closing this to have all the long URL issues under the same ticket https://github.com/lightdash/lightdash/issues/4137
