### ISSUE TITLE
Move CTAs in 'view mode' of a chart

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#9435]
<img width="1440" alt="Screenshot 2024-03-18 at 17 24 18" src="https://github.com/lightdash/lightdash/assets/12776522/cf5ee66a-d313-40d5-a8db-018b0057f9c9">

- [ ] Move the Explore from here and Link button to the header along with the other buttons there
- [ ] Order should be` Explore from here` , `Edit chart` , `link` , `3 dots`

This will get rid of the empty space and give more vertical height to the chart

**Comment by joaoviana** [comment]
Just view mode for now @PriPatel ?
