### ISSUE TITLE
fix pivot tables to fit on screen

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#9448]
### Description

Users are asking for a way to see all table data on dashboards or in explore without needing to horizontally scroll the table. They want tables to adjust to screen size automatically so everything is visible at once. We need to work on making table columns more responsive or introducing text wrapping to improve visibility on various screen sizes...

example of a pivot table:

![CleanShot 2024-03-19 at 17 50 45](https://github.com/lightdash/lightdash/assets/962095/7d6e6063-7b5c-453c-b7f4-0a66997473f2)

As you can see from the screenshot, the horizontal space within the data cells is just too big compared to the actual data point width, making it sensible for the column headers to wrap. This adjustment will result in a better grid layout for the retention table.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1710795537921729?thread_ts=1710795537.921729&cid=C03MG2VTR08
