### ISSUE TITLE
Initialize snowflake client with logging configuration

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#9449]
### Description

After the upgrade to v1.10.0 `snowflake-sdk` started logging some messages about trying to initialize their logger.

![image](https://github.com/lightdash/lightdash/assets/22939015/aaafffe4-0aaa-44be-94ef-17fe54504f26)

The code for these messages can be seen here: https://github.com/snowflakedb/snowflake-connector-nodejs/blob/eac53c9199ec66a7f4745f3be6db613e723d4aa4/lib/logger/easy_logging_starter.js#L26-L29

#### To reproduce:
1. Add a snowflake profile to profiles.yml
2. Run `lightdash compile` command

### What problem does this solve?

`snowflake-sdk` logging messages about trying to initialize their logger and not having logging config

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1710853376823589?thread_ts=1710853376.823589&cid=C053ESBT36V

**Comment by hamzahc1** [comment]
@almeidabbm is there any updates on this ticket? Do we still want to work on it?

**Comment by almeidabbm** [comment]
> @almeidabbm is there any updates on this ticket? Do we still want to work on it?

Seems like there haven't been any other reports, but also it shouldn't impact the functionality of the CLI, it's mostly for it not to show the logs in the screenshot
Don't think it should take very long to fix, will give it a try today 👌
