### ISSUE TITLE
Make the Run Query button look like its a button group

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#9476]
<img width="194" alt="Screenshot 2024-03-21 at 09 06 51" src="https://github.com/lightdash/lightdash/assets/12776522/6a229a86-ba96-4290-9e39-0903256771bb">

Right now, it just looks like there is an icon on either side of the button. Show a clear divider.

**Comment by calculuslmvt** [comment]
Hi,
I want to attempt this.
