### ISSUE TITLE
If a user gets an undefined error, we should prompt them to open an issue

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#948]
If a user gets an error that we don't know about/have an error type for, we should prompt them to open a new issue.

**Comment by owlas** [comment]
@TuringLovesDeathMetal would you like to use the chat widget for this or link directly to GitHub? We could offer both options when the error happens.

**Comment by TuringLovesDeathMetal** [comment]
I think it could be cool to have both. 

like, if you get an undefined error, then the chat widget pops up and says something like "Looks like you've found an error we've never seen before! You can either: fill out a bug report in GitHub (link to bug report), chat to someone from the team."
