### ISSUE TITLE
There should be an option to export results from a dashboard as .csv (not just image)

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9482]
### Description

Right now, there's no way to export the results from a dashboard as .csv files. Instead, I need to set up a scheduled delivery for this and `send now`. 

This should be an option when I hit `export dashboard`

When I open `export dashboard` there should be an option to switch betwen `csv` or `image` and the modal should update with the correct configurations (just like in the scheduled deliveries) 

<img width="375" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/363cbc04-895d-43f6-95ba-f7a10b6e636e">

### Analytics event

we should update the export dashboard event to include the file type of the export.

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1711101285332779

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1711101285332779?thread_ts=1711101285.332779&cid=C053ESBT36V

**Comment by rephus** [comment]
@TuringLovesDeathMetal  What does exporting a CSV mean on a dashboard ? is it just a `zip` with the results of all charts ?

**Comment by TuringLovesDeathMetal** [comment]
^Sorry, I really didn't make that clear. Yes, that's exactly it. 

Let's make this even more limited as well and say that there's only the option to `export the results in table` to .csv files. 

So you'd click `csv` and then there would be some copy saying `export results in table for all charts` (maybe it would be on hover over an `export` button?)

<img width="166" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/40d79962-6e39-4875-81e2-f2d1a2e68713">


There's no option to set the custom limit/all results/etc. at the start!
