### ISSUE TITLE
All of the quick calculations should work with `count` and `count distinct` metric types

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9498]
### Description

Right now, the `quick calculations` are only working with `sum`, `average` (and maybe some other?) metric types, but only `rank in column` is working for `count` and `count distinct` metric types. 

These metric types should support all of the other quick calculations as well (since they are numebrs).

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1711101285332779

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C053ESBT36V/p1711101285332779?thread_ts=1711101285.332779&cid=C053ESBT36V

**Comment by rephus** [comment]
Fixed by https://github.com/lightdash/lightdash/pull/9489
