### ISSUE TITLE
UI layout issues with Big Number comparison label

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#9506]
### Description

- There is a UI issue with the alignment of the percentage text, arrow icon, and label. ![CleanShot 2024-03-22 at 18 31 39@2x](https://github.com/lightdash/lightdash/assets/962095/9d765032-e735-4fe8-8e03-8cd7551ae856)
- Another UI issue arises with small tiles, where the comparison number gets cut off. ![image](https://github.com/lightdash/lightdash/assets/962095/d3303f42-af6f-4e44-abb6-f6e0263e0bc2)

### To Reproduce

- create bignumber chart
- add comparison and add comparison label
- add bignumber tile to the dashboard
- make tile height very small

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1711115212326209?thread_ts=1711115212.326209&cid=C03MG2VTR08
