### ISSUE TITLE
Change chart config category tabs to accordions

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#9520]
https://www.figma.com/file/rlqMIJ4pm3t8aAsiMd3CZJ/Lightdash-Product-New?type=design&node-id=4-79&mode=design&t=eU5N86sswwOTdcLA-0

- [ ] Show chart types up top as icons
- [ ] Change category types tabs to accordions

**Comment by joaoviana** [comment]
Will be done all in one: https://github.com/lightdash/lightdash/issues/9569
