### ISSUE TITLE
Quick running total calculation does not recognise order by dimension identifier

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#9526]
### Description

When using the "Running total" quick calculation in the explorer, the dimension specified in the `ORDER BY` within the window function is compiled without quote marks (the `${}` wrapper is also missing in the table calc editor for the auto-generated metric), so the query does not run

I'm not sure if this issue is specific to Snowflake.

I also ran into an issue (which is at least partly user error), where the ORDER BY part of the window function is missing if you don't explicitly order the query by a dimension. This is probably expected behaviour, but it might be worth making it clearer in the UI that certain quick calculations won't work unless you order by a dimension (or even auto-select a dimension for the ORDER BY, once such a quick calc has been created, if there is no existing ordering).

### To Reproduce

Steps & screenshot/gif/loom to reproduce the behavior
1. Select a timestamp dimension
2. Order the query by that dimension
3. Select at least one metric
4. Use the "quick calculations" on the metric to create a "Running total"
5. See error below
![image](https://github.com/lightdash/lightdash/assets/135957659/94c5eecf-273c-47fb-a2b7-ff6ed8de0239)

### App Version

v0.1042.2

**Comment by TuringLovesDeathMetal** [comment]
@mhawkins-runa sorry for getting back to this so late!

I _**believe**_ that we shipped a fix for this last week. But just wanted to double check - are you still running into this issue?

**Comment by mhawkins-runa** [comment]
@TuringLovesDeathMetal yes this issue seems to be fixed now - thanks!
