### ISSUE TITLE
`YEAR NUM` date interval has a comma in the number - this shouldn't be there. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9536]
### Description

Right now, if I use `YEAR NUM` as a time interval for my dimension, then there is a comma in the year, like `2,024`. 

This shouldn't appear with a comma. Can we format values that are `year num` date intervals?

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C06AUF70BTR/p1711532035234339

**Comment by joaoviana** [comment]
Related to: https://github.com/lightdash/lightdash/issues/4707
