### ISSUE TITLE
Interactive viewer doesn't have "explore from here" button in chart page

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#9549]
### Description

There should be a "explore from here" button in the chart header for interactive viewers.

<img width="1573" alt="Screenshot 2024-03-27 at 15 08 25" src="https://github.com/lightdash/lightdash/assets/9117144/d8ecf19c-b22a-4787-891b-3da2cf6930b3">

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C04KD95TF0U/p1711474758273419?thread_ts=1711474758.273419&cid=C04KD95TF0U
