### ISSUE TITLE
As a space admin I can't remove other space admins

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#9553]
### Description

As a space admin I can't remove other space admins.

All admins show a full access badge. 

<img width="617" alt="Screenshot 2024-03-27 at 15 26 34" src="https://github.com/lightdash/lightdash/assets/9117144/f068bc91-869d-43bf-84b5-1d19083cc732">

**Comment by TuringLovesDeathMetal** [comment]
I don't think you should be allowed to demote admins (I think admins should always have full access to a space and there's no way to remove this)
