### ISSUE TITLE
It should be more clear that if I'm the user who created a space, I'm added to `user access` 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9560]
### Description

When you create a space, you're now added to the `user access` list as `full access`. 

Two things:

1. If I created a space, is there any way to remove me from that space? (i.e. can another space admin remove me?)
2. It's not clear that I'm in the `user access` list because I created the space. Maybe we can add something like `Katie Hindson (created space)` or on hover it tells you that the user created teh space?

<img width="644" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/4b431771-d519-41a8-b731-5dc2d2362e56">

**Comment by ZeRego** [comment]
> If I created a space, is there any way to remove me from that space? (i.e. can another space admin remove me?)

Yes, this is possible. Any user with Full Access can remove other users with Full access except org/project admins.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as not planned. We can always reopen it if someone else complains about it/when we revamp some of this eventually...
