### ISSUE TITLE
Search for columns when building a query from tables

### ISSUE THREAD

**Issue by bobadams1** [lightdash/lightdash#9563]
### Description

Include column names in search results when building a new visualization from tables.  

Stretch: include column descriptions in search results in addition to column names

### What problem does this solve?

For organizations with a high count of columns in reportable data models, this would enable faster report creation without the need for end users to memorize which model a specific column is stored in.

**Comment by PriPatel** [comment]
Thanks for the feature request @bobadams1!
When you say ' search' do you mean the global search bar, or do you mean the area shown here in the screenshot? Thanks!
<img width="357" alt="Screenshot 2024-03-29 at 13 58 27" src="https://github.com/lightdash/lightdash/assets/12776522/22dd1c94-5d31-4c0c-b457-13702b10a3b1">

**Comment by bobadams1** [comment]
It would be the latter, @PriPatel.  This would enable users to search for fields within tables to speed up their visualization construction process.  Thanks!

**Comment by PriPatel** [comment]
Closing in favour of this milestone which covers the problem!
https://github.com/lightdash/lightdash/milestone/148
