### ISSUE TITLE
The Explores page should make it really obvious how to ask a question + what questions someone can ask

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#957]
### **Description: What is it?**

*This should be short and sweet 🍬*
*How would you explain this feature in two lines to someone else at Lightdash?*

When you land on the `Explores` page in Lightdash, it should be really obvious how to ask a question + what types of questions people can ask.

---

### **Problem: What problem does this solve?**

*Describe the problem that this feature requests solves (or potential opportunity we're looking at).*
*Add a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

Right now, when you land on the Explores page, if you've never used Looker, it's really unclear how to ask a question + what types of questions you can ask. 

 Landing on a list of tables doesn't feel like an intuitive way to ask a question. How does a list of tables let me ask a question?

---

### **(Optional) Why: How do we know this is a real problem and worth solving?**

*Why are we solving this?*
*If you're a Lightdash user suggesting a feature, you can skip this!* 
*Otherwise, add any links to customer conversations or research.*

The mission for Lightdash is to "enable everyone to answer their data questions." That means that the first time you land in Lightdash, it should be _**really**_ obvious how to ask + answer a question. 

We've gotten feedback from users that "unless you've used Looker, it's really not obvious how to build things in Lightdash." 

---

### **Success: How will we know if we’ve solved this problem?**

*Add how we will determine whether the problem has being solved. Qualitative and
quantitative measures.*

People are exploring the data once they come in. 

Quantitative:
The time between compiling Lightdash and running your first query should be short. 
Also, higher retention of users (especially those who have never used Looker). 

Qualitative:
You come into Lightdash, and you just know how to answer a question.
It should be really obvious how to "get to an answer" in Lightdash from scratch (i.e. not from saved content). 

---

### **Audience: Who are we building this for?**

*Add example user descriptions that would benefit from this solution (e.g. users who are onboarding, data consumers, data builders). It's unlikely that a solution is for everyone* 🙂

Users who are onboarding. 
It's more likely that this will be used by data builders than data consumers (since these are the people most likely to be asking "questions from scratch").

---

### **What: Roughly, what does this look like in the product?**

*Don't actually design a solution here. Try to use words or simple sketched pictures. Talk more about how this would interact with other parts of the product than how it should look.*

Three things:
1. The empty space when you land in Explores should make it clear _**how**_ to ask questions from this space.
2. When you land in Explores it should be clear _**what**_ types of questions you can ask
3. We make you set up your project so that when people are in the Explore page, it's easy to know which table to use to ask their question (e.g. we push you to add table descriptions because these are added to the Explore page)

---

### **(Optional) How: What is the experiment/release plan?**

*Once high level product design is figured out, add the release plan below and include what is in scope + out of scope.* 

...

---

### Notes on this template:

- Do not add the solution here. This proposal is meant to ***inform*** the solution.
- A proposal should fit on a printed A4 page. If it doesn't, you might want to keep working on it until you have a clearer view of the problem 🙂
- Use plain English. Try to avoid acronyms or technical words. Describe the problem like you would in a conversation with someone in the team.

**Comment by PriPatel** [comment]
### Design spec
Based on feedback from first-time users, I think we need to add some new `Results` card states depending on which fields the user has selected. 

<br />

State + link to design | Notes | Information icon link
-- | -- | --
[No table selected ](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=553%3A29716&scaling=scale-down-width&page-id=553%3A29715)| New empty state with image. | https://docs.lightdash.com/get-started/exploring-data/using-explores/
[Table selected - no fields selected](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=555%3A30609&scaling=scale-down-width&page-id=553%3A29715) | New state with explainer text and possibly some sort of CSS animations with rotating words and where the metrics/dimensions are colour coded?! | https://docs.lightdash.com/get-started/setup-lightdash/add-metrics
[Metric selected](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=559%3A31360&scaling=scale-down-width&page-id=553%3A29715) | New state only when metric is selected to push user to select a dimension and show the relationship | https://docs.lightdash.com/get-started/exploring-data/using-explores
[Dimension selected](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=564%3A31907&scaling=scale-down-width&page-id=553%3A29715) | New state only when dimension is selected to push user to select a metric and show the relationship | https://docs.lightdash.com/get-started/exploring-data/using-explores
[Metric + dimension selected](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=564%3A32170&scaling=scale-down-width&page-id=553%3A29715) | Text updated to push user to run query. | https://docs.lightdash.com/get-started/exploring-data/using-explores

### Notes
- [Link to figma file](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=553%3A29715)

- If it is possible to show the [rotating questions ](https://codepen.io/amritleone/pen/qERPmW) in a subtle way (TBD), here they are! : 
```
How many total signups per day ?
What is the total order count by location?
How many new followers every week?
What is the total order count split by status?
```
- I will provide svg assets separately.
