### ISSUE TITLE
Fields with timestamp type do not produce automatic time intervals

### ISSUE THREAD

**Issue by 12ian34** [lightdash/lightdash#9571]
A user was trying to have time intervals generated automatically for a date dimension.
Their date dimension was of type: `timestamp`.
As per [the docs](https://docs.lightdash.com/references/dimensions/#dimension-configuration), the default behaviour for both types `date` and `timestamp` appears to suggest that time intervals are created automatically.
However, this appears not to be working for `timestamp` types. 
The user worked around the problem by specifying `time_intervals` manually.

The fix is suggested to make the `time_interval` default to `default` for `timestamp` types.

**Comment by annebelleo** [comment]
small correction: this worked for type `timestamp`, but not for type `timestamptz`

**Comment by hamzahc1** [comment]
Time intervals work for timestamps - Lightdash doesn't have `timestamptz` types and it looks like the issue was resolved by specifying the type in Lightdash so closing this for now.
