### ISSUE TITLE
Scheduled delivery images are very low quality in Slack 

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#9582]
### Description

Scheduled delivery images are very low quality in Slack. Looking around the internet this seems to be a pretty consistent complaint people have with the Slack API. We don't directly control the image quality in Slack and the down-ressing happens on their end. BUT, there are some suggestions out there about things to try to get slack to deliver higher quality images to mobile.

**Comment by hamzahc1** [comment]
@magnew is there a specific user who has complained about this?

**Comment by magnew** [comment]
> @magnew is there a specific user who has complained about this?

Yup. They were on intercom. I verified we can repro this, but I think it's mostly a slack issue. The user said that today it seems to be fixed. 

So, we can probably close this.
