### ISSUE TITLE
Reference lines can break the axis range

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#9611]
### Description

Setting a reference line below or above the series minimum can make the axis range incorrect. It's not every time and requires some investigation.

**Comment by magnew** [comment]
There is a race condition in eCharts here. Reloading usually fixes it. I'm trying to find a good answer.

**Comment by TuringLovesDeathMetal** [comment]
i'm going to close this as not planned - hasn't been requested by any users/reported since it was opened
