### ISSUE TITLE
Remove the 'table' icon from every item in the Table list

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#9628]
<img width="391" alt="Screenshot 2024-04-03 at 16 00 35" src="https://github.com/lightdash/lightdash/assets/12776522/88be7854-b430-4c8c-bfde-307d7577a86e">

- [ ] If every item in this list is a table, there is no need to repeat the table icon every time. This adds more real estate for longer table names.
- [ ] Instead, Add a table icon in front of the Sidebar Title. This will help with continuity when moving over to the metrics/dims sidebar and seeing a table breadcrumb.

**Comment by Shravan773** [comment]
Can you assign me the task,i think i can fix the issue.

**Comment by Shravan773** [comment]
Working on it...
