### ISSUE TITLE
Results are showing as empty in the `results` panel, but they are not empty

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9637]
### Description

- run a query in the explore view
- see the results panel has some empty results, but not others
- open the query from the `sql` panel in the SQL runner
- the _**same query**_ returns non-empty results. 

See more details in Slack here: https://lightdash.slack.com/archives/C06J189BQCR/p1712176954450379?thread_ts=1712175831.948079&cid=C06J189BQCR

**Comment by rephus** [comment]
Solved, the SQL was using uppercased column names, one way to fix this is to change the names on the SQL. Affected warehouse: redshift. More details in the thread.
