### ISSUE TITLE
Link SSO to user if they have the same email

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#9643]
### Description

We should allow login using the same email with password and google sso . 

Thread: https://lightdash.slack.com/archives/C06AUF70BTR/p1712140945983809?thread_ts=1711129621.806779&cid=C06AUF70BTR

### To Reproduce

I think the steps to replicate are: 

- create an admin user (in this case it was the first user and perhaps only admin) 
- whitelist your `domain`  to automatically allow people to join (I think this might be important, and the reason why we were not able to replicate it before) 
- login with google SSO 
- You get  an `email already in use` error 
![image](https://github.com/lightdash/lightdash/assets/1983672/42383178-18d2-4ac9-a687-2ff973f02c17)

**Comment by ZeRego** [comment]
**Workaround:**
If you haven't previously connected your Gmail account you need to authenticate with email and password. Once you log in, you can connect your Gmail account under user settings.

**Comment by ZeRego** [comment]
Updated this bug to be a feature request. 

We already support, enabled via env var, linking SSO if user has another SSO with the same email. 
We should support, enabled via env var, linking SSO if user has the same email.
