### ISSUE TITLE
Improve dashboard responsiveness on mobile view

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#9655]
### Description

On mobile view, grid elements may be positioned awkwardly within the constraints of the responsive dashboard.

![Image](https://github.com/lightdash/lightdash/assets/382538/e363638e-a867-48d4-b8f6-579b2d7461be)

Grid elements should be more aggressively positioned on a simple vertical stack.

**Comment by hamzahc1** [comment]
Let me know if you make headway with this @filp
