### ISSUE TITLE
4. Each dashboard tab should possess a unique URL.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#9658]
We should have url paths specific to each tab. 

URL example
```
https://app.lightdash.cloud/projects/{uuid}/dashboards/{uuid}/view/tab/{uuid}
```

If tab uuid is not provided it should default to 
```
https://app.lightdash.cloud/projects/{uuid}/dashboards/{uuid}/view
```

**Comment by amitkharb** [comment]
Hi @PriPatel, @ZeRego , 

What are the requirements here for copying the link ( or share) of a tab of a dashboard. 

Currently we have this link to click to copy the link of dashboard and share with others. 

Do we want something similar if a user wants to share the link to a specific tab.

**Comment by ZeRego** [comment]
@amitkharb the copy url functionality doesn't need to be changed. The share URL button will copy the current URL.
For this ticket we need to:
- update the react router to support the new optional path/param 
- on page load, if tab param is available, open correct tab
- on view mode, update URL when user clicks a tab

It should be backwards compatible. We need to keep support for the route without the tab param.
