### ISSUE TITLE
3. I should have more control over filtering single tiles / single tabs / the whole dashboard

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#9659]
<img width="564" alt="Screenshot 2024-04-16 at 11 18 34" src="https://github.com/lightdash/lightdash/assets/12776522/d70690c3-6190-418d-a7bf-b0944e81c8b8">

- [ ] In the chart tiles section, **if a dashboard has tabs**, split the tiles up by tabs
- [ ] Each tab is an accordion that I can open and close
- [ ] I can use the checkboxes to deselect/select tiles in full tabs
- [ ] **Do not make any changes to the default behaviour of how the tiles are selected**
- [ ] When I click on the tiles section, by default, the tab accordion for the tab that I am currently on should be open. All the other tab accordions should be closed.

**Comment by rephus** [comment]
@amitkharb
