### ISSUE TITLE
Add tree-planting for GitHub stars to Readme 🌱 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#966]
### Which docs do you want to update?
*Add a link to the docs page you want to update.  If the doc doesn't exist yet, add the suggested title of the new doc here*
https://github.com/lightdash/lightdash/blob/main/README.md

### What needs updating?
*Describe what's wrong with the current docs. Or, summarize the improvements you want to make*

Add info about how we'll plant trees for folks who star the repo

**Comment by owlas** [comment]
Could somebody assign themselves to find a project for us to support

**Comment by TuringLovesDeathMetal** [comment]
Also add this to the github discussions intro
