### ISSUE TITLE
Metrics should appear to the right of dimensions in the results table by default

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#968]
### **Description: What is it?**

*This should be short and sweet 🍬*
*How would you explain this feature in two lines to someone else at Lightdash?*

Metrics should appear to the right of dimensions by default in the results table

### **Problem: What problem does this solve?**

*Describe the problem that this feature requests solves (or potential opportunity we're looking at).*
*Add a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

I'm always frustrated when the metric appears to the left of the dimension. It's not an intuitive way to read aggregated data and I always end up moving my metric to the right. 

### **(Optional) Why: How do we know this is a real problem and worth solving?**

*Why are we solving this?*
*If you're a Lightdash user suggesting a feature, you can skip this!* 
*Otherwise, add any links to customer conversations or research.*

We've had some other users complain about this. Also, I just find it a bit annoying when I use Lightdash :) 

### **Success: How will we know if we’ve solved this problem?**

*Add how we will determine whether the problem has being solved. Qualitative and
quantitative measures.*

Metrics always appear on the right side of dimensions in a results table by default

### **What: Roughly, what does this look like in the product?**

*Don't actually design a solution here. Try to use words or simple sketched pictures. Talk more about how this would interact with other parts of the product than how it should look.*

Metrics appear to the right of dimensions in the results table by default. 

- [ ] If I add a dimension in, it automatically gets added to the right of the rightmost dimension. 
- [ ] If there are no dimensions, and I add a dimension in, it automatically gets added to the left of the metrics + table calculations
- [ ] If I add a metric in, it automatically gets added to the furthest right column in the results table 
- [ ] I can still move my metrics to be left/right of dimensions, but if I add a new metric in, it gets put on the far-right of my results table. 

**Expected behaviour:**
| Results table | change | New results table |
|--------------|---------|------------------|
| dimension 1, dimension 2, metric 1, metric 2 | added metric 3 | dimension 1, dimension 2, metric 1, metric 2, metric 3|
| dimension 1, dimension 2, metric 1, metric 2 | added dimension 3 | dimension 1, dimension 2, dimension 3, metric 1, metric 2|
| dimension 1, dimension 2, metric 1, dimension 3, metric 2 | added metric 3 | dimension 1, dimension 2, metric 1, dimension 3, metric 2, metric 3|
| dimension 1, dimension 2, metric 1, dimension 3, metric 2 | added dimension 4 | dimension 1, dimension 2, metric 1, dimension 3, dimension 4, metric 2|
| metric 1, metric 2 | added dimension 1 | dimension 1, metric 1, metric 2|

**Comment by ZeRego** [comment]
Since users can drag and drop the table columns we can have difference scenarios:
- dimension 1, dimension 2, metric 1, metric 2
- metric 1, metric 2,  dimension 1, dimension 2
- dimension 1, metric 1, dimension 2, metric 2
- etc,

So when a user adds a new dimension we should always add to the first position and when they add a metric we should add it to the last position ? 

new dimension, ... existing columns ... , new metric

**Comment by owlas** [comment]
@ZeRego I'm thinking:
* new dimensions appear to the right of the rightmost dimension
* new metrics appear as the far right column

**Comment by TuringLovesDeathMetal** [comment]
^ I like @owlas 's idea

**Comment by JohnRomanski** [comment]
@ZeRego why would users put metrics in a position before dimensions? Dimensions are what determines the metrics. The metrics are the answers to the questions posed by dimensions. This could be confusing to users and have complicating implications downstream.
