### ISSUE TITLE
Date filters (and results) based on fields with timezone information should use local timezone information on selection (like timestamp filters)

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#9694]
### Description

Right now, if I use a date filter (or date field?) based on a field with timezone information, the date filter will always use UTC. 

E.g. `timestamp (Day)` or `timestamp (Week)`  - these "date" time intervals will use UTC.
<img width="845" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/c4df2bb9-3f05-4bff-bf35-08146826b5f5">

This is confusing to users and similar to the issues we had with timestamp filters since it's showing "incorrect data" based on their local timezone. E.g. `in the last completed day` if I'm in EST updates to include data from _**today**_ at 8PM EST (since this is midnight UTC). 

I think this should change so that:

- If I have a date/week/month filter built from a field with timezone information (e.g. `timestamp - day`, then the filter input should be based on my "local timezone" (as set in the project config), by default.

**How can we do this?**

Potentially we could set the server to using the local timezone?

The query could be executed in UTC - so, the input should be converted to UTC **(???? does this need to be executed in UTC? Or can we just set our server to be in PST and leave the converting to the data warehouse?)** In BigQuery, it looks like `CURRENT_DATE()` is executed by default in UTC so even if we set the server to be in PST, it wouldn't "know" to convert it. [But you can provide it with a timezone](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#current_date:~:text=The%20following%20queries%20produce%20the%20current%20date%20in%20a%20specified%20time%20zone%3A) - maybe we can look into this for relative date filters 👀 

### Here's an example:

It's May 1st, 2024

I'm in PST,  and I add a filter "timestamp (day) is in the last 1 day"

The filter should be "looking at" data from `2024-05-01 PST` 

So, the query should be querying data from `2024-05-01 08:00:00 UTC` to `2024-05-02 08:00:00 UTC`

## Acceptance Criteria

- [ ] fields that are built from a timestamp are also converted to the project timezone (before being truncated/extracted to the date grain like `day`, or `week`)
- [ ] This affects fields used in the results table, and fields used as filters. 
- [ ] This affects explicit date filters as well as relative date filters (e.g. `date = 2024-05-31` AND `date in the last 1 complete day`)
- [ ] **Something to play around with:** right now, we add the timezone information to a timestamp filter, beside the timestamp filter. Do we want to also do that to the dates? (it feels like it'll be really crowded/a bit much). Can we think of a better way of displaying this information to the user? (e.g. somewhere so it's obvious that it applies to _**all**_ of the date filters/fields in your query)

<img width="1075" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/fe347172-a8a0-40a8-b6f6-23d716eab540">

**Comment by TuringLovesDeathMetal** [comment]
**Note:** I'm not actually sure that we want to do this....this can get really complicated really quickly. It might be that if you want timezone information, you'll need to use a timestamp field in your filter, then we can filter to the last 24 hours, for example (and consider time zone information).

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned. Instead, I think that there should bea project-level timezone set and we should work backwards from that based on user feedback (i.e. this is too complicated to start with 😅 but we might do it later). 

https://github.com/lightdash/lightdash/issues/5921
