### ISSUE TITLE
Nested filters crop input modals like date pickers

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#9698]
### Description

[Screencast from 10-04-24 00:30:43.webm](https://github.com/lightdash/lightdash/assets/1983672/624e9558-5a89-4d0a-b7ab-f06f49850ec9)

**Comment by joaoviana** [comment]
Believe this has been fixed because I can't reproduce.

Closing this

https://github.com/user-attachments/assets/c8ae5156-3beb-42ad-92a5-11e64808a86c
