### ISSUE TITLE
Hide potentially dangerous metrics

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#97]
When joined tables aren't 1:1, metrics can go wrong for users in the frontend (e.g. https://looker.com/blog/aggregate-functions-gone-bad-and-the-joins-who-made-them-that-way)

One solution we've discussed is only allowing star schema type joins. I think this is an interesting solution, which sticks with the principal of moving work to dbt where possible!

**Comment by TuringLovesDeathMetal** [comment]
We need to build this. 

One way we could do this is:
- forcing you to specify join type (are you defining a 1:1 join? or many to one? Or one to many?)
- "hiding" the dangerous metrics from your join (similar to how we do it if there's an error in dbt compiling your tables - we'd have this for your metrics)
- ^would we even want to just have these dangerous metrics removed? 
- we could also include this in the linter?

**Comment by TuringLovesDeathMetal** [comment]
duplicate of #961
