### ISSUE TITLE
`tried to reference dimension with unknown field id: field` error occurring from dashboard filters

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9759]
### Description

After implementing the change to how filters work on dashboards we've noticed that one of our dashboards had charts that stopped working due to the error "Tried to reference dimension with unknown field id: field".

- we added a dashboard filter 
- The charts that are affected don't have the dashboard filters applied to them 
- You're not able to click `explore from here` on the chart (there's no option to do so)
- if you click `edit chart` then, the chart loads with no issues. 

This is likely caused by the changes we made to dashboard filters overriding chart filters.

### Steps to Reproduce the Bug or Issue

See more information with videos in the Slack thread here: https://lightdash.slack.com/archives/C05F0N3UPSP/p1713187862261879

### version

v0.1067.2

### Cloud or self-hosting

cloud

**Comment by rephus** [comment]
I managed to replicate this issue, but it took me some time, so I'm not sure if this is the same issue.

How to replicate:
- Have a chart with a date
- Add filter (eg: date year)
- on the chart tile  menu, select a chart, and map the date to a field you're going to remove (second image) (eg: date week)
you can now disable the tile, the field will still be selected.
- On dbt schema, remove week time interval in the field you selected from the chart tile
- Refresh dbt
- Now you get the error


Workaround to fix it:
- Go to the dashboard filter (maybe both)
- enable on chart tiles the chart with errors
- select a new field that exists
- disable chart again
- save and reload

[Screencast from 16-04-24 16:13:34.webm](https://github.com/lightdash/lightdash/assets/1983672/71d9457d-8599-4aaa-9228-18c1b3bd174a)

**Comment by rephus** [comment]
AFAIK This is because the filter is sent to the backend, even if the tile is disabled (this could be a bug). 

The backend has no context of tiles, so it applies the filter, failing to get the dimension in the process.
