### ISSUE TITLE
The 'back' button in 'Explores' takes me to the wrong page

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#979]
**Describe the bug**
When I have navigate to an 'Explore' page via `Saved charts` and then hit the 'back' button, I am taken to the homepage. 
Similarly, when I navigate to an 'explore' page via a `Dashboard`, the back button takes me to the homepage. 

**To Reproduce**
1. Go to `Saved charts`
2. Click on a chart
3. Hit the back button in our app (NOT the browser button) 

**Expected behavior**
The button should take you back to `Saved charts`
It should behave like the browser 'back' button. 

**Screenshots or Loom video**
![Screenshot 2021-12-10 at 16 25 59](https://user-images.githubusercontent.com/12776522/145608204-a894d7cb-451a-4c76-aa41-423739970905.png)

**Comment by hamzahc1** [comment]
@PriPatel - I'm guessing this button will stop existing in the new designs for Explore page? I always expect this button to minimise the sidebar then it just takes me back to somewhere else

**Comment by PriPatel** [comment]
@hamzahc1 yes! - We still need a button for people to access All tables, but agreed, it needs to be clearer what the button actually does. 
<img width="332" alt="Screenshot 2022-04-26 at 08 58 10" src="https://user-images.githubusercontent.com/12776522/165251120-29d02847-6f95-47a3-8dc7-60213d9b712d.png">
