### ISSUE TITLE
dbt cloud support

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#98]
We should have support for dbt cloud.

There are two components to how Lightdash relies on a dbt project:

1. The `manifest.json` and `catalog.json` - these are available from dbt cloud and have all the info we need
2. The raw project files. We plan to use this when the user is locally developing to detect changes on disk, and to map Lightdash syntax errors back to source files.

We should be able to support dbt cloud for production use cases, but will be harder for us to provide the "development" type features.

Also we currently don't have a nice way in the UI to distinguish between using "files" as the backend vs "dbt cloud". we might also add "GitHub" here. These are basically different source locations, each with their own features that they support in the UI. Could spiral quickly. 

A quick hack would be to take dbt cloud credentials as an environment variable.

**Comment by TuringLovesDeathMetal** [comment]
I think that we should actually have a ticket before this that's "figure out what we need to build to actually support dbt cloud"

I've made the ticket here and added this to a new milestone :) https://github.com/lightdash/lightdash/issues/132
