### ISSUE TITLE
Enable to expire preview projects

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#9820]
### Description

It would be good to set expiration of preview projects to keep Lightdash projects neat.

### What problem does this solve?

The Lightdash preview projects are awesome. Meanwhile, those can remain if Lightdash developers don't delete. So, it would be good to set expiration of a preview project. 

1. We can add an option to set the expiration hours or the expiration date of a preview project.
2. We can configure the default expiration hours or the expiration date of preview projects at project level or organization level.

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of https://github.com/lightdash/lightdash/issues/3733 and https://github.com/lightdash/lightdash/issues/6839
