### ISSUE TITLE
Make 'save chart' button easily acessible

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#984]
**Describe the bug**
New users find it hard to find the save chart button.
To save a chart a user needs to click on the 'more' button and then on the 'save chart' button. 

**To Reproduce**
1. Go to an explore page with selected dimensions/metrics
2. Click on '...' button
3. Click on 'Save chart' button

**Expected behavior**
The save button should be next to the 'run query' button.

**Screenshots or Loom video**
n/a

**Additional context**
n/a

**Comment by PriPatel** [comment]
'Save chart' is basically 'Save a query' right? 
Just wondering - My fresh eyes expected to see this button in the 'Charts' card.

**Comment by ZeRego** [comment]
@PriPatel 
> 'Save chart' is basically 'Save a query' right?

**query** is everything necessary to display the results table. What fields are selected, filters and sorting. 
**chart** is everything necessary to display the chart. A query ( defined above ) and chart configuration. 

> Just wondering - My fresh eyes expected to see this button in the 'Charts' card.

This could work as well. But not sure if it would be more confusing if we later show the chart name at the top next to the other buttons. Off course I'm open to a complete redesign :)

**Comment by TuringLovesDeathMetal** [comment]
One user asked if we had the ability to create saved charts. They were looking here:

![image](https://user-images.githubusercontent.com/31848148/148981446-7928c09a-d3f8-4fbe-a6aa-563322c61f48.png)

**Comment by PriPatel** [comment]
I went down a bit of a rabbit hole with this one!!! A bigger overhaul needs to take place for this to work elegantly. Thoughts below:

- I agree that the `save chart` button just needs to be in the chart space.
- I think that `save chart` should be a primary action as it is a core step we want users to take.
- I feel like 'Save' & 'Share' play a part in two very different workflows so I feel like the two should be separate. (not sure what everyone else thinks about this)...
Maybe we can try and do something quick like in the sketch below for now just so users know that they can save a chart! (until we have time to make design changes!!) 

<img width="832" alt="Screenshot 2022-01-12 at 15 06 09" src="https://user-images.githubusercontent.com/12776522/149129839-0deed92a-c31e-4d70-9dfd-9ddefec58b62.png">

**Comment by TuringLovesDeathMetal** [comment]
ooh nice! ya, I like it :) 

What happens when it's been saved already and you get the `save` vs. `save as` option? Would this become a drop-down blue button?

I feel like another thing that's hidden here is the `save to dashboard` in that three-dot menu 👀 out of scope for this ticket, but might be worth considering in a slightly bigger design change if we decide we need one!

![image](https://user-images.githubusercontent.com/31848148/149184824-1e8749db-75d0-4b95-a61a-e5ecd235b695.png)

**Comment by PriPatel** [comment]
Yup !  For now it can work as the same dropdown. 
Your point about `add to dashboard` is noted for when we consider a bigger change. I think maybe the primary CTA will be different if a chart is already saved.

**Comment by ZeRego** [comment]
@PriPatel @TuringLovesDeathMetal 

We can have the save chart always present and the rest of the options like `add to dashboard` under the dropdown button. 

<a href="https://www.loom.com/share/0e05acdb562c4a24b3edb218d9ded224">
    <p>Lightdash - Save chart UX  - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/0e05acdb562c4a24b3edb218d9ded224-with-play.gif">
  </a>

**Comment by PriPatel** [comment]
@ZeRego  nice!!!!
Question about "Configure" + "Export as"  - Is it poss to remove the left-side icons ? Just so the only icons we see in this space are for the different chart types? 

Also, we would need to update some of the docs right? As 'saving charts' will now have outdated screenshots?
