### ISSUE TITLE
Add a non-unique slug for charts + dashboards

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#9853]
Each chart or dashboard should have a slug generated from it's location + name in lightdash:

always lower case, use hyphens instead of spaces

```
# for charts
charts/space_name/chart_name

# for dashboards
dashboards/space_name/dashboard_name
```

It doesn't need to be unique for now

**Comment by rephus** [comment]
Just to clarify, What happens if the name changes , do we update the slug ? 
I've seen this pattern before, and normally the slug doesn't change once it is created

**Comment by owlas** [comment]
- Index ✅ 
- Make them fixed? Yes this makes sense if we plan to use these in the urls. We can always switch them to be updated later

Finally, would it be possible to have the slug be unique but nullable?
