### ISSUE TITLE
Add upstream projects to project metadata

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#9854]
### Description

- Each project can have an upstream project id (on delete set null). 
- Preview projects automatically inherent their base project as the upstream project

**Comment by rephus** [comment]
We already have `copied_from_project_uuid`on projects that points to the `parent project` , this is set when we create previews, to copy the content from 
![image](https://github.com/lightdash/lightdash/assets/1983672/635c5a44-18e6-4dfc-a30e-69f9c1fd552b)

Should we reuse this field ? create a new one ? (renaming might be confusing) 

IS the goal of this so the user can select their own project in the UI ? 
Does this Issue include that UI ?

**Comment by owlas** [comment]
> `compied_from_project_uuid`

How do we use this field today?

> user can select their own project in the UI?

Yes!

> this issue include the UI? 

No!

**Comment by rephus** [comment]
> How do we use this field today? It's very likely we can re-use this

When you create a preview project from the CLI, we send the selected project in the CLI , this project uuid will be stored in db. THen  a task in scheduler will run the duplicate content from this copied uuid to the preview. 

The idea was to also use this `compied_from_project_uuid` to copy content from preview to prod, so very similar to the `promotion` we're discussing.
