### ISSUE TITLE
Promote charts to upstream projects

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#9855]
### Description

**Biz logic**

- Try and promote a chart
- Check if upstream project exists, if not throw an error
- Find space with matching slug, if there's many error. if there's none create the space with dev space name, if there's one match, select it
- Find chart with matching slug, if there's many error, if there's none, create chart in space with dev chart name, if there's one match, update it

Only developers on the current project can promote. Always check permissions to create / update content in the target project.

**API**
- Endpoint to promote charts, could live on the chart result
- Add upstream project uuid to project endpoint

**UI**
- If upstream project exists on current project
- If chart is in a clean state (i.e. save button is grey), then show a promote button (behind a feature flag)
- Also add to the context menu from chart lists
- On success link to created content

**Comment by rephus** [comment]
> Find chart with matching slug, if there's many error, if there's none, create chart in space with dev chart name, if there's one match, update it

WHat happens if a charts has been moved to another space in one of the projects ? will that cause a duplicate ?

**Comment by owlas** [comment]
Yes that will cause a duplicate! There are many other cases where things won't work unless we implement a sync to "pull from upstream". Right now there's no sync

**Comment by rephus** [comment]
Do you see an obvious place to put this UI for selecting a project in settings ? 

![image](https://github.com/lightdash/lightdash/assets/1983672/ecf8b97b-ab92-4bf9-b9bf-4d0d79809396)

Should we make a new `promoting` setting page ?

**Comment by 12ian34** [comment]
> give it a fun name like a data ops data something like whatever marketing name we use to sell this is what should go here
