### ISSUE TITLE
Add diff view for promoting charts

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#9858]
### Description

When promoting a chart would update an existing chart in production (rather than creating a new one for the first time), then the user should see a diff view explaining what's changed before confirming the promote.

**Comment by rephus** [comment]
we should use this type: 

```
// example
type PromotionChanges = {
   spaces: [{
      action: 'create' | 'update' | 'delete';
      data: Space 
   }],
   dashboards: [{
      action: 'create' | 'update' | 'delete';
      data: Dashboard 
   }],
   charts: [{
      action: 'create' | 'update' | 'delete';
      data: Chart
   }],
}
```

and run permission checks based on this structure on dashboards
