### ISSUE TITLE
Add option to export results from dashboard to .csv in an embedded dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9859]
### Description

Right now, there's an option to export a dashboard as an image or .csv in teh Lightdash app. We'd also like to add this option to embedded dashboards. 

### Acceptance criteria

- [ ] there is an option in the `interactivity` section for `users can export dashboard results` which is a toggle
- [ ] Toggling this option on means that the `export dashboard to .csv` option appears in the dashboard

- [ ] add an analytics event for embedded dashboards created with this option toggled on
- [ ] add analytics event for embedded dashboards exported to .csv 
- [ ] add docs for this

**Comment by jonhydetitanbay** [comment]
Popping in a +1 to this as it would mean we can use Lightdash to replace manually created static csv reports we have to produce today and give our clients control over the exact data they want to download at the time they need to do it.
