### ISSUE TITLE
Issue with Y dimension ordering on the bar and line charts

### ISSUE THREAD

**Issue by halyna-oros1** [lightdash/lightdash#9883]
Currently, it seems that the Y dimension ordering results on the line and bar chart in the random order. Results appear as downward slopping lines/bars. The Y axes seem to be ordered by date, and not in ascending numerical order to reflect the sequence and position. Also stacked charts appear to be as a separate columns, instead of being aggregated.

**Comment by IrakliJani** [comment]
hi @halyna-oros1 thank you for opening a ticket 🙌 
Could you provide a screenshot of the rendered bar chart and its configuration? That would help us engineers at Lightdash replicate and fix the bug more quickly.

**Comment by halyna-oros1** [comment]
hey @IrakliJani! 
Thanks for fast response. Please find the example of the line chart below. From the screenshot you can see that Y axes appear to be ordered in mixed order (do not reflect correctly relative position of the data point on the chart). Same is issue is with other chart types (bar and scatter charts). For example, on screenshot vertical bar chart appears as horizontal bar chart. 

<img width="1008" alt="Line_chart_example" src="https://github.com/lightdash/lightdash/assets/166492494/50a28510-eb9b-44f7-a975-f063a6b54520">
<img width="1017" alt="Vertical_bar_chart" src="https://github.com/lightdash/lightdash/assets/166492494/555cc9e1-2de7-4794-9329-e4399287e03a">

**Comment by IrakliJani** [comment]
Thanks, @halyna-oros1, we've identified the problem and are working on the fix. It's a high priority, so expect it to be resolved today in an hour or so.

**Comment by IrakliJani** [comment]
related https://github.com/lightdash/lightdash/issues/9885

**Comment by halyna-oros1** [comment]
@IrakliJani Thank you very much for taking issue fast into development 🙌

**Comment by magnew** [comment]
Fix is here: https://github.com/lightdash/lightdash/pull/9888

Closing this ticket. Thank you for reporting!
