### ISSUE TITLE
Support event based reports

### ISSUE THREAD

**Issue by davidgasquez** [lightdash/lightdash#990]
### Description: What is it?

It would be cool to have a feature that allows people to examine how users perform events in a series (funnel analysis).

### Problem: What problem does this solve?

Exploring clickstream events is trickier in a tool that is focused on "Entities". Having an "Event" point of view helps exploring things like conversions or activations. 

### (Optional) Why: How do we know this is a real problem and worth solving?

This feature can be replaced by some modeling in the dbt side but I feel exposing a feature like this will make much easier to explore and derive insights from data!

### Audience: Who are we building this for?

 

This will benefit data consumers that want to dig deeper into how entities (e.g: users) are interacting (e.g: converting) with the system (e.g: mobile app). 

### What: Roughly, what does this look like in the product?

My hunch is that an UI [similar to Mixpanel Funnels](https://help.mixpanel.com/hc/en-us/articles/360019982652-Funnels-Report-Basics#:~:text=Mixpanel's%20Funnels%20allows%20you%20to,within%20a%20particular%20time%20window.) might be very intuitive and friendly.

**Comment by owlas** [comment]
Thanks so much for opening this @davidgasquez !! We've had a few requests to support exploring event-based data.

Next step here is to move to a design phase. @TuringLovesDeathMetal we should have an explicit milestone on the roadmap for this, I think it's bigger than a single issue

**Comment by 12ian34** [comment]
Marked as not stale since related feedback has just come from a user:

> No funnel or flow visualisations (that I could see in docs or demo). We often work with growth and product teams, and showing a conversion funnel or a user flow can surface interesting insights and is something we would need in a BI tool.

I feel like we might be able to achieve this under a separate, smaller Issue though. Thoughts?

**Comment by 12ian34** [comment]
I created issue #2594 to cover just the ability to have a funnel chart type

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this as a duplicate of #2594
