### ISSUE TITLE
Formatting in model-level metric isn't applied correctly

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#9904]
### Description

A customer has reported an issue where percentage formatting doesn't show the same way in results table and a chart. Internal thread here: https://lightdash.slack.com/archives/C03MCQ08UKS/p1714071164630899

Our existing percentage fields seem to work. Is it a type issue?

### Steps to Reproduce the Bug or Issue

n/a

### Cloud or self-hosting

None

**Comment by TuringLovesDeathMetal** [comment]
I just ran into a similar issue (I think?) 

The y-axis labels seems to be showing up as numbers, not percentages 
<img width="1357" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/0a713346-06c2-4ac2-ac1a-b3b2622962a2">

https://lightdash-demo-thyme.onrender.com/share/9M-lkrnJfq1DoxgE7Yb3I

**Comment by magnew** [comment]
Closing as duplicate of #9779
