### ISSUE TITLE
I want to hide duplicate tables from business users when they appear in joined tables, but not when they're standalone.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#9908]
If I have table `Orders` and it appears as a join in the table `Support Requests`, I don't want my business users to see `Orders` in the sidebar by itself as it is not useful to them. They should go to `Support Requests` straight away and use it from there. 

- This would keep the sidebar cleaner and lead to a higher chance of the business user finding what they need. 
- Alternatively, being able to add more notes/details to tables while the user is browsing through them could help. (so the builder could add a note 'don't use this table, use `xxx` instead'. 
- This feels optional, so how does the user choose whether they want to 'turn' this setting on or not?

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel this feels like it's something that people can already do 👀 but maybe I've misunderstood the request...

e.g. I can have a table appear as a join, but not appear as a standalone table int eh sidebar. This is described in the docs here: https://lightdash-knowledge-base.help.usepylon.com/articles/3073401434-how-do-i-hide-specific-tables

I'm going to close this as not planned, but feel free to reopen it if it's actually not the same issue as described in the help article!
