### ISSUE TITLE
I want to be able to create a custom dimension using custom SQL

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9930]
Context: https://www.notion.so/lightdash/67d3fd912f764d9eaf0f8e741d76fa00?v=805962b15e6a49958b88d1ec7dce15c4&p=f91f3d0a9c054d5ca68c5307354f2679&pm=s

### Description

There are groups and bin custom dimension types which are "commonly used" custom dimensions (and the shortcuts to build them are helpful). But sometimes I want to create dimensions using totally custom SQL. 

Here's an example use case:

I want to look at time between creating an account and using a bunch of different features in our product (e.g. time to first run query, time to first saved chart, etc.) and the average time for these events, each month. To do this today, I'd need to add these as additional dimensions in my .yml file, then create custom metrics which calculate the average. But, I don't have access to the .yml files (because I'm not on the data engineering team). So, I want to be able to create these dimensions in Lightdash (e.g. `DATE_DIFF(${my_table.first_saved_chart_created}, ${my_table.account_created}, DAY)`). Once I've created these dimensions, I want to then use them to create custom metrics! (e.g. the average time between creating an account and creating a saved chart, for each month this year). So, it's not just enough to be able to create these custom dimensions - I then want to be able to treat them like any other dimension. 

### Acceptance criteria

- [ ] I can create a custom dimension based on custom SQL
- [ ] The custom dimension definition can reference other dimensions from my table and any joined tables
- [ ] I can use the custom dimension to pivot (i.e. as a `column`) in a table visualization
- [ ] Only users with developer access or above can use custom SQL custom dimensions
- [ ] When I create a custom dimension using custom SQL, I need to select the `type` of my custom dimension (this should be the same types as table calculations)
- [ ] The modal for creating a custom dimension should be really similar to the table calculation modal
- [ ] There are two possible entry points to this:
    1. there’s an `+ Add` beside the dimension header in the sidebar (I think we should also do this for the `metrics` section, but we can do that separately)
  
<img width="248" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/2db2eacd-d50f-4443-9143-1bc9668a4147">

2. When you click `custom dimension` from a dimension in the sidebar, it opens a modal and you can select from the `types` : `bin` or `custom SQL`

### Documentation

add docs for custom dimensions using custom SQL to these docs: https://docs.lightdash.com/guides/how-to-create-custom-fields/

### Analytics event

- add `num_custom_sql_custom_dimensions` as a parameter to the `query_executed` event

**Comment by ZeRego** [comment]
Moved some of the requirements to separate tickets:
[reference dimensions](https://github.com/lightdash/lightdash/issues/10022)
[see underlying data with custom SQL dimensions](https://github.com/lightdash/lightdash/issues/10023)

**Comment by Daniel-SalazarSoplapuco** [comment]
@ZeRego Just checking, this was not implemented, right? 
Instead this was moved to a new ticket no

**Comment by ZeRego** [comment]
@Daniel-SalazarSoplapuco is currently behind a feature flag while we work on other tickets from this milestone. 
If you want to beta test this you can reach out to us in slack ;)
