### ISSUE TITLE
I want to be able to use a custom dimension to create a custom metric

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9931]
### Description

I want to be able to create a custom metric using a custom dimension.

**Comment by rephus** [comment]
@TuringLovesDeathMetal could you elaborate a bit more ? is there a UI for this ? 

Is this so on `custom dimensions` menu I can add custom metrics like in regular dimensions ? 


![Image](https://github.com/lightdash/lightdash/assets/1983672/ee0a86eb-9690-4ea4-8ae2-cd86213fd73b)

![Image](https://github.com/lightdash/lightdash/assets/1983672/e1a68783-2bab-4610-8e6b-30d2e93a9717)

This only applies to custom sql dimensions, not bins, right ?
