### ISSUE TITLE
Retry scheduled deliveries 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#9947]
### Description

Scheduled deliveries should be retried 3 times before marking the job as failed. 

Tech note:
Graphile library handles retries for us, we need to configure the job on creation.
Do we need to update our job logs to show retries? does it handle retries?

### What problem does this solve?

There are a few scenarios where scheduled deliveries fail. eg: timeout running a query, failed to generate image
It would be nice if it would automatically retry.

**Comment by rephus** [comment]
Errors I've seen in logs that we should retry all the time

{"error": "Protocol error: Connection closed. Most likely the page has been closed."}
{"error": "Protocol error (Page.captureScreenshot): Target closed"}
{"error": "Protocol error (DOM.describeNode): Target closed"}

**Comment by rephus** [comment]
This should fix the issue for auto `suspended` snowflake  warehouses: see thread https://lightdash.slack.com/archives/C04FQQU4RL7/p1715174131270259?thread_ts=1714378539.181729&cid=C04FQQU4RL7
