### ISSUE TITLE
Doesn't render on mobile

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#996]
### Describe the bug

Lightdash is completely broken on mobile

### To Reproduce

Open lightdash url on mobile

### Expected behavior

I should see something

### Proposed solution

We should show a friendly UI that informs the user that Lightdash doesn't render on smaller screens.

**Comment by PriPatel** [comment]
![Screenshot 2021-12-17 at 10 14 21](https://user-images.githubusercontent.com/12776522/146528613-945c201d-efb1-46c2-9f84-d2d78f4d6d11.png)
Something like this where we can direct them to our some other content for now. This is incase they are genuinely out and about and can't access Lightdash. Send them to our roundup!
