### ISSUE TITLE
Make secret fields optional when editing project settings

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#998]
### Description: What is it?

When editing project settings the secrets fields should be optional. 

### Problem: What problem does this solve?

When editing project settings the secrets are mandatory, this is a bit annoying since these values aren't always memorable and is a pain to get them most of the time.

### Success: How will we know if we’ve solved this problem?

There are fewer errors when users try to submit the form without populating the secret fields.

### What: Roughly, what does this look like in the product?

Turn secret fields to optional when editing a project. In the backend, if the secret values weren't provided, we reuse the existing values.

**Comment by owlas** [comment]
@ZeRego related to #623 ?
