### ISSUE TITLE
if field is timestamp make time_interval default

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#999]
Currently for all timestamp fields you have to explicitly say if you want the default or modified time intervals.

If nothing is specified for a timestamp field for time_intervals it should default to time_interval: default

**Comment by owlas** [comment]
Thanks for opening this @djayatillake this makes complete sense and would really improve the developer experience!

**Comment by ZeRego** [comment]
@djayatillake 

 ### What are we trying to achieve ?

We want all dimensions of type 'date' and 'timestamp' to be broken down into intervals. 
We should also provide a way for users to turn off this behaviour. We could support `time_intervals: off`

### How/where we breakdown the timestamp ?

When we are converting a dimension from dbt model we check their type and if they have a time_intervals value. If so we set the default intervals.

https://github.com/lightdash/lightdash/blob/3c85875f73cfcb1f8f599609c5454447fed8ba73/packages/backend/src/dbt/translator.ts#L250

### What we need to change ?

- Edit the condition mentioned above to add the extra dimensions if the time_intervals value is different than 'raw'
- Edit documentation to mention the value 'raw'

https://github.com/lightdash/lightdash/blob/3c85875f73cfcb1f8f599609c5454447fed8ba73/docs/docs/references/dimensions.md?plain=1#L55

- Update 'translator' unit tests

**Comment by owlas** [comment]
@all-contributors add @djayatillake for ideas

**Comment by djayatillake** [comment]
I'm going to work on this
